### ISSUE TITLE
Button icons should be larger when there is no text label

### ISSUE THREAD

**Issue by djmattyg007** [TuSimple/naive-ui#100]
## What problem does the feature solve?

If a button only has an icon and no label, the icon should be larger by default. This is necessary because it's the only thing to click on.

Right now even if you've set the size of the button to `large`, the icon will only be a maximum of 20px in size. You can set `size="40"` (for example) on the `n-icon` element, but then the presentation goes all whacky because the icon slot container element is still set to have a size of 20px.

## What does the proposed API look like?

A new prop named something like `icon` would be a good idea.

## Some pictures that can demonstrate the feature.

Here you can see the icon buttons overlapping each other:

![image](https://user-images.githubusercontent.com/489338/121810010-76830b80-cca2-11eb-83e4-f554d3a05655.png)

**Comment by 07akioni** [comment]
After some time of thinking I find it's not elegant to expose an extra type of button or expose an `icon-size` prop since the size is related many theme variables.

If you just want to use a icon button. I think the following way will meet your demand.

```html
<n-button text style="font-size: 36px;">
  <n-icon>
    <cash-icon />
  </n-icon>
</n-button>
```

**Comment by 07akioni** [comment]
ref https://www.naiveui.com/en-US/os-theme/components/button#icon-button
