### ISSUE TITLE
Required validator always fails when using "script setup" feature

### ISSUE THREAD

**Issue by SocVi100** [TuSimple/naive-ui#1005]
### TuSimple/naive-ui version (版本)
2.16.7

### Vue version (Vue 版本)
3.2.6

### Browser and its version (浏览器及其版本)
Chome (latest)

### System and its version (系统及其版本)
Windows 10 Pro

### Node version (Node 版本)
14

### Reappearance link (重现链接)
https://codesandbox.io/s/hardcore-wilson-uxetn?file=/src/App.vue

### Reappearance steps (重现步骤)
Try to write on the required field. Required validation will fail always...

### Expected results (期望的结果)
Required validation not failing if there's a value on the input

### Actual results (实际的结果)
Required validation fails always...
It doesn't happen if you don't use "script setup" feature

### Remarks (补充说明)
Sorry for the provided codesandbox, I didn't manage to arrange the initial dependencies, but the example is very simple, it all happens on the App.vue file

**Comment by Talljack** [comment]
The value bound to n-input in your example is wrong. I tried it locally, but the error was not verified.
![image](https://user-images.githubusercontent.com/34439652/131252431-5ff726fa-c8bc-4dde-9204-362e96ef90e6.png)
![image](https://user-images.githubusercontent.com/34439652/131252445-b03582eb-500e-432b-a71a-5de486017848.png)
