### ISSUE TITLE
n-input-number 

### ISSUE THREAD

**Issue by nullF** [TuSimple/naive-ui#1007]
### TuSimple/naive-ui version (版本)
2.16.7

### Vue version (Vue 版本)
3.2.6

### Browser and its version (浏览器及其版本)
92.0.4515.159

### System and its version (系统及其版本)
win7

### Reappearance link (重现链接)
https://codesandbox.io/s/busy-drake-d9ysy?file=/src/Demo.vue

### Reappearance steps (重现步骤)
js 小数加减问题，0.6->0.7时出现问题

### Expected results (期望的结果)
step为小数时，可以正常运行

### Actual results (实际的结果)
step为小数时，计算失败

**Comment by cisolarix** [comment]
链接测试了一下，`0.6` 到 `0.7` 的计算没发现什么问题。此处的计算失败是啥样的呢？

**Comment by nullF** [comment]
大佬你好，我因为网速问题当时提交没说清楚 是从1开始减小，每次减小0.1，当0.8降到0.7时，数据出现异常，原因应该是js 小数位计算丢失精度问题------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月31日(星期二) 下午3:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TuSimple/naive-ui] n-input-number  (#1007)
