### ISSUE TITLE
How to use naive UI directly through script tags

### ISSUE THREAD

**Issue by zhangtianxiao** [TuSimple/naive-ui#1014]
### This function solves the problem (这个功能解决的问题)
use naive UI directly through script tags
### Expected API (期望的 API)
<script src="jscdn.com/naive-ui"/>

**Comment by 07akioni** [comment]
> ### This function solves the problem (这个功能解决的问题)
> use naive UI directly through script tags
> 
> ### Expected API (期望的 API)
> <script src="jscdn.com/naive-ui"/>

I don't plan to provide a UMD version of naive since I don't want people to use it directly in HTML.

Also, technically, naive uses symbols in vue package, so make it work, it need to bundle the entire vue inside the package.

If anyone is interested in create a UMD version bundle, PR is welcomed.

**Comment by 07akioni** [comment]
UMD is supported in 2.30.3
