### ISSUE TITLE
How to write jsx directly in the render function of the table, or use the syntax of the template to write the columns of the table?

### ISSUE THREAD

**Issue by zhangshichuan** [TuSimple/naive-ui#1015]
### This function solves the problem (这个功能解决的问题)
I can write jsx directly in the expanded row or action bar of the table instead of h() or support the use of template syntax
### Expected API (期望的 API)
none

**Comment by 07akioni** [comment]
See your toolchain documentation, it is not relevant with naive.

**Comment by jukanntenn** [comment]
Do you find a way to solve this? Appreciate very much if you can share what you find.

**Comment by zhangshichuan** [comment]
> FYI, using `script setup` with `lang="txs"` or `lang="jsx"` let us write TSX/JSX in render function with Vite toolchain (and avoiding usage of the `h()` function.

thx

**Comment by zhangshichuan** [comment]
> Do you find a way to solve this? Appreciate very much if you can share what you have found.

Sorry, I don't use vue in my project, I just ran the demo locally.
