### ISSUE TITLE
n-checkbox

### ISSUE THREAD

**Issue by nullF** [TuSimple/naive-ui#1023]
### This function solves the problem (这个功能解决的问题)
能否增加按钮样式的多选组合
### Expected API (期望的 API)
 类似于 \<el-checkbox-button\>

**Comment by Talljack** [comment]
是否可以描述清楚一点

**Comment by nullF** [comment]
> 是否可以描述清楚一点
抱歉 GitHub 没事别出来 类似于  < el-checkbox-button > < / el-checkbox-button> 这种组件

**Comment by 07akioni** [comment]
暂时没有这种打算

**Comment by 07akioni** [comment]
或许你可以试试 checkable 的 tag
