### ISSUE TITLE
nspace的size貌似没有生效

### ISSUE THREAD

**Issue by JokerLoLgrey** [TuSimple/naive-ui#1037]
### TuSimple/naive-ui version (版本)
2.16.7

### Vue version (Vue 版本)
3.2.6

### Browser and its version (浏览器及其版本)
Microsoft Edge（92.0.902.84）

### System and its version (系统及其版本)
window 11

### Node version (Node 版本)
14.17.5

### Reappearance link (重现链接)
https://github.com/JokerLoLgrey/vite-naive-test

### Reappearance steps (重现步骤)
无

### Expected results (期望的结果)
size生效

### Actual results (实际的结果)
size不生效

**Comment by Volankey** [comment]
能来一个codesandbox的例子么？
直接扔一个repo还得看有没有其他的影响，不方便debug

**Comment by Talljack** [comment]
![image](https://user-images.githubusercontent.com/34439652/131700408-2e8f6919-a00c-46ef-9d7d-cf56fc4ba764.png)
看起来间距是不一样的，应该是生效了的。

**Comment by JokerLoLgrey** [comment]
> 能来一个codesandbox的例子么？
> 直接扔一个repo还得看有没有其他的影响，不方便debug，还得找到你在哪里写的
> 
> https://codesandbox.io/s/goofy-almeida-j4wsu?file=/src/Demo.vue

抱歉，抱歉，我看了一下你的例子确实生效了，但是我这个没有生效，我要看看什么出了问题

**Comment by JokerLoLgrey** [comment]
> ![image](https://user-images.githubusercontent.com/34439652/131700408-2e8f6919-a00c-46ef-9d7d-cf56fc4ba764.png)
> 看起来间距是不一样的，应该是生效了的。
> 可能文档描述不是很清楚，后续会改一下文档

生效了，文档确定有点不清晰，对了还有Tooltip和Popover的props、slots和methods是完全一致还是有细微差别呢，麻烦了

**Comment by 07akioni** [comment]
> 了还有Tooltip和Popover的props、slots和methods是

默认值有细微差别，剩下总体是一致的

**Comment by JokerLoLgrey** [comment]
> > 了还有Tooltip和Popover的props、slots和methods是
> 
> 默认值有细微差别，剩下总体是一致的
好的，了解了，感谢
