### ISSUE TITLE
NSelect doesn't support value of Object type

### ISSUE THREAD

**Issue by KeroZhai** [TuSimple/naive-ui#1043]
### The problem this function solves (这个功能解决的问题)
Support binding value of Object type for NSelect
支持为 NSelect 绑定对象类型的值
### Expected API (期望的 API)
In my case, the initial value to bind with NSelect is an object(like: `"{ "id": 1, "name": "a" }"`, or an object array for multiple select) fetched from backend API, while the option values are just ids, therefore I have to manually convert/map value to id(s) to match option(s). However, with a single additional prop "`value-key`"(just like Element UI) to specify the actual value field in the object(like `value-key="id"`),  NSelect can automatically extract value from object to match option, problem solved, simply and elegantly.
在我的项目中，绑定到 NSelect 的值是一个从后端接口取回的对象或者对象数组（例如 `"{ "id": 1, "name": "a" }"`），但选项的值则仅仅是一个数值（例如 `id`），所以必须在绑定前把值转化为 `id` 或者 `id` 数组，如此才能和选项值匹配上。但是如果能够有一个“`value-key`”这样的 prop（就像 Element UI 一样），就可以指明对象中哪一个字段表示实际的值（例如：`value-key="id"`），NSelect 自动从对象中提取该值来和选项匹配，问题解决，简单而优雅。

**Comment by kungege** [comment]
same as [#977](https://github.com/TuSimple/naive-ui/issues/977)

**Comment by 07akioni** [comment]
之后 onUpdateValue 回调会传回 option

**Comment by KeroZhai** [comment]
> 之后 onUpdateValue 回调会传回 option

之前的描述确实不太准确，其实这个并不是对回调的需求，而是希望对绑定值以及选项`key`增加对象类型的支持（目前仅支持字符串和数值类型）。烦请考虑以下场景：

* NSelect 选项的内容是从后端接口返回的 JSON 数据，例如是：`[{"id": 1, "name": "DotA"}]`，首先前端需要手动将其转换为 NSelect 支持的选项格式，即：`[{ label: 'DotA', key: 1 }]`，同时由于`key`为数值，那么为 NSelect 绑定的值`favouriteGame`也必须为数值类型。
* 选择此选项，提交表单，传给后端的 JSON 数据为：`{"favouriteGame": 1}`。但之后修改时，后端返回的表单数据中此字段并不是简单的数值，而是`{"favouriteGame": {"id": 1, "name": "DotA"}}`，此时如果不对其转换而直接绑定到 NSelect，则无法和选项的`key`匹配。

当然也不是不能解决，例如可以要求后端仅返回数值，或者由前端手动将`id`的值提取出来给`favouriteGame`。只是针对这种场景，Element UI 支持选项的值为对象类型，并提供了`value-key`这样的 prop 指明绑定的对象和选项值中用来匹配的字段，例如`value-key="id"`，由于提交表单时，后端对`favouriteGame`字段同时支持`id`（`{"favouriteGame": 1}`）与完整对象（`{"favouriteGame": {"id": 1, "name": "DotA"}}}`）两种形式，所以有原生支持的话相对来说方便一点。

**Comment by 07akioni** [comment]
> > 之后 onUpdateValue 回调会传回 option
> 
> 之前的描述确实不太准确，其实这个并不是对回调的需求，而是希望对绑定值以及选项`key`增加对象类型的支持（目前仅支持字符串和数值类型）。烦请考虑以下场景：
> 
> * NSelect 选项的内容是从后端接口返回的 JSON 数据，例如是：`[{"id": 1, "name": "DotA"}]`，首先前端需要手动将其转换为 NSelect 支持的选项格式，即：`[{ label: 'DotA', key: 1 }]`，同时由于`key`为数值，那么为 NSelect 绑定的值`favouriteGame`也必须为数值类型。
> * 选择此选项，提交表单，传给后端的 JSON 数据为：`{"favouriteGame": 1}`。但之后修改时，后端返回的表单数据中此字段并不是简单的数值，而是`{"favouriteGame": {"id": 1, "name": "DotA"}}`，此时如果不对其转换而直接绑定到 NSelect，则无法和选项的`key`匹配。
> 
> 当然也不是不能解决，例如可以要求后端仅返回数值，或者由前端手动将`id`的值提取出来给`favouriteGame`。只是针对这种场景，Element UI 支持选项的值为对象类型，并提供了`value-key`这样的 prop 指明绑定的对象和选项值中用来匹配的字段，例如`value-key="id"`，由于提交表单时，后端对`favouriteGame`字段同时支持`id`（`{"favouriteGame": 1}`）与完整对象（`{"favouriteGame": {"id": 1, "name": "DotA"}}}`）两种形式，所以有原生支持的话相对来说方便一点。

会做

**Comment by amadeus711** [comment]
#1003

**Comment by NilsEvers** [comment]
Sorry, this thread is a bit hard to follow for someone who doesn't speak Chinese.
Why was this issue closed? The linked PR does not implement the OPs feature request, if I"m not mistaken.

**Comment by 07akioni** [comment]
> Sorry, this thread is a bit hard to follow for someone who doesn't speak Chinese. Why was this issue closed? The linked PR does not implement the OPs feature request, if I"m not mistaken.

Let me explain. The primary reason we won't do that is the it's diffcult to determine if the object values are the same. For example:

```
<n-select :value="{ foo: 'bar' }" />
```

Each time the component is rendered, the `n-select` must be rerendered since the ref of the value prop is changed. That would cause a lot of edge cases. However, it's convient for user got the selected option, so we created PR to emit option in change callback, so that user can get the option each time the value changes.

A secondary concern it type interface. Add object to it would cause the `onUpdateValue`'s type more messy since vue doesn't support generic type.
