### ISSUE TITLE
Can Collapse component add suffix slot ? 

### ISSUE THREAD

**Issue by tarepanda1024** [TuSimple/naive-ui#1046]
### This function solves the problem (这个功能解决的问题)
I want to use Collapse component to manage collections , need some menus in the  suffix. Just like https://www.getoutline.com/ .I use tree in the conent of Collapse，not in the root node，because i can't custom the tree collapse icon.
### Expected API (期望的 API)
like this
```
<template #suffix>
      <n-icon>
        <cash-icon />
      </n-icon>
</template>
```

**Comment by 07akioni** [comment]
Okay
