### ISSUE TITLE
Table support slot for customColumn

### ISSUE THREAD

**Issue by nabaonan** [TuSimple/naive-ui#106]
## What problem does the feature solve?
we can custom column in template with slot 
## What does the proposed API look like?
```vue

//  template:

 <n-data-table  :columns="columns" :data="data" >
        <template #slotName="{value,row,columnProp}" >
             <span >{{row.title}} {{value}} Custom things</span>
        </template>
</n-data-table>


........
// script:

setup() {

      return {
          data:[],
          columns:[{
                key:'name',
                title: 'name',
                slot:'slotName'
           }]
      }
}

```

**Comment by 07akioni** [comment]
The row display is very subtle and related to many props. So no custom row api will be provided.

Please consider `colSpan` + render function.

**Comment by 07akioni** [comment]
Dynamic slot name is not a good pattern since it's very unfriendly to typescript. Personally I don't think this is a good API.

**Comment by 07akioni** [comment]
> 那为啥官方会报出警告，并建议使用slot方式来提升性能呢？ ![image](https://user-images.githubusercontent.com/20694902/190121916-f4beab9f-40bd-451f-a9fd-869bdd342530.png)
> 
> 而且使用h函数渲染会导致class等属性无效等问题 单组件自定义还行，多个组件自定义时就更不方便，而且难度不低哦 比如要实现这样de的效果： ![image](https://user-images.githubusercontent.com/20694902/190122686-08bc4e2e-cea0-4ef7-950b-d4804eb624b8.png) 貌似只能这么写吧：
> 
> ```js
> {
>   title: '操作',
>   key: 'operation',
>   render(row) {
>     return [
>       h(NButton, {
>         text: true,
>         onClick: () => {
>         },
>       }, '编辑'),
>       h(NButton, {
>         text: true,
>         style: {
>           marginLeft: '12px',
>         },
>         onClick: () => {
>         },
>       }, '删除'),
>       h(NButton, {
>         text: true,
>         style: {
>           marginLeft: '12px',
>         },
>         onClick: () => {
>         },
>       }, '重置密码'),
>     ]
>   },
> },
> ```

可以定义一个组件，包含着三个按钮然后暴露一些属性出来，那样渲染函数写起来会简单一些

**Comment by arnoson** [comment]
Since Vue 3.3 now supports [typed Slots with `defineSlots`](https://blog.vuejs.org/posts/vue-3-3#typed-slots-with-defineslots) it would be great If you could reconsider this decision. For me, render functions feel were un-vue like. I know there a basic feature of vue, but it feels much more natural, to keep all template related stuff inside `<template>`. A lot of other vue component libraries support this (primevue, vant, ...). Overall I just like this library better, so having the choice between render functions and slots would make it perfect for me :)

**Comment by stylefieber** [comment]
If you want to use other components in the cell template or / and use template directives, it would be much easier to use with having slots available.

**Comment by fudiwei** [comment]
I created a project [@skit/x.naive-ui](https://github.com/fudiwei/x.naive-ui) based on Naive-UI, enables to use DataTable in template style. Welcome to improve it.

For the scenario proposed by OP, it can be written as:

```vue
<x-n-data-table :columns="columns" :data="data">
  <template #renderCell="{ column, rowData, value }">
    <span>{{ column.title }} {{ value }} Custom things</span>
  </template>
</x-n-data-table>
```
