### ISSUE TITLE
n-layout-content组件在使用naive-ui风格滚动条时不显示滚动条

### ISSUE THREAD

**Issue by slpwlkr** [TuSimple/naive-ui#1060]
### TuSimple/naive-ui version (版本)
2.16.7

### Vue version (Vue 版本)
3.2.7

### Browser and its version (浏览器及其版本)
Chrome 92.0.4515.159

### System and its version (系统及其版本)
Windows 10

### Reappearance link (重现链接)
https://codesandbox.io/s/little-cloud-iuciz?file=/src/Demo.vue

### Reappearance steps (重现步骤)
（具体参考code sandbox内代码）
1.  在n-layout-content内放一个长款溢出的canvas元素
2. 设置canvas元素的样式：position设为absolute，坐标均为0，margin为auto
3. 设置父级n-layout的属性：position为absolute
4. 设置n-layout-content的属性：native-scrollbar为false，样式：overflow为auto

### Expected results (期望的结果)
能显示并使用naive-ui风格的滚动轴

### Actual results (实际的结果)
不能显示并使用naive-ui风格的滚动轴

### Remarks (补充说明)
可以使用原生的滚动轴；
把canvas元素的position: absolute去掉，可以使用naive-ui风格的滚动轴（设置为absolute是我需要让canvas在父元素内水平垂直居中显示

**Comment by 07akioni** [comment]
自定义的滚动条依赖于高度的测量，不可能做到浏览器那样的溢出检测。想实现同样的效果请使用其他能真实占据高度的 css 来做 workaround。
