### ISSUE TITLE
can't see haver shadow in darkmode

### ISSUE THREAD

**Issue by LAWTED** [TuSimple/naive-ui#1070]
### TuSimple/naive-ui version (版本)
2.16.7

### Vue version (Vue 版本)
3.2.8

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
Windows

### Reappearance link (重现链接)
https://codesandbox.io/api/v1/sandboxes/define

### Reappearance steps (重现步骤)
when the background is #000
Can't see haver shadow! Maybe the shadow need to be bright insted of the grey one in light mode

### Expected results (期望的结果)
see the haver shadow in darkmode

### Actual results (实际的结果)
can't see haver shadow because of the color is still darkgrey but not light grey

**Comment by Volankey** [comment]
The reappearance link can not opened.

**Comment by 07akioni** [comment]
Update the reproduction link and I'll reopen the issue.

**Comment by LAWTED** [comment]
> Update the reproduction link and I'll reopen the issue.

update the link,please check ,click the button to the darkmode

**Comment by 07akioni** [comment]
> > Update the reproduction link and I'll reopen the issue.
> 
> update the link,please check ,click the button to the darkmode

It's too dark to make the shadow visible.

**Comment by 07akioni** [comment]
You can apply some extra CSS in dark theme. It's impossible to make every cases work well.

**Comment by LAWTED** [comment]
> You can apply some extra CSS in dark theme. It's impossible to make every cases work well.

maybe box-shawdow need to be rgba(255,255,255,0.06) will display better in darkmode instead of the dark 

> In light mode, we use shadows to express elevation. The higher surface gets, the wider a shadow it casts. The same approach wouldn’t work in a dark theme — it’s hard to see a shadow against a dark background. It’s better to illuminate the surface of each level. The higher a surface’s elevation, the lighter that surface becomes.

from: https://uxplanet.org/8-tips-for-dark-theme-design-8dfc2f

**Comment by 07akioni** [comment]
> > You can apply some extra CSS in dark theme. It's impossible to make every cases work well.
> 
> maybe box-shawdow need to be rgba(255,255,255,0.06) will display better in darkmode instead of the dark
> 
> > In light mode, we use shadows to express elevation. The higher surface gets, the wider a shadow it casts. The same approach wouldn’t work in a dark theme — it’s hard to see a shadow against a dark background. It’s better to illuminate the surface of each level. The higher a surface’s elevation, the lighter that surface becomes.
> 
> from: https://uxplanet.org/8-tips-for-dark-theme-design-8dfc2f

I know illuminate the surface is a way to show elevation. However I haven't find any examples of transition from a elevation level to another elevation level in dark mode.

**Comment by LAWTED** [comment]
> a elevation level

thx for your explain, i will try a lighter background to make the shadow visible
