### ISSUE TITLE
DataTable增加自动监听父元素的变化去重新计算表格

### ISSUE THREAD

**Issue by qqfei1858** [TuSimple/naive-ui#1071]
### This function solves the problem (这个功能解决的问题)
业务上经常有表格去撑满整个页面,表头固定,设置height:auto|100%,table body可以进行上下滑动,如果固定height,那么页面resize的时候,会出现上下空白或者溢出body导致表头不固定
### Expected API (期望的 API)
auto-resize:  false | true

**Comment by Volankey** [comment]
来个复现，看看你是怎么用的

**Comment by qqfei1858** [comment]
@Volankey https://xuliangzhan_admin.gitee.io/vxe-table/#/table/base/autoHeight vxe-table的方式

**Comment by 07akioni** [comment]
props.flexHeight
