### ISSUE TITLE
Add dates to changelog

### ISSUE THREAD

**Issue by djmattyg007** [TuSimple/naive-ui#108]
It would be great if you could add dates to the changelog for new entries going forward. This would allow people to more easily see when the most recent releases occurred. It's okay to leave old entries as-is, but it would be really appreciated if new entries could be dated :pray: 

You might also want to consider creating a git tag for each release too.

**Comment by 07akioni** [comment]
I'll follow your instruction.

**Comment by 07akioni** [comment]
e9a422792aa7f0e692d6dbd730134537796a61d2

**Comment by djmattyg007** [comment]
You don't need to apologise :) You've responded so promptly to all my issues, it's been amazing!
