### ISSUE TITLE
Year and Month dropdown in calendar for easy navigation to specific month and year

### ISSUE THREAD

**Issue by Nikhilchandra-Rathod** [TuSimple/naive-ui#111]
**Example:**

![datepicker](https://user-images.githubusercontent.com/20199364/121846144-289eef80-cd04-11eb-9cff-e7547dd01795.png)

**Comment by Nikhilchandra-Rathod** [comment]
Hey, any updated on this feature ? I need it in my application.

**Comment by 07akioni** [comment]
> Hey, any updated on this feature ? I need it in my application.

We are considering about user interaction & user interface of the feature.

**Comment by Nikhilchandra-Rathod** [comment]
Do you have plan to implement this feature within a month or so? Or any timeline ?

**Comment by DannyFeliz** [comment]
I would love to have this too.

**Comment by 07akioni** [comment]
> Do you have plan to implement this feature within a month or so? Or any timeline ?

We have no explict plan, currently I prefer ant design's looking.

![image](https://user-images.githubusercontent.com/18677354/124484076-9effb080-dddd-11eb-8da9-01b3419bb94f.png)

How do think of it.

**Comment by Nikhilchandra-Rathod** [comment]
Yes, I checked it and it’s nice looking

**Comment by 07akioni** [comment]
> Yes, I checked it and it’s nice looking

@Fnzero I think we can make the feature. The detail implemention will differs from antd.

We can create a new panel with two column: year & month, like this

```
| Year | Month |
| - | - |
| 2000 | Jan |
| 2000 | Jan |
| 2000 | Jan |
| 2000 | Jan |
```

**Comment by 07akioni** [comment]
> Yes, I checked it and it’s nice looking

@Fnzero I think we can make the feature. The detail implemention will differs from antd.

We can create a new panel with two scrollable column: year (1900 ~ 2100) & month, like this

```
| Year | Month |
| - | - |
| 2000 | Jan |
| 2001 | Feb |
| 2002 | Mar |
| 2003 | Apr |
| 2004 | May |
| ... | ... |
```

**Comment by DannyFeliz** [comment]
> > Do you have plan to implement this feature within a month or so? Or any timeline ?
> 
> We have no explict plan, currently I prefer ant design's looking. How do think of it.
> 
> ![image](https://user-images.githubusercontent.com/18677354/124484076-9effb080-dddd-11eb-8da9-01b3419bb94f.png)

This design is perfect

**Comment by viztor** [comment]
> > Yes, I checked it and it’s nice looking
> 
> @Fnzero I think we can make the feature. The detail implemention will differs from antd.
> 
> We can create a new panel with two scrollable column: year (1900 ~ 2100) & month, like this
> 
> ```
> | Year | Month |
> | - | - |
> | 2000 | Jan |
> | 2001 | Feb |
> | 2002 | Mar |
> | 2003 | Apr |
> | 2004 | May |
> | ... | ... |
> ```
> 
> After we click at month or year of the panel, the panel content changes to the year month select.

We should also build stand-alone year/month selector along with this.

**Comment by Nikhilchandra-Rathod** [comment]
@07akioni You can also check UI for this calendar.
https://vcalendar.io/

**Comment by 07akioni** [comment]
> @07akioni You can also check UI for this calendar.
> https://vcalendar.io/

Ok, we will take into consideration.

**Comment by Nikhilchandra-Rathod** [comment]
Hello,
Any update on this issue ?

**Comment by 07akioni** [comment]
> Hello,
> Any update on this issue ?

I let it be high priority in tusimple's team. They will implement it if they have spare time.

However it won't be fast (in 1 month).

**Comment by thamibn** [comment]
Hi here is a suggestion on how the datepicker can be designed, and you can pick as many features around dates like

from - to
only select a week
etc.

can't wait for this to be implemented i want to start a new project and one of its requires include dates selection form and to.

**Comment by thamibn** [comment]
perfect it is coming alright.

hope your working on the year and month shotcut select cause now it is a pain selecting past years like 1995 etc.
you need to use the arrows until to that year.

**Comment by Nikhilchandra-Rathod** [comment]
Hello,

Any updates on it ?

**Comment by 07akioni** [comment]
> Hello,
> 
> Any updates on it ?

I expect it to be done in Jan.

**Comment by 07akioni** [comment]
@Talljack Put it at the first priority on January.

**Comment by 07akioni** [comment]
> Hello,
> 
> Any updates on it ?

Done, closed in 2.24.2

**Comment by rhengles** [comment]
Very nice addition, congratulations to the team as always!

I would like to just point out two very minor details I noticed:

1. On the docs site, the month and year inside of the date picker have no space between them: `Jun2007`

2. This feature is not discoverable if you don't know the widget yet as a user.
You have to click on the month/year label but there is nothing indicating that it is clickable.
Having an effect on hover may help, but I think it's necessary some indication even when the mouse is out.
For example, the month/year could be styled like a NSelect.

**Comment by 07akioni** [comment]
> Very nice addition, congratulations to the team as always!
> 
> I would like to just point out two very minor details I noticed:
> 
> 1. On the docs site, the month and year inside of the date picker have no space between them: `Jun2007`
> 2. This feature is not discoverable if you don't know the widget yet as a user.
>    You have to click on the month/year label but there is nothing indicating that it is clickable.
>    Having an effect on hover may help, but I think it's necessary some indication even when the mouse is out.
>    For example, the month/year could be styled like a NSelect.

Fixed in new version
