### ISSUE TITLE
n-data-table with two props scroll-x = "max-content" and :max-height="400",the table width will be a huge value

### ISSUE THREAD

**Issue by felismargarita** [TuSimple/naive-ui#1114]
### TuSimple/naive-ui version (版本)
2.18.0

### Vue version (Vue 版本)
3.2.9

### Browser and its version (浏览器及其版本)
any

### System and its version (系统及其版本)
any

### Reappearance link (重现链接)
https://codesandbox.io/s/data-table-scroll-x-and-maxheight-nhm61?file=/package.json

### Reappearance steps (重现步骤)
please refer the sandbox

### Expected results (期望的结果)
make the width to a normal value

### Actual results (实际的结果)
the table width is set to a huge value

**Comment by kungege** [comment]
![image](https://user-images.githubusercontent.com/16132584/132278524-c0089b7e-11e1-4753-9643-0d7ed6596cfe.png)
`max-content` is not defined

**Comment by Volankey** [comment]
![image](https://user-images.githubusercontent.com/23287363/132278766-e2f79a82-70c3-4dcd-ac13-6d2d8b09d41c.png)
`scroll-x` is set `min-width`

**Comment by felismargarita** [comment]
> ![image](https://user-images.githubusercontent.com/16132584/132278524-c0089b7e-11e1-4753-9643-0d7ed6596cfe.png)
> `scroll-x` has Incorrect value
if I only set scroll-x  with max-content,the table width will be a suitable value will not make the table width with a huge value

**Comment by kungege** [comment]
> > ![image](https://user-images.githubusercontent.com/16132584/132278524-c0089b7e-11e1-4753-9643-0d7ed6596cfe.png)
> > `scroll-x` has Incorrect value
> > if I only set scroll-x  with max-content,the table width will be a suitable value will not make the table width with a huge value

sorry,my option is wrong

**Comment by 07akioni** [comment]
When `max-height` is set, body and head DOM is separated. So `max-content` will never sync width of head and body, since they have different content.

When it comes to 1000000px, I think this may be fixed by applying width to actual table dom. I'm not sure (whether it would break things).

```
this would cause 1000000px
<div style="width: max-content">
  <div style="width: 100%;" />
</div>
```

However, it makes no sense to set width as `max-content` on a header-fixed table.
