### ISSUE TITLE
希望能够增加tabs的样式

### ISSUE THREAD

**Issue by JokerLoLgrey** [TuSimple/naive-ui#1133]
### This function solves the problem (这个功能解决的问题)
能有更多选择
### Expected API (期望的 API)
无

希望能有一个IOS的这种tabs样式
![image](https://user-images.githubusercontent.com/33446705/132440070-e22d11c0-e114-46cd-9076-8321a318d438.png)

**Comment by amadeus711** [comment]
same as #809

**Comment by 07akioni** [comment]
> same as #809

Not the same, just relevant.
