### ISSUE TITLE
timeline组件 timelineitem 无法同时使用多个插槽

### ISSUE THREAD

**Issue by kexirong** [TuSimple/naive-ui#1137]
### TuSimple/naive-ui version (版本)
2.18.1

### Vue version (Vue 版本)
3.2.10

### Browser and its version (浏览器及其版本)
lastest

### System and its version (系统及其版本)
lastest

### Node version (Node 版本)
lastest

### Reappearance link (重现链接)
https://codesandbox.io/s/funny-haze-m0oji

### Reappearance steps (重现步骤)
 修改 
```
<n-timeline-item color="grey" content="啊" #icon>
      <n-icon>
        <cash-icon />
      </n-icon>
    </n-timeline-item>
```
 为 
```
<n-timeline-item color="grey" content="啊" >
      <n-icon #icon>
        <cash-icon />
      </n-icon>
    </n-timeline-item>
```

### Expected results (期望的结果)
可以正常工作

### Actual results (实际的结果)
无法正常工作

### Remarks (补充说明)
或许是vue3 的我未掌握的技能而非bug。

**Comment by LYErin** [comment]
<template #icon>
        <n-icon>
          <cash-icon />
        </n-icon>
</template>
slot写在template上，可以满足多种插槽
https://codesandbox.io/s/bold-cloud-0f08h?file=/src/Demo.vue:96-189
