### ISSUE TITLE
add a way to hide n-upload-dragger without n-upload stop working

### ISSUE THREAD

**Issue by wc-matteo** [TuSimple/naive-ui#1141]
### This function solves the problem (这个功能解决的问题)
show other fields before upload without having n-upload-dragger wasting space after it's done its job
### Expected API (期望的 API)
either a prop to n-upload or make n-upload-dragger not be required (so one can use v-if on it)

**Comment by wc-matteo** [comment]
for now I'm using v-show on n-upload-dragger and it's working fine, btw

**Comment by 07akioni** [comment]
Will do

**Comment by 07akioni** [comment]
It's available now.

https://www.naiveui.com/en-US/os-theme/components/upload#abstract.vue
