### ISSUE TITLE
DatePicker是否可以接收String类型的值？

### ISSUE THREAD

**Issue by Eyanger** [TuSimple/naive-ui#1144]
### This function solves the problem (这个功能解决的问题)
后端api返回的日期值为String类型，转换成number比较麻烦。
### Expected API (期望的 API)
接收String类型的值

**Comment by AXiLiYa** [comment]
建议你用[dayjs](https://dayjs.gitee.io/zh-CN/)处理或者叫你们后端传timestamp，这个不是普遍需求

**Comment by 07akioni** [comment]
> ### This function solves the problem (这个功能解决的问题)
> 后端api返回的日期值为String类型，转换成number比较麻烦。
> 
> ### Expected API (期望的 API)
> 接收String类型的值

自己转吧，不难，如果你想打包体积小点就用 date-fns，不和 naive 内部重复
