### ISSUE TITLE
希望能在轮播图功能扩展

### ISSUE THREAD

**Issue by OrangePeel-2019** [TuSimple/naive-ui#1159]
### This function solves the problem (这个功能解决的问题)
切换的时候不再那么的生硬，更生动。
### Expected API (期望的 API)
①轮播图增加一些切换的过渡效果，比如：渐变；
②轮播图增加用户可以调节切换的速度；
③切换的时候可以用鼠标拖动切换；

**Comment by JokerLoLgrey** [comment]
同样希望增加更多的样式，可以参考https://element-plus.gitee.io/#/zh-CN/component/carousel卡片化
