### ISSUE TITLE
有没有计划给表格的单元格增加左右拖动的功能？

### ISSUE THREAD

**Issue by jinmarcus** [TuSimple/naive-ui#1162]
### This function solves the problem (这个功能解决的问题)
这样可以在数据显示比较多的情况下，使用拖动来展示更多的内容
### Expected API (期望的 API)
这样可以在数据显示比较多的情况下，使用拖动来展示更多的内容

类似的效果如下：
![image](https://user-images.githubusercontent.com/17996289/133024040-dc9359b6-d2e2-4a3b-8020-5e5feb6169c2.png)

**Comment by Volankey** [comment]
Same as #1072
