### ISSUE TITLE
用代码方式，外部改变NTabs，tabPane 不更新内容

### ISSUE THREAD

**Issue by xydz** [TuSimple/naive-ui#1165]
### TuSimple/naive-ui version (版本)
2.18.1

### Vue version (Vue 版本)
3.2.11

### Browser and its version (浏览器及其版本)
93.0.4577.63

### System and its version (系统及其版本)
chrome

### Reappearance link (重现链接)
https://codesandbox.io/s/naive-ui-tabs-error-p9qyn

### Reappearance steps (重现步骤)
<template>
  <n-space>
    <n-button @click="tabChange('alarm')">Default</n-button>
    <n-button @click="tabChange('error')" type="primary">Primary</n-button>
    <n-button @click="tabChange('dev')" type="info">Info</n-button>
  </n-space>
  <n-tabs
    type="line"
    size="large"
    :tabs-padding="20"
    pane-style="padding: 20px;"
    :default-value="childeSelected"
  >
    <n-tab-pane
      v-for="item in childrenTabs"
      :key="item.title"
      :name="item.key"
      :tab="item.title"
      display-directive="if"
    >
      <div>{{ item.title }}</div>
    </n-tab-pane>
  </n-tabs>
</template>

<script>
import { defineComponent, ref, computed } from "vue";

export default defineComponent({
  setup() {
    const tabItems = [
      {
        key: "alarm",
        text: "报警数量",
      },
      {
        key: "error",
        text: "错误数量",
      },
      {
        key: "dev",
        text: "技术栈",
      },
    ];

    const childTabItemsConfig = {
      alarm: [{ key: "groupkey", title: "团队占比" }],
      error: [
        { key: "groupkey", title: "团队占比" },
        { key: "httpcode", title: "错误码占比" },
      ],
      dev: [
        { key: "framework", title: "框架分布" },
        { key: "language", title: "语言" },
      ],
    };

    const selected = ref("alarm");

    const childrenTabs = computed(() => childTabItemsConfig[selected.value]);
    const childeSelected = ref(childTabItemsConfig[selected.value][0].key);
    // const childeSelected = computed(() => childrenTabs.value[0].key);

    function tabChange(value) {
      selected.value = value;
      // childrenTabs.value.splice(0, childrenTabs.value.length);
      // childrenTabs.value.push(...childTabItemsConfig[value]);
      childeSelected.value = childTabItemsConfig[value][0].key;
    }
    return {
      tabItems,
      tabChange,
      childrenTabs,
      childeSelected,
    };
  },
});
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

### Expected results (期望的结果)
没有触发pan的更新，动态渲染没有watch props

### Actual results (实际的结果)
动态改变pane个数，重新for更新， :name有变化，内容pane没有更新。

**Comment by xydz** [comment]
https://codesandbox.io/s/naive-ui-tabs-error-p9qyn

**Comment by Volankey** [comment]
See https://codesandbox.io/s/quizzical-dust-sdvws?file=/src/App.vue.
