### ISSUE TITLE
如何分别控制light theme和dark theme下自定义的颜色值？

### ISSUE THREAD

**Issue by mollerzhu** [TuSimple/naive-ui#1167]
我想实现界面可以切换主题，但是自定义的颜色值，如何针对light和dark进行不同的颜色？

**Comment by 07akioni** [comment]
> 我想实现界面可以切换主题，但是自定义的颜色值，如何针对light和dark进行不同的颜色？

你既然能控制主题的切换，你就能分别针对 dark 和 light 写两份对象
