### ISSUE TITLE
我想实现界面可以切换主题，但是自定义的颜色值，如何针对light和dark进行不同的颜色？

### ISSUE THREAD

**Issue by mollerzhu** [TuSimple/naive-ui#1171]
### This function solves the problem (这个功能解决的问题)
实现主题切换的同时，还可以自定义不同背景色下的元素颜色
### Expected API (期望的 API)
我想实现界面可以切换主题，但是自定义的颜色值，如何针对light和dark进行不同的颜色？

**Comment by 07akioni** [comment]
你既然能控制主题的切换，就可以为不同的主题安排不同的主题对象
