### ISSUE TITLE
优化textarea的滚动条

### ISSUE THREAD

**Issue by labradorGitHubCanine** [TuSimple/naive-ui#1172]
### This function solves the problem (这个功能解决的问题)
textarea在内容过长时会显示原生的滚动条，希望可以改成与n-layout内置滚动条相同的样式
### Expected API (期望的 API)
<n-input type="textarea"></n-input>

**Comment by 07akioni** [comment]
从原理上做不到。

**Comment by fcloud89** [comment]
> 理论上有可能，优先级并不高

我也有这需求，在看这个问题，n-scrollbar和textarea组合好像不太好弄，我在想要不要在textarea内部再移植部分n-scrollbar的实现？

**Comment by 07akioni** [comment]
> ，n-scrollbar要包裹在textarea内的#shadow-root的内容上，才

肯定是不好弄，实现原理要有区别，之前不弄不是没有原因的，监听不了内容的 resize，只能坚挺内容变化
