### ISSUE TITLE
useThemeVars()获取的变量没有包含n-config-provider组件中覆盖的变量

### ISSUE THREAD

**Issue by jinmarcus** [TuSimple/naive-ui#1176]
### TuSimple/naive-ui version (版本)
2.18.2

### Vue version (Vue 版本)
3.1.1

### Browser and its version (浏览器及其版本)
chrome 91.0.4472.124

### System and its version (系统及其版本)
win10

### Node version (Node 版本)
14.15.4

### Reappearance link (重现链接)
https://codesandbox.io/s/purple-fire-fukqr?file=/src/main.js

### Reappearance steps (重现步骤)
useThemeVars() 只能获取到系统初始化的变量

如果在n-config-provider组件中设置 theme-overrides 覆盖的变量，则获取不到

### Expected results (期望的结果)
useThemeVars() 只能获取到系统初始化的变量

如果在n-config-provider组件中设置 theme-overrides 覆盖的变量，则获取不到

### Actual results (实际的结果)
useThemeVars() 只能获取到系统初始化的变量

如果在n-config-provider组件中设置 theme-overrides 覆盖的变量，则获取不到

**Comment by 07akioni** [comment]
@Talljack
