### ISSUE TITLE
日期控件希望支持自定义输出格式

### ISSUE THREAD

**Issue by jerrytang67** [TuSimple/naive-ui#1182]
### This function solves the problem (这个功能解决的问题)
日期控件希望支持自定义输出格式,而非只有时间戳
### Expected API (期望的 API)
像element还有个value-format的prop

**Comment by 07akioni** [comment]
@Volankey onUpdateValue 第二个参数输出一下格式化好的时间戳咋样？

**Comment by wenhongjie** [comment]
> @Volankey onUpdateValue 第二个参数输出一下格式化好的时间戳咋样？

该功能实现了吗?

**Comment by 07akioni** [comment]
> > @Volankey onUpdateValue 第二个参数输出一下格式化好的时间戳咋样？
> 
> 该功能实现了吗?

没有
