### ISSUE TITLE
Date Picker 日期范围选择，当选择第一个日期后给一个回调事件？

### ISSUE THREAD

**Issue by Adangs** [TuSimple/naive-ui#1186]
### This function solves the problem (这个功能解决的问题)
通过选择的第一个日期，动态控制禁用日期范围
### Expected API (期望的 API)
像 element 的 change 事件

**Comment by 07akioni** [comment]
> ### This function solves the problem (这个功能解决的问题)
> 通过选择的第一个日期，动态控制禁用日期范围
> 
> ### Expected API (期望的 API)
> 像 element 的 change 事件

通过目前提供的禁用 API 已经可以动态禁用时间范围了，DEMO 里面有

**Comment by Adangs** [comment]
> > ### This function solves the problem (这个功能解决的问题)
> > 通过选择的第一个日期，动态控制禁用日期范围
> > ### Expected API (期望的 API)
> > 像 element 的 change 事件
> 
> 通过目前提供的禁用 API 已经可以动态禁用时间范围了，DEMO 里面有

功能是实现了，但碰到另外一个问题；我不确定是我的写法有问题，还是组件的问题；

代码片段
![image](https://user-images.githubusercontent.com/5443355/142987260-6b3c3a11-3f66-490f-87eb-10df7a382ff2.png)
![image](https://user-images.githubusercontent.com/5443355/142987093-e08c38b4-20bc-4aef-90fb-95707dbe43a4.png)
![image](https://user-images.githubusercontent.com/5443355/142987112-4a066a33-46d4-463b-82d5-6e77251b5e41.png)

开发时的警告
![image](https://user-images.githubusercontent.com/5443355/142987014-822dca5f-81cc-4907-a42d-923bb1f4e162.png)

build后，使用该功能时浏览器会直接卡死掉

**Comment by 07akioni** [comment]
> > > ### This function solves the problem (这个功能解决的问题)
> > > 通过选择的第一个日期，动态控制禁用日期范围
> > > ### Expected API (期望的 API)
> > > 像 element 的 change 事件
> > 
> > 
> > 通过目前提供的禁用 API 已经可以动态禁用时间范围了，DEMO 里面有
> 
> 功能是实现了，但碰到另外一个问题；我不确定是我的写法有问题，还是组件的问题；
> 
> 代码片段 ![image](https://user-images.githubusercontent.com/5443355/142987260-6b3c3a11-3f66-490f-87eb-10df7a382ff2.png) ![image](https://user-images.githubusercontent.com/5443355/142987093-e08c38b4-20bc-4aef-90fb-95707dbe43a4.png) ![image](https://user-images.githubusercontent.com/5443355/142987112-4a066a33-46d4-463b-82d5-6e77251b5e41.png)
> 
> 开发时的警告 ![image](https://user-images.githubusercontent.com/5443355/142987014-822dca5f-81cc-4907-a42d-923bb1f4e162.png)
> 
> build后，使用该功能时浏览器会直接卡死掉

估计你写法有问题 template 里面依赖了 oneDate，这样的话就循环渲染了。
