### ISSUE TITLE
Date picker props 'clearable' should also affect the button 'clear' in popover 

### ISSUE THREAD

**Issue by Hawods** [TuSimple/naive-ui#1196]
### This function solves the problem (这个功能解决的问题)
If clearable = false, it means we don't want user to clear the value of picker, no matter how.
### Expected API (期望的 API)
No new API needed.

**Comment by LYErin** [comment]
`clearable` 只是清除输入框的日期值， 不需要弹出框的清除按钮，自行通过actions控制

**Comment by 07akioni** [comment]
> `clearable` 只是清除输入框的日期值， 不需要弹出框的清除按钮，按钮自行通过actions控制

我其实在想这两个要不要关联，毕竟 clearable 这个行为需要一致，我们说不 clearable 其实一定程度是想说值选了就删除不了
