### ISSUE TITLE
Data table slots to customize appearance and cells, similar to Vuetify

### ISSUE THREAD

**Issue by Async0x42** [TuSimple/naive-ui#120]
### This function solves the problem (这个功能解决的问题)
This makes customizing the datable more intuitive by allowing use of automatically imported components (vite-plugin-components) using slots rather than the render function

### Expected API (期望的 API)
https://vuetifyjs.com/en/components/data-tables/#slots

**Comment by 07akioni** [comment]
> ### This function solves the problem (这个功能解决的问题)
> This makes customizing the datable more intuitive by allowing use of automatically imported components (vite-plugin-components) using slots rather than the render function
> 
> ### Expected API (期望的 API)
> https://vuetifyjs.com/en/components/data-tables/#slots

We will consider the api after vue's slot supports TypeScript.
