### ISSUE TITLE
树组件设置复选框父子组件级联问题

### ISSUE THREAD

**Issue by 18302971493** [TuSimple/naive-ui#1201]
### This function solves the problem (这个功能解决的问题)
这个功能的目的是为了解决去掉勾选某一个子节点而和父节点互不影响，例如：设置权限功能，强制级联就导致勾掉某个子权限，父权限也同时被去勾掉。
### Expected API (期望的 API)
建议在树组件增加属性用于开启是否级联操作，开启后可进行级联，关闭后则不进行级联。

**Comment by 07akioni** [comment]
cascade 属性就可以控制级联
