### ISSUE TITLE
select,checkbox v-model:value support object wanted

### ISSUE THREAD

**Issue by hxx0215** [TuSimple/naive-ui#1208]
### This function solves the problem (这个功能解决的问题)
Sometimes we want to know which object the user selected instead of find it in the options.
### Expected API (期望的 API)
Just support v-model:value use object

**Comment by 07akioni** [comment]
Won't provide. Option is the second parameter of `on:update-value` callback.

**Comment by hxx0215** [comment]
So if I want to init the select I should map the List[T] to List[String | Number] and I should collect the user's operation in the on:update-value. 
In the Vueitify's api, it support bind the options with object. Is it hard to implement?

**Comment by 07akioni** [comment]
> So if I want to init the select I should map the List[T] to List[String | Number] and I should collect the user's operation in the on:update-value.
> In the Vueitify's api, it support bind the options with object. Is it hard to implement?

It will make internal code messy. I don't think it's that useful. I would firstly consider feature that is no way to achieve by current APIs.

There are tons of such tricks we can adopt. However that would distract us from focusing on more important things. For example people would ask it for `tree`, `tree-select`, `cascader`, `popselect`, multiple mode. We need hundreds lines of code to make it work stable. Also it does harm to type interface of the current API.

**Comment by hxx0215** [comment]
So, I write a simple version of support object value in CheckboxGroup, could you look at it? Or you just do not want the feature.
[https://github.com/hxx0215/naive-ui/commit/8d429ecfb0271b1ba33c5b2ab314b10d877a0543]()

**Comment by 07akioni** [comment]
> So, I write a simple version of support object value in CheckboxGroup, could you look at it? Or you just do not want the feature.
> https://github.com/hxx0215/naive-ui/commit/8d429ecfb0271b1ba33c5b2ab314b10d877a0543

I just don't want the feature and the reason is said as above.

**Comment by hxx0215** [comment]
It makes your code messy and distracting you, right? Interesting.

**Comment by 07akioni** [comment]
> > So if I want to init the select I should map the List[T] to List[String | Number] and I should collect the user's operation in the on:update-value.
> > In the Vueitify's api, it support bind the options with object. Is it hard to implement?
> 
> It will make internal code messy. I don't think it's that useful. I would firstly consider feature that is no way to achieve by current APIs.
> 
> There are tons of such tricks we can adopt. However that would distract us from focusing on more important things. For example people would ask it for `tree`, `tree-select`, `cascader`, `popselect`, multiple mode. We need hundreds lines of code to make it work stable. Also it does harm to type interface of the current API and has potential confilcts with current API such as `fallback-option`.

See the comment

**Comment by 07akioni** [comment]
If you quite need so, making a composable or an HOC is a way.

**Comment by 07akioni** [comment]
> So, I write a simple version of support object value in CheckboxGroup, could you look at it? Or you just do not want the feature.
> https://github.com/hxx0215/naive-ui/commit/8d429ecfb0271b1ba33c5b2ab314b10d877a0543

Corner cases may happen every where. For `deepEqual` you need a lodash version, since you can assume user is passing a object without cyclic reference.
