### ISSUE TITLE
建议日期选择及时间选择组件bind 的数据值格式修改为日期格式

### ISSUE THREAD

**Issue by 18302971493** [TuSimple/naive-ui#1215]
### This function solves the problem (这个功能解决的问题)
由于日期组件绑定的值目前为时间戳，对接后台服务器不好处理，后台服务器基本都是date类型，需要进行类型转换，很麻烦
### Expected API (期望的 API)
建议选择日期数据直接绑定格式为:"2021-09-22"等这种字符串格式，或者增加一个属性进行控制需要返回时间戳还是日期字符串格式，有效较少前后台对接时间

**Comment by Talljack** [comment]
可以加但是感觉意义不是很大 你拿到时间戳用第三方库转一下就行

**Comment by 07akioni** [comment]
记得有一个相关 issue，这个先关了。@Talljack 把格式化字符串作为第二个参数发出来这个最近可以搞搞，感觉还是有用户需求的

**Comment by jingtu-Lincoin** [comment]
> 可以加但是感觉意义不是很大 你拿到时间戳用第三方库转一下就行

意义不大？我认为意义很大。还要我自己格式化，那我设置的format干嘛用？
