### ISSUE TITLE
Data table not re-render my components 

### ISSUE THREAD

**Issue by artem-kovalev** [TuSimple/naive-ui#1216]
### TuSimple/naive-ui version (版本)
2.16.6

### Vue version (Vue 版本)
3.0.0

### Browser and its version (浏览器及其版本)
Version 93.0.4577.82 (Official Build) (64-bit)

### System and its version (系统及其版本)
Window 10

### Reappearance link (重现链接)
https://github.com/artem-kovalev/naive-data-table-bug

### Reappearance steps (重现步骤)
1) Create data-table component with several column with pagination.
2) Create component with dynamic tags component
3) Add column with custom rendering component from 2 step. 
4) Try to change page size or number

### Expected results (期望的结果)
Column with custom render my component should be redraw

### Actual results (实际的结果)
Column with custom rendering function  did not re-render, all other re-render

**Comment by 07akioni** [comment]
@Volankey

**Comment by Volankey** [comment]
Add `row-key` to `data-table`, otherwise, the components will be reused by vue in the order of the array.
