### ISSUE TITLE
如何理解loading-bar组件中的void el.offsetWidth

### ISSUE THREAD

**Issue by liuzaijiang** [TuSimple/naive-ui#1218]
https://github.com/TuSimple/naive-ui/blob/93fa426b202973a14cde0b92111eba84263b5aae/src/loading-bar/src/LoadingBar.tsx#L64

**Comment by 07akioni** [comment]
> https://github.com/TuSimple/naive-ui/blob/93fa426b202973a14cde0b92111eba84263b5aae/src/loading-bar/src/LoadingBar.tsx#L64

`el.offsetWidth` 是强制 reflow。加 void 是因为 eslint 不允许空表达式，我懒得改规则
