### ISSUE TITLE
栅格自适应display问题，如何设置n-gi某一块小屏幕不可见？

### ISSUE THREAD

**Issue by Baiyuetribe** [TuSimple/naive-ui#1220]
### This function solves the problem (这个功能解决的问题)
栅格自适应display问题，希望新增小屏幕或大屏不可见
### Expected API (期望的 API)
比如bootstrap 或 antdv的栅格设计，a-row内部的a-col可以设置为0，相当于display:none.。 目前naive-ui还没有自适应display，希望新增自适应不可见功能

**Comment by 07akioni** [comment]
设成 0 不显示这个可以考虑

**Comment by 07akioni** [comment]
@Talljack
