### ISSUE TITLE
下拉菜单字体模糊问题

### ISSUE THREAD

**Issue by jinmarcus** [TuSimple/naive-ui#1223]
### TuSimple/naive-ui version (版本)
2.19.1

### Vue version (Vue 版本)
3.2.14

### Browser and its version (浏览器及其版本)
chrome 91.0.4472.124

### System and its version (系统及其版本)
win10

### Node version (Node 版本)
14.15.4

下拉菜单弹出的选项中的菜单有时候会出现字体模糊的情况，我找了一下原因
原因是在下拉菜单的浮层中使用了transform: translateX或translateY中的数字不是整数引起的

比如以下会出现字体模糊：
![image](https://user-images.githubusercontent.com/17996289/134458537-27758bf8-fd1b-4b84-b309-a0475cc1f7d1.png)
```
<div class="v-binder-follower-content" v-placement="bottom-start" style="width: 170px; min-width: 170px; transform: translateX(666.5px) translateY(215.5px); transform-origin: left top;">
</div>
```

但是如果translateX或translateY中的像素是整数就不会，如下就不会出现模糊
![image](https://user-images.githubusercontent.com/17996289/134449271-b341210b-4b20-4d1e-be87-59066266e9cc.png)
```
<div class="v-binder-follower-content" v-placement="bottom-start" style="width: 170px; min-width: 170px; transform: translateX(671px) translateY(206px); transform-origin: left top;">
</div>
```

建议是否可以将该处的像素值改为整数型？
这样可以解决下拉字体模糊的问题。

**Comment by Volankey** [comment]
这是否是浏览器和系统的原因，因为我这没发现这种情况

**Comment by jinmarcus** [comment]
@Volankey 你把下拉菜单放到浮层内，再拖动浮层，就会出现这个问题。
然后我发现是下拉菜单调用了vueuc，这个插件，问题出现在这个插件中，
我已经给这个插件提了一个pr，合并后就可以解决这个问题。

https://github.com/07akioni/vueuc/pull/91
https://github.com/07akioni/vueuc/issues/90

**Comment by jinmarcus** [comment]
@Volankey 
可否更新一下vueuc的版本号为：0.4.12 
这个插件已经在最新的版本中，修复了这个问题。

**Comment by Volankey** [comment]
@07akioni

**Comment by 07akioni** [comment]
@jinmarcus 更新看看还有么

**Comment by jinmarcus** [comment]
@07akioni 我看过了，该插件已更新了，这个问题已经解决了。
