### ISSUE TITLE
[Custom Theme] Global common theme does not effect `NSelect`

### ISSUE THREAD

**Issue by myWsq** [TuSimple/naive-ui#1229]
### TuSimple/naive-ui version (版本)
2.19.1

### Vue version (Vue 版本)
3.2.10

### Browser and its version (浏览器及其版本)
Chrome(93.0.4577.82)

### System and its version (系统及其版本)
MacOS 11.5.2

### Reappearance link (重现链接)
https://codesandbox.io/s/reverent-wright-9kcg8?file=/src/App.vue

### Reappearance steps (重现步骤)
Override `fontSizeMedium` and `heightMedium` on `n-config-provider`

### Expected results (期望的结果)
The `Select` component height should same with input component.

### Actual results (实际的结果)
Global common theme does not effect `NSelect`

### Remarks (补充说明)
The problem may be caused by `InternalSelection`

**Comment by 07akioni** [comment]
@Volankey

**Comment by Volankey** [comment]
Select should override by the follow code
```
 /**
   * @type import('naive-ui').GlobalThemeOverrides
   */
   const theme = {
      common: {
        fontSizeMedium: "14px",
        heightMedium: "40px",
      },
      Select: {
        peers: {
          InternalSelection:{
           heightMedium: "40px",
          fontSizeMedium: '14px',

          }
        },
      },
    };
```

**Comment by myWsq** [comment]
@Volankey Yeah I found that way when I view source code. I still confused why `InternalSelection` does not inherit public properties.

**Comment by Volankey** [comment]
It depends on implementation, @07akioni  can give you a reasonable answer.

**Comment by 07akioni** [comment]
> @Volankey Yeah I found that way when I view source code. I still confused why `InternalSelection` does not inherit global properties.

I'll take a look.
