### ISSUE TITLE
components/dropdown/手动定位，右击出现后，必须选择后才消失，点击页面其它位置它也应该关闭

### ISSUE THREAD

**Issue by Lonely-flyer** [TuSimple/naive-ui#123]
### This function solves the problem (这个功能解决的问题)
增强友好，右击出现dropdown后不一定选择某项之后才能关闭，点击dropdown外部它也应该关闭

### Expected API (期望的 API)
https://ant.design/components/dropdown-cn/
他应该像antd一样出现之后，再次点击任何位置就关闭了

**Comment by 07akioni** [comment]
会考虑暴露一个 `onClickoutside`
