### ISSUE TITLE
Tree控件，checked-keys属性与cascade关联选择冲突的问题。

### ISSUE THREAD

**Issue by imhuntun** [TuSimple/naive-ui#1231]
### TuSimple/naive-ui version (版本)
2.19.1

### Vue version (Vue 版本)
3.2.16

### Browser and its version (浏览器及其版本)
Chrome  92.0.4515.159

### System and its version (系统及其版本)
Window 10

### Reappearance link (重现链接)
http://github.com

### Reappearance steps (重现步骤)
1.Tree中包含两级结构，每级下包含多个选择。
2.设置Tree的cascade属性和checkable，并给checked-keys赋值，checked-keys中的数值仅包含第一级以及第二级的其中一个
3.Tree会将checked-keys中不包含的二级选项一并勾选。

### Expected results (期望的结果)
Tree根据checked-keys中的数据，进行勾选。

### Actual results (实际的结果)
目前Tree组件会自动勾选级别以下的所有数据，而不是根据checked-keys中的数据进行勾选的。

**Comment by Volankey** [comment]
第一级都被选中了，第二级为什么不是全选呢?
要想只选第二级中的其中一个，`checked-keys` 就不应该包含第一级

**Comment by 07akioni** [comment]
如果你觉得现有逻辑不满意，可以完全由自己控制值，不要开 cascade。

现在的逻辑是合理的。

**Comment by xuzhitudev** [comment]
真诚希望贵团队可以考虑一下加个checked-strage类似的属性，实际场景中确实存在诸如此类的问题。

**Comment by 07akioni** [comment]
> 真诚希望贵团队可以考虑一下加个checked-strage类似的属性，实际场景中确实存在诸如此类的问题。

check-strategy 现在已经有了，所有的树形数据组件都有

**Comment by xuzhitudev** [comment]
> > 真诚希望贵团队可以考虑一下加个checked-strage类似的属性，实际场景中确实存在诸如此类的问题。
> 
> check-strategy 现在已经有了，所有的树形数据组件都有

...看到了。回到问题本身，试了下后端返回的方式去处理，写起来些也很Nice！
