### ISSUE TITLE
How to listen for scroll events？（n-layout-content）

### ISSUE THREAD

**Issue by mzl1988** [TuSimple/naive-ui#1232]
### This function solves the problem (这个功能解决的问题)
How to listen for scroll events？
### Expected API (期望的 API)
<n-layout-content @scroll="scrollChange"/>

**Comment by Volankey** [comment]
Because `n-scrollbar` is an internal components, we don't expose the api. It is recommended that you use ref to obtain dom to monitor scroll events.
Of course, if you find it troublesome, you can do it this way, See https://codesandbox.io/s/7djjy?file=/src/Demo.vue:1103-1117.

**Comment by 07akioni** [comment]
> Because `n-scrollbar` is an internal components, we don't expose the api. It is recommended that you use ref to obtain dom to monitor scroll events.
> Of course, if you find it troublesome, you can do it this way, See https://codesandbox.io/s/7djjy?file=/src/Demo.vue:1103-1117.

We should expose scroll event. It's useful
