### ISSUE TITLE
checkbox 可否定义选中和未选中的值

### ISSUE THREAD

**Issue by jinmarcus** [TuSimple/naive-ui#1233]
checkbox目前的值只有 true 和 false
可否通过传参的方式，来定义选中和未选中的值？
比如 1 和 0
这在业务场景比较常见。

**Comment by 07akioni** [comment]
> checkbox目前的值只有 true 和 false
> 可否通过传参的方式，来定义选中和未选中的值？
> 比如 1 和 0
> 这在业务场景比较常见。

感觉说服力不太够，这个事并不是很复杂。

任何组件最后都可能有这种对于仅 emit 值不满意的状况，开这个口子不实际。
