### ISSUE TITLE
checkbox和switch是否可定义选中和未选中的值

### ISSUE THREAD

**Issue by jinmarcus** [TuSimple/naive-ui#1234]
### This function solves the problem (这个功能解决的问题)

checkbox和switch目前的值只有 true 和 false
可否通过传参的方式，来定义选中和未选中的值？
比如 1 和 0
这在业务场景比较常见。
### Expected API (期望的 API)
比如
```
<n-checkbox
  v-model:checked="value"
  :true-value="1"
  :false-value="0"
>性别</n-checkbox>
```

switch组件
```
<n-switch
  v-model:value="value"
  :true-value="1"
  :false-value="0"
/>
```

**Comment by Volankey** [comment]
什么实际场景下用到？

**Comment by jinmarcus** [comment]
业务场景基本上都要用到，数据库里不可能存true和false，基本上都是1或0，也可能是别的字符串来代替，总之true和false的可能性不大，true和false基本上只能用于前端来判断，和数据库交互，基本上都要自己去修改
所以如果能定义true-value和false-value，那灵活性就很大了。

**Comment by 07akioni** [comment]
这又是一个需要做深拷贝对比的需求，如果值是对象，怎么盘算 switch 是否打开，这是个问题。

如果你只想支持基本类型，我觉得可以考虑。

**Comment by jinmarcus** [comment]
@07akioni 我认为仅可以支持boolean / string / number这三种类型足够了。
可以满足绝大部分的业务场景了。

**Comment by 07akioni** [comment]
> @07akioni 我认为仅可以支持boolean / string / number这三种类型足够了。
> 可以满足绝大部分的业务场景了。

有没有其他的库实现了类似的功能？

**Comment by jinmarcus** [comment]
可参考：
https://element-plus.gitee.io/zh-CN/component/switch.html#attributes
https://element-plus.gitee.io/zh-CN/component/checkbox.html#checkbox-button-attributes

**Comment by 07akioni** [comment]
> https://element-plus.gitee.io/zh-CN/component/switch.html#attributes

来个 PR？`checkedValue` & `uncheckedValue`

**Comment by OneSeven** [comment]
@07akioni 同需要，很多细节方面element-ui做的很不错，希望写组件的时候能参考一下
目前switch组件，在应对0和1的时候，都需要在接受数据和发送数据做转换，太过繁琐了

**Comment by 07akioni** [comment]
> @07akioni 同需要，很多细节方面element-ui做的很不错，希望写组件的时候能参考一下
> 目前switch组件，在应对0和1的时候，都需要在接受数据和发送数据做转换，太过繁琐了

我的观念也得跟着大家的反馈更新
