### ISSUE TITLE
cascader目前仅返回了最后一级的值，能返回相关的父级值吗？

### ISSUE THREAD

**Issue by Adangs** [TuSimple/naive-ui#1235]
### This function solves the problem (这个功能解决的问题)
比如省市区选择时，表单提交的时候需要提供对应的三级数据
### Expected API (期望的 API)
element cascader 值返回了一个数组[1,2,3]，
使用者可以自由选择

请问naive ui 支持吗？

**Comment by 07akioni** [comment]
> ### This function solves the problem (这个功能解决的问题)
> 比如省市区选择时，表单提交的时候需要提供对应的三级数据
> 
> ### Expected API (期望的 API)
> element cascader 值返回了一个数组[1,2,3]，
> 使用者可以自由选择
> 
> 请问naive ui 支持吗？

暂时没有，可以加上

**Comment by 07akioni** [comment]
这个确实还挺有必要的

**Comment by hanpandeng** [comment]
> 这个确实还挺有必要的

请问这个功能加上了吗？我现在也碰到相同的功能需求。
如果这个功能没有加上可以提供解决方法吗？感谢

**Comment by hanpandeng** [comment]
> > 这个确实还挺有必要的
> 
> 请问这个功能加上了吗？我现在也碰到相同的功能需求。 如果这个功能没有加上可以提供解决方法吗？感谢

解决了，使用update回调方法中的第三个参数pathValues拿到完整的所有层级选中的value；不过还是希望能够v-model：value能够默认完整的层架value，类似elementui和ant design中级联组件拿到的值 [1,2,3]。
感谢

**Comment by yesw6a** [comment]
> > > 这个确实还挺有必要的
> > 
> > 
> > 请问这个功能加上了吗？我现在也碰到相同的功能需求。 如果这个功能没有加上可以提供解决方法吗？感谢
> 
> 解决了，使用update回调方法中第三个参数pathValues拿到完整的所有层级选中的value；不过还是希望能够在v-model：value默认完整的层级value，类似elementui和ant design中级联组件拿到的值 [1,2,3]。 感谢

虽然能够拿到所有的父级值，但是回显的时候应该怎么处理呢？

**Comment by ly-857** [comment]
> > > 这个确实还挺有必要的
> > 
> > 
> > 请问这个功能加上了吗？我现在也碰到相同的功能需求。 如果这个功能没有加上可以提供解决方法吗？感谢
> 
> 解决了，使用update回调方法中第三个参数pathValues拿到完整的所有层级选中的value；不过还是希望能够在v-model：value默认完整的层级value，类似elementui和ant design中级联组件拿到的值 [1,2,3]。 感谢

**Comment by ly-857** [comment]
> > > 这个确实还挺有必要的
> > 
> > 
> > 请问这个功能加上了吗？我现在也碰到相同的功能需求。 如果这个功能没有加上可以提供解决方法吗？感谢
> 
> 解决了，使用update回调方法中第三个参数pathValues拿到完整的所有层级选中的value；不过还是希望能够在v-model：value默认完整的层级value，类似elementui和ant design中级联
