### ISSUE TITLE
[Feature request] `disabled` or `max` props for `n-upload`

### ISSUE THREAD

**Issue by liho98** [TuSimple/naive-ui#1237]
### This function solves the problem (这个功能解决的问题)
hide the upload button when the number of file limit is reached, or disabled the upload button when the number of file limit is reached
### Expected API (期望的 API)
```
<n-upload :max="2" list-type="image-card" /> // will hide the upload button when the number of file limit is reached.

<n-upload :disabled="fileList >=2" list-type="image-card" /> // will disabled the upload button when the number of file limit is reached.

```

**Comment by Volankey** [comment]
Try controlled upload https://www.naiveui.com/en-US/os-theme/components/upload#controlled.
```
 v-model:file-list="fileList"
 :disabled="fileList.length>3"
```

**Comment by liho98** [comment]
> Try controlled upload https://www.naiveui.com/en-US/os-theme/components/upload#controlled.
> 
> ```
>  v-model:file-list="fileList"
>  :disabled="fileList.length>3"
> ```

did you tried this code, when disabled is true the opacity of entire file list is BELOW 1, besides doc didnt even mentioned about disabled, however max props is more useful then.
![unknown](https://user-images.githubusercontent.com/44250267/134793688-45d9ad5c-a840-45be-942a-e4b77bad3961.png)

**Comment by Volankey** [comment]
@07akioni

**Comment by 07akioni** [comment]
Add a `trigger-disabled` prop?

`max` is needed for uncontrolled mode and it should be related to trigger disabled state.
