### ISSUE TITLE
文档是 on-update:value，而实际在 vue3 里的写法是 @update:value ，这样的文档写法是否可以改进一下？

### ISSUE THREAD

**Issue by moketao** [TuSimple/naive-ui#124]
### TuSimple/naive-ui version (版本)
2.11.11

### Vue version (Vue 版本)
3.1.1

### Browser and its version (浏览器及其版本)
Chrome 最新版

### System and its version (系统及其版本)
Windows 最新版

请看这个文档，https://www.naiveui.com/zh-CN/os-theme/components/slider

### Expected results (根据文档，我写出这样的代码)：
on-update:value="onChange"

### Actual (实际应该写成这样)：
@update:value="onChange"

### Remarks (补充说明)
文档中，对于 update 事件的描述是 on-update:value，而实际在 vue3 里的写法是 @update:value ，这样的文档写法是否可以改进一下？或者建议加上关于 on-update 的例子

**Comment by 07akioni** [comment]
实际上两种书写风格结果是一样的，这么些最主要的原因是，**这个 prop 的名字真的就叫 `onUpdate:value`**。

对于 Demo 应该不会做专门修改了，但是可以在常见问题里面补充一下这些区别。

**Comment by mrerhuo** [comment]
提交问题很麻烦。你们得简化提交问题的流程，不然不想尝试了。

**Comment by mumashanren** [comment]
在 VSCode 中 @update:value="handleUpdateValue" 提示不出真实的参数类型且类型检查错误，如果使用 vue-tsc 构建检查会报错。用 @update-value="handleUpdateValue" 可以正常工作。用的是 Volar 插件。

**Comment by 07akioni** [comment]
> 在 VSCode 中 @update:value="handleUpdateValue" 提示不出真实的参数类型且类型检查错误，如果使用 vue-tsc 构建检查会报错。用 @update-value="handleUpdateValue" 可以正常工作。用的是 Volar 插件。

这是 volar 的 bug。
