### ISSUE TITLE
希望新增 菜单 Menu 展开/收缩的回调

### ISSUE THREAD

**Issue by Greasen** [TuSimple/naive-ui#1241]
### This function solves the problem (这个功能解决的问题)
希望新增 菜单 Menu 展开/收缩的回调
### Expected API (期望的 API)
希望菜单 Menu 中新增 展开/收缩的回调，希望新增展开/收缩成功回调

**Comment by Volankey** [comment]
`on-update:expanded-keys` 应该可以，试试

**Comment by 07akioni** [comment]
这个是否折叠就是你控制的，自己监听一下就好了

**Comment by Greasen** [comment]
可能我没有描述清楚，我想要的是监听展开/收缩动画或动作结束后的回调。

**Comment by 07akioni** [comment]
@Greasen 改一下 issue 名称

**Comment by 07akioni** [comment]
> 可能我没有描述清楚，我想要的是监听展开/收缩动画或动作结束后的回调。

虽然可以加，但是你要这个功能是干啥呢？

**Comment by jinmarcus** [comment]
似乎是有的
on-update:show
设个方法就是显示状态改变的回调函数

**Comment by 07akioni** [comment]
@Greasen

**Comment by Greasen** [comment]
业务场景中需要监听到动画结束后处理相应的交互。

**Comment by Talljack** [comment]
@07akioni 应该是合理的吧 是否可以加上

**Comment by 07akioni** [comment]
> @07akioni 应该是合理的吧 是否可以加上

其实我已经加上了，只是因为我没听到合理的理由就没放写出来，你个加个 changelog 和文档关掉吧。可能是 onAfterCollapse

**Comment by Talljack** [comment]
> > @07akioni 应该是合理的吧 是否可以加上
> 
> 其实我已经加上了，只是因为我没听到合理的理由就没放出来，你个加个 changelog 和文档关掉吧。可能是 onAfterCollapse

好的

**Comment by 07akioni** [comment]
@Greasen 我有一点没搞懂 是横向的收缩展开 还是里面子菜单的？

**Comment by Greasen** [comment]
> @Greasen我有一点没搞懂是横向的收缩展开还是里面子菜单的？

是收缩展开
