### ISSUE TITLE
关于button 的size的class名（只是一个建议）

### ISSUE THREAD

**Issue by jinmarcus** [TuSimple/naive-ui#1244]
### This function solves the problem (这个功能解决的问题)

如果button的size设为类似这种
```
<n-button size="tiny">小小</n-button>
```
然后实际的dom节点的类是这样的
```
<button class="n-button n-button--default-type" type="button"></button>
```

就是我想单独为这个size的按钮修改样式没有办法修改，只能手动加一个className才可以

### Expected API (期望的 API)
可否给size属性，单独设一个classname？
比如加一个类似`n-button--size-tiny`的类名，给予区分
这只是一个建议，这样统一设置样式的时候会比较方便一点。

```
<button class="n-button n-button--default-type n-button--size-tiny" type="button"></button>
```

**Comment by 07akioni** [comment]
可以的，可以来个 PR，用 `n-button--tiny-size` 这种形式

**Comment by 07akioni** [comment]
我顺手写了
