### ISSUE TITLE
希望新增Upload支持大小图预览

### ISSUE THREAD

**Issue by Kigoal** [TuSimple/naive-ui#1245]
### This function solves the problem (这个功能解决的问题)
在没有点击预览时默认加载小尺寸图片，以节约服务端流量
### Expected API (期望的 API)
```json
{
  "thumbnailUrl": {
    "small": "https://xxxx.com?size=100",
    "original": "https://xxxx.com?size=auto"
  }
}
```

**Comment by kev1nzh37** [comment]
UploadFileInfo.thumbnailUrl 应该符合，当传入时缩略图会使用这个属性的 url。

**Comment by 07akioni** [comment]
@Kigoal 试试？

**Comment by Kigoal** [comment]
目前为止，显示缩略图url是通过props的createThumbnailUrl接口返回获取的，而非直接在UploadFileInfo类型中直接传入thumbnailUrl字段值。
