### ISSUE TITLE
体验性建议，级联选择框和树选择框没有动画效果

### ISSUE THREAD

**Issue by LIUSHUAI2018** [TuSimple/naive-ui#1249]
### This function solves the problem (这个功能解决的问题)
组件流畅性
### Expected API (期望的 API)
希望级联选择框和树选择框这两个组件有一些动画效果

**Comment by 07akioni** [comment]
> ### This function solves the problem (这个功能解决的问题)
> 组件流畅性
> 
> ### Expected API (期望的 API)
> 希望级联选择框和树选择框这两个组件有一些动画效果

cascader 没有是预期中的，加上动画无法做每个菜单右侧角落圆角到直角的过渡。

tree select 因为默认开启的虚拟滚动，这个涉及一个比较麻烦改动的点，所以优先级很低。
