### ISSUE TITLE
n-input v-model:value not updated if it is related to an object's property

### ISSUE THREAD

**Issue by hcivelek** [TuSimple/naive-ui#1256]
### TuSimple/naive-ui version (版本)
2.19.3

### Vue version (Vue 版本)
3.2.19

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
Macos(11.2.3)

### Reappearance link (重现链接)
https://codesandbox.io/s/pedantic-flower-ngmcl?file=/src/Demo.vue

### Reappearance steps (重现步骤)
Fill all inputs
Click to reset button

### Expected results (期望的结果)
There are three inputs. The first and the second have v-model:value="form.name" and v-model:value="form.email". When reset button clicked form.value = {} but input's value not changed. They should change.

### Actual results (实际的结果)
The first and the second input's value not changed but the form variable is changed.

**Comment by amadeus711** [comment]
https://codesandbox.io/s/compassionate-hoover-mxffb?file=/src/Demo.vue
Will that solve your problem?

**Comment by hcivelek** [comment]
Yes :)
I found the same solution, too after publishing the issue. But I hesitated to write here because maybe it is still a bug to fix. Thank you, that solves my problem anyway. I have to check all properties of the form but not a big deal. It works.

**Comment by 07akioni** [comment]
> found the same solution, too after publishing the issue. But I hesitated to write here because maybe it is still a bug to fix. Thank you, that solves my problem anyway. I have to check all properties of the form but not a big deal. It works.

If an input's value is undefined, we treated it in uncontrolled mode, so if you change a value to undefined, the displayed value won't change.

**Comment by galaxy-s10** [comment]
oh my god，use undefined no resolved problem，but use null can resolved problem，i search half a day

**Comment by 07akioni** [comment]
> oh my god，use undefined no resolved problem，but use null can resolved problem，i search half a day

I've added a new doc page which may explains the problem for users.

https://www.naiveui.com/en-US/os-theme/docs/controlled-uncontrolled

**Comment by zclzone** [comment]
> > found the same solution, too after publishing the issue. But I hesitated to write here because maybe it is still a bug to fix. Thank you, that solves my problem anyway. I have to check all properties of the form but not a big deal. It works.发布问题后也找到了相同的解决方案。但我犹豫是否要写在这里，因为也许它仍然是一个需要修复的错误。谢谢，无论如何，这解决了我的问题。我必须检查表单的所有属性，但没什么大不了的。有用。
> 
> If an input's value is undefined, we treat it in uncontrolled mode, so if you change a value to undefined, the displayed value won't change.如果输入的值未定义，我们将其视为不受控制的模式，因此，如果将值更改为未定义，则显示的值不会更改。

This design is a bit bad.

**Comment by Caffeine19** [comment]
> > found the same solution, too after publishing the issue. But I hesitated to write here because maybe it is still a bug to fix. Thank you, that solves my problem anyway. I have to check all properties of the form but not a big deal. It works.
> 
> If an input's value is undefined, we treat it in uncontrolled mode, so if you change a value to undefined, the displayed value won't change.

This becomes problematic when using the “vee-validate” package.
When called "resetForm" from "vee-validate",
it would reset form values into {}
And I cant set the field value to null, because the reset form only accepts undefined|string

```ts
  resetForm(
    {
      // reset to an empty object, wont work
      values: {},
    },
    {
      force: true,
    },
  )

  // wont work
  setFormFieldValue('alarmType', undefined)

  // will work, but type error
  setFormFieldValue('alarmType', null)
```

<img width="917" height="180" alt="Image" src="https://github.com/user-attachments/assets/ca0850c8-e15e-4a97-b4cf-9e0071886bba" />
