### ISSUE TITLE
[feat]请求描述组件去掉冒号

### ISSUE THREAD

**Issue by OneSeven** [TuSimple/naive-ui#1263]
### This function solves the problem (这个功能解决的问题)
不需要冒号，或者想用其他符号代替
### Expected API (期望的 API)
去掉冒号。
默认加冒号，默写场景下多余，还不能去掉！

**Comment by 07akioni** [comment]
可以给个属性

**Comment by 07akioni** [comment]
你可以先用 display: none 凑活一下
