### ISSUE TITLE
当下拉菜单位置在边缘，弹出的菜单被浏览器遮挡

### ISSUE THREAD

**Issue by jinmarcus** [TuSimple/naive-ui#1268]
### TuSimple/naive-ui version (版本)
2.19.1

### Vue version (Vue 版本)
3.2.14

### Browser and its version (浏览器及其版本)
chrome 91.0.4472.124

### System and its version (系统及其版本)
win10

### Node version (Node 版本)
14.15.4

当下拉菜单位置在边缘，弹出的菜单被浏览器遮挡

![image](https://user-images.githubusercontent.com/17996289/135375824-9462185d-234f-46f9-9125-f3e6f2d2ab4d.png)

代码
```
<n-dropdown trigger="hover" @select="handleSelect" :options="options">
    <n-button>设置</n-button>
</n-dropdown>
```

**Comment by 07akioni** [comment]
弹出内容只会做向对面的翻转，没有做其他类的反转。

这种时候你最好明确的写好 placement，而不是等着组件去适应。

**Comment by 07akioni** [comment]
要增加横向的调整是一个比较麻烦的体力活，暂时还没空弄。

**Comment by jinmarcus** [comment]
没事，这些是细节，希望框架越来越强。

**Comment by Xwudao** [comment]
类似的还有tooltip之类的组件，之后有时间如果要修改，可以一并弄了

**Comment by 07akioni** [comment]
这个应该是已经支持了
