### ISSUE TITLE
关于虚拟滚动的几个问题!

### ISSUE THREAD

**Issue by qqfei1858** [TuSimple/naive-ui#127]
### This function solves the problem (这个功能解决的问题)
virtual-scroll

### Expected API (期望的 API)
1.关于Data Table的虚拟化是否支持树形?
2.关于Tree的虚拟化是否支持不开启虚拟话的正常功能?例如复选和单选!

**Comment by 07akioni** [comment]
> ### This function solves the problem (这个功能解决的问题)
> virtual-scroll
> 
> ### Expected API (期望的 API)
> 1.关于Data Table的虚拟化是否支持树形?
> 2.关于Tree的虚拟化是否支持不开启虚拟话的正常功能?例如复选和单选!

1. DataTable 支持
2. Tree 开不开虚拟滚动功能是一样的

不要在 GitHub 里面问功能相关的问题，请去钉钉群或者 Discord。
