### ISSUE TITLE
Table列的key支持 a.b.c 的嵌套写法

### ISSUE THREAD

**Issue by Eyanger** [TuSimple/naive-ui#1271]
### This function solves the problem (这个功能解决的问题)
简化嵌套key的写法，不然需要写个render函数。
### Expected API (期望的 API)
可以使用嵌套的key，如：
const columns = [
  {
    title: '用户名',
    key: 'user.name',
  },
  ...
]

**Comment by 07akioni** [comment]
我觉得你可能错误理解了这个 key 是在干什么，这个 key 是列的 key，不是行的 key。

**Comment by 07akioni** [comment]
合理，安排
