### ISSUE TITLE
日期范围选择器是否可以支持默认选中结束时间来结束选择

### ISSUE THREAD

**Issue by JonDoe297-Rorschach** [TuSimple/naive-ui#128]
### This function solves the problem (这个功能解决的问题)
daterange类型的选择器在actions缺失confirm时实际上无法选择时间

### Expected API (期望的 API)
daterange类型的选择器在actions缺失confirm时是否可以支持默认选中结束时间来结束选择

**Comment by 07akioni** [comment]
> ### This function solves the problem (这个功能解决的问题)
> daterange类型的选择器在actions缺失confirm时实际上无法选择时间
> 
> ### Expected API (期望的 API)
> daterange类型的选择器在actions缺失confirm时是否可以支持默认选中结束时间来结束选择

未来可能会增加一个 Prop 来控制关闭时是否更新值。
