### ISSUE TITLE
color-picker 组件增加自定义预设颜色 最好能增加颜色吸取功能

### ISSUE THREAD

**Issue by xiangshaolong** [TuSimple/naive-ui#1281]
### This function solves the problem (这个功能解决的问题)
color-picker 组件增加自定义预设颜色 最好能增加颜色吸取功能
### Expected API (期望的 API)
color-picker 组件增加自定义预设颜色 最好能增加颜色吸取功能

**Comment by anish-dcruz** [comment]
@nooooooom thanks

I think the action slot needs to be documented

**Comment by 07akioni** [comment]
It's not documented since I don't want it to be public yet. However you can use it.

**Comment by 07akioni** [comment]
> > 一般来说吸色功能要借助浏览器自己的 color-picker 来做，我们提供个 trigger 封装一下。
> 
> 是准备集成原生的input来做吗

是的，这是一个可行的方案
