### ISSUE TITLE
PopSelect show dropdown menuitem incorrect when set multislect

### ISSUE THREAD

**Issue by coader** [TuSimple/naive-ui#1282]
### TuSimple/naive-ui version (版本)
2.19.3

### Vue version (Vue 版本)
3.2.19

### Browser and its version (浏览器及其版本)
Chrome 91

### System and its version (系统及其版本)
Win10

### Reappearance link (重现链接)
https://codesandbox.io/s/happy-river-c9n6j?file=/src/Demo.vue

### Reappearance steps (重现步骤)
set multi

### Expected results (期望的结果)
the check flag icon should not overlay text

### Actual results (实际的结果)
overlay

**Comment by coader** [comment]
![popselect](https://user-images.githubusercontent.com/3700498/135832972-9cd8a3c9-9cca-4ed3-ada8-1301ac5a0473.png)

**Comment by 07akioni** [comment]
确实有点问题

**Comment by coader** [comment]
另外有点建议：
1 可以设置最小宽度 
2 已选中的不需要backgroundcolor 不太美观

现在我可以通过style自行设定

**Comment by coader** [comment]
![image](https://user-images.githubusercontent.com/3700498/135833350-86a8e187-1cbf-4545-9961-59d7b9587a34.png)

**Comment by 07akioni** [comment]
> 另外有点建议： 1 可以设置最小宽度 2 已选中的不需要backgroundcolor 不太美观
> 
> 现在我可以通过style自行设定

你可以试试 style，应该是会直接挂到菜单上的

**Comment by 07akioni** [comment]
active 背景色这个事情在实现层面是比较尴尬的状态，我以后会想办法调整一下

active 的优先级高于 hover，所以如果我把 active 设为透明的话 hover 也会是透明，这就不太好了，我还没找到啥方法能仿佛 active 的样式没写过一样

**Comment by coader** [comment]
已选中的现在背景色 会让人误以为是disabled 
我再看了下ant design 它文字不会变色 只是加粗 稍为好点
但是过多的干扰色 从操作和阅读上来说 是不利的
我最倾向的还是标记图标在左侧 不做任何颜色改变

**Comment by 07akioni** [comment]
> 已选中的现在背景色 会让人误以为是disabled 我再看了下ant design 它文字不会变色 只是加粗 稍为好点 但是过多的干扰色 从操作和阅读上来说 是不利的 我最倾向的还是标记图标在左侧 不做任何颜色改变

标记在左侧我也考虑过，在不选东西的时候因为对齐的问题看起来很违和，至于颜色的话我之后会想办法弄的好调整一些，哪怕默认的不满足要求也可以让用户调起来简单点
