### ISSUE TITLE
datatable selection column width is wrong when set fixed left

### ISSUE THREAD

**Issue by coader** [TuSimple/naive-ui#1283]
### TuSimple/naive-ui version (版本)
2.19.3

### Vue version (Vue 版本)
3.2.19

### Browser and its version (浏览器及其版本)
Chrome91

### System and its version (系统及其版本)
Win10

### Reappearance link (重现链接)
https://codesandbox.io/s/tender-chaplygin-uon1q?file=/src/Demo.vue

### Reappearance steps (重现步骤)
set selection and the other first column fixed=left
set td whitespace nowrap

### Expected results (期望的结果)
keep selection column's witdh to be 40px

### Actual results (实际的结果)
width be 16px

**Comment by coader** [comment]
![image](https://user-images.githubusercontent.com/3700498/135838370-81b2729c-5f32-44ed-9e8a-9356198c66eb.png)

**Comment by coader** [comment]
大概看了一下  colgroup 里 width 在这种情况下不受控制了

**Comment by coader** [comment]
增加 .n-data-table .n-data-table-th.n-data-table-th--selection 
min-width:40px 可以解决
这种布局可能不太符合标准 但我这个场景还是比较有用的

**Comment by 07akioni** [comment]
这个看起来可以处理，我来加一个 min-width 的属性
