### ISSUE TITLE
popover and tooltips layout

### ISSUE THREAD

**Issue by coader** [TuSimple/naive-ui#1284]
### TuSimple/naive-ui version (版本)
2.19.3

### Vue version (Vue 版本)
3.2.19

### Browser and its version (浏览器及其版本)
chrome91

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://codesandbox.io/s/pedantic-mclean-bolsr?file=/package.json

### Reappearance steps (重现步骤)
hover "setting", then move to "重置"

### Expected results (期望的结果)
.

### Actual results (实际的结果)
.

**Comment by coader** [comment]
按naiveui admin写的类似的 但行为不管是popover的出现位置 还是tooltip的出现时机和位置 都不对
另外setting如果用button包括 popover的出现位置是对的

**Comment by 07akioni** [comment]
这个例子里面你要弹出东西的元素套了 div 了，自然会按照 div 的位置去定位

**Comment by 07akioni** [comment]
![image](https://user-images.githubusercontent.com/18677354/135883355-f864dd7f-9cc3-4cae-9cd4-0c060539f34f.png)

不想出问题就套宽度不会自动撑开的元素

**Comment by coader** [comment]
我改为button了 但tooltip依然在左上角

**Comment by coader** [comment]
之前是popover位置不对 改为button后 popover没问题 tooltip仍然不对

**Comment by 07akioni** [comment]
> 之前是popover位置不对 改为button后 popover没问题 tooltip仍然不对

目前 popover 的嵌套还存在问题，你可以在其中一层给 popover 套个 inline-flex 的 div 放在 tooltip 里面
