### ISSUE TITLE
Popover 是否支持渲染到父节点？

### ISSUE THREAD

**Issue by rashagu** [TuSimple/naive-ui#1288]
### This function solves the problem (这个功能解决的问题)
Popover 支持渲染到指定节点
### Expected API (期望的 API)
getPopoverContainer：() => document.body

**Comment by 07akioni** [comment]
to="htmlelement or selector or false"

这个没在文档里写

**Comment by 07akioni** [comment]
试试，用起来没问题的话我在文档加上

**Comment by rashagu** [comment]
> 试试，用起来没问题的话我在文档加上
 popover组件   试了一下可以的  填`false`的话直接渲染到了父节点。
好像 没有ts类型 提示，然后在下拉菜单组件 是否也有这个属性？

**Comment by 07akioni** [comment]
> > 试试，用起来没问题的话我在文档加上
> > popover组件   试了一下可以的  填`false`的话直接渲染到了父节点。
> > 好像 没有ts类型 提示，然后在下拉菜单组件 是否也有这个属性？

应该是所有能转移的都有这个属性

**Comment by 07akioni** [comment]
没有类型是个失误

**Comment by 07akioni** [comment]
下个版本加上
