### ISSUE TITLE
Add hold event to change value of <n-input-number/>

### ISSUE THREAD

**Issue by sondh0127** [TuSimple/naive-ui#1293]
### This function solves the problem (这个功能解决的问题)
we can change the value of input number in single hold click
### Expected API (期望的 API)
The element-plus team use this 'v-repeat-click' directive
```
 <span
  v-if="controls"
  v-repeat-click="increase"
  class="el-input-number__increase"
  role="button"
  :class="{ 'is-disabled': maxDisabled }"
  @keydown.enter="increase"
>
  <i :class="`el-icon-${controlsAtRight ? 'arrow-up' : 'plus'}`"></i>
</span>
```
https://github.com/element-plus/element-plus/blob/dev/packages/directives/repeat-click/index.ts

**Comment by Talljack** [comment]
Which demo in element?

**Comment by sondh0127** [comment]
> Which demo in element?
This one
https://element-plus.org/en-US/component/input-number.html

**Comment by Talljack** [comment]
> > Which demo in element?
> > This one
> > https://element-plus.org/en-US/component/input-number.html

I think you can be specific like https://element-plus.org/en-US/component/input-number.html#steps
