### ISSUE TITLE
Input 中的 show-count 可以考虑支持传入一个function来自定义显示字数统计逻辑

### ISSUE THREAD

**Issue by Adangs** [TuSimple/naive-ui#1314]
### This function solves the problem (这个功能解决的问题)
常用的案例：中文计1个长度，英文计0.5个长度；右下角还可以自定义组合文案展示内容
### Expected API (期望的 API)
无参考
但中英文区分计数在实际开发过程中很常见；
还有一些特殊场景，比如：[微笑]，计一个长度；

**Comment by 07akioni** [comment]
> ### This function solves the problem (这个功能解决的问题)
> 常用的案例：中文计1个长度，英文计0.5个长度；右下角还可以自定义组合文案展示内容
> 
> ### Expected API (期望的 API)
> 无参考 但中英文区分计数在实际开发过程中很常见； 还有一些特殊场景，比如：[微笑]，计一个长度；

我感觉很有道理，安排 @Talljack
