### ISSUE TITLE
n-upload 上传失败后点击重试，请求 body 中的 file 会变成 null

### ISSUE THREAD

**Issue by ManiaJack** [TuSimple/naive-ui#1316]
### TuSimple/naive-ui version (版本)
2.19.5

### Vue version (Vue 版本)
3.2.9

### Browser and its version (浏览器及其版本)
Chrome(94.0.4606.61)

### System and its version (系统及其版本)
Windows 10 Build 19043.1237

### Node version (Node 版本)
v14.15.2

### Reappearance link (重现链接)
https://codesandbox.io/s/broken-fast-sifhc?file=/src/App.vue

### Reappearance steps (重现步骤)
1. 向一个不存在的地址上传一个文件，文件会展示为失败状态。
2. 此时点击文件列表右侧的重试按钮，会重新发送请求。

### Expected results (期望的结果)
在点击重试后，请求正常携带原文件。

### Actual results (实际的结果)
在点击重试后，请求 body 中的 file 为 null。

### Remarks (补充说明)
第一次上传时服务出现问题，所以直接失败了，重启服务后点了重试，服务报错了，发现文件为 null

**Comment by 07akioni** [comment]
@Volankey
