### ISSUE TITLE
web-types.json 文件缺少slots声明

### ISSUE THREAD

**Issue by OneSeven** [TuSimple/naive-ui#1320]
### TuSimple/naive-ui version (版本)
2.19.6

### Vue version (Vue 版本)
3.2.20

### Browser and its version (浏览器及其版本)
chrome 94

### System and its version (系统及其版本)
windows10

### Reappearance link (重现链接)
https://codepen.io/

### Reappearance steps (重现步骤)
https://cdn.jsdelivr.net/npm/naive-ui@2.19.6/web-types.json 
导致webstorm无法识别插槽

### Expected results (期望的结果)
完事web-types文件补齐slots声明

### Actual results (实际的结果)
完事web-types文件补齐slots声明

**Comment by 07akioni** [comment]
这个目前缺少一个自动维护的手段，解决的动力不是很高

**Comment by 07akioni** [comment]
我会开着这个 issue，以后想办法弄弄

**Comment by 07akioni** [comment]
> > 我会开着这个 issue，以后想办法弄弄
> 
> element-plus好像是根据文档来生成的
> 
> [element-plus/element-plus@8adbd47](https://github.com/element-plus/element-plus/commit/8adbd4735b6d83e3cf92d8e6c50995228b0133d6)
> 
> 看下这个提交呢

这个想法有点意思，我考虑一下

**Comment by 07akioni** [comment]
> > > > 我会开着这个 issue，以后想办法弄弄
> > > 
> > > 
> > > element-plus好像是根据文档来生成的
> > > [element-plus/element-plus@8adbd47](https://github.com/element-plus/element-plus/commit/8adbd4735b6d83e3cf92d8e6c50995228b0133d6)
> > > 看下这个提交呢
> > 
> > 
> > 这个想法有点意思，我考虑一下
> 
> 大佬抓下紧啊 🔥

这没法着急啊，事情太多了😂

我觉得你有时间可以来个 PR
