### ISSUE TITLE
表单验证能否添加重置表单功能

### ISSUE THREAD

**Issue by Gitpingping** [TuSimple/naive-ui#1321]
### This function solves the problem (这个功能解决的问题)
部分场景如搜索条件较多时，经常需要清空搜索栏
### Expected API (期望的 API)
比如element-plus表单中的resetFields

**Comment by 07akioni** [comment]
你应该注意到了，所有需要验证的值都是你传给 Form 的，所以组件无法帮你清空所有值，如果你有需求的话可以非常简单的 deepClone 一个 model，然后重置的话把再 clone 一下赋值给 model

**Comment by zane0904** [comment]
清空表单值api是最基础的功能了，应该考虑加进来

**Comment by KYX1234** [comment]
我也觉得，想element ant这些都有api，而且表单又是高频操作，能有api最好，毕竟用组件就是为了省心

**Comment by Mylinaa** [comment]
我也觉得要加上去

**Comment by atvp** [comment]
新手用
```
const obj = {
user: {
    name: '',
    age: ''
  },
  phone: ''
}
const model = ref(obj)

const x = deepClone(model );

function reset(){
model.value = x
}
```
但是`obj`的值仍然会被覆盖，第一次重置可以，后面值就没有被重置了

**Comment by jiayafei** [comment]
我甚至后悔使用这个库了
