### ISSUE TITLE
NSelect prop fallback-option's better type hint

### ISSUE THREAD

**Issue by sigmarising** [TuSimple/naive-ui#1327]
### This function solves the problem (这个功能解决的问题)
Help make dev with vscode better.
### Expected API (期望的 API)
The [offical docs](https://www.naiveui.com/en-US/os-theme/components/select) show that fallback-option's type is `false | (value: string | number) => SelectOption`

![offical docs](https://user-images.githubusercontent.com/25470568/136802570-a8c47b9d-2bc8-4c93-a3ef-a6c93f4b2786.png)

But actually I found in .d.ts file is `(value: string | number) => false | SelectOption`, which made the vscode give me an type error when I put the false value into the prop.

![error of vscode](https://user-images.githubusercontent.com/25470568/136802676-fa30f4a6-5b2e-4aed-add3-268cbceb577f.png)

![detail error](https://user-images.githubusercontent.com/25470568/136802735-921303ee-f236-422e-9b58-c7a7404f44f2.png)

![.d.ts file](https://user-images.githubusercontent.com/25470568/136802811-d4070f7f-9da9-4ce0-91e5-750898696646.png)

However, even vscode give me this error, I can still compile my code and run it successfully.

**Comment by 07akioni** [comment]
This is a bug, I'll fix it.
