### ISSUE TITLE
n-input 组件的 input methods 再增加一个select 方法

### ISSUE THREAD

**Issue by xiangshaolong** [TuSimple/naive-ui#1328]
### This function solves the problem (这个功能解决的问题)
方便聚焦组件后直接选中全部内容
### Expected API (期望的 API)
n-input 组件的 input methods 再增加一个select 方法 方便聚焦组件后直接选中全部内容

**Comment by Talljack** [comment]
聚焦组件的方法可以用focus,focus有啥问题吗

**Comment by 07akioni** [comment]
> 聚焦组件的方法可以用focus,focus有啥问题吗

他的意思是全选
