### ISSUE TITLE
希望新增以下组件的一些方法

### ISSUE THREAD

**Issue by steel-li** [TuSimple/naive-ui#1333]
### This function solves the problem (这个功能解决的问题)
使用更加方便
### Expected API (期望的 API)
> 1、DataTable

1.1 `selection` 多选后可以有方法负责清空已选择列<br/>
1.2 `Action` 操作栏位可加入多个按钮，通过数组遍历展示，按钮挤在一起太难看<br/>
1.3 渲染 `DataTable` 时希望能够有默认的序号列，虽然通过代码也可渲染实现<br/>

> 2、Message，Dialog

2.1 希望 `Message`，`Dialog` 能够使用更加方便，下方的使用有些麻烦了。例如在 `axios` 拦截器中使用时。<br/>
我查看了 `naive-ui-admin` 代码，发现是需要将 `Message`，`Dialog` 注册成组件后挂载在单独的 `mount` 上才能使用。

以上是我个人的一些使用中的建议。

**Comment by wangzeyu-ym1120** [comment]
> 如果可以，请使用` setup，这两个组件在 setup 中使用更加方便。如果在请求过程中需要使用，可以同样将 HTTP Client 包装成 Hook，然后在请求的 Hook 中使用。

我想请教一下Message在setup中怎么更方便的使用呢，我还是没有得出结论。

**Comment by 07akioni** [comment]
> > 如果可以，请使用` setup，这两个组件在 setup 中使用更加方便。如果在请求过程中需要使用，可以同样将 HTTP Client 包装成 Hook，然后在请求的 Hook 中使用。
> 
> 我想请教一下Message在setup中怎么更方便的使用呢，我还是没有得出结论。

使用 useMessage，除此之外没有更方便的办法。
