### ISSUE TITLE
data-table fixed header and group header cannot work fine together

### ISSUE THREAD

**Issue by joanne3634** [TuSimple/naive-ui#1341]
### TuSimple/naive-ui version (版本)
2.19.7

### Vue version (Vue 版本)
3.2.20

### Browser and its version (浏览器及其版本)
Chrome 94.0.4606.54 (Official Build) (64-bit)

### System and its version (系统及其版本)
Ubuntu 94.0.4606.54 (Official Build) (64-bit)

### Reappearance link (重现链接)
https://codesandbox.io/s/spring-smoke-8zjkl

### Reappearance steps (重现步骤)
1. create group header with single header
2. set group header and single header all fixed left 

### Expected results (期望的结果)
the header set fixed: left should all stick in the left

### Actual results (实际的结果)
scroll to right, the fixed left header not working properly
![Screenshot from 2021-10-12 13-24-32](https://user-images.githubusercontent.com/7580346/137024570-30b53a43-b395-46d6-8bb5-2e67d8d70f5b.png)
![Screenshot from 2021-10-12 13-24-46](https://user-images.githubusercontent.com/7580346/137024568-b060770e-65ac-459b-8ebd-8638d7ef6b96.png)

**Comment by 07akioni** [comment]
@LYErin it's a bit more complex than you think. ref 37d7fc981b21d
