### ISSUE TITLE
NPopconfirm在最边上弹出的时候会被挡住

### ISSUE THREAD

**Issue by xcore-oss** [TuSimple/naive-ui#1344]
### TuSimple/naive-ui version (版本)
2.19.5

### Vue version (Vue 版本)
3.2.20

### Browser and its version (浏览器及其版本)
Edge(94.0.992.38)

### System and its version (系统及其版本)
Windows 11

### Reappearance link (重现链接)
https://codesandbox.io/s/exciting-pascal-so0rh?file=/src/Demo.vue

### Reappearance steps (重现步骤)
点击左边或右边的都可以看到被挡住

### Expected results (期望的结果)
自动判断是否超出显示范围调整到正确的位置或可以设置显示方向

### Actual results (实际的结果)
根据内容的位置居中显示

**Comment by vnues** [comment]
我咋感觉是target的位置问题
