### ISSUE TITLE
DataTable: virtual scroll and fixed column — visual bug with row (1px displacement) and border overlap

### ISSUE THREAD

**Issue by dzorogh** [TuSimple/naive-ui#1353]
### TuSimple/naive-ui version (版本)
2.19.7

### Vue version (Vue 版本)
3.2.20

### Browser and its version (浏览器及其版本)
Chrome(95.0.4638.32)

### System and its version (系统及其版本)
MacOS(11.5.2)

### Reappearance link (重现链接)
https://codesandbox.io/s/wyz0z

### Reappearance steps (重现步骤)
1) Use "virtual-scroll" on NDataTable 
2) Use "fixed" on one or more columns
3) Have some data in table, more data (more columns) or more slow rendering means more bugged rows
4) Scroll table vertically and make sure that virtual scroll work — some rows must be dynamically loaded.

It can be reproduced on example from docs https://www.naiveui.com/en-US/os-theme/components/data-table#virtual

### Expected results (期望的结果)
No visual bugs on scroll

### Actual results (实际的结果)

![Screen Recording 2021-10-13 at 18 24 31](https://user-images.githubusercontent.com/1428839/137168365-2308c303-96fa-47c0-a537-f8b73a6a311c.gif)

You see that some random rows in fixed column have bugged border, looks like cell is lower or higher by 1px.
If you hover that row - bug disappears.

### Remarks (补充说明)
If add fixed row height, then the bug does not appear.

**Comment by Dzorogh** [comment]
No, and zoom level doesn't affect that bug.
It is definitely Chrome bug, because in Safari 14.1.2 it works good.
