### ISSUE TITLE
虚拟表格，在移动端chrome浏览器下滚动时，表头会抖动

### ISSUE THREAD

**Issue by Leo-LL** [TuSimple/naive-ui#1378]
### TuSimple/naive-ui version (版本)
2.19.8

### Vue version (Vue 版本)
3.2.20

### Browser and its version (浏览器及其版本)
94

### System and its version (系统及其版本)
IOS15

### Reappearance link (重现链接)
https://codesandbox.io/s/gracious-sound-gc80e

### Reappearance steps (重现步骤)
1. 打开复现link，复制预览窗口的link
2. 将link在移动端打开。

### Expected results (期望的结果)
表头不抖动

### Actual results (实际的结果)
在表格中滚动时，表头会一直抖动

**Comment by 07akioni** [comment]
即时代码写的没问题，也不要对它有太高的期望

**Comment by 07akioni** [comment]
确实抖，但不计划修，safari 是新时代 IE
