### ISSUE TITLE
对话框组件在隐藏图标和标题的情况下，关闭按钮触发区变得非常小难以捕获

### ISSUE THREAD

**Issue by jack3018** [TuSimple/naive-ui#1381]
### TuSimple/naive-ui version (版本)
2.19.8

### Vue version (Vue 版本)
3.2.6

### Browser and its version (浏览器及其版本)
 94.0.4606.81 (x86_64)

### System and its version (系统及其版本)
macos(11.6)

### Reappearance link (重现链接)
https://codesandbox.io/s/dyuwb?file=/src/Demo.vue

### Reappearance steps (重现步骤)
<template>
  <n-space>
    <n-button @click="handleConfirm"> 警告 </n-button>
    
  </n-space>
</template>

<script>
import { defineComponent } from 'vue'
import { useMessage, useDialog } from 'naive-ui'

export default defineComponent({
  setup () {
    const message = useMessage()
    const dialog = useDialog()
    return {
      handleConfirm () {
        dialog.warning({
          //title: '警告',
          content: "有我在对话框关闭触发区就会变得非常小，很难捕获",
          closable: true,
          showIcon: false,
          maskClosable: false,
          positiveText: '确定',
          negativeText: '不确定',
        })
      }
    }
  }
})
</script>

### Expected results (期望的结果)
在隐藏对话框组件图标和标题的情况下，关闭按钮的触发区域仍然和关闭按钮保持一样大小。

### Actual results (实际的结果)
在隐藏对话框组件图标和标题的情况下，关闭按钮的触发区变得非常小，用鼠标很难定位关闭对话框。

**Comment by jack3018** [comment]
//DEMO文件代码：
<template>
  <n-space>
    <n-button @click="handleConfirm"> 警告 </n-button>
    
  </n-space>
</template>

<script>
import { defineComponent } from 'vue'
import { useMessage, useDialog } from 'naive-ui'

export default defineComponent({
  setup () {
    const message = useMessage()
    const dialog = useDialog()
    return {
      handleConfirm () {
        dialog.warning({
          //title: '警告',
          content: "有我在对话框关闭触发区就会变得非常小，很难捕获",
          closable: true,
          showIcon: false,
          maskClosable: false,
          positiveText: '确定',
          negativeText: '不确定',
        })
      }
    }
  }
})
</script>

**Comment by 07akioni** [comment]
下次直接改 codesandbox 的链接
