### ISSUE TITLE
模态框和抽屉组件关闭问题

### ISSUE THREAD

**Issue by batsx** [TuSimple/naive-ui#139]
### TuSimple/naive-ui version (版本)
2.11.11

### Vue version (Vue 版本)
3.1.1

### Browser and its version (浏览器及其版本)
Chrome 91.0.4472.106

### System and its version (系统及其版本)
Windows 10

### Reappearance link (重现链接)
https://codesandbox.io/s/75pnb

### Reappearance steps (重现步骤)
模态框或者抽屉组件打开时右上角没有关闭的小叉叉

### Expected results (期望的结果)
模态框或者抽屉组件打开后右上角那个小角落有一个小叉叉，以便mask-closable为false又没得其他操作时有个地方能关掉

### Actual results (实际的结果)
么得小叉叉

**Comment by 07akioni** [comment]
在 Modal 里面使用 card preset 有 closable 的属性。

**Comment by 07akioni** [comment]
Drawer 之后会加一个
