### ISSUE TITLE
ellipsis show tooltip bug

### ISSUE THREAD

**Issue by cwjTerrace** [TuSimple/naive-ui#1393]
### TuSimple/naive-ui version (版本)
2.19.9

### Vue version (Vue 版本)
3.2.20

### Browser and its version (浏览器及其版本)
Microsoft Edge 94.0.992.50

### System and its version (系统及其版本)
MacOS(11.6)

### Reappearance link (重现链接)
https://codesandbox.io/s/funny-swirles-f2m9e?file=/src/Demo.vue

### Reappearance steps (重现步骤)
<template>   
  <n-ellipsis style="width: 70px; font-family: 'Helvetica Neue'">     624748504   </n-ellipsis> 
</template>
文本省略字体换了之后，宽度正好可以放下，显示了省略号，但不显示tootip，感觉是浏览器的bug

### Expected results (期望的结果)
显示tooltip

### Actual results (实际的结果)
没有显示tooltip

**Comment by Volankey** [comment]
感觉还是和字体或者浏览器有关，我这没啥问题

**Comment by cwjTerrace** [comment]
offsetWidth可以通过getBoundingClientRect()获取，但是scrollWidth没找到办法

**Comment by 07akioni** [comment]
> offsetWidth可以通过getBoundingClientRect()获取，但是scrollWidth没找到办法

那这个我感觉不太好弄的样子

**Comment by 07akioni** [comment]
> going offscreen on ellipses. Any Fix? Please repl


> Popover is going offscreen on ellipses. Any Fix? Please reply in English. <img alt="Screenshot 2021-10-29 at 8 50 32 AM" width="1440" src="https://user-images.githubusercontent.com/21134455/139370569-78afc685-8f4d-489b-baf9-30a08ff77975.png">

Set style for tooltip:

```
 :tooltip="{ style: 'max-width: 100px;' }"
```

Sorry for late response, I've missed the notification.
