### ISSUE TITLE
date-picker component add others type

### ISSUE THREAD

**Issue by libbGit** [TuSimple/naive-ui#1402]
### This function solves the problem (这个功能解决的问题)
date-picker others type
### Expected API (期望的 API)
current  type:    ['date' | 'datetime' | 'daterange' |'datetimerange' |'month']
miss type:    ['year','season', 'week', 'yearrange', 'seasonrange', 'monthrange','weekrange']

Can you complete those miss type?  thx

**Comment by Talljack** [comment]
same #111
