### ISSUE TITLE
mouse wheel to scroll in chrome or edge results console error in Tabs 

### ISSUE THREAD

**Issue by zmtlwzy** [TuSimple/naive-ui#1413]
### TuSimple/naive-ui version (版本)
2.19.11

### Vue version (Vue 版本)
3.2.20

### Browser and its version (浏览器及其版本)
chrome edge latest

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://codesandbox.io/s/rwuit

### Reappearance steps (重现步骤)
![steps](https://user-images.githubusercontent.com/49909526/138234901-16d95c91-9595-42d1-bb18-b4c0d1773bc3.gif)

### Expected results (期望的结果)
no error

### Actual results (实际的结果)
Unable to preventDefault inside passive event listener invocation.

### Remarks (补充说明)
May be set { passive: false} in EventListener.

**Comment by 07akioni** [comment]
Fixed, you can remove lock-file and reinstall node_modules
