### ISSUE TITLE
Make `<NModal />` Draggable

### ISSUE THREAD

**Issue by richwxd** [TuSimple/naive-ui#1414]
### This function solves the problem (这个功能解决的问题)
As we know, multiple frameworks has good features for some scene, such as drag & drop a modal by clicking title, making max size in a frame. Could naiveui support them too? 
### Expected API (期望的 API)
Please see avuejs modal as a sample.

**Comment by ue360** [comment]
啥时候能加上这个功能不？迫切需要

**Comment by 07akioni** [comment]
> 啥时候能加上这个功能不？迫切需要

不在短期计划中，建议不要等这个

Not planned in short term

**Comment by ForeverSun** [comment]
关注中

**Comment by maddenBoy** [comment]
+1

**Comment by peter-brennan** [comment]
+1

**Comment by jahnli** [comment]
duplicate  https://github.com/tusen-ai/naive-ui/issues/2152
