### ISSUE TITLE
OnBeforeLeave For a modal component?

### ISSUE THREAD

**Issue by joo1es** [TuSimple/naive-ui#1424]
### This function solves the problem (这个功能解决的问题)
As showing a dialog before close the modal
### Expected API (期望的 API)
I have 2 ideas
1. onBeforeLeave prop, () => boolean | Promise\<boolean\>
if true, close the modal
if false, do nothing
2. Like dialog, onMaskClick prop

**Comment by thatsgolden** [comment]
> Use `on:update:show`
> 
> If show turns from `true` to `false`, it mean the modal is `before leave`.

`on:update:show` only triggers when close via `Esc` and `Mask Click`, but `Negative Click` or `Right-top corner close button`. and `onUpdateShow` is missing in DialogOptions Properties, it will not pass ts check.
