### ISSUE TITLE
select 结合tooltip使用，有错误

### ISSUE THREAD

**Issue by kexirong** [TuSimple/naive-ui#1436]
### TuSimple/naive-ui version (版本)
2.19.11

### Vue version (Vue 版本)
3.2.20

### Browser and its version (浏览器及其版本)
*

### System and its version (系统及其版本)
*

### Reappearance link (重现链接)
github.com
![image](https://user-images.githubusercontent.com/31177595/138694645-b515504c-a7b9-4a8f-8141-48038d659db7.png)

### Reappearance steps (重现步骤)
naive-ui 文档中的例子 存在相同问题，点击时下拉时会出现5条错误。

### Expected results (期望的结果)
naive-ui 文档中的例子 存在相同问题，点击时下拉时会出现5条错误。

### Actual results (实际的结果)
naive-ui 文档中的例子 存在相同问题，点击时下拉时会出现5条错误。

### Remarks (补充说明)
naive-ui 文档中的例子 存在相同问题，点击时下拉时会出现5条错误。

**Comment by nooooooom** [comment]
应该是 ResizeObserver 组件把 Tooltip 的占位注释节点给误判了导致的

**Comment by 07akioni** [comment]
> 应该是 ResizeObserver 组件把 Tooltip 的占位注释节点给误判了导致的

这个之前发现了 还没空修
