### ISSUE TITLE
Add 'search' event to AutoComplete same as Select 

### ISSUE THREAD

**Issue by etay2000** [TuSimple/naive-ui#1459]
### This function solves the problem (这个功能解决的问题)
Allows AutoComplete to be used for searching by providing a separate 'search' event. 
### Expected API (期望的 API)
Currently the 'update:value' is the only event provided, and it fires on both typing and selection. When trying to trigger a search based on the value being updated, selecting an option will cause the value to be updated again with the search result. This results in another search being performed using the search result value. A separate search event would allow a separation of those 2 actions.

**Comment by 07akioni** [comment]
> I'm trying to use it as a 'typeahead' component. When the input changes from user input an async search is performed. Currently the only way to listen to input changes is through the update value event. This works well for that purpose, however once a selection is made the same value property also gets updated again with the new selected option value. This causes an additonal unwanted search to be performed using the whole selected value. Being able to distinguish between input value changes (search) and value changes would prevent this.

Maybe try this?

```
const searchValueRef = ref('')

watch(searchValueRef, () => {
  // set ref to the same value won't fire the callback again
})
```

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
