### ISSUE TITLE
statistic enhancements - Support for numerical animation

### ISSUE THREAD

**Issue by jahnli** [TuSimple/naive-ui#1465]
### This function solves the problem (这个功能解决的问题)
Improve functions and enhance user experience
### Expected API (期望的 API)
1.Turn on numerical animation
2.add Countdown module

**Comment by Talljack** [comment]
like https://arco.design/vue/component/statistic

**Comment by Sepush** [comment]
I will give it a try

**Comment by Sepush** [comment]
can assign to me @07akioni
