### ISSUE TITLE
time picker enhancements - Customize the hours, minutes, and seconds to be displayed. 

### ISSUE THREAD

**Issue by jahnli** [TuSimple/naive-ui#1470]
### This function solves the problem (这个功能解决的问题)
Customize the hours, minutes, and seconds to be displayed.
### Expected API (期望的 API)
Customize the hours, minutes, and seconds to be displayed.

![image](https://user-images.githubusercontent.com/20943608/139200037-796cd467-2ba5-45c7-add3-672cf75754c4.png)

**Comment by 07akioni** [comment]
use12Hours is supported
