### ISSUE TITLE
Alert组件Text相关的主题配置属性无效

### ISSUE THREAD

**Issue by Gyang18** [TuSimple/naive-ui#1495]
### TuSimple/naive-ui version (版本)
2.20.0

### Vue version (Vue 版本)
3.2.7

### Browser and its version (浏览器及其版本)
 95.0.4638.54

### System and its version (系统及其版本)
Macos 10.15.7

### Node version (Node 版本)
14.18.1

### Reappearance link (重现链接)
https://codesandbox.io/s/priceless-noether-pgduj?file=/src/App.vue

### Reappearance steps (重现步骤)
Alert组件设置contentTextColorWarning、titleTextColorWarning 等文字颜色属性均未生效

### Expected results (期望的结果)
期望在不同的状态下展示不同的字体颜色

### Actual results (实际的结果)
设置相关的主题配置属性无效

### Remarks (补充说明)
https://www.naiveui.com/zh-CN/os-theme/components/alert，此页面就可以复现此问题

**Comment by 07akioni** [comment]
@Talljack

**Comment by Talljack** [comment]
demo跑步起来

**Comment by 07akioni** [comment]
> demo跑步起来

配一下试试就知道了

**Comment by Volankey** [comment]
文字 color 均没有使用对应类型的 color ,而是 contentTextColor, titleTextColor
