### ISSUE TITLE
希望部署一份静态的文档

### ISSUE THREAD

**Issue by fanmore** [TuSimple/naive-ui#1497]
### This function solves the problem (这个功能解决的问题)
希望加个静态文档分支，解决文档时常无法访问问题
### Expected API (期望的 API)
希望加一个静态文档的分支，方便下载、查阅，让更多的人使用

**Comment by Volankey** [comment]
https://naive-ui-9gl1vf6c742ac979-1256843205.ap-shanghai.app.tcloudbase.com/zh-CN/os-theme

**Comment by 07akioni** [comment]
> ### This function solves the problem (这个功能解决的问题)
> 希望加个静态文档分支，解决文档时常无法访问问题
> 
> ### Expected API (期望的 API)
> 希望加一个静态文档的分支，方便下载、查阅，让更多的人使用

直接拉 `clone` `pnpm install` `npm run build:site` 然后看 `site` 文件夹就好了
