### ISSUE TITLE
n-tabs mistake

### ISSUE THREAD

**Issue by dxyqn** [TuSimple/naive-ui#1502]
### TuSimple/naive-ui version (版本)
2.20.1

### Vue version (Vue 版本)
3.2.20

### Browser and its version (浏览器及其版本)
95.0.4638.54

### System and its version (系统及其版本)
windows 10

### Reappearance link (重现链接)
https://codesandbox.io/s/dxyqn-ybekq

### Reappearance steps (重现步骤)
please click the add button,you will look at the bug

### Expected results (期望的结果)
Initially there is more than one tab

### Actual results (实际的结果)
more than one tab display error
![image](https://user-images.githubusercontent.com/51109237/139781276-eb5cc397-b1f9-4635-a6f6-634f572b5a17.png)

**Comment by Talljack** [comment]
Maybe there is a problem with your usage.
![image](https://user-images.githubusercontent.com/34439652/139784592-9f57d292-5c04-4651-928c-cdce7bb0f7f1.png)
