### ISSUE TITLE
Customize Pagination's PageSizePicker text

### ISSUE THREAD

**Issue by joo1es** [TuSimple/naive-ui#1515]
### This function solves the problem (这个功能解决的问题)
Customize Pagination's PageSizePicker text
### Expected API (期望的 API)
show-size-picker: boolean | (size: number) => string

**Comment by kungege** [comment]
why not use `page-sizes` prop?

**Comment by joo1es** [comment]
> why not use `page-sizes` prop?

i need to change the text like '10 / page' to '10 per page'.
page-sizes is a prop to set which page-size can be selected.

**Comment by kungege** [comment]
> > why not use `page-sizes` prop?
> 
> i need to change the text like '10 / page' to '10 per page'. page-sizes is a prop to set which page-size can be selected. ![1](https://user-images.githubusercontent.com/76929557/140252654-0ecc661e-5ff9-4d80-8ba5-758c9dd339b6.png)

all right, i see.
