### ISSUE TITLE
How to verify the rule of a single form-item in the form?

### ISSUE THREAD

**Issue by kurisLei** [TuSimple/naive-ui#1524]
### This function solves the problem (这个功能解决的问题)
Need to verify the rule of a form-item in the form.Please give me some advice
### Expected API (期望的 API)
formRef.validate()

**Comment by Talljack** [comment]
Maybe you can use validate method of Form or FormItem.
![image](https://user-images.githubusercontent.com/34439652/140478651-b21ea841-c5cd-4ed1-98e1-2442c954899d.png)

**Comment by kurisLei** [comment]
Ok,got it,thank you.

**Comment by kurisLei** [comment]
> Maybe you can use validate method of Form or FormItem.
> ![image](https://user-images.githubusercontent.com/34439652/140478651-b21ea841-c5cd-4ed1-98e1-2442c954899d.png)

Ok,got it,thank you!
