### ISSUE TITLE
About supporting custom internationalized files

### ISSUE THREAD

**Issue by lu-cheng** [TuSimple/naive-ui#1525]
### This function solves the problem
custom internationalized files
### Expected API
Added support for internationalized files, or already supported, please add the documentation on how to use.
Of course, third-party components can also be used, but this will cause fragmentation in use.

**Comment by Talljack** [comment]
Maybe you can take a look at this.
https://www.naiveui.com/zh-CN/os-theme/docs/i18n

**Comment by lu-cheng** [comment]
@Talljack 自定义国际化文件,UI组件已经支持国际化了，能否将这个功能开放使用，还是写死的？使用第三方国际化组件会造成使用时UI自己国际化，其他代码自己国际化的碎片问题，可能是我忽略了什么，这文档哪里有写自定义国际化文件和自定义国际化文件怎样使用？我只在这个文档里看到了UI组件怎样国际化。

**Comment by Talljack** [comment]
嗯好像是文件内的 没有开放 @07akioni

**Comment by 07akioni** [comment]
> 嗯好像是文件内的 没有开放 @07akioni

把类型导出去然后写个文档吧

**Comment by Talljack** [comment]
> > 嗯好像是文件内的 没有开放 @07akioni
> 
> 把类型导出去然后写个文档吧，这个没啥不能开放的

你的意思是把这些i18n文件导出去吗，他想的是自定义国际化文件，而我们内部有自己定义的国际化文件

**Comment by 07akioni** [comment]
我来弄吧
