### ISSUE TITLE
a custom vnode between in n-grid 

### ISSUE THREAD

**Issue by AserJoker** [TuSimple/naive-ui#1526]
### This function solves the problem (这个功能解决的问题)
when I need render a form with schema, a custom component witch contains n-gi and render in n-grid is necessary
### Expected API (期望的 API)
///form.vue
<n-form>
<n-grid :x-gap=""24" :cols="24"> 
   <custom-component/>
</n-grid>
</n-form>

///custom-component.vue
<n-form-item-gi :span="8">
    <some-context/>
</n-form-item-gi/>

**Comment by Talljack** [comment]
same #1527
