### ISSUE TITLE
a custom vnode between in n-grid 

### ISSUE THREAD

**Issue by AserJoker** [TuSimple/naive-ui#1527]
### This function solves the problem (这个功能解决的问题)
when I need render a form with schema, a custom component witch contains n-gi and render in n-grid is necessary
### Expected API (期望的 API)
Form.ts:
h(NForm,{...},()=>h(NGrid,{...},()=>h(CustomFormItem)
CustomFormItem.ts:
h(NFormItemGi,{...},()=>h(....));

**Comment by 07akioni** [comment]
I haven't thought of an elegant way to do that.
