### ISSUE TITLE
Popconfirm 支持一下 header slot？

### ISSUE THREAD

**Issue by Adangs** [TuSimple/naive-ui#1528]
### This function solves the problem (这个功能解决的问题)
业务场景中还是比较需要一个标题的
### Expected API (期望的 API)
跟Popover header Slot 保持一致即可

**Comment by 07akioni** [comment]
🤔 非得要那个分割线吗？我感觉需要 confirm 的场景一般是不会做标题和内容的分割的

**Comment by Adangs** [comment]
> 🤔 非得要那个分割线吗？我感觉需要 confirm 的场景一般是不会做标题和内容的分割的

看来我只能去睡服产品了 [坏笑]

**Comment by 07akioni** [comment]
> > 🤔 非得要那个分割线吗？我感觉需要 confirm 的场景一般是不会做标题和内容的分割的
> 
> 看来我只能去睡服产品了 [坏笑]

我是没见到，要是有过类似的实践也不是不行

最差的情况可以用 popover 自己做
