### ISSUE TITLE
[naive/use-message]: No outer <n-message-provider /> founded

### ISSUE THREAD

**Issue by slowchen** [TuSimple/naive-ui#153]
新手请教<n-message-provider/>到底该怎么用
```vue
# App.vue
<template>
  <n-message-provider>
    <HelloWorld/>
  </n-message-provider>
</template>

<script setup>
import HelloWorld from './components/HelloWorld.vue';
</script>

<style>

</style>
```

```vue
# HelloWorld.vue
<template>

  <n-space>
    <n-button @click="info"> 信息 </n-button>
    <n-button @click="error"> 错误 </n-button>
    <n-button @click="warning"> 警告 </n-button>
    <n-button @click="success"> 成功 </n-button>
    <n-button @click="loading"> 加载中 </n-button>

  </n-space>
</template>

<script>
import { useMessage, NButton } from 'naive-ui'

export default {
  setup () {
    const message = useMessage()
    return {
      info () {
        message.info("I don't know why nobody told you how to unfold your love")
      },
      error () {
        message.error('Once upon a time you dressed so fine')
      },
      warning () {
        message.warning('How many roads must a man walk down')
      },
      success () {
        message.success(
          "'Cause you walked hand in hand With another man in my place"
        )
      },
      loading () {
        message.loading(
          'If I were you, I will realize that I love you more than any other guy'
        )
      }
    }
  }
}
</script>
```

F12 报错[naive/use-message]: No outer <n-message-provider /> founded，新手实在不知道<n-message-provider />该放哪，求指教

**Comment by ChenHaolinOlym** [comment]
import {NMessageProvider} from 'naive-ui'
in script

**Comment by mrerhuo** [comment]
靠，这效率太低了。非要这样搞，基本上写啥啊。我不想尝试了。

**Comment by waiylgeek** [comment]
I am facing the same issue and it seems I am blocked from using useMessage.

I have a master layout: 

`// MasterLayout.vue`
```
<template>
    <div class="mx-4">
       // ... lots of templating going on here...
        <slot></slot>
    </div>
</template>
```

All my pages are using MasterLayout

`// Dashboard.vue`
```
<template>
   <master-layout>
      <div>Dashboard content here...</div>
   </master-layout>
</template>
```

I have tried everything but nothing seems to be working.

I encapsulated the `<slot></slot>` with `<n-message-provider>` as follows 

```
//... inside MasterLayout.vue

...
<n-message-provider>
   <slot></slot>
</n-message-provider>
```

but still throws `No outer <n-message-provider />`

I encapsulated the whole `MasterLayout` with `<n-message-provider>` but with no success.

What shall I do in this case?

Thank you (amazing library but the way)

**Comment by 07akioni** [comment]
> I am facing the same issue and it seems I am blocked from using useMessage.
> 
> I have a master layout:
> 
> `// MasterLayout.vue`
> 
> ```
> <template>
>     <div class="mx-4">
>        // ... lots of templating going on here...
>         <slot></slot>
>     </div>
> </template>
> ```
> 
> All my pages are using MasterLayout
> 
> `// Dashboard.vue`
> 
> ```
> <template>
>    <master-layout>
>       <div>Dashboard content here...</div>
>    </master-layout>
> </template>
> ```
> 
> I have tried everything but nothing seems to be working.
> 
> I encapsulated the `<slot></slot>` with `<n-message-provider>` as follows
> 
> ```
> //... inside MasterLayout.vue
> 
> ...
> <n-message-provider>
>    <slot></slot>
> </n-message-provider>
> ```
> 
> but still throws `No outer <n-message-provider />`
> 
> I encapsulated the whole `MasterLayout` with `<n-message-provider>` but with no success.
> 
> What shall I do in this case?
> 
> Thank you (amazing library but the way)

`useMessage` must be used in a child component of `n-message-provider`. Use it in the same component won't work. Like this it won't work.

```
<template>
  <n-message-provider>...</n-message-provider>
</template>

<script>
...

const message = useMessage() // it won't work
</script>
```

You should make message provider in the parent component.

**Comment by 07akioni** [comment]
> I am facing the same issue and it seems I am blocked from using useMessage.
> 
> I have a master layout:
> 
> `// MasterLayout.vue`
> 
> ```
> <template>
>     <div class="mx-4">
>        // ... lots of templating going on here...
>         <slot></slot>
>     </div>
> </template>
> ```
> 
> All my pages are using MasterLayout
> 
> `// Dashboard.vue`
> 
> ```
> <template>
>    <master-layout>
>       <div>Dashboard content here...</div>
>    </master-layout>
> </template>
> ```
> 
> I have tried everything but nothing seems to be working.
> 
> I encapsulated the `<slot></slot>` with `<n-message-provider>` as follows
> 
> ```
> //... inside MasterLayout.vue
> 
> ...
> <n-message-provider>
>    <slot></slot>
> </n-message-provider>
> ```
> 
> but still throws `No outer <n-message-provider />`
> 
> I encapsulated the whole `MasterLayout` with `<n-message-provider>` but with no success.
> 
> What shall I do in this case?
> 
> Thank you (amazing library but the way)

`useMessage` must be used in a child component of `n-message-provider`. Use it in the same component won't work. Like this it won't work.

```
<template>
  <n-message-provider>...</n-message-provider>
</template>

<script>
...

const message = useMessage() // it won't work
</script>
```

You should make message provider in the parent component.

**Comment by waiylgeek** [comment]
Is there any way we can use it globally?

**Comment by 07akioni** [comment]
> Is there any way we can use it globally?

http://localhost:3000/en-US/os-theme/components/message#Use-Message-Outside-Setup

**Comment by JerryWang24** [comment]
直接劝退
