### ISSUE TITLE
能不能把内联style放到class里面，看着真累

### ISSUE THREAD

**Issue by libbGit** [TuSimple/naive-ui#1534]
### TuSimple/naive-ui version (版本)
2.20.2

### Vue version (Vue 版本)
3.2.21

### Browser and its version (浏览器及其版本)
Microsoft edge 95.0.1020.44

### System and its version (系统及其版本)
win11

### Reappearance link (重现链接)
https://github.com/TuSimple/naive-ui

### Reappearance steps (重现步骤)
no

### Expected results (期望的结果)
no

### Actual results (实际的结果)
no

### Remarks (补充说明)
no

**Comment by 07akioni** [comment]
做不到，每个组件的样式都可以独立配置，互不影响。

放入 class 的话我试过两种方法：

1. 把所有组件的 css-vars 都打入 body 之类的地方，性能太差
2. 只放 design token 在 body，那样的话对于样式的实现有限制，因为某些组件的变量值是由 js + design token 算出来的
