### ISSUE TITLE
数据表格选中行增加高亮以及单选行高亮

### ISSUE THREAD

**Issue by yanbowe** [TuSimple/naive-ui#1542]
### This function solves the problem (这个功能解决的问题)
可以很明显的看到自己选中了哪些行，现在row-props虽然可以实现行点击事件，但是也需要高亮选中的这一行，不然用户可能会忘记选中的行
### Expected API (期望的 API)
多选默认高亮选中行
单选：highlight-current-row

**Comment by yanbowe** [comment]
现在找到了替代方案，将row-props和rowClassName一起使用可以达到预期效果，不知道是否考虑增加api，如果不增加的话我就关闭此问题

**Comment by Talljack** [comment]
感觉没必要加

**Comment by 07akioni** [comment]
选中的逻辑是 checkbox 负责的，其他交互逻辑自己实现就好了

**Comment by yanbowe** [comment]
> 选中的逻辑是 checkbox 负责的，其他交互逻辑自己实现就好了

好的，感谢

**Comment by yanbowe** [comment]
贴个实现连接
https://codesandbox.io/s/agitated-wing-4wdrji?file=/src/Demo.vue

**Comment by wanbo0424** [comment]
> 贴个实现连接 https://codesandbox.io/s/agitated-wing-4wdrji?file=/src/Demo.vue

你这个也没实现效果啊
