### ISSUE TITLE
tabs 组件在可增加页签模式 横向左右滚动的时候报错

### ISSUE THREAD

**Issue by xiangshaolong** [TuSimple/naive-ui#1547]
### This function solves the problem (这个功能解决的问题)
目前看起来这个报错不影响功能 不知道是不是 bug
### Expected API (期望的 API)
Unable to preventDefault inside passive event listener invocation.
源码部分：
function handleWheel(e) {
            const preventYWheel = e.currentTarget.offsetWidth <
                e.currentTarget.scrollWidth;
            if (!preventYWheel || e.deltaY === 0)
                return;
            e.currentTarget.scrollLeft  = e.deltaY   e.deltaX;
            e.preventDefault(); // ==> 报错行
        }

**Comment by 07akioni** [comment]
是 naive 版本比较老吧？新版本好像修了

**Comment by Talljack** [comment]
如果是bug相关，请提bug issue，并提供复现

**Comment by 07akioni** [comment]
先关了，确定有问题再回复一下
