### ISSUE TITLE
可编辑的datatable

### ISSUE THREAD

**Issue by Gintoki-C** [TuSimple/naive-ui#1548]
### This function solves the problem (这个功能解决的问题)
可编辑
### Expected API (期望的 API)
可编辑的表格

[demo](https://codesandbox.io/s/sweet-bash-yd91y)
表格内的输入框绑定数据后无法编辑，请问有人知道要怎么解决吗？

**Comment by joo1es** [comment]
你要多绑定一个事件
onUpdate:value: e => row.name = e

**Comment by Gintoki-C** [comment]
> 你要多绑定一个事件 onUpdate:value: e => row.name = e

添加了change监听好像不起作用
[demo](https://codesandbox.io/s/sweet-bash-yd91y?file=/src/Demo.vue)

**Comment by joo1es** [comment]
> > 你要多绑定一个事件 onUpdate:value: e => row.name = e
> 
> 添加了change监听好像不起作用 [demo](https://codesandbox.io/s/sweet-bash-yd91y?file=/src/Demo.vue)

data 不是一个 ref，应该改成
data: ref(
  Array.apply(null, { length: 46 }).map((_, index) => ({
    key: index,
    name: `Edward King ${index}`,
    age: 32,
    address: `London, Park Lane no. ${index}`,
    name2: "",
    betaRef: null,
  }))
),

**Comment by Gintoki-C** [comment]
> > > 你要多绑定一个事件 onUpdate:value: e => row.name = e
> > 
> > 
> > 添加了change监听好像不起作用 [demo](https://codesandbox.io/s/sweet-bash-yd91y?file=/src/Demo.vue)
> 
> data 不是一个 ref，应该改成
> 
> ```
> data: ref(
>   Array.apply(null, { length: 46 }).map((_, index) => ({
>     key: index,
>     name: `Edward King ${index}`,
>     age: 32,
>     address: `London, Park Lane no. ${index}`,
>     name2: "",
>     betaRef: null,
>   }))
> ),
> ```


data 添加ref就可以用了，感谢感谢。
