### ISSUE TITLE
tree增加连接线显示，可以定制组件图标以及定制节点图标

### ISSUE THREAD

**Issue by yanbowe** [TuSimple/naive-ui#1551]
### This function solves the problem (这个功能解决的问题)
满足一些对树额外样式的需求
### Expected API (期望的 API)
tree增加连接线显示：showLine
定制组件图标：可通过插槽或者在树的TreeOption Properties 增加一个switcher-icon属性
定制节点图标：可通过插槽或者在树的TreeOption Properties 增加一个icon属性

**Comment by yanbowe** [comment]
可参考[arco design](https://arco.design/vue/component/tree#show-line)的树

**Comment by muchenfine** [comment]
+1

**Comment by 07akioni** [comment]
@Talljack switch-icon
