### ISSUE TITLE
Table新增Striped功能

### ISSUE THREAD

**Issue by Baiyuetribe** [TuSimple/naive-ui#1552]
### This function solves the problem (这个功能解决的问题)
增强表格的视觉展示效果
### Expected API (期望的 API)
类似bootstrap那样的Striped功能，使得表格明暗交替。
![image](https://user-images.githubusercontent.com/43716063/140964184-57d807bb-ceb3-4447-93c3-7844ce66dcac.png)

**Comment by 07akioni** [comment]
可以考虑一下，🤔

**Comment by Baiyuetribe** [comment]
看到dataTable已经完善了，希望普通的Table也支持下

**Comment by Baiyuetribe** [comment]
> 可以考虑一下，🤔

看到dataTable已经完善了，希望普通的Table也支持下

**Comment by 07akioni** [comment]
We need to implement striped prop for normal table

**Comment by JerryChan31** [comment]
I'll try. 😄

**Comment by jince-boy** [comment]
数据表格的情况下，我使用树形数据，striped就没办法显示了，这是什么原因呢？

<img width="281" height="507" alt="Image" src="https://github.com/user-attachments/assets/8280fbcf-6407-449b-ae97-3ef36e55ce85" />
