### ISSUE TITLE
Input enhancements - Supports other native input types

### ISSUE THREAD

**Issue by daofresh** [TuSimple/naive-ui#1553]
### This function solves the problem (这个功能解决的问题)
Use native input types (e.g. `tel`, `email` and `url`) to improve users' mobile typing experience
### Expected API (期望的 API)
```html
<n-input type="tel" />
```
or
```html
<n-input :input-props="{type: 'tel'}" />
```

**Comment by daofresh** [comment]
**ACTUAL BEHAVIOR**

![Screen Shot 2021-11-10 at 00 35 14](https://user-images.githubusercontent.com/5574919/140975869-972ac837-4c50-4e45-bacf-78e587d9b61b.png)

**Comment by Sepush** [comment]
we provide a prop called `input-props` for native props it's type is `HTMLInputAttributes` you can use it
see the doc https://www.naiveui.com/zh-CN/os-theme/components/input#API
![image](https://user-images.githubusercontent.com/39197136/141265235-0ce88af0-5f69-4bb7-a294-702c4a9e6b9f.png)

**Comment by Sepush** [comment]
I give it a try but I found there is a problem when we use `input-props="{type:'tel'}"` the type still `type:"text"` is the default value of props type
![image](https://user-images.githubusercontent.com/39197136/141267435-b40935fa-c5df-4165-bfa6-255c2cab5e07.png)


maybe we should filter it when we use `input-pops` 
What do you think of it? @07akioni

**Comment by 07akioni** [comment]
> I give it a try but I found there is a problem when we use `input-props="{type:'tel'}"` the type still `type:"text"` is the default value of props type ![image](https://user-images.githubusercontent.com/39197136/141267435-b40935fa-c5df-4165-bfa6-255c2cab5e07.png)
> 
> maybe we should filter it when we use `input-pops` What do you think of it? @07akioni

I think we can make it override the default type. However we should make caveat in API table about it.
