### ISSUE TITLE
NButton(circle) 与 NInput 放在flex-row的容器内，NButton(circle)内容如果不够撑起宽度，圆形会在高度方向被拉长

### ISSUE THREAD

**Issue by xby020** [TuSimple/naive-ui#1557]
### TuSimple/naive-ui version (版本)
2.20.2

### Vue version (Vue 版本)
3.2.21

### Browser and its version (浏览器及其版本)
Edge

### System and its version (系统及其版本)
Win 10

### Reappearance link (重现链接)
https://codesandbox.io/embed/clever-gwen-bhenb?fontsize=14&hidenavigation=1&theme=dark

### Reappearance steps (重现步骤)
1. 创建一个flex容器；
2. 把一个circle的button和input组件放一起；
3. button瘪了

### Expected results (期望的结果)
`<n-button circle></n-button>`应该在大部分情况下保持圆形

### Actual results (实际的结果)
`<n-button circle/>`在flex容器内与INPUT组件放在同一行，水平方向宽度减少。

**Comment by xby020** [comment]
![image](https://user-images.githubusercontent.com/26197465/141086758-a32e2154-30c2-4477-8649-d9a5aca8b25f.png)
像这样

**Comment by 07akioni** [comment]
@amadeus711  add `flex-shrink: 0` to button
