### ISSUE TITLE
Dialog component does not give focus to action button

### ISSUE THREAD

**Issue by cefiro** [TuSimple/naive-ui#1559]
### TuSimple/naive-ui version (版本)
2.20.2

### Vue version (Vue 版本)
3.2.21

### Browser and its version (浏览器及其版本)
Latest Chrome

### System and its version (系统及其版本)
ArchLinux

### Reappearance link (重现链接)
https://codesandbox.io/s/578sx

### Reappearance steps (重现步骤)
Opening a dialog and pressing the "Enter" key

### Expected results (期望的结果)
Closing dialogue pending

### Actual results (实际的结果)
New dialogues open

### Remarks (补充说明)
Watch in the video: https://webm.red/view/2CCD.webm

**Comment by 07akioni** [comment]
We will try to fix it

**Comment by Talljack** [comment]
@LYErin press Space key you need consider too.

**Comment by flyingTodream** [comment]
maybe you can try it without 'positive-text' and 'positive-text' props. @07akioni

**Comment by 07akioni** [comment]
> maybe you can try it without 'positive-text' and 'positive-text' props. @07akioni

See the new issue, I'll fix it soon.
