### ISSUE TITLE
Drawer组件能不能添加一个关闭前的回调函数?

### ISSUE THREAD

**Issue by pepsi1211** [TuSimple/naive-ui#1571]
### This function solves the problem (这个功能解决的问题)
解决了缺少一个关闭前没有回调的问题
### Expected API (期望的 API)
在做一些防误触的确认弹框时, 发现update:show的回调会直接关闭Drawer, 需要有一个关闭前的回调, 确认弹框完成之后再进行是否关闭的处理

**Comment by Talljack** [comment]
受控状态下你可以自己控制show值，触发update:value你可以执行一些回调再将show置为false

**Comment by wjw020206** [comment]
> 受控状态下你可以自己控制show值，触发update:value你可以执行一些回调再将show置为false

请问closable关闭的怎么控制，我这边尝试你说的方法，虽然能检测到show的值发生变化，但是还是关闭了抽屉
