### ISSUE TITLE
clearing an n-select with a default-value attribute 

### ISSUE THREAD

**Issue by rampall** [TuSimple/naive-ui#1577]
when clearing an n-select with a default-value attribute the value is set to `null` instead of the `default-value` attribute

**Comment by 07akioni** [comment]
> when clearing an n-select with a default-value attribute the value is set to `null` instead of the `default-value` attribute

The default value is not a value that can't be **cleared**, but just a default value.

What you mean is actually 'reset to default value'.

**Comment by 07akioni** [comment]
A possible solution is let `clearable` to accpet a value `"default"`, thus we can make select reset to default.
