### ISSUE TITLE
NDatePicker 希望可以配置默认时间

### ISSUE THREAD

**Issue by AustinQin** [TuSimple/naive-ui#1579]
### This function solves the problem (这个功能解决的问题)
选择日期时间范围时，每次选完日期还要去调时间，希望可以配置一个默认时刻如“['00:00:00', '23:59:59']"
### Expected API (期望的 API)
类似default-time="['00:00:00', '23:59:59']"

**Comment by 07akioni** [comment]
感觉有点道理，可以加上

**Comment by 07akioni** [comment]
加上了
