### ISSUE TITLE
change demos from kebab-case to PascalCase

### ISSUE THREAD

**Issue by xiaoxiangmoe** [TuSimple/naive-ui#16]
see https://vuejs.org/v2/style-guide/index.html#Component-name-casing-in-templates-strongly-recommended
 
> In most projects, component names should always be PascalCase in single-file components
> ...
> using kebab-case everywhere is also acceptable

It seems that it will be great if we change demo codes from from kebab-case to PascalCase

**Comment by 07akioni** [comment]
> see https://vuejs.org/v2/style-guide/index.html#Component-name-casing-in-templates-strongly-recommended
> 
> > In most projects, component names should always be PascalCase in single-file components
> > ...
> > using kebab-case everywhere is also acceptable
> 
> It seems that it will be great if we change demo codes from from kebab-case to PascalCase

This is vue 2's docs. Can you find a similar description in vue 3 docs?

Personally I don't think it's a big problem. Change all the demos will take a huge effort and the gain won't be large.

**Comment by xiaoxiangmoe** [comment]
> Can you find a similar description in vue 3 docs?

https://v3.vuejs.org/style-guide/#component-name-casing-in-templates-strongly-recommended
> In most projects, component names should always be PascalCase in single-file components


---

> Change all the demos will take a huge effort

I can create a PR to do this.

@07akioni

**Comment by 07akioni** [comment]
> > Can you find a similar description in vue 3 docs?
> 
> 
> 
> https://v3.vuejs.org/style-guide/#component-name-casing-in-templates-strongly-recommended
> 
> > In most projects, component names should always be PascalCase in single-file components
> 
> 
> 
> 
> 
> ---
> 
> 
> 
> > Change all the demos will take a huge effort
> 
> 
> 
> I can create a PR to do this.
> 
> 
> 
> @07akioni 
> 
> 

You can see in the picture the vue documented that use consistent kebab case is a good example. So there is no need for doing that.

**Comment by xiaoxiangmoe** [comment]
> Also note that if you've already invested heavily in kebab-case, consistency with HTML conventions and being able to use the same casing across all your projects may be more important than the advantages listed above. In those cases, using kebab-case everywhere is also acceptable.

"using kebab-case everywhere is also acceptable" means this is not prefer.  Evan You always use PascalCase in SFC.

**Comment by 07akioni** [comment]
> > Also note that if you've already invested heavily in kebab-case, consistency with HTML conventions and being able to use the same casing across all your projects may be more important than the advantages listed above. In those cases, using kebab-case everywhere is also acceptable.
> 
> "using kebab-case everywhere is also acceptable" means this is not prefer (but this is acceptable). Evan You always use PascalCase in SFC.
> 
> @07akioni

That's the reason why I think there's no need for changing it. 😂

I admit the advantages the docs said, but just let it be, I think it's acceptable.
