### ISSUE TITLE
当Space下面的子元素都被v-if掉之后，Space整体是否也不要进行渲染了？

### ISSUE THREAD

**Issue by Adangs** [TuSimple/naive-ui#1605]
### This function solves the problem (这个功能解决的问题)
比如表格操作列会使用多个Space配置多行多个操作按钮
当针对按钮添加上权限之后，有可能当前Space行下都被v-if隐藏掉了；
这个时候Space自带的一些样式就不是特别友好了；
### Expected API (期望的 API)
无参考

**Comment by Adangs** [comment]
这种情况下也是个问题。

![image](https://user-images.githubusercontent.com/5443355/142132543-684d84be-423f-46af-b816-b795b26928f3.png)
![image](https://user-images.githubusercontent.com/5443355/142132581-8a1bda45-a4f0-49a1-bd04-5689eb7a84b6.png)

**Comment by 07akioni** [comment]
合理

**Comment by 07akioni** [comment]
你是说每一个都被 v-if false 还是说仅存在一个元素

**Comment by Adangs** [comment]
> 你是说每一个都被 v-if false 还是说仅存在一个元素

两种情况
1、当某些被 v-if false 的时候
2、当所有的都被 v-if false 的时候

![image](https://user-images.githubusercontent.com/5443355/142342395-ce1bf04e-9dfe-4e4d-a1d1-8f307504227b.png)
![image](https://user-images.githubusercontent.com/5443355/142342588-1c60cce4-c825-47a5-a132-6efe5f2d0de8.png)

**Comment by Adangs** [comment]
> 你是说每一个都被 v-if false 还是说仅存在一个元素
经过再次尝试发现，
第一种情况，1、当某些被 v-if false 的时候
元素是会被隐藏的；

至于我上面为什么会出现不隐藏的情况；
是因为我return出来一个空字符串；当return出一个null的时候，就ok了；

![image](https://user-images.githubusercontent.com/5443355/142375262-86fd6d29-5055-4056-b978-dcd861d712d7.png)

**Comment by 07akioni** [comment]
> > 你是说每一个都被 v-if false 还是说仅存在一个元素
> 
> 两种情况 1、当某些被 v-if false 的时候 2、当所有的都被 v-if false 的时候
> 
> ![image](https://user-images.githubusercontent.com/5443355/142342395-ce1bf04e-9dfe-4e4d-a1d1-8f307504227b.png) ![image](https://user-images.githubusercontent.com/5443355/142342588-1c60cce4-c825-47a5-a132-6efe5f2d0de8.png)

1 是做不到的，没有办法在做到读取 children node 的时候还知道 children node 里面是什么，即使这个 children node 没有自己的 children
2 的话我觉得没问题，这就做
