### ISSUE TITLE
在data-table中用h函数渲染一个NPopselect并传入options会报错

### ISSUE THREAD

**Issue by YiFo0315** [TuSimple/naive-ui#1609]
![image](https://user-images.githubusercontent.com/80516655/142156021-fd142f1c-0d42-48c5-af7c-aa4af35fc1c5.png)
加入multiple、options prop都会报错
![image](https://user-images.githubusercontent.com/80516655/142156003-bb49fb06-ab5d-4be3-a2ba-b862912d8a4a.png)

### This function solves the problem (这个功能解决的问题)
希望提供一种传入options的方法

**Comment by Talljack** [comment]
![image](https://user-images.githubusercontent.com/34439652/142194673-47d5a02a-5d83-464d-a24a-053c35f393cf.png)
I tried it, and no error was reported. I think there is a problem with your writing.

**Comment by YiFo0315** [comment]
> ![image](https://user-images.githubusercontent.com/34439652/142194673-47d5a02a-5d83-464d-a24a-053c35f393cf.png) I tried it, and no error was reported. I think there is a problem with your writing.
![image](https://user-images.githubusercontent.com/80516655/142197019-f7859da3-002b-4e7a-8e24-2b3632eac134.png)

我这么写也不会报错，但是换成变量亦或者向里面加了数据之后就会报错
![image](https://user-images.githubusercontent.com/80516655/142197019-f7859da3-002b-4e7a-8e24-2b3632eac134.png)

**Comment by YiFo0315** [comment]
> ![image](https://user-images.githubusercontent.com/34439652/142194673-47d5a02a-5d83-464d-a24a-053c35f393cf.png) 我尝试了这样使用，并没有问题，应该是你的使用有问题

![image](https://user-images.githubusercontent.com/80516655/142197241-c6b53043-8d5e-4521-9dcf-d865b4df0615.png)
我这么写也不会报错，但是换成变量或者是解包，或者是向数组里面加了数据之后就会报错
![image](https://user-images.githubusercontent.com/80516655/142197324-a150742d-35f3-4dae-a98a-9f45feadba76.png)
![image](https://user-images.githubusercontent.com/80516655/142197388-ff64b4f7-eeb8-4119-bbf7-90d479871faf.png)

**Comment by 07akioni** [comment]
估计是你引入 h 的方法或者某些错误地方导入了的东西

**Comment by Talljack** [comment]
![image](https://user-images.githubusercontent.com/34439652/142396271-019ffeef-3e04-4158-8461-e2ffa8dd249f.png)
![image](https://user-images.githubusercontent.com/34439652/142396366-5d49844b-3788-4e76-8cab-2d4334bc3f1f.png)
不会啊　应该是你用法问题

**Comment by 07akioni** [comment]
给出一个明确的复现，我们可以重新打开这个 issue
