### ISSUE TITLE
按钮大小是否可以全局替换

### ISSUE THREAD

**Issue by JHeLiu** [TuSimple/naive-ui#1618]
### This function solves the problem (这个功能解决的问题)
按钮大小是否可以全局替换，目前默认的高34px有点太大了，我想改成32px，看useThemeVars 里面并没有可设置的
### Expected API (期望的 API)
全局设置 或者可以覆盖的公开变量

**Comment by Talljack** [comment]
![image](https://user-images.githubusercontent.com/34439652/142395429-8ad2eccf-b8ad-46c7-bbd7-3c913d36c13d.png)
你可以去改common变量中的对应尺寸的值

**Comment by 497983606** [comment]
是否可以提供一个全局配置上一个属性，类似element 的 size 配置，这样 input 和 button 等都会是默认的 small 或者 large

**Comment by 07akioni** [comment]
> 是否可以提供一个全局配置上一个属性，类似element 的 size 配置，这样 input 和 button 等都会是默认的 small 或者 large

暂时没有这个计划

**Comment by Tylrr123126** [comment]
我觉得这个是很重要的特性啊，为什么没有这个计划呢

**Comment by jahnli** [comment]
正常情况下项目使用都会二次封装下
