### ISSUE TITLE
Button can still be clicked in loading state  

### ISSUE THREAD

**Issue by muchenfine** [TuSimple/naive-ui#1628]
### TuSimple/naive-ui version (版本)
2.20.3

### Vue version (Vue 版本)
3.2.22

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
mac

### Node version (Node 版本)
16

### Reappearance link (重现链接)
https://codesandbox.io/api/v1/sandboxes/define

### Reappearance steps (重现步骤)
Button can still be clicked in loading state  

### Expected results (期望的结果)
I think it is not operable in the loading state

### Actual results (实际的结果)
Button can still be clicked in loading state

**Comment by amadeus711** [comment]
@07akioni

**Comment by ManiaJack** [comment]
同意啊，Loading 状态的按钮通常都是不允许再次被点击的

**Comment by 07akioni** [comment]
> 同意啊，Loading 状态的按钮通常都是不允许再次被点击的

目前计划在下个 minor 进行一个调整

**Comment by jahnli** [comment]
I think the same should be true of switch loading

**Comment by Sepush** [comment]
can be closed now

**Comment by Talljack** [comment]
> can be closed now

okay
