### ISSUE TITLE
为auto-complete添加类似select组件的render-option等功能

### ISSUE THREAD

**Issue by Rhilip** [TuSimple/naive-ui#1629]
### This function solves the problem (这个功能解决的问题)
在使用auto-complete组件作为输入框使用时，我们希望能为其渲染出不同的选项信息。
功能类似 Github或者豆瓣的搜索输入框，见
![Github](https://user-images.githubusercontent.com/13842140/142725004-ef32a006-25bb-44c1-b153-9f5734705c60.png)
![Douban](https://user-images.githubusercontent.com/13842140/142725013-aef4aa8d-a9cc-43af-97a9-581275850fee.png)

但直接使用 `[{label: () => h(), value: ''}]` 还是 `[{label: '', render: () => h(), value: ''}]` 都会出现意料外的情况
（鉴于我不太会用codepen，所以我建立了一个最小实现repo： https://github.com/Rhilip/bugreport-naiveui-autocomplete ，构建： https://rhilip.github.io/bugreport-naiveui-autocomplete/ ）

如实现例：
- 当使用 `[{label: () => h(), value: ''}]` 并点击时，v-model会被更新成 类似 `() => (0,vue__WEBPACK_IMPORTED_MODULE_0__.h)(naive_ui__WEBPACK_IMPORTED_MODULE_1__["default"], null, {default: () => valueRef1.value   v})` 的字符串
- 当使用 `[{label: '', render: () => h(), value: ''}]` 时，整个下拉选择框不能实现点击生效

![image](https://user-images.githubusercontent.com/13842140/142724985-72f05098-bcca-4280-8108-f7d5a4b0c4f6.png)

> update at 2021.11.20 PM19 : 
> 目前，配合使用  `[{label: () => h(), value: ''}]` 作为options以及auto-complete组件的`@select`、`clear-after-select` 等prop 以及hack的手法，基本实现了期望
> ![image](https://user-images.githubusercontent.com/13842140/142724972-e1d0efe2-6e1a-444e-95d1-56bd797b2f2a.png)

### Expected API (期望的 API)
能提供一种方式如slot，或者类似 select 组件的render-option等props，来支持对选项的自定义渲染

**Comment by 07akioni** [comment]
@Talljack 看看
