### ISSUE TITLE
Drawer component closable prop not rendering the close button

### ISSUE THREAD

**Issue by htmnk** [TuSimple/naive-ui#163]
### TuSimple/naive-ui version (版本)
2.11.12

### Vue version (Vue 版本)
3.1.1

### Browser and its version (浏览器及其版本)
Chrome(91.0.4472.101)

### System and its version (系统及其版本)
MacOS(11.4)

### Node version (Node 版本)
14.16.0

### Reappearance link (重现链接)
https://codesandbox.io/s/5t3ll

### Reappearance steps (重现步骤)
1. Create a simple closable drawer
2. Open the drawer

### Expected results (期望的结果)
The close button should be displayed and should close the drawer after click.

### Actual results (实际的结果)
The close button is not displayed.

### Remarks (补充说明)
It works as expected on the docs page here.
https://www.naiveui.com/en-US/os-theme/components/drawer

But not working on the demo code sandbox. I also tried it locally on 2.11.11 and the button is not rendered.

**Comment by 07akioni** [comment]
I'm not sure what happens with codesandbox. However after tried locally I fint it actually works.

This is your demo. Please refers to changelog and update to `2.11.12`.

![image](https://user-images.githubusercontent.com/18677354/122246947-8ea09800-cef9-11eb-883e-b81392d33564.png)
