### ISSUE TITLE
Tabs 与 router 组合使用时并不友好「 `Tabs` are not friendly when used in combination with `router` 」

### ISSUE THREAD

**Issue by Air-Cooled** [TuSimple/naive-ui#1630]
### This function solves the problem (这个功能解决的问题)
Tabs 的内容有时需要通过路由加载不同内容
例如 中后台 的页面标签功能，不知 Tabs 能否支持一下

The contents of `tabs` sometimes need to load different contents through routing,
For example, I wonder if `tabs` can support the page label function in the middle and background.
### Expected API (期望的 API)
期望 Tabs 可用于 中后台 的页面标签功能（与菜单类似，可切换路由页面）
还有Tabs的数量过多时，只能通过鼠标滚轮进行滚动，并无法添加左右滚动按钮
当我尝试使用 Tabs 作为页面标签时，Tabs 下方会出现一行空白内容
对了，还有 TabPane 右键菜单功能

It is expected that `tabs` can be used for the page label function in the middle and background (similar to the menu, you can switch the routing page);
In addition, when the number of `tabs` is too large, you can only scroll through the mouse wheel, and you cannot add left and right scroll buttons;
When I try to use `tabs` as a page label, a blank line appears below the `tabs`.
By the way, there is also the `tabpane` right-click menu function.
![image](https://user-images.githubusercontent.com/55440364/142722043-f4ec6f36-120d-44b0-95ca-454d48dbb31d.png)

**Comment by yanbowe** [comment]
可以参考下ant-design-vue 的tabs卡片式页签 https://next.antdv.com/components/tabs-cn/#Tabs-

**Comment by 07akioni** [comment]
I planned to add make tabs work without panel. That may solve some of you problems.

**Comment by Air-Cooled** [comment]
When there are too many 'tabs', I need to control the left and right scrolling buttons, and the activated' tab 'needs to be automatically visible.  Don't know if it can

**Comment by 07akioni** [comment]
What does
> the activated' tab 'needs to be automatically visible
mean?

**Comment by Air-Cooled** [comment]
当切换菜单时，`tabs`会在受控模式下随之改变，无则添加，存在则切换；在切换或添加时，我需要激活的`tab`它是可见的，而不会因`tabs`过多导致激活的`tab`被隐藏；用户是需要看到当前页面是哪一个`tab`的

**Comment by 07akioni** [comment]
> 当切换菜单时，`tabs`会在受控模式下随之改变，无则添加，存在则切换；在切换或添加时，我需要激活的`tab`它是可见的，而不会因`tabs`过多导致激活的`tab`被隐藏；用户是需要看到当前页面是哪一个`tab`的

Scroll into view automatically?

**Comment by Air-Cooled** [comment]
Yes, need to scroll into view automatically
Of course, when users need to switch 'tab', they also need to manually (button) control the scrolling view
The reason for requiring buttons is that the scroll wheel view may not be known to the user

**Comment by 07akioni** [comment]
> Yes, need to scroll into view automatically Of course, when users need to switch 'tab', they also need to manually (button) control the scrolling view The reason for requiring buttons is that the scroll wheel view may not be known to the user

We will try to solve it later.

**Comment by Air-Cooled** [comment]
When `tabs`is too numerous to display in its entirety, can configure arrow buttons for scrolling
