### ISSUE TITLE
关于数据表格的树形数据展示问题

### ISSUE THREAD

**Issue by AFK92** [TuSimple/naive-ui#1644]
### TuSimple/naive-ui version (版本)
2.21.0

### Vue version (Vue 版本)
3.2.22

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
windows

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/data-table#row-props

### Reappearance steps (重现步骤)
无

### Expected results (期望的结果)
按理来说数据（08akioni）属于数据（07akioni）的children，通过数据（07akioni）可以折叠控制数据（08akioni）的显示隐藏，但文档显示，数据（07akioni）的折叠并没有起作用，不知道是bug还是故意设计如此

### Actual results (实际的结果)
数据（07akioni）的折叠不起作用

**Comment by Talljack** [comment]
链接是这个吧 https://www.naiveui.com/zh-CN/os-theme/components/data-table#tree
