### ISSUE TITLE
否能增加一个Prop控制Image组件预览开关

### ISSUE THREAD

**Issue by Adangs** [TuSimple/naive-ui#1647]
### This function solves the problem (这个功能解决的问题)
1、当不想有预览时，目前好像只能使用Avatar或者原生img标签了
2、预览时的图片配置 max-height: 90vh; max-width: 90vw; 是否会更友好一些；当大图片时100vh 100vw太满了

### Expected API (期望的 API)
无

**Comment by 07akioni** [comment]
如果说不想预览的话为啥不用 img 元素？

**Comment by wuyu8512** [comment]
预览开关+1，此外我还想要固定长宽比，懒加载等功能

**Comment by 07akioni** [comment]
> 此外我还想要固定长宽比，懒

说的详细点？最好有个其他组件库的 demo

**Comment by wuyu8512** [comment]
> > 此外我还想要固定长宽比，懒
> 
> 说的详细点？最好有个其他组件库的 demo

https://vuetifyjs.com/zh-Hans/components/images/
用Intersection Observer实现延迟加载，有一个ratio属性可以控制图片有一个固定的长宽比，有个占位符显示加载中，另外这个组件是图片完全加载后一下子显示在页面上的，或许也可以来个属性控制一下？

**Comment by Adangs** [comment]
> 如果说不想预览的话为啥不用 img 元素？

Image组件应该可以再封装更深一些，

比如，
lazy-load
slot error
slot placeholder
@error 
@load

参考
https://developers.weixin.qq.com/miniprogram/dev/component/image.html
https://element.eleme.cn/#/zh-CN/component/image
