### ISSUE TITLE
NButton secondary, tertiary and quaternary are not working

### ISSUE THREAD

**Issue by Nictadel** [TuSimple/naive-ui#1652]
### TuSimple/naive-ui version (版本)
2.21.0

### Vue version (Vue 版本)
3.2.22

### Browser and its version (浏览器及其版本)
Chrome 89

### System and its version (系统及其版本)
macOS 11.2.3

### Node version (Node 版本)
v16.1.0

### Reappearance link (重现链接)
https://codesandbox.io/s/dp7oc (this is the codepen from the docs)

### Reappearance steps (重现步骤)
Open the codepen

### Expected results (期望的结果)
According to the docs, the buttons should have alternate styling because 'secondary' is defined on n-button like this:
<n-button secondary>Default</n-button>

### Actual results (实际的结果)
The button has the same appearance as the default button.

### Remarks (补充说明)
I have confirmed the same for secondary, tertiary, quaternary buttons.

**Comment by 07akioni** [comment]
![image](https://user-images.githubusercontent.com/18677354/142889641-811eafff-be17-4ca1-986f-54f128c8de5f.png)

I find it's okay.
