### ISSUE TITLE
[input-number]设置最小值后会干扰其他值输入

### ISSUE THREAD

**Issue by ue360** [TuSimple/naive-ui#1664]
### TuSimple/naive-ui version (版本)
2.21.1

### Vue version (Vue 版本)
3.2.22

### Browser and its version (浏览器及其版本)
any

### System and its version (系统及其版本)
any

### Reappearance link (重现链接)
https://codesandbox.io/s/gracious-snyder-vd6bs

### Reappearance steps (重现步骤)
设置min="50"，比如我想输入100，输入1的时候一直会跳成50

### Expected results (期望的结果)
正常输入

### Actual results (实际的结果)
干扰正常输入值

### Remarks (补充说明)
应该有个输入框失去焦点或者回车的动作里面去控制最大最小值判断
https://element-plus.gitee.io/zh-CN/component/input.html#input-%E4%BA%8B%E4%BB%B6

**Comment by Talljack** [comment]
我记得之前的设计就是这样的 不确定是不是需要改动 @07akioni

**Comment by ue360** [comment]
什么时候能修复这个问题呢？目前严重影响输入使用了

**Comment by 07akioni** [comment]
> [input-number]仅在输入框失去焦点或用户按下回车时触发 #1662

我看看哈
