### ISSUE TITLE
选择器/select组件 报错 ResizeObserver loop completed with undelivered notifications.

### ISSUE THREAD

**Issue by Satlantisy** [TuSimple/naive-ui#1671]
### TuSimple/naive-ui version (版本)
2.21.1

### Vue version (Vue 版本)
3.2.22

### Browser and its version (浏览器及其版本)
Safari 15.1

### System and its version (系统及其版本)
MacOS 12.0.1

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/select#render-person

### Reappearance steps (重现步骤)
// options会从API拉取数据加进去
const existTable = reactive({
  name: '',
  options: [] 
})

// template
<n-select 
          v-model:value="existTable.name" 
          :options="existTable.options" />

// Safari 控制台报错 ResizeObserver loop completed with undelivered notifications. Chrome无报错。
// 如果options不用reactive则无报错，其他正常。

### Expected results (期望的结果)
无报错

### Actual results (实际的结果)
Safari 控制台报错 ResizeObserver loop completed with undelivered notifications.

**Comment by 07akioni** [comment]
需要一个完整的复现，我没试出问题

**Comment by xujialiang** [comment]
> 需要一个完整的复现，我没试出问题

我也复现了。 

Safari浏览器  版本15.1 (17612.2.9.1.20) 
macOS Monterey 12.0.1

<img width="1824" alt="iShot2021-12-14 00 00 52" src="https://user-images.githubusercontent.com/1549351/145845809-d92093aa-58e5-4aca-b3d7-a868e7675a61.png">

**Comment by 07akioni** [comment]
具体是哪个 Demo

**Comment by xujialiang** [comment]
> 具体是哪个 Demo

https://www.naiveui.com/zh-CN/os-theme/components/select


<img width="1828" alt="iShot2021-12-14 14 37 27" src="https://user-images.githubusercontent.com/1549351/145945989-a29aea84-b822-4b6c-8651-f1188bd2e6cb.png">

**Comment by xiaoqingb** [comment]
@07akioni  problem still not be resolve

**Comment by xiaoqingb** [comment]
<script setup lang="ts">
import {ref} from 'vue'
import NSelect from 'naive-ui/es/select/src/Select.mjs';

const model = ref({
  selectValue: undefined,
});

const generalOptions = ref([
    {
      label: '1',
      value: 1,
      key: 'groode'
    },
    {
      label: '2',
      value: 2,
      key: 'veli'
    }
  ]);
</script>

<template>
  <NSelect v-model:value="model.selectValue" style="width: 240px" :options="generalOptions" />
</template>

<style>

.n-base-select-option {
  margin-bottom: 4px;
}
.main-content {
  max-width: 768px;
  margin: auto;
  .n-form {
    max-width: 558px;
    margin: auto;
  }
}
.avatar-icon {
  width: 1px;
  height: 20px;
  background: #d9dde1;
  border-radius: 0px 0px 0px 0px;
  opacity: 1;
}
</style>
