### ISSUE TITLE
日期时间选择器n-date-picker  type="daterange" 组件报错 vendor.17cd93bb.js:5 RangeError: Invalid time value

### ISSUE THREAD

**Issue by FgitYY** [TuSimple/naive-ui#1678]
### TuSimple/naive-ui version (版本)
2.21.1

### Vue version (Vue 版本)
3.2.6

### Browser and its version (浏览器及其版本)
96.0.4664.45

### System and its version (系统及其版本)
any

### Node version (Node 版本)
14.16.1

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/date-picker

### Reappearance steps (重现步骤)
设置n-date-picker  type="daterange" 点击组件弹窗 鼠标点击时分秒输入框 删除时分秒 控制台报错RangeError: Invalid time value；并且组件卡死无法操作

### Expected results (期望的结果)
删除无报错 正常可以操作

### Actual results (实际的结果)
控制台报错 组件卡死 无法操作

**Comment by Talljack** [comment]
第一daterange没有时分秒
第二官网没复现请给个demo复现

**Comment by FgitYY** [comment]
> 第一日期范围没有时分 第二官网没复现请给个演示复现
写错了 应该是datetimerange 类型   
截图了一个这个图片https://user-images.githubusercontent.com/58028358/143407057-3cc98d53-cced-4316-ba43-3404261d6c8f.png
随便一个都可以复现 点击输入框 弹窗出来的选择器 删除随便一个时分秒 就可复现
https://user-images.githubusercontent.com/58028358/143407409-befb14ac-d311-4426-9a5e-71d7059d3eb7.png

**Comment by Talljack** [comment]
![image](https://user-images.githubusercontent.com/34439652/143408353-bac0cbc8-0ce4-4261-b826-2d12409b553a.png)
还是没复现
你还是去https://codesandbox.io/s/h0qdp来个复现

**Comment by FgitYY** [comment]
> 

https://codesandbox.io/s/sparkling-dew-381yl?file=/src/Demo.vue  
需要删除时分秒
![image](https://user-images.githubusercontent.com/58028358/143409400-3fc82856-da24-4454-b8a4-ff36aa85441e.png)

**Comment by Talljack** [comment]
> > 
> 
> https://codesandbox.io/s/sparkling-dew-381yl?file=/src/Demo.vue 需要删除时分秒 ![image](https://user-images.githubusercontent.com/58028358/143409400-3fc82856-da24-4454-b8a4-ff36aa85441e.png)

OK
