### ISSUE TITLE
when build, ts error TS4032: 'LoadingBarInst'  cannot be named

### ISSUE THREAD

**Issue by liuzw2579** [TuSimple/naive-ui#1679]
### This function solves the problem (这个功能解决的问题)
Exported variable '_sfc_main' has or is using name 'LoadingBarInst' from external module "D:/WorkSpace/ithinkdt-cloud/ithinkdt-frame-front/node_modules/naive-ui/lib/loading-bar/src/LoadingBarProvider" but cannot be named.
### Expected API (期望的 API)
fix it

**Comment by 07akioni** [comment]
给个复现吧，看这个我真猜不出来

**Comment by Talljack** [comment]
先关闭，提供复现后将重新打开
