### ISSUE TITLE
click radio button fire event twice

### ISSUE THREAD

**Issue by coader** [TuSimple/naive-ui#1680]
### TuSimple/naive-ui version (版本)
2.21.1

### Vue version (Vue 版本)
3.2.22

### Browser and its version (浏览器及其版本)
Chrome 90

### System and its version (系统及其版本)
Win10

### Reappearance link (重现链接)
https://codesandbox.io/s/crazy-hertz-y8vux

### Reappearance steps (重现步骤)
click radio button

### Expected results (期望的结果)
fire once

### Actual results (实际的结果)
fire twice

**Comment by 07akioni** [comment]
@amadeus711 就用 stopPropagation 解决吧，感觉没啥特别好的办法

**Comment by 07akioni** [comment]
或者你有时间参考一下 rc-checkbox 做了什么事，我估计他们也得处理这个问题
