### ISSUE TITLE
颜色组件（color picker）不能接受单词的颜色输入 如 white blue，作为初始值

### ISSUE THREAD

**Issue by xiangshaolong** [TuSimple/naive-ui#1683]
### This function solves the problem (这个功能解决的问题)
颜色组件不能接受单词的颜色输入 如 white blue，作为初始值
### Expected API (期望的 API)
颜色组件不能接受单词的颜色输入 如 white blue，作为初始值

**Comment by rico0808** [comment]
#fff 不想吗？

**Comment by xiangshaolong** [comment]
不够香，哈哈

**Comment by nooooooom** [comment]
输入处可以丢在 `HEX` 类型的输入框上，内部在色板上其实有对于文字颜色类型的处理，看看作者觉得必不必要

**Comment by 07akioni** [comment]
这个功能没那么必要，面向程序员这个转化不用在这做，整个库凑活一下。面向用户的话，用户不理解什么是红色。

**Comment by 07akioni** [comment]
在文档里面提供了一个方案，可供未来参考 696315f1c2792f1ae2dac9c4d244338807cb9765
