### ISSUE TITLE
td-color-hover should be darker than td-color-striped

### ISSUE THREAD

**Issue by ouuan** [TuSimple/naive-ui#1686]
### TuSimple/naive-ui version (版本)
2.21.1

### Vue version (Vue 版本)
3.2.23

### Browser and its version (浏览器及其版本)
Mozilla Firefox 94.0.2

### System and its version (系统及其版本)
Arch Linux 5.15.4-zen1-1-zen

### Reappearance link (重现链接)
https://codesandbox.io/s/naive-ui-td-color-hovered-demo-rgppd?file=/src/App.vue

### Reappearance steps (重现步骤)
Create a data table with the `striped` option

### Expected results (期望的结果)
`td-color-hover` should be darker than `td-color-striped`

### Actual results (实际的结果)
`td-color-hover` is the same as `td-color-striped`

**Comment by Talljack** [comment]
变量颜色重新定义下 @07akioni
