### ISSUE TITLE
首次无法安装

### ISSUE THREAD

**Issue by kavinluo** [TuSimple/naive-ui#1693]
### This function solves the problem (这个功能解决的问题)
当我的node版本默认是 8.11.4  我执行 yarn add naive-ui
我怎么切换node 版本都下载不了
 yarn add naive-ui
yarn add v1.17.3
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error @babel/eslint-parser@7.16.3: The engine "node" is incompatible with this module. Expected version "^10.13.0 || ^12.13.0 || >=14.0.0". Got "8.11.4"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
❯ nvm use 10.13.0
Now using node v10.13.0 (npm v6.4.1)
❯ yarn add naive-ui
yarn add v1.17.3
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error highlight.js@11.3.1: The engine "node" is incompatible with this module. Expected version ">=12.0.0". Got "10.13.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
❯ nvm use 12.0.0
Now using node v12.0.0 (npm v6.9.0)
❯ yarn add naive-ui
yarn add v1.17.3
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error @babel/eslint-parser@7.16.3: The engine "node" is incompatible with this module. Expected version "^10.13.0 || ^12.13.0 || >=14.0.0". Got "12.0.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
❯ nvm use 12.13.0
N/A: version "12.13.0 -> N/A" is not yet installed.

You need to run "nvm install 12.13.0" to install it before using it.
❯ nvm use 14.0.0
Now using node v14.0.0 (npm v6.14.4)
❯ yarn add naive-ui
yarn add v1.17.3
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error jest-diff@27.3.1: The engine "node" is incompatible with this module. Expected version "^10.13.0 || ^12.13.0 || ^14.15.0 || >=15.0.0". Got "14.0.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

### Expected API (期望的 API)
希望能正常安装

**Comment by Talljack** [comment]
node升级到15+试试

**Comment by 07akioni** [comment]
@kavinluo 首先是你的 node 版本太低了，应该升级一下，很多库已经只支持 12+。

另外就是我的一个 dep 写错了，应该写到 dev deps，这个会修改掉。

**Comment by 07akioni** [comment]
ref 5b10f8
