### ISSUE TITLE
n-tag dark模式下添加背景色

### ISSUE THREAD

**Issue by afocus** [TuSimple/naive-ui#1699]
### This function solves the problem (这个功能解决的问题)
当使用属性bordered=false时 显示更友好
### Expected API (期望的 API)
无

**Comment by 07akioni** [comment]
没理解，是说啥意思？

**Comment by afocus** [comment]
darktheme下 tag 如果使用bordered的属性置为false 则只有文字颜色  没有背景底色

**Comment by 07akioni** [comment]
OK，会研究一下

**Comment by 07akioni** [comment]
下个版本会加上
