### ISSUE TITLE
select component in multiple mode with other component in one line expand abnormally

### ISSUE THREAD

**Issue by joanne3634** [TuSimple/naive-ui#170]
### TuSimple/naive-ui version (版本)
2.12.0

### Vue version (Vue 版本)
3.1.1

### Browser and its version (浏览器及其版本)
Version 89.0.4389.90 (Official Build) (64-bit)

### System and its version (系统及其版本)
Ubuntu 18.04.5 LTS

### Reappearance link (重现链接)
https://codesandbox.io/s/hopeful-bell-szkk7

### Reappearance steps (重现步骤)
select one option in the first selection component

### Expected results (期望的结果)
the container should only expand with the input size that the selected value has changed line.

### Actual results (实际的结果)
the container expanded when the input isn't.

**Comment by joanne3634** [comment]
<img width="357" alt="Screen Shot 2021-06-11 at 11 55 53 AM" src="https://user-images.githubusercontent.com/7580346/122324809-4922a180-cede-11eb-81bf-3088e355e9ee.png">

**Comment by joanne3634** [comment]
![Screenshot from 2021-06-16 20-07-30](https://user-images.githubusercontent.com/7580346/122324901-7707e600-cede-11eb-8f07-e66ea599299f.png)

**Comment by 07akioni** [comment]
Set `display: inline-flex;` on `n-select` & `align-self: stretch` on multiple `n-base-selection`. Please create a PR.

**Comment by Talljack** [comment]
If we fix it, it will affect the performance of multiple choices in the flex container，you can add styles if needed.
