### ISSUE TITLE
n-switch 希望支持active-color/inactive-color

### ISSUE THREAD

**Issue by bzw1204** [TuSimple/naive-ui#1718]
### This function solves the problem (这个功能解决的问题)
希望 n-switch组件支持自定义选中和非选中的颜色

### Expected API (期望的 API)
active-color	switch 打开时的背景色	string	—	#409EFF
inactive-color	switch 关闭时的背景色	string	—	#C0CCDA

**Comment by Talljack** [comment]
为啥都放一个pr里面 @2277419213

**Comment by 2277419213** [comment]
> 为啥都放一个pr里面 @2277419213

忘记切分支了，一提交pr就自己更新过来了

**Comment by 07akioni** [comment]
closed in #1714
