### ISSUE TITLE
Pagenation component 

### ISSUE THREAD

**Issue by sunlifei1** [TuSimple/naive-ui#172]
### This function solves the problem (这个功能解决的问题)
The pagination component lacks the function of returning to the first page and the last page, so it is expected to be added as a configurable item

### Expected API (期望的 API)
<n-pagination  firstEndIsShow />
firstEndIsShow controls whether the button to return to the end of the first page is displayed

**Comment by 07akioni** [comment]
First page & last page is always shown.

![image](https://user-images.githubusercontent.com/18677354/122357071-fa304700-cf85-11eb-9438-dd1f9f29c5d8.png)
