### ISSUE TITLE
Select组件使用show受控之后，启用了多选（multiple）的 filterable 功能失效

### ISSUE THREAD

**Issue by conanliuhuan** [TuSimple/naive-ui#1723]
### TuSimple/naive-ui version (版本)
2.21.2

### Vue version (Vue 版本)
3.2.23

### Browser and its version (浏览器及其版本)
Any

### System and its version (系统及其版本)
Any

### Reappearance link (重现链接)
https://codesandbox.io/s/goofy-ritchie-bjz2g?file=/src/Demo.vue

### Reappearance steps (重现步骤)
1、在组件中启用filterable
2、在组件中启用multiple
3、使用show控制Select下拉列表是否显示
4、在input中尝试输入内容，无法正常输入

### Expected results (期望的结果)
filterable功能正常

### Actual results (实际的结果)
filterable功能失效

**Comment by 07akioni** [comment]
这个问题最终的解决方案：
1. show = false 的时候，我们只认为开启了 tag 选项是可以正常使用的，就是说作为创建 tag 的一个手段
2. 为什么不计划对普通的选项生效。是因为用户看不到，所以搜索也不存在意义，至少在大多数情况下这是没用的
