### ISSUE TITLE
Select组件使用show控制下拉列表收起，然而select仍然是focus的外观状态

### ISSUE THREAD

**Issue by conanliuhuan** [TuSimple/naive-ui#1724]
### TuSimple/naive-ui version (版本)
2.21.2

### Vue version (Vue 版本)
3.2.23

### Browser and its version (浏览器及其版本)
Any

### System and its version (系统及其版本)
Any

### Reappearance link (重现链接)
https://codesandbox.io/s/hardcore-glade-bzwgk?file=/src/Demo.vue

### Reappearance steps (重现步骤)
1、Select组件使用show控制是否显示，同时使用focus事件，将show设为true
2、在show为true的情况下，不使用blur事件，而是用其它方法将show设为false（例如点击操作插槽中的按钮）

### Expected results (期望的结果)
期望show为false后，Select状态变成被blur后的正常状态

### Actual results (实际的结果)
实际上虽然下拉列表被关闭，然而Select输入框仍然是有颜色的，好像是被focus一样

**Comment by 07akioni** [comment]
看起来不能复现

**Comment by conanliuhuan** [comment]
> 看起来不能复现

只是外观会有一个绿色包裹而已。并没什么影响。倒不如加一个手动触发blur的方法

**Comment by JerryChan31** [comment]
https://user-images.githubusercontent.com/14790315/144568429-6340becb-ec15-4488-902e-6cb4d40a792e.mov

看起来没有绿色包裹的情况出现

**Comment by CherryRum** [comment]
![ScreenGif](https://user-images.githubusercontent.com/24296698/145033398-eac990c1-8fe8-4713-9120-73d9ca87fd1a.gif)
看起来没有

**Comment by conanliuhuan** [comment]
https://user-images.githubusercontent.com/26618275/145130263-4ffc24f2-e70a-4dfb-b0b6-832eed15e7f5.mp4

Win10,firefox，点击取消后，绿色框还在

**Comment by conanliuhuan** [comment]
厄，tim截屏的视频firefox上传之后居然看不了 - -b
算了，这个不管吧，我自己另外搞个组件去实现它
