### ISSUE TITLE
NSwitch 创建轨道样式API 调整建议

### ISSUE THREAD

**Issue by bzw1204** [TuSimple/naive-ui#1732]
### This function solves the problem (这个功能解决的问题)
首先，感谢大佬的辛苦付出，上次提出希望支持NSwitch的轨道颜色自定义，此次更新已收到！但是想问下大佬提供的API 只能以此次更新的这种函数式的方式提供吗？能否提供简单的两个属性去更改呢，个人感觉提供的API不是很方便也不容易维护
### Expected API (期望的 API)
打开背景颜色属性
关闭背景颜色属性
![image](https://user-images.githubusercontent.com/9693637/144531184-188662ac-14d8-4ee7-a7b1-f7a0a15b5635.png)
![image](https://user-images.githubusercontent.com/9693637/144530851-ab581ea2-cbfb-4868-9c1a-98c304cbd64d.png)

**Comment by 07akioni** [comment]
> ### This function solves the problem (这个功能解决的问题)
> 首先，感谢大佬的辛苦付出，上次提出希望支持NSwitch的轨道颜色自定义，此次更新已收到！但是想问下大佬提供的API 只能以此次更新的这种函数式的方式提供吗？能否提供简单的两个属性去更改呢，个人感觉提供的API不是很方便也不容易维护
> 
> ### Expected API (期望的 API)
> 打开背景颜色属性 关闭背景颜色属性 ![image](https://user-images.githubusercontent.com/9693637/144531184-188662ac-14d8-4ee7-a7b1-f7a0a15b5635.png) ![image](https://user-images.githubusercontent.com/9693637/144530851-ab581ea2-cbfb-4868-9c1a-98c304cbd64d.png)

BoxShadow 怎么办，我觉得不能遇到一个加一个，他们这个没问题是因为没有 box-shadow

**Comment by 07akioni** [comment]
好不好维护的对于这么简单的 case 是个伪命题，要么你自己封装一个符合自己场景的组件，要么抽一个公用的函数

**Comment by 07akioni** [comment]
一般来说当功能不能满足需求的情况下，我会对易用性做一些让步

**Comment by bzw1204** [comment]
是否可以把box-shadow单独领出来属性

**Comment by 07akioni** [comment]
> 是否可以把box-shadow单独领出来属性

这就会把本来用对象做的东西打平了，我觉得这样问题还是比较大

**Comment by bzw1204** [comment]
> > 是否可以把box-shadow单独领出来属性
> 
> 这就会把本来用对象做的东西打平了，我觉得这样问题还是比较大
> 
> 说白了我们很难处理每一种对样式的需求，这也是为什么 popover 没有提供 max-width 或者 min-width 这种 API（曾经有过，被我 deprecated 了），他们是更大范畴下的一些子属性
> 
> 作为一个库，我们需要在易用性、可维护性、功能性上做一个权衡，不存在十全十美的方案
> 
> naive 的价值观是尽量提供“能力”，而不是特别具体的属性

好吧，明白了

**Comment by 07akioni** [comment]
> > > 是否可以把box-shadow单独领出来属性
> > 
> > 
> > 这就会把本来用对象做的东西打平了，我觉得这样问题还是比较大
> > 说白了我们很难处理每一种对样式的需求，这也是为什么 popover 没有提供 max-width 或者 min-width 这种 API（曾经有过，被我 deprecated 了），他们是更大范畴下的一些子属性
> > 作为一个库，我们需要在易用性、可维护性、功能性上做一个权衡，不存在十全十美的方案
> > naive 的价值观是尽量提供“能力”，而不是特别具体的属性
> 
> 好吧，明白了

不是说这样就是最好的，我也知道写起来更麻烦。不同的人可能价值取向不同，只是恰好你用的这个库在这块和你的取向有些差别
