### ISSUE TITLE
Enhance date picker so that its user friendly

### ISSUE THREAD

**Issue by BroJenuel** [TuSimple/naive-ui#1733]
### This function solves the problem (这个功能解决的问题)
The problem is there is no shortcut for selecting year. This is for reference -> https://element-plus.org/en-US/component/date-picker.html#enter-date

Its a lot easier for users to select year and month, because currently I have to click multiple times just to find the year or month.

If we can add this in our date picker, it would be awesome.

example:
![date](https://user-images.githubusercontent.com/31676163/144532460-3a3e2076-aa4e-4be0-8214-813a0735202e.png)

After Clicking the year I would able to select what year.
![select year](https://user-images.githubusercontent.com/31676163/144532912-44784166-8385-481b-8228-e90798410f41.png)

Same thing as the month
![select month](https://user-images.githubusercontent.com/31676163/144532936-d17481e7-c76e-46ff-ade8-1aedc4105c31.png)

### Expected API (期望的 API)
maybe add a props, and much better a default

**Comment by Talljack** [comment]
![image](https://user-images.githubusercontent.com/34439652/144535306-0524ced5-1b32-4b76-9297-bc434ca98722.png)
![image](https://user-images.githubusercontent.com/34439652/144535464-5e0c6ba0-10ee-464f-8a32-78939268e395.png)
You can also customize shortcuts for year and month, you can try.

**Comment by Talljack** [comment]
Maybe I need to add the year and month documents.

**Comment by BroJenuel** [comment]
@Talljack That would be awesome 👍👍
