### ISSUE TITLE
求一个虚拟滚动组件

### ISSUE THREAD

**Issue by conanliuhuan** [TuSimple/naive-ui#1737]
### This function solves the problem (这个功能解决的问题)
自己在渲染大量数据列表的时候也有虚拟滚动的需求。希望可以将naive-ui封装好的虚拟滚动组件公开出来。
有n-scrollbar的滚动条更好看~
么么哒，跪等~(づ￣ 3￣)づ
### Expected API (期望的 API)
这个问题由大大决定咯🌹

**Comment by 07akioni** [comment]
Planned, with low priority

**Comment by conanliuhuan** [comment]
仅用了一点点代码，把n-data-table改造封装成了一个虚拟滚动，暂时不需要了

**Comment by songispm** [comment]
需要列表的虚拟滚动，虽然我可以安装 vueuc，但是既然tree和table、select都支持了

希望List组件、timeline组件也可以支持

**Comment by songispm** [comment]
那么 naiveUI 就是虚拟化利用的最好的组件库了

而且希望列表的虚拟化，可以支持 window scroll 或指定具体某个 scroll 容器，而不只是滚动条在虚拟组件自身
