### ISSUE TITLE
Naive-Ui 有数据驱动的表格吗

### ISSUE THREAD

**Issue by zhangle1** [TuSimple/naive-ui#1738]
### This function solves the problem (这个功能解决的问题)
类似ant-pro-table 那种 数据驱动的表格 
https://procomponents.ant.design/components/table/?current=1&pageSize=5
### Expected API (期望的 API)
request 
获取数据的api
(params?: {pageSize,current},sort,filter) => {data,success,total}

**Comment by Talljack** [comment]
嗯 可以去看看 data-table组件
