### ISSUE TITLE
Input component line height fluctuation problem(Input组件的行高变动)

### ISSUE THREAD

**Issue by Yiuman** [TuSimple/naive-ui#174]
### TuSimple/naive-ui version (版本)
2.12.0

### Vue version (Vue 版本)
3.1.1

### Browser and its version (浏览器及其版本)
 91.0.4472.101

### System and its version (系统及其版本)
MacOS(11.4)

### Reappearance link (重现链接)
https://codesandbox.io/s/xlw4g

### Reappearance steps (重现步骤)
1.Input numbers or letters （输入数字或者字母）
2.Input Chinese Characters  （输入中文字符，此时可见Input组件的行高改变）

### Expected results (期望的结果)
Whatever you put in，line-height does not change.（无论输入什么行高都不改变，不跳动）

### Actual results (实际的结果)
Line height fluctuation problem

**Comment by Volankey** [comment]
![image](https://user-images.githubusercontent.com/23287363/122350225-9f93ec80-cf7f-11eb-94b2-605fcc14bc48.png)
设置行高可修复这个bug
可以提个pr吗? 应该不难

**Comment by Yiuman** [comment]
我有时间看看吧~
