### ISSUE TITLE
Add `block-protection` component

### ISSUE THREAD

**Issue by Air-Cooled** [TuSimple/naive-ui#1745]
### This function solves the problem (这个功能解决的问题)
For confidential content, it is forbidden to take photos or screenshots, and watermarks can be added; In case of leakage, it is convenient to confirm the source
### Expected API (期望的 API)
Like : https://procomponents.ant.design/components/water-mark
Of course, it's best to disable ctrl-s to save the page content. It may be difficult, but I hope `Naive` will become more and more perfect!

**Comment by 07akioni** [comment]
We may implement it later.

**Comment by Sepush** [comment]
I will have a try.
