### ISSUE TITLE
n-upload: When NUpload list type is "image-card" and is used in NForm, uploaded images are displayed in vertical

### ISSUE THREAD

**Issue by LarchLiu** [TuSimple/naive-ui#1746]
### TuSimple/naive-ui version (版本)
2.21.3

### Vue version (Vue 版本)
3.2.23

### Browser and its version (浏览器及其版本)
Chrome(96.0.4664.55)

### System and its version (系统及其版本)
MacOS(11.2.3)

### Reappearance link (重现链接)
https://stackblitz.com/edit/vitejs-vite-jxps3n?file=src%2Fcomponents%2FHelloWorld.vue

### Reappearance steps (重现步骤)
1. set NUpload  list type to "image-card" 
2. use NUpload in NForm

### Expected results (期望的结果)
Horizontal display of uploaded images

### Actual results (实际的结果)
Uploaded images are displayed in vertical

**Comment by 07akioni** [comment]
You can set `width: 100%;` to `n-upload` as a workaround.
