### ISSUE TITLE
Type `FormValidate` not up to date

### ISSUE THREAD

**Issue by OrbisK** [TuSimple/naive-ui#1747]
### TuSimple/naive-ui version (版本)
2.21.3

### Vue version (Vue 版本)
3.2.23

### Browser and its version (浏览器及其版本)
OperaGX LVL3 (core: 81.0.4196.61)

### System and its version (系统及其版本)
Windows 10 Home

### Reappearance link (重现链接)
https://codesandbox.io/s/elegant-leaf-43ep8?file=/src/Demo.vue

### Reappearance steps (重现步骤)
No steps required.

### Expected results (期望的结果)
```typescript
// naive-ui/es/form/src/interface.d.ts
export declare type FormValidate = ((callback?: FormValidateCallback) => void, (shouldRuleBeApplied?: FormItemRule) => boolean) & (() => Promise<void>);
```

### Actual results (实际的结果)
```typescript
// naive-ui/es/form/src/interface.d.ts
export declare type FormValidate = ((callback?: FormValidateCallback) => void) & (() => Promise<void>);
```
Is wrong (I guess). FormValidate has 2 arguments.

**Comment by 07akioni** [comment]
In fact the second argument is not a public API. I'm not sure about the API pattern is good.
