### ISSUE TITLE
希望列表组件提供和Data Table一样的selection选中行

### ISSUE THREAD

**Issue by YiFo0315** [TuSimple/naive-ui#1748]
### This function solves the problem (这个功能解决的问题)
希望列表组件提供和Data Table一样的selection选中行
### Expected API (期望的 API)
列表头加入选中，并提供个props和value绑定

**Comment by 07akioni** [comment]
未来计划改进一下 list，但是优先级暂时不是很高

具体改进的思路应该会像 https://procomponents.ant.design/components/list

**Comment by conanliuhuan** [comment]
> 未来计划改进一下 list，但是优先级暂时不是很高
> 
> 具体改进的思路应该会像 https://procomponents.ant.design/components/list

List能不能加个虚拟滚动？

**Comment by 07akioni** [comment]
> > 未来计划改进一下 list，但是优先级暂时不是很高
> > 具体改进的思路应该会像 https://procomponents.ant.design/components/list
> 
> List能不能加个虚拟滚动？

目前我想的话，可能性不大，感觉没必要搞这么大的 feature，用户体验也不会多好。

这种重视图而非数据的组件为什么要加这么大量的数据进来？

**Comment by conanliuhuan** [comment]
> > > 未来计划改进一下 list，但是优先级暂时不是很高
> > > 具体改进的思路应该会像 https://procomponents.ant.design/components/list
> > 
> > 
> > List能不能加个虚拟滚动？
> 
> 目前我想的话，可能性不大，感觉没必要搞这么大的 feature，用户体验也不会多好。
> 
> 这种重视图而非数据的组件为什么要加这么大量的数据进来？

可以循环渲染大量自定义内容我只能想到list了，而大量的话确实很需要虚拟滚动呀。目前我都不知道可以选哪个组件来实现类似的功能
