### ISSUE TITLE
input组件未指定placeholder默认就应该为空，不需要显示"please input"

### ISSUE THREAD

**Issue by panyox** [TuSimple/naive-ui#1761]
### This function solves the problem (这个功能解决的问题)
不需要重复写无意义的 placeholder=""
### Expected API (期望的 API)
<n-input type="text"/> 不指定placeholder就不应该显示任何内容

**Comment by 07akioni** [comment]
这个行为已经没法改了，因为牵扯太多了，已经发布了这么久。

可以给你提供一个 workaround。

**Comment by panyox** [comment]
> 我承认这是个不好的设计，但牵扯太多，已经发布了这么久，没办法改变这个默认行为了。
> 
> 可以给你提供一个 workaround。
> 
> ```ts
> import { createLocale, zhCN } from 'naive-ui'
> 
> const myZhCN = createLocale({
>   Input: {
>     placeholder: ''
>   }
> }, zhCN) // 然后在 config provider 中使用这个语言包
> ```

希望改进吧，这设计太反人类了

**Comment by 07akioni** [comment]
> 而且工程量也不算大吧，就加一个if的事情

加了这个会让之前所有依赖这个设计的人的应用出问题

**Comment by 07akioni** [comment]
> > > 而且工程量也不算大吧，就加一个if的事情
> > 
> > 
> > 加了这个会让之前所有依赖这个设计的人的应用出问题，虽然你没用但是可能有人会用
> 
> 我觉得这个应该需要改下，因为如果是业务系统用这个框架，新建单据，几十个 请输入密密麻麻的，太违和了。。考虑下吧

回复中提供了统一解决方案。默认状况已经没有改动的可能。
