### ISSUE TITLE
tree  动态加载的data，default-expand-all 不起作用，希望动态加载tree，default-expand-all 能起作用

### ISSUE THREAD

**Issue by confuseMyself** [TuSimple/naive-ui#1767]
### This function solves the problem (这个功能解决的问题)
tree  动态加载的data，default-expand-all 不起作用
### Expected API (期望的 API)
tree  动态加载的data，default-expand-all 不起作用

**Comment by Talljack** [comment]
将defaultExpandedKeys放入到watch-props中应该可以

**Comment by 07akioni** [comment]
> defaultExpandedKeys

试试这个，应该可以
