### ISSUE TITLE
When `Carousel` is a single picture, or do I not need `dot` existence?

### ISSUE THREAD

**Issue by Air-Cooled** [TuSimple/naive-ui#1777]
### TuSimple/naive-ui version (版本)
2.21.5

### Vue version (Vue 版本)
3.2.24

### Reappearance steps (重现步骤)
Use `Carousel`

### Expected results (期望的结果)
Can control whether the `dot` the `Carousel` are displayed

### Actual results (实际的结果)
The `dot` of `Carousel` must exist

**Comment by Talljack** [comment]
If you think it's a bug, please provide demo, convenient for us to quickly troubleshoot bug

**Comment by Air-Cooled** [comment]
If don’t think need a scenario that does not show `dot`, can turn it off

**Comment by Talljack** [comment]
will do, ref #1462

**Comment by Sepush** [comment]
still not fixed

**Comment by ruihildt** [comment]
I have a usecase where I don't want dot at all. I would like to have a props where I can hide them.

Would that be possible?

**Comment by Sepush** [comment]
> I have a usecase where I don't want dot at all. I would like to have a props where I can hide them.
> 
> Would that be possible?

set `dot-type` to `never`

**Comment by 07akioni** [comment]
set `show-dots` to false

**Comment by 07akioni** [comment]
doc has some mistakes

**Comment by ruihildt** [comment]
Thank you. :)
