### ISSUE TITLE
The button in loading does not disable events

### ISSUE THREAD

**Issue by Essentric** [TuSimple/naive-ui#178]
### TuSimple/naive-ui version (版本)
2.12.0

### Vue version (Vue 版本)
3.1.1

### Browser and its version (浏览器及其版本)
90

### System and its version (系统及其版本)
window

### Reappearance link (重现链接)
https://codesandbox.io/embed/romantic-bash-wihuq?fontsize=14&hidenavigation=1&theme=dark

### Reappearance steps (重现步骤)
Set the Loading property for the button,then click the button
给按钮设置loading属性,然后点击

### Expected results (期望的结果)
click event no repond
点击事件不响应

### Actual results (实际的结果)
click event reponded
点击事件响应了

**Comment by 07akioni** [comment]
I think loading shouldn't disable events. This is expected.
