### ISSUE TITLE
add a Hide Properties MenuOption Properties for hiding menu

### ISSUE THREAD

**Issue by BroJenuel** [TuSimple/naive-ui#1780]
### This function solves the problem (这个功能解决的问题)
I am using naive-ui in a dashboard that uses multiple user access level, some of my users are superadmin, admin, and regular users. I want to hide some menus to regular users. But it seems their is no availble property that will let me do it.

Hoping their is a hide property for hiding a menu.
### Expected API (期望的 API)
Add a MenuOption Properties hide for MenuOptions that can accept a Boolean of false or true.

**Comment by 07akioni** [comment]
> Properties hide for MenuOptions that can acc

This should be implemented in user land. Create a function `createMenuOptions(options: { isAdmin: boolean })`.
