### ISSUE TITLE
希望日期选择器增加只使用面板功能

### ISSUE THREAD

**Issue by JokerLoLgrey** [TuSimple/naive-ui#1784]
### This function solves the problem (这个功能解决的问题)
可以直观的选择某一日期和某一段日期
### Expected API (期望的 API)
可以参考这个https://arco.design/vue/component/date-picker，然后可以的话，还希望增加一个属性来控制多选是使用单面板，还是双面板，可以默认双面板

![image](https://user-images.githubusercontent.com/33446705/145183218-b7cad766-5076-4066-9031-06439bae4454.png)

**Comment by 07akioni** [comment]
有在考虑，不知道实现起来成本如何，这应该是一个比较长期的工作

**Comment by muchenfine** [comment]
+1

**Comment by yanyuku** [comment]
+1

**Comment by 07akioni** [comment]
在 2.29 中添加了
