### ISSUE TITLE
数据表格支持自定义渲染sort icon

### ISSUE THREAD

**Issue by tracy2zhang** [TuSimple/naive-ui#1785]
### This function solves the problem (这个功能解决的问题)
可以修改表头排序所展示的icon
### Expected API (期望的 API)
renderFilterIcon: (options: { active: boolean, asc: boolean }) => VNodeChild

**Comment by 07akioni** [comment]
Will do.

**Comment by tracy2zhang** [comment]
麻烦问一下这个功能何时能支持一下🤝

**Comment by 07akioni** [comment]
> 麻烦问一下这个功能何时能支持一下🤝

最近的两个版本吧，最好是年前
