### ISSUE TITLE
n-space标签中使用n-select,必须要在n-select标签上使用vertical属性才正常 (原问题: n-tab-pane 中 使用n-space里面再用n-select，未选中时 n-select的样式异常，无法进行选择。)

### ISSUE THREAD

**Issue by HKMV** [TuSimple/naive-ui#1787]
### TuSimple/naive-ui version (版本)
2.21.5

### Vue version (Vue 版本)
3.2.24

### Browser and its version (浏览器及其版本)
Microsoft Edge 版本 96.0.1054.43

### System and its version (系统及其版本)
win11 22509.1011

### Reappearance link (重现链接)
https://codesandbox.io/s/pedantic-colden-qincm?file=/src/components/Bug.vue

### Reappearance steps (重现步骤)
n-tab-pane 中 使用n-space里面再用n-select，未选中时 n-select的样式异常

### Expected results (期望的结果)
可以正常选择

### Actual results (实际的结果)
无法选择

**Comment by HKMV** [comment]
已经找到原因:
n-space标签中使用n-select,一定要在n-select标签上使用vertical属性将布局设置为纵向才不会有问题.
n-space默认是横向,经过测试不只是上述情况(n-tab-pane 中)中有这个问题,而是在任何位置只要不在n-space中使用vertical属性都会有这个问题.

**Comment by 07akioni** [comment]
kan ni de miao看你的描述似乎原因和这个是类似的  https://github.com/TuSimple/naive-ui/issues/1798，你可以关注一下，应该是符合预期的

还有就是你的复现我好像打不开

![image](https://user-images.githubusercontent.com/18677354/145466478-9c42b161-110a-43df-8cce-5b9310a4e074.png)

**Comment by HKMV** [comment]
> 看你的描述似乎原因和这个是类似的 #1798
> 
> 你可以关注一下，应该是符合预期的
> 
> 还有就是你的复现我好像打不开
> 
> ![image](https://user-images.githubusercontent.com/18677354/145466478-9c42b161-110a-43df-8cce-5b9310a4e074.png)

嗯嗯,明白了,复现打不开可能是组件配置的问题,不太明白这个在线工具怎么使用的.

**Comment by HKMV** [comment]
> 看你的描述似乎原因和这个是类似的 #1798
> 
> 你可以关注一下，应该是符合预期的
> 
> 还有就是你的复现我好像打不开
> 
> ![image](https://user-images.githubusercontent.com/18677354/145466478-9c42b161-110a-43df-8cce-5b9310a4e074.png)

感谢师傅解答疑惑
