### ISSUE TITLE
Image组件class无效，width/height百分比无效

### ISSUE THREAD

**Issue by wtto00** [TuSimple/naive-ui#1788]
### TuSimple/naive-ui version (版本)
2.21.5

### Vue version (Vue 版本)
3.2.24

### Browser and its version (浏览器及其版本)
Chrome(96.0.4664.45)

### System and its version (系统及其版本)
Windows10

### Reappearance link (重现链接)
https://codesandbox.io/s/recursing-jones-3v9jh?file=/src/Demo.vue

### Reappearance steps (重现步骤)
Image组件class无效，width/height百分比无效

### Expected results (期望的结果)
Image组件class有效，width/height百分比有效

### Actual results (实际的结果)
Image组件class无效，width/height百分比无效

**Comment by 07akioni** [comment]
因为功能需求，naive 的图片需要重新套一个 div，你写的样式会直接挂到 div 上，你需要两层一起配合才能正常的使用图片。

使用 img-props 来给 img 元素加样式。

![image](https://user-images.githubusercontent.com/18677354/145204102-3a08a0f9-ff3d-46fa-ab49-c967df4ca02b.png)

**Comment by wtto00** [comment]
> 因为功能需求，naive 的图片需要重新套一个 div，你写的样式会直接挂到 div 上，你需要两层一起配合才能正常的使用图片。
> 
> 使用 img-props 来给 img 元素加样式。
> 
> ![image](https://user-images.githubusercontent.com/18677354/145204102-3a08a0f9-ff3d-46fa-ab49-c967df4ca02b.png)

不是呀，我这里说的无效就是对包裹图片的`div`无效，不是对`img`标签无效，所以不是`img-props`这个属性。
1. 写的`class`在`div`上面是无效的，`class`确实在`div`上面了，但是`div`上面没有`style scoped`的那个组件唯一`key`值，所以写的`class`样式对包裹图片的`div`元素是无效的。如果没有`scoped`的样式，就可以有效。
2. 我看到文档中`NImage`有写`width="100"`属性，是有效的。但是写`width="100%"`就无效。`height="100%"`也无效。

看[重现链接](https://codesandbox.io/s/recursing-jones-3v9jh?file=/src/Demo.vue)呀
@07akioni

**Comment by wtto00** [comment]
jsx丢失scopedId的问题，可以看下这个解决方案 https://github.com/vuejs/jsx-next/issues/51#issuecomment-770400811

**Comment by wtto00** [comment]
主要是`scopeId`丢失的问题，有了`scopeId`可以写`class`的话，我一般不会直接在元素上面写样式

**Comment by 07akioni** [comment]
scope id 给了，百分比的话我想了想还是算了，感觉比较 hack，还是让用户直接控制比较好
