### ISSUE TITLE
Locale DateTime format not used in NDatePicker (input inside the dropdown) + update fr-FR locale date separator

### ISSUE THREAD

**Issue by M1CK431** [TuSimple/naive-ui#1793]
### TuSimple/naive-ui version (版本)
2.21.5

### Vue version (Vue 版本)
3.2.24

### Browser and its version (浏览器及其版本)
N/A

### System and its version (系统及其版本)
N/A

### Reappearance link (重现链接)
https://www.naiveui.com/en-US/os-theme/components/date-picker

### Reappearance steps (重现步骤)
Choose fr-FR locale, open NDatePicker dropdown, then pick a date: the date input inside the dropdown is still using en-US locale.

### Expected results (期望的结果)
Locale DateTime format used in NDatePicker (input inside the dropdown)

### Actual results (实际的结果)
That input is still using the default en-US locale

### Remarks (补充说明)
Oups! I just notice that, in my previous issue #1751, I miss the date separator (`/` instead of `-`) in my translation, it should be:
```js
{
  Time: {
    dateFormat: "dd/MM/yyyy",
    dateTimeFormat: "dd/MM/yyyy HH:mm:ss"
  }
  DatePicker: {
    monthTypeFormat: "MM/yyyy",
    dateFormat: "dd/MM/yyyy",
    dateTimeFormat: "dd/MM/yyyy HH:mm:ss"
  }
}
```
Really sorry, my bad :disappointed: 

Also, I guess the input field inside `NDatePicker` should probably respect the locale format too:
![image](https://user-images.githubusercontent.com/31622263/145108651-86ee6d42-1dab-42f5-9053-14ce6f83161b.png)

**Comment by Talljack** [comment]
@amadeus711

**Comment by 07akioni** [comment]
@M1CK431 In fact the date-time panel doesn't follows dateFormat now, we will try to fix it.

**Comment by 07akioni** [comment]
I've fix it in this weekend

**Comment by M1CK431** [comment]
Hi @07akioni , thanks a lot.

I have notice a new translation for quarter selection:
https://github.com/TuSimple/naive-ui/blob/9d0558ae0989a160f72ddf2d0499eaa139f36cf6/src/locales/common/frFR.ts#L42-L43

The Fr translation is: `Sélectionner le trimestre`.

And for:
https://github.com/TuSimple/naive-ui/blob/9d0558ae0989a160f72ddf2d0499eaa139f36cf6/src/locales/common/frFR.ts#L32

The FR format is `qqq yyyy`.

Also please don't forget to update the FR date separator (and sorry again, its my mistake).

**Comment by wc-matteo** [comment]
I receive: `Cannot read properties of undefined (reading 'monthBeforeYear')` when clicking on a NDatePicker with a date

**Comment by wc-matteo** [comment]
I was missing `	monthBeforeYear: true` in my custom locale file
