### ISSUE TITLE
Select auto blur after select

### ISSUE THREAD

**Issue by llk2yq** [TuSimple/naive-ui#1796]
### This function solves the problem (这个功能解决的问题)
Select auto blur after select
单选的时候，选中某个选项之后，收起下拉框，并自动失去焦点（一个体现就是边框应该消失）。
### Expected API (期望的 API)
Select auto blur after select

**Comment by 07akioni** [comment]
不符合 HTML 的 select 行为。

https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/select

未来会提供一个 blur 方法。
