### ISSUE TITLE
关于Form表单内用inline的时候select选择器样式失效的问题

### ISSUE THREAD

**Issue by XIERENHUA** [TuSimple/naive-ui#1798]
### TuSimple/naive-ui version (版本)
2.21.5

### Vue version (Vue 版本)
3.2.24

### Browser and its version (浏览器及其版本)
chorm(92.0.4515.159)

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://codesandbox.io/s/magical-agnesi-87mu0?file=/src/App.vue

### Reappearance steps (重现步骤)
form表单内设置inline属性的时候，选择器会被压缩，样式丢失，无法正常操作

### Expected results (期望的结果)
select选择器有固定长度，不会被压缩。

### Actual results (实际的结果)
form表单内设置inline属性的时候，选择器会被压缩，样式丢失，无法正常操作

**Comment by 07akioni** [comment]
这个是预期行为，naive 因为对样式的要求所以没有使用 input 作为默认的 select selector 展示。

原生的有个最小宽度是因为 input 元素有一个默认的 length 属性，这个事对于大多数人来说未必了解是这个原因，一般来说也是需要调整的。所以你可以考虑设定一下宽度，从技术上我不太好给一个最小宽度因为每个用户的场景都不同。
