### ISSUE TITLE
Image 组件包裹img标签的div标签，scoped class以及width/height无效

### ISSUE THREAD

**Issue by wtto00** [TuSimple/naive-ui#1799]
> 因为功能需求，naive 的图片需要重新套一个 div，你写的样式会直接挂到 div 上，你需要两层一起配合才能正常的使用图片。
> 
> 使用 img-props 来给 img 元素加样式。
> 
> ![image](https://user-images.githubusercontent.com/18677354/145204102-3a08a0f9-ff3d-46fa-ab49-c967df4ca02b.png)

不是呀，我这里说的无效就是对包裹图片的`div`无效，不是对`img`标签无效，所以不是`img-props`这个属性。
1. 写的`class`在`div`上面是无效的，`class`确实在`div`上面了，但是`div`上面没有`style scoped`的那个组件唯一`key`值，所以写的`class`样式对包裹图片的`div`元素是无效的。如果没有`scoped`的样式，就可以有效。
2. 我看到文档中`NImage`有写`width="100"`属性，是有效的。但是写`width="100%"`就无效。`height="100%"`也无效。

看[重现链接](https://codesandbox.io/s/recursing-jones-3v9jh?file=/src/Demo.vue)呀
@07akioni

_Originally posted by @wtto00 in https://github.com/TuSimple/naive-ui/issues/1788#issuecomment-988829796_

**Comment by 07akioni** [comment]
看了看，height 是 0，应该是确实有点问题

**Comment by 07akioni** [comment]
等我空了看一下
