### ISSUE TITLE
Image 组件，包裹img标签的div标签，scoped class以及width/height无效

### ISSUE THREAD

**Issue by wtto00** [TuSimple/naive-ui#1800]
### TuSimple/naive-ui version (版本)
2.21.5

### Vue version (Vue 版本)
3.2.24

### Browser and its version (浏览器及其版本)
Chrome(96.0.4664.45)

### System and its version (系统及其版本)
Windows10

### Reappearance link (重现链接)
https://codesandbox.io/s/recursing-jones-3v9jh?file=/src/Demo.vue

### Reappearance steps (重现步骤)
class以及width/height对包裹图片的div无效，不是对img标签无效，所以不是img-props这个属性。

1. 写的class在div上面是无效的，class确实在div上面了，但是div上面没有style scoped的那个组件唯一key值，所以写的class样式对包裹图片的div元素是无效的。如果没有scoped的样式，就可以有效。
2. 我看到文档中NImage有写width="100"属性，是有效的。但是写width="100%"就无效。height="100%"也无效。
看重现链接呀

### Expected results (期望的结果)
Image组件class有效，width/height百分比有效

### Actual results (实际的结果)
Image组件class无效，width/height百分比无效

### Remarks (补充说明)
![image](https://user-images.githubusercontent.com/30424139/145350750-c47b36b4-db01-408d-9eb9-057a13176731.png)

**Comment by wtto00** [comment]
#1788 之前提的被关了，这应该是属于bug的吧

**Comment by 07akioni** [comment]
在 #1788 追踪这个问题
