### ISSUE TITLE
`data-table` custom `slot`

### ISSUE THREAD

**Issue by Air-Cooled** [TuSimple/naive-ui#1803]
### This function solves the problem (这个功能解决的问题)
`render` sometimes the function is too complex and needs to customize the `slot` to simplify the code 
### Expected API (期望的 API)
```vue
<script setup>
import { h } from 'vue'
import { NDataTable } from 'naive-ui'

cont columns = [
  {
    title: 'custom slot',
    key: 'custom',
    render(row) {
      return h('slot', { name: 'custom' })
    }
  }
]
</script>

<template>
  <n-data-table :columns="columns" :data="[{key: 0}]">
    <template #custom> Custom content </template>
  </n-data-table>
</template>
```

**_Maybe there is something wrong with my writing. Can you give a case or support this_**

**Comment by 07akioni** [comment]
We have discussed it in previous issues.

**Comment by 07akioni** [comment]
See https://github.com/TuSimple/naive-ui/issues/106

Basically our resource can't afford the result of introducing the API.
