### ISSUE TITLE
[CSS] class 权重过低，被 tailwindcss3 Preflight 样式覆盖

### ISSUE THREAD

**Issue by Innei** [TuSimple/naive-ui#1808]
### TuSimple/naive-ui version (版本)
2.21.5

### Vue version (Vue 版本)
3.2.24

### Browser and its version (浏览器及其版本)
Chrome 96.0.4664.55

### System and its version (系统及其版本)
macOS12

### Reappearance link (重现链接)
https://github.com/Innei/tailwindcss3-naive-ui-reproduction

### Reappearance steps (重现步骤)
启动此项目，观察按钮的背景颜色被覆盖

### Expected results (期望的结果)
颜色不被覆盖

### Actual results (实际的结果)
颜色被覆盖

### Remarks (补充说明)
![image](https://user-images.githubusercontent.com/41265413/145520347-7bfca567-d3bb-4c1f-9c24-2553b03bb20a.png)
![image](https://user-images.githubusercontent.com/41265413/145520369-0d29f5bd-b35a-40d8-bf58-0803d1f0f9c1.png)

**Comment by 07akioni** [comment]
从根源上来讲应该逐渐添加一些前缀了

**Comment by 07akioni** [comment]
这个我们按组件慢慢加吧
