### ISSUE TITLE
下拉菜单组件设置style的宽度不生效

### ISSUE THREAD

**Issue by seafronthu** [TuSimple/naive-ui#1810]
### TuSimple/naive-ui version (版本)
2.21.5

### Vue version (Vue 版本)
3.2.24

### Browser and its version (浏览器及其版本)
edge(Microsoft Edge 版本 95.0.1020.53 )

### System and its version (系统及其版本)
MacOs(12.0.1)

### Reappearance link (重现链接)
https://codesandbox.io/s/dreamy-spence-hn2v3?file=/src/Demo.vue

### Reappearance steps (重现步骤)
1、n-dropdown添加style设置width:200px;height:300px;overflow:auto;

### Expected results (期望的结果)
在内联样式中width生效

### Actual results (实际的结果)
在内联样式中只有height:300px;overflow:auto;而没有width

**Comment by Talljack** [comment]
可以使用width属性设置宽度
