### ISSUE TITLE
Data Table add property 'min-width' to set column min width and self-adaptation width by ratio

### ISSUE THREAD

**Issue by Salt1024** [TuSimple/naive-ui#1813]
### This function solves the problem (这个功能解决的问题)
min-width property like element-plus
https://element-plus.org/zh-CN/component/table.html#table-column-属性
### Expected API (期望的 API)
DataTableColumn Properties add min-width

**Comment by Fnzero** [comment]
You can  set `className` property on column object to assign a class name to a certain column.

**Comment by 07akioni** [comment]
ref https://drafts.csswg.org/css2/#columns

**Comment by 07akioni** [comment]
@Fnzero See what do they do when min-width is set. If it works differently from with width we should implement it.
