### ISSUE TITLE
[Feature Request] 添加v-loading指令

### ISSUE THREAD

**Issue by llk2yq** [TuSimple/naive-ui#1822]
### This function solves the problem (这个功能解决的问题)
当table正在loading的时候，同时希望其它table相关的功能（例如搜索）也不可用，目前是使用`n-spin`来实现的，希望可以添加`v-loading`指令，直接添加到需要同时loading的模块上。
### Expected API (期望的 API)
[ElementPlus loading](https://element-plus.org/zh-CN/component/loading.html#%E5%8C%BA%E5%9F%9F%E5%8A%A0%E8%BD%BD)

**Comment by Talljack** [comment]
应该不会做 ref #260

**Comment by llk2yq** [comment]
可惜了，看来优雅已经过时了。
