### ISSUE TITLE
Select开启filterable时，选项很长时显示错误

### ISSUE THREAD

**Issue by llk2yq** [TuSimple/naive-ui#1823]
### TuSimple/naive-ui version (版本)
2.21.5

### Vue version (Vue 版本)
3.2.24

### Browser and its version (浏览器及其版本)
edge 96

### System and its version (系统及其版本)
win11

### Reappearance link (重现链接)
https://codesandbox.io/s/vibrant-mountain-hefvp?file=/src/Demo.vue

### Reappearance steps (重现步骤)
进入链接即可查看

### Expected results (期望的结果)
超出部分显示省略号

### Actual results (实际的结果)
超出部分未显示省略号

### Remarks (补充说明)
开启了`filterable`才会有这个问题

**Comment by Talljack** [comment]
我看你的demo里没有看到问题，并且你设置了consistent-menu-width为false则会默认撑开最大宽度

**Comment by llk2yq** [comment]
@Talljack 更新了demo，你再看一下，之前忘记保存了。

**Comment by Talljack** [comment]
> @Talljack 更新了demo，你再看一下，之前忘记保存了。第一个select是有问题的，第二个作为参照没有问题。

![image](https://user-images.githubusercontent.com/34439652/145705946-586e55a9-f7d3-464f-abd8-89de3ba7ae0f.png)
和filterable是没关系的，是你设置了consistent-menu-width为false的问题

**Comment by llk2yq** [comment]
可能是我没表述清楚，（其实demo的代码里写了注释的，）问题效果如下图：
文本很长时，开了`filterable`的超出部分显示异常，没开的则显示正常。
![问题](https://user-images.githubusercontent.com/22813922/145706039-191f3984-21b2-4dc8-9a01-f8f22f70d9eb.png)

**Comment by Talljack** [comment]
明白了

**Comment by llk2yq** [comment]
@Talljack 可以再帮忙看一下这个[问题](https://github.com/TuSimple/naive-ui/issues/1826)吗？

**Comment by 07akioni** [comment]
> @Talljack 可以再帮忙看一下这个[问题](https://github.com/TuSimple/naive-ui/issues/1826)吗？

理解你说的问题了
