### ISSUE TITLE
Drawer有打开事件吗？

### ISSUE THREAD

**Issue by llk2yq** [TuSimple/naive-ui#1826]
```vue
<n-drawer @update:show="updateShow" :show="show">
  <!--content-->
</n-drawer>
```
`updateShow`目前好像只在关闭时才触发，是否有打开时的事件呢？

**Comment by llk2yq** [comment]
看了源码是没有的，只能是自己先`watch`一下`show`了，后续会加关闭事件吗？

**Comment by nooooooom** [comment]
`on-hide` is deprecated, please use `on-update:show` instead.

![image](https://user-images.githubusercontent.com/61452855/145708296-137ec2b0-6af1-4313-98c9-f65381561b55.png)

**Comment by nooooooom** [comment]
`on-show` is deprecated, please use `on-update:show` instead.

![image](https://user-images.githubusercontent.com/61452855/145708318-c02f08e4-2386-473c-8a57-010c14dcaa3b.png)

**Comment by 07akioni** [comment]
> ```
> <n-drawer @update:show="updateShow" :show="show">
>   
> </n-drawer>
> ```
> 
> `updateShow`目前好像只在关闭时才触发，是否有打开时的事件呢？

这个 show 是由用户控制的，所以说你其实可以知道打开的时机。

watch show 也是一个合理的办法。

通常来说，html 中的元素是不会把用户对值的改变作为自身事件发出来的。

例如你对 `inputElement.value = 'x'` 并不会触发其 `onchange` 事件，这也是为什么 onUpdateShow 不会提供一个展开的回调，因为这个是用户触发的。

**Comment by llk2yq** [comment]
主要是项目里很多地方用到了`drawer`，每个里面`watch`的话，感觉不够优雅，是否可以考虑由`drawer`来`watch`，然后`emit`事件出来呢？  @07akioni

**Comment by 07akioni** [comment]
> 主要是项目里很多地方用到了`drawer`，每个里面`watch`的话，感觉不够优雅，是否可以考虑由`drawer`来`watch`，然后`emit`事件出来呢？ @07akioni

这个问题我在上面那个回复过了，你可以考虑一下，自己是不是写了 `show = true`，如果是的话你在这里就可以调用，那么返回头来你可以直接写一个封装好的 `openDrawer`
