### ISSUE TITLE
data-table的render参数值错误（The render parameter of data-table is incorrect）

### ISSUE THREAD

**Issue by sundaqiang** [TuSimple/naive-ui#1839]
### TuSimple/naive-ui version (版本)
2.21.5

### Vue version (Vue 版本)
3.2.26

### Browser and its version (浏览器及其版本)
Edge(96.0.1054.29)

### System and its version (系统及其版本)
windows10

### Reappearance link (重现链接)
https://codesandbox.io/s/ss4v4?file=/src/Demo.vue

### Reappearance steps (重现步骤)
点击启用后查看控制台日志
Click Enable to view console logs

### Expected results (期望的结果)
控制台应打印正确对应的下标值
The console should print the correct subscript values

### Actual results (实际的结果)
打印的下标值永远都是最大的下标值
The printed subscript value is always the largest subscript value

**Comment by 07akioni** [comment]
No row key.
