### ISSUE TITLE
期望新增Tabbar，移动端适配刚需

### ISSUE THREAD

**Issue by Baiyuetribe** [TuSimple/naive-ui#1845]
### This function solves the problem (这个功能解决的问题)
目前的n-tab适合页面内切换，移动端需要底部固定的tabbar，实现页面间切换。
### Expected API (期望的 API)
期望新增tabbar，满足移动端适配的刚需问题。
特点是：移动端可见、底部固定，通常与路由搭配一起使用

可参考案例：https://nutui.jd.com/#/tabbar
![image](https://user-images.githubusercontent.com/43716063/145950127-03b87135-1753-428d-9794-22290267aaf6.png)

**Comment by 07akioni** [comment]
没有相关的计划，这个库主要为了桌面端使用。

各个组件的设计仅仅希望保证在移动端能正常使用。
