### ISSUE TITLE
All components in the loading state should be unclickable and disabled  

### ISSUE THREAD

**Issue by muchenfine** [TuSimple/naive-ui#1853]
### TuSimple/naive-ui version (版本)
2.22.0

### Vue version (Vue 版本)
3.2.26

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
window

### Node version (Node 版本)
16

### Reappearance link (重现链接)
https://codesandbox.io/api/v1/sandboxes/define

### Reappearance steps (重现步骤)
1.The loading state of the switch component is still clickable
2.The style in loading state should be is disabled style
### Expected results (期望的结果)
All components in the loading state should be unclickable and disabled  ,
The style in loading state should be is disabled style

### Actual results (实际的结果)
1.The loading state of the switch component is still clickable
2.The style in loading state should be is disabled style

**Comment by muchenfine** [comment]
At present, the switch can still be clicked in the loading state. I think all components should be consistent

**Comment by Talljack** [comment]
select loading也是吧

**Comment by muchenfine** [comment]
@07akioni @Talljack  Yes, and I think that in loading state, it should be in the same style as disabled

**Comment by 07akioni** [comment]
> select loading也是吧

Don't change select now. It needs further consideration.

**Comment by Talljack** [comment]
> > select loading也是吧
> 
> Don't change select now. It needs further consideration.
okay

**Comment by muchenfine** [comment]
@07akioni  @Talljack  是否考虑先把loading的css样式改为disabled的样式

**Comment by Talljack** [comment]
> @07akioni @Talljack 是否考虑先把loading的css样式改为disabled的样式

我们需要先对一下哪些组件需要修改，在考虑修改方案

**Comment by 07akioni** [comment]
> @07akioni @Talljack 是否考虑先把loading的css样式改为disabled的样式

这个不能一蹴而就，要循序渐进，一点一点来

**Comment by 07akioni** [comment]
> > @07akioni @Talljack 是否考虑先把loading的css样式改为disabled的样式
> 
> 我们需要先对一下哪些组件需要修改，在考虑修改方案 @07akioni

Switch 是合理的，改了没问题
