### ISSUE TITLE
let CSS var prefixed with n for `upload`

### ISSUE THREAD

**Issue by amadeus711** [TuSimple/naive-ui#1854]

**Comment by Sepush** [comment]
现在 ci 有个问题目前不是由模板创建的issue都会被关闭 
我已经和issue-helper的人交流了 他们会出一个新的action来帮助区分是不是由tacking issue的convert to issue创建  等他们出了 我会完善 我们的ci 我们就可以正常的使用tacking issue的功能了
目前就先发了pr 点掉就ok了
