### ISSUE TITLE
Suggestions for improving Input Number component

### ISSUE THREAD

**Issue by linkurzweg** [TuSimple/naive-ui#1859]
### This function solves the problem (这个功能解决的问题)
Thanks a lot for developing this fantastic UI library :)

Currently the Input Number component is a bit limited in its feature range imho.
It does not accept decimal separators for other locales (e.g. in Germany a comma is used for separating decimal values instead of a dot). 

At the moment the component uses a text input under the hood. An input of type number would detect the correct locale automatically if it's set on the html tag (e.g. `<html lang="de">`) and a comma as decimal separator would be accepted. 

I think it's safe to assume that most people would expect the "Input Number" to behave like an input of type number. If there is a technical reason that makes it necessary to use a text input, I would suggest making it possible to pass a locale or a custom decimal separator / a list of custom decimal separators to the component.

Also it would be great if it was possible to limit the decimal places to a fixed number, so that the user can't enter decimals with longer decimal places. This would be very useful for price inputs especially. In that case it would also be great to add a zero to the decimal place. E.g. 34.5 would become 34.50.
### Expected API (期望的 API)
decimal-separators `string[]` - custom separators allowed for decimal numbers
decimal-places `number` - the maximum length of decimal places for the number (zeroes will be added automatically to fill the decimal places)

`<n-input-number ... :decimal-separators="[',']" :decimal-places="2" />`

**Comment by nooooooom** [comment]
Maybe we can allow users to customize the value format, it looks like
```js
// after running format function, the input value is shown as
1000 -> $1,000

// after running parse function, we can get clean number for output
$2,000 -> 2000
```

**Comment by 07akioni** [comment]
> This would be very useful for price inputs especially. In that case it would also be great to add a zero to the decimal place. E.g. 34.5 would become 34.50.

It would be a challenge feature. Like antd's input number. I didn't do it since it would be very subtle & complex. It need a solid model to handler input & output correctly.
