### ISSUE TITLE
Whether the expansion of datatable and tree structure expansion can add animation transitions  

### ISSUE THREAD

**Issue by muchenfine** [TuSimple/naive-ui#1861]
### This function solves the problem (这个功能解决的问题)
Whether the expansion of datatable and tree structure expansion can add animation transitions  
### Expected API (期望的 API)
Whether the expansion of datatable and tree structure expansion can add animation transitions

**Comment by 07akioni** [comment]
We won't add animation to tree table in a short term, since the code would be too complex. The return on investment don't worth to do it.
