### ISSUE TITLE
The style of Carousel boundary

### ISSUE THREAD

**Issue by vvizden** [TuSimple/naive-ui#1866]
### TuSimple/naive-ui version (版本)
2.22.0

### Vue version (Vue 版本)
3.2.25

### Browser and its version (浏览器及其版本)
Chrome(96.0.4664.110)

### System and its version (系统及其版本)
Windows 10 20H2

### Node version (Node 版本)
12.17.0

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/carousel

### Reappearance steps (重现步骤)
Resize the browser until you can see the boundary of the next image.

### Expected results (期望的结果)
Can't see the boundary of the next one.

### Actual results (实际的结果)
See the boundary of the next one.

### Remarks (补充说明)
None.

**Comment by 07akioni** [comment]
Is zoom level set?

What's the resolution of you screen?

**Comment by vvizden** [comment]
> Is zoom level set?
> 
> What's the resolution of you screen?

Normal zoom level (100%),  1920 * 1080.

Attach a screenshot:
![263604B1-F6F0-42e2-8C43-F9027B93FF94](https://user-images.githubusercontent.com/32644183/146487996-9a5f592f-38d1-4404-b10f-7b7744501b3b.png)

**Comment by doom-9** [comment]
![CleanShot 2021-12-17 at 17 31 31](https://user-images.githubusercontent.com/65016011/146522369-57684261-540e-40b7-a2f9-931a3ca4f427.png)
Is it related to the percentage of this width?
