### ISSUE TITLE
Skeleton cause the page error

### ISSUE THREAD

**Issue by arctanzyy** [TuSimple/naive-ui#1867]
### TuSimple/naive-ui version (版本)
2.21.2

### Vue version (Vue 版本)
3.2.16

### Browser and its version (浏览器及其版本)
HuaWei Mobile Browser(12.0.1.300) / WeChat build-in browser(Version 8.0.16 android)

### System and its version (系统及其版本)
Android 10

### Reappearance link (重现链接)
https://codesandbox.io/s/id9tv

### Reappearance steps (重现步骤)
1. Use HuaWei Mobile Browser or WeChat build-in Browser
2. Enter https://codesandbox.io/s/id9tv
3. The Skeleton can't show and the page shows errors

### Expected results (期望的结果)
show Skeleton 

### Actual results (实际的结果)
the page error

**Comment by 07akioni** [comment]
Naive's skeleton uses CSS houdini API. It maybe the reason.

**Comment by 07akioni** [comment]
Wechat version & Huawei browser version should be a useful info, if you could please provide.

**Comment by 07akioni** [comment]
Error message is required for us

**Comment by arctanzyy** [comment]
[Vue warn]: Unhandled error during execution of beforeMount hook 
  at <Skeleton height="40px" width="33%" > 
  at <Space vertical="" > 
  at <Demo> 
  at <DialogProvider> 
  at <NotificationProvider> 
  at <MessageProvider> 
  at <LoadingBarProvider> 
  at <App> Error: Failed to execute 'registerProperty' on 'CSS': The initial value provided does not parse for the given syntax.    at eval (https://id9tv.csb.app/node_modules/naive-ui/es/_utils/composable/use-houdini.js:16:13)

    at callWithErrorHandling ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:5903:18)

    at callWithAsyncErrorHandling ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:5911:17)

    at Array.hook.__weh.hook.__weh ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:2376:19)

    at invokeArrayFns ***@***.***/shared/dist/shared.esm-bundler.js:755:11)

    at ReactiveEffect.componentUpdateFn [as fn] ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:4134:48)

    at ReactiveEffect.run ***@***.***/reactivity/dist/reactivity.esm-bundler.js:376:21)   at mountComponent ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:4096:5)
    at processComponent ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:4061:9)
    at patch ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:3776:11)
    at mountChildren ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:3925:7)
    at mountElement ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:3856:9)
    at processElement ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:3840:7)
    at patch ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:3774:11)
    at mountChildren ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:3925:7)
    at mountElement ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:3856:9)
    at processElement ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:3840:7)
    at patch ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:3774:11)
    at ReactiveEffect.componentUpdateFn [as fn] ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:4173:11)
    at ReactiveEffect.run ***@***.***/reactivity/dist/reactivity.esm-bundler.js:376:21)
    at setupRenderEffect ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:4258:5)
    at ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:4096:5)
    at processComponent ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:4061:9)
    at patch ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:3776:11)
    at ReactiveEffect.componentUpdateFn [as fn] ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:4173:11)
    at ReactiveEffect.run ***@***.***/reactivity/dist/reactivity.esm-bundler.js:376:21)
    at setupRenderEffect ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:4258:5)
    at mountComponent ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:4096:5)
    at ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:4061:9)
    at patch ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:3776:11)
    at mountChildren ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:3925:7)
    at processFragment ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:4041:7)
    at patch ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:3770:9)
    at mountChildren ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:3925:7)
    at processFragment ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:4041:7)
    at patch     at patch ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:3776:11)
    at mountChildren ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:3925:7)
    at processFragment ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:4041:7)
    at patch ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:3770:9)
    at mountChildren ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:3925:7)
    at processFragment ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:4041:7)
    at patch ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:3770:9)
    at ReactiveEffect.componentUpdateFn [as fn] ***@***.***/runtime-core/dist/runtime-core.esm-bundler.js:4173:11
