### ISSUE TITLE
对话框 Dialog弹出bug

### ISSUE THREAD

**Issue by flyingTodream** [TuSimple/naive-ui#1868]
### TuSimple/naive-ui version (版本)
2.22.0

### Vue version (Vue 版本)
3.2.26

### Browser and its version (浏览器及其版本)
Chrome 版本 96.0.4664.110（正式版本） (arm64)

### System and its version (系统及其版本)
MacOS(12.1)

### Node version (Node 版本)
v14.17.1

### Reappearance link (重现链接)
https://codesandbox.io/s/eager-brattain-0j2l6?file=/src/App.vue

### Reappearance steps (重现步骤)
1. 打开dialog
2. 重复按下空格键
3. dialog会重复额外渲染

### Expected results (期望的结果)
关闭或无响应

### Actual results (实际的结果)
dialog会重复额外渲染

**Comment by Talljack** [comment]
ref #1559

**Comment by flyingTodream** [comment]
maybe you can try it without 'positive-text' and 'positive-text' props
