### ISSUE TITLE
更新日志变成2020年了

### ISSUE THREAD

**Issue by baixiaoyu2997** [TuSimple/naive-ui#187]
### TuSimple/naive-ui version (版本)
2.12.0

### Vue version (Vue 版本)
3.1.1

### Browser and its version (浏览器及其版本)
89

### System and its version (系统及其版本)
macos 11.2.3

### Node version (Node 版本)
14

### Reappearance link (重现链接)
https://codesandbox.io/s/lottienuxt-c2ir7?file=/components/Lottie.vue

### Reappearance steps (重现步骤)
打开官网

### Expected results (期望的结果)
日志不正确

### Actual results (实际的结果)
日志不正确

**Comment by amadeus711** [comment]
repo: https://www.naiveui.com/zh-CN/os-theme/docs/changelog
