### ISSUE TITLE
`n-data-table` 受控模式下 数据变化时 当期页未更新

### ISSUE THREAD

**Issue by afocus** [TuSimple/naive-ui#1876]
### TuSimple/naive-ui version (版本)
2.23.0

### Vue version (Vue 版本)
3.2.26

### Browser and its version (浏览器及其版本)
Microsoft Edge( 96.0.1054.53 )

### System and its version (系统及其版本)
windows 11 家庭版 64位

### Reappearance link (重现链接)
https://codesandbox.io/s/mystifying-euclid-zropq

### Reappearance steps (重现步骤)
1. 数据必须时大于1页的
2. 点击分页按钮切换到第二页
3. 数据设置为不到一页的
4. 此时页面显示无数据

### Expected results (期望的结果)
当前页正常

### Actual results (实际的结果)
当前页继承事前数据计算的结果 未有变更

**Comment by 07akioni** [comment]
这个得你来控制页数，ui 是不知道数据变更后你期望切到那一页的

**Comment by wushijiang13** [comment]
我也遇到了这个问题，就是数据全部都是异步加载，然后第一页显示10条，第二页可能只有3条，这样我会把这3条数据重新覆盖table中的data 但是页面会显示无数据

**Comment by wushijiang13** [comment]
补充一句，数据总条数 传入的是13 然后会出现此问题。

**Comment by 07akioni** [comment]
> 我也遇到了这个问题，就是数据全部都是异步加载，然后第一页显示10条，第二页可能只有3条，这样我会把这3条数据重新覆盖table中的data 但是页面会显示无数据

你应该是没设定 remote？我感觉大概率是这样的
