### ISSUE TITLE
Dialog open  bug (still not fixed)

### ISSUE THREAD

**Issue by flyingTodream** [TuSimple/naive-ui#1877]
### TuSimple/naive-ui version (版本)
2.23.0

### Vue version (Vue 版本)
3.2.26

### Browser and its version (浏览器及其版本)
Chrome  版本 96.0.4664.110（正式版本） (arm64)

### System and its version (系统及其版本)
MacOS(12.1)

### Reappearance link (重现链接)
https://codesandbox.io/s/immutable-moon-6hnm8?file=/src/Demo.vue

### Reappearance steps (重现步骤)
1. use the dialog component without 'positive-text' and 'negative-text'
2. when the dialog is open
3. press 'enter' or 'space' key
4. open a new dialog and repeat

### Expected results (期望的结果)
close the dialog

### Actual results (实际的结果)
open a new dialog

### Remarks (补充说明)
i have submit a issue yestoday, it was closed without fixed.
I saw the version released today, but it still not be fixed, I hope it can be resolved soon.

**Comment by Sepush** [comment]
the autofocus is dependent on the  `positive-text` and `negative-text` so you should provide them

**Comment by 07akioni** [comment]
This is a bug, I'll refactor it later.

**Comment by 07akioni** [comment]
We should learn from this.
ref https://mui.com/components/dialogs/
