### ISSUE TITLE
Last generation of `tree` can be tiled

### ISSUE THREAD

**Issue by Air-Cooled** [TuSimple/naive-ui#1894]
### This function solves the problem (这个功能解决的问题)
Lower the height and reduce the rolling distance
### Expected API (期望的 API)
![image](https://user-images.githubusercontent.com/55440364/146678433-81a77c52-2c06-4371-b8eb-5ba414bfa8f5.png)

**Comment by 07akioni** [comment]
Can you explain more? I can't get it.

**Comment by Air-Cooled** [comment]
**_ In the limited height, we can make full use of its width so that we can see more data _**

![image](https://user-images.githubusercontent.com/55440364/146683071-53f529d4-ddc5-460d-9e82-94506d7af01a.png)

** `Tree` is just a structure. The purpose is to better display the data and its structure **
_ Sometimes too much scattered data is not conducive to viewing, So it needs a little tweaking _

**Comment by 07akioni** [comment]
> **_In the limited height, we can make full use of its width so that we can see more data_**
> 
> ![image](https://user-images.githubusercontent.com/55440364/146683071-53f529d4-ddc5-460d-9e82-94506d7af01a.png)
> 
> **`Tree` is just a structure. The purpose is to better display the data and its structure** _Sometimes too much scattered data is not conducive to viewing, So it needs a little tweaking_

I don't think it worth implementing it. It's not a common pattern.

**Comment by Air-Cooled** [comment]
> Think of a operation system's file viewer, It won't displag files horizontally & folders vertical even if files name is short.

![image](https://user-images.githubusercontent.com/55440364/146697552-49da466b-5742-4261-b9be-207ad8d4e10a.png)

I wanted to adjust the style myself to achieve the effect I needed, but the `tree` level of `naive` was not nested, so I couldn't start

_Although each viewpoint has different degrees of defects, wouldn't it be better to give users the space to choose and let users decide by themselves; If you don't think so, you can turn it off_

**Comment by 07akioni** [comment]
> 

I've different opinion, those are 2 things.
