### ISSUE TITLE
<n-carousel> 可否增加动画切换方向和不显示 dot 的 props

### ISSUE THREAD

**Issue by Bisstocuz** [TuSimple/naive-ui#1931]
### This function solves the problem (这个功能解决的问题)
能够竖直切换 item，不显示 dot
### Expected API (期望的 API)
给轮播图组件增加两个 props：
1、show-dot 是否显示 dot
2、animation-direction 切换动画的方向，原来只有水平，现在可以竖直切换

**Comment by muchenfine** [comment]
我也期待它

**Comment by 07akioni** [comment]
团队最近有人在优化，应该会上
