### ISSUE TITLE
文本域拖拽到最小时有竖向滚动条出现

### ISSUE THREAD

**Issue by muchenfine** [TuSimple/naive-ui#1932]
### TuSimple/naive-ui version (版本)
2.23.1

### Vue version (Vue 版本)
3.2.26

### Browser and its version (浏览器及其版本)
crhome

### System and its version (系统及其版本)
window

### Node version (Node 版本)
16

### Reappearance link (重现链接)
https://codesandbox.io/s/v56r8

### Reappearance steps (重现步骤)
文本域拖拽到最小时有竖向滚动条出现
![image](https://user-images.githubusercontent.com/94693483/146921356-843bd033-be2e-4969-b106-1772ba4c86c6.png)

### Expected results (期望的结果)
优化滚动条

### Actual results (实际的结果)
文本域拖拽到最小时有竖向滚动条出现

**Comment by 07akioni** [comment]
现阶段这是预期中的表现（定制 textarea 的滚动条会比较麻烦），长期会想办法优化

**Comment by 07akioni** [comment]
有相关的 issue，先关掉了
