### ISSUE TITLE
table大数据虚拟滚动下, 不支持通过pageup, pagedown, home和end键来导航数据表格内的数据

### ISSUE THREAD

**Issue by bthulu** [TuSimple/naive-ui#1981]
### TuSimple/naive-ui version (版本)
2.23.1

### Vue version (Vue 版本)
3.2.26

### Browser and its version (浏览器及其版本)
edge

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/data-table#virtual

### Reappearance steps (重现步骤)
创建一个n-data-table标签, 加载10万条数据

### Expected results (期望的结果)
支持通过pageup, pagedown, home和end键来导航数据表格内的数据

### Actual results (实际的结果)
不支持通过pageup, pagedown, home和end键来导航数据表格内的数据

**Comment by 07akioni** [comment]
这个暂时没啥想法，我觉得如果你需要翻页的话感觉用最普通的会好一点

**Comment by 07akioni** [comment]
10w 数据在不能过滤的时候本来对于用户就没什么意义了

**Comment by 07akioni** [comment]
不计划支持，未来可能会给 table 增加滚动方法，不在这个 issue 追踪。
