### ISSUE TITLE
input-number增加loading属性

### ISSUE THREAD

**Issue by tracy2zhang** [TuSimple/naive-ui#1984]
### This function solves the problem (这个功能解决的问题)
input-number可以支持loading状态的展示
### Expected API (期望的 API)
loading: boolean

**Comment by Talljack** [comment]
啥场景下需要loading啊？

**Comment by tracy2zhang** [comment]
> 啥场景下需要loading啊？

失焦后将现有值提交给后端，就需要展示loading状态。而且input组件就有loading，input-number有loading也顺理成章。

**Comment by Sepush** [comment]
I will do it
