### ISSUE TITLE
modalProps 中增加style类型

### ISSUE THREAD

**Issue by yanbowe** [TuSimple/naive-ui#1985]
### This function solves the problem (这个功能解决的问题)
现在modalProps 缺少style类型声明
### Expected API (期望的 API)
type

**Comment by Sepush** [comment]
consider needed I found we have deprecated props for this. @07akioni @Talljack 
https://github.com/TuSimple/naive-ui/blob/633648a98cb17bbf5ecfdc2baa9d7dff516498d6/src/modal/src/Modal.tsx#L72

**Comment by Talljack** [comment]
可以直接用style,overlayStyle废弃了

**Comment by yanbowe** [comment]
> 可以直接用style,overlayStyle废弃了

是在下个版本发布吗？

**Comment by yanbowe** [comment]
当前版本overlayStyle是在ModalProps中的，style并不在
![1640230822697_930C4551-DE3E-4d34-89DB-3153590D102F](https://user-images.githubusercontent.com/43030980/147319662-4487297b-e72e-44f3-b4a2-a80fa590b966.png)

**Comment by Talljack** [comment]
style本身就是作为attrs 属性传递下去的
