### ISSUE TITLE
[Bug] Wrong behavior of manually located Dropdown

### ISSUE THREAD

**Issue by duskmoon314** [TuSimple/naive-ui#20]
I have some interest in naive-ui and am browsing the documentation. This error occurs when I tried the demo in the documentation.

### Environment Info

- Naive UI version: 2.11.4
- Browser Info: Edge 91.0.864.41
- System Info: Windows 10

### Reproduction link

https://www.naiveui.com/zh-CN/light/components/dropdown

### Steps to reproduce

Right click in the green square more than three times.

For the first two click, the `dropdown` component opens where I clicked. But from the third click, it will never change position.

![x15GK0HW0e](https://user-images.githubusercontent.com/20477228/121143353-8c8e6780-c86f-11eb-862b-98a7e74bc9db.gif)

### What is expected?

Maybe change the position?

### What is actually happening?

See above.

---

I also tried the demo in the sandbox. I noticed that the `xRef.value` and `yRef.value` changed as I clicked, but the position of the component did not change. But I am new to vue3, so I can't locate where is the problem.

**Comment by 07akioni** [comment]
It's about position sync timing.

**Comment by 07akioni** [comment]
没想到隔壁的同学会看这个😂

**Comment by duskmoon314** [comment]
> 没想到隔壁的同学会看这个😂

😄 

刷知乎看到的，觉得做的很好，我又正好最近开始学习Vue。

好看的Vue3组件库，还有膜的成分，当然要支持一个XD
