### ISSUE TITLE
drawer 当设置native-scrollbar为false时， slot footer的 位置错误

### ISSUE THREAD

**Issue by jahnli** [TuSimple/naive-ui#2003]
### TuSimple/naive-ui version (版本)
2.23.1

### Vue version (Vue 版本)
3.2.26

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
windows

### Reappearance link (重现链接)
https://codesandbox.io/s/busy-dream-x4gxd

### Reappearance steps (重现步骤)
drawer 当设置native-scrollbar为false时， slot footer的 位置错误

### Expected results (期望的结果)
应该保持一致

### Actual results (实际的结果)
drawer 当设置native-scrollbar为false时， slot footer的 位置错误

**Comment by jahnli** [comment]
设置前  设置后
![image](https://user-images.githubusercontent.com/20943608/147233339-feff301f-925b-4771-8c29-ce8218fcf65f.png)

![image](https://user-images.githubusercontent.com/20943608/147233265-f7a65689-cbf1-498c-bd79-5d83c4c3097f.png)

**Comment by Talljack** [comment]
@07akioni

**Comment by 07akioni** [comment]
你应该把 native-scrollbar=false 设在 content 上，drawer 和 content 都有这个属性，只有正确的组合才能搞出东西来

**Comment by 07akioni** [comment]
https://codesandbox.io/s/naughty-blackburn-8hkbg?file=/src/Demo.vue

**Comment by 07akioni** [comment]
@jahnli

**Comment by 07akioni** [comment]
不过确实发现了一个 BUG，虽然和这个 issue 本身的场景无关
