### ISSUE TITLE
希望在n-upload控件上增加双击事件或者自定义功能按钮

### ISSUE THREAD

**Issue by XuYaoAnansi** [TuSimple/naive-ui#2005]
### This function solves the problem (这个功能解决的问题)
n-upload只在照片墙模式提供了预览功能，希望提供一个事件做预览其他文件类型的功能
### Expected API (期望的 API)
在n-upload上增加@click这类的属性，开发人员自行处理相关点击文件列表中文件的事件

**Comment by 07akioni** [comment]
https://www.naiveui.com/zh-CN/os-theme/components/upload#abstract

你可以通过这种方式来自定义触发，只渲染 list，然后需要上传时候调用 upload ref 的 openOpenFileDialog 方法。
