### ISSUE TITLE
n-radio 的value选项应该支持传入任何值

### ISSUE THREAD

**Issue by doom-9** [TuSimple/naive-ui#2012]
### This function solves the problem (这个功能解决的问题)
n-radio 的value选项应该支持传入任何值，现在只允许string. |  number
### Expected API (期望的 API)
value:any

**Comment by Talljack** [comment]
我们应该会支持boolean

**Comment by 07akioni** [comment]
> 我们应该会支持boolean

Boolean 还是算了，感觉一致性不好，我还是考虑 aria

**Comment by 07akioni** [comment]
这东西能给 object 感觉用处也不是特别大

**Comment by 07akioni** [comment]
common case 不是说做不了，但是觉得开这个口子也带不来太多的便利，v-model 的时候需要深对比

**Comment by 07akioni** [comment]
我先关了，可以继续讨论
