### ISSUE TITLE
非受控下tree组件 获取半选状态key值

### ISSUE THREAD

**Issue by ZhangJunkang** [TuSimple/naive-ui#2013]
### This function solves the problem (这个功能解决的问题)
后台需要半选状态值
### Expected API (期望的 API)
getHalfCheckedKeys

**Comment by Talljack** [comment]
你可以用indeterminate-keys和update:indeterminate-keys去获取你需要的半选的keys

**Comment by ZhangJunkang** [comment]
update:indeterminate-keys只在树进行check时才会响应，如果是后台数据，没有半选值，只有选中值的情况下，再下次保存时，无法得到半选值

**Comment by 07akioni** [comment]
> minate-keys只在树进行check时才会响应，如果是后台数据，没有半选值，只有选中值的情况下，再下次保存时，无法得到半选值

后端不给，你这个时候拿到做什么用？假如说是为了传回去，不 check 没啥可传的。所以需要这个数据是做啥呢？

**Comment by 07akioni** [comment]
> 一整个数组,那我怎么知道哪些是半选中的呢，像这个组件父节点选中就是子节点全选中的；
> 难道让我再去把后端给的数据筛选出部分选中吗， 用nodek

事件是会把变化后的 indeterminate keys 发出来的。

初始状态目前确实无法拿到这个值。但是一个正确的实现是，后端对于这个初始值应该是清楚的，不应该依赖于前端做做逻辑判断，也就是说即使我们什么都不改，直接把页面关掉，后端也应该知道什么是半选的，不然的话这个半选对于后端没有数据层面的价值。

**Comment by MartinLongYW** [comment]
> > 一整个数组,那我怎么知道哪些是半选中的呢，像这个组件父节点选中就是子节点全选中的；
> > 难道让我再去把后端给的数据筛选出部分选中吗， 用nodek
> 
> 事件是会把变化后的 indeterminate keys 发出来的。
> 
> 初始状态目前确实无法拿到这个值。但是一个正确的实现是，后端对于这个初始值应该是清楚的，不应该依赖于前端做做逻辑判断，也就是说即使我们什么都不改，直接把页面关掉，后端也应该知道什么是半选的，不应该依赖于前端了解这个的初始值，不然的话这个半选对于后端没有数据层面的价值。

半选的节点，其实也属于一个菜单权限，后端需要保存下来的。返回的时候也会一起给出。
