### ISSUE TITLE
<n-data-table> emit event when a row has been selected with the row data as payload.

### ISSUE THREAD

**Issue by Tebra** [TuSimple/naive-ui#2030]
### This function solves the problem (这个功能解决的问题)
I would like to open a detail view when a row is selected in the table. 
The event should be triggered when the row has been clicked (in any column), and it should emit the data in the current selected row.
### Expected API (期望的 API)

// Event or Prop
| Name | Type | Default | Description |
| --- | --- | --- | --- |
| row-selected | `(rowData: any) => void` | `undefined` | Callback when the row is selected. |

```
<n-data-table
   @row-selected="openDetailView">
</n-data-table>

<!-- or if prop -->
<n-data-table
    :on-row-selected="openDetailView">
</n-data-table>


setup() {
   function openDetailView(rowData) {
       doSomethingWithData(rowData)
   }

   return {
       openDetailView
   }
}
```

**Comment by 07akioni** [comment]
I find row-props fits your demand. Have a try.

https://www.naiveui.com/en-US/os-theme/components/data-table
