### ISSUE TITLE
pagination component - Hides pages when there is only one page

### ISSUE THREAD

**Issue by muchenfine** [TuSimple/naive-ui#2043]
### This function solves the problem (这个功能解决的问题)
pagination component - Hides pages when there is only one page
### Expected API (期望的 API)
pagination component - Hides pages when there is only one page

**Comment by 07akioni** [comment]
I think `v-if="pageCount > 1"` is okay.

**Comment by muchenfine** [comment]
Hopefully, it can be added to make the component more user-friendly

**Comment by simpleAndElegant** [comment]
I am working on it
