### ISSUE TITLE
datatable  remote分页，不应该依据data数据个数来计算

### ISSUE THREAD

**Issue by jahnli** [TuSimple/naive-ui#2044]
### TuSimple/naive-ui version (版本)
2.23.1

### Vue version (Vue 版本)
3.2.26

### Browser and its version (浏览器及其版本)
chome

### System and its version (系统及其版本)
windows

### Reappearance link (重现链接)
https://codesandbox.io/s/nnd6t

### Reappearance steps (重现步骤)
datatable  remote分页，不应该依据data数据个数来计算
既然是异步，应该按照total变量来进行显示总条数，如果根据data的数量跟同步还有什么差异吗 ？

### Expected results (期望的结果)
如果是remote，根据pagination的总条数来判断总数据量，动态调整page，pageSize请求接口渲染数据

### Actual results (实际的结果)
还是根据请求回来的实际数据量来显示，而不是总条数

**Comment by jahnli** [comment]
![image](https://user-images.githubusercontent.com/20943608/147450696-b6abc7e5-f079-4c40-b27a-7eaf490302e0.png)

类似于Element-Plus

**Comment by 07akioni** [comment]
从本意上讲我是不太希望传一个不精确的值出来，但是想了想传一个不精确的出来也可以接受

**Comment by 07akioni** [comment]
如果需要精确的用户传进来就好了

**Comment by jahnli** [comment]
@07akioni   如果只是依据接口返回的数据，意义上来说并不算是remote ，有一种大多场景是分页total作为总条数，page和pageSize取特定10条或20条的数据，

**Comment by 07akioni** [comment]
所以 99 + pagesize 10 显示 990 就是期望的对吧？
