### ISSUE TITLE
增加数据表格展开功能的插槽

### ISSUE THREAD

**Issue by liubake** [TuSimple/naive-ui#205]
### This function solves the problem (这个功能解决的问题)
在展开的内容比较复杂的时候,使用代码的方式处理很不直观,请考虑增加插槽支持.

### Expected API (期望的 API)
类似 element-ui 或 ant-vue 的实现

**Comment by 07akioni** [comment]
出于维护成本，暂时不考虑增加相应插槽

**Comment by fudiwei** [comment]
毛遂自荐 [@skit/x.naive-ui](https://github.com/fudiwei/x.naive-ui)，基于 Naive-UI 二次封装了 DataTable 组件，支持插槽式的写法。
