### ISSUE TITLE
级联面板  -  自定义节点内容

### ISSUE THREAD

**Issue by muchenfine** [TuSimple/naive-ui#2053]
### This function solves the problem (这个功能解决的问题)
可以通过scoped slot对级联选择器的备选项的节点内容进行自定义
### Expected API (期望的 API)

https://codepen.io/pen/?&prefill_data_id=9dcd4a11-bced-42e9-82ab-c4536d1980f3

![image](https://user-images.githubusercontent.com/94693483/147532827-bccd81b6-af0d-46b7-9eb5-de55d98ed4e7.png)

可以通过scoped slot对级联选择器的备选项的节点内容进行自定义

**Comment by 07akioni** [comment]
https://www.naiveui.com/zh-CN/os-theme/components/cascader#custom-render.vue
