### ISSUE TITLE
是否考虑将组件中的H函数调整为template  插槽

### ISSUE THREAD

**Issue by muchenfine** [TuSimple/naive-ui#2054]
### This function solves the problem (这个功能解决的问题)
体验不友好
### Expected API (期望的 API)
是否考虑将组件中的H函数调整为template  插槽

**Comment by muchenfine** [comment]
目前看element antd arco 都是template ， antd也从h函数都修改成了template， 我认为这是友好的

**Comment by 07akioni** [comment]
这个问题讨论了比较多次了，在之前一些 datatable 的 issue 里面有。

简单来说就是开发成本划不来，不符合正确性优先的理念，你可以关注一下过往的 issue。

**Comment by 07akioni** [comment]
没有绝对的对错，只是选择，slot 在很多场景确实更简单

**Comment by fudiwei** [comment]
毛遂自荐 [@skit/x.naive-ui](https://github.com/fudiwei/x.naive-ui)，基于 Naive-UI 二次封装了 DataTable/Select 等组件，支持插槽式的写法。
