### ISSUE TITLE
Checkbox  - 可选项目数量的限制

### ISSUE THREAD

**Issue by muchenfine** [TuSimple/naive-ui#2055]
### This function solves the problem (这个功能解决的问题)
使用 min 和 max 属性能够限制可以被勾选的项目的数量。
### Expected API (期望的 API)
Checkbox  - 可选项目数量的限制
![image](https://user-images.githubusercontent.com/94693483/147533068-7f925d6d-cd71-4b96-b7b8-8efd54621060.png)

**Comment by doom-9** [comment]
![CleanShot 2021-12-28 at 14 17 45](https://user-images.githubusercontent.com/65016011/147534532-dc667e4f-b437-4a36-af04-ea7a353a14ac.png)
有对应的prop
