### ISSUE TITLE
Dropdown should works fine with button

### ISSUE THREAD

**Issue by Kingwl** [TuSimple/naive-ui#2060]
### This function solves the problem (这个功能解决的问题)
Some thing like: https://element.eleme.cn/#/zh-CN/component/dropdown#hong-fa-dui-xiang
### Expected API (期望的 API)
Not sure

**Comment by 07akioni** [comment]
Like this？

![image](https://user-images.githubusercontent.com/18677354/147586683-87d5f193-aecd-40ad-9b6a-e4bb2ea3ba95.png)
