### ISSUE TITLE
badge的进程中闪烁感觉怪怪的，闪烁不流畅

### ISSUE THREAD

**Issue by mysllove** [TuSimple/naive-ui#2066]
### TuSimple/naive-ui version (版本)
2.23.2

### Vue version (Vue 版本)
3.2.26

### Browser and its version (浏览器及其版本)
google

### System and its version (系统及其版本)
window10

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/badge

### Reappearance steps (重现步骤)
页面中示例

### Expected results (期望的结果)
流畅度参照ant ui

### Actual results (实际的结果)
流畅度不流畅

**Comment by nooooooom** [comment]
很早之前提过这个问题[#37](https://github.com/TuSimple/naive-ui/issues/37)，在不同的设备下表现确实会这样

**Comment by 07akioni** [comment]
track in #37
