### ISSUE TITLE
I want to add a parameter to n-input-number to control the decimal point期望n-input-number参数控制小数位的参数

### ISSUE THREAD

**Issue by xingxian1982** [TuSimple/naive-ui#2068]
### This function solves the problem (这个功能解决的问题)
Use this parameter to format the entered value automatically. For example, set the accuracy to 2 for amount and 6 for exchange rate（通过此参数让输入的数值自动格式化，比如为金额时设定精度为2，汇率时设定精度为6）
### Expected API (期望的 API)
:precision=2

**Comment by 07akioni** [comment]
精度的坑可大，这玩意想写好了非常费劲，如果就单纯的一直往上加功能的话会很危险。

现在 input number 的这个架构我觉得撑不住加太多功能，需要一个更高层次的模型抽象。

**Comment by yanbowe** [comment]
> 精度的坑可大，这玩意想写好了非常费劲，如果就单纯的一直往上加功能的话会很危险。
> 
> 现在 input number 的这个架构我觉得撑不住加太多功能，需要一个更高层次的模型抽象。

聪哥，这个有计划在做吗？
