### ISSUE TITLE
popselect can't show-arrow

### ISSUE THREAD

**Issue by Sepush** [TuSimple/naive-ui#2074]
### TuSimple/naive-ui version (版本)
2.23.2

### Vue version (Vue 版本)
3.2.26

### Browser and its version (浏览器及其版本)
96

### System and its version (系统及其版本)
win10

### Node version (Node 版本)
16

### Reappearance link (重现链接)
https://codesandbox.io/s/dark-voice-4g4ly?file=/src/Demo.vue

### Reappearance steps (重现步骤)
1 click the reproduction link
2 click the button
3 you can see when we set `show-arrow="true"` still no arrow

### Expected results (期望的结果)
can control whether show arrow or not

### Actual results (实际的结果)
show arrow does not work

### Remarks (补充说明)
when we set `show-arrow=true` the props of `popover` `show-arrow` is `true` but does not work

**Comment by Talljack** [comment]
popselect does not support arrow and will update the document
