### ISSUE TITLE
NDatePicker doesn't support formatting value

### ISSUE THREAD

**Issue by KeroZhai** [TuSimple/naive-ui#2075]
### The problem this function solves  (这个功能解决的问题)
Provides ability to format the binding value.
### Expected API (期望的 API)
Use a prop like `value-format` which accepts a format string. No offense here, but the way Element UI implements such component provides more convenience to me, and I sincerely hope Naive UI could have this feature too.

**Comment by Talljack** [comment]
Do you mean this?
![image](https://user-images.githubusercontent.com/34439652/147724358-cbf60036-c15f-4783-8765-ac85435b38c3.png)

**Comment by KeroZhai** [comment]
> Do you mean this? ![image](https://user-images.githubusercontent.com/34439652/147724358-cbf60036-c15f-4783-8765-ac85435b38c3.png)

No, this actually formats the label, not _value_.

**Comment by 07akioni** [comment]
We'll add it in recent version.

**Comment by 07akioni** [comment]
closed in 980d98be66810a72ac910a70d72263f1120154be
