### ISSUE TITLE
无法在Drawer里显示NInput

### ISSUE THREAD

**Issue by alaywn** [TuSimple/naive-ui#2077]
### TuSimple/naive-ui version (版本)
2.23.2

### Vue version (Vue 版本)
3.2.26

### Browser and its version (浏览器及其版本)
Chrome（96.0.4664.110）

### System and its version (系统及其版本)
MacOS 12.0.1

### Node version (Node 版本)
17

### Reappearance link (重现链接)
https://codesandbox.io/s/eager-sunset-jmmjo?file=/src/components/HelloWorld.vue

### Reappearance steps (重现步骤)
在drawer中填入input即可

### Expected results (期望的结果)
在drawer中可以正常显示input

### Actual results (实际的结果)
input在最新版naive（2.23.2）中不显示

**Comment by 07akioni** [comment]
去掉 native-scrollbar false

**Comment by alaywn** [comment]
去掉 native-scrollbar false后，是ok的，但是当出现滚动条的时候，会比较难看

**Comment by alaywn** [comment]
应该在NDrawerContent上使用:native-scrollbar="false"，而不应该在NDrawer上使用。
