### ISSUE TITLE
popover和tooltip在disabled状态下的按钮上没有效果

### ISSUE THREAD

**Issue by tracy2zhang** [TuSimple/naive-ui#2078]
### TuSimple/naive-ui version (版本)
2.23.2

### Vue version (Vue 版本)
3.2.26

### Browser and its version (浏览器及其版本)
96.0.4664.110

### System and its version (系统及其版本)
macos12.01

### Node version (Node 版本)
16.13.0

### Reappearance link (重现链接)
https://codesandbox.io/s/hopeful-bash-msgm5?file=/src/Demo.vue

### Reappearance steps (重现步骤)
1. 给一个disabled状态的按钮包裹popover或tooltip，trigger为hover或click
2. hover或click此按钮

### Expected results (期望的结果)
popover和tooltip内容正常显示

### Actual results (实际的结果)
popover和tooltip均不能显示

**Comment by 07akioni** [comment]
see https://www.naiveui.com/zh-CN/os-theme/components/button#popover
