### ISSUE TITLE
support modalService to open a component with modal

### ISSUE THREAD

**Issue by Silentdoer** [TuSimple/naive-ui#2084]
### This function solves the problem (这个功能解决的问题)
类似实现antd angular/react里的用modalSercice.create(component: CustomComponent, {props:xxx,....})，这样就不需要在父组件的HTML里增加一个modal元素，而且要由父组件来控制是否关闭；通过这种方式可以在CustomComponent里添加modalClose函数来关闭自己同时回传关闭的返回值。父组件可以通过await modalSercice.create(...)来获取子modal组件关闭时的回传返回值数据。
### Expected API (期望的 API)
such as antd react/angular

**Comment by 07akioni** [comment]
可以探讨一下，我觉得必要性不大。

第一如果 naive 要实现的话肯定会用 `<n-moda-provider />` 这种形式，然后里面 `useModal` 来做。但是 dialog 基本上覆盖了 modal 的常用的无组件触发场景了。

第二就是如果给了这么个 service 用户必然要写很多渲染函数，因为 modal 会比较复杂。

我觉得没必要引入这种 API，并不是非常常用，常用的 case 现在已经有 dialog 来提供了。

简单来说就是收益不明显，但是维护成本和使用不低。

**Comment by 07akioni** [comment]
因为不打算实现所以先关掉了，如果你有别的看法可以继续讨论
