### ISSUE TITLE
是否应该不废弃 row col 

### ISSUE THREAD

**Issue by muchenfine** [TuSimple/naive-ui#2085]
### This function solves the problem (这个功能解决的问题)
是否应该不废弃 row col , 它与grid作用并不完全一直，有些特定的场景写row col 更为合适
### Expected API (期望的 API)
保留row col
![image](https://user-images.githubusercontent.com/94693483/147801305-e7ece53e-ad7b-421c-8910-0393fa17dbe2.png)

**Comment by 07akioni** [comment]
你的说的有点道理，我会考虑的

**Comment by muchenfine** [comment]
期待调整，不然会遇到好多grid满足不了的场景

**Comment by muchenfine** [comment]
@07akioni   是否有进度 ？

**Comment by 07akioni** [comment]
> @07akioni 是否有进度 ？

不耽误使用，你就正常用，这个组件我肯定不会删的

**Comment by muchenfine** [comment]
能正常用，就是一直在废弃那一栏，每周公司项目都有代码审核。。 过不了关  0.0.

**Comment by 07akioni** [comment]
> 能正常用，就是一直在废弃那一栏，每周公司项目都有代码审核。。 过不了关 0.0.

只能说你们公司真牛逼，我回家把这玩意从废弃拿出来

**Comment by 07akioni** [comment]
> > 能正常用，就是一直在废弃那一栏，每周公司项目都有代码审核。。 过不了关 0.0.
> 
> 只能说你们公司真牛逼，我回家把这玩意从废弃拿出来

有这功夫审计一下后端安全多好，看看自己 deps 树里面有多少 deprecated 的

**Comment by muchenfine** [comment]
还有更恶心的，偷偷告诉你 效仿*为狼性文化呢。。。

**Comment by 07akioni** [comment]
文档改过了
