### ISSUE TITLE
为什么没有编辑表格

### ISSUE THREAD

**Issue by mx4g** [TuSimple/naive-ui#209]
### This function solves the problem (这个功能解决的问题)
官网的组件里面没有编辑表格

### Expected API (期望的 API)
官网的组件里面，没有编辑表格吗？不应该呀！这个很常用的。

**Comment by amadeus711** [comment]
抱歉，目前 table 组件提供的方法与其他 naive-ui 组件组合是可以满足这个需求，所以暂不考虑对此需求进行补充。我们会尽快完善 table 组件的文档，为其添加更多使用的 demo。如果你感兴趣，欢迎 pr 一起补充与维护。
