### ISSUE TITLE
下拉菜单 Dropdown希望可以添加指示图标 

### ISSUE THREAD

**Issue by bzw1204** [TuSimple/naive-ui#2092]
### This function solves the problem (这个功能解决的问题)
1. 当前组件无法看出该组件是一个下拉组件
### Expected API (期望的 API)
1. 参考链接 https://element-plus.gitee.io/zh-CN/component/dropdown.html#%E8%A7%A6%E5%8F%91%E5%AF%B9%E8%B1%A1

**Comment by Talljack** [comment]
是否是这样的效果？https://www.naiveui.com/zh-CN/light/components/dropdown#arrow

**Comment by 07akioni** [comment]
@bzw1204 向 Button 中添加一个 arrow icon 就好了，dropdown 只负责显示，它不修改触发元素

**Comment by bzw1204** [comment]
> 是否是这样的效果？https://www.naiveui.com/zh-CN/light/components/dropdown#arrow
不是，可以看下参考链接
