### ISSUE TITLE
Dialog中useDialog能否支持单独ts文件二次封装调用

### ISSUE THREAD

**Issue by JacksMaster** [TuSimple/naive-ui#2093]
### This function solves the problem (这个功能解决的问题)
二次封装后直接引入调用不用再一个个繁琐的配置基础信息。目前是不能使用的会报错TypeError: Cannot read properties of undefined (reading 'info')

### Expected API (期望的 API)
useDialog，useMessage，useNotification支持ts或js文件二次封装并在.vue setup里面调用

![image](https://user-images.githubusercontent.com/85353476/147852492-3963ab69-a67f-410a-90c6-a7050063c5d7.png)
![image](https://user-images.githubusercontent.com/85353476/147852501-49d97abe-a298-4e56-9317-c12828115627.png)
![image](https://user-images.githubusercontent.com/85353476/147852507-4766358e-9c91-462f-b6e6-fde9186dd66d.png)

**Comment by 07akioni** [comment]
可以二次封装的，App mount 之后挂导出来就好了。

```js
// mymessage.js

export let resolve

let message = new Promise((res) => resolve = res)

function useMyMessage (options) { // 把这个自己用
  message.then(useMessage => useMessage(options))
}
```

```js
import { resolve } from 'mymessage'

export default {
  setup () {
    resolve(useMessage())
  }
}
```

**Comment by banana-framework-lab** [comment]
但是在TS的情况下会有语法报错
