### ISSUE TITLE
tree children isleaf同时设置报错

### ISSUE THREAD

**Issue by lwp001** [TuSimple/naive-ui#2096]
### TuSimple/naive-ui version (版本)
2.23.2

### Vue version (Vue 版本)
3.2.26

### Browser and its version (浏览器及其版本)
89

### System and its version (系统及其版本)
win11

### Node version (Node 版本)
16

### Reappearance link (重现链接)
https://codesandbox.io/s/quirky-khorana-voy51?file=/src/Demo.vue

### Reappearance steps (重现步骤)
tree数据项同时 设置 children=[] isleaf = true 
F12 开发控制台 出现错误提示

### Expected results (期望的结果)
浏览器开发工具 控制台无错误提示

### Actual results (实际的结果)
浏览器开发工具 控制台出现错误提示

**Comment by 07akioni** [comment]
对这种数据表示不能苟同，是 leaf 就不应该有 children 这么个东西了。

不过为了兼容性我还是会把这个问题处理一下。

**Comment by 07akioni** [comment]
closed in https://github.com/07akioni/treemate/commit/71ece1ed53a5e2b8e1bc8844373a28a4125da06f
