### ISSUE TITLE
是否增加无限滚动

### ISSUE THREAD

**Issue by LvCoding112** [TuSimple/naive-ui#2106]
### This function solves the problem (这个功能解决的问题)
加载长列表时，可能会用到无限滚动
### Expected API (期望的 API)
无限滚动，虚拟滚动

**Comment by Acoustic-exe** [comment]
datatable组件 virtual-scroll 属性
是否查看了文档？

**Comment by LvCoding112** [comment]
感谢回复，是否可以提供可以无限滚动的容器，而非table

**Comment by Sepush** [comment]
https://element-plus.org/zh-CN/component/infinite-scroll.html#infinite-scroll-%E6%97%A0%E9%99%90%E6%BB%9A%E5%8A%A8 你想要这个？

**Comment by Acoustic-exe** [comment]
> 感谢回复，是否可以提供可以无限滚动的容器，不可更改

无限滚动需要固定的行高，不然很难实现精准定位，而且比较依赖双向绑定，所以用table就好，里面有render自定义渲染函数，可当做容器使用。实在不行自己做一个组件，大约100行代码就能实现这个

**Comment by LvCoding112** [comment]
好的，感谢Thanks♪(･ω･)ﾉ
