### ISSUE TITLE
Anchor 组件滚动至某个节点后，页面URL已经变化，但是刷新页面不会自动滚动到该节点

### ISSUE THREAD

**Issue by muchenfine** [TuSimple/naive-ui#2110]
### This function solves the problem (这个功能解决的问题)
Anchor 组件滚动至某个节点后，页面URL已经变化，但是刷新页面不会自动滚动到该节点
### Expected API (期望的 API)
应该要根据URL，自动跳转到该节点
参考 Element ant iview

**Comment by Talljack** [comment]
![image](https://user-images.githubusercontent.com/34439652/148076903-b6e54e81-7452-4aea-b1c5-e10720971497.png)
当URL里面有anchor时刷新会自动到当前anchor的地方，但是普通滚动是不会更新URL的anchor的

**Comment by muchenfine** [comment]
是需要设置什么吗 ？ URL有# ***, 不会跳转

**Comment by 07akioni** [comment]
> 是需要设置什么吗 ？ URL有# ***, 不会跳转

根据 hash 在加载时滚动到合适的位置时浏览器默认的行为，这个的前提是 hash 已经被设定

如果 hash 内容对应的 dom 出现的太晚浏览器是不会滚动的，具体时机目前我也不是特别清楚

**Comment by 07akioni** [comment]
@Talljack 可以研究一下浏览器滚动到 hash 未知的前提条件是什么

**Comment by muchenfine** [comment]
https://user-images.githubusercontent.com/94693483/148144940-ea5f2f94-4f03-4da9-994c-67376f61508c.mp4

**Comment by muchenfine** [comment]
我测试了一下， 是不会跳转的，  我不确定前提是什么。 @07akioni @Talljack

**Comment by muchenfine** [comment]
http://localhost:8080/document#category-61cea09acfa3c96b9a4d265f

**Comment by jahnli** [comment]
我不确定具体是不是因为 category-  的原因， 我把category- 去掉 它就是正常的

**Comment by muchenfine** [comment]
我不确定具体是不是因为 category- 的原因， 我把category- 去掉 它就是正常的

**Comment by Talljack** [comment]
应该不太可能是这个 category 的原因，如果可以的话给个demo我排查下

**Comment by muchenfine** [comment]
> 应该不太可能是这个 category 的原因，如果可以的话给个demo我排查下

应该如何联系你 ？

**Comment by Talljack** [comment]
> > 应该不太可能是这个 category 的原因，如果可以的话给个demo我排查下
> 
> 应该如何联系你 ？

可以在钉钉群立找到我
![image](https://user-images.githubusercontent.com/34439652/148523460-3246b65c-54ce-4da8-9699-748ab5636319.png)
