### ISSUE TITLE
输入以0结尾的数字时不会触发on-update:value事件

### ISSUE THREAD

**Issue by cjx-2435** [TuSimple/naive-ui#2115]
### TuSimple/naive-ui version (版本)
2.23.2

### Vue version (Vue 版本)
3.0.0

### Browser and its version (浏览器及其版本)
Chrome/96.0.4664.110

### System and its version (系统及其版本)
Windows NT 10.0

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/input-number

### Reappearance steps (重现步骤)
官方文档 数字输入 Input Number 演示-事件 在输入框中输入 1 时 显示吐司 update:value(1)
再输入 0 时 不会弹出吐司 直到输入非 0 数字 才会 弹出吐司 update:value(xx)

### Expected results (期望的结果)
在输入 0 时正常触发事件update:value

### Actual results (实际的结果)
在输入以0结尾的数字时不会触发update:value事件

**Comment by Talljack** [comment]
目前来看这是合理的，因为如果你输入0那么update:value的时候会进行Number转换, 0也不会更新上

**Comment by cjx-2435** [comment]
在输入1之后再输入0 结果为10
值是明显发生改变了的，但是没自动更新
只有失去焦点后才会触发更新，感觉不是很合理

**Comment by Talljack** [comment]
> 在输入1之后再输入0 结果为10 值是明显发生改变了的，但是没自动更新 只有失去焦点后才会触发更新，感觉不是很合理
没考虑的的情况，我们会修改

**Comment by cjx-2435** [comment]
好的

**Comment by cjx-2435** [comment]
> 默认值是空字符串的时候，我输入0，无法触发更新事件，好像也么有找到如何触发输入事件，文档没有写

我在线文档上试着没毛病
输入事件就是这个
![image](https://github.com/user-attachments/assets/3a9aa820-2dd5-451a-8377-3c242d218e4f)
