### ISSUE TITLE
重新刷新tabs中的数据，tabs不会恢复初始状态，选中的横线也出现错误

### ISSUE THREAD

**Issue by muchenfine** [TuSimple/naive-ui#2120]
### TuSimple/naive-ui version (版本)
2.23.2

### Vue version (Vue 版本)
3.2.26

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
windows

### Reappearance link (重现链接)
https://codesandbox.io/s/broken-river-c5qyj?file=/src/Demo.vue

### Reappearance steps (重现步骤)
重新刷新tabs中的数据，tabs不会恢复初始状态，选中的横线也出现错误

### Expected results (期望的结果)
数据重置时候 应重置状态，恢复初始化横线

### Actual results (实际的结果)
重新刷新tabs中的数据，tabs不会恢复初始状态，选中的横线也出现错误

**Comment by 07akioni** [comment]
这个问题还真的比我想象的处理起来复杂一点，最终的解决方式是暴露一个手动更新的方法出来

**Comment by 07akioni** [comment]
不过是个好 bug，检验了极端场景
