### ISSUE TITLE
Dynamic Input Reordering

### ISSUE THREAD

**Issue by zSoulweaver** [TuSimple/naive-ui#2121]
### This function solves the problem (这个功能解决的问题)
If the order of the array matters it's easy to adjust directly through the component. Currently I'm using it for a game's loot table, the order of the array doesn't *really* matter for my use, but it would be nice if I can put the more common items up the top rather jumbled in the rest of the entries. If the list needs to be altered later with additions it's just eternally stuck at it's position.

Although, I can see ordering of the list being essential to plenty of use cases outside of mine.
### Expected API (期望的 API)
A simple hamburger styled icon which is draggable to reorganise the component would be the best solution. Alternatively, if dragging the row is too heavy for the framework, simply two up and down arrows could work fine.

Example Images:
![image](https://help.syncfusion.com/xamarin/listview/sflistview_images/sflistview-itemreordering.gif)

![image](https://user-images.githubusercontent.com/11328975/148231201-24915368-c5be-4ba8-bc46-8b19c9a4a84b.png)

**Comment by 07akioni** [comment]
As you say, dnd is too heavy for a framework.

Make item orderable would take much code.

I think we may add arrow buttons later.

**Comment by 07akioni** [comment]
closed in #2139
