### ISSUE TITLE
form label-align  invalid

### ISSUE THREAD

**Issue by jahnli** [TuSimple/naive-ui#213]
### TuSimple/naive-ui version (版本)
2.12.2

### Vue version (Vue 版本)
3.1.1

### Browser and its version (浏览器及其版本)
89

### System and its version (系统及其版本)
window10

### Reappearance link (重现链接)
https://codesandbox.io/s/quirky-chandrasekhar-we11r?file=/src/Demo.vue

### Reappearance steps (重现步骤)
The label-align="left" setting is invalid, there is no change in UI, right  

### Expected results (期望的结果)
fix

### Actual results (实际的结果)
The label-align="left" setting is invalid, there is no change in UI, right

**Comment by kungege** [comment]
@Fnzero  🙋‍♂️
