### ISSUE TITLE
n-data-table 使用:row-props, 行内使用n-button,点击button事件会传递会调用row-props

### ISSUE THREAD

**Issue by superpluss** [TuSimple/naive-ui#2136]
### TuSimple/naive-ui version (版本)
2.23.2

### Vue version (Vue 版本)
3.2.26

### Browser and its version (浏览器及其版本)
Edge(97.0.1072.55)

### System and its version (系统及其版本)
Windows 10 (19044.1415)

### Node version (Node 版本)
v14.16.1

### Reappearance link (重现链接)
https://codesandbox.io/s/reverent-platform-ck8q3

### Reappearance steps (重现步骤)
n-data-table 使用:row-props, 行内使用n-button,点击button事件会传递会调用row-props

### Expected results (期望的结果)
button会消费点击事件,不会再传递给n-data-table 执行row-props

### Actual results (实际的结果)
button 的点击事件与 n-data-table row-props事件两个一起执行了

**Comment by 07akioni** [comment]
符合预期的行为，你需要自行处理不同的点击
