### ISSUE TITLE
www.naiveui.com 被限制了吧, 打不开

### ISSUE THREAD

**Issue by Lanseria** [TuSimple/naive-ui#214]
### This function solves the problem (这个功能解决的问题)
能在国内打开

### Expected API (期望的 API)
希望有gitee官网

![image](https://user-images.githubusercontent.com/14802764/122714095-5c948a80-d299-11eb-8987-4f6d69fbaae6.png)

**Comment by amadeus711** [comment]
感谢建议，有安排相关维护人员跟进。
