### ISSUE TITLE
谷歌浏览器下,select 组件的下拉菜单选中一项时,会出现文字模糊叠影问题

### ISSUE THREAD

**Issue by mengyubit** [TuSimple/naive-ui#2146]
### TuSimple/naive-ui version (版本)
2.23.2

### Vue version (Vue 版本)
3.2.26

### Browser and its version (浏览器及其版本)
Chrome/96.0.4664.45 Safari/537.36

### System and its version (系统及其版本)
Ubuntu(20.04.3)

### Node version (Node 版本)
14.18.2

### Reappearance link (重现链接)
https://codesandbox.io/s/jovial-monad-15c35?file=/src/Demo.vue

### Reappearance steps (重现步骤)
选中某一个选项时,出现文字糊有叠影的问题

### Expected results (期望的结果)
选中时,应该是没有任何瑕疵的正常展示

### Actual results (实际的结果)
组件下拉框内文字出现了模糊和叠影效果

**Comment by Sepush** [comment]
没能复现

**Comment by 07akioni** [comment]
你开了缩放吗？

**Comment by Volankey** [comment]
> 你开了缩放吗？

没开，ubuntu下chrome确实会有问题，试了firefox没问题，八成还是特定平台的bug。

**Comment by 07akioni** [comment]
> 有问题，试了firefox没问题，八

有啥属性可以解决吗？会不会和 transform 有关系

**Comment by Volankey** [comment]
> > 有问题，试了firefox没问题，八
> 
> 有啥属性可以解决吗？会不会和 transform 有关系

仔细看了一下，和 这个 transform 有关
![image](https://user-images.githubusercontent.com/23287363/149065698-70f13a41-5962-42a8-aa75-0d87e2cd5fe3.png)
translateZ，去掉就不会有这个问题，还是和chrome的渲染有关

**Comment by Volankey** [comment]
还尝试给 base-select-option 设置从小到大的 z-index 也可以

**Comment by 07akioni** [comment]
> 还尝试给 base-select-option 设置从小到大的 z-index 也可以

这个就算了，感觉不太行

**Comment by 07akioni** [comment]
> > > 有问题，试了firefox没问题，八
> > 
> > 
> > 有啥属性可以解决吗？会不会和 transform 有关系
> 
> 仔细看了一下，和 这个 transform 有关 ![image](https://user-images.githubusercontent.com/23287363/149065698-70f13a41-5962-42a8-aa75-0d87e2cd5fe3.png) translateZ，去掉就不会有这个问题，还是和chrome的渲染有关

这个可以调整，换成普通的 transformX 和 transformY 就好了？

**Comment by 07akioni** [comment]
@mengyubit 把 vueuc （naive 的依赖，可以删除 lock 安装 node_modules，或者手动装一下）更新到 0.4.22 试试，看看有没有问题

**Comment by mengyubit** [comment]
vueuc 目前是0.4.24可以了
