### ISSUE TITLE
Select 左侧 padding 和 Input 不一致，Input 为 12px 而 Select 为 14px

### ISSUE THREAD

**Issue by Mikasa33** [TuSimple/naive-ui#2149]
### TuSimple/naive-ui version (版本)
2.23.2

### Vue version (Vue 版本)
3.2.26

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
MacOS

### Reappearance link (重现链接)
https://github.com/TuSimple/naive-ui

### Reappearance steps (重现步骤)
Select 和 Input 一对比就会发现

### Expected results (期望的结果)
padding 一致

### Actual results (实际的结果)
select 的 padding 比 input 多了 2px

### Remarks (补充说明)

![image](https://user-images.githubusercontent.com/29498153/148768040-e8a701fb-7365-4565-83d4-a242e209e360.png)
![image](https://user-images.githubusercontent.com/29498153/148768060-61d634ee-e6be-4d7e-a2c3-baec76b282d9.png)

**Comment by Sepush** [comment]
I will fix it.
