### ISSUE TITLE
table  使用 template 风格的 API

### ISSUE THREAD

**Issue by jahnli** [TuSimple/naive-ui#216]
### This function solves the problem (这个功能解决的问题)
结构更清晰，更易使用

### Expected API (期望的 API)

参考antd，element

`<a-table-column key="action" title="Action">
    <template slot-scope="text, record">
      <span>
        <a>Action 一 {{ record.firstName }}</a>
        <a-divider type="vertical" />
        <a>Delete</a>
      </span>
    </template>
  </a-table-column>
`

**Comment by jahnli** [comment]
<a-table-column key="action" title="Action">
      <template slot-scope="text, record">
        <span>
          <a>Action 一 {{ record.firstName }}</a>
          <a-divider type="vertical" />
          <a>Delete</a>
        </span>
      </template>
    </a-table-column>

**Comment by amadeus711** [comment]
出于：
    1. 维护成本
    2. TypeScript 支持
暂时不考虑增加相应插槽

**Comment by xxholly32** [comment]
```
{
  title: 'Tags',
  key: 'tags',
  render (row) {
    const tags = row.tags.map((tagKey) => {
      return h(
        NTag,
        {
          style: {
            marginRight: '6px'
          },
          type: 'info'
        },
        {
          default: () => tagKey
        }
      )
    })
    return tags
  }
}
```

我可以理解定义columns作为json带来的好处，但大部分用户是不太爱用h，其实我们业务为了适应多语言环境基本都不能用span，都要封装一层 自动省略的组件，所以可能每个col都是要写一个h；相当恶心

**Comment by jahnli** [comment]
I think so

**Comment by jahnli** [comment]
@xxholly32 You bring up the suggestion again

**Comment by 07akioni** [comment]
可以理解大家的想法，但是在 vue 明确 slot 的类型之前我们不会增加这类 API，到时候如果产生了 breaking changes 大家都会很难受，这是特定的代价，没有办法在每个时刻让每个人都满意。

**Comment by jahnli** [comment]
@07akioni  ![image](https://user-images.githubusercontent.com/20943608/126423653-16f4b095-43f7-4bb8-90f4-af9485f2ed00.png)
 3.2 In BATA, has the author given the solution

**Comment by 07akioni** [comment]
> @07akioni ![image](https://user-images.githubusercontent.com/20943608/126423653-16f4b095-43f7-4bb8-90f4-af9485f2ed00.png)
> 3.2 In BATA, has the author given the solution

他这个评论我看到了，还没空研究，这是 volar 专有的特性？

**Comment by anrananran** [comment]
因为没有插槽，使用体验非常非常非常糟糕！

**Comment by 07akioni** [comment]
> 因为没有插槽，使用体验非常非常非常糟糕！

目前整个 vue 生态的 ts 支持好了一些，会考虑逐步添加 slots 了。

会先再简单的组件做一些实验。

**Comment by qingmang** [comment]
能否优先考虑这个

**Comment by oooowl** [comment]
+1，后台业务中会大量用到table等组件，用slot写法会很有效率

**Comment by qingmang** [comment]
[07akioni](https://github.com/07akioni) 这个今年还没计划吗 @07akioni

**Comment by 07akioni** [comment]
> [07akioni](https://github.com/07akioni) 这个今年还没计划吗 @07akioni

暂时没有

**Comment by rftughniwwe** [comment]
太可惜了,表格不支持插槽很难受,其他都很好,唯独这一点效率很低

**Comment by yajore** [comment]
vue3不是老早都支持了吗，依然不肯跟进。。

**Comment by chenbimo** [comment]
真难受，只能换其他UI组件库了。

**Comment by gzlboy** [comment]
不支持插槽，非常难受！

**Comment by fudiwei** [comment]
毛遂自荐 [@skit/x.naive-ui](https://github.com/fudiwei/x.naive-ui)，基于 Naive-UI 二次封装了 DataTable 组件，支持插槽式的写法。

**Comment by dengsong666** [comment]
> 可以理解大家的想法，但是在 vue 明确 slot 的类型之前我们不会增加这类 API，到时候如果产生了 breaking changes 大家都会很难受，这是特定的代价，没有办法在每个时刻让每个人都满意。

快2024年了，有计划支持了吗？我了解到vue3.3已经开始支持slot类型了

**Comment by Cat7373** [comment]
已经 2024 年了

**Comment by jahnli** [comment]
![55dcc7a997e06e6d8b6624226edc100c](https://github.com/user-attachments/assets/4054d2d5-5a65-4e4e-a612-4914396ebd37)

使用 `tsx`  一样
