### ISSUE TITLE
n-tabs with icons possible?

### ISSUE THREAD

**Issue by TheFreeman** [TuSimple/naive-ui#2163]
### This function solves the problem (这个功能解决的问题)
Hi,

is there any possibility to use also xicons instead of text or as text-prefix?
This would be a great feature.
Thaks a lot!

kind regards,
TF
### Expected API (期望的 API)
```
<template>
  <n-card title="Song of" style="margin-bottom: 16px;">
    <n-tabs type="line">
      <n-tab-pane xicon-fluent="MusicNote" name="oasis" tab="Oasis">Wonderwall</n-tab-pane>
      <n-tab-pane xicon-fluent="MusicNote" name="the beatles" tab="the Beatles">Hey Jude</n-tab-pane>
      <n-tab-pane xicon-fluent="MusicNote" name="jay chou" tab="Jay Chou">Qilixiang</n-tab-pane>
    </n-tabs>
  </n-card>
</template>
```

**Comment by Talljack** [comment]
you can use tab prop to render
![image](https://user-images.githubusercontent.com/34439652/149106229-41cb2ab1-fbc3-4f5a-930a-b5614e1b7c6b.png)

**Comment by 07akioni** [comment]
![image](https://user-images.githubusercontent.com/18677354/149162442-5069b3ff-dcce-45e1-add6-8283e1d7c5e1.png)
use tab slot

**Comment by TheFreeman** [comment]
Hi, thank you so far.
Could you please give me a proper code example?
