### ISSUE TITLE
是否可以支持tree最内层图标的自定义渲染icon 

### ISSUE THREAD

**Issue by wawa0584** [TuSimple/naive-ui#2164]
看是否可以支持最内层自定义渲染icon 类似下图这样 目前暂时通过treemate三方库的map结构修改来达成类似的功能
![image](https://user-images.githubusercontent.com/60140118/149103934-6a2fb634-6003-4dc3-b40c-b90270def93e.png)

**Comment by Talljack** [comment]
啥叫支持最内层自定义渲染icon? 最内层指啥

**Comment by wawa0584** [comment]
> 啥叫支持最内层自定义渲染icon? 最内层指啥

![image](https://user-images.githubusercontent.com/60140118/149114047-a8f09a2f-8353-47b8-bc77-ff826445854e.png)
箭头指向的这一层

**Comment by Talljack** [comment]
![image](https://user-images.githubusercontent.com/34439652/149116882-f59a4f43-acf9-4028-80ba-d7f2566ed836.png)
或许你可以使用这个函数然后判断是否是isLeaf去渲染
