### ISSUE TITLE
row col 增加响应式,类似于gird

### ISSUE THREAD

**Issue by muchenfine** [TuSimple/naive-ui#2165]
### This function solves the problem (这个功能解决的问题)
row col 无响应式， 考虑增加响应式,类似于gird
### Expected API (期望的 API)
:xs="8" :sm="6" :md="4" :lg="3" :xl="1"
![image](https://user-images.githubusercontent.com/94693483/149263585-78e40321-63bc-4ce3-b32c-8c8eadf27877.png)

**Comment by 07akioni** [comment]
我觉得没啥必要，你画的这个 case grid 够了
