### ISSUE TITLE
[Select] onScroll triggered and change options, scrollbar go back to top

### ISSUE THREAD

**Issue by Zhaocl1997** [TuSimple/naive-ui#2168]
### TuSimple/naive-ui version (版本)
2.24.1

### Vue version (Vue 版本)
3.2.26

### Browser and its version (浏览器及其版本)
chrome 97

### System and its version (系统及其版本)
win10 Enterprise

### Node version (Node 版本)
16.13

### Reappearance link (重现链接)
https://codesandbox.io/s/elated-brown-dzhl9?file=/src/Demo.vue

### Reappearance steps (重现步骤)
Focus on select, scroll down, and when bottom reached triggered, scrollbar go back to top

### Expected results (期望的结果)
do not scroll to top when options changed

### Actual results (实际的结果)
scrollbar go back to top when options changed

**Comment by 07akioni** [comment]
We need to consider how the behavior should work since sometimes user may want to scroll to top & sometimes user may want not to scroll to top.

**Comment by Zhaocl1997** [comment]
Ok, it's werid though when i want to load more options from backend, it just scroll back to top. Or maybe provide a flag(?) to decide whether scroll to top when options changed? Is that possible?

**Comment by 07akioni** [comment]
> Ok, it's werid though when i want to load more options from backend, it just scroll back to top. Or maybe provide a flag(?) to decide whether scroll to top when options changed? Is that possible?

Will try.

**Comment by 07akioni** [comment]
closed in 09d362df769e3f26a2e15a024adb8380a40263da

**Comment by Zhaocl1997** [comment]
ok, thanks
