### ISSUE TITLE
`Config Provider` add  global configuration `size`

### ISSUE THREAD

**Issue by Air-Cooled** [TuSimple/naive-ui#2171]
### This function solves the problem (这个功能解决的问题)
Easy to adjust the size of the global, you can avoid the size inconsistency and other issues
### Expected API (期望的 API)
`n-config-provider` adds `size` prop

**Comment by Talljack** [comment]
same #356

**Comment by Air-Cooled** [comment]
> same #356

When I want to switch from compact style to atmospheric style, I need to resize the buttons and forms globally. Is there a simple way to configure this? Or what do I do when I automatically resize according to the resolution size?

**Comment by Talljack** [comment]
you can customizing Select and Form's theme vars
https://www.naiveui.com/en-US/os-theme/docs/customize-theme#Customizing-theme-vars-(design-tokens)

**Comment by Air-Cooled** [comment]
This can be done, but is too complex; don’t consider adding a global size configuration? I Can Wait 💖

**Comment by 07akioni** [comment]
> This can be done, but is too complex; don’t consider adding a global size configuration? I Can Wait 💖

I think it would introduce too much unnecessary overhead in library implementation & won't reduce much userland code. We won't add it.

If you are using form there's a size prop. Otherwise you need to configure size manually.
