### ISSUE TITLE
希望考虑PageHeader组件支持自定义返回图标

### ISSUE THREAD

**Issue by repertory** [TuSimple/naive-ui#2176]
### This function solves the problem (这个功能解决的问题)
有时候不一定使用返回图标，希望能支持自定义
### Expected API (期望的 API)
可以类似menu组件的icon，支持自定义

**Comment by 07akioni** [comment]
不使用返回图标的话用啥呢？那个地方放些什么？

**Comment by Talljack** [comment]
他应该主要是想自定义图标
