### ISSUE TITLE
Allow changing separator of n-number-animation component 

### ISSUE THREAD

**Issue by ilyosjon09** [TuSimple/naive-ui#2181]
### This function solves the problem (这个功能解决的问题)
Currently we can format large numbers with a separator for improving readability. However default separator  may look odd for people from Russia or Central Asia since the default number separator in these countries' regional format is a single space. Numbers after comma represents fraction of the number.

So allowing to add custom separator or locale would be beneficial to solve this problem. 
### Expected API (期望的 API)
`<n-number-animation separator=" " />`
or
`<n-number-animation separator-locale="uz-uz" />`
or
`<n-number-animation respect-locale-format="true" />`

**Comment by Sepush** [comment]
make sence,I will give a PR later.You can use it in Next Version.

**Comment by 07akioni** [comment]
> make sence,I will give a PR later.You can use it in Next Version.

I'm not sure browser can give a reasonable format, if it does that's great. If not we should export the render method.

**Comment by Sepush** [comment]
> 
```js
new Intl.NumberFormat().format() 
```
looks great but I need test

**Comment by 07akioni** [comment]
> > 
> 
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/formatToParts
> 
> ```js
> new Intl.NumberFormat().formatToParts()
> ```
> 
> looks great for this /cc @07akioni

Not bad, make sure to notify users compitability.
