### ISSUE TITLE
keep-alive缓存页面时，DataTable显示有些问题

### ISSUE THREAD

**Issue by MYxu** [TuSimple/naive-ui#2183]
### This function solves the problem (这个功能解决的问题)
使用keep-alive缓存页面后，再次进入包含有DataTable组件页面时，DataTable会显示空白，必须再次滚动才能显示数据，而且滚动位置也被重新滚动到顶部了
### Expected API (期望的 API)
期望能记录DataTable的最后滚动位置，重新切换回页面时，能复原到最后滚动位置

**Comment by 07akioni** [comment]
复现

**Comment by MYxu** [comment]
> 复现
https://github.com/MYxu/naive-ui-admin-demo

**Comment by MYxu** [comment]
[](https://github.com/MYxu/naive-ui-admin-demo/blob/main/%E5%A4%8D%E7%8E%B0.gif)

**Comment by MYxu** [comment]
![GIF](https://user-images.githubusercontent.com/18640435/149624329-13c356fc-9059-43db-8fea-9579c67812dd.gif)
