### ISSUE TITLE
useMessage() 如何单独使用，我在封装axios时使用它报Inject()错误

### ISSUE THREAD

**Issue by zxbe** [TuSimple/naive-ui#2185]
### This function solves the problem (这个功能解决的问题)
//src/utils/useMyMsg.ts
import { VNodeChild } from 'vue'
import { useMessage, MessageOptions } from 'naive-ui'

declare type ContentType = string | (() => VNodeChild)
const notyf1 = useMessage() //不正确
export function useNotyfMsg() {
  //const notyf1 = useMessage() //正确
  return {
    info: (content: ContentType, options?: MessageOptions) =>
      notyf1.info(content, options),
    success: (content: ContentType, options?: MessageOptions) =>
      notyf1.success(content, options),
    warning: (content: ContentType, options?: MessageOptions) =>
      notyf1.warning(content, options),
    error: (content: ContentType, options?: MessageOptions) =>
      notyf1.error(content, options),
    loading: (content: ContentType, options?: MessageOptions) =>
      notyf1.loading(content, options),
    destroyAll: () => notyf1.destroyAll()
  }
}
### Expected API (期望的 API)
可以像elplus那样独立使用

**Comment by 07akioni** [comment]
文档写了

**Comment by 07akioni** [comment]
![image](https://user-images.githubusercontent.com/18677354/149624001-c55bf407-e06f-4eb9-8a62-fb70d4e5658a.png)

**Comment by zhoufanglu** [comment]
> ![image](https://user-images.githubusercontent.com/18677354/149624001-c55bf407-e06f-4eb9-8a62-fb70d4e5658a.png)

如果我在app.vue内挂载， 怎么报错了
```js
// App.vue
<script setup>
// 全局挂载Msg
import { useMessage } from 'naive-ui'

console.log(5, window)
window.$message = useMessage()

console.log(7, window)
</script>
```
error:warn.js:13 Uncaught (in promise) Error: [naive/use-message]: No outer <n-message-provider /> founded. See prerequisite in

**Comment by 07akioni** [comment]
> > ![image](https://user-images.githubusercontent.com/18677354/149624001-c55bf407-e06f-4eb9-8a62-fb70d4e5658a.png)
> 
> 如果我在app.vue内挂载， 怎么报错了
> 
> ```js
> // App.vue
> <script setup>
> // 全局挂载Msg
> import { useMessage } from 'naive-ui'
> 
> console.log(5, window)
> window.$message = useMessage()
> 
> console.log(7, window)
> </script>
> ```
> 
> error:warn.js:13 Uncaught (in promise) Error: [naive/use-message]: No outer founded. See prerequisite in

因为 inject 和 provider 不能在同一个组件里，这是 vue 的特性

**Comment by houqiangxie** [comment]
1，增加一个组件 message-api.vue
<template>
  <div></div>
</template>
 
<script>
import { defineComponent, getCurrentInstance } from "vue";
import { useMessage } from "naive-ui";
 
export default defineComponent({
  setup() {
    window.$message = useMessage();
  },
});
</script>




<template>
  <n-message-provider>
    <MessageApi />
  </n-message-provider>
  <router-view />
</template>
 
<script>
import MessageApi from "@/components/message-api.vue";
import { NMessageProvider } from "naive-ui";
 
export default {
  components: { MessageApi, NMessageProvider },
  name: "App",
  setup(props) {},
};
</script>
 
<style>
* {
  margin: 0;
  padding: 0;
}
</style>

3.任意组件内使用方式：
window.$message.success("success message");
window.$message.error('error message')

**Comment by houqiangxie** [comment]
1，增加一个组件 message-api.vue
<template>
  <div></div>
</template>
 
<script>
import { defineComponent, getCurrentInstance } from "vue";
import { useMessage } from "naive-ui";
 
export default defineComponent({
  setup() {
    window.$message = useMessage();
  },
});
</script>

2，在App.vue中增加如下配置
<template>
  <n-message-provider>
    <MessageApi />
  </n-message-provider>
  <router-view />
</template>
 
<script>
import MessageApi from "@/components/message-api.vue";
import { NMessageProvider } from "naive-ui";
 
export default {
  components: { MessageApi, NMessageProvider },
  name: "App",
  setup(props) {},
};
</script>
 
<style>
* {
  margin: 0;
  padding: 0;
}

</style>

3.任意组件内使用方式：
window.$message.success("success message");
window.$message.error('error message')
window.$message.warning('warning messsage')

**Comment by qqaimh** [comment]
那main.ts里怎么使用呢？
