### ISSUE TITLE
按钮点击后台有报错：Button.js:89 Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by alaywn** [TuSimple/naive-ui#2186]
### TuSimple/naive-ui version (版本)
2.24.1

### Vue version (Vue 版本)
3.2.26

### Browser and its version (浏览器及其版本)
版本 97.0.4692.71（正式版本） (x86_64)

### System and its version (系统及其版本)
MacOs 12.0.1

### Reappearance link (重现链接)
https://codesandbox.io/s/angry-ptolemy-9tvi1?file=/src/App.vue

### Reappearance steps (重现步骤)
只要是按钮组件，点击就可以

### Expected results (期望的结果)
排查报错原因，不再有报错提示

### Actual results (实际的结果)
点击按钮有报错提示

### Remarks (补充说明)
任何地方增加一个NButton组件，点击后都可以重现问题

**Comment by 07akioni** [comment]
https://codesandbox.io/s/elastic-keldysh-lunr1?file=/src/App.vue

没发现错误

**Comment by alaywn** [comment]
codesandbox上的APP.vue我打包以后发布在：http://106.14.167.81:9527/，这个可以看到报错提示，代码跟codesandbox地址上的一模一样
