### ISSUE TITLE
是否考虑把 `src/components-declaration.d.ts` 暴露出来

### ISSUE THREAD

**Issue by myWsq** [TuSimple/naive-ui#2187]
### This function solves the problem (这个功能解决的问题)
为 Volar 提供全局组件类型声明，可在全局引入模式使用，或配合 [unplugin-vue-components](https://github.com/antfu/unplugin-vue-components) 使用。

### Expected API (期望的 API)
```json5
// tsconfig.json
{
  "compilerOptions": {
    // ...
    "types": ["naive-ui/global"]
  }
}
```

```ts
// global.d.ts
declare module "vue" {
  export interface GlobalComponents {
    NAffix: typeof import("naive-ui")["NAffix"];
    NAlert: typeof import("naive-ui")["NAlert"];
    NAnchor: typeof import("naive-ui")["NAnchor"];
    NAnchorLink: typeof import("naive-ui")["NAnchorLink"];
    NAutoComplete: typeof import("naive-ui")["NAutoComplete"];
    // .....
  }
}

export {};
```

<img width="593" alt="CleanShot 2022-01-15 at 23 36 22@2x" src="https://user-images.githubusercontent.com/35214490/149627660-85d409f9-e3b9-4275-b6b3-a123fd1e29d5.png">

**Comment by Talljack** [comment]
有考虑

**Comment by 07akioni** [comment]
有考虑，这个会在一月份做了
