### ISSUE TITLE
DataTable sort typing or docs wrong

### ISSUE THREAD

**Issue by OrbisK** [TuSimple/naive-ui#2192]
### TuSimple/naive-ui version (版本)
2.24.1

### Vue version (Vue 版本)
3.2.26

### Browser and its version (浏览器及其版本)
Opera GX LVL 3 (core: 82.0.4227.50)

### System and its version (系统及其版本)
Win 11

### Reappearance link (重现链接)
https://github.com/TuSimple/naive-ui/blob/e5fd7badf0e4d65a0b77c3dd5c3304c5ae2bf97c/src/data-table/src/interface.ts#L303

### Reappearance steps (重现步骤)
no steps needed

### Expected results (期望的结果)
to be able to pass null to sort

### Actual results (实际的结果)
`TS2345: Argument of type 'string | number | null' is not assignable to parameter of type 'string | number'.   Type 'null' is not assignable to type 'string | number'.`

### Remarks (补充说明)
Docs says: If columnKey set to null, it is the same as clearSorter. `string | number | null`

Interface: `string | number`

**Comment by 07akioni** [comment]
I think we would better follow the implementation, since clear sortetr is provided. Adding more ways to do it would be confusing.
