### ISSUE TITLE
The question about the placeholder swap

### ISSUE THREAD

**Issue by labbomb** [TuSimple/naive-ui#2195]
### This function solves the problem (这个功能解决的问题)
Placeholder can have normal line breaks
### Expected API (期望的 API)
Placeholder can have normal line breaks

**Comment by Talljack** [comment]
I think overflow hidden is better.

**Comment by labbomb** [comment]
> I think overflow hidden is better.

But placeholder is long, so it's a hint to users that you can't overflow

**Comment by Talljack** [comment]
The default input's placeholder is hidden, the placeholder is just a reminder that the input is not real and can't open the height, we may increase the ellipsis.

**Comment by 07akioni** [comment]
![image](https://user-images.githubusercontent.com/18677354/150654819-376cbc65-0bcb-4085-ab6b-54e92baa9c85.png)

Overflow is the default behavior of the browser.
