### ISSUE TITLE
tabs 多种type类型

### ISSUE THREAD

**Issue by muchenfine** [TuSimple/naive-ui#2196]
### This function solves the problem (这个功能解决的问题)
通过 type 可以设置标签的类型。
### Expected API (期望的 API)
通过 type 可以设置标签的类型。
参考：arco.design
![image](https://user-images.githubusercontent.com/94693483/149741009-c76a313c-b1b4-4688-917f-287c646b22fb.png)

**Comment by Talljack** [comment]
same #1466
