### ISSUE TITLE
n-input's clear button trigger on-change event

### ISSUE THREAD

**Issue by ZerroRt** [TuSimple/naive-ui#2197]
### This function solves the problem (这个功能解决的问题)
When the clear button of the n-input is clicked, trigger the on-change event of the n-input
### Expected API (期望的 API)
_

**Comment by Talljack** [comment]
we have done
![image](https://user-images.githubusercontent.com/34439652/149776367-0730f0fd-743e-42f8-a71f-25705a962b41.png)

**Comment by ZerroRt** [comment]
> 

https://codesandbox.io/s/old-shape-ng1i1?file=/src/Demo.vue
but from this demo, clear btn does not trigger change event

**Comment by ZerroRt** [comment]
> we have done.

https://codesandbox.io/s/old-shape-ng1i1?file=/src/Demo.vue
but from this demo, clear btn does not trigger change event
