### ISSUE TITLE
add  'focus' 'blur' 'select' method for all input controls

### ISSUE THREAD

**Issue by coader** [TuSimple/naive-ui#2202]
### This function solves the problem (这个功能解决的问题)
add  'focus' 'blur' 'select' method for: NSelect NDatePicker NCheckbox...
now only input and inputnumber have those methods
### Expected API (期望的 API)
<NSelect ref="ele" ....

const ele=ref(null)
...
ele.focus()

**Comment by 07akioni** [comment]
No select method will be provided.
