### ISSUE TITLE
Upload component [input file type] not reading "input-props"

### ISSUE THREAD

**Issue by vicenterusso** [TuSimple/naive-ui#2204]
### TuSimple/naive-ui version (版本)
2.24.1

### Vue version (Vue 版本)
3.2.26

### Browser and its version (浏览器及其版本)
Version 1.34.80 Chromium: 97.0.4692.71 (Official Build) (64-bit)

### System and its version (系统及其版本)
Linux Kubuntu 21.04

### Reappearance link (重现链接)
https://codesandbox.io/s/vu3-naive-input-props-input-file-plei9

### Reappearance steps (重现步骤)
Just open the link and check generated input "name" attributes

### Expected results (期望的结果)
Expected to have "name" attribute to file input

### Actual results (实际的结果)
Currently the "name" attribute is not being generated

**Comment by vicenterusso** [comment]
> This file input is hidden, why do you need to set attributes?

Sometimes is needed to send files in standard way, not async

**Comment by OrbisK** [comment]
why is prop `name` not working tho?

it might be replaced by `input-props` in the furture!

**Comment by Talljack** [comment]
yeah, you can use `name` prop to do it.

**Comment by OrbisK** [comment]
@Talljack sure, but i guess this is currently not working

**Comment by Talljack** [comment]
> @Talljack sure, but i guess this is currently not working

okay, i will check

**Comment by 07akioni** [comment]
`name` is not `input` element's data, but the upload FormData's value.
