### ISSUE TITLE
n-form-item-gi v-show 无法隐藏

### ISSUE THREAD

**Issue by lwp001** [TuSimple/naive-ui#2206]
### TuSimple/naive-ui version (版本)
2.24.1

### Vue version (Vue 版本)
3.2.27

### Browser and its version (浏览器及其版本)
89

### System and its version (系统及其版本)
win11

### Node version (Node 版本)
16

### Reappearance link (重现链接)
https://codesandbox.io/s/cocky-nova-xcbj7?file=/src/Demo.vue

### Reappearance steps (重现步骤)
 <n-form-item-gi v-show="false" label="路由地址" /> 初始时隐藏的 在切换菜单类型后 无法被隐藏

### Expected results (期望的结果)
正常隐藏和显示

### Actual results (实际的结果)
不隐藏

**Comment by Talljack** [comment]
menuForm是一个ref值，你用它去改变menu_type的时候必须要带上.value

**Comment by lwp001** [comment]
> 

不是值的问题时 CSS 无法隐藏

**Comment by Talljack** [comment]
> > 
> 
> 不是值的问题时 CSS 无法隐藏

你是指在网页上无法看到还是说html元素没隐藏？

**Comment by lwp001** [comment]
> 
应该隐藏的 没有隐藏
![image](https://user-images.githubusercontent.com/3365765/150065484-b4e8815b-d456-47f1-aee9-c1f924dac51c.png)

**Comment by Talljack** [comment]
> > 
> 
> 应该隐藏的 没有隐藏 ![image](https://user-images.githubusercontent.com/3365765/150065484-b4e8815b-d456-47f1-aee9-c1f924dac51c.png)

好的 我会看看

**Comment by lhf6623** [comment]
现在能隐藏了，多次显示隐藏后报错
