### ISSUE TITLE
Persistent NSlider's tooltip

### ISSUE THREAD

**Issue by sahitono** [TuSimple/naive-ui#2212]
### This function solves the problem (这个功能解决的问题)
nslider's tooltip can be seen without mouse hover
### Expected API (期望的 API)
`<nslider :persistent-tooltip="true" />`

**Comment by Talljack** [comment]
How do I know which data the tooltip should display without mouse hover?

**Comment by sahitono** [comment]
> How do I know which data the tooltip should display without mouse hover?

We can use the current value of the slider

**Comment by 07akioni** [comment]
I've made it work on non-range slider.

Range silder will be optimized later.
