### ISSUE TITLE
数据表格的复选框勾选怎么只能获取的设定的key,不能获取当前选中的数据？

### ISSUE THREAD

**Issue by mysllove** [TuSimple/naive-ui#2215]
### This function solves the problem (这个功能解决的问题)
数据表格当前行勾选就能显示所有数据，而不是自己再去从数据里遍历筛选
### Expected API (期望的 API)
数据表格当前行勾选就能显示所有数据，而不是自己再去从数据里遍历筛选

**Comment by 07akioni** [comment]
你的意思是说所有 key 对应的所有的行都一并给出来？

**Comment by mysllove** [comment]
是的

**Comment by Mrqqqwww** [comment]
这个功能什么时候能更新啊
