### ISSUE TITLE
Theme  does not work properly on server side rendering 主题在SSR下无法正常工作

### ISSUE THREAD

**Issue by Zolyn** [TuSimple/naive-ui#2219]
### TuSimple/naive-ui version (版本)
2.24.1

### Vue version (Vue 版本)
3.2.27

### Browser and its version (浏览器及其版本)
Edge (98.0.1093.6)

### System and its version (系统及其版本)
Arch Linux (kernel 5.15.12)

### Node version (Node 版本)
v14.18.2

### Reappearance link (重现链接)
https://github.com/Zolyn/Ephemeres

### Reappearance steps (重现步骤)
1. run `npm run dev`
2. access `localhost:3000`
---
1. 运行`npm run dev`
2. 浏览器访问`localhost:3000`

### Expected results (期望的结果)
Theme should work as expected.
各组件的主题正常工作（即与系统主题相匹配）

### Actual results (实际的结果)
Theme does not work properly. My browser theme is light, but the component theme is dark.
主题无法正常工作。我的浏览器主题为浅色，但组件主题为深色。

### Remarks (补充说明)
I've tried running the project on gitpod and got the same issue. However, it works when I switch to client side rendering (`vite dev`).
项目在gitpod上测试仍有该问题，但使用客户端渲染（`vite dev`）不会发生这种情况

**Comment by 07akioni** [comment]
问题还存在？

**Comment by Zolyn** [comment]
> 问题还存在？

问题还存在，似乎我提的两个issue事实上和NConfigProvider组件有关？刚刚用devtools看了一下，NConfigProvider里的theme属性是有值的（值来自于NaiveUI导出的darkTheme变量，即理论上当前主题应为深色），但实际上除了NBackTop组件其他组件的主题还是浅色的，目前的解决方案就是通过传递key属性在mounted后强制触发NConfigProvider组件重新渲染，这样可以解决我之前提的两个问题，但缺点是会使子组件渲染两次

**Comment by Zolyn** [comment]
> 问题还存在？

问题解决了！是我服务端渲染中没有对服务端和客户端做判断，导致调用的都是createSSRApp()函数，我是照着Vite官方给的例子写的，难道是官方的例子有问题？😂
