### ISSUE TITLE
TimePicker: Icon misaligned when you set clearable true

### ISSUE THREAD

**Issue by Nikhilchandra-Rathod** [TuSimple/naive-ui#222]
### TuSimple/naive-ui version (版本)
2.12.2

### Vue version (Vue 版本)
3.1.1

### Browser and its version (浏览器及其版本)
Chrome(91.0.4472.114)

### System and its version (系统及其版本)
Windows 10

### Reappearance link (重现链接)
https://codesandbox.io/s/youthful-vaughan-nw0m7?file=/src/App.vue

### Reappearance steps (重现步骤)
- Set clearable flag true in timepicker

### Expected results (期望的结果)
- Time icon should be align to right

### Actual results (实际的结果)
- Time icon is misaligned

**Comment by WJCHumble** [comment]
需要 pr 吗，把  `base-clear` 的 `position` 改为 `absolute` 可以解决这个问题，也不会影响 `input`

**Comment by 07akioni** [comment]
> 需要 pr 吗，把 `base-clear` 的 `position` 改为 `absolute` 可以解决这个问题，也不会影响 `input`

已经关了，你可以看一眼对应的 PR 和代码，这个其实有做过相应的实现，只是有的时候忘了改了
