### ISSUE TITLE
Scrollbar does not show on server side rendering 滚动条在SSR下不显示

### ISSUE THREAD

**Issue by Zolyn** [TuSimple/naive-ui#2220]
### TuSimple/naive-ui version (版本)
2.24.1

### Vue version (Vue 版本)
3.2.27

### Browser and its version (浏览器及其版本)
Edge (98.0.1093.6)

### System and its version (系统及其版本)
Arch Linux (kernel 5.15.12)

### Node version (Node 版本)
v14.18.2

### Reappearance link (重现链接)
https://github.com/Zolyn/Ephemeres

### Reappearance steps (重现步骤)
1. run `npm run dev`
2. access `localhost:3000`
---
1. 运行`npm run dev`
2. 浏览器访问`localhost:3000`
---
![2022-01-20_01-24](https://user-images.githubusercontent.com/35414841/150183532-cd48994d-6572-4b8c-bee5-50c6d0526e85.png)
./src/layouts/default.vue
### Expected results (期望的结果)
Scrollbar can be displayed.
滚动条能显示

### Actual results (实际的结果)
Scrollbar is not displayed.
滚动条不显示

### Remarks (补充说明)
At first I chose to write my own CSS to modify the browser scrollbar instead of using the scrollbar of Naive UI, but later I found that client side rendering didn't cause this problem.
一开始我选择自己写css修改浏览器滚动条来代替NaiveUI的滚动条，但后来发现使用客户端渲染不会出现这个问题。

**Comment by 07akioni** [comment]
问题解决了吗？

**Comment by oooowl** [comment]
还是没有解决
