### ISSUE TITLE
Selected item slot for Select component

### ISSUE THREAD

**Issue by ayZagen** [TuSimple/naive-ui#223]
### This function solves the problem
It would be great to have `selected-item`(or any other name) slot to improve customization of selected value.

### Expected API
Also instead of `render-label` property, it would be great to have scoped slot as I think it is more suitable for Vue. Having prop to customize render is kind of React thing.

```vue
<template>
<n-select :options="options" >
  <template #selected-item="{ item }">
    {{item.label}} - {{item.value}} 
  </template>
  <template #option="{ item }">
    This is {{item.label}}
  </template>
</n-select>
</template>
```

**Comment by 07akioni** [comment]
`render-label` actually passes `selected` as 2nd argument (not documented and will be documented).

Adding too much specify slot api is not a good pattern. Naive UI prefers slots for display-only slot such as `header` or something like that, but won't add too many render slots.

**Comment by ayZagen** [comment]
Excuse me but I could not understand how to customize selected item with `render-label`?

**Comment by 07akioni** [comment]
> Excuse me but I could not understand how to customize selected item with `render-label`?
> For ref:
> ![image](https://user-images.githubusercontent.com/11196940/122776061-6aefa000-d2b3-11eb-9087-bdf64e0ca3dd.png)

You mean you want to customize tags (in select input)?

**Comment by ayZagen** [comment]
I've digged into code all I need need is to customize `NInternalSelection`.

Also you said `Naive UI prefers slots for display-only slot` and my usage example is also for display-only purposes. slots by itself are meant to be display only purposes.

**Comment by 07akioni** [comment]
> and my usage example is also for display-only purposes. slots itself are meant to be display only purposes.

I mean it doesn't mix too much logic in it. Since Vue doesn't has good typescript support for slots. I think it is dangerous to rely too much on slots now (nor API and implementation may break a lot if vue change its API).

However the feature will be provided (not by slot api). It's necessary.

**Comment by ayZagen** [comment]
I don't thinks the API is gonna change as vue is in stable release now, though it was discussed a lot in RFCs. As a consumer it would be great to have more slot oriented customization. Please consider using slots more.

Anyway, thank you for your work naive-ui is really great framework, I liked it a lot so far.

**Comment by 07akioni** [comment]
> I don't think the API is gonna change as vue is in stable release now, though it was discussed a lot in RFCs. As a consumer it would be great to have more slot oriented customization. Please consider using slots more.
> 
> Anyway, thank you for your work naive-ui is really great framework, I liked it a lot so far.

Thanks! I know many people perfer slot API (if it is typed, I would too). However now the typed slot rfc is still pending (the same for generic types), I think it's risky to implement it before the rfc is merged. If there're some changes, it will cost a lot to change all the related codes.

https://github.com/vuejs/rfcs/pull/192
