### ISSUE TITLE
DataTableColumn support max-width property.

### ISSUE THREAD

**Issue by iota9star** [TuSimple/naive-ui#2230]
### This function solves the problem (这个功能解决的问题)
Limit the maximum width of the column.
### Expected API (期望的 API)
```
:max-width='100'
max-width='100px'
max-width='5rem'
max-width='20%'
```

**Comment by 07akioni** [comment]
I think there's no cheap way to implement it since CSS rules don't support it currently.

In 2021, the only way I know to get a proper customizable table layout is `ResizeObserver`.

Abstract code:

```html
<ResizeObserver>
  <div>
    <DataTable v-if="sizeReady" :col-widths="colWidthList" />
  </div>
</ResizeObserver>
```
```js
function onResize(width) {
  sizeReady = true
  colWidthList = getColWidthList(width) // for example returns [100, 200, 300, 400]
}
```
