### ISSUE TITLE
数据表格自动处理唯一的 key

### ISSUE THREAD

**Issue by zhaojh329** [TuSimple/naive-ui#2235]
### This function solves the problem (这个功能解决的问题)
可以避免冗余代码。
如果有很多个数据表格，需要对每个表格需要的数据做如下处理：
data = data.map((e, i) => {
    e.key = i;
    return e
})
### Expected API (期望的 API)
无

**Comment by 07akioni** [comment]
包装一个 withKey 函数就行了，成本很低，不用你写的那么长。

正常来说 key 也不应该是 index。

自动拿 index 当 key 会对实现造成很多没必要的困难。

首先一个组件不能修改用户传入的数据，所以组件不应该直接在你传入的对象里增加 key，这样的话就要求组件用一个 Map 来储存传入的每一个数据对象，再反着记录下对应的 index。

**Comment by 07akioni** [comment]
包装一个 withKey 函数就行了，成本很低，不用你写的那么长。

正常来说 key 也不应该是 index。

自动拿 index 当 key 会对实现造成很多没必要的困难。

首先一个组件不能修改用户传入的数据，所以组件不应该直接在你传入的对象里增加 key，这样的话就要求组件用一个 Map 来储存传入的每一个数据对象，再反着记录下对应的 index。

**Comment by zhaojh329** [comment]
我的理解是：事实上，这个 key  是与业务无关的，这个 key 只是 vue 系统用来维护列表节点的状态的。
没必要由使用者来实现，由组件库实现可以减少重复代码。使用者通常只需关系业务代码即可，

**Comment by 07akioni** [comment]
是的，所以用户会用着用着就发现问题了，然后再返回头来问为啥。

针对这件事其实没啥完美的方案，我个人的倾向就是把正确性放在非常高的位置，正确才能保证复杂的组合出更少的问题。

如果少了这个 feature 会让用户多写非常多的代码（几十行），那我会出于易用性加上，但是如果只是为了给用户省几行代码而失去了正确性，我个人不认可。
