### ISSUE TITLE
n-data-table: Virtual scrolling   expand

### ISSUE THREAD

**Issue by OrbisK** [TuSimple/naive-ui#2239]
### TuSimple/naive-ui version (版本)
2.21.5

### Vue version (Vue 版本)
3.2.26

### Browser and its version (浏览器及其版本)
Opera GX LVL3 (core: 82.0.4227.50)

### System and its version (系统及其版本)
Win 11

### Node version (Node 版本)
v16.13.0

### Reappearance link (重现链接)
https://codesandbox.io/s/charming-leftpad-hhke1?file=/src/Demo.vue

### Reappearance steps (重现步骤)
1. e.g. expand the 4th row.
2. scroll down.
3. scroll up
4. repeat 2 and 3 sometimes

### Expected results (期望的结果)
Data-Table row to render correctly.

### Actual results (实际的结果)
It duplicates the expanded content. 
Some rows get deleted.

### Remarks (补充说明)
Its somehow related to the virtual scrolling. In the console are some warning: "duplicate keys"

**Comment by OrbisK** [comment]
Not sure if its actually a bug or just not possible with virtual scrolling

**Comment by 07akioni** [comment]
@amadeus711
