### ISSUE TITLE
官网示例怎么跑通？

### ISSUE THREAD

**Issue by mrerhuo** [TuSimple/naive-ui#224]
### TuSimple/naive-ui version (版本)
2.12.2

### Vue version (Vue 版本)
3.1.1

### Browser and its version (浏览器及其版本)
89.0.4

### System and its version (系统及其版本)
MacOS11.2.3

### Reappearance link (重现链接)
https://codepen.io/team/Vue/pen/xxGadPZ

### Reappearance steps (重现步骤)
https://www.naiveui.com/zh-CN/os-theme/components/modal
Uncaught (in promise) Error: [naive/use-message]: No outer <n-message-provider /> founded.

### Expected results (期望的结果)
Uncaught (in promise) Error: [naive/use-message]: No outer <n-message-provider /> founded.

### Actual results (实际的结果)
Uncaught (in promise) Error: [naive/use-message]: No outer <n-message-provider /> founded.

### Remarks (补充说明)
怎么解决？

**Comment by 07akioni** [comment]
之后会更新 Message 的文档，有问题可以进钉钉群问
