### ISSUE TITLE
expose function to clear n-upload fileList

### ISSUE THREAD

**Issue by bruceeewong** [TuSimple/naive-ui#2247]
### This function solves the problem (这个功能解决的问题)
The scenario is reUploading single file: clicking reUpload should firstly clear the existed fileList, but I can't find any instruction of this. Am I missing something? 

I know passing `fileList` will set the component to controlled mode, however it's not reactive: I set things like `previewFileList.value = undefined;`, the fileList of n-upload is still visible and it prevents me to do another upload.

My temp solution is to get the ref of inputElRef from n-upload, and call 
`fileInputRef.value.inputElRef.fileList = undefined` to makes it work, but I think it's kind of a tricky solution. Hoping for a fresh one.
### Expected API (期望的 API)
maybe add expose function like `clear` or `reset` to n-upload component?

**Comment by 07akioni** [comment]
Will do
