### ISSUE TITLE
Lazy validation trigger

### ISSUE THREAD

**Issue by dav245** [TuSimple/naive-ui#2249]
### This function solves the problem (这个功能解决的问题)
As of now, i don't see an option to change validation trigger behavior based on validation status. I am trying to achieve trigger on blur for non validated fields, if validation on blur throws an error it should change trigger to input. Once user fixes given field it should toggle back to on blur. It is in my opinion the best UX as user is not harassed as soon as he starts typing for example email. At the same time once he manages to enter incorrect value he sees he fixed the problem as soon as he corrects the value and does not need to focus out of the field.
### Expected API (期望的 API)
As for the implementation maybe - and i have just flew over the code - it would be possible to get desired outcome just by accepting trigger as ref. 

You could then do wrapper around validator like so:

```ts
export const makePasswordRule: FormItemRule = (options) => {
  let trigger = ref('blur');
  const passwordValidator: FormItemRuleValidator = (rule, value) => {
     const result = getValidationResult(rule, value); // at least 6 chars, required, ...
     trigger.value = result instanceof Error ? 'input' : 'blur';
     return result;
  }
  return {
    validator: passwordValidator,
    trigger: trigger
  }
}
```

**Comment by 07akioni** [comment]
I think it's possible to change trigger of rules now. Can't it be achieved?

**Comment by dav245** [comment]
Hmm i have spent good hour or two going through docs, source code and trying some ideas. However nothing was working for me. You could theoretically modify original array of rules. However that is kinda hackish way of dealing with the problem.

Simple pseudocode

```ts
const rules = {email: {trigger: 'blur', ...}, ...};
...
rules.email.trigger = 'input';
```

To be able to do the same thing from the factory you would have to store returned object.

```ts
export const makePasswordRule1: FormItemRule = (options) => {
  const passwordValidator: FormItemRuleValidator = (rule, value) => {
     const result = getValidationResult(rule, value); // at least 6 chars, required, ...
     resultObject.trigger = result instanceof Error ? 'input' : 'blur';
     return result;
  }
  const resultObject = {
    validator: passwordValidator,
    trigger: 'blur'
  }
  return resultObject;
}
```

And that is in my opinion big no no. Once anyone does Object.assign({}, resultObject) you loose the working reference.

But if you think that it can be achieved please show me general direction how to do that. I will happily experiment around to possibly improve this awesome repo.

**Comment by 07akioni** [comment]
https://codesandbox.io/s/peaceful-field-sbeys?file=/src/Demo.vue

For name with length >= 10, error will be trigger on input.

For name with length length between 0 and 10, you need blur to get the validation result.

**Comment by 07akioni** [comment]
It's a bit hack but I think it can be encapsulate.

**Comment by dav245** [comment]
I am not totally sure why my solution is working. Maybe your insight will help. Here is working demo:

```ts
<script setup lang="ts">
export const makePasswordRule: () => FormItemRule = () => {
  const trigger = ref('blur'); // Trigger is reactive
  const passwordValidator: FormItemRuleValidator = (rule, value) => {
    if (value.length < 6) {
      trigger.value = 'input';

      return new Error('password must be at least 6 characters long');
    }

    trigger.value = 'blur';
    return true;
  };

  return reactive( // and whole rule needs to be reactive too
    {
      validator: passwordValidator,
      trigger: trigger, // Linter says Ref<string> is not one of string | string[] | undefined
    }
  );
};

const rules = {
  password: makePasswordRule(),
};
</script>

<template>
  <n-form :rules="rules"></n-form>
</template>
```

I have tried some combinations:
return nonreactive object / non ref trigger - validation works, trigger is NOT changed
return nonreactive object / ref trigger - validation does not work at all
return reactive object / ref trigger - everything works, just linter complains about ref<string> not being one of string | string[] | undefined
return reactive object / non ref trigger - validation works, trigger is NOT changed

I honestly don't know why combo reactive object ref trigger works.

**Comment by dav245** [comment]
So basically here is a wrapper for any validator, that returns lazy validator.

```ts
const makeValidatorWithLazyTrigger = (
  validator: FormItemRuleValidator,
) => {
  const trigger = ref('blur');

  const wrappedValidator: FormItemRuleValidator = (...args) => {
    const result = validator(...args);

    trigger.value = result instanceof Error ? 'input' : 'blur';

    return result;
  };

  return reactive({
    trigger: trigger,
    validator: wrappedValidator,
  });
};

```

I was quite surprised no one was dealing with this issue before me. At least not publicly. Maybe this is something worth mentioning in the docs. Still i would firstly validate, that that weird thing with reactive around ref is valid solution and not something horrible to do.

Anyways tahank you for your help. I will close this issue
