### ISSUE TITLE
官网示例怎么跑通？

### ISSUE THREAD

**Issue by mrerhuo** [TuSimple/naive-ui#225]
### TuSimple/naive-ui version (版本)
2.12.2

### Vue version (Vue 版本)
3.1.1

### Browser and its version (浏览器及其版本)
89.0.4

### System and its version (系统及其版本)
MacOS11.2.3

### Reappearance link (重现链接)
https://codepen.io/team/Vue/pen/xxGadPZ

### Reappearance steps (重现步骤)
https://www.naiveui.com/zh-CN/os-theme/components/modal
Uncaught (in promise) Error: [naive/use-message]: No outer <n-message-provider /> founded.

### Expected results (期望的结果)
期望与文档demo一直
### Actual results (实际的结果)
实际情况是：
Uncaught (in promise) Error: [naive/use-message]: No outer <n-message-provider /> founded.

### Remarks (补充说明)
不好用啊。

**Comment by 07akioni** [comment]
具体到这个问题，你需要在应用根部包一个 `<n-message-provider />`

App.vue
```
<template>
  <n-message-provider>
     <rest />
  </n-message-provider>
</template>
```

Rest.js
```
...

{
  setup () {
    const message = useMessage()
  }
}
```

**Comment by 07akioni** [comment]
如果你有进一步的使用问题可以加入钉钉群，那里响应大多数时候更及时

**Comment by toolse** [comment]
我也遇到这个问题了，确实在使用上不太合理，消息提示或加载条大多数会在xxx.js中的请求或响应拦截器中使用

**Comment by 07akioni** [comment]
> 确实在使用上不太合理，消息提示或加载条大多数会在xxx.js中的请求或响应拦截器中使用，可以统一对API返回的消息进行响应和控

naive 设计的范式就是一切都是应用内的状态，脱离这种用法确实会出现一些反模式

**Comment by jakeliyw** [comment]
那我在axios，响应后端数据时如何使用呢？

**Comment by 07akioni** [comment]
> 那我在axios，响应后端数据时如何使用呢？

如果你写了拦截器，就把 useMessage 拿到的结果挂到一个全局变量里

如果你只是在 setup 里面用，那么直接用 useMessage 得到的结果就好

**Comment by zhoufanglu** [comment]
难顶 还要挂载windows上。。

**Comment by 07akioni** [comment]
> 难顶 还要挂载windows上。。

存在哪里是无所谓的，怎么组织 JS 是自由的

**Comment by whqgo** [comment]
同样问题 咋写啊 咋这么麻烦？？？？

**Comment by a3246995** [comment]
APP中居然没法使用,我一个websocket在app中调用想引用它才发现不行...

**Comment by InsHomePgup** [comment]
把Provider包裹在APP.vue的最外层就可以用了。

```

APP.vue

  <n-message-provider>
    <main>
      <RouterView />
    </main>
  </n-message-provider>


```

```

// 你的组件里

<script setup lang="ts">
const message = useMessage()
... 这里你就可以用message的api了。
</script>

```
