### ISSUE TITLE
建议UPLOAD组件支持自适应大小

### ISSUE THREAD

**Issue by idanran** [TuSimple/naive-ui#2251]
### This function solves the problem (这个功能解决的问题)
PC端组件占用面积过小
### Expected API (期望的 API)
根据屏幕大小占用适宜的面积

**Comment by idanran** [comment]
指的是拖动上传那个

**Comment by 07akioni** [comment]
给点图？看看现在效果占用面积过小是啥样子

**Comment by idanran** [comment]
> 给点图？看看现在效果占用面积过小是啥样子

![IMG20220124125140.jpg](https://user-images.githubusercontent.com/96647698/150723975-0d834728-fa90-4b4f-a42c-8f2b07fc8987.jpg)

**Comment by 07akioni** [comment]
> 给点图？看看现在效果占用面积过小是啥样子

这个大小你可以自己设 style 来调整

**Comment by idanran** [comment]
> > 给点图？看看现在效果占用面积过小是啥样子
> 
> 这个大小你可以自己设 style 来调整

请问该如何调整,我不知道该给那个组件设置style

**Comment by 07akioni** [comment]
upload-dragger

**Comment by idanran** [comment]
> upload-dragger

好的,谢谢.

**Comment by idanran** [comment]
> upload-dragger

.n-upload-trigger
将这个CLASS的宽度改为100%,才能实现自适应
