### ISSUE TITLE
建议Spin组件支持显示全屏动画

### ISSUE THREAD

**Issue by idanran** [TuSimple/naive-ui#2253]
### This function solves the problem (这个功能解决的问题)
防止用户操作
### Expected API (期望的 API)
类似于 https://element-plus.gitee.io/zh-CN/component/loading.html#%E8%AE%A9%E5%8A%A0%E8%BD%BD%E7%BB%84%E4%BB%B6%E9%93%BA%E6%BB%A1%E6%95%B4%E4%B8%AA%E5%B1%8F%E5%B9%95

**Comment by Talljack** [comment]
暂时不考虑 ref #260
