### ISSUE TITLE
弹框中添加表单，在打开弹框时表单第一个元素会自动获取焦点

### ISSUE THREAD

**Issue by HX1194361432** [TuSimple/naive-ui#2270]
### This function solves the problem (这个功能解决的问题)
表单中含有颜色选择器时，当颜色选择器的值不是通过色板选择，而是在打开的颜色选择面板中的输入框中输入时，不会自动跳转到表单第一个元素
### Expected API (期望的 API)
可选择表单是否自动获取焦点

**Comment by 07akioni** [comment]
有 prop 可以用，把 autofocus 设为 false

**Comment by HX1194361432** [comment]
我不能每个都输入框都设置啊，之前也是不会自动获取焦点的，是更新了naive版本之后出现的情况

**Comment by 07akioni** [comment]
> 我不能每个都输入框都设置啊，之前也是不会自动获取焦点的，是更新了naive版本之后出现的情况

给 Modal 或者 drawer 设置

**Comment by 07akioni** [comment]
> autoFocus默认可否设置为false 默认false不改变原来的行为，新代码如果要使用再显式设置true就好了。

这行为是符合 a11y 的，是设 Modal 的 autofocus

再改又是 breaking 了，没必要，默认开着是个好的实践

**Comment by thankwsx** [comment]
> 

哈哈，反正已经有过breaking了，能够克制也能表示理解吧。
