### ISSUE TITLE
数据表格：表格行点击->当前行高亮

### ISSUE THREAD

**Issue by kuyzuli-smt** [TuSimple/naive-ui#2272]
### This function solves the problem (这个功能解决的问题)
解决主从表联动问题；
### Expected API (期望的 API)
数据表的属性,增加onClickRow:(row:object)=>void; currentRowChange:(row:object) 和highlightrow(row-key)方法

**Comment by Talljack** [comment]
这个可以解决你的问题　https://www.naiveui.com/zh-CN/os-theme/components/data-table#row-props
