### ISSUE TITLE
Upload组件支持多选

### ISSUE THREAD

**Issue by idanran** [TuSimple/naive-ui#2277]
### This function solves the problem (这个功能解决的问题)
多选上传
### Expected API (期望的 API)
```
<n-upload multiple>
    <n-button>上传文件</n-button>
</n-upload>
```

**Comment by idanran** [comment]
> ### This function solves the problem (这个功能解决的问题)
> 多选上传
> 
> ### Expected API (期望的 API)
> multiple

**Comment by 07akioni** [comment]
多选本身就支持吧，不支持目录而已

**Comment by idanran** [comment]
> 多选本身就支持吧，不支持目录而已

啊这，是我眼睛不太好。🤣
