### ISSUE TITLE
请问NativeUi代码中是否包含了dom和window对象操作?我想用在uniapp里面使用，NativeUi是否跨端兼容?

### ISSUE THREAD

**Issue by ailuhaosi** [TuSimple/naive-ui#2283]
### This function solves the problem (这个功能解决的问题)
我想用在uniapp里面使用NativeUi，请问NativeUi是否跨端兼容，因为uniapp要求无dom的vue组件才能跨端兼容。
或者大多数组件跨端兼容也可以。
### Expected API (期望的 API)
``

**Comment by 07akioni** [comment]
不支持跨端，实现上没什么可能性，建议使用别的库
