### ISSUE TITLE
[CSS] class was overwritten by tailwindcss3 Preflight

### ISSUE THREAD

**Issue by uruz-7** [TuSimple/naive-ui#2285]
### TuSimple/naive-ui version (版本)
2.24.6

### Vue version (Vue 版本)
3.2.29

### Browser and its version (浏览器及其版本)
Chrome Version 97.0.4692.99 (Official Build) (x86_64)

### System and its version (系统及其版本)
macOS 12.1 (21C52)

### Node version (Node 版本)
v16

### Reappearance link (重现链接)
https://github.com/uruz-7/tailwindcss3-naive-ui-reproduction

### Reappearance steps (重现步骤)
```
pnpm install 
pnpm vite
```

### Expected results (期望的结果)
background color is not overwritten

### Actual results (实际的结果)
background color is overwritten

### Remarks (补充说明)
This issue (#1808) still occurs with latest version "naive-ui": "2.24.6", "tailwindcss": "3.0.16".
这个issue(#1808)在最新版本里仍可重现。

Tailwind css preflight: https://tailwindcss.com/docs/preflight

<img src="https://raw.githubusercontent.com/uruz-7/tailwindcss3-naive-ui-reproduction/master/image/Screen%20Shot%202022-01-26%20at%2015.35.40.png">

**Comment by Sepush** [comment]
可以尝试一下这个方法
https://www.naiveui.com/zh-CN/os-theme/docs/style-position

**Comment by uruz-7** [comment]
It worked. Thanks!

**Comment by weizhiwen** [comment]
> you can use the following solution. 可以尝试一下这个解决方案。 https://www.naiveui.com/en-US/os-theme/docs/style-position https://www.naiveui.com/zh-CN/os-theme/docs/style-position

链接失效了

**Comment by Sepush** [comment]
> > you can use the following solution. 可以尝试一下这个解决方案。 https://www.naiveui.com/en-US/os-theme/docs/style-position https://www.naiveui.com/zh-CN/os-theme/docs/style-position
> 
> 链接失效了

updated

**Comment by weizhiwen** [comment]
> > > you can use the following solution. 可以尝试一下这个解决方案。 https://www.naiveui.com/en-US/os-theme/docs/style-position https://www.naiveui.com/zh-CN/os-theme/docs/style-position
> > 
> > 
> > 链接失效了
> 
> updated

![image](https://user-images.githubusercontent.com/22706559/169697035-65c2636d-a490-4bcc-8cd5-1d383d6b0816.png)
打开是官网首页

**Comment by 07akioni** [comment]
https://www.naiveui.com/zh-CN/os-theme/docs/style-conflict

**Comment by Developer27149** [comment]
还有一招，从tailwind入手，不引入@base的preflight.css，单独下载一份修改需要修改的地方。
[https://unpkg.com/tailwindcss@3.2.4/src/css/preflight.css](https://unpkg.com/tailwindcss@3.2.4/src/css/preflight.css)

**Comment by qindongliang** [comment]
The real reason is that tailwind has a preset default style of Preflight, which is friendly to new projects, but when we integrate tailwindcss into existing projects, it will cause style conflicts, we only need to disable this tailwindcss Preflight The style settings in your tailwind.config.js or tailwind.config.cjs
```ts
module.exports = {
  corePlugins: {
    preflight: false,
  }
}
```
Refer to tailwind css official website for explanation：
https://tailwindcss.com/docs/preflight#disabling-preflight

**Comment by czhlin** [comment]
其实保持：1.tailwind 2.naive-ui 3.main.css的顺序是最合理的
所以可以在html中这样修改

In fact, maintaining the order of 1.tailwind 2.naive-ui 3.main.css is the most reasonable, so it can be modified like this in html
```html
<link rel="stylesheet" href="/tailwind.css" />
<meta name="naive-ui-style" />
```
```javascript
// main.ts
import 'uno.css'
import '~/styles/main.css'
```
