### ISSUE TITLE
文档添加issue状态

### ISSUE THREAD

**Issue by jahnli** [TuSimple/naive-ui#2286]
### This function solves the problem (这个功能解决的问题)
更清楚的查询未在文档中体现出来的问题和解决方案
有概率减少多余的issue
### Expected API (期望的 API)
文档添加issue状态
![image](https://user-images.githubusercontent.com/20943608/151122671-c7d887a1-6124-49c6-87c0-d18073e3d531.png)
参考 https://tdesign.tencent.com/vue-next

**Comment by Talljack** [comment]
我感觉不是很有必要 @07akioni

**Comment by Sepush** [comment]
没必要+1

**Comment by 07akioni** [comment]
没必要，在现有开发资源下纯属样子货
