### ISSUE TITLE
How to use the Message outside a vue component?

### ISSUE THREAD

**Issue by B1anker** [TuSimple/naive-ui#229]
### This function solves the problem (这个功能解决的问题)
make it easier to use the Message

### Expected API (期望的 API)
import { message } from 'naive-ui';

message.info('xxx');

**Comment by amadeus711** [comment]
Sorry, the Issues don't answer questions about usage, you can join the community to ask questions: 
- [Discord](https://discord.gg/Pqv7Mev5Dd)
- DingTalk Group 33482509
