### ISSUE TITLE
建议Dropdown组件支持设置按钮文字颜色

### ISSUE THREAD

**Issue by idanran** [TuSimple/naive-ui#2292]
### This function solves the problem (这个功能解决的问题)
设置按钮文字颜色（例如,设置为白色）
### Expected API (期望的 API)
color="#FFFFFF"

**Comment by Sepush** [comment]
button 组件暗色模式下有白色文字，但是亮色模式下的文字不应该是白色

**Comment by Talljack** [comment]
文字颜色自己设置或者使用主题变量修改
