### ISSUE TITLE
Button组件设置文字颜色不生效

### ISSUE THREAD

**Issue by idanran** [TuSimple/naive-ui#2294]
### TuSimple/naive-ui version (版本)
2.24.6

### Vue version (Vue 版本)
3.2.29

### Browser and its version (浏览器及其版本)
Chrome（97）

### System and its version (系统及其版本)
Windows（10)

### Reappearance link (重现链接)
https://codepen.io/idanran/pen/PoOoMZG

### Reappearance steps (重现步骤)
导入组件后,肉眼观察

### Expected results (期望的结果)
设置为白色

### Actual results (实际的结果)
保持原颜色

**Comment by Sepush** [comment]
`<n-button color="#FFF">登录</n-button>` 请查看文档
