### ISSUE TITLE
Vertical view for DatePicker in range type

### ISSUE THREAD

**Issue by setterlee** [TuSimple/naive-ui#2297]
### This function solves the problem (这个功能解决的问题)
DatePicker "type=range"looks ok in wide screens but in narrow screens like mobile devices just appear one and a half calendars
### Expected API (期望的 API)
a vertical mode (one calendar over another) maybe help or an api property to set just one calendar for type range.

**Comment by 07akioni** [comment]
We mainly focus on pc. For mobile device you should use 2 date picker rather than a range picker.

A picker in vertical view may still overflow a screen in most case.

Eg. iPhone 7 screen has a height of 667px height.

**Comment by setterlee** [comment]
> We mainly focus on pc. For mobile device you should use 2 date pickers rather than a range picker.
> 
> A picker in vertical view may still overflow a screen in most case.
> 
> Eg. iPhone 7 screen has a height of 667px.

and a property to show just one calendar in range mode???
