### ISSUE TITLE
表格新增右键菜单

### ISSUE THREAD

**Issue by wei1034937343** [TuSimple/naive-ui#2303]
### This function solves the problem (这个功能解决的问题)
解决页面受限，表格操作按钮过多，及便捷操作
### Expected API (期望的 API)
如 View UI，或类似表格分页，整合成根据json数据渲染
<template>
    <Table
        context-menu
        show-context-menu
        border
        :columns="columns1"
        :data="data1"
        @on-contextmenu="handleContextMenu"
    >
        <template slot="contextMenu">
            <DropdownItem @click.native="handleContextMenuEdit">编辑</DropdownItem>
            <DropdownItem @click.native="handleContextMenuDelete" style="color: #ed4014">删除</DropdownItem>
        </template>
    </Table>
</template>

![image](https://user-images.githubusercontent.com/28970254/151366219-da886fe3-d53d-4861-a81d-3f54c9dac34e.png)

**Comment by 07akioni** [comment]
不会增加功能，会补充个使用现有功能组合的文档
