### ISSUE TITLE
建议Card组件支持自定义header-extra插槽样式

### ISSUE THREAD

**Issue by idanran** [TuSimple/naive-ui#2304]
### This function solves the problem (这个功能解决的问题)
自定义header-extra插槽样式
### Expected API (期望的 API)
header-extra-style:""

**Comment by Sepush** [comment]
你可以直接用 `style`

**Comment by idanran** [comment]
> 你可以直接用 `style`

插槽可以直接用吗？

**Comment by Sepush** [comment]
包一层 span div 之类的元素 然后在上面设置你想要的样式

**Comment by idanran** [comment]
> 包一层 `span` `div` 之类的元素 然后在上面设置你想要的样式

我想直接设置插槽的样式,,你说的我也试过,没能解决问题

**Comment by 07akioni** [comment]
> > 包一层 `span` `div` 之类的元素 然后在上面设置你想要的样式
> 
> 我想直接设置插槽的样式,,你说的我也试过,没能解决问题

详细说说？

**Comment by idanran** [comment]
> > > 包一层 `span` `div` 之类的元素 然后在上面设置你想要的样式
> > 
> > 我想直接设置插槽的样式,,你说的我也试过,没能解决问题
> 
> 详细说说？

我想给header-extra设置宽度，以避免子元素内文字过长而挤占header空间。当我尝试给子元素设置宽度时，这是无效的。当我用开发者工具给header-extra设置宽度时，问题得到解决。

**Comment by idanran** [comment]
求支持，谢谢。

**Comment by 07akioni** [comment]
![image](https://user-images.githubusercontent.com/18677354/151492650-a365fb75-840c-48d5-9a90-6fb42e3663bd.png)

自己调整一下 css

**Comment by idanran** [comment]
> ![image](https://user-images.githubusercontent.com/18677354/151492650-a365fb75-840c-48d5-9a90-6fb42e3663bd.png)
> 
> 自己调整一下 css

当我将宽度设置为50%的时候，就会出现问题。假设有一行比较长的文字，我想让它在大屏上能一行显示完，小屏上显示两行。如果将宽度固定为px，在大屏上将不能一行显示完。

**Comment by idanran** [comment]
> ![image](https://user-images.githubusercontent.com/18677354/151492650-a365fb75-840c-48d5-9a90-6fb42e3663bd.png)
> 
> 自己调整一下 css

那我提个pr吧

**Comment by 07akioni** [comment]
> > ![image](https://user-images.githubusercontent.com/18677354/151492650-a365fb75-840c-48d5-9a90-6fb42e3663bd.png)
> > 自己调整一下 css
> 
> 那我提个pr吧

我想想这块的问题

**Comment by idanran** [comment]
> > > ![image](https://user-images.githubusercontent.com/18677354/151492650-a365fb75-840c-48d5-9a90-6fb42e3663bd.png)
> > > 自己调整一下 css
> > 
> > 那我提个pr吧
> 
> 我想想这块的问题

👌

**Comment by 07akioni** [comment]
考虑了一下，感觉可以加上这个属性

**Comment by 07akioni** [comment]
added in `header-extra-style` prop

**Comment by idanran** [comment]
> 考虑了一下，感觉可以加上这个属性

好的，谢谢。
