### ISSUE TITLE
表格行点击，联动选中复选框

### ISSUE THREAD

**Issue by wei1034937343** [TuSimple/naive-ui#2305]
### This function solves the problem (这个功能解决的问题)
某些业务场景下，业务员需要快速的办理业务，频繁操作表格选中，因复选框太小，不利于用户操作的效率问题
### Expected API (期望的 API)
类似View UI 的高亮行，设置了复选框的情况下，并可以联动选中复选框

![image](https://user-images.githubusercontent.com/28970254/151368551-f69a9c15-0d86-4e8f-a8aa-c2da28adc0fc.png)

**Comment by Talljack** [comment]
感觉不是很常见，或许你可以通过行点击事件拿到row然后去更新checkRowKeys

**Comment by 07akioni** [comment]
用 rowProps 先试试，不行的话可以在这里继续沟通，给个理由

**Comment by wei1034937343** [comment]
已经可以了的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TuSimple/naive-ui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月2日(星期三) 凌晨0:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TuSimple/naive-ui] 表格行点击，联动选中复选框 (Issue #2305)





 
用 rowProps 先试试，不行的话可以在这里继续沟通，给个理由
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
