### ISSUE TITLE
Dynamic Input create button text prop

### ISSUE THREAD

**Issue by sagaban** [TuSimple/naive-ui#2312]
### This function solves the problem (这个功能解决的问题)
When the array that will contain the Dynamic Input values is empty, a "Create" button in shown. It would be nice to be able to specify the button text, and not use a static one.
### Expected API (期望的 API)
Passing a prop to the component (like `create-button-text`) to be used in the button will fix the issue.

```js
  <n-dynamic-input
    v-model:value="value"
    placeholder="Please type here"
    create-button-text="Add a new value"
  />
```

**Comment by tang-junjie** [comment]
The official online doc just indicate that the default value as undefined, could anymoe give an example on how to use this new create-button-props DynamicInput Props?

Thanks a lot!

**Comment by littlestone** [comment]
Could anyone provide an example on how to use this new DynamicInput prop (i.e. create-button-props)? Not able to figure it out simply by the offical doc, thanks!
