### ISSUE TITLE
Data Table to have a scroll event like Async Unfinite Scroll.

### ISSUE THREAD

**Issue by BroJenuel** [TuSimple/naive-ui#2320]
### This function solves the problem (这个功能解决的问题)
Like for example I scroll to the very end of the data, then It will fetch others data and be pushed on the data.
### Expected API (期望的 API)
maybe add an event handler, where it fires when the datatable is scrolled on the very end.
```
<NDataTable ... @scrolledToEnd="myFunction()" />
```

**Comment by 07akioni** [comment]
I don't think this is a proper feature for data-table.

**Comment by danvratil** [comment]
I would welcome this feature too. I'm using data-table to display a possibly very long list of data that's too expensive to fetch from the server in a single request (and store it in the browser) and while I could use pagination, an "infinite" scroll would provide much better user experience in this case.

**Comment by 07akioni** [comment]
> I'm using data-table to display a possibly very long list of data that's too expensive to fetch from the server in a single request (and store it in the browser) and while I could use pagination, an "infinite" scroll would provide much better user experience in this case.

If there are tons of lines, for example 5000, what's the meaning of scroll? Scrolling down from 0, can they wait for async loading for 5000 items? If so it's probably one the first XXX(maybe 500 as most) lines is valuable for user.

**Comment by BroJenuel** [comment]
> > I'm using data-table to display a possibly very long list of data that's too expensive to fetch from the server in a single request (and store it in the browser) and while I could use pagination, an "infinite" scroll would provide much better user experience in this case.
> 
> If there are tons of lines, for example 5000, what's the meaning of scroll? Scrolling down from 0, can they wait for async loading for 5000 items? If so it's probably one the first XXX(maybe 500 at most) lines are valuable for user.

I think we can fetch like 15 rows, everytime a user scrolls to the end. Or 50 rows etc.

**Comment by 07akioni** [comment]
> > > I'm using data-table to display a possibly very long list of data that's too expensive to fetch from the server in a single request (and store it in the browser) and while I could use pagination, an "infinite" scroll would provide much better user experience in this case.
> > 
> > 
> > If there are tons of lines, for example 5000, what's the meaning of scroll? Scrolling down from 0, can they wait for async loading for 5000 items? If so it's probably one the first XXX(maybe 500 at most) lines are valuable for user.
> 
> I think we can fetch like 15 rows, everytime a user scrolls to the end. Or 50 rows etc.

If only 15 rows are visible for users. Why not just using pagination.
