### ISSUE TITLE
`to` router-link props for button

### ISSUE THREAD

**Issue by ruihildt** [TuSimple/naive-ui#2321]
### This function solves the problem (这个功能解决的问题)
Adds the possibility to wrap the whole button as a router-link.
### Expected API (期望的 API)
<n-button to='/my-route'>Link to another view</n-button>

**Comment by 07akioni** [comment]
We won't encapsulate router link inside button.

**Comment by 07akioni** [comment]
That would make implementation entangled.

**Comment by 07akioni** [comment]
You should use custom router link.

Ref https://next.router.vuejs.org/guide/advanced/extending-router-link.html#extending-routerlink

**Comment by qiquanlu** [comment]
tl;dr
```javascript
<router-link v-slot="{ navigate }" :to="{ name: 'dashboard' }" custom>
  <n-button @click="navigate">Dashboard</n-button>
</router-link>
```

**Comment by gijsroge** [comment]
@qiquanlu the problem with this approach is that there is no native link rendered. So control + click doesn't open in a new tab etc..

It would be better if there was somehow a way of using the button styles on an actual `<a href>`. But I don't see any way of doing that. 

Thanks for the possible solution tho!

**Comment by qiquanlu** [comment]
@gijsroge you could add tag="a", you can check the [ button document](https://www.naiveui.com/en-US/light/components/button#tag.vue) here

**Comment by gijsroge** [comment]
Just for anyone stumbling upon this

Here is an example

```
<router-link v-slot="{ navigate, href }" to="/your/route/here" custom>
    <n-button
      tag="a"
      v-bind="$attrs"
      :href="href"
      type="primary"
      @click="navigate"
    >
     text
    </n-button>
  </router-link>
```

**Comment by dieegov** [comment]
Here's a short implementation using tsx.

```
export const CustomButton = defineComponent({
    props: {
        ...RouterLink.props,
    },
    setup(props, attrs) {

        const { navigate, href, route, isActive, isExactActive } = useLink(props)

        return () => (
            <NButton type="primary" tag="a" href={href} onClick={navigate}>
                {{
                    default: () => props.content
                }}
            </NButton>
        )
    }
})
```

So you can use like this

```
<CustomButton to={{name: "your-router-name"}} />
```
