### ISSUE TITLE
栅格n-grid-item提供align功能

### ISSUE THREAD

**Issue by stan12138** [TuSimple/naive-ui#2325]
### This function solves the problem (这个功能解决的问题)
栅格在使用中，例如n-grid-item span=1，其中元素宽度小于这个栅格的宽度，此时经常会希望元素可以做到左对齐，右对齐，或者居中等。但是n-gi看起来并不支持align，是否可以支持呢？
### Expected API (期望的 API)
<n-gi :span="1" align="center">

**Comment by stan12138** [comment]
<n-grid x-gap="12" :cols="9">
            <n-gi :offset="3" :span="3" justify="center">
                <n-pagination v-model:page="page" :page-count="pageNum" style="margin-bottom: 15px;" />
            </n-gi>
        </n-grid>
这样吗？看起来好像并不行

**Comment by 07akioni** [comment]
> ```
>     <n-grid x-gap="12" :cols="9">
>         <n-gi :offset="3" :span="3" justify="center">
>             <n-pagination v-model:page="page" :page-count="pageNum" style="margin-bottom: 15px;" />
>         </n-gi>
>     </n-grid>
> ```
> 
> 这样吗？看起来好像并不行

我的意思是如果有这个属性，应该叫 justify

**Comment by 07akioni** [comment]
![image](https://user-images.githubusercontent.com/18677354/152333167-f2838808-4b35-42f6-94bc-f3778a7a2db9.png)

这么写就行了
