### ISSUE TITLE
Carousel添加属性

### ISSUE THREAD

**Issue by eagle0898** [TuSimple/naive-ui#2340]
### This function solves the problem (这个功能解决的问题)
现在Carousel组件的功能已经比较强大了，当effect的值为card时，如果能增加一个属性用来定义主Card和其它两个Card的高度比就更好了。例如，添加一个heightScale属性，它的值可以是1或1.2这样的值。
### Expected API (期望的 API)
heightScale

**Comment by amadeus711** [comment]
需要考虑一下更好的 api 实现

**Comment by eagle0898** [comment]
您的邮件已收到。
