### ISSUE TITLE
n-tag 选中时样式bug：background-color: 'var(--n-color-checked)

### ISSUE THREAD

**Issue by zhanlizhu530** [TuSimple/naive-ui#2342]
### TuSimple/naive-ui version (版本)
2.25.1

### Vue version (Vue 版本)
3.2.26

### Browser and its version (浏览器及其版本)
chrome89

### System and its version (系统及其版本)
windows10

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/tag

### Reappearance steps (重现步骤)
.n-tag.n-tag--checkable.n-tag--checked {
    color: var(--n-text-color-checked);
    background-color: 'var(--n-color-checked);
}

### Expected results (期望的结果)
删除多余单引号即可

### Actual results (实际的结果)
由于多了单引号导致背景色失效，官网文档中的demo也会出现该问题

**Comment by 07akioni** [comment]
fixed in 5458ce445fba6b803c1c01ab551de66878674e48
