### ISSUE TITLE
Add `Download` component

### ISSUE THREAD

**Issue by Air-Cooled** [TuSimple/naive-ui#2346]
### This function solves the problem (这个功能解决的问题)
Download Progress Visualization
### Expected API (期望的 API)
Bind a link and click to download files, etc.
Triggers a browser download, or displays progress, network speed, remaining time, and so on

**Comment by Air-Cooled** [comment]
Sometimes I need to carry a token or a request header

**Comment by 07akioni** [comment]
I'm not sure whether we should make it.
I think a composable may be better a component.

**Comment by Air-Cooled** [comment]
The browser seems to be able to do this only through the `<a/>` tag, but it can't carry a header like token; do you have a better solution?

Other download methods are basically through the Blob object to save the file, but such a large file will have to wait a long time to pop up to save the file, in the meantime how long is unknown;

So i want to have a visual download component that lets user know what doing

Or let the button support the background color as the progress bar? Can calculate progress with `onDownloadProgress`

**Comment by Air-Cooled** [comment]
> > I'm not sure whether we should make it. I think a composable may be better a component.
> 
> Since there's no common pattern for download a file.
> 
> It can a modal, a list, a popover, or just let browser do it.

The browser seems to be able to do this only through the `<a/>` tag, but it can't carry a header like token; do you have a better solution?

Other download methods are basically through the Blob object to save the file, but such a large file will have to wait a long time to pop up to save the file, in the meantime how long is unknown;

So i want to have a visual download component that lets user know what doing

Or let the button support the background color as the progress bar? Can calculate progress with `onDownloadProgress`

**Comment by Air-Cooled** [comment]
Of course `Progress` can be visualized in combination with `onDownloadProgress`, hoping to provide an easy way to do this, preferably including the remaining hours of network speed, etc. 

Or you can trigger the browser download for me by using the url and token

**Comment by Air-Cooled** [comment]
Of course `Progress` can be visualized in combination with `onDownloadProgress`, hoping to provide an easy way to do this, preferably including the remaining hours of network speed, etc. 

Or you can trigger the browser download for me by using the url and token

**Comment by 07akioni** [comment]
> Of course `Progress` can be visualized in combination with `onDownloadProgress`, hoping to provide an easy way to do this, preferably including the remaining hours of network speed, etc.
> 
> Or you can trigger the browser download for me by using the url and token

Those are totally different interactions. The demand is vague for a component.

**Comment by Air-Cooled** [comment]
How Do I trigger the browser download? How to carry token at the same time? Whether it can be encapsulated as a component is, I believe, the best solution for a simple download

**Comment by 07akioni** [comment]
1. https://stackoverflow.com/questions/11620698/how-to-trigger-a-file-download-when-clicking-an-html-button-or-javascript
2. https://stackoverflow.com/questions/29452031/how-to-handle-file-downloads-with-jwt-based-authentication

**Comment by junmaqiang** [comment]
@07akioni  https://www.naiveui.com/zh-CN/os-theme/components/menu 官方文档顶部的搜索功能失效了？

**Comment by junmaqiang** [comment]
@07akioni https://www.naiveui.com/zh-CN/  官方文档里面 很多组件都没有对齐属性

**Comment by 07akioni** [comment]
> @07akioni https://www.naiveui.com/zh-CN/os-theme/components/menu 官方文档顶部的搜索功能失效了？

没失效

**Comment by 07akioni** [comment]
> @07akioni https://www.naiveui.com/zh-CN/ 官方文档里面没找到 a 标签的具体用法，没有这个组件？

typography 里面，还有 a 标签是原生元素，即使没有 ui 你也可以用

**Comment by junmaqiang** [comment]
> 
我发现了，是和搜索的关键词要和组件名有关才可以

**Comment by 07akioni** [comment]
If you have further disscussion, I'll reopen the issue.
