### ISSUE TITLE
Dropdown、Tabs ssr error

### ISSUE THREAD

**Issue by cinob** [TuSimple/naive-ui#2347]
### TuSimple/naive-ui version (版本)
2.25.0

### Vue version (Vue 版本)
3.2.26

### Browser and its version (浏览器及其版本)
Chrome/97.0.4692.99

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://github.com/cinob/naive-ui-ssr-issue

### Reappearance steps (重现步骤)
Internal server error: document is not defined
at Object.queryElement (xxx\node_modules\.pnpm\css-render@0.15.8\node_modules\css-render\lib\utils.js:17:5)

### Expected results (期望的结果)
support ssr

### Actual results (实际的结果)
not support ssr

**Comment by Talljack** [comment]
![image](https://user-images.githubusercontent.com/34439652/155085723-50ca3999-a44f-46d2-8935-5e5f6cacd731.png)
![image](https://user-images.githubusercontent.com/34439652/155085757-6d66fea2-7451-4ca2-8077-dd0603b49c09.png)
You need to use setup function of @css-render/vue3-ssr, please ref [naive-ssr](https://www.naiveui.com/zh-CN/os-theme/docs/ssr).
