### ISSUE TITLE
期望 Modal 组件增加一个 loading 的 API

### ISSUE THREAD

**Issue by feligo887** [TuSimple/naive-ui#2353]
### This function solves the problem (这个功能解决的问题)
现在 Modal 组件是没有loading 功能的，只能用 n-spin 来配合使用，但是使用 spin 组件之后，就会有一些小问题，
spin 来包裹 content 部分 <template #header> 中的title就显示为空，spin不包裹 <template #header> 的话，用户就可以点击到 close 按钮。
### Expected API (期望的 API)
:loading = ture | false；

**Comment by amadeus711** [comment]
![image](https://user-images.githubusercontent.com/46394163/152959011-48cf99f8-1890-4d10-ba97-ae91fcc2bef7.png)
