### ISSUE TITLE
Auto Complete: Remote source

### ISSUE THREAD

**Issue by Nikhilchandra-Rathod** [TuSimple/naive-ui#236]
### This function solves the problem (这个功能解决的问题)
We can search things from remote source
### Expected API (期望的 API)
<n-autocomplete remote @on-search="handleSearch(keyword)"></n-autocomplete>

**Comment by 07akioni** [comment]
> ### This function solves the problem (这个功能解决的问题)
> We can search things from remote source
> 
> ### Expected API (期望的 API)
> <n-autocomplete remote @on-search="handleSearch(keyword)">

All the options of auto complete is controlled by user, it can be used for remote searching.

**Comment by Nikhilchandra-Rathod** [comment]
Can we have loading state for autocomplete ?

**Comment by 07akioni** [comment]
> Can we have loading state for autocomplete ?

That's okay and we will implement it.

**Comment by Nikhilchandra-Rathod** [comment]
One more question, Is there any way to expose all the css common variables at :root {} level ?

**Comment by Nikhilchandra-Rathod** [comment]
> > Can we have loading state for autocomplete ?
> 
> That's okay and we will implement it.

Thanks :)
