### ISSUE TITLE
n-input status "success" seems not working

### ISSUE THREAD

**Issue by nicolasxu** [TuSimple/naive-ui#2375]
### TuSimple/naive-ui version (版本)
2.25.0

### Vue version (Vue 版本)
3.2.26

### Browser and its version (浏览器及其版本)
Chrome latest

### System and its version (系统及其版本)
MacOS

### Reappearance link (重现链接)
https://codesandbox.io/s/3p9ws

### Reappearance steps (重现步骤)
Change 
<n-input status="warning" placeholder="" />
to
<n-input status="success" placeholder="" />

I expect input border will be green, but it is gray. 

### Expected results (期望的结果)
border will be green

### Actual results (实际的结果)
border will be gray

**Comment by 07akioni** [comment]
Success is designed as normal state.
