### ISSUE TITLE
n-select建议增加label-field和value-field

### ISSUE THREAD

**Issue by yudan215** [TuSimple/naive-ui#2384]
### This function solves the problem (这个功能解决的问题)
选项如果从API获取，可以自定义label-field和value-field简单进行渲染
### Expected API (期望的 API)
自定义label-field和value-field

**Comment by 07akioni** [comment]
map 一下吧，我觉得加这个的理由不是很强力

**Comment by 07akioni** [comment]
你如果可以举出一些场景 map 解决起来非常困难，我可以考虑

**Comment by 07akioni** [comment]
不加的动机是我觉得这个并不比较大的简化用户的使用过程。

这不像树形结构，这个用户处理起来确实很困难，那么我们加上是能解决用户大问题的。

**Comment by yudan215** [comment]
好的

**Comment by 07akioni** [comment]
或者赶上我比较闲的时候说不定也就加了
