### ISSUE TITLE
feat: adjustable/flexible dialog width

### ISSUE THREAD

**Issue by OrbisK** [TuSimple/naive-ui#2386]
### This function solves the problem (这个功能解决的问题)
The width of the dialog is currently static. Some components e.g. `<n-transfer />` stick over the edges.
### Expected API (期望的 API)
```
dialog.warning({
    ...
    width: '200px' || flexWidth: true
  });
```

**Comment by 07akioni** [comment]
I found it's already supported just not documented. So just use it.
