### ISSUE TITLE
No data in the Select "Version" and "Vue Version" of the Issue Helper

### ISSUE THREAD

**Issue by chyj4747** [TuSimple/naive-ui#2388]
### This function solves the problem (这个功能解决的问题)
I dont know whether it is a CORS problem but the browser gives me the error bellow:

Access to XMLHttpRequest at 'https://registry.npm.taobao.org/naive-ui' from origin 'https://naive-ui.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
### Expected API (期望的 API)
None

**Comment by 07akioni** [comment]
It's not relevant with us. You can use other registry or contact taobao npm.

**Comment by amadeus711** [comment]
Thank you for your feedback. The bug has been fixed.
