### ISSUE TITLE
[Bug] Select in Modal. The selection list is showed behind the modal.（模态框里的选择器，下拉列表会显示在模态框后面）

### ISSUE THREAD

**Issue by chyj4747** [TuSimple/naive-ui#2389]
### This function solves the problem (这个功能解决的问题)
This is a bug but there is a problem in the Issue Helper so that I can't report Bug.
这是个bug，但由于Issue Helper有bug，可能因为跨域的关系，总之两个Version选择框里无数据，导致无法提交，所以只能用需求提交bug了

Reproduce:
Create a Modal and put a Select with several options into it. Then click the select.
创建一个模态框，在模态框里放一个选择器，点击选择器展开列表

Expected:
The options of Select shows normally.
选择器列表正常展开

Actually happening:
The options of Select shows behind the modal.
选择器列表被渲染在了模态框后面

Comment:
It works fine with naive-ui v2.21.2. Just broke when I updated naive-ui to v2.25.2.
我之前用的naive-ui版本是2.21.2，显示正常，今天刚升级成2.25.2，就出现bug了

edit:
NColorPicker has the same problem. Maybe the components that can open another element all have this problem.
刚刚发现颜色选择器也有一样的问题，可能所有能打开另一个视图或窗口的组件都有这个问题
### Expected API (期望的 API)
None

**Comment by chyj4747** [comment]
我自己写了个简单的demo，发现是正常的。。

然后看了下在我的项目里会有两个n-modal-container，第一个是空的z-index:2000，第二个z-index:2001才是naive-ui用来显示模态框的，所以下拉列表之类的z-index:2000就被模态框遮挡了

被遮挡的原因就是这个，现在的问题就变成了为什么会有两个n-modal-container，原因我还没找到，不知道你们官方有没有什么想法？因为之前2.21.2的时候没出现这个问题

**Comment by 07akioni** [comment]
> 我自己写了个简单的demo，发现是正常的。。
> 
> 然后看了下在我的项目里会有两个n-modal-container，第一个是空的z-index:2000，第二个z-index:2001才是naive-ui用来显示模态框的，所以下拉列表之类的z-index:2000就被模态框遮挡了
> 
> 被遮挡的原因就是这个，现在的问题就变成了为什么会有两个n-modal-container，原因我还没找到，不知道你们官方有没有什么想法？因为之前2.21.2的时候没出现这个问题
> 
> edit: 我有一个应用场景是模态框里要再打开模态框，会不会跟这个有关？

可能和这个有点关系？我也不是特别确定

**Comment by 07akioni** [comment]
> 最好还是能给个复现，我自己也会试试

我自己写了一个嵌套的 modal，没有遇到这种问题，我感觉是你触发了某些非常诡异的条件（也可能是你写错了），引发了一点 zindex 的 bug。

**Comment by 07akioni** [comment]
现在需要一个复现，不然感觉有点困难了

**Comment by chyj4747** [comment]
正在尝试复现，不过目前我自己也复现不了。。

试验之后发现跟嵌套模态框没关系

在我自己的项目中，bug出现的流程是先打开一个模态框A(zindex: 2000)，然后模态框A关闭之后使用vue的router和markRaw(defineAsyncComponent(() => import(".......")))动态创建了部分新界面，在新界面中，再打开一个模态框B(zindex: 2001)，此时模态框B中选择框创建的v-binder-follower-container就有会出现zindex: 2000

如果打开模态框的按钮还有popover，这个也会添加v-binder-follower-container，打开A的按钮先出现popover(zindex:2000)，然后打开模态框A(zindex:2000)，再打开模态框B(zindex:2001)，这时B中的下拉框的zindex就是2001，显示正确

再进一步，跟模态框A同层还有一个模态框C，先显示A的popover(zindex: 2000)，打开模态框A(zindex: 2000)，然后打开模态框C(zindex: 2001)，之后再打开模态框B(zindex: 2002)，此时B里的下拉框zindex是2001，显示再模态框B后面

从上述三个测试结果感觉模态框的zindex和v-binder-follower-container是分开计算的，但写复现demo的时候好像又不是这样
我再试试，如果实在复现不了，那我只能去跟你们的代码了

**Comment by 07akioni** [comment]
> 正在尝试复现，不过目前我自己也复现不了。。
> 
> 试验之后发现跟嵌套模态框没关系
> 
> 在我自己的项目中，bug出现的流程是先打开一个模态框A(zindex: 2000)，然后模态框A关闭之后使用vue的router和markRaw(defineAsyncComponent(() => import(".......")))动态创建了部分新界面，在新界面中，再打开一个模态框B(zindex: 2001)，此时模态框B中选择框创建的v-binder-follower-container就有会出现zindex: 2000
> 
> 如果打开模态框的按钮还有popover，这个也会添加v-binder-follower-container，打开A的按钮先出现popover(zindex:2000)，然后打开模态框A(zindex:2000)，再打开模态框B(zindex:2001)，这时B中的下拉框的zindex就是2001，显示正确
> 
> 再进一步，跟模态框A同层还有一个模态框C，先显示A的popover(zindex: 2000)，打开模态框A(zindex: 2000)，然后打开模态框C(zindex: 2001)，之后再打开模态框B(zindex: 2002)，此时B里的下拉框zindex是2001，显示在模态框B后面
> 
> 从上述三个测试结果感觉模态框的zindex和v-binder-follower-container是分开计算的，但写复现demo的时候好像又不是这样 我再试试，如果实在复现不了，那我只能去跟你们的代码了

你看看 node_modules 里面 vueuc 和 naive-ui 是不是引用了不同的 vdirs 包

**Comment by 07akioni** [comment]
正常来说应该是共用一个 vdirs，如果不是的话就可能说你说的问题

**Comment by chyj4747** [comment]
解决了……我把naive-ui删掉重装后就好了

那我大概知道问题了，因为我更新naive-ui的时候我的程序正在跑，可能一部分文件被占用所以写入失败了，也就是更新不完全，才导致了这个问题，bug的原因也确实没有共用一个vdirs，断点只看到模态框在z-index-manager里增加zindex，follower增加zindex不会被断住，应该就是用了不同的库

感谢回复

**Comment by 07akioni** [comment]
不客气

**Comment by fxjs** [comment]
![image](https://user-images.githubusercontent.com/3682415/218059296-68db76f8-988f-4e69-b92b-49ea3ed0224b.png)
在el-dialog里写n-select会出现下拉在背景遮罩后面（两个库的z-index有冲突）， 有没办法适配呢？
