### ISSUE TITLE
希望更完善的布局组件

### ISSUE THREAD

**Issue by confuseder** [TuSimple/naive-ui#2390]
### This function solves the problem (这个功能解决的问题)
目前的布局组件稍有欠缺，我明白开发者希望更简洁的组件，但是类似element-ui的布局组件（row、col、main），是更加易用的。目前的布局容器是欠缺的，缺乏对整个页面布局的统一配置能力，开发者需要额外增加更多的css代码。
### Expected API (期望的 API)
参见https://element-plus.gitee.io/zh-CN/component/container.html

**Comment by confuseder** [comment]
抱歉打扰，不尽感激。

**Comment by 07akioni** [comment]
row 和 col 有，有啥问题呢？

**Comment by 07akioni** [comment]
你发的链接里面 layout 功能也都有了

**Comment by Preyou** [comment]
然而文档里没有

**Comment by 07akioni** [comment]
> 然而文档里没有

在这里 https://www.naiveui.com/zh-CN/os-theme/components/legacy-grid
