### ISSUE TITLE
Grid: when use inside wrapper component grid item span not working

### ISSUE THREAD

**Issue by Nikhilchandra-Rathod** [TuSimple/naive-ui#240]
### TuSimple/naive-ui version (版本)
2.13.0

### Vue version (Vue 版本)
3.1.1

### Browser and its version (浏览器及其版本)
Chrome(91.0.4472.114)

### System and its version (系统及其版本)
Windows 10

### Reappearance link (重现链接)
https://codesandbox.io/s/intelligent-yalow-5jjy6?file=/src/App.vue

### Reappearance steps (重现步骤)
Open codesendbox in browser

### Expected results (期望的结果)
- It should span grid item as defined in :span props

### Actual results (实际的结果)
- Its always span by 1

**Comment by 07akioni** [comment]
This is expected behavior (and we may need to document it later). Since Vue use slot (render props) as children. It's not efficient for us to unwrap the incoming VNode layer by layer.

React doesn't work like this so it's okay to unwrap some layers.

**Comment by 07akioni** [comment]
@Fnzero 补充一下相关的文档，`n-grid` 里面只能放 `n-grid-item`，不能放别的，也不能包装 `n-grid-item`

**Comment by Nikhilchandra-Rathod** [comment]
- Can we have responsive grid items ?
- Like: from ant design
- <a-row>
    <a-col :xs="{ span: 5, offset: 1 }" :lg="{ span: 6, offset: 2 }">
      Col
    </a-col>
    <a-col :xs="{ span: 11, offset: 1 }" :lg="{ span: 6, offset: 2 }">
      Col
    </a-col>
    <a-col :xs="{ span: 5, offset: 1 }" :lg="{ span: 6, offset: 2 }">
      Col
    </a-col>
  </a-row>

**Comment by 07akioni** [comment]
> * Can we have responsive grid items ?
> * Like: from ant design
>   `<a-row> <a-col :xs="{ span: 5, offset: 1 }" :lg="{ span: 6, offset: 2 }"> Col </a-col> <a-col :xs="{ span: 11, offset: 1 }" :lg="{ span: 6, offset: 2 }"> Col </a-col> <a-col :xs="{ span: 5, offset: 1 }" :lg="{ span: 6, offset: 2 }"> Col </a-col> </a-row>`

The grid is responsive. You can see the demo in site. However `offset` won't be supported.
