### ISSUE TITLE
Bug: n-select renderTag closeable triggers dropdown

### ISSUE THREAD

**Issue by OrbisK** [TuSimple/naive-ui#2405]
### TuSimple/naive-ui version (版本)
2.25.2

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
Opera GX LVL3 (core: 83.0.4254.46)

### System and its version (系统及其版本)
Win 11

### Reappearance link (重现链接)
https://codesandbox.io/s/jolly-fire-pfi0e?file=/src/Demo.vue

### Reappearance steps (重现步骤)
1. Add some tags in select.
2. close them via x

### Expected results (期望的结果)
Dropdown does not trigger.

### Actual results (实际的结果)
Dropdown does trigger :D

**Comment by 07akioni** [comment]
This is expected, you should stop event propagation manually.

We have no way to check whether a click is intended to open or not open the menu.

**Comment by OrbisK** [comment]
ohhh. Thats smart... kinda missed that ^^
