### ISSUE TITLE
淦！主题变量"primaryColor"设置为黄色("yellow")时n-input组件光标消失！！！

### ISSUE THREAD

**Issue by LuckLin520** [TuSimple/naive-ui#2415]
### TuSimple/naive-ui version (版本)
2.25.2

### Vue version (Vue 版本)
3.2.25

### Browser and its version (浏览器及其版本)
Chrome 97.0.4692.71（正式版本） （32 位）

### System and its version (系统及其版本)
windows 10

### Node version (Node 版本)
v16.14.0

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/input

### Reappearance steps (重现步骤)
themeOverrides.js->common->primaryColor:"yellow"

### Expected results (期望的结果)
光标正常显示黄色

### Actual results (实际的结果)
光标看不到/消失

### Remarks (补充说明)
设置成其他颜色能够正常显示（例如：blue），唯独设置黄色光标消失

**Comment by Talljack** [comment]
![image](https://user-images.githubusercontent.com/34439652/154204763-59bba785-d36f-48ae-bcef-6971717fe8a7.png)
我看了下　黄色是显示的
https://codesandbox.io/s/immutable-leaf-s6ncnn?file=/src/App.vue

**Comment by 07akioni** [comment]
不建议用文字颜色，UI 内部会对颜色做运算，RGBA 是最稳的
