### ISSUE TITLE
[Nuxt3]grid组件服务端渲染后自适应有问题，需要手动缩放才能与客户端渲染一样

### ISSUE THREAD

**Issue by Baiyuetribe** [TuSimple/naive-ui#2462]
### TuSimple/naive-ui version (版本)
2.25.2

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
Windows

### Reappearance link (重现链接)
https://stackblitz.com/edit/github-mbmlr5-pbzrrz?file=app.vue

### Reappearance steps (重现步骤)
![grid erro](https://user-images.githubusercontent.com/43716063/154707728-7cec95a3-fb4b-4177-968e-e145fbbeec31.gif)

其余组件在nuxt3里均正常工作，唯独grid组件自适应有问题，实际服务端渲染的首屏无法识别屏幕大小，采用了最小屏效果，手动缩放屏幕后恢复正常，与客户端渲染一样。

### Expected results (期望的结果)
期望服务端渲染后的效果与客户端渲染保持一样

### Remarks (补充说明)
个人能力有限，但是该组件确实很重要，希望可以解决

**Comment by Baiyuetribe** [comment]
根据这几天的实际使用，Nuxt3里naive-ui组件功能都正常，唯独grid响应有问题。类似的，经过测试，element plus和@inkline/inkline服务端渲染正常，盲猜是独立出css所以无异常，缺点是这两个是全部引入css，不像naive-ui是自动按需引入的。
一个正常案例 【inkline模板】：https://stackblitz.com/edit/github-nw7fzh-k8c3nd?file=app.vue 
https://github.com/Baiyuetribe/nuxt3-naive-ui-starter/issues/5#issuecomment-1042896668

**Comment by 07akioni** [comment]
> 根据这几天的实际使用，Nuxt3里naive-ui组件功能都正常，唯独grid响应有问题。类似的，经过测试，element plus和@inkline/inkline服务端渲染正常，盲猜是独立出css所以无异常，缺点是这两个是全部引入css，不像naive-ui是自动按需引入的。 一个正常案例 【inkline模板】：https://stackblitz.com/edit/github-nw7fzh-k8c3nd?file=app.vue [Baiyuetribe/nuxt3-naive-ui-starter#5 (comment)](https://github.com/Baiyuetribe/nuxt3-naive-ui-starter/issues/5#issuecomment-1042896668)

出 css 确实是一个思路，这个提示了我

**Comment by Baiyuetribe** [comment]
该问题应该通用与任意SSR渲染工具，不局限于Nuxt3的SSR模式，要不搞个简单点的纯依赖vite的SSR模式？这样便于开发和调试，要是能跟其他组件一样用CSS抽离解决，估计SSR就正常了

**Comment by 07akioni** [comment]
> > 根据这几天的实际使用，Nuxt3里naive-ui组件功能都正常，唯独grid响应有问题。类似的，经过测试，element plus和@inkline/inkline服务端渲染正常，盲猜是独立出css所以无异常，缺点是这两个是全部引入css，不像naive-ui是自动按需引入的。 一个正常案例 【inkline模板】：https://stackblitz.com/edit/github-nw7fzh-k8c3nd?file=app.vue [Baiyuetribe/nuxt3-naive-ui-starter#5 (comment)](https://github.com/Baiyuetribe/nuxt3-naive-ui-starter/issues/5#issuecomment-1042896668)
> 
> 出 css 确实是一个思路，这个提示了我，基于屏幕宽度的 grid ssr 时候是可以不闪的

我研究了一下，因为 naive 支持了折叠等功能，所以还是不能光靠 CSS

**Comment by 07akioni** [comment]
这个事比我想象的复杂一些，感觉不是很好解决

**Comment by 07akioni** [comment]
> > 这个事比我想象的复杂一些，感觉不是很好解决
> > 要想完善的解决第一需要解决 tail + collapsed 的功能
> > 第二需要解决不闪的问题，这两块代码会不太好处理
> 
> 不闪烁的问题好办，用vue的过渡特效Transion就可以解决

我们说的不是一回事，我说的是这些内容只要上屏了就不会再改

**Comment by 07akioni** [comment]
closed in a89f8b1d03c4c276fdf09d0095f40add7e62b9b8
