### ISSUE TITLE
主题编辑器input设置有bug

### ISSUE THREAD

**Issue by popdo** [TuSimple/naive-ui#2480]
### TuSimple/naive-ui version (版本)
2.25.2

### Vue version (Vue 版本)
3.2.25

### Browser and its version (浏览器及其版本)
edge 版本 93.0.961.38

### System and its version (系统及其版本)
macOs

### Reappearance link (重现链接)
https://www.naiveui.com/ 官网的主题编辑器

### Reappearance steps (重现步骤)
主题编辑器中 Input
1、将border、borderHover、borderDisabled均设置为：1px solid #dee2e6。
2、再将borderFocus改为 1px solid #df0000。
3、最后boxShadowFocus设置为none之后。

会造成表单input的focus状态不更新，必须移动鼠标才会显示出focus效果。

### Expected results (期望的结果)
修复bug

### Actual results (实际的结果)
主题编辑器中 Input-->boxShadowFocus设置为none之后，会造成表单input的focus状态不更新，必须移动鼠标才会显示出focus效果。

**Comment by 07akioni** [comment]
看起来是 focus 的优先级比 hover 高，从直觉上想了想感觉确实应该 focus 强一些
