### ISSUE TITLE
form自定义校验 validator value 参数undefined时返回null 

### ISSUE THREAD

**Issue by lljj-x** [TuSimple/naive-ui#2486]
### TuSimple/naive-ui version (版本)
2.25.2

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
chrome 98.0.4758.102

### System and its version (系统及其版本)
macos 12.1

### Reappearance link (重现链接)
https://codesandbox.io/s/hungry-silence-qo0xpp?file=/src/Demo.vue

### Reappearance steps (重现步骤)
1. 打开如上链接，当清空age时，会设置age为 undefined。
2. 清空age
3. 查看控制台显示 validator value:  null，期望还是undefined

### Expected results (期望的结果)
期望在 validator callback中value为 `undefined` 时，不要默认 `null`

### Actual results (实际的结果)
https://github.com/TuSimple/naive-ui/blob/main/src/form/src/FormItem.tsx#L264

如上代码，在使用 lodash 获取 path value的时候这里做了默认`null` 的操作

### Remarks (补充说明)
不确定这里故意默认 `null` 的原因，会导致实际的表单数据和这里不一致，一些数据校验不符合预期

**Comment by 07akioni** [comment]
你说的非常有道理，当时应该就是没考虑那么多，写错了

然后主要就是我不知道 lodash 会这么处理，以为是有 key 就会返回 key 的，没有 key 才会 fallback
