### ISSUE TITLE
[bug] `upload` did not re-render in controlled manner upon value change

### ISSUE THREAD

**Issue by viztor** [TuSimple/naive-ui#249]
### TuSimple/naive-ui version (版本)
2.13.0

### Vue version (Vue 版本)
3.1.1

### Browser and its version (浏览器及其版本)
Chrome (91.0.4472.114)

### System and its version (系统及其版本)
macOS 11.4

### Reappearance link (重现链接)
https://codesandbox.io/s/nifty-khayyam-96t9q

### Reappearance steps (重现步骤)
upload file

### Expected results (期望的结果)
file list change on error

### Actual results (实际的结果)
did not update

### Remarks (补充说明)
through inspection via vue devtool it's obvious that data has changed but the component did not update

**Comment by viztor** [comment]
@07akioni any thoughts?

**Comment by 07akioni** [comment]
> @07akioni any thoughts?

You didn't config `action` of the upload, so there is no upload progress that actuarlly happens. The file is still in pending status and the progress bar won't display. If you need to show it please take care of the file status too.

**Comment by viztor** [comment]
> > @07akioni any thoughts?
> 
> You didn't config `action` of the upload, so there is no upload progress that actually happens. The file is still in pending status and the progress bar won't display. If you need to show it please take care of the file status too.
> 
> Src code releated:
> ![image](https://user-images.githubusercontent.com/18677354/123362084-b7342c00-d5a2-11eb-9ffa-00bb7b6a5bbd.png)



> > @07akioni any thoughts?
> 
> You didn't config `action` of the upload, so there is no upload progress that actually happens. The file is still in pending status and the progress bar won't display. If you need to show it please take care of the file status too.
> 
> Src code releated:
> ![image](https://user-images.githubusercontent.com/18677354/123362084-b7342c00-d5a2-11eb-9ffa-00bb7b6a5bbd.png)

First of all, I'm using controlled mode, and file uploads are handled externally (in my case to a GraphQL endpoint, ). Secondly, it was assumed from the docs that in controlled mode the upload component should behave as 'view' layer only, in the case it wasn't it should be a documented behavior.

**Comment by 07akioni** [comment]
Will fix.

**Comment by viztor** [comment]
> Will fix.

Really impressed and appreciate your excellent work.

**Comment by viztor** [comment]
> Will fix.

:) Any update?

**Comment by 07akioni** [comment]
There are some pr trying to fix it but none solves the problem. I'll try to fix it.

**Comment by 07akioni** [comment]
After some investigatings, I find that's not a bug. Please note that the `file` and `fileList` in the callback is non reactive. So you need to write in another manner:

```html
<n-upload :file-list="fileListRef" @change="handleUploadChange">
  <n-button>上传文件</n-button>
</n-upload>
```

```js
import { NUpload, NButton } from 'naive-ui'
import { ref } from 'vue'

export default {
  name: 'App',
  components: {
    NUpload,
    NButton
  },
  setup () {
    const fileListRef = ref([])
    const handleUploadChange = ({ file, fileList, event }) => {
      fileListRef.value = fileList
      setTimeout(() => {
        // file is non reactive, so the status change won't have any effect
        // file.status = 'error'
        fileListRef.value.forEach(f => {
          f.status = 'error'
        })
      }, 1000)
    }
    return {
      fileListRef,
      handleUploadChange
    }
  }
}
```

I've a simpler version to illustrate what happens in your code.

```
setup () {
  const file = {}
  const fileListRef = ref([])
  fileListRef.value.push(file)
  file.hello = 'world'
  // nothing will happens since file is non reactive
}
```
