### ISSUE TITLE
date-picker's `format` prop not localized when using date-fns localized date string (e.g. `PP`)

### ISSUE THREAD

**Issue by wc-matteo** [TuSimple/naive-ui#250]
### TuSimple/naive-ui version (版本)
2.13.0

### Vue version (Vue 版本)
3.1.2

### Browser and its version (浏览器及其版本)
Chrome 91.0.4472.106

### System and its version (系统及其版本)
Windows 10

### Reappearance link (重现链接)
https://codesandbox.io/s/affectionate-browser-e13mu?file=/src/Demo.vue

### Reappearance steps (重现步骤)
Select the chinese locale
Select a date
Observe the formatted value in the date-picker field

### Expected results (期望的结果)
The format of the date matches the locale

### Actual results (实际的结果)
The format of the date is always in the english locale

**Comment by 07akioni** [comment]
It seems the problem of date-fns.

Please see https://codesandbox.io/s/sleepy-ardinghelli-320ju?file=/src/index.js

![image](https://user-images.githubusercontent.com/18677354/123019954-17409c00-d404-11eb-9521-3ac9acd74e5e.png)

**Comment by wc-matteo** [comment]
https://codesandbox.io/s/confident-johnson-w6ky5?file=/src/index.js:35-72

with my locale (italian) it works correctly

**Comment by wc-matteo** [comment]
I'm not really that familiar with date-fns but as far as I see you need to provide a locale option for every function call (e.g. `format`)

**Comment by 07akioni** [comment]
> I'm not really that familiar with date-fns but as far as I see you need to provide a locale option for every function call (e.g. `format`)

Yes, I use it because it's treeshakable. However I just expose a number interface outside, if you want use other libs it's not hard.

**Comment by 07akioni** [comment]
If you need more locale please create a PR and add the locale you needed

**Comment by wc-matteo** [comment]
I created italian locale fro my project. I'll submit a pr once I'm sure it's all good 👍🏿

**Comment by wc-matteo** [comment]
would you consider adding the locale parameter to format's date-fns function. Like here: https://github.com/TuSimple/naive-ui/blob/main/src/date-picker/src/DatePicker.tsx#L336
?

**Comment by 07akioni** [comment]
> https://github.com/TuSimple/naive-ui/blob/main/src/date-picker/src/DatePicker.tsx#L336

Sure, it seems to be a bug.

**Comment by 07akioni** [comment]
Some `format` hasn't been passed in with locale options.

**Comment by Volankey** [comment]
Fix #286
