### ISSUE TITLE
autosize的多行输入框样式异常

### ISSUE THREAD

**Issue by yuzhenqiang** [TuSimple/naive-ui#2505]
### TuSimple/naive-ui version (版本)
2.25.5

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
Chrome(98.0.4758.102)

### System and its version (系统及其版本)
MacOS(12.2.1)

### Reappearance link (重现链接)
https://codesandbox.io/s/goofy-germain-ucjqct?file=/src/Demo.vue

### Reappearance steps (重现步骤)
文本框内容超过一行时

### Expected results (期望的结果)
内容在多行文本框内正常显示

### Actual results (实际的结果)
n-input__textarea-el 宽度溢出，导致内容溢出

**Comment by xxf512** [comment]
这个我也碰到了，好像是加了autosize 这个属性 就会这样子，去掉就正常了

**Comment by yuzhenqiang** [comment]
> 这个我也碰到了，好像是加了autosize 这个属性 就会这样子，去掉就正常了

但我们需要autosize

**Comment by Sepush** [comment]
我一会儿修

**Comment by 07akioni** [comment]
![image](https://user-images.githubusercontent.com/18677354/155657422-a10cbfed-c956-4bff-b67c-0bac0b140504.png)

是个 bug，应该是因为 right 对于 textarea 不生效导致的

**Comment by 07akioni** [comment]
这个事情从根源上讲是为了做滚动条效果才搞出来的，是因为滚动监听区域和滚动条区域不一致闹出来的问题。

目前临时修正了一下，长久的解决方案还是得把 scrollbar 几个内部组件拆开，通过 context 绑定。

```
<scrollbar>
  <textarea>
  </textarea>
  <textarea-suffix />
  <vertical-rail />
  <horizontal-rail />
</scrollbar>
```
