### ISSUE TITLE
n-spin进度环被js堵塞

### ISSUE THREAD

**Issue by dostufffancy** [TuSimple/naive-ui#2506]
### TuSimple/naive-ui version (版本)
2.25.5

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
Chrome 98.0.4758.102

### System and its version (系统及其版本)
windows 10

### Reappearance link (重现链接)
https://codesandbox.io/s/currying-hooks-ef7g87?file=/src/App.vue

### Reappearance steps (重现步骤)
点击alert按钮,模拟堵塞状态

### Expected results (期望的结果)
执行alert时，n-spin仍然旋转

### Actual results (实际的结果)
执行alert时，n-spin停止旋转

### Remarks (补充说明)
关于codesandbox重现链接，如果报错。多刷新几次

**Comment by 07akioni** [comment]
没办法，js 会阻塞 ui 渲染

**Comment by dostufffancy** [comment]
> 没办法，js 会阻塞 ui 渲染

你肯定没看重现链接，我在里面写了两个进度环，

**Comment by 07akioni** [comment]
这个事情比较奇怪，只能学习一下人家的写法了

**Comment by 07akioni** [comment]
closed in 2543

**Comment by Flipped199** [comment]
单放个spin cpu占用好高啊

**Comment by suica** [comment]
> 单放个spin cpu占用好高啊

确实，进入spin文档页面，chrome的CPU占用会增加5%左右。

**Comment by webceoboy** [comment]
version:2.40 alert就转的慢，alert取消就恢复正常速度，估计跟n-spin里面的js watch有关
