### ISSUE TITLE
数据表格单元格点击 和单元格渲染

### ISSUE THREAD

**Issue by zhangle1** [TuSimple/naive-ui#2523]
### Expected API (期望的 API)
   render( cellIndex:number)
  单元格索引 可以获取吗

**Comment by Talljack** [comment]
![image](https://user-images.githubusercontent.com/34439652/156159672-188275bf-2b3d-4d52-857f-4635fda47d83.png)
可以获取到的

**Comment by Talljack** [comment]
render函数就是渲染某一列的，这一列你应该是知道的，再加上这个rowIndex行信息就知道第几行几列了

**Comment by zhangle1** [comment]
是的,  但是我的column里定义了key   ，但是我不希望直接去根据key映射rowData里的对象, 我的数据rowData{    key:{ value:'1', queryParam:{}  }    }   这样子我可以根据columnIndex ，去得到当前Column的key,  rowData[key].value 去得到我想要的值。  是不是我使用的方式有点问题

**Comment by 07akioni** [comment]
> 是的, 但是我的column里定义了key ，但是我不希望直接去根据key映射rowData里的对象, 我的数据rowData{ key:{ value:'1', queryParam:{} } } 这样子我可以根据columnIndex ，去得到当前Column的key, rowData[key].value 去得到我想要的值。 是不是我使用的方式有点问题

没懂，你在写

```
{
  xxx: {
    yyy: // 这个时候你已经能知道 xxx 了
  }
}
```
