### ISSUE TITLE
form-item validate rule need a `render-message` like `render-label`

### ISSUE THREAD

**Issue by yiptsangkin** [TuSimple/naive-ui#2525]
### This function solves the problem (这个功能解决的问题)
when change i18n language, the rule message can not change.
### Expected API (期望的 API)
:render-message="(option) => h('span', {}, $t(option.message))"

**Comment by Talljack** [comment]
The form-item validate message is written by yourself, we cannot control it, maybe you can retry validate.

**Comment by 07akioni** [comment]
> e message is written by yourself, we cannot control it, maybe yo

We may try it, I think it's somehow possible.

Although message is uncontrolled, it can accept context and change its content.

**Comment by yiptsangkin** [comment]
> 

thx！
