### ISSUE TITLE
does not provide an export named 'getTimezoneOffset'

### ISSUE THREAD

**Issue by phcent** [TuSimple/naive-ui#2545]
### TuSimple/naive-ui version (版本)
2.26.0

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
Chrome(98.0.4758.102)

### System and its version (系统及其版本)
Chrome(98.0.4758.102)

### Reappearance link (重现链接)
https://codesandbox.io/s/practical-northcutt-woeq78

### Reappearance steps (重现步骤)
浏览器报错：Uncaught SyntaxError: The requested module '/_nuxt/node_modules/date-fns-tz/index.js?v=297527ff' does not provide an export named 'getTimezoneOffset'

### Expected results (期望的结果)
没有错误

### Actual results (实际的结果)
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/date-fns-tz/index.js?v=297527ff' does not provide an export named 'getTimezoneOffset'

**Comment by phcent** [comment]
/naive-ui/es/time/src/Time.js 第三行

**Comment by Sepush** [comment]
seems causes by `date-fns-tz`, I will try to fix it later

**Comment by 07akioni** [comment]
closed in #2555

**Comment by phcent** [comment]
https://codesandbox.io/s/woeq78

**Comment by 07akioni** [comment]
![image](https://user-images.githubusercontent.com/18677354/157299299-920553ff-cf98-41ad-ae72-624bc2ceb2c6.png)

没看出有啥问题

**Comment by 07akioni** [comment]
有啥可以复现的仓库么

**Comment by 07akioni** [comment]
我把 codesandbox 拉下来用 npm i 跑了一下

![image](https://user-images.githubusercontent.com/18677354/157300073-7e8919bc-1c50-4ac8-92b5-616e01a6d1f0.png)

说实话我到现在为止从来没跑起来过任何一个直接拉下来的 nuxt 仓库，搞的每次为这个东西 debug 好像和浪费时间一样

**Comment by phcent** [comment]
> ![image](https://user-images.githubusercontent.com/18677354/157299299-920553ff-cf98-41ad-ae72-624bc2ceb2c6.png)
> 
> 没看出有啥问题

将右侧的地址https://woeq78.sse.codesandbox.io/ 复制到浏览器打开 就能看见错误了 图片所示也是有异常的 幻灯片并不能切换 这个错误导致了 整个系统都不能正常使用哦 情况很严重呢

**Comment by Sepush** [comment]
> > ![image](https://user-images.githubusercontent.com/18677354/157299299-920553ff-cf98-41ad-ae72-624bc2ceb2c6.png)
> > 没看出有啥问题
> 
> 将右侧的地址https://woeq78.sse.codesandbox.io/ 复制到浏览器打开 就能看见错误了 图片所示也是有异常的 幻灯片并不能切换 这个错误导致了 整个系统都不能正常使用哦 情况很严重呢

这种bug 希望能给一个GitHub仓库地址 clone之后能跑起来的 这样方便我们debug 线上环境会有一些问题

**Comment by phcent** [comment]
![image](https://user-images.githubusercontent.com/70010565/157345079-ecca1f1f-df8a-4d9b-826c-fe61417705e9.png)

**Comment by phcent** [comment]
https://github.com/phcent/navie-nuxt 项目地址 我测试是可以运行的

**Comment by leixuexxxx** [comment]
same problem here
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/date-fns-tz/index.js?v=4a0bed47' does not provide an export named 'getTimezoneOffset'

**Comment by 07akioni** [comment]
临时方案建议可以进 node_modules 里面把 time 从导出移除掉。

<img width="370" alt="image" src="https://user-images.githubusercontent.com/18677354/158407623-d67e3840-32cc-4fe0-9af2-b58e6df38f01.png">

感觉你们还是得去 nuxt 那边提个 issue。

**Comment by 07akioni** [comment]
This is a nuxt bug, it doesn't transform common js index to a esm index. I don't know why.

**Comment by phcent** [comment]
@07

> This is a nuxt bug, it doesn't transform common js index to a esm index. I don't know why.
> 
> If possible you can create an issue in nuxt repo.
> 
> 这玩意就不能正常工作一下吗，佛了

es/time/src/Time.js
能将一下引用方式更改一下 来适应nuxt吗？
import { getTimezoneOffset } from 'date-fns-tz';
改成以下任意一种
import  getTimezoneOffset  from 'date-fns-tz/getTimezoneOffset';
import { getTimezoneOffset } from 'date-fns-tz/esm/getTimezoneOffset';

**Comment by 07akioni** [comment]
> @07
> 
> > This is a nuxt bug, it doesn't transform common js index to a esm index. I don't know why.
> > If possible you can create an issue in nuxt repo.
> > 这玩意就不能正常工作一下吗，佛了
> 
> es/time/src/Time.js 能将一下引用方式更改一下 来适应nuxt吗？ import { getTimezoneOffset } from 'date-fns-tz'; 改成以下任意一种 import getTimezoneOffset from 'date-fns-tz/getTimezoneOffset'; import { getTimezoneOffset } from 'date-fns-tz/esm/getTimezoneOffset';

第一种具体啥问题我忘了，好像是打包会出问题
第二种和 CJS 不兼容，打包不了 CJS 兼容包

我都试过

**Comment by 07akioni** [comment]
> @07
> 
> > This is a nuxt bug, it doesn't transform common js index to a esm index. I don't know why.
> > If possible you can create an issue in nuxt repo.
> > 这玩意就不能正常工作一下吗，佛了
> 
> es/time/src/Time.js 能将一下引用方式更改一下 来适应nuxt吗？ import { getTimezoneOffset } from 'date-fns-tz'; 改成以下任意一种 import getTimezoneOffset from 'date-fns-tz/getTimezoneOffset'; import { getTimezoneOffset } from 'date-fns-tz/esm/getTimezoneOffset';

这个 feature 应该是没开放出去，我看看没开出去的话下个版本先删了

**Comment by Baiyuetribe** [comment]
> same problem here Uncaught SyntaxError: The requested module '/_nuxt/node_modules/date-fns-tz/index.js?v=4a0bed47' does not provide an export named 'getTimezoneOffset'

这是因为你们的项目里nuxt3配置错误导致的，该问题早就修复了。这才是正确使用方式，https://github.com/Baiyuetribe/nuxt3-naive-ui-starter

**Comment by phcent** [comment]
> > same problem here Uncaught SyntaxError: The requested module '/_nuxt/node_modules/date-fns-tz/index.js?v=4a0bed47' does not provide an export named 'getTimezoneOffset'
> 
> 这是因为你们的项目里nuxt3配置错误导致的，该问题早就修复了。这才是正确使用方式，https://github.com/Baiyuetribe/nuxt3-naive-ui-starter

你这是把naive排除在ssr渲染之外了

**Comment by phcent** [comment]
@Baiyuetribe 你先试试最新版本能不能跑起来  我用你的并没有跑起来

**Comment by Baiyuetribe** [comment]
> 

我都开发出了两个实际案例了，最小demo都给了，这demo还可以在线`stackblitz`上一键运行，到底是谁的问题？
案例1： 书籍系统 https://duhaoshu.cc
案例2：云盘资源分享网 https://www.aliyunpanziyuan.com
开源分享，完全没必要欺诈吧？

**Comment by 07akioni** [comment]
> https://github.com/Baiyuetribe/nuxt3-naive-ui-starter

倒不是你说的这样，他的配置没啥问题。

我暂时没空实验，推测是这样的逻辑：

vite 默认会把能外部化的依赖还是用外部的，比如说 naive 提供了 cjs 就去用 naive 的，不去再跑一次 vite 打包。

但是外部化的情况下 nuxt 这个玩意有 bug，导致爆了你说的这个问题。

或许 noExternal 恰好能处理这个问题。

<img width="797" alt="image" src="https://user-images.githubusercontent.com/18677354/162062277-11f6d73e-8074-4ba8-924a-517dfd2f3c5f.png">

**Comment by cinob** [comment]
遇到了相同的问题 dev下正常 build完就报错了

**Comment by leixuexxxx** [comment]
我的解决办法是在app.vue里面 import { getTimezoneOffset } from 'date-fns-tz'
然后随便用一下

**Comment by phcent** [comment]
@07akioni 大佬 改一下引用方式呢 下面的这种方法我确定可以解决问题
es/time/src/Time.js
将以下引用方式
import { getTimezoneOffset } from 'date-fns-tz';
改成为下面
import getTimezoneOffset from 'date-fns-tz/getTimezoneOffset';

**Comment by cinob** [comment]
大佬们 有什么更好的解决方案嘛 现在每次都得直接改Time.js里源码 有点难受啊

**Comment by 07akioni** [comment]
> 大佬们 有什么更好的解决方案嘛 现在每次都得直接改Time.js里源码 有点难受啊

最好的办法是给 nuxt 提 issue，我最近确实没什么时间处理这个问题，如果今晚我解决不了那最早也得周末了
