### ISSUE TITLE
Add `data-form` like `data-table`: schema-based forms

### ISSUE THREAD

**Issue by wxs77577** [TuSimple/naive-ui#255]
### This function solves the problem (这个功能解决的问题)
Makes development more efficient.
### Expected API (期望的 API)
`<n-data-form :fields="fields" v-model="formData"  />`
or
`<n-data-form :columns="columns" v-model="formData"  />`

**Comment by 07akioni** [comment]
We won't do it in the library. 
If you are interested, you can integrate it with other existing libraries.
