### ISSUE TITLE
Input Number is missing several input props

### ISSUE THREAD

**Issue by NilsEvers** [TuSimple/naive-ui#2551]
### This function solves the problem (这个功能解决的问题)
The `Input Number` component is missing several props that the regular `Input` component has, like `autofocus`, `readonly` and so on.

This is especially frustrating when switching between those fields and can result in a lot of extra work.
### Expected API (期望的 API)
The `Input Number` should be based on the regular `Input` or at least implement the same props.

**Comment by Sepush** [comment]
in fact `NInputNumber` based on `NInput`

**Comment by 07akioni** [comment]
`n-input-number` supports readonly. Seems it's not documented.
