### ISSUE TITLE
可否在表格列的column属性中增加个visible的属性

### ISSUE THREAD

**Issue by poerlang** [TuSimple/naive-ui#2554]
### This function solves the problem (这个功能解决的问题)
可否在表格列的 column 属性中增加个 **visible** 的属性，对特定列进行临时的隐藏或再显示，这样就不用直接删除列
### Expected API (期望的 API)
DataTableColumnProperties {
    visible
}

**Comment by 07akioni** [comment]
重复 https://github.com/TuSimple/naive-ui/issues/2490
