### ISSUE TITLE
对于 Modal、Dialog和Drawer等弹窗组件，打开时能把html的滚动禁止掉，关闭时恢复滚动

### ISSUE THREAD

**Issue by honghuangdc** [TuSimple/naive-ui#2556]
### This function solves the problem (这个功能解决的问题)
打开弹窗后禁止html滚动，关闭弹窗恢复html滚动
### Expected API (期望的 API)
像AntDesignVue、ElementPlus等UI库的这些弹窗组件打开时都会禁止html滚动，关闭弹窗恢复html滚动

**Comment by 07akioni** [comment]
我自己试了一下没能复现出滚动效果，需要一个复现

**Comment by honghuangdc** [comment]
https://soybean.pro/#/dashboard/analysis
这个页面出现滚动条，html滚动(如果没出现把浏览器的高度缩小些)，然后点击右边的项目设置按钮呼出抽屉，把光标放在遮罩上，滑动滚轮，页面依然会滚动。
https://preview.pro.antdv.com/dashboard/workplace
参考这个，点击设置按钮时呼出抽屉，会禁止html滚动

**Comment by honghuangdc** [comment]
要不有空我提一个pr

**Comment by 07akioni** [comment]
![image](https://user-images.githubusercontent.com/18677354/156895582-2aa0a302-b185-4d9c-9978-c4deca0436f7.png)

我打不开 soybean 的页面

**Comment by 07akioni** [comment]
> 要不有空我提一个pr

感觉没啥问题，可以专门加一个属性

**Comment by honghuangdc** [comment]
> ![image](https://user-images.githubusercontent.com/18677354/156895582-2aa0a302-b185-4d9c-9978-c4deca0436f7.png)
> 
> 我打不开 soybean 的页面

再看一下，没问题了

**Comment by 07akioni** [comment]
感觉有点神奇，我自己就复现不出来，不知道是不是和 dom 结构啥的也有关系。

确实应该禁用页面滚动的。

**Comment by 07akioni** [comment]
![image](https://user-images.githubusercontent.com/18677354/156899083-ee4fb586-3d47-413a-9b82-6b4c7e744680.png)

这种地方可以用 arrow-point-to-center 优化一下

**Comment by honghuangdc** [comment]
> ![image](https://user-images.githubusercontent.com/18677354/156899083-ee4fb586-3d47-413a-9b82-6b4c7e744680.png)
> 
> 这种地方可以用 arrow-point-to-center 优化一下

收到

**Comment by honghuangdc** [comment]
> 感觉有点神奇，我自己就复现不出来，不知道是不是和 dom 结构啥的也有关系。
> 
> 确实应该禁用页面滚动的。

最外层没有用内置的Scrollbar组件，用的浏览器的滚动

**Comment by 07akioni** [comment]
closed in 40cbafe48bfdefb0fe4788e53b5bb783d00dd09b
