### ISSUE TITLE
Tree组件请支持点击文字也能展开children，以及支持同级手风琴模式

### ISSUE THREAD

**Issue by tingyuu** [TuSimple/naive-ui#2557]
### This function solves the problem (这个功能解决的问题)
1.Tree组件只能点击展开开关才能展开children很不合理，点击文字也能展开会更加符合用户的操作习惯；
2.Tree组件支持同级手风琴模式会更加整洁；
### Expected API (期望的 API)
无

**Comment by lisonge** [comment]
TreeOption 好像也没有手动控制展开的属性

**Comment by 07akioni** [comment]
> TreeOption 好像也没有手动控制展开的属性

展开是通过 tree 的属性控制的，通过 tree option 控制展开是不合理的设计

因为 tree 总是需要对行为进行响应，因此在调整的时候需要发出事件，告诉用户下一次状态的展开 key 是什么，如果还要用户把这个信息放回 option 就太复杂了
