### ISSUE TITLE
n-select 组件新增  n-tag popover 内容的自定义或者是否禁用功能

### ISSUE THREAD

**Issue by tianyu94** [TuSimple/naive-ui#2558]
### This function solves the problem (这个功能解决的问题)
解决当选择的数据项较多时(大概5000个以上时就卡了，选中项到达几万级别时影响流畅使用)，页面渲染无法应用 virtual-scroll 特性(因为是多选，要么全部显示很卡，要么设置 max-tag-count 后 +n 的 popover 中的 tag 内容较多时也会卡)，最终导致页面很卡。

### Expected API (期望的 API)
新增 tag-count-popover 属性到 n-select 组件；
- 可以是 tag-count-popover-props 传 NPopover 的 props，从而控制 popover 的属性让其禁用 (disabled)
- 或者是 tag-count-popover-disabled: boolean 可启用或禁用 tag count 的 popover
- 或者加一个槽 #tag-count-popover-trigger 

以上均可以解决渲染的性能问题。

**Comment by 07akioni** [comment]
理论上这个是可以做的。

可是意义是什么呢？

选中 5000 个的时候，除了数量意外，对于用户的有用信息是什么？

**Comment by amadeus711** [comment]
> 理论上这个是可以做的，可以提供一个关掉 popover 的选项，我觉得可以做，从交互上是有意义的。
> 
> 可是选中这么多意义是什么呢？
> 
> 选中 5000 个的时候，除了数量意外，对于用户的有用信息是什么？
> 
> 对于用户来说 5000 和 50w 的区别我感觉可能不太大，反正都翻不出来，那到时候可能就有人来问选中 50w 个卡顿怎么办了。所以我想讨论一下这个事。

有些业务场景会默认全选吧

**Comment by tianyu94** [comment]
> 理论上这个是可以做的，可以提供一个关掉 popover 的选项，我觉得可以做，从交互上是有意义的。
> 
> 可是选中这么多意义是什么呢？
> 
> 选中 5000 个的时候，除了数量意外，对于用户的有用信息是什么？
> 
> 对于用户来说 5000 和 50w 的区别我感觉可能不太大，反正都翻不出来，那到时候可能就有人来问选中 50w 个卡顿怎么办了。所以我想讨论一下这个事。

是的，我也想了一下，确实忽略了用户在使用时的情况。目前我是自定义的表单组件（n-select + n-button），点击 button 打开 n-data-table (in modal) 再可以分页查询勾选或取消勾选（select 的 options 和 data-table 的 data 数据一致）。

我遇到的业务场景是一个分组，然后下面可能有大量的关联数据。就是在编辑这个分组的表单时出现的这种情况。

确实把大量的关联数据放进 select 里也不太好，我还是再设计下这种情况的表单 item 交互方式吧，数据太多就只用 data-table 给用户操作，避免重复（这个时候 select 也比较臃肿了，也不方便勾选操作）。

感谢 :)

**Comment by vintonHuang** [comment]
我想问一下，这个出现的popover 目前最新版本解决了嘛。有出api可以控制不显示了嘛
