### ISSUE TITLE
手风琴模式下，更改菜单value，自动展开菜单/When the menu is in accordion mode, the change value will expand automatically.

### ISSUE THREAD

**Issue by windinternet** [TuSimple/naive-ui#2562]
### This function solves the problem (这个功能解决的问题)
当使用tab组件配合做多页admin时，可以在切换tab的时候自动展开对应的菜单

When you use the tab component to cooperate with multi page admin, you can automatically expand the corresponding menu when switching tabs
### Expected API (期望的 API)
增加属性，来决定要不要自动展开菜单，即当前value所在路径
auto-expand : bool

**Comment by 07akioni** [comment]
为啥要 tabs 和 menu 共存？我觉得这个场景不是很常见。

**Comment by windinternet** [comment]
做多页admin模板使用，不过这个不是重点，重点是希望有一个api来展开指定菜单，如果是手风琴模式，则收起其他菜单。

**Comment by 07akioni** [comment]
你这个需求我感觉明确一点说应该是当前选中的值一定要展开吧，只要不是用户继续手动关掉了

**Comment by Nakus0426** [comment]
> 还是需要你把预期行为描述的准确一点，我还不能理解的特别明白

这个需求应该是指提供一个属性来选择菜单当前的选中值是否自动展开

**Comment by 07akioni** [comment]
> > 还是需要你把预期行为描述的准确一点，我还不能理解的特别明白
> 
> 这个需求应该是指提供一个属性来选择菜单当前的选中值是否自动展开

那我再手动点击父级菜单让他合起来呢

**Comment by Nakus0426** [comment]
单次选中值改变后，用户的操作覆盖组件的操作，下次选中值改变时再覆盖用户的操作。选中值改变时菜单自动展开选中的菜单项，用户手动关闭后如果再改变选中值，就再自动展开

**Comment by 07akioni** [comment]
> 下次选中值改变时再覆盖用户的操作。选中值改变时菜单自动展开选中的菜单项，用户手动关闭后如果再改变选中值，就再自动展开

基本能理解了，you kong kan kan

**Comment by 07akioni** [comment]
提供了一个 `showOption(key?)` 的方法，让用户指定哪个要被展开

**Comment by windinternet** [comment]
感谢大佬支持！
