### ISSUE TITLE
在Microsoft Edge中naive-ui官方文档切换深色模式浅色模式时，左边的menu组件的字体颜色不对 

### ISSUE THREAD

**Issue by 2383155523** [TuSimple/naive-ui#2563]
### TuSimple/naive-ui version (版本)
2.26.1

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
Microsoft Edge(99.0.1150.30 (官方内部版本) (64 位))

### System and its version (系统及其版本)
windows 11

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/dark/components/avatar

### Reappearance steps (重现步骤)
在Microsoft Edge打开https://www.naiveui.com/zh-CN/dark/components/avatar 点击右上角的深色模式浅色模式切换

### Expected results (期望的结果)
深色模式，浅色模式下 字体颜色正常

### Actual results (实际的结果)
深色模式，浅色模式下 字体颜色不正常

**Comment by 2383155523** [comment]
![bug1](https://user-images.githubusercontent.com/58352334/156919683-9db63a48-bad4-41ff-9f90-ea5ab43953c8.png)
![bug2](https://user-images.githubusercontent.com/58352334/156919684-791d39cc-a49b-411c-b5d4-a58e42195460.png)
![bug3](https://user-images.githubusercontent.com/58352334/156919686-b3192a6b-179a-45c8-8a3c-d31b460797d8.png)

**Comment by Sepush** [comment]
![image](https://user-images.githubusercontent.com/39197136/156920023-21d8c1ed-36b8-4868-8485-5261c66d2875.png)
win10 edge 没有复现 你可以考虑一下是不是你的什么插件导致的

**Comment by Sepush** [comment]
不停的来回切换确实有问题 会修 不光 edge 有这个问题

**Comment by 2383155523** [comment]
![QQ截图20220306185956](https://user-images.githubusercontent.com/58352334/156920206-6df805e9-5793-4e9b-90e5-da4310a55ef1.png)
我让我同学也在他的win11系统下的edge 也试过了

**Comment by 2383155523** [comment]
不过我的Chrome和火狐没发现问题

**Comment by Sepush** [comment]
> 不过我的Chrome和火狐没发现问题

火狐没有问题 chrome 和 edge 下都能复现

**Comment by 2383155523** [comment]
https://fuyouplus.cn/blog-admin-online/  我一开始是在自己写的一个 后台管理面板项目中发现的，也就这几天的事，之前从来没发现过这个问题

**Comment by 2383155523** [comment]
账号密码 随便输入 ，你可以进去看看

**Comment by 2383155523** [comment]
我认为是组件库内部 有bug  不光是 官方文档里面有

**Comment by 2383155523** [comment]
"naive-ui": "^2.25.5", 这是这个项目 naive-ui 的版本

**Comment by Sepush** [comment]
我们排查一下

**Comment by 07akioni** [comment]
我感觉大概率是 edge 的 bug，毕竟是和 chrome 用的同款内核

**Comment by 2383155523** [comment]
![QQ截图20220307105830](https://user-images.githubusercontent.com/58352334/156960412-53194651-6278-43e5-b5bf-67cc1d3f9fa7.png)
Element Plus 好像没发现这个问题。。。

**Comment by 2383155523** [comment]
![QQ截图20220307110625](https://user-images.githubusercontent.com/58352334/156960993-5f784420-2c52-4915-96f4-0b91dd1259c3.png)
Ant D 也是没这个问题的

**Comment by 2383155523** [comment]
![bug1](https://user-images.githubusercontent.com/58352334/156961555-cfaf0109-6b86-47cb-8d59-b3e157be628f.png)
官方的NaiveUiAdmin 这个项目的侧边菜单 就不会出现 已经切换到下个菜单项了上个选中的菜单项 还存在高亮的情况..

**Comment by 2383155523** [comment]
![1646623656917](https://user-images.githubusercontent.com/58352334/156962916-128c6239-41f2-4787-9443-aee3c28b9465.png)
我终于知道为啥昨天我的chrome 没出现那种问题了， 现在已经可以确认就是浏览器自身的bug了,我刚刚给我的Chrome升级了一下 也出现那种bug 了,我现在有个疑问，为啥这个bug 只对Naive UI 做出了影响，其他几个组件库好像都没受到影响.

**Comment by 2383155523** [comment]
![QQ截图20220307113233](https://user-images.githubusercontent.com/58352334/156963272-b57a655a-93c2-44dc-a3f6-ef5c0fc0743b.png)
这个版本下的Chrome 都有出现那种问题 上张图的 那个版本 就不会

**Comment by Sepush** [comment]
> ![1646623656917](https://user-images.githubusercontent.com/58352334/156962916-128c6239-41f2-4787-9443-aee3c28b9465.png) 我终于知道为啥昨天我的chrome 没出现那种问题了， 现在已经可以确认就是浏览器自身的bug了,我刚刚给我的Chrome升级了一下 也出现那种bug 了,我现在有个疑问，为啥这个bug 只对Naive UI 做出了影响，其他几个组件库好像都没受到影响.

你去 arco-design 的网站试试不停切换亮色暗色 你会发现也有这种问题 其他几个组件库的官网没有提供一件切换的按钮

**Comment by 2383155523** [comment]
> > ![1646623656917](https://user-images.githubusercontent.com/58352334/156962916-128c6239-41f2-4787-9443-aee3c28b9465.png) 我终于知道为啥昨天我的chrome 没出现那种问题了， 现在已经可以确认就是浏览器自身的bug了,我刚刚给我的Chrome升级了一下 也出现那种bug 了,我现在有个疑问，为啥这个bug 只对Naive UI 做出了影响，其他几个组件库好像都没受到影响.
> 
> 你去 arco-design 的网站试试不停切换亮色暗色 你会发现也有这种问题 其他几个组件库的官网没有提供一件切换的按钮

是的 我看到了，我现在好像也知道为啥  NaiveUiAdmin 提供了一键切换深浅模式按钮却 不受影响的原因了，因为他的深色模式和浅色模式下 的颜色 都是一样的白色。。

**Comment by WHYBBE** [comment]
我使用NMenu也有这个问题，Chrome和Edge都有出现，大版本号是99，火狐没出现

**Comment by 07akioni** [comment]
> ![1646623656917](https://user-images.githubusercontent.com/58352334/156962916-128c6239-41f2-4787-9443-aee3c28b9465.png) 我终于知道为啥昨天我的chrome 没出现那种问题了， 现在已经可以确认就是浏览器自身的bug了,我刚刚给我的Chrome升级了一下 也出现那种bug 了,我现在有个疑问，为啥这个bug 只对Naive UI 做出了影响，其他几个组件库好像都没受到影响.

因为 naive 技术方案比较复杂，需要支持组件级别的主题调整
