### ISSUE TITLE
希望data table组件提供类似Window.scrollTo()的滚动方法

### ISSUE THREAD

**Issue by oiltofu** [TuSimple/naive-ui#2570]
### This function solves the problem (这个功能解决的问题)
data table组件无法使用js去动态控制滚动位置
### Expected API (期望的 API)
类似
window.scrollTo(x-coord,y-coord )

window.scrollTo(options)
https://developer.mozilla.org/zh-CN/docs/Web/API/Window/scrollTo

**Comment by zhht1204** [comment]
+1。现在好像没有显式控制滚动的方式。

**Comment by zhht1204** [comment]
thx.
