### ISSUE TITLE
官方文档 选择器 Select 组件 选择菜单 的样式 无法响应深浅模式的切换

### ISSUE THREAD

**Issue by 2383155523** [TuSimple/naive-ui#2571]
### TuSimple/naive-ui version (版本)
2.26.1

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
Chrome(99.0.4844.51)

### System and its version (系统及其版本)
windows11

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/select

### Reappearance steps (重现步骤)
进入Naive UI 官方文档 https://www.naiveui.com/zh-CN/light/components/select 左侧菜单点击 选择器 Select
在右侧随便找个示例 点击组件展开 选择菜单  然后鼠标移动至右上角点击切换深色模式按钮，此时 选择菜单会消失，然后再次打开它 他的样式 还是呈 浅色模式的状态

### Expected results (期望的结果)
选择器 Select 的选择菜单的样式 会响应深浅模式的切换

### Actual results (实际的结果)
选择器 Select 的选择菜单的样式 无法响应深浅模式的切换

**Comment by 2383155523** [comment]
![QQ截图20220307172132](https://user-images.githubusercontent.com/58352334/157003068-e96e80f8-b628-48da-93db-8e494eb70980.png)

**Comment by 2383155523** [comment]
![bug1](https://user-images.githubusercontent.com/58352334/157030752-a58668ed-5fd2-41f6-aef0-cdd738201fec.png)
![bug2](https://user-images.githubusercontent.com/58352334/157030773-c41118d5-b234-4a08-8e82-8cf5224bca87.png)
点开 基础用法那个 示例的 选择菜单 然后鼠标 直接移动到 切换深色模式按钮， 然后 再去把 基础用法那个示例 的选择菜单打开。

**Comment by 2383155523** [comment]
![QQ截图20220307200735](https://user-images.githubusercontent.com/58352334/157031625-7ea9bcd4-c726-44d7-ab10-99a5d94b8112.png)

**Comment by greenhat616** [comment]
确实，该问题可以复现

**Comment by coder-chin** [comment]
![image](https://user-images.githubusercontent.com/79465534/157225091-905b851d-328f-4c58-9eb2-ebd478b22edc.png)

**Comment by coder-chin** [comment]
确实是bug
![image](https://user-images.githubusercontent.com/79465534/157225351-a6c09e80-dbc8-485f-b7d4-091f5caec281.png)

**Comment by 07akioni** [comment]
fixed in #2584
