### ISSUE TITLE
动态标签 `DynamicTags` 的 input 插槽 支持传递焦点事件

### ISSUE THREAD

**Issue by Air-Cooled** [TuSimple/naive-ui#2575]
### This function solves the problem (这个功能解决的问题)
自定义输入框时，输入框失去焦点后无法恢复为新增按钮
![Dynamic Tags](https://user-images.githubusercontent.com/55440364/157145471-f89406ed-0972-445b-8f9f-5a6ac172bcef.gif)
### Expected API (期望的 API)
期望自定义输入同样可在失去焦点后可显示新增按钮

**Comment by Sepush** [comment]
will do
