### ISSUE TITLE
动态标签 `DynamicTags` 支持 label-value 回显

### ISSUE THREAD

**Issue by Air-Cooled** [TuSimple/naive-ui#2576]
### This function solves the problem (这个功能解决的问题)
这样动态标签 `DynamicTags` 的 input 插槽可以使用 `Select` 组件选择数据，结合支持单独指定每个 `tag` 的 type 或 color ，用户体验可能远优于 `Select` 显示形式 
### Expected API (期望的 API)
1.  `input` 插槽可以使用 `Select` 组件选择 label-value 数据
2. 支持单独指定每个 `tag` 的 type 或 color

**Comment by Talljack** [comment]
input现在可以使用select组件的，前提是数据结构匹配（不为数组
![image](https://user-images.githubusercontent.com/34439652/157414370-92ee4025-8687-4783-ad3d-bc0610a6f392.png)

**Comment by Air-Cooled** [comment]
确定你这样可用？选项的 label与value 值不一样时呢？
`DynamicTags` 可以像 `Select` 的多选一样吗？且没有输入框的限制
![image](https://user-images.githubusercontent.com/55440364/157597871-a0c5aa6a-d3ae-4067-ab02-ddf1286f2102.png)

**Comment by Talljack** [comment]
> 确定你这样可用？选项的 label与value 值不一样时呢？ `DynamicTags` 可以像 `Select` 的多选一样吗？且没有输入框的限制 ![image](https://user-images.githubusercontent.com/55440364/157597871-a0c5aa6a-d3ae-4067-ab02-ddf1286f2102.png)

如果使用select确实会存在你这样的问题，label和value不知道显示哪个的问题以及不能多选的情况（这种应该被禁止

**Comment by 07akioni** [comment]
> 确定你这样可用？选项的 label与value 值不一样时呢？ `DynamicTags` 可以像 `Select` 的多选一样吗？且没有输入框的限制 ![image](https://user-images.githubusercontent.com/55440364/157597871-a0c5aa6a-d3ae-4067-ab02-ddf1286f2102.png)

Label 和 value 的值可以用 onCreate 去关联

**Comment by Air-Cooled** [comment]
那不同的 `Tab` 如何显示不同的颜色呢？还是说 `DynamicTags` 不考虑可为每个标签设置不同颜色

**Comment by 07akioni** [comment]
> 那不同的 `Tab` 如何显示不同的颜色呢？还是说 `DynamicTags` 不考虑可为每个标签设置不同颜色

会增加动态渲染的能力的，这块具体怎么做我还要再想想，因为现在是纯 string
