### ISSUE TITLE
`Tabs`closable 优化

### ISSUE THREAD

**Issue by Air-Cooled** [TuSimple/naive-ui#2577]
### This function solves the problem (这个功能解决的问题)
支持 `closable` 的相关操作中 `closable` 按钮都将持续显示，视觉体验有待优化
![image](https://user-images.githubusercontent.com/55440364/157152171-7f4fc077-2e41-4866-8ed5-223b695d7c18.png)
### Expected API (期望的 API)
支持 `closable` 的相关操作中 `closable` 按钮应在鼠标悬浮后在显示，提升 UE
![closable 优化](https://user-images.githubusercontent.com/55440364/157149431-8f91d941-4e79-4163-aa79-bccda000e6c8.png)

**Comment by Sepush** [comment]
这个需求感觉不是很合理 如果hover的时候才显示close按钮不够直观 用户体验很难说是变好了

**Comment by Sepush** [comment]
这个需求感觉不是很合理 如果hover的时候才显示close按钮不够直观 用户体验很难说是变好了

**Comment by Air-Cooled** [comment]
对于 `Tabs` hover 或 选中 时显示 close 应该是比较合理

**Comment by Sepush** [comment]
> 对于 `Tabs` hover 或 选中 时显示 close 应该是比较合理

你看最常见的 可以close的tab 比如浏览器的tab页也不会是hover或者选中的时候才显示
![image](https://user-images.githubusercontent.com/39197136/157154173-14028e8d-a7ab-4697-b214-fb5a43ccf6d3.png)

**Comment by Air-Cooled** [comment]
> > 对于 `Tabs` hover 或 选中 时显示 close 应该是比较合理
> 
> 你看最常见的 可以close的tab 比如浏览器的tab页也不会是hover或者选中的时候才显示 ![image](https://user-images.githubusercontent.com/39197136/157154173-14028e8d-a7ab-4697-b214-fb5a43ccf6d3.png)

![image](https://user-images.githubusercontent.com/55440364/217987163-0932c81c-6619-4a88-ad80-fdd66aef970a.png)
当数量过多时也只会显示当前的close
