### ISSUE TITLE
有关按钮被禁用的一个bug

### ISSUE THREAD

**Issue by dntc** [TuSimple/naive-ui#258]
### TuSimple/naive-ui version (版本)
2.13.0

### Vue version (Vue 版本)
3.1.2

### Browser and its version (浏览器及其版本)
Chrome(91.0.4472.114)

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://codesandbox.io/s/nice-gareth-0czn0

### Reappearance steps (重现步骤)
很奇怪的一个bug，n-space 里面的两组按钮，在切换按钮组的显示时， 按钮4 会被禁用，如果把 n-space 改为 div，或者改变两个 template 的顺序，或者删除 按钮4 的 click 事件等情况下，就正常了。

### Expected results (期望的结果)
在切换到按钮组2时，按钮4应该是启用状态

### Actual results (实际的结果)
在切换到按钮组2时，按钮4是禁用状态

**Comment by 07akioni** [comment]
You may add keyes as a workaround.

**Comment by 07akioni** [comment]
Why it's closed? Do you find the reason? @dntc
