### ISSUE TITLE
NTabsPane 组件无法直接绑定click事件，而且回调事件只有value参数返回，不方便写业务逻辑

### ISSUE THREAD

**Issue by vzane** [TuSimple/naive-ui#2583]
### This function solves the problem (这个功能解决的问题)
希望能给 NTabsPane 绑定原生事件方法
### Expected API (期望的 API)
@click

**Comment by vzane** [comment]
目前通过回调处理，但是回调会增加一些业务逻辑，而且因为数据响应式，多个地方同时触发value变更，会导致方法多次执行，我的需求是点击NTabPane组件，才执行指定方法，和监听事件区分开来，试过插槽方式来处理，但是想要点击整个标签需要修改样式，比较麻烦，所以能否考虑NTabPane可以直接绑定click事件

**Comment by 07akioni** [comment]
用 `tab-props` 属性
