### ISSUE TITLE
Icon 组件建议添加 iconfont 图标支持

### ISSUE THREAD

**Issue by vzane** [TuSimple/naive-ui#2595]
### This function solves the problem (这个功能解决的问题)
包括我在内 iconfont 用户应该是很大一部分群体，比较习惯使用样式引入图标，我自己封装了下naive-ui的Icon和Menu组件，已经能够支持 iconfont，但是希望官方可以直接支持，可以兼容更多项目开发
### Expected API (期望的 API)
Icon组件和Menu组件直接支持 iconfont 配置

**Comment by ChenZhaoYu02** [comment]
> 

iconfont 不适合支持进独立的组件，应该是使用者自行封装。

**Comment by vzane** [comment]
我自己处理了，iconfont 全部导出了 svg，然后加了 vite-plugin-svg-icons，重新封装了一下 icon 组件，都支持了

**Comment by liub1934** [comment]
这个自己二次封装下就行了，比如在`components`下面建立个组件叫`iconfont`，内容如下：
```vue
<template>
  <n-icon>
    <svg aria-hidden="true">
      <use :xlink:href="`#${iconName}`"></use>
    </svg>
  </n-icon>
</template>

<script lang="ts" setup>
import { computed } from 'vue';
const props = defineProps({
  name: {
    type: String,
    required: true,
  },
  prefix: {
    type: String,
    default: 'icon',
  },
});
const iconName = computed(() => {
  // 支持name传入icon-xxx或者xxx
  return props.name.indexOf(`${props.prefix}-`) > -1
    ? props.name
    : `${props.prefix}-${props.name}`;
});
</script>
```

使用：
iconfont图标类型选择`Symbol`，下载至本地，提前在`main.ts`中引入里面的`iconfont.js`
![image](https://user-images.githubusercontent.com/29849550/195823197-cae7f03a-8af0-4fce-a0cf-dcfe9aa831b7.png)
![image](https://user-images.githubusercontent.com/29849550/195823373-09f0ddd9-9cfc-43e1-bae1-1fde0f44be43.png)
然后就可以用了
```vue
<template>
  <iconfont size="40" color="#0e7a0d" name="icon-user" />
  <iconfont size="40" color="#0e7a0d" name="user" />
</template>
```

最后感觉作者可以加以封装下，全局可以配置引入`iconfont.js`，毕竟国内使用iconfont还是比较多的。 @07akioni
