### ISSUE TITLE
n-tree error when move children outside

### ISSUE THREAD

**Issue by moolex** [TuSimple/naive-ui#2597]
### TuSimple/naive-ui version (版本)
2.26.3

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
Chrome(99.0.4844.51)

### System and its version (系统及其版本)
MacOS(12.2.1)

### Reappearance link (重现链接)
https://codesandbox.io/s/quizzical-cartwright-euhcpr?file=/src/App.vue

### Reappearance steps (重现步骤)
move children outside will cause n-tree error "Cannot read properties of undefined (reading 'forEach')"

### Expected results (期望的结果)
n-tree should works when remove children by change source data

### Actual results (实际的结果)
it doesn't works

**Comment by Talljack** [comment]
How to reproduce? Did you click move children to top?

**Comment by moolex** [comment]
> How to reproduce? Did you click move children to top?

Yes, by click move children to top, it  will cause errors

<img width="913" alt="image" src="https://user-images.githubusercontent.com/1132321/157597000-cff65098-2b0c-4d90-8737-63d22dc68e1d.png">

**Comment by 07akioni** [comment]
醉了，这个和动画的逻辑也相关
