### ISSUE TITLE
add theme override: menu item selected + hover

### ISSUE THREAD

**Issue by wc-matteo** [TuSimple/naive-ui#2598]
### This function solves the problem (这个功能解决的问题)
To style the text/icon/etc when a menu item is selected differently than when it's not selected while the user is hovering on that item
### Expected API (期望的 API)
add new theme override props like: `itemTextColorActiveHover`
(don't forget the inverted variant!)

**Comment by Talljack** [comment]
The design is originally designed like this, which is more convenient for users to adjust. If you need to keep the hover and active colors the same, you can set these two variables to be the same.

**Comment by wc-matteo** [comment]
unless I'm mistaken, right now there is now way (using theme override) to have a different hover text/icon/etc color ONLY for the selected menu item:

to give an example this is what I implemented using n-menu + custom css:

![image](https://user-images.githubusercontent.com/10562635/157618081-261f6952-2dd2-4ff7-a42e-d7345440c56b.png)

when the menu item is selected the hover text/icon/etc should be a dark color (cause the selected menu item bg is light), when it's not selected, the opposite (cause the menu item bg is dark).

**BONUS**

![image](https://user-images.githubusercontent.com/10562635/157618485-862f1a1f-7f06-4b69-a690-63831a32026b.png)

would be nice to have a configurable hover bg like this as well

**Comment by Talljack** [comment]
![image](https://user-images.githubusercontent.com/34439652/157646932-40983607-695d-4c2d-9acc-1e0a4f8bb3a8.png)
Sorry, we understand the instance you said, but you set the itemColorActive variable to set the bg, and then you can set the color of the hover through the itemTextColorHover and itemIconColorHover variables, the effect is as above.

**Comment by wc-matteo** [comment]
yes but I need 2 different hover colors! I need a hover color for when I have the active bg and another hover color for when I don't have the active bg.

**Comment by Talljack** [comment]
yeah, maybe add new theme override props

**Comment by 07akioni** [comment]
> yes but I need 2 different hover colors! I need a hover color for when I have the active bg and another hover color for when I don't have the active bg.

This is really a tough problem. How to define the theme variable name.

**Comment by wc-matteo** [comment]
there already is `itemXXXColorActive` and `itemXXXColorHover`. You could add `itemXXXColorActiveHover`.

Also. it'd be nice to have the term `actve` be changed to  `selected`. To better align it with the term used in the documentation and because `active` also represents [another concept](https://developer.mozilla.org/en-US/docs/Web/CSS/:active).

**Comment by 07akioni** [comment]
> there already is `itemXXXColorActive` and `itemXXXColorHover`. You could add `itemXXXColorActiveHover`.
> 
> Also. it'd be nice to have the term `actve` be changed to `selected`. To better align it with the term used in the documentation and because `active` also represents [another concept](https://developer.mozilla.org/en-US/docs/Web/CSS/:active).

Active in naive ui is named as pressed.
