### ISSUE TITLE
Spin  Icon customization ，And provide the v-loading instruction modifier

### ISSUE THREAD

**Issue by jahnli** [TuSimple/naive-ui#260]
### This function solves the problem (这个功能解决的问题)
Using complex
### Expected API (期望的 API)
Icon customization ，And provide the v-loading instruction modifier

**Comment by 07akioni** [comment]
We may provide a customization slot for spin.

**Comment by 07akioni** [comment]
We won't provide a directive such a v-loading.

**Comment by yuntian001** [comment]
v-loading是非常实用的，强烈建议加上，主题更改v-loading的样式用css解决就好了,或者v-loading部分自己用style传参方式自定义主题支持就好了，没有必要为了主题 而全部用组件化，建议做一些取舍。

**Comment by liu-xinhui** [comment]
用这种ui库的基本都是后台项目，90%的后台项目都不会做主题更改，所以为了这么个主题功能让功能变得不易用，不值得

**Comment by wcldyx** [comment]
> v-loading是非常实用的，强烈建议加上，主题更改v-loading的样式用css解决就好了,或者v-loading部分自己用style传参方式自定义主题支持就好了，没有必要为了主题 而全部用组件化，建议做一些取舍。 @07akioni

非常赞同
