### ISSUE TITLE
Wanted: Grid should support setting `minmax`

### ISSUE THREAD

**Issue by zhmushan** [TuSimple/naive-ui#2603]
### This function solves the problem (这个功能解决的问题)
`minmax` is set to `(0, 1fr)` by the Grid itself as part of the `grid-template-columns` value, and cannot be customized
### Expected API (期望的 API)
Not sure how to do it, not seen such implementations in other ui frameworks, maybe the Grid component can expose props like `minWidth`

**Comment by 07akioni** [comment]
This is expected. You can set min-width of the whole grid.
