### ISSUE TITLE
cascader组件筛选结果过长显示不全

### ISSUE THREAD

**Issue by godzzh** [TuSimple/naive-ui#2606]
### This function solves the problem (这个功能解决的问题)
数据层级过多，看不到筛选出来的完整结果
### Expected API (期望的 API)
希望筛选出来的结果过长后鼠标移入能加个tooltip

**Comment by godzzh** [comment]
![https://raw.githubusercontent.com/godzzh/vue-demo/master/public/001.png]

**Comment by godzzh** [comment]
![ Image Text] https://raw.githubusercontent.com/godzzh/vue-demo/master/public/001.png

**Comment by godzzh** [comment]
![Image Text](https://raw.githubusercontent.com/godzzh/vue-demo/master/public/001.png)

**Comment by Sepush** [comment]
duplicate with #2381

**Comment by Sepush** [comment]
你这个用的是select组件不是 cascader 组件吧 可以参考官网 cascader 的 demo https://www.naiveui.com/zh-CN/os-theme/components/cascader#single.vue

**Comment by godzzh** [comment]
> 你这个用的是select组件不是 cascader 组件吧 可以参考官网 cascader 的 demo https://www.naiveui.com/zh-CN/os-theme/components/cascader#single.vue

是用的cascader组件，层级太多，这个下拉选项是筛选出来的结果

**Comment by godzzh** [comment]
> > 你这个用的是select组件不是 cascader 组件吧 可以参考官网 cascader 的 demo https://www.naiveui.com/zh-CN/os-theme/components/cascader#single.vue
> 
> 是用的cascader组件，层级太多，这个下拉选项是筛选出来的结果

可以选中任一层级的时候，搜索结果筛选项是这样，只能勾选叶节点的时候，筛选项只有最后一级

**Comment by 07akioni** [comment]
> ![Image Text](https://raw.githubusercontent.com/godzzh/vue-demo/master/public/001.png)

图裂掉了？

**Comment by 07akioni** [comment]
问题比较类似，会考虑一下怎么处理

**Comment by godzzh** [comment]
> 问题比较类似，会考虑一下怎么处理

好的 谢谢

**Comment by lvyiwen** [comment]
请问这个问题解决的怎么样了，我这边也出现了这个问题

**Comment by godzzh** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by lvyiwen** [comment]
> 问题比较类似，会考虑一下怎么处理

请问这个问题解决了么，我现在也遇见了这个问题
