### ISSUE TITLE
Transfer组件的label可以用slot吗

### ISSUE THREAD

**Issue by lileiemq** [TuSimple/naive-ui#2608]
### This function solves the problem (这个功能解决的问题)
Transfer组件的label除了字符串，还想显示一些tag
### Expected API (期望的 API)
<template #label></template>

**Comment by 07akioni** [comment]
transfer 在重构中，估计这两个月会有个大的重构，会支持除 string 以外的 label 支持

**Comment by 07akioni** [comment]
现在这版暂时不会做改动
