### ISSUE TITLE
table enhancements

### ISSUE THREAD

**Issue by jahnli** [TuSimple/naive-ui#261]
### This function solves the problem (这个功能解决的问题)
Using complex
### Expected API (期望的 API)
1、Table drag stretch column width
2、Editable row
3、Expandable arrow hovers for cursor:pointer ，Animation transitions during expansion

**Comment by 07akioni** [comment]
1. Not planned
2. You can use render function, we won't provide builtin support for editable table. There will be a demo later.
3. `cursor: pointer` is a good idea. Table won't provide expansion animation due to complexity of virtual scroll, it's hard to maintain.

**Comment by 07akioni** [comment]
Expandable icon's cursor is fixed.
