### ISSUE TITLE
[Drawer] Does not pass the parameter value in the callback when opening

### ISSUE THREAD

**Issue by cefiro** [TuSimple/naive-ui#2610]
### TuSimple/naive-ui version (版本)
2.26.3

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
Chrome(99.0.4844.51)

### System and its version (系统及其版本)
Manjaro(latest)

### Reappearance link (重现链接)
https://codesandbox.io/s/reverent-andras-xbfdos?file=/src/Demo.vue

### Reappearance steps (重现步骤)
Open and close drawer, view console

### Expected results (期望的结果)
When opened, true is expected

### Actual results (实际的结果)
There is nothing when opening

**Comment by 07akioni** [comment]
This is expected. For example if you mount a `<input value="123" @change="xxx" />`, the change callback won't be fired. The same as drawer. By no means drawer can trigger `updateShow` with true by itself. If you need to know when it's changed to true, `watch` it or just trigger it when you click the button.
