### ISSUE TITLE
[n-time-picker] Strange behaviour

### ISSUE THREAD

**Issue by OrbisK** [TuSimple/naive-ui#2612]
### TuSimple/naive-ui version (版本)
2.26.3

### Vue version (Vue 版本)
3.2.27

### Browser and its version (浏览器及其版本)
Opera GX LVL 3 (core: 83.0.4254.70)

### System and its version (系统及其版本)
Win 11

### Reappearance link (重现链接)
https://codesandbox.io/s/focused-grothendieck-vibw12?file=/src/Form.vue

### Reappearance steps (重现步骤)
1. Click on the button
1. Select a time in first select
1. Select a time in second select

### Expected results (期望的结果)
Second select should work properly

### Actual results (实际的结果)
Second select closes after each selection.
First one works properly.

**Comment by OrbisK** [comment]
I guess it related to the focus. Somehow it remains on the first one

**Comment by OrbisK** [comment]
![image](https://user-images.githubusercontent.com/37191683/157688808-54e756a0-1bbb-4c6a-8a5f-289696f5696a.png)
i did :o

**Comment by OrbisK** [comment]
> > I guess it related to the focus. Somehow it remains on the first one
> 
> 你的复现没写完啊 ![image](https://user-images.githubusercontent.com/39197136/157688518-590c86dc-2738-4220-b2dc-5b00eed45682.png)

![image](https://user-images.githubusercontent.com/37191683/157688884-aebd8b94-b2d4-4540-9881-f8e362c01774.png)
I did

**Comment by Sepush** [comment]
嗯 现在好了 确实是个bug

**Comment by 07akioni** [comment]
This is actually caused by focus management. I think I should provide a demo to make the behavior clearer.

**Comment by 07akioni** [comment]
If you only want to make it work, set `trapFocus` to false.
