### ISSUE TITLE
provide props such as prefix, suffix

### ISSUE THREAD

**Issue by jahnli** [TuSimple/naive-ui#262]
### This function solves the problem (这个功能解决的问题)
user experience
### Expected API (期望的 API)
Other than slot, provide props such as prefix, suffix, etc

**Comment by 07akioni** [comment]
Please list related components.

**Comment by jahnli** [comment]
<n-input
      prefix-icon="***"
      or
      suffix='***'
 />

For now, naiveui supports a lot of slots, but there are a lot of places you can use props to replace them  

I think too many slots will make the code too bloated, whether to provide props or directives to make it easier to use

**Comment by 07akioni** [comment]
> code too bloated, whether to provide

In my pointer of view, if something is more of just **inserting some DOM in**, a slot is enough. `prefix` and `suffix` are some of them.

If we provide a prop, it means it may contain some logic in it (or it need types).

I'm not a fan of **everything should be in template**.
