### ISSUE TITLE
checkbox的选中样式不由checked值控制

### ISSUE THREAD

**Issue by YamadaAoi** [TuSimple/naive-ui#2620]
### TuSimple/naive-ui version (版本)
2.25.2

### Vue version (Vue 版本)
3.2.25

### Browser and its version (浏览器及其版本)
chrome 99.0.4844.51

### System and its version (系统及其版本)
windows11 21H2

### Node version (Node 版本)
16.14.0

### Reappearance link (重现链接)
https://codesandbox.io/s/w6ns4i?file=/src/Demo.vue

### Reappearance steps (重现步骤)
点击checkBox

### Expected results (期望的结果)
希望checkBox的的选中状态样式和checked值绑定

### Actual results (实际的结果)
1、在naive-ui官网提供的  “尺寸”   CodeSandbox例子中，没有v-model，点击checkBox样式发生了变化。
2、在实际使用过程中，项目使用tsx开发的组件里，checked初始值为false，点击时onUpdateChecked事件内未改变checked值，但是checkBox已切换为选中的状态。

**Comment by Talljack** [comment]
内部有一套非受控的checked值，当你toggle的时候会进行改变
至于你说的传了checked值（受控模式下）没有改变checked值但是状态改变了需要来个复现demo

**Comment by YamadaAoi** [comment]
问题已发现，感谢回答。
留下我的踩坑记录给小伙伴们，
<NCheckbox
      size="small"
      checked={!!node.checked}
       onUpdateChecked={this.branchChange}
/>
在tsx渲染的时候，如果配置里的默认值类型类似checked?: boolean;并且未给初始值时，NCheckbox会使用内部的非受控的checked值。
所以，可以设置checked={!!node.checked}，确保checked有值。
