### ISSUE TITLE
table 动态设置columns项，实现列的显示隐藏的时候，当隐藏的时候，列没有真正从dom移除，导致有空单元格占位

### ISSUE THREAD

**Issue by lozhu** [TuSimple/naive-ui#2627]
![B0EF8324-46C1-40ae-9C60-77A9AA8E233E](https://user-images.githubusercontent.com/68715772/158045768-7e71a123-ac96-4a45-92b7-5027ded478e0.png)

### TuSimple/naive-ui version (版本)
2.26.4

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://stackblitz.com/edit/vue-agvftn?file=src%2FApp.vue

### Reappearance steps (重现步骤)
通过dropdown按钮，选择需要显示/隐藏的table列，当columns列数据隐藏后，表格响应式更新列项，实现表格的autolayout

### Expected results (期望的结果)
1、期望table columns选项可以增加一个status属性，true/false来显示隐藏列。
例：{
    title: "角色名称",
    key: "name",
    status: true,
  },
2、如果第1条实现不了，希望在隐藏列的时候，单元格从dom移除，而不是单元格的内容不显示

### Actual results (实际的结果)
table 动态设置columns项，实现列的显示隐藏的时候，当隐藏的时候，表格会自动autolayout,但列没有真正从dom移除，导致有空单元格占位，如果单元格有右边框，这个单元格就显示出来了

**Comment by lozhu** [comment]
动态设置columns的值:
 1、值类似于=》保留下标[{title,key},{},{title,key}]  这种的表格渲染成功，但是单元格没有真正移除，存在边框
 2、值类似于=>下标重新排[{title,key},{title,key}] 隐藏的列项直接删除，导致表格渲染失败

**Comment by 9yues** [comment]
解决了吗
