### ISSUE TITLE
Pagination  total props

### ISSUE THREAD

**Issue by jahnli** [TuSimple/naive-ui#263]
### This function solves the problem (这个功能解决的问题)
UE
### Expected API (期望的 API)
Provide the total number of pages for users to view more intuitively

**Comment by 07akioni** [comment]
> ### This function solves the problem (这个功能解决的问题)
> UE
> 
> ### Expected API (期望的 API)
> Provide the total number of pages for users to view more intuitively

Please use `item-count`, it works like `total`.

http://localhost:3000/zh-CN/os-theme/components/pagination#item-count

**Comment by jahnli** [comment]
I'm talking about the total amount of data, not the number of entries per page，

**Comment by jahnli** [comment]
So far in the case, I don't know exactly how many pieces of data I have.

**Comment by 07akioni** [comment]
> I'm talking about the total amount of data, not the number of entries per page，

I'm talking about the total amount of data (use `item-count`), not the number of entries per page (use `page-size`).

So far in the case, I don't know exactly how many pieces of data I have. (use `page-count`)

**Comment by yanwenjia** [comment]
`page-count` and `item-count` should't be specified together. Only `item-count` will take effect.
