### ISSUE TITLE
Nspace 包裹的组件，使用 v-if、v-show 后，space 生成的 dom 没有被同步清除

### ISSUE THREAD

**Issue by pengzhen-developer** [TuSimple/naive-ui#2632]
### TuSimple/naive-ui version (版本)
2.26.4

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
版本 97.0.4692.71（正式版本） (arm64)

### System and its version (系统及其版本)
MacOS(12.0.1)

### Reappearance link (重现链接)
https://codesandbox.io/s/relaxed-joliot-28nsz9?file=/src/App.vue

### Reappearance steps (重现步骤)
1、使用 space 包裹任意组件
2、对包裹组件使用 v-if、v-show 进行销毁、隐藏。

### Expected results (期望的结果)
间距正确

### Actual results (实际的结果)
间距不对

### Remarks (补充说明)

![image](https://user-images.githubusercontent.com/12759499/158286702-0cdaee31-507a-45f1-a414-65a05afd3c0d.png)
![image](https://user-images.githubusercontent.com/12759499/158286729-49e014f2-db46-4c32-8707-207dbee765cf.png)

**Comment by Sepush** [comment]
v-if 是“真正”的条件渲染，因为它会确保在切换过程中，条件块内的事件监听器和子组件适当地被销毁和重建。

v-if 也是惰性的：如果在初始渲染时条件为假，则什么也不做——直到条件第一次变为真时，才会开始渲染条件块。

相比之下，v-show 就简单得多——不管初始条件是什么，元素总是会被渲染，并且只是简单地基于 CSS 进行切换。

**Comment by Sepush** [comment]
使用 v-if 是正常的
![image](https://user-images.githubusercontent.com/39197136/158299170-671b2422-a42a-494e-8d0b-2e392d321849.png)

**Comment by pengzhen-developer** [comment]
> v-if 是“真正”的条件渲染，因为它会确保在切换过程中，条件块内的事件监听器和子组件适当地被销毁和重建。
> 
> v-if 也是惰性的：如果在初始渲染时条件为假，则什么也不做——直到条件第一次变为真时，才会开始渲染条件块。
> 
> 相比之下，v-show 就简单得多——不管初始条件是什么，元素总是会被渲染，并且只是简单地基于 CSS 进行切换。

**Comment by pengzhen-developer** [comment]
> v-if 是“真正”的条件渲染，因为它会确保在切换过程中，条件块内的事件监听器和子组件适当地被销毁和重建。
> 
> v-if 也是惰性的：如果在初始渲染时条件为假，则什么也不做——直到条件第一次变为真时，才会开始渲染条件块。
> 
> 相比之下，v-show 就简单得多——不管初始条件是什么，元素总是会被渲染，并且只是简单地基于 CSS 进行切换。

感谢说明。
