### ISSUE TITLE
tabs position

### ISSUE THREAD

**Issue by jahnli** [TuSimple/naive-ui#264]
### This function solves the problem (这个功能解决的问题)
insufficiency of function 
### Expected API (期望的 API)
Currently only support the top, whether will support left and right position

**Comment by 07akioni** [comment]
> ### This function solves the problem (这个功能解决的问题)
> insufficiency of function
> 
> ### Expected API (期望的 API)
> Currently only support the top, whether will support left and right position

Planned, not with high priority.

**Comment by pengxiaotian** [comment]
+1

**Comment by Talljack** [comment]
same #1466
