### ISSUE TITLE
add type (i.e. color) to popconfirm buttons

### ISSUE THREAD

**Issue by wc-matteo** [TuSimple/naive-ui#2642]
### This function solves the problem (这个功能解决的问题)
I often use popconfirms to confirm a delete operation. It'd be nice if the button inside the popconfirm was red in this case (i.e. type="error"). I know there's the action slot, but it's much more work to setup...
### Expected API (期望的 API)
positive-type / negative-type using values from n-button type (default, primary, tertiary, info, success, warning and error)

**Comment by 07akioni** [comment]
How about adding positive-button-props?

**Comment by wc-matteo** [comment]
even better! :)
