### ISSUE TITLE
Dropdown，Modal

### ISSUE THREAD

**Issue by vzane** [TuSimple/naive-ui#2653]
### This function solves the problem (这个功能解决的问题)
1、Dropdown下拉菜单能否增加插槽自定义，没有用 JSX，脚本里面处理渲染问题代码看起来怪怪的
 2、Modal 组件 content 内容自适应高度有 bug，这个是flex垂直布局都有的一个问题，如果内容是 flex-wrap 属性，会有溢出 bug，需要通过样式修复，而且只能写 style 来添加宽高属性，能否支持 class 宽高或者 width，height 属性
### Expected API (期望的 API)
Dropdown下拉菜单可插槽自定义，Modal 组件修复高度自适应 bug 和新增宽高属性配置

**Comment by 07akioni** [comment]
1. 插槽应该暂时不会增加
2. 第二个问题可以给个复现？

**Comment by vzane** [comment]
https://q4tj9h.csb.app/

**Comment by vzane** [comment]
https://q4tj9h.csb.app/
因为需要自适应高度，所以先要设置这个样式，然后内容使用百分百高度，会有溢出
 .n-dialog .n-dialog__content {
  flex: 1;
}

**Comment by 07akioni** [comment]
没有回复，暂时关闭
