### ISSUE TITLE
tree组件renderPrefix前缀图标不显示

### ISSUE THREAD

**Issue by lozhu** [TuSimple/naive-ui#2657]
### TuSimple/naive-ui version (版本)
2.26.4

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://codesandbox.io/s/old-night-u8zz5h?file=/src/Demo.vue

### Reappearance steps (重现步骤)
tree组件的前缀批量渲染图标不显示

### Expected results (期望的结果)
tree组件的前缀批量渲染的图标能正常显示

### Actual results (实际的结果)
tree组件的前缀图标不一样的时候，图标渲染不出来，通过h(resolveComponent(tree.option.nicon))这种方式也没有办法渲染

**Comment by 07akioni** [comment]
resolveComponent 组件需要全局安装在 app 上
