### ISSUE TITLE
当DatePicker所绑定的值被清空时，DatePicker输入框内的值没有被清空

### ISSUE THREAD

**Issue by labradorGitHubCanine** [TuSimple/naive-ui#2677]
### TuSimple/naive-ui version (版本)
2.26.4

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
Edge

### System and its version (系统及其版本)
Windows11

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/date-picker

### Reappearance steps (重现步骤)
例如在data中有form: {}，DatePicker的v-model:value=form.date，
我勾选了某一日期后例如2020-01-01，数据变为form: {date: xxxxxx}，DatePicker内显示2020-01-01，
当我在script中执行form = {}后，虽然date数据已经不存在了，但是DatePicker仍然显示2020-01-01，
正常情况是否应该清空该值的显示，不知这是不是个bug

### Expected results (期望的结果)
DatePicker所绑定的值被清空后，输入框内的显示日期也被清空

### Actual results (实际的结果)
DatePicker所绑定的值被清空后，输入框内的显示日期没有被清空

**Comment by 07akioni** [comment]
这是一个预期的行为，undefined 会让 date-picker 退化为非受控的值，所以你应该用 `null` 来置空

**Comment by labradorGitHubCanine** [comment]
ok
