### ISSUE TITLE
n-tabs希望新增hover触发函数

### ISSUE THREAD

**Issue by Baiyuetribe** [TuSimple/naive-ui#2679]
### This function solves the problem (这个功能解决的问题)
当前为点击tabs后切换页面，希望鼠标hover时也能自动切换，类似it之家的热榜切换
### Expected API (期望的 API)
新增hover触发，实现鼠标移动时自动切换页面
![tabs](https://user-images.githubusercontent.com/43716063/160227377-a55275e1-b876-4552-ae5b-abd25e688f10.gif)

参考：https://it.ithome.com/people

**Comment by 07akioni** [comment]
可以有
