### ISSUE TITLE
`Tabs` 数量过多时两端可显示滚动按钮

### ISSUE THREAD

**Issue by Air-Cooled** [TuSimple/naive-ui#2683]
### This function solves the problem (这个功能解决的问题)
目前Tabs过多时只支持滚轮滚动，无法通过点击方式进行翻页滚动
### Expected API (期望的 API)
![image](https://user-images.githubusercontent.com/55440364/160287325-a253f6e6-0236-419a-8f4e-49b0e0ffa2f9.png)

**Comment by 07akioni** [comment]
discuss in https://github.com/TuSimple/naive-ui/issues/2128
