### ISSUE TITLE
NSelect使用h函数渲染--在默认获取后端数据的情况下，再次改变value无效

### ISSUE THREAD

**Issue by duangkey** [TuSimple/naive-ui#2685]
### TuSimple/naive-ui version (版本)
2.27.0

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
 99.0.4844.82

### System and its version (系统及其版本)
windows 10

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/select

### Reappearance steps (重现步骤)
no fixed

### Expected results (期望的结果)
在拿到后端数据填充到选项后，仍然支持更新value

### Actual results (实际的结果)
在编辑功能中，对在tableData使用NSelect，获取后端传来的值后，无法再次对值进行修改

**Comment by amadeus711** [comment]
你的 value 设置的是 defaultValue 还是 value ？

**Comment by duangkey** [comment]
> 你的 value 设置的是 defaultValue 还是 value ？

设置的是value，使用场景是：在tableData中的columns中使用render函数和h函数写NSelect或者NInput，新增时默认值是undefined，此时可以选择或者输入值，当对新增的数据进行编辑时（此时从后端获取到数据填充到select或者input中，就无法修改了）

**Comment by duangkey** [comment]
大佬提醒了我，使用defaultValue 先去接收后端传来的数据，就没有这个问题了，谢谢
