### ISSUE TITLE
如何手动控制data table 树形菜单展开

### ISSUE THREAD

**Issue by wushijiang13** [TuSimple/naive-ui#2695]
### This function solves the problem (这个功能解决的问题)
由于功能需要 单独点击icon 并不能满足需求，并且无法加入其它扩展功能逻辑，如我需要在展开之前请求后台可展开等，无法控制展开将使未来需求不能继续在此扩展下去
### Expected API (期望的 API)
加入单独列属性值控制树形展开

**Comment by wushijiang13** [comment]
data-table 中：https://www.naiveui.com/zh-CN/light/components/data-table

**Comment by 07akioni** [comment]
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/18677354/160676206-a75dcd1e-1094-4506-ba83-8bc7ac8f5f5e.png">
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/18677354/160676224-7c19e5a1-1933-4ea6-8505-0e15afab3348.png">

**Comment by 07akioni** [comment]
可以在点击列的时候把变化先忽略，等数据回来了再控制 expanded-row-keys 打开

**Comment by wushijiang13** [comment]
好的，感谢
