### ISSUE TITLE
提供能够修改组件配置的全局方法

### ISSUE THREAD

**Issue by pengzhen-developer** [TuSimple/naive-ui#2696]
### This function solves the problem (这个功能解决的问题)
解决重复声明属性的问题。

例如在 DatePicker 的组件上，update-value-on-close 属性非常好用，但是每次使用都需要声明该属性为 true。

### Expected API (期望的 API)
提供一个函数，支持初始化时，进行组件属性自定义。

类似这样：https://www.vue-tailwind.com/docs/settings/

```javascript
const settings = {
  TModal: {
    clickToClose: false,
  },
}

// Add the settings as the second parameter when you register your component
Vue.use(VueTailwind, settings)
```

**Comment by 07akioni** [comment]
自己封装一下吧。

他们这种做法局限性太高了，如果他们改了包内组件的默认值，会让多个一起用这个包的包冲突。如果他们不改默认值，那么做不到全局引入的情况下调整这个默认值。

如果你真的有这个诉求，我觉得可以自己维护一个改动脚本，本质上和他们做的事没啥差别

```
NDatePicker.props.updateValueOnClose = { type: Boolean, default: true }
```

**Comment by pengzhen-developer** [comment]
> 自己封装一下吧。
> 
> 他们这种做法局限性太高了，如果他们改了包内组件的默认值，会让多个一起用这个包的包冲突。如果他们不改默认值，那么做不到非全局引入的情况下调整这个默认值。
> 
> 如果你真的有这个诉求，我觉得可以自己维护一个改动脚本，本质上和他们做的事没啥差别
> 
> ```
> NDatePicker.props.updateValueOnClose = { type: Boolean, default: true }
> ```


感谢思路，非常有用。


但这种方法更适合手动按需加载，例如官网介绍中：

``` JavaScript
import { createApp } from 'vue'
import {
  // create naive ui
  create,
  // component
  NDatePicker
} from 'naive-ui'

// 全局调整
NDatePicker.props.updateValueOnClose = { type: Boolean, default: true }

const naive = create({
  components: [NDatePicker]
})

const app = createApp()
app.use(naive)
```


不太适合使用了 unplugin-vue-components 自动按需加载的方式。



最终使用 HOC 的方案迂回解决了 。
但该方法并不推荐，会生成一个额外的无意义的中间组件，并且使用起来也缺少了 Naive UI 丝滑的 TS 提示。
仅供不得已而为之的人参考：

``` JavaScript
// HOC.tsx
import { defineComponent } from 'vue'

export default function HOC(WrappedComponent: any) {
  const yourProps = {
    type: 'primary'
  }

  return defineComponent({
    setup(props, { slots }) {
      return () => (
        <WrappedComponent {...props} {...yourProps}>
          {{
            ...slots
          }}
        </WrappedComponent>
      )
    }
  })
}

```

``` JavaScript
// App.vue

<template>
  <MyButton>My button text</MyButton>
</template>

<script lang="ts">
import HOC from './HOC'
import { NButton } from 'naive-ui'

export default {
  components: {
    MyButton: HOC(NButton)
  }
}
</script>

```

<img width="1715" alt="image" src="https://user-images.githubusercontent.com/12759499/160860663-3f362473-f1cf-471b-96f2-36b91b9b201e.png">

**Comment by 07akioni** [comment]
你说的对，Vue 确实有 hoc 不好封装的问题，目前看除非把最基础的组件 props 定义导出应该是没别的办法能结局
