### ISSUE TITLE
n-time相对时间最小值希望精确到秒

### ISSUE THREAD

**Issue by Baiyuetribe** [TuSimple/naive-ui#2703]
### This function solves the problem (这个功能解决的问题)
使用场景：websocket搭建实时监控面板，一些场景下当前相对时间最小值仅显示“不到一分钟内”,这粒度感觉怪怪的，希望将一分钟内精确到秒。
### Expected API (期望的 API)
n-time相对时间的一分钟内精确到秒，小于1分钟后显示几秒前。

**Comment by Baiyuetribe** [comment]
参考了下date-fns的api，目前naive-ui调用了`formatDistance`所以返回值比较粗略。精确到秒只需要替换为`formatDistanceStrict`这个api就行，看下直接替换？还是另外加个`Strict`属性
参考自：https://date-fns.org/v2.28.0/docs/formatDistanceStrict

**Comment by Baiyuetribe** [comment]
最常用的还是距离现在的相对时间，干脆另外加一个props属性，然后加上`formatDistanceToNowStrict`这个api。就可以精确显示。

**Comment by 07akioni** [comment]
我这周看一下

**Comment by 07akioni** [comment]
closed in https://github.com/TuSimple/naive-ui/pull/2714
