### ISSUE TITLE
修改自定义的文字颜色

### ISSUE THREAD

**Issue by merry-kugua** [TuSimple/naive-ui#2705]
### This function solves the problem (这个功能解决的问题)
可不可以考虑增加自定义文字颜色，:style="十进制颜色编码 "改变当前组件的文字颜色
### Expected API (期望的 API)
menu list 中颜色固定 每次开发需要修改对应的class样式

**Comment by Talljack** [comment]
修改默认的主题变量就好了啊

**Comment by 07akioni** [comment]
menu 有一堆主题变量可以用，去仔细看一下主题定制的文档
