### ISSUE TITLE
希望n-data-table组件增加cell-click回调能力

### ISSUE THREAD

**Issue by a15218378694** [TuSimple/naive-ui#2706]
### This function solves the problem (这个功能解决的问题)
当某个单元格被点击时会触发事件, 类似element-plus的cell-click, 我这边要实现一个, 点击选中变颜色的功能, cellProps是一开始触发的, 好像用不上
### Expected API (期望的 API)
element-plus的cell-click

**Comment by 07akioni** [comment]
cell-props="{ onClick: xxx }"

**Comment by a15218378694** [comment]
> 
没看懂, 官方也没说支持cell-props, 只有cellProps, 能给个完整demo吗, 谢谢了

**Comment by a15218378694** [comment]
> cell-props="{ onClick: xxx }"

我没有看懂, 可以给个demo吗? 谢谢

**Comment by pengzhen-developer** [comment]
> > cell-props="{ onClick: xxx }"
> 
> 我没有看懂, 可以给个demo吗? 谢谢

{
      title: 'Title',
      key: 'title',
      cellProps(rowData, rowIndex){
        return {
          onClick(){
            alert(`点击了${rowIndex}行的 Title`)
          },
        }
      },
    }

**Comment by AlanKnightly** [comment]
@pengzhen-developer  通过cellProps和rowProps下发onClick，发现只要mouseUp，都一律触发click事件，造成严重的bug，请问你们有遇到这个情况嘛？

**Comment by pengzhen-developer** [comment]
> 

https://codesandbox.io/s/crimson-brook-gqt40i?file=/src/Demo.vue

没有这种情况。

**Comment by pengzhen-developer** [comment]
> @pengzhen-developer 通过cellProps和rowProps下发onClick，发现只要mouseUp，都一律触发click事件，造成严重的bug，请问你们有遇到这个情况嘛？



参考示例，没有这种情况。

https://codesandbox.io/s/crimson-brook-gqt40i?file=/src/Demo.vue
