### ISSUE TITLE
mousedown.stop will prevent color-picker to close when click outside

### ISSUE THREAD

**Issue by moolex** [TuSimple/naive-ui#2709]
### TuSimple/naive-ui version (版本)
2.27.0

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
MacOS

### Reappearance link (重现链接)
https://codesandbox.io/s/naive-ui-color-picker-click-outside-9jo6gl?file=/src/App.vue

### Reappearance steps (重现步骤)
Click case1, case2 in codesandbox and click outside

### Expected results (期望的结果)
works as case2 (with onClickOutside from vueuse)

### Actual results (实际的结果)
not works

**Comment by Sepush** [comment]
https://codesandbox.io/s/naive-ui-color-picker-click-outside-forked-6x2ry8?file=/src/App.vue

**Comment by Talljack** [comment]
> https://codesandbox.io/s/naive-ui-color-picker-click-outside-forked-6x2ry8?file=/src/App.vue

https://codesandbox.io/s/naive-ui-color-picker-click-outside-forked-mqqu4v?file=/src/App.vue 这样是有问题的

**Comment by Sepush** [comment]
> > https://codesandbox.io/s/naive-ui-color-picker-click-outside-forked-6x2ry8?file=/src/App.vue
> 
> https://codesandbox.io/s/naive-ui-color-picker-click-outside-forked-mqqu4v?file=/src/App.vue 这样是有问题的

嗯 这样需要点击 400px 以外的才会有效 是否 clickout 的条件确实有点问题

**Comment by Talljack** [comment]
> > > https://codesandbox.io/s/naive-ui-color-picker-click-outside-forked-6x2ry8?file=/src/App.vue
> > 
> > 
> > https://codesandbox.io/s/naive-ui-color-picker-click-outside-forked-mqqu4v?file=/src/App.vue 这样是有问题的
> 
> 嗯 这样需要点击 400px 以外的才会有效 判断是否 clickout 的条件确实有点问题

主要还是.stop了阻止了事件

**Comment by 07akioni** [comment]
This is a bug, we'll try to fix it.
