### ISSUE TITLE
在「轮播图」组建中添加滑动切换/Add cruise ship switching in 「Broadcasting」（Translate by Google）

### ISSUE THREAD

**Issue by HUD-A** [TuSimple/naive-ui#271]
### This function solves the problem (这个功能解决的问题)
手机端用户操作过于麻烦/Too much trouble for mobile users
### Expected API (期望的 API)
能够通过滑动来切换轮播图

**Comment by amadeus711** [comment]
> ### This function solves the problem (这个功能解决的问题)
> 手机端用户操作过于麻烦/Too much trouble for mobile users
> 
> ### Expected API (期望的 API)
> 能够通过滑动来切换轮播图

Planned, not with high priority.
