### ISSUE TITLE
循环select placeholder不显示

### ISSUE THREAD

**Issue by clgwxg** [TuSimple/naive-ui#2711]
### TuSimple/naive-ui version (版本)
2.27.0

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
chrome 99.0.4844.84

### System and its version (系统及其版本)
window10

### Reappearance link (重现链接)
https://codesandbox.io/s/damp-mountain-hl6nc0

### Reappearance steps (重现步骤)
查看CodeSandbox 代码即可

### Expected results (期望的结果)
显示placeholder

### Actual results (实际的结果)
查看CodeSandbox 代码即可

**Comment by Talljack** [comment]
value的值为‘’时会认为这是存在值的，你需要将value默认为null才会显示placeholder
