### ISSUE TITLE
树形选择勾选部分子菜单时，如何将父菜单也变成选中状态

### ISSUE THREAD

**Issue by kane245** [TuSimple/naive-ui#2713]
### This function solves the problem (这个功能解决的问题)
树形选择勾选部分子菜单时，如何将父菜单也变成选中状态
### Expected API (期望的 API)
Tree Select

**Comment by coder-chin** [comment]
看看级联选择器能不能满足你的需求  https://www.naiveui.com/zh-CN/os-theme/components/cascader

**Comment by 07akioni** [comment]
> ### This function solves the problem (这个功能解决的问题)
> 树形选择勾选部分子菜单时，如何将父菜单也变成选中状态
> 
> ### Expected API (期望的 API)
> Tree Select

cascade = true
