### ISSUE TITLE
在SSR环境下使用 Naive ui Message 控件时，从第二次开始的弹框不在有Icon

### ISSUE THREAD

**Issue by sorakylin** [TuSimple/naive-ui#2721]
### TuSimple/naive-ui version (版本)
2.27.0

### Vue version (Vue 版本)
3.2.27

### Browser and its version (浏览器及其版本)
Chrome/99.0.4844.84

### System and its version (系统及其版本)
Win 10

### Node version (Node 版本)
v14.16.0

### Reappearance link (重现链接)
https://github.com/sorakylin/naiveui-message-bug

### Reappearance steps (重现步骤)
* clone repo： https://github.com/sorakylin/naiveui-message-bug
* npm install
* npm run dev
* -> http://localhost:3000/
* click message button

### Expected results (期望的结果)
在服务端渲染（Vite SSR）时使用 Naive ui 的 Message 控件，让第二次及其之后的message弹框出现icon

### Actual results (实际的结果)
只有第一次有icon，从第二次开始就没有icon了。

**Comment by Baiyuetribe** [comment]
还有Grid组件SSR模式下响应式也有问题

**Comment by sorakylin** [comment]
> 还有Grid组件SSR模式下响应式也有问题

Grid这个控件有啥问题？ 我还没发现。
我这用的是Vite SSR，看看有没有你说的情况

**Comment by Baiyuetribe** [comment]
> > 还有Grid组件SSR模式下响应式也有问题
> 
> Grid这个控件有啥问题？ 我还没发现。 我这用的是Vite SSR，看看有没有你说的情况

Grid组件的自适应响应，服务端渲染后需要手动缩放才能跟客户端一样，是个bug. #2462

**Comment by Talljack** [comment]
更多讨论在这里　https://github.com/TuSimple/naive-ui/issues/636#issuecomment-1014702520

**Comment by 07akioni** [comment]
找到原因了，因为使用了静态的 component vnode 导致 hydration 的时候 el 还挂在老的 vnode 上，然后导致走进了水合的逻辑。

感谢复现，这个 bug 终于算是解决了，这么看其他地方其实也有潜在的 bug。

**Comment by oooowl** [comment]
> 找到原因了，因为使用了静态的 component vnode 导致 hydration 的时候 el 还挂在老的 vnode 上，然后导致走进了水合的逻辑。
> 
> 感谢复现，这个 bug 终于算是解决了，这么看其他地方其实也有潜在的 bug。

2.28.0 message正常了，dialog和notification依然存在这个问题

**Comment by 07akioni** [comment]
> > 找到原因了，因为使用了静态的 component vnode 导致 hydration 的时候 el 还挂在老的 vnode 上，然后导致走进了水合的逻辑。
> > 感谢复现，这个 bug 终于算是解决了，这么看其他地方其实也有潜在的 bug。
> 
> 2.28.0 message正常了，dialog和notification依然存在这个问题

Will fix
