### ISSUE TITLE
Select menu not shown in full screen components

### ISSUE THREAD

**Issue by twitwi** [TuSimple/naive-ui#2722]
### TuSimple/naive-ui version (版本)
2.27.0

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
Chromium 100, Firefox 98

### System and its version (系统及其版本)
Linux Manjaro 21.2.5

### Reappearance link (重现链接)
https://www.naiveui.com/en-US/os-theme/components/select

### Reappearance steps (重现步骤)
- Open the documentation page
- Make the content section full-screen using the code below in the console and then clicking on the content (sorry for not creating a codepen)
- click on a select

```javascript
document.querySelector('.document-scroll-container').onclick = e => {
   let root = document.querySelector('.document-scroll-container');
   root.requestFullscreen();
   root.onclick = null;
}
```

### Expected results (期望的结果)
The select should popup up it's list of choice.

### Actual results (实际的结果)
No list of choice is shown (until we leave fullscreen with "escape").

### Remarks (补充说明)
Probably, the menu is created somewhere else in the DOM (outside of the fullscreen component), I'm not sure how much this is a constraint or if there is an easy workaround.

**Comment by 07akioni** [comment]
I think the main problem is that we detach menu to body by default of all popup components.

There's need to provide a global configuration to let user specify where component should be detached.

**Comment by 07akioni** [comment]
I find there's a `to` prop on select. You can use it to specify the (selector of) DOM to detach the select menu.

You can use it currently until we make it also configurable on config-provider.

**Comment by twitwi** [comment]
Amazing. That works and seems to be reactive so I'll be able to use it as a workaround. Thanks a lot !

**Comment by twitwi** [comment]
Thinking about it. https://developer.mozilla.org/en-US/docs/Web/API/Document/fullscreenElement (when non-null) might be a good default for a least-surprise implementation.

**Comment by 07akioni** [comment]
> Amazing. That works and seems to be reactive so I'll be able to use it as a workaround. Thanks a lot !

We'll at least document it recently.

**Comment by 07akioni** [comment]
> Thinking about it. https://developer.mozilla.org/en-US/docs/Web/API/Document/fullscreenElement (when non-null) might be a good default for a least-surprise implementation.

Cool! We will try it later.

**Comment by twitwi** [comment]
That was fast!

**Comment by 07akioni** [comment]
> That was fast!

Thanks for your hint.

**Comment by twitwi** [comment]
Thanks for your project and reactivity.
