### ISSUE TITLE
data-table的数据, 双击复制会带空格, 尽管双击选中的数据是没有空格的

### ISSUE THREAD

**Issue by a15218378694** [TuSimple/naive-ui#2725]
### TuSimple/naive-ui version (版本)
2.27.0

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
C

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/data-table#ajax-usage

### Reappearance steps (重现步骤)
看官网例子就行

### Expected results (期望的结果)
没有空格

### Actual results (实际的结果)
有空格

**Comment by Sepush** [comment]
不能复现

**Comment by Sepush** [comment]
> > 不能复现
> > It Can't be replicated
> 
>  _2022_04_04_17_53_14_892.mp4

好的 在文本编辑器里确实能看出来 多了一个tab

**Comment by coder-chin** [comment]
> > > 不能复现
> > > It Can't be replicated
> > 
> > 
> > _2022_04_04_17_53_14_892.mp4
> 
> 好的 在文本编辑器里确实能看出来 多了一个tab

这个感觉是编辑器配置的原因，我没有复现

**Comment by coder-chin** [comment]
> > 不能复现
> > It Can't be replicated
> 
>  _2022_04_04_17_53_14_892.mp4

粘到其他地方也一样吗，我感觉是编辑器配置问题

**Comment by a15218378694** [comment]
> > > 不能复现
> > > It Can't be replicated
> > 
> > 
> > _2022_04_04_17_53_14_892.mp4
> 
> 粘到其他地方也一样吗，我感觉是编辑器配置问题

你可以试下粘贴到微信, 是部分值有问题, 我家电脑, 和公司的都一样

**Comment by a15218378694** [comment]
> > > 不能复现
> > > It Can't be replicated
> > 
> > 
> > _2022_04_04_17_53_14_892.mp4
> 
> 粘到其他地方也一样吗，我感觉是编辑器配置问题

你好, 请问你们那边复现了吗

**Comment by 07akioni** [comment]
这个双击复制是什么功能，有稳定复现吗？

根据我对 DOM 的检查，DataTable 里面的数据是没有空格的，如果真的是复制的时候出了问题很有可能是哪个复制功能本身有点问题。

<img width="707" alt="image" src="https://user-images.githubusercontent.com/18677354/162053409-f139a635-9c65-4222-9bf7-115d6a7848e8.png">

<img width="721" alt="image" src="https://user-images.githubusercontent.com/18677354/162053469-b4f67588-c0c6-409b-8a6a-631075256227.png">

**Comment by a15218378694** [comment]
> 这个双击复制是什么功能，有稳定复现吗？
> 
> 根据我对 DOM 的检查，DataTable 里面的数据是没有空格的，如果真的是复制的时候出了问题很有可能是哪个复制功能本身有点问题。
> 
> <img alt="image" width="707" src="https://user-images.githubusercontent.com/18677354/162053409-f139a635-9c65-4222-9bf7-115d6a7848e8.png">
> 
> <img alt="image" width="721" src="https://user-images.githubusercontent.com/18677354/162053469-b4f67588-c0c6-409b-8a6a-631075256227.png">

你那边方便录个视频吗 ? 我看看复制出来是怎样的, 主要是我经过了家里和公司的电脑, 都看到了空格, 就纳闷了

**Comment by 07akioni** [comment]
> > 这个双击复制是什么功能，有稳定复现吗？
> > 根据我对 DOM 的检查，DataTable 里面的数据是没有空格的，如果真的是复制的时候出了问题很有可能是哪个复制功能本身有点问题。
> > <img alt="image" width="707" src="https://user-images.githubusercontent.com/18677354/162053409-f139a635-9c65-4222-9bf7-115d6a7848e8.png">
> > <img alt="image" width="721" src="https://user-images.githubusercontent.com/18677354/162053469-b4f67588-c0c6-409b-8a6a-631075256227.png">
> 
> 你那边方便录个视频吗 ? 我看看复制出来是怎样的, 主要是我经过了家里和公司的电脑, 都看到了空格, 就纳闷了

我电脑没这个功能

**Comment by a15218378694** [comment]
> > > 这个双击复制是什么功能，有稳定复现吗？
> > > 根据我对 DOM 的检查，DataTable 里面的数据是没有空格的，如果真的是复制的时候出了问题很有可能是哪个复制功能本身有点问题。
> > > <img alt="image" width="707" src="https://user-images.githubusercontent.com/18677354/162053409-f139a635-9c65-4222-9bf7-115d6a7848e8.png">
> > > <img alt="image" width="721" src="https://user-images.githubusercontent.com/18677354/162053469-b4f67588-c0c6-409b-8a6a-631075256227.png">
> > 
> > 
> > 你那边方便录个视频吗 ? 我看看复制出来是怎样的, 主要是我经过了家里和公司的电脑, 都看到了空格, 就纳闷了
> 
> 我电脑没这个功能

可以下载个oCam, 这个确实只在naive的data-table组件复现, element是没有的

**Comment by Sepush** [comment]
应该是插件问题 和 个人设定的问题 在我的电脑上 naive 多一个 tab element 多一个 \n

**Comment by a15218378694** [comment]
> 应该是插件问题 和 个人设定的问题 双击+ctrl c 在我的电脑上 naive 多一个 tab element 多一个 \n

插件问题, 是指什么插件

**Comment by 07akioni** [comment]
> > 这个双击复制是什么功能，有稳定复现吗？
> > 根据我对 DOM 的检查，DataTable 里面的数据是没有空格的，如果真的是复制的时候出了问题很有可能是哪个复制功能本身有点问题。
> > <img alt="image" width="707" src="https://user-images.githubusercontent.com/18677354/162053409-f139a635-9c65-4222-9bf7-115d6a7848e8.png">
> > <img alt="image" width="721" src="https://user-images.githubusercontent.com/18677354/162053469-b4f67588-c0c6-409b-8a6a-631075256227.png">
> 
> 你那边方便录个视频吗 ? 我看看复制出来是怎样的, 主要是我经过了家里和公司的电脑, 都看到了空格, 就纳闷了

我试了一下，在 mac 上没这个问题

**Comment by 07akioni** [comment]
> > 应该是插件问题 和 个人设定的问题 双击+ctrl c 在我的电脑上 naive 多一个 tab element 多一个 \n
> 
> 插件问题, 是指什么插件

这是浏览器的默认行为，你可以试这个例子

```
<html>
<body>

<table border="1">
  <tr>
    <th>Month</th>
    <th>Savings</th>
  </tr>
  <tr>
    <td>January January January</td>
    <td>$100</td>
  </tr>
</table>

</body>
</html>
```

双击 `January January January`

**Comment by Stew0316** [comment]
> > > 应该是插件问题 和 个人设定的问题 双击+ctrl c 在我的电脑上 naive 多一个 tab element 多一个 \n
> > 
> > 
> > 插件问题, 是指什么插件
> 
> 这是浏览器的默认行为，你可以试这个例子
> 
> ```
> <html>
> <body>
> 
> <table border="1">
>   <tr>
>     <th>Month</th>
>     <th>Savings</th>
>   </tr>
>   <tr>
>     <td>January January January</td>
>     <td>$100</td>
>   </tr>
> </table>
> 
> </body>
> </html>
> ```
> 
> 双击 `January January January`


document.addEventListener('copy', e => {
        e.preventDefault();
        let text = window.getSelection().toString();
        text = text.replace(/\n/g, ''); // 去除所有换行符
        text = text.replace(/\t/g, '');
        e.clipboardData.setData('text/plain', text);
      });
通过阻止浏览器的默认行为和重写有效
