### ISSUE TITLE
手动指定 NTree 的 selected-keys 值时 @update:selected-keys 指定的回调函数无法被正确触发

### ISSUE THREAD

**Issue by qingruikz** [TuSimple/naive-ui#2729]
### TuSimple/naive-ui version (版本)
2.27.0

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
99.0.4844.84

### System and its version (系统及其版本)
Windows 11

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/tree

### Reappearance steps (重现步骤)
```
<template>
    <n-tree
      :data="treeData"
      @update:selected-keys="handleSelectedChange"
      :multiple="true"
      :selected-keys="selectedKeys"
    />
    <n-button @click="handleBtnClick">change</n-button>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const treeData = [
  { key: '001', label: '001', children: [] },
  { key: '002', label: '002', children: [] },
  { key: '003', label: '003', children: [] }
]
const selectedKeys = ref<any[]>([])
const handleSelectedChange = (
  keys: Array<string | number>,
  option: Array<any | null>
) => {
  console.log(keys)
}
const handleBtnClick = () => {
  selectedKeys.value.push('001')
}
</script>
```

### Expected results (期望的结果)
点击按钮 change 后：
① 节点 '001' 会被选中
② 控制台会打印 ['001']

### Actual results (实际的结果)
① 节点 '001' 会被选中
② **_控制台没有打印任何内容_**

**Comment by Talljack** [comment]
expandedKeys也会有这样的问题 @07akioni

**Comment by 07akioni** [comment]
> 

会尽快修一下

**Comment by 07akioni** [comment]
我仔细看了一下例子，这个是符合预期的，用户传入值的变化不应该触发组件的回调

@Talljack 所有的组件都应该是这种逻辑

**Comment by laterdays** [comment]
@07akioni  有一种场景是后台只给了全选的数据，我选中了， 但是我更新的时候， 如果不触发回调， 我就拿不到半选indeterminate-keys的数据 。

**Comment by Mylinaa** [comment]
n-tree 组件可以加入取消选中状态的功能吗
