### ISSUE TITLE
Data Table 的 actions 支持一下Popconfirm ，或者给个demo

### ISSUE THREAD

**Issue by chpinck** [TuSimple/naive-ui#2738]
### This function solves the problem (这个功能解决的问题)
Data Table 的 actions 支持一下Popconfirm ，或者给个demo，尝试了好久，没有搞定
```json
{
  title: 'Action',
  key: 'actions',
  render (row) {
    return h(
      NButton,
      {
        size: 'small',
        onClick: () => sendMail(row)
      },
      { default: () => 'Send Email' }
    )
  }
}
```
### Expected API (期望的 API)
Data Table or Popconfirm

**Comment by Sepush** [comment]
https://codesandbox.io/embed/zealous-lamarr-idq1gf?fontsize=14&hidenavigation=1&theme=dark

**Comment by chpinck** [comment]
@Sepush Tks

**Comment by chpinck** [comment]
@Sepush 
目前可以用，但是console有警告，看能否优化，3Q
```
[Vue warn]: Non-function value encountered for slot "trigger". Prefer function slots for better performance. 
  at <Popconfirm onPositiveClick=fn<onPositiveClick> > 
```

**Comment by Sepush** [comment]
> @Sepush 目前可以用，但是console有警告，看能否优化，3Q
> 
> ```
> [Vue warn]: Non-function value encountered for slot "trigger". Prefer function slots for better performance. 
>   at <Popconfirm onPositiveClick=fn<onPositiveClick> > 
> ```

![image](https://user-images.githubusercontent.com/39197136/164878824-a3c5f097-f771-4a8e-afe9-9414781ac46f.png)
这里改成箭头函数

**Comment by chpinck** [comment]
@Sepush Tks
