### ISSUE TITLE
tooltip/popover增加enterable属性

### ISSUE THREAD

**Issue by labradorGitHubCanine** [TuSimple/naive-ui#2739]
### This function solves the problem (这个功能解决的问题)
类似于element中的功能：
https://element.eleme.cn/#/zh-CN/component/tooltip#attributes

使用场景：在比较密集的一堆按钮中使用tooltip的话，会遮挡住其它按钮，影响操作，增加一个enterable属性即设置tooltip为不可进入的状态，这样即使鼠标悬浮在tooltip上方也不会影响其正常消失，不影响点击其它按钮。
### Expected API (期望的 API)
enterable=true（默认）鼠标进入tooltip，悬浮不会消失
enterable=false 鼠标进入tooltip也不影响其正常消失，不影响点击被tooltip覆盖的内容

**Comment by 07akioni** [comment]
<img width="1318" alt="image" src="https://user-images.githubusercontent.com/18677354/162054346-1ec26f2c-0b69-4748-9994-a27439a57465.png">
