### ISSUE TITLE
tree-select 打开时控制台提示onDrop未定义

### ISSUE THREAD

**Issue by edhumxiang** [TuSimple/naive-ui#2740]
### TuSimple/naive-ui version (版本)
2.27.0

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
 99.0.4844.84

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://github.com/edhumxiang/vite-test-project

### Reappearance steps (重现步骤)
打开treeselect

### Expected results (期望的结果)
不提示

### Actual results (实际的结果)
Property "onDrop" was accessed during render but is not defined on instance. 
![image](https://user-images.githubusercontent.com/37981171/161881517-fcc5d569-5db7-4840-b61b-89b4f4899576.png)

**Comment by Talljack** [comment]
will do

**Comment by 07akioni** [comment]
This is a bug and will be fixed in next version.

Already fixed in main branch. Waiting for release.
