### ISSUE TITLE
data-table加tooltip后, 滚动条有问题(跑到最外面)或者失效

### ISSUE THREAD

**Issue by a15218378694** [TuSimple/naive-ui#2742]
### TuSimple/naive-ui version (版本)
2.27.0

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
Chrome100

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/data-table#ajax-usage

### Reappearance steps (重现步骤)
忽略上面链接, 直接用下面的组件就好, CodeSandbox的模板是支持js的, 而官方是ts的demo, 有点尴尬..公司这个git提不上去, 麻烦直接看视频吧

### Expected results (期望的结果)
不要带动上面的home和about也滚动, 如果放到某些容器内部, 会导致没法滚动

### Actual results (实际的结果)
上面的home和about也跟着滚动

### Remarks (补充说明)
<template>
  <NDataTable
    :columns="columns"
    :data="data"
    :pagination="pagination"
    :bordered="false"
  />
</template>

<script lang="ts">
import { h, defineComponent, ref } from 'vue'
import { NButton, useMessage, DataTableColumns } from 'naive-ui'
const createColumns = ({
  play
}) => {
  return [
    {
      title: 'No',
      key: 'no',
      fixed: 'left',
      width: 100,
      ellipsis: {
        tooltip: true
      }
    },
    {
      title: 'Title',
      key: 'title',
      width: 800,
      ellipsis: {
        tooltip: true
      }
    },
    {
      title: 'Length',
      key: 'length',
      width: 800,
      ellipsis: {
        tooltip: true
      }
    },
    {
      title: 'Length',
      key: 'length',
      width: 600,
      ellipsis: {
        tooltip: true
      }
    },
    {
      title: 'Length',
      key: 'length',
      width: 600,
      ellipsis: {
        tooltip: true
      }
    },
    {
      title: 'Action',
      key: 'actions',
      width: 800,
      ellipsis: {
        tooltip: true
      },
      render (row) {
        return h(
          NButton,
          {
            strong: true,
            tertiary: true,
            size: 'small',
            onClick: () => play(row)
          },
          { default: () => 'Play' }
        )
      }
    }
  ]
}

const data = [
  {
    no: 3, title: `
    Wonderwall1111111111111111111111111111111111111111111111111111111111
    Wonderwall1111111111111111111111111111111111111111111111111111111111
    Wonderwall1111111111111111111111111111111111111111111111111111111111
    Wonderwall1111111111111111111111111111111111111111111111111111111111
    `, length: '4:18',
  },
  {
    no: 3, title: 'Wonderwall1111111111111111111111111111111111111111111111111111111111', length: '4:18',
  },
]

export default defineComponent({
  setup () {
    const message = useMessage()
    return {
      data,
      columns: createColumns({
        play (row: any) {
          message.info(`Play ${row.title}`)
        }
      }),
      pagination: false as const
    }
  }
})
</script>

**Comment by a15218378694** [comment]
https://user-images.githubusercontent.com/29919045/161907607-7855eec8-9026-4e7c-a7fd-038aa058ad4a.mp4

**Comment by a15218378694** [comment]
我是从element-ui转到naive重构的, 希望官方大大可以帮忙看下, 过几天要发生产了...

**Comment by a15218378694** [comment]
这个用一些元素包住之后, 还不会滚动了, 如果去掉column.ellipsis.tooltip = true, 又可以滚动了

**Comment by a15218378694** [comment]
加tooltip, 我看少了这些元素
![image](https://user-images.githubusercontent.com/29919045/161913545-38aafaeb-9951-4b6e-9276-5239bb326314.png)

**Comment by Sepush** [comment]
弄个 codesanboxs 吧 官网的 demo 有 JS 的选项
![image](https://user-images.githubusercontent.com/39197136/161970095-0015250e-2152-417d-954c-f8b6ac890a72.png)

**Comment by 07akioni** [comment]
根据我的感觉不是 data table 带着上面动了，而是太多内容让 datatable 横向溢出，然后让整个页面能滚动了

滚动的是页面，你应该先试试调整一下样式，给 table 一个横向的最大宽度

我在之后的版本应该会调整一下 data-table 内部的折行样式，让折行更友好一些

**Comment by a15218378694** [comment]
> 根据我的感觉不是 data table 带着上面动了，而是太多内容让 datatable 横向溢出了窗口，然后让整个页面能滚动了
> 
> 滚动的是页面，你应该先试试调整一下样式，给 table 一个横向的最大宽度
> 
> 我在之后的版本应该会调整一下 data-table 内部的折行样式，让折行更友好一些

嗯嗯, 这个我通过改组件内部元素样式解决了

**Comment by diduweiwu** [comment]
> 

我遇到了一样的情况,只要加了ellipsis参数就不行,我写了个示例在这里的sandbox,升级了最新版的naiveui还是一样的问题,感谢啦
https://codesandbox.io/s/crazy-scott-gf2m2z?file=/src/Demo.vue
