### ISSUE TITLE
日期选择器 n-date-picker，当type="daterange"时，增加属性使左右两边panel可以同时前进或后退

### ISSUE THREAD

**Issue by tracy2zhang** [TuSimple/naive-ui#2751]
### This function solves the problem (这个功能解决的问题)
比如左边panel是2月，右边是3月，点击左边panel的后退按钮，左边变成1月，右边变成2月。其他组件库的rangepicker基本上默认行为都是这样。希望能增加一个开关来开启此功能
### Expected API (期望的 API)
move-together: boolean

**Comment by 07akioni** [comment]
closes in 1c8de54e802e209a71267bcd4a8e05d9576f4324
