### ISSUE TITLE
drawer组件的onUpdate:show不会在组件显示时触发

### ISSUE THREAD

**Issue by extclp** [TuSimple/naive-ui#2752]
### TuSimple/naive-ui version (版本)
2.27.0

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
chrome 100.0.4896.75 

### System and its version (系统及其版本)
Windows 11

### Node version (Node 版本)
v16.14.2

### Reappearance link (重现链接)
https://codesandbox.io/s/sad-wildflower-2b3z0c?file=/src/Demo.vue

### Reappearance steps (重现步骤)
无

### Expected results (期望的结果)
无

### Actual results (实际的结果)
无

**Comment by 07akioni** [comment]
复合预期，组件不会 watch 一个值然后发事件出来

show 是你传进来的

不然你每次改修改 input 的 value 然后 input 就要发一个 change 事件出来然后就死循环了
