### ISSUE TITLE
建议新增树形表格，展开/收起图标指定显示在哪一列的配置

### ISSUE THREAD

**Issue by wei1034937343** [TuSimple/naive-ui#2757]
### This function solves the problem (这个功能解决的问题)
当树形表格第一列展示自定义序号列时，展开/收起图标默认也显示在第一列，同序号列摆放在一起很不美观
### Expected API (期望的 API)
类似ViewUI的树形表格，在 column 开启属性 tree，则该列会显示展开/收起图标。

如：column =  [
                    {
                        title: '序号',
                        key: 'index'
                    },
                    {
                        title: 'Name',
                        key: 'name',
                        tree: true
                    },
                    {
                        title: 'Age',
                        key: 'age'
                    }
                ];

![image](https://user-images.githubusercontent.com/28970254/162583243-007a8af2-d198-4486-939e-f0d6e475f18d.png)

**Comment by 07akioni** [comment]
会考虑

**Comment by yudan215** [comment]
建议增加可自定义文字或者图标，展开时可异步获取数据等
