### ISSUE TITLE
树形表格异步展开树形数据，未展开树形数据的情况下（type='selection'）点击复选框报错

### ISSUE THREAD

**Issue by wei1034937343** [TuSimple/naive-ui#2758]
### TuSimple/naive-ui version (版本)
2.27.0

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
edge

### System and its version (系统及其版本)
windows11

### Reappearance link (重现链接)
https://codesandbox.io/s/reverent-dawn-sqs1uo?file=/src/Demo.vue

### Reappearance steps (重现步骤)
未展开树形数据的情况下，点击勾选复选框，因为子节点中的数据还未加载，导致报错

### Expected results (期望的结果)
不要报错，把当前已经加载好的数据勾选上

### Actual results (实际的结果)
页面或控制台报错，勾选无反应

### Remarks (补充说明)

![image](https://user-images.githubusercontent.com/28970254/162584603-4fcb30c4-aaa8-4b90-9dbc-27b6d05f2363.png)

**Comment by 07akioni** [comment]
<img width="975" alt="image" src="https://user-images.githubusercontent.com/18677354/162585660-433ce570-9bc0-42e0-a6ca-6b93d69dd57d.png">

设为 false

**Comment by 07akioni** [comment]
是个 bug，cascade 设为 false 也不行
