### ISSUE TITLE
Data table max-height calculated coherently

### ISSUE THREAD

**Issue by liubake** [TuSimple/naive-ui#276]
### TuSimple/naive-ui version (版本)
2.13.0

### Vue version (Vue 版本)
3.1.2

### Browser and its version (浏览器及其版本)
Chrome(91.0.4472.114)

### System and its version (系统及其版本)
Windows10

### Node version (Node 版本)
14.17.1

### Reappearance link (重现链接)
https://github.com/liubake/BugReport/naiveui

### Reappearance steps (重现步骤)
The max-height attribute of data table was not calculated coherently, when data table width is less than 1200px the max-height is not included table header height, but when the width is greater than 1200px the max-height included table header height.

### Expected results (期望的结果)
max-height calculate consistently, include or not include table header height.

### Actual results (实际的结果)
max-height calculated coherently

**Comment by Fnzero** [comment]
Reappearance link cannot open

**Comment by liubake** [comment]
> Reappearance link cannot open

![a_01](https://user-images.githubusercontent.com/32254021/123196725-09127e80-d4dd-11eb-843a-ab18dc505cac.png)
![a_02](https://user-images.githubusercontent.com/32254021/123196729-0a43ab80-d4dd-11eb-9e0a-2799382cf561.png)

this is debug screenshot

**Comment by 07akioni** [comment]
> ### TuSimple/naive-ui version (版本)
> 2.13.0
> 
> ### Vue version (Vue 版本)
> 3.1.2
> 
> ### Browser and its version (浏览器及其版本)
> Chrome(91.0.4472.114)
> 
> ### System and its version (系统及其版本)
> Windows10
> 
> ### Node version (Node 版本)
> 14.17.1
> 
> ### Reappearance link (重现链接)
> https://github.com/liubake/BugReport/naiveui
> 
> ### Reappearance steps (重现步骤)
> The max-height attribute of data table was not calculated coherently, when data table width is less than 1200px the max-height is not included table header height, but when the width is greater than 1200px the max-height included table header height.
> 
> ### Expected results (期望的结果)
> max-height calculate consistently, include or not include table header height.
> 
> ### Actual results (实际的结果)
> max-height calculated coherently
> 
> ### Remarks (补充说明)

This works as expected. Although it's possible to use `ResizeObserver` to achieve your demand (which we have done before), it does a lot of harm to performance (which doesn't worth it) and makes the table more unmaintainable.

If you need the feature you can create a PR.
