### ISSUE TITLE
tree 组件过滤时隐藏无关节点

### ISSUE THREAD

**Issue by duyuntao** [TuSimple/naive-ui#2764]
### This function solves the problem (这个功能解决的问题)
首先感谢naiveui的虚拟树功能，我项目中tree有大量的节点。
在搜索过程中，被命中的节点有下划线效果，但是我需要在众多的节点中寻找被命中的节点，这使得用户体验不太友好，我希望可以隐藏不被命中的节点，只显示被命中的节点和他的父节点以及父节点的父节点，直到根节点。en..我想我表达清楚了。当然这个功能不能影响虚拟树本身的功能，包括拖拽。
### Expected API (期望的 API)
filterDisplayMode 属性.  一个String枚举或者Boolean ，默认为下划线选中效果（就现在的展示效果），另一个为只展示命中节点效果

**Comment by 07akioni** [comment]
会做

**Comment by duyuntao** [comment]
> 会做
大概什么时候呢

**Comment by ddkwork** [comment]
> > > 会做
> > > 大概什么时候呢
> 
> 已经上了，看 changelog

大佬你好，表格和树形表格可否增加一个全局搜索的开关，类似tree这个的搜索，小白菜初学乍道啊
