### ISSUE TITLE
Improved multiple file upload handling

### ISSUE THREAD

**Issue by lwansbrough** [TuSimple/naive-ui#2765]
### This function solves the problem (这个功能解决的问题)
When dropping multiple files into the upload area, we can obtain the full path of files within sub-directories. This is useful if the user drops one or more folders, instead of individual files. It is made possible by using non-standard APIs that (I believe) are supported by major browsers (https://caniuse.com/?search=webkitGetAsEntry). As a result, you get a full path like `my-folder/images/foo.jpeg`

Here is the code to support this behaviour.

```
async function drop(e) {
  e.preventDefault()
  e.stopPropagation()
  let transfer = e.dataTransfer
  let entries = await getAllFileEntries(transfer.items)

  entries.forEach(async entry => {
    entry.file(async file => {
      console.log(entry.fullPath, file)
    })
  })
}

async function getAllFileEntries(dataTransferItemList) {
  let fileEntries = []
  let queue = []
  for (let i = 0; i < dataTransferItemList.length; i  ) {
    queue.push(dataTransferItemList[i].webkitGetAsEntry())
  }

  while (queue.length > 0) {
    let entry = queue.shift()
    if (entry.isFile) {
      fileEntries.push(entry)
    } else if (entry.isDirectory) {
      let reader = entry.createReader()
      queue.push(...await readAllDirectoryEntries(reader))
    }
  }
  return fileEntries
}

async function readAllDirectoryEntries(directoryReader) {
  let entries = []
  let readEntries = await new Promise(directoryReader.readEntries)
  while (readEntries.length > 0) {
    entries.push(...readEntries)
    readEntries = await new Promise(directoryReader.readEntries)
  }
  return entries
}
```
### Expected API (期望的 API)
The API can remain unchanged, but `UploadFileInfo` should have `fullPath` or similar.

**Comment by 07akioni** [comment]
Is it possible to also support `directory`?

https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory

**Comment by lwansbrough** [comment]
Good question, maybe! I would be interested to see what is returned from the input change event. It may include `e.items` or something which could be the `DataTransferItem` type.
