### ISSUE TITLE
scrollbar nuxt3中不显示

### ISSUE THREAD

**Issue by oooowl** [TuSimple/naive-ui#2769]
### TuSimple/naive-ui version (版本)
2.28.0

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
chrome100

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://codesandbox.io/s/admiring-boyd-mgee7y?file=/app.vue

### Reappearance steps (重现步骤)
npm  install   && npm run dev

### Expected results (期望的结果)
scrollbar nuxt3中不显示，n-layout的scrollbar 也有这个问题

### Actual results (实际的结果)
scrollbar nuxt3 正常显示

**Comment by 07akioni** [comment]
We have find that this is an vue issue. You can upgrade vue to `3.2.36` to solve the problem.
