### ISSUE TITLE
timeline左右个性化设置

### ISSUE THREAD

**Issue by qqfei1858** [TuSimple/naive-ui#277]
### This function solves the problem (这个功能解决的问题)
timeline左边显示时间,右边显示内容,如下图
![image](https://user-images.githubusercontent.com/26538473/123193603-abc7fe80-d4d7-11eb-9d76-89148c6dd506.png)

### Expected API (期望的 API)
暂无

**Comment by 07akioni** [comment]
The style requires a totally another implementation compared with current timeline. The style if too specific. We won't provide it.
