### ISSUE TITLE
NBadge content color

### ISSUE THREAD

**Issue by EgorPopovPP** [TuSimple/naive-ui#2772]
### This function solves the problem (这个功能解决的问题)
I used NBadge component and ran into unexpected behavior
Color of Badge's content is red by default, that unseen from the docs
Can we create prop for text color or at least add demo case in docs?
<img width="113" alt="image" src="https://user-images.githubusercontent.com/36714079/162764394-910f7efd-7361-4b4d-bdbe-613f7d3b0b5d.png">

### Expected API (期望的 API)
Add prop `text/text-color/text-type` for text color or add demo case in docs

**Comment by Sepush** [comment]
![image](https://user-images.githubusercontent.com/39197136/162864146-e4ce6cbd-7dc8-4910-adf2-616ef3e1bab2.png)
add style for the content
