### ISSUE TITLE
DatePicker 的 focus方法没有弹出选择器

### ISSUE THREAD

**Issue by ununian** [TuSimple/naive-ui#2773]
### TuSimple/naive-ui version (版本)
2.27.0

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
Chrome/100.0.4896.75

### System and its version (系统及其版本)
Windows 10

### Reappearance link (重现链接)
https://stackblitz.com/edit/vitejs-vite-tsdcog?file=src/App.vue

### Reappearance steps (重现步骤)
datePicker.focus。
点击按钮，DatePicker的Input只是获取了焦点，但是没有日期选择器弹出来。

### Expected results (期望的结果)
一般来说 DatePicker 的执行 focus 函数是为了弹出日期选择器吧。期望执行了 focus 后能出现日期选择器。
或者为了区分 focus 和 active 行为，可以新增一个 active 函数，或者 showPicker 函数。

### Actual results (实际的结果)
点击按钮，DatePicker的Input只是获取了焦点，但是没有日期选择器弹出来。

### Remarks (补充说明)
我看 handleInputActivate 可以实现想要的效果，只要重新导出一下就能实现了吧。

**Comment by Sepush** [comment]
这是复合预期的 不需要改

**Comment by ununian** [comment]
@Sepush 那能否加一个 active 或者 showPicker 函数呢

**Comment by 07akioni** [comment]
> @Sepush 那能否加一个 active 或者 showPicker 函数呢

为啥需要这个？场景是啥

**Comment by ununian** [comment]
> > @Sepush 那能否加一个 active 或者 showPicker 函数呢
> 
> 为啥需要这个？场景是啥

我们有一个开始时间和结束时间的选择框，但是都可以单独选择，所以不能用 DateRange。如果选择的开始时间大于结束时间，就需要用户重新选择结束时间，这时候需要自动打开结束时间的选择面板。

**Comment by 07akioni** [comment]
> > > @Sepush 那能否加一个 active 或者 showPicker 函数呢
> > 
> > 
> > 为啥需要这个？场景是啥
> 
> 我们有一个开始时间和结束时间的选择框，但是都可以单独选择，所以不能用 DateRange。如果选择的开始时间大于结束时间，就需要用户重新选择结束时间，这时候需要自动打开结束时间的选择面板。

那用户就是不选呢？

**Comment by cai1035752265** [comment]
打开选择器可以使用update:show。但是我想问的是，focus说是聚焦但只是边框有个聚焦的样式，鼠标光标并没有出现，这个问题该怎么解决
