### ISSUE TITLE
n-drawer在native-scrollbar属性设置为false时内容无法正常显示

### ISSUE THREAD

**Issue by labradorGitHubCanine** [TuSimple/naive-ui#2774]
### TuSimple/naive-ui version (版本)
2.28.0

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
windows

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/drawer

### Reappearance steps (重现步骤)
<n-drawer :show="true" :native-scrollbar="true" :width="502">
    <n-drawer-content title="斯通纳">
        《斯通纳》是美国作家约翰·威廉姆斯在 1965 年出版的小说。
    </n-drawer-content>
</n-drawer>

### Expected results (期望的结果)
在:native-scrollbar="true"时，内部的文字可以正常显示
在:native-scrollbar="false"时，内部没有任何文字的显示（除了title中的内容）

### Actual results (实际的结果)
内容正常显示

**Comment by 07akioni** [comment]
研究了一下，这属于一个预期行为。

n-drawer-content 不应该和外部的 native-scrollbar=false 共存，会在文档里面明确一下。
