### ISSUE TITLE
Scrollbar components exposed

### ISSUE THREAD

**Issue by jahnli** [TuSimple/naive-ui#278]
### This function solves the problem (这个功能解决的问题)
user experience
### Expected API (期望的 API)
1、Scrollbar components exposed
2、The scroll bar is too dark

**Comment by Fnzero** [comment]
In fact, you can use <n-scrollbar> now

**Comment by jahnli** [comment]
ok，Whether can document clearly

**Comment by jahnli** [comment]
Whether the scrollbar is too dark can be changed or custom-configured

**Comment by 07akioni** [comment]
We are not gonna to document scrollbar. Not stable warranty for the API.

`n-scrollbar` is designed to only work with naive components (although it can work with most common scene). In fact it's impossible to write a scrollbar component which behaviors the same as browser scrollbar. We have no extra time to deal with relevant issue.

So if you are trying to use it, please note that we don't promise it will works in your scene. If it doesn't work as you expected, please check source code and find the solution.
