### ISSUE TITLE
Conflict with tailwindcss normalize.css

### ISSUE THREAD

**Issue by Alverrt** [TuSimple/naive-ui#2782]
### TuSimple/naive-ui version (版本)
2.28.0

### Vue version (Vue 版本)
3.2.32

### Browser and its version (浏览器及其版本)
Chrome Version 100.0.4896.75 (Official Build) (arm64)

### System and its version (系统及其版本)
MacOS(11.5.2)

### Reappearance link (重现链接)
https://codesandbox.io/s/admiring-dream-jjx2ci?file=/src/Demo.vue

### Reappearance steps (重现步骤)
Just install tailwindcss and add buttons with type of "primary"

### Expected results (期望的结果)
Buttons background expected to be colorful because of "primary" button type.

### Actual results (实际的结果)
Unlike primary type, buttons acting like default type with only outlines and button text is invisible.

### Remarks (补充说明)
There is a conflict with tailwind's normalizer. Normalizers overrides naive's buttons background color.

**Comment by Sepush** [comment]
a solution has been provided in docs read it
https://www.naiveui.com/en-US/os-theme/docs/style-position

**Comment by czhlin** [comment]
其实保持：1.tailwind 2.naive-ui 3.main.css的顺序是最合理的
所以可以在html中这样修改
In fact, maintaining the order of 1.tailwind 2.naive-ui 3.main.css is the most reasonable, so it can be modified like this in html
<link rel="stylesheet" href="/tailwind.css" />
<meta name="naive-ui-style" />
Copy
// main.ts
import 'uno.css'
import '~/styles/main.css'

**Comment by czhlin** [comment]
其实保持：1.tailwind 2.naive-ui 3.main.css的顺序是最合理的
所以可以在html中这样修改

In fact, maintaining the order of 1.tailwind 2.naive-ui 3.main.css is the most reasonable, so it can be modified like this in html
```html
<link rel="stylesheet" href="/tailwind.css" />
<meta name="naive-ui-style" />
```
```typescript
// main.ts
import 'uno.css'
import '~/styles/main.css'
````
