### ISSUE TITLE
表单验证增强

### ISSUE THREAD

**Issue by carbonhe** [TuSimple/naive-ui#2784]
### This function solves the problem (这个功能解决的问题)
建议可以在表单验证的validator函数里可以获取当前FormItem的label值。这样可以把validator函数抽离到其他的地方,且给到用户的错误消息可以根据label值明确是哪个控件产生的错误
### Expected API (期望的 API)
validator(..., label:string){
 if(!value){
   return new Error(`${label}` 不能为空)
}
return ture
}

**Comment by Talljack** [comment]
rule.field应该可以拿到这个信息

**Comment by carbonhe** [comment]
@Talljack   这个拿到的应该是FormItem里面的path属性而非label

**Comment by Talljack** [comment]
> @Talljack 这个拿到的应该是FormItem里面的path属性而非label

噢，我弄错了

**Comment by 07akioni** [comment]
这个目前从 API 层面看应该很难加了，之前的设计不是很好，基本是完全交给了 async-validator 验证，现在也没法再塞个参数进去
