### ISSUE TITLE
能否把虚拟列表集成在Naive UI?

### ISSUE THREAD

**Issue by qqfei1858** [TuSimple/naive-ui#279]
### This function solves the problem (这个功能解决的问题)
在业务场景中,有时我们需要在自定义列表中使用虚拟滚动!希望在Naive UI集成,虽然有vueuc!
### Expected API (期望的 API)
暂无

**Comment by 07akioni** [comment]
> ### This function solves the problem (这个功能解决的问题)
> 在业务场景中,有时我们需要在自定义列表中使用虚拟滚动!希望在Naive UI集成,虽然有vueuc!
> 
> ### Expected API (期望的 API)
> 暂无

不会这么做，组件库和底层工具库做的不是一类事情，有需要的话可以直接使用 vueuc
