### ISSUE TITLE
use  n-popover set trigger="manual"  has  bug   slot[trigger] is empty

### ISSUE THREAD

**Issue by zlz20180804** [TuSimple/naive-ui#2792]
### TuSimple/naive-ui version (版本)
2.28.0

### Vue version (Vue 版本)
3.2.33

### Browser and its version (浏览器及其版本)
chrome latest

### System and its version (系统及其版本)
none

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/popover#Popover-Props

### Reappearance steps (重现步骤)
none

### Expected results (期望的结果)
repair bug

### Actual results (实际的结果)
use  n-popover set trigger="manual"  has  bug   slot[trigger] is empty

**Comment by Talljack** [comment]
Please give a peappearance demo link

**Comment by 07akioni** [comment]
no reproduction
