### ISSUE TITLE
Notification增加图标render 函数

### ISSUE THREAD

**Issue by oooowl** [TuSimple/naive-ui#2793]
### This function solves the problem (这个功能解决的问题)
Notification增加图标render 函数

目前nuxt3中第二次调用不显示，可以通过传递render 函数 弥补这个bug 
### Expected API (期望的 API)
icon:() => VNodeChild

**Comment by 07akioni** [comment]
> ### This function solves the problem (这个功能解决的问题)
> Notification增加图标render 函数
> 
> 目前nuxt3中第二次调用不显示，可以通过传递render 函数 弥补这个bug
> 
> ### Expected API (期望的 API)
> icon:() => VNodeChild

我大概知道问题在哪了，会修复

**Comment by 07akioni** [comment]
然后 avatar 和图标是一样的位置，用 avatar 可以覆盖图标
