### ISSUE TITLE
Input Number add `decimalSeparator` prop

### ISSUE THREAD

**Issue by jdwit** [TuSimple/naive-ui#2795]
### This function solves the problem (这个功能解决的问题)
Currently the Input Number component works great when using the dot `.` when entering decimals. However in may countries some other character is used as a separator. For instance in my country we use a comma `,`. When the used decimal separator is configurable using a prop `decimalSeparator` the Input Number component will be more usable in many locales.
### Expected API (期望的 API)
A `decimalSeparator: string` prop is added. This is a dot `'.'` by default. The component maintains its internal state with the valid number value. For instance the util function `isWipValue` is currenty:
```
export function isWipValue (value: string | string[]): boolean {
  return value.includes('.') && (/^(-)?\d .*(\.|0)$/.test(value) || /^\.\d $/.test(value))
}
```
The dot `.` is harcoded in the regular expression, this needs to be replaced with the value of `decimalSeparator` prop (among some other things that need to be changed).

Ideally multiple strings are supported (`string[]`) since dot and comma are used interchangeable and it will be confusing if one of them is not accepted.

The Ant Design library has a InputNumber component that supports exactly this (a single value howwever), this can be used for reference. https://ant.design/components/input-number/#API, https://antdv.com/components/input-number/#API

**Comment by Talljack** [comment]
same as #1859
