### ISSUE TITLE
期望在【UploadCustomRequestOptions】的onError和onFinish中提供服务端处理上传请求之后返回的数据

### ISSUE THREAD

**Issue by casatwy** [TuSimple/naive-ui#2799]
### This function solves the problem (这个功能解决的问题)
文件上传完成时，服务端会生成这个文件的URL，然后在上传成功时随着请求的返回而带给前端。
虽然目前在uploader上传组件里直接使用file来展示图片了，但其他地方还是要用URL的，所以期望uploader组件在上传结束之后，能够将本次上传请求的服务端数据也能够透传出来
### Expected API (期望的 API)
期望在【UploadCustomRequestOptions】的onError和onFinish中提供服务端处理上传请求之后返回的数据

**Comment by 07akioni** [comment]
如果用了 onCustomRequest，你应该是先拿到响应再调用的 onFinish。比如
```
...
const resp = axios(...)
// 所以你可以在这个地方直接使用你自己拿到的响应结果
onFinish()
// 或者在这个地方也可以
```

如果我要你把结果传进去再穿出来就是没有必要的冗余了。

**Comment by casatwy** [comment]
我可能是没有理解，目前看你的描述，我确认一下这意思哈

是我在onCustomRequest的回调函数里，我根据参数给到的request对象自己发起请求，然后再调用跟随这个request对象里的onError和onFinish是吧？

```html
<n-uploader :customRequest="handleCustomRequest"  ... />
```

```javascript
async function handleCustomRequest(request) {
  let response = await axios(reformedRequest) // reformedRequest是由request整理得来
  if (response.data.success) {
    request.onFinish()
  } else {
    request.onError()
  }
}
```

我确认一下你的意思是这样的吧？

**Comment by 07akioni** [comment]
我不是太理解你的说法。

从根源上讲就是 custom request 的时候是你拿到数据之后再告诉组件你完成了，这个时候数据已经在你手上了，不需要从再从组件的回调拿任何东西。

**Comment by 1459632934** [comment]
对 我也想拿到这个文件的返回结果 但是不会
