### ISSUE TITLE
date-picker  With shortcut options 

### ISSUE THREAD

**Issue by jahnli** [TuSimple/naive-ui#280]
### This function solves the problem (这个功能解决的问题)
Shortcut options missing
### Expected API (期望的 API)
date-picker  With shortcut options 
For example, the latest day, the latest week, the latest month

**Comment by 07akioni** [comment]
Planned

**Comment by theo-stocchetti** [comment]
@07akioni  Currently the first day of the week is Sunday, is it planned to set it to Monday?

**Comment by 07akioni** [comment]
> @07akioni Currently the first day of the week is Sunday, is it planned to configure it to Monday?

It's related to locale.You want monday first in English?

**Comment by theo-stocchetti** [comment]
No, for the English language, everything works fine. It would be for the French language. I was also thinking of adding in parallel the configuration for this one, as it is the case for the other languages: 
https://github.com/TuSimple/naive-ui/tree/75fc48e31f3d7f49baebde31769dbbd141cde374/src/locales/date

**Comment by 07akioni** [comment]
> https://github.com/TuSimple/naive-ui/tree/75fc48e31f3d7f49baebde31769dbbd141cde374/src/locales/date

There is a french PR.

https://github.com/TuSimple/naive-ui/pull/895

**Comment by 07akioni** [comment]
> No, for the English language, everything works fine. It would be for the French language. I was also thinking of adding in parallel the configuration for this one, as it is the case for the other languages:
> https://github.com/TuSimple/naive-ui/tree/75fc48e31f3d7f49baebde31769dbbd141cde374/src/locales/date

Or you can create a PR for French it there's no progress in that PR.
