### ISSUE TITLE
【咨询】在主题配置器里找不到NSelect的border的配置，请问一下它是落在哪个地方？

### ISSUE THREAD

**Issue by casatwy** [TuSimple/naive-ui#2804]
### This function solves the problem (这个功能解决的问题)
需要去掉NSelect的border
### Expected API (期望的 API)
无

**Comment by 07akioni** [comment]
https://www.naiveui.com/zh-CN/os-theme/docs/customize-theme#%E4%BD%BF%E7%94%A8-peers-%E4%B8%BB%E9%A2%98%E5%8F%98%E9%87%8F
