### ISSUE TITLE
NDataTable建议增加自定义展开功能

### ISSUE THREAD

**Issue by yudan215** [TuSimple/naive-ui#2808]
### This function solves the problem (这个功能解决的问题)
可在某单元格后面跟随自定义图标或者文件，点击展开不同内容·例如展开一个新的表格·
展开时可异步请求接口获取对应表格数据进行渲染
### Expected API (期望的 API)
暂时没想到

**Comment by 07akioni** [comment]
https://www.naiveui.com/zh-CN/os-theme/components/data-table#expand

**Comment by yudan215** [comment]
> https://www.naiveui.com/zh-CN/os-theme/components/data-table#expand

这个只允许在独立列实现，希望是可以在其他数据单元格后面增加一个自定义图标·点击展开功能

**Comment by yudan215** [comment]
> https://www.naiveui.com/zh-CN/os-theme/components/data-table#expand

或者是否能增加触发的方法，目前只能通过type列为expand的才可展开，并且没有类似树形表格异步展开树形数据的回调方法
