### ISSUE TITLE
Input Number  Button position

### ISSUE THREAD

**Issue by jahnli** [TuSimple/naive-ui#281]
### This function solves the problem (这个功能解决的问题)
So far the Input Number is not customizable
### Expected API (期望的 API)
Input Number  Button position

For example: left and right（   - 100    ）, up and down （ 100 ±  ）

**Comment by 07akioni** [comment]
Due to the complexity of implementation, we won't provide an up and down position.

Also, in which scene do you need to place the button to the left? 

We may provide and left positioned button later (but only for rtl support).

**Comment by jahnli** [comment]
One scenario: -99 +

**Comment by 07akioni** [comment]
> One scenario: -99 +

I don't think this is quite necessary. I'll keep the issue open and check if there is more interaction.
