### ISSUE TITLE
NDataTable 展开一个表格不显示

### ISSUE THREAD

**Issue by yudan215** [TuSimple/naive-ui#2811]
### TuSimple/naive-ui version (版本)
2.28.0

### Vue version (Vue 版本)
3.2.33

### Browser and its version (浏览器及其版本)
89

### System and its version (系统及其版本)
Windows 11

### Reappearance link (重现链接)
https://github.com/

### Reappearance steps (重现步骤)
`    renderExpand: () => (h(
      NDataTable,
      {
        data: data,
        cloumns: cloumns,
)),
  }`

### Expected results (期望的结果)
显示正常表格

### Actual results (实际的结果)
只显示一条线

**Comment by 07akioni** [comment]
1. 缺少重现链接
2. 拼写错误：cloumns: cloumns，应该是 columns
