### ISSUE TITLE
使用级联选择，选择多项内容时，使用max-tag-count，鼠标放置多余数量上，悬浮框展示所有的选项。此时，如果数据过多，悬浮框展示不全，应有滚动条！

### ISSUE THREAD

**Issue by Jasmine-xq** [TuSimple/naive-ui#2815]
### TuSimple/naive-ui version (版本)
2.28.0

### Vue version (Vue 版本)
3.2.33

### Browser and its version (浏览器及其版本)
Google Chrome（100.0.4896.88）

### System and its version (系统及其版本)
Windows10

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/cascader

### Reappearance steps (重现步骤)
使用级联选择，选择多项内容时，使用max-tag-count，鼠标放置多余数量上，悬浮框展示所有的选项。此时，如果数据过多，悬浮框展示不全，应有滚动条！

### Expected results (期望的结果)
使用级联选择，选择多项内容时，使用max-tag-count，鼠标放置多余数量上，悬浮框展示所有的选项。此时，如果数据过多，悬浮框展示不全，应有滚动条！

### Actual results (实际的结果)
使用级联选择，选择多项内容时，使用max-tag-count，鼠标放置多余数量上，悬浮框展示所有的选项。此时，如果数据过多，悬浮框展示不全，没有滚动条！

**Comment by Jasmine-xq** [comment]
![image](https://user-images.githubusercontent.com/68681111/163906271-943e54aa-8f0c-4f94-ac75-02b4ef31d2e0.png)

**Comment by vintonHuang** [comment]
这里不会出现数量过多的情况下，悬浮框展示所有的选项，然后出现页面卡顿嘛？ 数量大于2500以上
