### ISSUE TITLE
data-table在特定情况下没有正常显示竖向的border

### ISSUE THREAD

**Issue by labradorGitHubCanine** [TuSimple/naive-ui#2817]
### TuSimple/naive-ui version (版本)
2.28.0

### Vue version (Vue 版本)
3.2.33

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
windows10

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/data-table

### Reappearance steps (重现步骤)
1.开启了表格的竖向border属性
2.后面两列设置了fixed=right属性
3.当表格横向滚动到最右边时，fixed的列和没有fixed的列之间的border消失不见了
4.这种情况只有在浏览器缩放=100%时才出现，放大或缩小border都会显示出来

### Expected results (期望的结果)
正常显示border

### Actual results (实际的结果)
没有正常显示border

**Comment by 07akioni** [comment]
> 没有滚动到最右边时border正常显示 ![1650359285(1)](https://user-images.githubusercontent.com/28785991/163970348-b7a8918b-d5c5-43be-ae87-e4cb626aa1fc.png)
> 
> 滚动到最右边border消失了 ![1650359338(1)](https://user-images.githubusercontent.com/28785991/163970483-e9bf91c7-15bd-4c3d-8f83-b52d74c67946.png)
> 
> 浏览器缩放调整为110%可以正常显示border（除了100%都可正常显示） ![1650359357(1)](https://user-images.githubusercontent.com/28785991/163970673-ab51e9fd-5d3c-41fa-8226-28a0cae15575.png)

如果真的是这样的话大大概率是浏览器的问题。

然后我们需要一个完整的 codesandbox 复现来排查
