### ISSUE TITLE
部分组件缺少原生HTML的props类型

### ISSUE THREAD

**Issue by UMRzcz-831** [TuSimple/naive-ui#2823]
### This function solves the problem (这个功能解决的问题)
不能将类型“{ onClick: () => void; key: number; "v-slots": { prefix: () => Element; }; }”分配给类型“IntrinsicAttributes & Partial<{}> & Omit<Readonly<ExtractPropTypes<{}>> & VNodeProps & AllowedComponentProps & ComponentCustomProps, never>”。
  类型“IntrinsicAttributes & Partial<{}> & Omit<Readonly<ExtractPropTypes<{}>> & VNodeProps & AllowedComponentProps & ComponentCustomProps, never>”上不存在属性“onClick”。ts(2322)
### Expected API (期望的 API)
如<NListItem/>组件，补充onCLick事件

**Comment by Sepush** [comment]
哪个组件 有在线demo吗 应该是你写错了

**Comment by UMRzcz-831** [comment]
那只能 勉为其难这样`{...{onClick: () => handleSomthing as any}`

**Comment by 07akioni** [comment]
> 那只能 勉为其难这样`{...{onClick: () => handleSomthing as any}`

这种组件本身没提供的就得依赖 vue-tsc 做一些骚操作了，因为从 jsx 层面讲，任何没声明的都是不合法，vue 在运行时并没有这种限制
