### ISSUE TITLE
DataTable 可否指定rowKey键名

### ISSUE THREAD

**Issue by AnsGoo** [TuSimple/naive-ui#2825]
### This function solves the problem (这个功能解决的问题)
DataTable 的rowKey键名默认是'key',但是我的数据里面没有key,我想以Id作为key，这时候我不得的不给每行手动加一个‘key’的键，值为id的值
### Expected API (期望的 API)
 aliasRowkey

**Comment by 07akioni** [comment]
> 我看支持rowkey属性`:rowKey="(rowData) => rowData.id"`，是可以满足这个需求，可否这样`rowkey="id"`

不会支持，一件事没必要有两种做法
