### ISSUE TITLE
n-select 组件远程搜索bug

### ISSUE THREAD

**Issue by flyingTodream** [TuSimple/naive-ui#2826]
### TuSimple/naive-ui version (版本)
2.28.1

### Vue version (Vue 版本)
3.2.33

### Browser and its version (浏览器及其版本)
100.0.4896.127

### System and its version (系统及其版本)
MacOS12.3.1

### Reappearance link (重现链接)
https://codesandbox.io/s/hopeful-sun-st0y5g

### Reappearance steps (重现步骤)
1. 设置show属性
2. 输入搜索关键词
3. 点击option
4. option的label没有回填至select框

### Expected results (期望的结果)
期望option的label回填至select并关闭option菜单选项

### Actual results (实际的结果)
实际并未回填，option菜单也并未关闭

**Comment by 07akioni** [comment]
options 一直有长度，show 一直是 true，自然不会关掉。

目前清除 query 的条件是关闭，而不是选中。
