### ISSUE TITLE
data-table中使用pagination属性在script setup语法中失效

### ISSUE THREAD

**Issue by fcloud89** [TuSimple/naive-ui#2837]
### TuSimple/naive-ui version (版本)
2.28.2

### Vue version (Vue 版本)
3.2.33

### Browser and its version (浏览器及其版本)
Chrome(100.0.4896.127)

### System and its version (系统及其版本)
MacOS(12.3.1)

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/data-table#controlled-page

### Reappearance steps (重现步骤)
在vue3.2 环境下，
采用<script setup>语法，
对data-table的参数pagination进行赋值（受控或非受控模式均可）
再进行表格数据增删，改变数据条数

### Expected results (期望的结果)
期望data-table内的pagination属性，在常规setup(){return {...}}语法下，以及<script setup>语法下，均正常

### Actual results (实际的结果)
pagination对象内设定的值均无效，
并且无法随表格数据变化，而改变pagination内的数据，例如数据总数，页码等

### Remarks (补充说明)
采用常规
setup () {
    return {
      pagination: {...}
    }
}
则无问题

**Comment by 07akioni** [comment]
需要完整复现
