### ISSUE TITLE
数据表格的文档样例"受控的过滤器"使用表现有问题

### ISSUE THREAD

**Issue by WHYBBE** [TuSimple/naive-ui#2840]
### TuSimple/naive-ui version (版本)
2.27.0

### Vue version (Vue 版本)
3.2.32

### Browser and its version (浏览器及其版本)
Edge(100.0.1185.44)

### System and its version (系统及其版本)
Windows11(22H2)

### Reappearance link (重现链接)
https://codesandbox.io/s/2k4br0

### Reappearance steps (重现步骤)
1. 打开沙盒
2. 打开Demo.vue文件
3. 改变第105行的pageSize:为3
4. 在界面上对Address进行筛选，条件为London，筛选成功
5. 清除筛选条件
6. 在界面上让数据表格切换到第二页
7. 再对Address进行筛选，条件为London，数据为空，筛选失败

### Expected results (期望的结果)
我觉得切换到第二页后，再对条件进行筛选应该和第一页的筛选结果一样，或者至少是对第二页有的数据进行筛选

### Actual results (实际的结果)
只要是不对第一页进行筛选，那么查询的结果总是为空

**Comment by 07akioni** [comment]
我感觉我们应该限制一下分页
