### ISSUE TITLE
inject() can only be used inside setup() or functional components

### ISSUE THREAD

**Issue by madsh93** [TuSimple/naive-ui#2849]
### This function solves the problem (这个功能解决的问题)
Is it a bug, am I doing something wrong or does NaiveUI not handle calling e.g. `useMessage` inside a composable?

I'm getting this error: 
`inject() can only be used inside setup() or functional components`
### Expected API (期望的 API)
If calling useMessage inside a composable is not possible. Maybe it should be added to docs. But i'm sure i'm mistaken.

**Comment by Talljack** [comment]
![image](https://user-images.githubusercontent.com/34439652/165206403-366c0043-deed-445c-91ba-dbdac5d773be.png)
![image](https://user-images.githubusercontent.com/34439652/165206430-96ca623d-a4c9-4451-81c5-4922d7379043.png)
Maybe your usage is wrong, I can.
