### ISSUE TITLE
breadcrumb dropdown Hover the mouse style

### ISSUE THREAD

**Issue by jahnli** [TuSimple/naive-ui#285]
### TuSimple/naive-ui version (版本)
2.14.0

### Vue version (Vue 版本)
3.1.2

### Browser and its version (浏览器及其版本)
89

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://codesandbox.io/s/4i02l

### Reappearance steps (重现步骤)
In the demo, the first mouse hover in the drop-down menu is inconsistent with the second mouse hover  

### Expected results (期望的结果)
stay the same 

### Actual results (实际的结果)
In the demo, the first mouse hover in the drop-down menu is inconsistent with the second mouse hover

**Comment by 07akioni** [comment]
This works as expected. We may need to provide a new API to let user determine if a breadcrumb item is clickable.
