### ISSUE TITLE
时间组件没有close和submit的回调

### ISSUE THREAD

**Issue by Tomato-Java** [TuSimple/naive-ui#2852]
### This function solves the problem (这个功能解决的问题)
在使用时间组件 时，点击底部的关闭和确认按钮后， 没有找到对应的回调， 只有一个update事件，要根据update事件里值去判断是清空操作还是确认操作，这样感觉有点奇怪
### Expected API (期望的 API)
加上close和submit回调事件

**Comment by Talljack** [comment]
> 你说的是 `date-picker` 还是 `time-picker` 组件 可能会加`onClear` `onConfirm`

或许应该两个都加上吧
