### ISSUE TITLE
n-input只能绑定字符串和数组，绑定数字会报警告

### ISSUE THREAD

**Issue by Tomato-Java** [TuSimple/naive-ui#2858]
### This function solves the problem (这个功能解决的问题)
在使用input组件时，我有一个字段是年龄属性，是number类型，用v-model.value绑定时报了警告,
### Expected API (期望的 API)
希望去掉input的number警告，因为我的年龄字段确实是number类型没有问题

**Comment by Sepush** [comment]
`input `的` value `类型是 `string | [string, string] | null` 
如果你有` number `类似的值 考虑使用 `input-number` 组件代替
