### ISSUE TITLE
data-table加ellipsis参数后, 横向滚动条失效

### ISSUE THREAD

**Issue by diduweiwu** [TuSimple/naive-ui#2861]
### TuSimple/naive-ui version (版本)
2.28.2

### Vue version (Vue 版本)
3.2.25

### Browser and its version (浏览器及其版本)
Chrome(101.0.4951.41)

### System and its version (系统及其版本)
MacOS(12.3.1)

### Node version (Node 版本)
v16.13.0

### Reappearance link (重现链接)
https://codesandbox.io/s/crazy-scott-gf2m2z?file=/src/Demo.vue

### Reappearance steps (重现步骤)
1.访问页面
2.等待data table渲染完成
3.尝试拖动横向滚动条(事实上滚动条并没有展示出来)
4. 去掉column定义的 ellipsis: true  参数,横向滚动条正常展示并且可以拖动

### Expected results (期望的结果)
希望能正常拖动横向滚动条

### Actual results (实际的结果)
1.滚动条不显示出来
2.无法横向拖动列表

**Comment by 07akioni** [comment]
一但你使用了 ellipsis，table 的 layout 会变成 fixed，这会导致 table 的一些行为改变。

这种情况下你应该先写好 scrollX。

**Comment by diduweiwu** [comment]
> 一但你使用了 ellipsis，table 的 layout 会变成 fixed，这会导致 table 的一些行为改变。
> 
> table 什么时候能变成 fixed 是个比较复杂的问题，写出来多数人应该也比较难理解，所以没有在文档里专门开一段。
> 
> 这种情况下你应该先写好 scrollX。

恩恩,添加后确实可以了,看来我还需要多熟悉下文档,多谢多谢~

**Comment by WYaWX** [comment]
> 一但你使用了 ellipsis，table 的 layout 会变成 fixed，这会导致 table 的一些行为改变。
> 
> table 什么时候能变成 fixed 是个比较复杂的问题，写出来多数人应该也比较难理解，所以没有在文档里专门开一段。
> 
> 这种情况下你应该先写好 scrollX。

写好 scrollX不就成固定的吗，那我列宽拖拽后的，横向滚动条也不是动态了的啊
