### ISSUE TITLE
spin在App.vue包裹时，深色模式无效

### ISSUE THREAD

**Issue by CarmenHYC** [TuSimple/naive-ui#2862]
### TuSimple/naive-ui version (版本)
2.28.2

### Vue version (Vue 版本)
3.2.33

### Browser and its version (浏览器及其版本)
Microsoft Edge Version 100.0.1185.50 (Official build) (x86_64)

### System and its version (系统及其版本)
Mac OS（11.6.5）

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/dark/components/spin

### Reappearance steps (重现步骤)
```
<template>
    <n-config-provider :theme="darkTheme">
        <n-message-provider>
        <n-notification-provider>
        <n-dialog-provider>
            <n-spin :show="true">
                <router-view class="w-full min-h-screen" />
            </n-spin>
        </n-dialog-provider>
        </n-notification-provider>
        </n-message-provider>
    </n-config-provider>
</template>
```

### Expected results (期望的结果)
深色模式下应该是深色样式

### Actual results (实际的结果)
深色模式下还是浅色样式

**Comment by 07akioni** [comment]
https://codesandbox.io/s/blue-mountain-m0uz5h?file=/src/App.vue

未能复现

**Comment by CarmenHYC** [comment]
> https://codesandbox.io/s/blue-mountain-m0uz5h?file=/src/App.vue
> 
> 未能复现

[](https://codesandbox.io/s/old-voice-n3qi1b?file=/src/App.vue)

你的连接上复现的就是深色模式下还是浅色样式呢，我在两个文件中都加了作下对比，烦请你再看一下哦~

**Comment by 07akioni** [comment]
> https://codesandbox.io/s/old-voice-n3qi1b?file=/src/App.vue)

浅色样式只会对组件生效，如果你需要 body 也挂上应该用 n-global-style

**Comment by 07akioni** [comment]
https://www.naiveui.com/zh-CN/os-theme/components/global-style

**Comment by 07akioni** [comment]
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/18677354/165820313-556db093-0628-4c82-837e-5f1a5041d100.png">
