### ISSUE TITLE
Scrollbar is not showing while scrolling on mobile device

### ISSUE THREAD

**Issue by mitow7821** [TuSimple/naive-ui#2863]
### TuSimple/naive-ui version (版本)
2.28.2

### Vue version (Vue 版本)
3.2.33

### Browser and its version (浏览器及其版本)
100.0.4896.127

### System and its version (系统及其版本)
Android 10

### Reappearance link (重现链接)
https://codesandbox.io/s/mops5p

### Reappearance steps (重现步骤)
Try to scroll on mobile device. Scroll works but bar isn't displayed.
Scroll bar is showing only when text is clicked.

### Expected results (期望的结果)
Bar should be visible while scrolling on mobile.

### Actual results (实际的结果)
Bar isn't showing on scroll.

**Comment by 07akioni** [comment]
I'm not sure what happens on your phone. However naive's scrollbar is designed to show only in PC. In a mobile phone, it should follow native behavior.

**Comment by mitow7821** [comment]
Ok, so it's working as expected. 
Is there any chance of adding option to always show scroll visibility? That would be usefull in some mobile scenarios.

**Comment by 07akioni** [comment]
> Ok, so it's working as expected. Is there any chance of adding option to always show scroll? That would be usefull in some mobile scenarios.

I don't want to add the feature. If naive's scrollbar is shown, as far as I know there's no way to disable native scrollbar on mobile phone, so it would break on most mobiles phones.
