### ISSUE TITLE
data-table没有点击当前行的回调

### ISSUE THREAD

**Issue by wanbo0424** [TuSimple/naive-ui#2865]
### This function solves the problem (这个功能解决的问题)
data-table事件中没有点击行的回调事件，回调函数也比较少，能满足的需求相应会少
### Expected API (期望的 API)
提供类似rowClick的回调，并添加当前行相应回调参数

**Comment by Talljack** [comment]
看这个demo https://www.naiveui.com/zh-CN/os-theme/components/data-table#row-props
