### ISSUE TITLE
不支持表单多层嵌套验证

### ISSUE THREAD

**Issue by labbomb** [TuSimple/naive-ui#2866]
### TuSimple/naive-ui version (版本)
2.28.2

### Vue version (Vue 版本)
3.2.33

### Browser and its version (浏览器及其版本)
Chrome(100.0.4896.127（正式版本） (x86_64))

### System and its version (系统及其版本)
macOS(12.2.1)

### Reappearance link (重现链接)
https://stackblitz.com/edit/vue-67fyzu?file=src%2Fcomponents%2FHelloWorld.vue

### Reappearance steps (重现步骤)
参见链接

### Expected results (期望的结果)
可以支持嵌套的验证

### Actual results (实际的结果)
无法检测到验证

**Comment by 07akioni** [comment]
naive 封装之后的写法和 async validator 有点差别，可以看

https://stackblitz.com/edit/vue-jfnys2?file=src%2Fcomponents%2FHelloWorld.vue

<img width="1355" alt="image" src="https://user-images.githubusercontent.com/18677354/165819975-f7583dcf-3513-4574-a8d6-2c8e3cd0c54f.png">
