### ISSUE TITLE
data-table组件, 如果表格内容的长度是不固定的, 怎样才能保持hover显示滚动条 ?

### ISSUE THREAD

**Issue by a15218378694** [TuSimple/naive-ui#2867]
### This function solves the problem (这个功能解决的问题)
hover显示滚动条
### Expected API (期望的 API)
element的table, 不需要设置scroll-x类似属性, 就能hover显示滚动条

**Comment by 07akioni** [comment]
hover 显示滚动条好歹是需要宽度超了容器的

**Comment by 07akioni** [comment]
有更具体的场景吗？

**Comment by a15218378694** [comment]
> 

https://codesandbox.io/s/quizzical-feather-ryet75?file=/src/Demo.vue

**Comment by 07akioni** [comment]
> https://codesandbox.io/s/quizzical-feather-ryet75?file=/src/Demo.vue

因为这个例子用了 fixed，如果有 fixed，那么 scroll-x 是必须有的

**Comment by dellenshang** [comment]
我这边的做法是在设置columns的时候（使用computed），将title的文字长度算出，逐个累加，再加上你认为合适的基础宽度值，然后把值给scroll-x ，就可以支持columns的动态不固定的也可以很好的显示滚动条了
