### ISSUE TITLE
input autofill background color

### ISSUE THREAD

**Issue by AinneShen** [TuSimple/naive-ui#2869]
### TuSimple/naive-ui version (版本)
2.28.2

### Vue version (Vue 版本)
3.2.33

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
Linux

### Reappearance link (重现链接)
https://codesandbox.io/s/quiet-shape-w1yybt?file=/src/App.vue

### Reappearance steps (重现步骤)
1. input user and passward,then submit.
2. Refresh page.
3. Auto fill user and password.

### Expected results (期望的结果)
Input has the correct background color.

### Actual results (实际的结果)
The input background color is white
![image](https://user-images.githubusercontent.com/23020951/165876610-15ca8fd9-6c60-461e-bc1d-4454bfae5e87.png)

**Comment by 07akioni** [comment]
No way to override it.

You can set `input-props="{ autocomplete: false }"` to disable it.

**Comment by thibodeauxjl** [comment]
```
input:-webkit-autofill,
input:-webkit-autofill:hover, 
input:-webkit-autofill:focus,
textarea:-webkit-autofill,
textarea:-webkit-autofill:hover,
textarea:-webkit-autofill:focus,
select:-webkit-autofill,
select:-webkit-autofill:hover,
select:-webkit-autofill:focus {
    -webkit-box-shadow: 0 0 0 1000px #303033 inset !important;
    -webkit-text-fill-color: rgba(255,255,255,.82) !important;
}
```

You can use an inset box shadow to override Chrome default autofill background. You can also set a text fill color.
