### ISSUE TITLE
在 `vuedraggable@next` 中 `NButton` 无法使用

### ISSUE THREAD

**Issue by Air-Cooled** [TuSimple/naive-ui#2882]
### TuSimple/naive-ui version (版本)
2.28.2

### Vue version (Vue 版本)
3.2.25

### Browser and its version (浏览器及其版本)
Chrome( 100.0.4896.127)

### System and its version (系统及其版本)
win 10

### Node version (Node 版本)
v16.13.2

### Reappearance link (重现链接)
https://github.com/SortableJS/vue.draggable.next

### Reappearance steps (重现步骤)
``` vue
<draggable v-model="list"  item-key="id">
  <template #item="{element}">
      <n-button> {{element.name}} </n-button>
  </template>
</draggable>
```

### Expected results (期望的结果)
点击 button 可以进行拖拽

### Actual results (实际的结果)
点击 button 无法拖拽，
换为 div 即可拖拽，但在 div 内 button 上点击依旧无法进行拖拽

**Comment by 07akioni** [comment]
这个问题你可以给 vuedraggable 提 issue

**Comment by Air-Cooled** [comment]
> 这个问题你可以给 vuedraggable 提 issue

`element-plus` 的 `button` 是可以正常使用的，确定不是 `naive-ui` 的问题？

**Comment by 07akioni** [comment]
> https://github.com/TuSimple/naive-ui/blob/main/src/button/src/Button.tsx#L157

我也记不太清了

> `mousedown`阻止默认事件导致`dragstart`不会触发。
> 
> @07akioni 为啥这块需要`preventDefault()`，https://github.com/TuSimple/naive-ui/blob/main/src/button/src/Button.tsx#L157。
> 
> 如果真的必须的话，可以放在https://github.com/TuSimple/naive-ui/blob/main/src/button/src/Button.tsx#L161里面。

因为不 preventDefault 的话 button 点击后无法在 safari 被聚焦

**Comment by 07akioni** [comment]
加了一个属性可以关掉这个行为
