### ISSUE TITLE
Allow icon-placement top on Button

### ISSUE THREAD

**Issue by wc-davide** [TuSimple/naive-ui#2884]
### This function solves the problem (这个功能解决的问题)
I have a table with buttons on the final column which is aligned centered, it would be nice if the icon could be above the button text to look more "centered".

Example on what I'm trying to achieve: https://i.imgur.com/9LjMe9K.png (in this example the button would be "text")
### Expected API (期望的 API)
Currently icon-placement allows only "left" and "right", adding "top" (maybe "bottom" too) options

**Comment by wc-davide** [comment]
Currently I'm achieving that result with:

```html
<n-button
	text
	tag="a"
	:href="event._previewLink"
	target="_blank"
	class="flex flex-col"
	:themeOverrides="{iconMarginMedium: 0}"
>
	anteprima
	<template #icon>
		<n-icon>
			<i-carbon-view />
		</n-icon>
	</template>
</n-button>
```

**Comment by 07akioni** [comment]
I don't think is a common pattern, since I haven't seen it in any popular product.

There's little possibility that we will implement it.
