### ISSUE TITLE
`Menu` 压缩后，弹出子菜单过长时内部无滚动

### ISSUE THREAD

**Issue by Air-Cooled** [TuSimple/naive-ui#2885]
### TuSimple/naive-ui version (版本)
2.28.2

### Vue version (Vue 版本)
3.2.33

### Browser and its version (浏览器及其版本)
Chrome(101.0.4951.54)

### System and its version (系统及其版本)
win 10

### Node version (Node 版本)
v16.13.2

### Reappearance steps (重现步骤)
![动画15](https://user-images.githubusercontent.com/55440364/166723679-6b2ed3a7-4bfa-427e-9d55-8af43ad26e86.gif)

### Expected results (期望的结果)
弹出框高度不要超出可视区

**Comment by 07akioni** [comment]
未来会想办法优化一下，不过建议不要放这么多 item 进去

**Comment by u10k** [comment]
> 在下个版本可以使用dropdown-props来开启滚动和设置滚动高度 `:dropdown-props="{ scrollable: true, menuProps: () => ({ style: 'max-height: 100px;' }) }"`

应该是
`:menu-props="() => ({ style: { maxHeight: '200px', overflow: 'auto' }})"`

如果能用嵌套组件n-scrollbar 实现就更好了

**Comment by amadeus711** [comment]
> > 在下个版本可以使用dropdown-props来开启滚动和设置滚动高度 `:dropdown-props="{ scrollable: true, menuProps: () => ({ style: 'max-height: 100px;' }) }"`
> 
> 应该是 `:menu-props="() => ({ style: { maxHeight: '200px', overflow: 'auto' }})"`
> 
> 如果能用嵌套组件n-scrollbar 实现就更好了

用 scrollable 那个是推荐的解决方式
