### ISSUE TITLE
select组件render-option导致的高度bug

### ISSUE THREAD

**Issue by yiptsangkin** [TuSimple/naive-ui#2886]
### TuSimple/naive-ui version (版本)
2.28.2

### Vue version (Vue 版本)
3.2.33

### Browser and its version (浏览器及其版本)
89

### System and its version (系统及其版本)
OSX 12.3.1

### Reappearance link (重现链接)
CodeSandbox

### Reappearance steps (重现步骤)
 当render-option中option的高度小于34px（-n-select-option默认的高度），在第一次展开下拉列表的时候底部会有空白，就是计算的高度有问题，这个要怎么解决？
<img width="633" alt="image" src="https://user-images.githubusercontent.com/11978548/166858532-01a14adc-69b6-4c9c-8ea9-541393061feb.png">
### Expected results (期望的结果)
没有空白

### Actual results (实际的结果)
有空白

**Comment by 07akioni** [comment]
在这种情况下你需要用 theme-overrides 把 select option 的高度变小，变成你预期的大小

或者可以关掉虚拟滚动

**Comment by yiptsangkin** [comment]
> 在这种情况下你需要用 theme-overrides 把 select option 的高度变小，变成你预期的大小
> 
> 或者可以关掉虚拟滚动

改theme-overrides全部组件都会改，我试试关掉虚拟滚动吧，thx！

**Comment by 07akioni** [comment]
> > 在这种情况下你需要用 theme-overrides 把 select option 的高度变小，变成你预期的大小
> > 或者可以关掉虚拟滚动
> 
> 改theme-overrides全部组件都会改，我试试关掉虚拟滚动吧，thx！

theme-overrides 可以只改动某个组件
