### ISSUE TITLE
能否新增图片对比组件，超实用

### ISSUE THREAD

**Issue by Baiyuetribe** [TuSimple/naive-ui#2890]
### This function solves the problem (这个功能解决的问题)
对比两张图片，方便观察效果。适用于任意需要对比两张图片的场景，比如照片上色、特效处理、风格化对比等等。
### Expected API (期望的 API)
参考示例：https://image-compare-viewer.netlify.app/
![image](https://user-images.githubusercontent.com/43716063/166936103-7cf7dd77-07d4-45a2-9d6c-d548796ff79a.png)

**Comment by 07akioni** [comment]
感觉这种组件并不是很常用，属于一个比较特殊的功能了，没有打算做进来，搞个第三方的就好了
