### ISSUE TITLE
Rate component, add `readonly` prop

### ISSUE THREAD

**Issue by jdwit** [TuSimple/naive-ui#2892]
### This function solves the problem (这个功能解决的问题)
Currently the Rate component is always interactive/editable. There is no `disabled` or `readonly` prop. This can currently be "simulated" by adding `pointer-events: none;` css to the component DOM container. However this is not ideal. It would make sense that component has a prop that controls this behaviour (see https://arco.design/vue/component/rate and https://ant.design/components/rate/)
### Expected API (期望的 API)
a `readonly` or `disabled` prop.

**Comment by 07akioni** [comment]
<img width="866" alt="image" src="https://user-images.githubusercontent.com/18677354/167199510-fa607f9b-01a8-4cb2-a70b-17c41befb5f3.png">


<img width="1060" alt="image" src="https://user-images.githubusercontent.com/18677354/167199484-de2d32b0-9de7-4a1a-bb63-205e3be176a7.png">

???
