### ISSUE TITLE
n-input 能否限制输入的时候只能输入数字

### ISSUE THREAD

**Issue by 9yues** [TuSimple/naive-ui#2896]
### This function solves the problem (这个功能解决的问题)
n-input 能否限制输入的时候只能输入数字
### Expected API (期望的 API)
n-input 能否限制输入的时候只能输入数字

**Comment by ouuan** [comment]
为什么不用 `n-input-number` 呢

**Comment by 9yues** [comment]
> 为什么不用 `n-input-number` 呢

n-input-number也可以输入英文的

**Comment by ouuan** [comment]
> n-input-number也可以输入英文的

你是说连不合法都不可以，必须不能输入吗，为什么呢

**Comment by 07akioni** [comment]
你可以先这么弄一下

```html
<template>
  <n-space vertical>
    <n-input
      :value="value"
      type="text"
      placeholder="基本的 Input"
      @update-value="handleUpdateValue"
    />
  </n-space>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue'

export default defineComponent({
  setup () {
    const valueRef = ref('')
    return {
      value: valueRef,
      handleUpdateValue (v: string) {
        if (/^\d+$/.test(v)) {
          valueRef.value = v
        }
      }
    }
  }
})
</script>
```

**Comment by 9yues** [comment]
> > n-input-number也可以输入英文的
> 
> 你是说连不合法都不可以，必须不能输入吗，为什么呢

没办法呀，需求是这样

**Comment by 9yues** [comment]
> 你可以先这么弄一下
> 
> ```
> <template>
>   <n-space vertical>
>     <n-input
>       :value="value"
>       type="text"
>       placeholder="基本的 Input"
>       @update-value="handleUpdateValue"
>     />
>   </n-space>
> </template>
> 
> <script lang="ts">
> import { defineComponent, ref } from 'vue'
> 
> export default defineComponent({
>   setup () {
>     const valueRef = ref('')
>     return {
>       value: valueRef,
>       handleUpdateValue (v: string) {
>         if (/^\d+$/.test(v)) {
>           valueRef.value = v
>         }
>       }
>     }
>   }
> })
> </script>
> ```

好的，谢谢，我先试试

**Comment by tuutoo** [comment]
我也感觉最好是直接就禁止其他字符输入, 只显示输入不合法的意义不大. 
到时候用户直接给你点个保存, 值就存到数据库了.  还得自己另外写逻辑防这一手.

**Comment by ouuan** [comment]
> 到时候用户直接给你点个保存, 值就存到数据库了. 还得自己另外写逻辑防这一手.

绑定的值在输入不合法的时候不会变吧

**Comment by tuutoo** [comment]
> > 到时候用户直接给你点个保存, 值就存到数据库了. 还得自己另外写逻辑防这一手.
> 
> 绑定的值在输入不合法的时候不会变吧

试了下果然是这样, 高级!
