### ISSUE TITLE
Transfer 穿梭框可否增加自定义渲染

### ISSUE THREAD

**Issue by Aicmortal** [TuSimple/naive-ui#2897]
### This function solves the problem (这个功能解决的问题)
Transfer 穿梭框的内容显示感觉不够灵活,希望可以增加自定义渲染的API
### Expected API (期望的 API)
renderSourceItem自定义左侧每一条源数据的渲染结构
renderTargetItem 自定义右侧每一条已选项的渲染结构

**Comment by 07akioni** [comment]
Whis will be done.

Transfer has a large refractor to release later.

**Comment by Aicmortal** [comment]
谢谢您的解答,期待下一个版本

**Comment by Aicmortal** [comment]
谢谢您的解答,期待下一个版本
