### ISSUE TITLE
data-table组件, 超出隐藏的临界情况, 有问题, 没有tooltip效果

### ISSUE THREAD

**Issue by a15218378694** [TuSimple/naive-ui#2899]
### TuSimple/naive-ui version (版本)
2.28.2

### Vue version (Vue 版本)
3.2.33

### Browser and its version (浏览器及其版本)
Chrome100

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://codesandbox.io/s/quizzical-feather-ryet75?file=/src/Demo.vue

### Reappearance steps (重现步骤)
打开看第一列的hover效果, name隐藏了部分, 但是没有tooltip

### Expected results (期望的结果)
显示tooltip

### Actual results (实际的结果)
没显示tooltip

**Comment by a15218378694** [comment]
是正在更改, 所以关闭了这个issue吗

**Comment by 07akioni** [comment]
> 是正在更改, 所以关闭了这个issue吗

没能在你给的 codesandbox 复现，不过 ellipsis 是有这个问题，已经修了

**Comment by a15218378694** [comment]
升级版本就能解决了是吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月9日(周一) 中午12:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TuSimple/naive-ui] data-table组件, 超出隐藏的临界情况, 有问题, 没有tooltip效果 (Issue #2899)




  
是正在更改, 所以关闭了这个issue吗
  
没能在你给的 codesandbox 复现，不过 ellipsis 是有这个问题，已经修了

**Comment by 07akioni** [comment]
> 升级版本就能解决了是吧
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年5月9日(周一) 中午12:57 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [TuSimple/naive-ui] data-table组件, 超出隐藏的临界情况, 有问题, 没有tooltip效果 (Issue #2899) 是正在更改, 所以关闭了这个issue吗 没能在你给的 codesandbox 复现，不过 ellipsis 是有这个问题，已经修了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

下个版本应该可以
