### ISSUE TITLE
Select component scroll event cannot get `currentTarget` property

### ISSUE THREAD

**Issue by Lonely-shang** [TuSimple/naive-ui#2902]
### TuSimple/naive-ui version (版本)
2.28.2

### Vue version (Vue 版本)
3.2.33

### Browser and its version (浏览器及其版本)
Chrome(101.0.4951.41)

### System and its version (系统及其版本)
MacOS(12.1)

### Node version (Node 版本)
17.2.0

### Reappearance link (重现链接)
https://github.com/Lonely-shang/test-naive-ui

### Reappearance steps (重现步骤)
Install dependencies and run them directly， I quoted the case from the official website

### Expected results (期望的结果)
I want to be able to get the `currentTarget` property through the `@scroll` event

### Actual results (实际的结果)
`currentTarget` property is null

**Comment by 07akioni** [comment]
I'm not sure what happened, but I can't reproduce it.

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/18677354/167311236-e1f616fe-4c4e-4c68-b228-45adc94b23a5.png">

**Comment by 07akioni** [comment]
![Uploading image.png…]()

**Comment by 07akioni** [comment]
![Uploading image.png…]()

**Comment by Lonely-shang** [comment]
> 直接打 event 再展开看起来确实会没有 currentTarget

OK Thanks but the case on the official website does not always load the list as expected

**Comment by 07akioni** [comment]
> > 直接打 event 再展开看起来确实会没有 currentTarget
> 
> OK Thanks but the case on the official website does not always load the list as expected

Need a reproduction.
