### ISSUE TITLE
Tree: Regex filtering

### ISSUE THREAD

**Issue by ManasMadrecha** [TuSimple/naive-ui#2904]
### This function solves the problem (这个功能解决的问题)

To be able to filter the tree using regex instead of simple pattern.

### Expected API (期望的 API)
---

**Comment by ManasMadrecha** [comment]
Needed for https://github.com/guopenghui/obsidian-quiet-outline/issues/22

**Comment by 07akioni** [comment]
You should use filter prop.

**Comment by ManasMadrecha** [comment]
@07akioni That's what I suggested there. Thanks for the confirmation. 😊
