### ISSUE TITLE
Data Table的自定义样式不生效

### ISSUE THREAD

**Issue by ZHB12123** [TuSimple/naive-ui#2921]
### TuSimple/naive-ui version (版本)
2.28.4

### Vue version (Vue 版本)
3.2.33

### Browser and its version (浏览器及其版本)
101.0.4951.64

### System and its version (系统及其版本)
Windows10

### Reappearance link (重现链接)
https://codesandbox.io/s/u4y20n

### Reappearance steps (重现步骤)
Data Table组件的自定义样式功能不生效，可以参考：https://codesandbox.io/s/u4y20n。

### Expected results (期望的结果)
如文档（https://www.naiveui.com/zh-CN/dark/components/data-table）中所说自定义样式可以生效。

### Actual results (实际的结果)
Data Table的自定义样式不生效。

**Comment by 07akioni** [comment]
scoped

![Uploading image.png…]()

**Comment by ZHB12123** [comment]
请问是不是和chrome版本有关系？
![image](https://user-images.githubusercontent.com/26193691/168092623-a22e6c5f-d39b-4017-8488-0cdb8d373e4e.png)
![image](https://user-images.githubusercontent.com/26193691/168092800-4e4deaec-44ce-40ff-92d6-7fbbbb7e90e3.png)
