### ISSUE TITLE
希望 Data Table 能增加点击某行后高亮的选项

### ISSUE THREAD

**Issue by qingruikz** [TuSimple/naive-ui#2925]
### This function solves the problem (这个功能解决的问题)
希望 Data Table 能增加点击某行后高亮的选项（以及对应的主题编辑器中的颜色变量），类似 Tree 的点击效果。能像 Tree 一样增加多选，受控点击选择等选项就更好了（类似 Element  的 Table）。现在的 Data Table 已经很好用了，就是只能通过勾选框来进行单选/多选等操作，有时候考虑效果不太想用勾选框。

### Expected API (期望的 API)
highlight-current-row: boolean
multiple: boolean
selected-keys: Array<string | number>

**Comment by yanbowe** [comment]
> ### This function solves the problem (这个功能解决的问题)
> 希望 Data Table 能增加点击某行后高亮的选项（以及对应的主题编辑器中的颜色变量），类似 Tree 的点击效果。能像 Tree 一样增加多选，受控点击选择等选项就更好了（类似 Element 的 Table）。现在的 Data Table 已经很好用了，就是只能通过勾选框来进行单选/多选等操作，有时候考虑效果不太想用勾选框。
> 
> ### Expected API (期望的 API)
> highlight-current-row: boolean multiple: boolean selected-keys: Array<string | number>

可以参考这个[#1542](https://github.com/TuSimple/naive-ui/issues/1542)

**Comment by qingruikz** [comment]
> > ### This function solves the problem (这个功能解决的问题)
> > 希望 Data Table 能增加点击某行后高亮的选项（以及对应的主题编辑器中的颜色变量），类似 Tree 的点击效果。能像 Tree 一样增加多选，受控点击选择等选项就更好了（类似 Element 的 Table）。现在的 Data Table 已经很好用了，就是只能通过勾选框来进行单选/多选等操作，有时候考虑效果不太想用勾选框。
> > ### Expected API (期望的 API)
> > highlight-current-row: boolean multiple: boolean selected-keys: Array<string | number>
> 
> 可以参考这个[#1542](https://github.com/TuSimple/naive-ui/issues/1542)

谢谢！
