### ISSUE TITLE
建议分页 Pagination 的“跳至”功能增加失去焦点后即可跳转该页

### ISSUE THREAD

**Issue by colin5213** [TuSimple/naive-ui#2928]
### This function solves the problem (这个功能解决的问题)
1.增加失去焦点后即可跳转该页，这样就不必输入后Enter才跳转；
2.限制输入除数字外的其他字符；
3.输入大于最大数时应跳至最大一页，现在是不跳 没有什么反应；
4.输入小于最小页数时应跳至最小一页，现在是不跳 没有什么反应；

### Expected API (期望的 API)
无

**Comment by Sepush** [comment]
1.我觉得不应该失去焦点就跳转 这个跳转应该由用户来确认
2 3 4 可以考虑

**Comment by 07akioni** [comment]
blur 对于用户来说可能会出现误操作的情况，剩下的确实可以考虑
