### ISSUE TITLE
if child menu is selected, parent hover text color is wrong

### ISSUE THREAD

**Issue by wc-matteo** [TuSimple/naive-ui#2929]
### TuSimple/naive-ui version (版本)
2.28.4

### Vue version (Vue 版本)
3.2.33

### Browser and its version (浏览器及其版本)
Version 101.0.4951.67

### System and its version (系统及其版本)
win 10

### Reappearance link (重现链接)
https://codesandbox.io/s/recursing-cray-yqxlyp?file=/src/Demo.vue

### Reappearance steps (重现步骤)
1 select `narrator` menu item (under `dance dance dance`)
2 try to hover over `dance dance dance` menu item

### Expected results (期望的结果)
the text color has the same color as other menu items when hovering

### Actual results (实际的结果)
the text color has the wrong color (it's the `active` color)

![image](https://user-images.githubusercontent.com/10562635/168237794-874c3662-737f-4fdb-8ee1-4c61c4a25a74.png)

**Comment by 07akioni** [comment]
I can't say this is a bug since color of child active is not provided. So hover color will always take control.

We may add some variables to support it.
