### ISSUE TITLE
Add the '`top-center`' and '`bottom-center`' placement to the Notification component

### ISSUE THREAD

**Issue by DannyFeliz** [TuSimple/naive-ui#2930]
### This function solves the problem (这个功能解决的问题)
It will allow notifications to be placed at the top and bottom centers.
### Expected API (期望的 API)
I need to show a notification at the top center of the screen but currently, the possible values for the prop placement are `'top-right'` | `'top-left'` | `'bottom-left'` | `'bottom-right'` (see [here](https://www.naiveui.com/en-US/os-theme/components/notification#placement.vue)) so I propose to add 'top-center' and 'bottom-center'.

The ant.design team includes these placements as `'top'` and `'bottom'` in their notification component.
https://ant.design/components/notification/#components-notification-demo-placement

**Comment by Sepush** [comment]
`message` component may feat your demand
