### ISSUE TITLE
对于chrome101版本Data Table的自定义样式不生效

### ISSUE THREAD

**Issue by ZHB12123** [TuSimple/naive-ui#2936]
### TuSimple/naive-ui version (版本)
2.28.4

### Vue version (Vue 版本)
3.2.33

### Browser and its version (浏览器及其版本)
101.0.4951.64

### System and its version (系统及其版本)
Windows10

### Reappearance link (重现链接)
https://codesandbox.io/s/u4y20n

### Reappearance steps (重现步骤)
请使用101.0.4951.64版本的chrome浏览器打开链接https://codesandbox.io/s/u4y20n。

### Expected results (期望的结果)
如文档（https://www.naiveui.com/zh-CN/dark/components/data-table）中所说自定义样式可以生效。

### Actual results (实际的结果)
Data Table的自定义样式不生效。参考截图：https://user-images.githubusercontent.com/26193691/168092623-a22e6c5f-d39b-4017-8488-0cdb8d373e4e.png
chrome浏览器版本截图：https://user-images.githubusercontent.com/26193691/168092800-4e4deaec-44ce-40ff-92d6-7fbbbb7e90e3.png

**Comment by 07akioni** [comment]
样式没加 scoped

同一个问题 https://github.com/TuSimple/naive-ui/issues/2921

仔细看图

**Comment by ZHB12123** [comment]
谢谢解答，如果可以的话请帮忙修正一下文档，谢谢。
![image](https://user-images.githubusercontent.com/26193691/168465993-332eb52d-9716-4e63-a878-94a28fa8720b.png)
