### ISSUE TITLE
n-data-table: pagination prop pageCount not valid(数据表格中使用pagination的prop[page-count]没有效果) 

### ISSUE THREAD

**Issue by RAGGA-TIME** [TuSimple/naive-ui#2941]
### TuSimple/naive-ui version (版本)
2.28.4

### Vue version (Vue 版本)
3.2.26

### Browser and its version (浏览器及其版本)
Chrome(100 )

### System and its version (系统及其版本)
undefined

### Reappearance link (重现链接)
https://codesandbox.io/s/6omdc0?file=/src/Demo.vue

### Reappearance steps (重现步骤)
设置n-data-table的prop pagination为{ page: 1, pageCount:2 }无效 总页数始终显示1

### Expected results (期望的结果)
设置n-data-table的prop pagination为{ page: 1, pageCount:2 }时,  总页数为2 可翻页

### Actual results (实际的结果)
设置n-data-table的prop pagination为{ page: 1, pageCount:2 }无效 总页数始终显示1

**Comment by 07akioni** [comment]
需要生效的话得写 remote 属性。在使用本地数据的时候，会使用数据总量来计算页数。

**Comment by RAGGA-TIME** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by YangJ0605** [comment]
> 需要生效的话得写 remote 属性。在使用本地数据的时候，会使用数据总量来计算页数。

有个问题，NDataTable中加上remote属性后，列的filter就无法生效，是我用法不对还是不支持这样使用，文档中也看到了有关表格异步的用法，但是我想要的是每列filter函数在添加remote属性后还是能够生效

**Comment by 07akioni** [comment]
> > 需要生效的话得写 remote 属性。在使用本地数据的时候，会使用数据总量来计算页数。
> 
> 有个问题，NDataTable中加上remote属性后，列的filter就无法生效，是我用法不对还是不支持这样使用，文档中也看到了有关表格异步的用法，但是我想要的是每列filter函数在添加remote属性后还是能够生效

可以看我给你在另一个 issue 评论的回复

**Comment by lilonghe** [comment]
翻了半小时检索，实现最小化复现 demo 时发现 pageCount 无效，然后终于检索到正确答案了 😂  
略微好奇，table 的使用场景中大部分都是本地分页而不是远程分页吗？  
如果传递了无效属性，是否可以有 warn 提示呢

**Comment by RAGGA-TIME** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 07akioni** [comment]
> 翻了好久检索没找到相关BUG，实现最小化复现 demo 时发现 pageCount 无效，然后终于检索到正确答案了 😂 略微好奇，table 的使用场景中大部分都是本地分页而不是远程分页吗？ 如果传递了无效属性，是否可以有 warn 提示呢

我觉得在文档加一下吧，这块的考虑是如果数据和分页不匹配会有更大的问题
