### ISSUE TITLE
tree组件，如何实现点击节点名称后，展开或收缩，也就是，点击节点名称的效果，要和点击箭头的效果一致

### ISSUE THREAD

**Issue by iZaiZaiA** [TuSimple/naive-ui#2949]
### This function solves the problem (这个功能解决的问题)
tree组件，如何实现点击节点名称后，展开或收缩，也就是，点击节点名称的效果，要和点击箭头的效果一致，我看了文档和示例，好像没有这个需求的支持，只能点节点名称前面的箭头实现。但我现在的项目上，需要实现点击节点名称展开或收缩效果。。。

### Expected API (期望的 API)
https://element-plus.org/zh-CN/component/tree.html

饿了么UI的tree，就蛮好的，但我不太想一个项目里，使用太多的UI框架，只想使用naiveUI进行开发，所以，希望能提供下实现的方案，谢谢

**Comment by iZaiZaiA** [comment]
还有手风琴效果，貌似也没有，但我们的项目中，需要手风琴效果。。也就是，点击同级的节点，只能展开一个节点，其它节点收缩起来。

**Comment by 07akioni** [comment]
> 还有手风琴效果，貌似也没有，但我们的项目中，需要手风琴效果。。也就是，点击同级的节点，只能展开一个节点，其它节点收缩起来。

用 @select 处理一下 expanded-keys

**Comment by 07akioni** [comment]
手风琴可以考虑一下，但是优先级比较低

**Comment by 07akioni** [comment]
点击展开是为了解决啥问题？纯展示么？

**Comment by iZaiZaiA** [comment]
> 点击展开是为了解决啥问题？纯展示么？

是的，纯展示，主要是，因为我们做的项目，是面向工程建设的，所以，tree只能点箭头展开或收缩的话，操作人员可能会搞不明白，没有直接点节点名称展开或收缩子级来的简单明了，公司不太想增加太多使用培训的成本和培训太多东西，还有就是（产品经理，要那样搞，我只是个前端，很无奈，包括tree的手风琴。。。）

**Comment by 07akioni** [comment]
> > 点击展开是为了解决啥问题？纯展示么？
> 
> 是的，纯展示，主要是，因为我们做的项目，是面向工程建设的，所以，tree只能点箭头展开或收缩的话，操作人员可能会搞不明白，没有直接点节点名称展开或收缩子级来的简单明了，公司不太想增加太多使用培训的成本和培训太多东西，还有就是（产品经理，要那样搞，我只是个前端，很无奈，包括tree的手风琴。。。）

问题在于如果点击是展开或者收起，那正常点是干啥呢？

**Comment by iZaiZaiA** [comment]
> > > 点击展开是为了解决啥问题？纯展示么？
> > 
> > 
> > 是的，纯展示，主要是，因为我们做的项目，是面向工程建设的，所以，tree只能点箭头展开或收缩的话，操作人员可能会搞不明白，没有直接点节点名称展开或收缩子级来的简单明了，公司不太想增加太多使用培训的成本和培训太多东西，还有就是（产品经理，要那样搞，我只是个前端，很无奈，包括tree的手风琴。。。）
> 
> 问题在于如果点击是展开或者收起，那正常点是干啥呢？

正常点，也是选中，相当于，点击节点名称时，展开收缩，也同时选中，如果没有子节点了，就是只选中节点，然后，根据事件提供的节点数据，去获取相应的其它数据。

**Comment by 07akioni** [comment]
> 参数，是否启用，来单独处理这套逻辑，比如，是否在展开收缩时选中节点、是否点击节点时展开收缩等。这样，就可以自行按照

这个诉求会考虑

**Comment by mrzjl1024** [comment]
我想要一个功能，就是 通过调用tree的内置方法，展开相应的节点 并且关联的父节点 也要一并展开。

**Comment by 07akioni** [comment]
> 我想要一个功能，就是 通过调用tree的内置方法，展开相应的节点 并且关联的父节点 也要一并展开。

有需求的话提一个新的 issue，方便追踪
