### ISSUE TITLE
既然有回到顶部了，那么是否可以弄一个回到底部的组件

### ISSUE THREAD

**Issue by lvzhenbo** [TuSimple/naive-ui#2954]
### This function solves the problem (这个功能解决的问题)
我正在用naive做一个聊天应用，聊天内容是自上而下排列，所以需要一个回到底部的组件
### Expected API (期望的 API)
和回到顶部差不多

**Comment by 07akioni** [comment]
啊这，感觉在网页中不是很常用，自制一个应该难度不大
