### ISSUE TITLE
upload组件获取服务端响应内容

### ISSUE THREAD

**Issue by BeADre** [TuSimple/naive-ui#2955]
### This function solves the problem (这个功能解决的问题)
能够在上传完成后获取服务端的响应内容
### Expected API (期望的 API)
在事件参数列表中添加response

**Comment by 07akioni** [comment]
onFinish(event)

event.response

**Comment by BeADre** [comment]
感谢 我没获取到是因为 mock 重写了 XMLHttpRequest 对象  😓😓

**Comment by pylist** [comment]
> response

event.response好像已经拿不到响应内容了
