### ISSUE TITLE
NPopselect scrollable is not working

### ISSUE THREAD

**Issue by lisonge** [TuSimple/naive-ui#2956]
### TuSimple/naive-ui version (版本)
2.28.4

### Vue version (Vue 版本)
3.2.33

### Browser and its version (浏览器及其版本)
Chrome/101.0.4951.64

### System and its version (系统及其版本)
win11x64

### Reappearance link (重现链接)
https://codesandbox.io/s/bf4n72?file=/src/Demo.vue:93-108

### Reappearance steps (重现步骤)
https://codesandbox.io/s/bf4n72?file=/src/Demo.vue:93-108

### Expected results (期望的结果)
scrollable

### Actual results (实际的结果)
not scrollable

**Comment by lisonge** [comment]
v2.27.0 is working

**Comment by 07akioni** [comment]
This is fixed & will be released in next version
