### ISSUE TITLE
表格的render函数支持jsx语法吗？

### ISSUE THREAD

**Issue by zefangChen** [TuSimple/naive-ui#2963]
### This function solves the problem (这个功能解决的问题)
我用的v2.28.0，表格的render函数只能用h函数，好low啊,，希望快点支持吧，不然写业务的时候，用h函数，要累死人的
### Expected API (期望的 API)
render

**Comment by 07akioni** [comment]
任何支持 h 的地方都支持 JSX。

JSX 需要用户自己配置，库本身是不感知用户源码的。
