### ISSUE TITLE
Steps: Click to switch between steps 点击切换步骤

### ISSUE THREAD

**Issue by symbioticstar** [TuSimple/naive-ui#2967]
### This function solves the problem (这个功能解决的问题)
Sometimes we need to view the information and operation of previous steps.
At present, click switching is not supported.

There's a few implementations from other frameworks:
- Vuetify 'non linear stepper': https://vuetifyjs.com/en/components/steppers/#non-linear
- Antdv 'clickable steps': https://antdv.com/components/steps

### Expected API (期望的 API)
Add v-model support for current
Add ```disabled``` prop to NStep. Step is not clickable if ```disabled``` is set.

```html
  <n-steps v-model:current="(current as number)">
    <n-step disabled></n-step>
  </n-steps>
```

**Comment by 07akioni** [comment]
closed in https://github.com/TuSimple/naive-ui/pull/3014
