### ISSUE TITLE
Tree组件点击node时选中node并勾选

### ISSUE THREAD

**Issue by thqymy** [TuSimple/naive-ui#2968]
### This function solves the problem (这个功能解决的问题)
设置checked-keys后，改变checked-keys但没有触发@update:checked-keys
### Expected API (期望的 API)
https://element-plus.org/zh-CN/component/tree.html#%E5%B1%9E%E6%80%A7中的check-on-click-node API

**Comment by 07akioni** [comment]
closed in https://github.com/TuSimple/naive-ui/issues/2968
