### ISSUE TITLE
Escape key handlers should stop event propagation

### ISSUE THREAD

**Issue by ademenev** [TuSimple/naive-ui#2973]
### TuSimple/naive-ui version (版本)
2.29.0

### Vue version (Vue 版本)
3.2.34

### Browser and its version (浏览器及其版本)
Chrome/101.0.4951.64

### System and its version (系统及其版本)
MacOS (10.15.7)

### Reappearance link (重现链接)
https://codesandbox.io/s/admiring-lumiere-m7cq89

### Reappearance steps (重现步骤)
Open the modal, then click any of the inputs, so the input popup is open, then press Escape key

### Expected results (期望的结果)
The popup open by the input is closed, modal stays open

### Actual results (实际的结果)
Modal closes

**Comment by 07akioni** [comment]
I think we should handle the problem. However solution maybe complex.

We need to save esc event in a weak set, then check it in modal event handler.
