### ISSUE TITLE
about lodash dependencies

### ISSUE THREAD

**Issue by flyingTodream** [TuSimple/naive-ui#2981]
### This function solves the problem (这个功能解决的问题)
项目里面的依赖为什么既用了lodash又用了lodash-es，这样打包的时候会导致既有lodash的包又有lodash-es的包，
增加了不必要的打包体积，能否优化一下只使用一个lodash？
### Expected API (期望的 API)
only lodash or lodash-es

**Comment by 07akioni** [comment]
不会导致打包的时候又有 lodash 又有 lodash-es

一个是给 cjs 环境用的，一个是给 esm 环境用的
