### ISSUE TITLE
Other languages appear even after the framework has set the language

### ISSUE THREAD

**Issue by liguangyuan1997** [TuSimple/naive-ui#2984]
### This function solves the problem (这个功能解决的问题)
When we set the language to Japanese, the OK button in the time picker uses "OK" instead of the corresponding Japanese text
当我们将语言设置为日语之后,时间选择器中的确定按钮使用的是"OK"而不是对应的日语文本
confirm: 'OK',----no!no!no!
confirm: '確定'-----yes!yes!yes!
### Expected API (期望的 API)
Now that the language has been set, translate all the languages into one
既然已经设置了语言那就将所有的语言全部翻译成为一种

**Comment by 07akioni** [comment]
我不太懂那些语言，如果懂的话欢迎修正的 PR
