### ISSUE TITLE
When NSelect is multiselect and filterable, the filter keywords will not be cleared after selecting one option

### ISSUE THREAD

**Issue by cnguu** [TuSimple/naive-ui#299]
### This function solves the problem (这个功能解决的问题)
After filtering, multiple options can be selected in succession
### Expected API (期望的 API)
<n-select
    v-model:value="selectedValues"
    :multiple="true"
    :filterable="true"
    :options="options"
/>

**Comment by 07akioni** [comment]
We will provide an prop to controll the behavior.

Some people want to clear the input after selection & some doesn't want the behavior.

**Comment by Fnzero** [comment]
> ### This function solves the problem (这个功能解决的问题)
> After filtering, multiple options can be selected in succession
> 
> ### Expected API (期望的 API)

We have cleared the keywords after select an option now. Can you provide a test link?
