### ISSUE TITLE
NModal 在開啟時，不會觸發 @update:show

### ISSUE THREAD

**Issue by Ken-QQ** [TuSimple/naive-ui#2990]
### TuSimple/naive-ui version (版本)
2.29.0

### Vue version (Vue 版本)
3.2.36

### Browser and its version (浏览器及其版本)
Edge(101.0.1210.53)

### System and its version (系统及其版本)
Window

### Node version (Node 版本)
v16.14.2

### Reappearance link (重现链接)
https://codesandbox.io/s/nmodal-issue-7nguk7?file=/src/App.vue

### Reappearance steps (重现步骤)
點選畫面中的 Show Modal! 按鈕以開啟 NModal，此時應觸發 @update:show 並且回傳參數為 true，
目前只有在關閉 NModal 時才會觸發 @update:show 參數為 false

### Expected results (期望的结果)
開啟 NModal 時觸發 @update:show 並且參數回傳 true

### Actual results (实际的结果)
開啟 NModal 不會觸發 @update:show

### Remarks (补充说明)
參考文檔中 NModal 的 Props:
on-update:show	(value: boolean) => void	undefined	模態框更新是否展示狀態的回調

https://www.naiveui.com/zh-CN/os-theme/components/modal

**Comment by amadeus711** [comment]
Hello! NModal開啟動作是使用者的行為，你在編碼過程中是可以檢測到這個行為的。 經團隊討論，組件內部watch使用者的值再發回去並無意義，而且整個組件庫都遵循這個邏輯，所以這裡不予處理。

**Comment by 07akioni** [comment]
补充一点，你可以试试直接更改一个 input dom 的 value 属性，看看 dom 会不会抛一个 change 出来。

在你这个场景中是一致的。
