### ISSUE TITLE
Tabs hopes to support the position attribute

### ISSUE THREAD

**Issue by TheBlindM** [TuSimple/naive-ui#2995]
### This function solves the problem (这个功能解决的问题)
Tabs hopes to support the position attribute, for example, you can put options to the right or left
### Expected API (期望的 API)
Refer to adding tab-position attribute to el-tabs tag

**Comment by 07akioni** [comment]
What type of tabs you want the feature with.

**Comment by 07akioni** [comment]
> It's an ordinary n-tabs. I want to implement the sidebar like desktop tool vscode

You can use css as a workaround. We may not add the feature recently.

<img width="339" alt="image" src="https://user-images.githubusercontent.com/18677354/170882726-4e289591-1d76-497d-b2a7-be39fee56d0b.png">

<img width="667" alt="image" src="https://user-images.githubusercontent.com/18677354/170882734-5ef5cf56-7802-42c0-bd2c-affc42bad7b2.png">
