### ISSUE TITLE
Spin is Flashing

### ISSUE THREAD

**Issue by zzfn** [TuSimple/naive-ui#30]
### Environment Info

- Naive UI version: 2.11.4
- Browser Info: Chome 91
- System Info: Mac OS 10.15

### Reproduction link

https://www.naiveui.com/zh-CN/light/components/spin

### Steps to reproduce
官网例子
### What is expected?
流畅动画
### What is actually happening?
闪烁

**Comment by 07akioni** [comment]
Yes, I haven't find the solution. Since in theory the timing should be syncronized. Do you have any idea?

**Comment by chuifengji** [comment]
> I'll refactor the spin.
use a simpler animation, or use CSS3 instead of SVG ?

**Comment by chuifengji** [comment]
> I'll refactor the spin.

Use a simple animation, or use css3 instead of svg?

**Comment by 07akioni** [comment]
> > I'll refactor the spin.
> 
> Use a simple animation, or use css3 instead of svg?

I prefer material styled spin and will managed to implement it.
