### ISSUE TITLE
NPopconfirm增加action按钮的loading

### ISSUE THREAD

**Issue by 1161906592** [TuSimple/naive-ui#3006]
### This function solves the problem (这个功能解决的问题)
由于on-positive-click和on-negative-click两个事件回调本身是支持返回Promise的，那在Promise完成之前通常会需要有一个loading的用户反馈。
### Expected API (期望的 API)
增加一个入参来控制在Promise期间action按钮是否loading

**Comment by 07akioni** [comment]
你可以用 `:positiveButtonProps="{ loading: xxx}"` 来控制
