### ISSUE TITLE
当n-moda设置v-if与v-model:show为相同变量时，关闭弹框后html中的overflow: hidden

### ISSUE THREAD

**Issue by Adangs** [TuSimple/naive-ui#3015]
### This function solves the problem (这个功能解决的问题)
当n-moda设置v-if与v-model:show为相同变量时，关闭弹框后html中的overflow: hidden没被清除

<img width="297" alt="image" src="https://user-images.githubusercontent.com/5443355/170261574-f9faa0fd-9095-4815-9193-f8aafa8e2b3f.png">

### Expected API (期望的 API)
无

**Comment by 07akioni** [comment]
> 看了下文档，是2.28.3新增的特性； 可以通过 blockScroll 去控制；
> 
> 但是不是也应该考虑一下v-if的情况呢；

你说的对，我应该把这个当成 bug
