### ISSUE TITLE
n-select建议增加label-field和value-field

### ISSUE THREAD

**Issue by duanzonglong** [TuSimple/naive-ui#3018]
### This function solves the problem (这个功能解决的问题)
选项如果从API获取，可以自定义label-field和value-field简单进行渲染

前端每个地方都去转一遍太费事了 也有点浪费性能 如果数据量过大就更浪费了
### Expected API (期望的 API)
Expected API (期望的 API)
自定义label-field和value-field

**Comment by 07akioni** [comment]
我评估一下吧

**Comment by Enaium** [comment]
但这个功能不能像表单的path那样直接用对象路径进行渲染，需要在赋值options时把对象转换
<img width="599" alt="Snipaste_2023-11-27_20-24-35" src="https://github.com/tusen-ai/naive-ui/assets/32991121/858d450e-9f7c-48ac-a019-fd8f74de7167">
