### ISSUE TITLE
建议在根节点下使用css var来实现模式切换

### ISSUE THREAD

**Issue by Licoy** [TuSimple/naive-ui#3021]
### This function solves the problem (这个功能解决的问题)
在现在的框架实现内，每个组件都会携带style属性，其中包含大量的颜色及属性定义，当页面元素过多的时候，会造成性能的严重下降，建议在根节点下使用`css var`的方式定义颜色值及其相关通用属性。
### Expected API (期望的 API)
例如：
```
html{
--color-bg:#fff;
}
html.dark{
--color-bg:#000;
}
```

**Comment by 07akioni** [comment]
没发现有性能问题，有可靠的数据吗？

**Comment by 07akioni** [comment]
另外根节点定义这种无法做到每个组件都能独立的定制样式，不能满足库的功能诉求，我很早以前就试过。

**Comment by Licoy** [comment]
@07akioni 页面使用layout/menu/card/text组合的元素，1000个card小区块元素就会导致menu收缩展开异常卡顿，改天用codesandbox写个示例您看看

**Comment by Licoy** [comment]
@07akioni 在此demo中，节点数据量一旦过多，关闭菜单栏就会很卡：https://codesandbox.io/s/stoic-sinoussi-spu0yt?file=/src/views/demo.vue

**Comment by 07akioni** [comment]
> https://codesandbox.io/s/stoic-sinoussi-spu0yt?file=/src/views/demo.vue

你没有搞清楚问题在哪，页面节点多本身性能就会差，哪怕全都是普通 div 也会卡。

https://codesandbox.io/s/fancy-https-6ezy6f?file=/src/views/demo.vue

**Comment by 07akioni** [comment]
另外开发者如果遇到过多 DOM 的情况应该采取一些措施来解决这个问题，页面上一般 DOM 节点不要超过 1w 个。你给的这个了例子有 4w+，是 youtube 首页的 5 倍多，在开启动效的情况下卡是不可避免的。

**Comment by Licoy** [comment]
> 另外开发者如果遇到过多 DOM 的情况应该采取一些措施来解决这个问题，页面上一般 DOM 节点不要超过 1w 个。你给的这个例子有 4w+，是 youtube 首页的 5 倍多，在开启动效的情况下卡是不可避免的。

这个测试的节点上的内容都是很简单的，在实际应用中dom节点比这个要复杂一些，之前同样的方式，是渲染的10*100，也就是1000个n-card的节点，就和这个测试里面的一样卡，当时把里面的组件由原生标签替换，一下就不卡了，所以感觉是style的属性过于太多而导致的。

**Comment by 07akioni** [comment]
> 内容都是很简单的，在实际应用中dom节点比这个要复杂一些，之前同样的方式，是渲染的10*100，也就是1000个n-card的节点，就和这个测试里面的一样卡，当时把里面的组件由原生标签替换，一下就不卡了，所以感觉是style的属性过于太多而导致的。

你的感觉是不准确的，在 config-provider 上可以使用 inline-theme-disabled 把 inline 样式关掉，效果是一样的。

**Comment by 07akioni** [comment]
在你这个场景下，唯一可行的方案就是提供一个关掉折叠动画的属性。

**Comment by Licoy** [comment]
@07akioni 好的，感谢

**Comment by 07akioni** [comment]
> @07akioni 好的，感谢

如果需要关掉动画的话可以单独提一个 issue，我感觉是个合理的诉求
