### ISSUE TITLE
Image组件预览工具栏能否添加一个图片原尺寸展示的开关

### ISSUE THREAD

**Issue by ColoeusEdward** [TuSimple/naive-ui#3023]
### This function solves the problem (这个功能解决的问题)

ImagePreview组件里最大放大倍数为3倍, 对于某些长图来说并不够用
https://codesandbox.io/s/sharp-christian-kptfdj?file=/src/Demo.vue

### Expected API (期望的 API)

类似如下的Image组件
https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZGVtby1pbWFnZV9fcHJldmlld1wiPlxuICAgIDxlbC1pbWFnZVxuICAgICAgc3R5bGU9XCJ3aWR0aDogMTAwcHg7XCJcbiAgICAgIDpzcmM9XCJ1cmxcIlxuICAgICAgOnByZXZpZXctc3JjLWxpc3Q9XCJzcmNMaXN0XCJcbiAgICAgIDppbml0aWFsLWluZGV4PVwiNFwiXG4gICAgICBmaXQ9XCJjb3ZlclwiXG4gICAgLz5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuY29uc3QgdXJsID1cbiAgJ2h0dHA6Ly90dmExLnNpbmFpbWcuY24vbGFyZ2UvOTQ0OGJiZjhneTFoMm16b3gwOHRsajIwZzQ1eHloMHEuanBnJ1xuY29uc3Qgc3JjTGlzdCA9IFtcbiAgJ2h0dHA6Ly90dmExLnNpbmFpbWcuY24vbGFyZ2UvOTQ0OGJiZjhneTFoMm16b3gwOHRsajIwZzQ1eHloMHEuanBnJyxcbl1cbjwvc2NyaXB0PlxuXG48c3R5bGUgc2NvcGVkPlxuLmRlbW8taW1hZ2VfX2Vycm9yIC5pbWFnZS1zbG90IHtcbiAgZm9udC1zaXplOiAzMHB4O1xufVxuLmRlbW8taW1hZ2VfX2Vycm9yIC5pbWFnZS1zbG90IC5lbC1pY29uIHtcbiAgZm9udC1zaXplOiAzMHB4O1xufVxuLmRlbW8taW1hZ2VfX2Vycm9yIC5lbC1pbWFnZSB7XG4gIHdpZHRoOiAxMDAlO1xuICBoZWlnaHQ6IDIwMHB4O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==

**Comment by Sepush** [comment]
可以考虑

**Comment by 07akioni** [comment]
fixed
