### ISSUE TITLE
Have Modal open on dropdown

### ISSUE THREAD

**Issue by rationalthinker1** [TuSimple/naive-ui#3024]
### This function solves the problem (这个功能解决的问题)
https://www.naiveui.com/en-US/dark/components/dropdown
I want to use `n-modal` in one of the dropdown options.
### Expected API (期望的 API)
For `Dropdown`, I think that it should be another component called `dropdown-item` rather than options list.

**Comment by 07akioni** [comment]
use `on-select` to listen to option select.

set modal to show on the option selected.
