### ISSUE TITLE
嵌套的Drawer最内层的Input不能输入内容

### ISSUE THREAD

**Issue by focci** [TuSimple/naive-ui#3026]
### TuSimple/naive-ui version (版本)
2.29.0

### Vue version (Vue 版本)
3.2.36

### Browser and its version (浏览器及其版本)
Chrome(89.0.4389.128)

### System and its version (系统及其版本)
MacOS(11.2.3)

### Reappearance link (重现链接)
https://codesandbox.io/s/optimistic-wind-jw53nb?file=/src/Demo.vue

### Reappearance steps (重现步骤)
1）两个嵌套的Drawer，将最内层的show-mask值设置为false
2）点击最内层的Drawer中的Input

### Expected results (期望的结果)
【内层的Drawer】中的Input获得焦点，并可以输入内容

### Actual results (实际的结果)
【外层Drawer】中的Input获得焦点

**Comment by amadeus711** [comment]
https://codesandbox.io/s/competent-wave-od8c1l?file=/src/Demo.vue
如果想实现这个效果，你需要在内层的Drawer中关闭mask-closable

**Comment by focci** [comment]
添加了此属性，内层Drawer的Input还是不能输入内容

**Comment by focci** [comment]
@amadeus711 
关闭了mask-closable 属性，内层Drawer的Input还是不能输入内容
https://codesandbox.io/s/competent-wave-od8c1l?file=/src/Demo.vue

**Comment by 07akioni** [comment]
> https://codesandbox.io/s/competent-wave-od8c1l?file=/src/Demo.vue

都加上这个就好了
<img width="289" alt="image" src="https://user-images.githubusercontent.com/18677354/170879389-7c736ea6-2e07-43d9-8fe2-9ac94fbeacea.png">

**Comment by 07akioni** [comment]
不过我感觉你给的这个 case 确实比较特殊。

我之后会考虑把 trap-focus 默认设为 false
