### ISSUE TITLE
【dataTable】 remote属性和column的filter属性冲突

### ISSUE THREAD

**Issue by YangJ0605** [TuSimple/naive-ui#3027]
### TuSimple/naive-ui version (版本)
2.29.0

### Vue version (Vue 版本)
3.2.36

### Browser and its version (浏览器及其版本)
edge最新版本

### System and its version (系统及其版本)
win11

### Reappearance link (重现链接)
https://github.com/YangJ0605/test-naive-ui/blob/main/src/components/TestTable.tsx

### Reappearance steps (重现步骤)
DataTable中的remote属性和filter冲突，如果不加remote无法得到正确的分页显示，就算是加了pageCount也是无法显示，但是filter是可以正常过滤，而加上remote，可以正常的显示分页，但是filter就无效果了

### Expected results (期望的结果)
期待remote和filter都能正常使用

### Actual results (实际的结果)
remote属性和filter不能同时起效果

**Comment by 07akioni** [comment]
filter 预期是全局生效。remote 情况下过滤数据的获取由用户控制。

**Comment by whalesink** [comment]
开启 remote 情况下应该怎么用 filter ？看了下 filter 是不被调用的

**Comment by pro-xiaoy** [comment]
在配置了remote的时候 有没有方法可以手动触发column中filter的方法，这个方法在web端做筛选很好用 @07akioni
