### ISSUE TITLE
NUpload 非受控手动提交后的回调问题

### ISSUE THREAD

**Issue by craigary** [TuSimple/naive-ui#3028]
### This function solves the problem (这个功能解决的问题)
在 NUpload 组件中，为避免重复上传，使用了手动提交上传。即在 NModal 组件中（`preset="dialog"`）的  `@positive-click` 提交上传，然后希望根据返回的文件地址进行提交等下一步操作。

然而执行 `NUploadRef?.value?.submit()` 后不会返回信息，且因为异步的原因，无法方便得通过 onFinish 获取上传结果。
### Expected API (期望的 API)
希望执行 `NUploadRef?.value?.submit()` 后返回 `onFinish` 的信息

**Comment by 07akioni** [comment]
执行之前遍历一下 fileList 可以吗？

**Comment by 07akioni** [comment]
closed for no response
