### ISSUE TITLE
点击一个数据表格展开箭头，所有的可展开项被同时展开

### ISSUE THREAD

**Issue by wj007881** [TuSimple/naive-ui#3032]
### TuSimple/naive-ui version (版本)
2.29.0

### Vue version (Vue 版本)
3.2.36

### Browser and its version (浏览器及其版本)
EDGE101.0.1210.53 (正式版本) (64 位)

### System and its version (系统及其版本)
Windows10

### Reappearance link (重现链接)
https://codesandbox.io/s/falling-snow-86pyxh?file=/src/Demo.vue

### Reappearance steps (重现步骤)
点击一个数据表格展开箭头，所有的可展开项被同时展开

### Expected results (期望的结果)
只展开一项

### Actual results (实际的结果)
所有项目都被展开

**Comment by 07akioni** [comment]
估计是 key 没穿或者 rowKey 给错了
