### ISSUE TITLE
New Component: Dashboard Layout

### ISSUE THREAD

**Issue by brsanthu** [TuSimple/naive-ui#3044]
### This function solves the problem (这个功能解决的问题)
Most of the applications need dashboard layout to show graphs or metrics in home page. It would be awesome to provide such component in naive-ui.
### Expected API (期望的 API)
<NDashboard>

</NDashboard>

**Comment by 07akioni** [comment]
What does you mean dashboard layout? It's there more specific reference?

**Comment by brsanthu** [comment]
With Dashboard layout I mean, a component that allows you to add one or more widgets into it, re-arrange them, resize them etc., 

https://www.google.com/search?q=dashboard+layout

https://www.syncfusion.com/react-ui-components/react-dashboard-layout#:~:text=React%20Dashboard%20Layout%20is%20a,programmatically%20or%20dynamically%20at%20runtime.

**Comment by Sepush** [comment]
What you need is a dashbord teamplate.
Compose a few components of naive-ui, you can get a dashbord layout.
We don't need to provide a component.
If you don't want to do it yourself,base on one of dashbord teamplate in https://github.com/naive-ui/awesome-naive also a choice.

**Comment by 07akioni** [comment]
> What you need is a dashbord teamplate. Compose a few components of naive-ui, you can get a dashbord layout. We don't need to provide a component. If you don't want to do it yourself,base on one of dashbord teamplate in https://github.com/naive-ui/awesome-naive also a choice.

Yes, I think grid + card is somehow enough. If it's not enough I think it's better to use a library for the specific scene.
