### ISSUE TITLE
Horizontal scrollbar not showing in datatable

### ISSUE THREAD

**Issue by andripgbyk** [TuSimple/naive-ui#3047]
### TuSimple/naive-ui version (版本)
2.29.1

### Vue version (Vue 版本)
3.2.36

### Browser and its version (浏览器及其版本)
Chrome (102.0.5005.63)

### System and its version (系统及其版本)
Windows 11 (10.0.22000 Build 22000)

### Node version (Node 版本)
16.14.0

### Reappearance link (重现链接)
https://www.naiveui.com/en-US/os-theme/components/data-table#fixed-header-column.vue

### Reappearance steps (重现步骤)
from the demo in the documentation it doesn't work anymore

### Expected results (期望的结果)
Previously, the horizontal scrollbar appeared

### Actual results (实际的结果)
After I updated the version to 2.29.1

**Comment by kkfive** [comment]
I met the same problem
