### ISSUE TITLE
是否可以提供入口，将所有组件的关闭样式恢复到之前版本

### ISSUE THREAD

**Issue by muchenfine** [TuSimple/naive-ui#3051]
### This function solves the problem (这个功能解决的问题)
目前所有组件的关闭按钮使用了新样式、看起来风格跟现在的完全不和谐。。 是否可以提供全局修改的入口，可以恢复到之前版本的样式
### Expected API (期望的 API)
目前所有组件的关闭按钮使用了新样式、看起来风格跟现在的整体风格完全不和谐。。 是否可以提供全局修改的入口，可以恢复到之前版本的样式
![QQ截图20220606151525](https://user-images.githubusercontent.com/94693483/172113973-4a946141-d847-4a0b-9d39-2c7b1be7bfbb.png)

**Comment by 07akioni** [comment]
可以用主题覆盖
```
{
  "common": {
    "closeColorHover": "rgba(0, 0, 0, 0)",
    "closeColorPressed": "rgba(0, 0, 0, 0)",
    "closeIconColorHover": "rgba(149, 149, 149, 1)",
    "closeIconColorPressed": "rgba(89, 89, 89, 1)",
    "closeIconColor": "rgba(122, 122, 122, 1)"
  }
}
```

**Comment by muchenfine** [comment]
为什么考虑要重构按钮， 现在的风格感觉像纯净的风格里面加了一个tag....

**Comment by 07akioni** [comment]
> 为什么考虑要重构按钮， 现在的风格感觉像纯净的风格里面加了一个tag....

新的风格对触发区域和点按效果体现的更明确，我觉得是 icon button 更好的一个处理方式

比如看 gmail

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/18677354/172132632-c14561d4-505e-44c4-9e05-94a281b3006d.png">

**Comment by muchenfine** [comment]
![QQ截图20220606171946](https://user-images.githubusercontent.com/94693483/172133348-a98e6d63-07da-4f08-93dc-c6315b03eb40.png)
![QQ截图20220606171950](https://user-images.githubusercontent.com/94693483/172133319-dc929e35-8659-4c20-884a-d7bb8ee29ef1.png)
![QQ截图20220606171955](https://user-images.githubus
![QQ截图20220606172001](https://user-images.githubusercontent.com/94693483/172133337-f2b73e7b-c1e0-4cfe-80a9-8c74aa61cd9d.png)
ercontent.com/94693483/172133328-d3d15ca6-1c35-4867-920f-935a710aef20.png)

我参考了 element  ，ant，arco 
目前都没有采用阴影部分的背景色，大多都是悬停时符号高亮，只有arco悬停时有个浅阴影框

是否意味着这样的设计更合理。

**Comment by 07akioni** [comment]
设计是一种选择，很难说哪种就一定在所有人眼里都是更好的。

只能说做选择的人认为这样的设计更合理，并且也有对应的动机。

所以也提供了主题调整这种功能让用户可以将设计调整到用户认为的合理。

muchenfine ***@***.***> 于2022年6月6日周一 17:22写道：
