### ISSUE TITLE
NDataTable设置虚拟滚动的情况下会渲染出colSpan的单元格

### ISSUE THREAD

**Issue by JoshZxux** [TuSimple/naive-ui#3052]
### TuSimple/naive-ui version (版本)
2.30.0

### Vue version (Vue 版本)
3.2.36

### Browser and its version (浏览器及其版本)
Microsoft Edge 版本 101.0.1210.53 

### System and its version (系统及其版本)
Windows 11

### Reappearance link (重现链接)
https://codesandbox.io/s/xu88zj

### Reappearance steps (重现步骤)
1、设置virtual-scroll为true
2、设置某一列的colSpan
3、colSpan之后渲染了后面合并的单元格

### Expected results (期望的结果)
colSpan合并的列不渲染

### Actual results (实际的结果)
colSpan与虚拟滚动同时设置时 会渲染所有的列

**Comment by 07akioni** [comment]
data-table 目前不支持虚拟滚动 + rowSpan。

不过去掉 rowSpan 应该还是有一些 bug
