### ISSUE TITLE
DataTable 组件是否可以加入单选模式（radio）

### ISSUE THREAD

**Issue by kitaharafay** [TuSimple/naive-ui#3056]
### This function solves the problem (这个功能解决的问题)
There'a a scene, we only want to select single row of data-table.

有这样一个场景：我们使用DataTable有且只需要选择一行。
现在 type只有'selection' | 'expand'两个选择，使用selection会在TableHeader出现全选checkbox，这个并不是我们需要的
### Expected API (期望的 API)
DataTableColumn Properties
type: 'selection' | 'expand' | 'radio'

**Comment by 07akioni** [comment]
会考虑，优先级暂时不是很高，欢迎 PR

**Comment by binghc** [comment]
这很容易，在官方文档table组件位置随便这个demo或者自己写一个，吧这个table现在在一个有限大小的div里面，

**Comment by binghc** [comment]
这很容易，在官方文档table组件位置随便这个demo或者自己写一个，吧这个table现在在一个有限大小的div里面
比如这样
<div style="width:500px;height:500px;overflow: auto;padding:5px;background: orange;">
        <n-data-table
                :columns="[				
                    {
                        title: 'Name',
                        key: 'name',
                        width: 300,
                    },
                    {
                        title: 'Age',
                        key: 'age',
                        width: 300,
                    },
                    {
                        title: 'Address',
                        key: 'address',
                        width: 300,
                    }
                ]"
                :data="data"
                :pagination="pagination"
                :maxHeight="150"
                v-model:checked-row-keys="checkedRowKeys"
        />
    </div>

**Comment by binghc** [comment]
```
<div style="width:500px;height:500px;overflow: auto;padding:5px;background: orange;">
        <n-data-table
                :columns="[				
                    {
                        title: 'Name',
                        key: 'name',
                        width: 300,
                    },
                    {
                        title: 'Age',
                        key: 'age',
                        width: 300,
                    },
                    {
                        title: 'Address',
                        key: 'address',
                        width: 300,
                    }
                ]"
                :data="data"
                :pagination="pagination"
                :maxHeight="150"
                v-model:checked-row-keys="checkedRowKeys"
        />
    </div>
```

**Comment by binghc** [comment]
刚又发现table一个bug，没有给table设置maxHeight固定表头，这个table依然放在一个高度和宽度比table小的父容器里面，这时table会有垂直滚动条和水平滚动条，这没问题，但是只有垂直滚动条滚到下面才能看到水平滚动条

**Comment by binghc** [comment]
另外再提一个tree懒加载的一个bug，配置了expand-on-click，如果用户点击的这个节点还没有加载数据会报错

**Comment by 07akioni** [comment]
> <div style="width:500px;height:500px;overflow: auto;padding:5px;background: orange;">
>         <n-data-table
>                 :columns="[				
>                     {
>                         title: 'Name',
>                         key: 'name',
>                         width: 300,
>                     },
>                     {
>                         title: 'Age',
>                         key: 'age',
>                         width: 300,
>                     },
>                     {
>                         title: 'Address',
>                         key: 'address',
>                         width: 300,
>                     }
>                 ]"
>                 :data="data"
>                 :pagination="pagination"
>                 :maxHeight="150"
>                 v-model:checked-row-keys="checkedRowKeys"
>         />
>     </div>

这种情况不被看作 bug，必须要设定 scroll-x

**Comment by 07akioni** [comment]
closed in https://github.com/TuSimple/naive-ui/pull/3209
