### ISSUE TITLE
有没有办法让数据表格的下拉展示做成点击同行数据展开而不是点击箭头展开的吗

### ISSUE THREAD

**Issue by wj007881** [TuSimple/naive-ui#3059]
### This function solves the problem (这个功能解决的问题)
无法通过点击行数据展开对应的下拉展示界面
### Expected API (期望的 API)
https://gn.testin.cn/report/demo，就像网页里的点击行展开内容一样

**Comment by kitaharafay** [comment]
感觉可以用这个属性完成？
DataTable Props:
**row-props**: (rowData: object, rowIndex : number) => object

**Comment by 07akioni** [comment]
> 感觉可以用这个属性完成？ DataTable Props: **row-props**: (rowData: object, rowIndex : number) => object

+1

**Comment by wj007881** [comment]
感谢您的回复，但是我参考组件文档中的介绍，仍无法将expand列和row-props函数组合在一起使用，或者单独使用row-props函数完成内容的展开？
能否抽空帮忙提供一个实例说明下，谢谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月11日(周六) 凌晨0:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TuSimple/naive-ui] 有没有办法让数据表格的下拉展示做成点击同行数据展开而不是点击箭头展开的吗 (Issue #3059)




  
感觉可以用这个属性完成？ DataTable Props: row-props: (rowData: object, rowIndex : number) =&gt; object
  
+1

**Comment by wj007881** [comment]
感谢您的回复，但是我参考组件文档中的介绍，仍无法将expand列和row-props函数组合在一起使用，或者单独使用row-props函数完成内容的展开？
能否抽空帮忙提供一个实例说明下，谢谢！




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月11日(周六) 凌晨0:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TuSimple/naive-ui] 有没有办法让数据表格的下拉展示做成点击同行数据展开而不是点击箭头展开的吗 (Issue #3059)




  
感觉可以用这个属性完成？ DataTable Props: row-props: (rowData: object, rowIndex : number) =&gt; object
  
+1

**Comment by 07akioni** [comment]
`:row-props="{ onClick: rowData =>  expandedKeys.push(rowData.key) }"`

大概是这么个意思，注意要去重
