### ISSUE TITLE
When Menu collapsed，render-label did not work！

### ISSUE THREAD

**Issue by fufenghao** [TuSimple/naive-ui#306]
### TuSimple/naive-ui version (版本)
2.14.0

### Vue version (Vue 版本)
3.1.2

### Browser and its version (浏览器及其版本)
Chrome(89.0.4389.128)

### System and its version (系统及其版本)
Win

### Reappearance link (重现链接)
https://codesandbox.io/embed/rough-glitter-0mi1x?fontsize=14&hidenavigation=1&theme=dark

### Reappearance steps (重现步骤)
renderMenuLabel(option) {
        return h(
          "span",
          {
            to: option.key,
          },
          { default: () => option.label   "123345" }
        );
      },

### Expected results (期望的结果)
label is rendered

### Actual results (实际的结果)
label is not rendered

**Comment by 07akioni** [comment]
Will fix

**Comment by timeTravelCYN** [comment]
@fufenghao https://github.com/TuSimple/naive-ui/pull/308,

**Comment by 07akioni** [comment]
@timeTravelCYN Not fully fixed, dropdown still need a renderLabel prop to make menu work.
