### ISSUE TITLE
使用unplugin-vue-components自动引入时NSelect的选项为空

### ISSUE THREAD

**Issue by JawilX** [TuSimple/naive-ui#3066]
### TuSimple/naive-ui version (版本)
2.30.3

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Chrome(102.0.5005.61)

### System and its version (系统及其版本)
MacOS(10.15.7 )

### Node version (Node 版本)
16.14.2

### Reappearance link (重现链接)
https://jawilx.github.io/jtools/#/hexConvert

### Reappearance steps (重现步骤)
点击"10进制"选择框

### Expected results (期望的结果)
下拉列表正常显示内容

### Actual results (实际的结果)
下拉列表显示空白

**Comment by 07akioni** [comment]
这个肯定是最终代码哪里错了，unplugin 这个东西不是 naive 维护的

**Comment by 07akioni** [comment]
具体来说估计就是 options 有问题

**Comment by JawilX** [comment]
是的，就是看到options没加载进来，但是我想手动引入都找不到相应的组件，我再去unplugin那边问问吧
