### ISSUE TITLE
设置数据表格宽度大一点，如100，第二个fixed拖拽时会覆盖

### ISSUE THREAD

**Issue by halely** [TuSimple/naive-ui#3067]
### TuSimple/naive-ui version (版本)
2.30.3

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
102.0.5005.63

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://github.com/halely/issuelist/tree/master/%E5%88%97%E8%A6%86%E7%9B%96

### Reappearance steps (重现步骤)
设置数据表格 selection 列，宽度为100，设置fixed，然后再设置第二列fixed，宽度150，列数稍微多点，scroll-x 通过每个列的宽度相加生成，拖拽的时候，第二个会覆盖selection 

### Expected results (期望的结果)
预期是scroll-x计算没有问题的情况下，每一列间距分明

### Actual results (实际的结果)
出现了覆盖

**Comment by 07akioni** [comment]
是个重要的 bug
