### ISSUE TITLE
transfer 组件是否可以提供一个自定义数据项渲染函数

### ISSUE THREAD

**Issue by opcooc** [TuSimple/naive-ui#3069]
### This function solves the problem (这个功能解决的问题)
当transfer数据太长是会出现换行并挤在一起的问题

### Expected API (期望的 API)
function(h, option)
![image](https://user-images.githubusercontent.com/34977303/172850018-2b33dbd7-97b4-4ed0-a54b-b971b0e5e235.png)

**Comment by 07akioni** [comment]
现在这个 transfer 的能力确实不尽如人意= =。。。

**Comment by 07akioni** [comment]
会想个办法尽量解决掉

**Comment by opcooc** [comment]
> 会想个办法尽量解决掉

好的 多谢大佬了

**Comment by opcooc** [comment]
2.32.0版本已解决 感谢
