### ISSUE TITLE
图像 Image组件，添加支持图片默认放大并展示底部工具栏，且放大的图片显示在指定元素内

### ISSUE THREAD

**Issue by wei1034937343** [TuSimple/naive-ui#3072]
### This function solves the problem (这个功能解决的问题)
政务办公系统一般讲究效率，查看不同类型的文件时，如图片、文本、多媒体文件等，用户不愿意多次文件点击查看，用于制作一款能够同时查看多种不同类型的文件查看器
### Expected API (期望的 API)
如增加参数，default-show-toolbar: true 表示图片默认放大并展示底部工具栏，show-toolbar-object-fit: div 表示放大图片在指定的dom元素中展示，此时preview-disabled: true 表示不能点击图片进行还原

希望，图像 Image组件，能够默认放大并展示底部工具栏，并且放大后的图片展示在，下图小弹出框左侧预留的空白区域，谢谢。

![image](https://user-images.githubusercontent.com/28970254/172837245-64a70b31-10c4-4fcb-b4f9-09fd756f485d.png)

**Comment by 07akioni** [comment]
图片预览组件应该是不会支持其他类型的文件，然后位置适配应该也是不太会做的，这个预期就是起一个全屏预览的功能
