### ISSUE TITLE
希望data-table组件给一个默认展开所有选中行的属性

### ISSUE THREAD

**Issue by opcooc** [TuSimple/naive-ui#3073]
### This function solves the problem (这个功能解决的问题)
当表格数据为树形数据时 用户希望结构全部展开
### Expected API (期望的 API)
props
![image](https://user-images.githubusercontent.com/34977303/172849525-d4af7331-a9e1-4bcf-906b-cd64ce7f6882.png)

**Comment by 07akioni** [comment]
这个勾选和展开做关联我确实感觉有点子奇怪

**Comment by 07akioni** [comment]
当然也不是完全不合理

**Comment by 07akioni** [comment]
要说默认全都展开我倒是也可以理解

**Comment by opcooc** [comment]
> 要说默认全都展开我倒是也可以理解，这个可以算是个通用功能

是的 如果可以的话希望帮忙加下默认全部展开 多谢了
