### ISSUE TITLE
分页组件在点击fast-forward按钮的时候有展示性的问题

### ISSUE THREAD

**Issue by casatwy** [TuSimple/naive-ui#3076]
### TuSimple/naive-ui version (版本)
2.30.3

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
102.0.5005.61（正式版本） (x86_64)

### System and its version (系统及其版本)
macOS（10.15.7）

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/pagination

### Reappearance steps (重现步骤)

目前看这应该是pagination组件的bug，因为我在官网Demo中也复现了同样的bug：

在官网的《使用元素个数控制分页》demo中，先选择1，将当前页设置为1。然后点击fast-forward按钮，此时当前页跳到6。bug产生：此时page 6为选中状态，但是fast-backword按钮的内容应该是【...】，而不应该是【<-】

### Expected results (期望的结果)
点击fast-forward之后，当前page的label为选中状态，且fast-backword按钮的内容应该是【...】

### Actual results (实际的结果)
点击fast-forward之后，当前page的label为选中状态，但fast-backword按钮的内容是【<-】

### Remarks (补充说明)

![截屏2022-06-09 下午9 53 20](https://user-images.githubusercontent.com/1005781/172865803-32b111f6-3e78-41b6-bb95-ed0d2f6a7ac0.png)

**Comment by 07akioni** [comment]
别说，这个 bug 有点意思...

**Comment by 07akioni** [comment]
fixed in 24075c8cb7c74ca3388794b00bbb16d18ab576f3
