### ISSUE TITLE
tree 需要横向滚动条 子节点特别多的情况下 参考文件夹目录场景

### ISSUE THREAD

**Issue by gowy222** [TuSimple/naive-ui#3077]
### This function solves the problem (这个功能解决的问题)
网盘文件夹 无可预期会一层层嵌套多少子节点。
异步 无限 加载 子文件夹场景... 最终超出屏幕范围显示异常
目前的tree横向 文字 都超出屏幕范围,
只有Y轴自带滚动条, X轴没有。
另外，可否支持 目前显示滚动条?不要hover的情况才显示滚动条。
### Expected API (期望的 API)
Y轴，X轴 都有滚动条，且可控 是否只有hover才显示滚动条

**Comment by 07akioni** [comment]
参考一下这个 https://github.com/TuSimple/naive-ui/issues/2875
