### ISSUE TITLE
使用n-carousel的时候，无法展示具体的每一页的内容

### ISSUE THREAD

**Issue by casatwy** [TuSimple/naive-ui#3078]
### TuSimple/naive-ui version (版本)
2.30.3

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
102.0.5005.61（正式版本） (x86_64)

### System and its version (系统及其版本)
macOS（10.15.7）

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/carousel

### Reappearance steps (重现步骤)
按照demo的默认写法使用

### Expected results (期望的结果)
期望能看到图片

### Actual results (实际的结果)
图片没有展示

### Remarks (补充说明)

我使用的代码如下：

![截屏2022-06-10 上午9 39 50](https://user-images.githubusercontent.com/1005781/172973456-33c4429f-27af-45f3-aac1-9110109b6603.png)

在浏览器上展示如下：

![截屏2022-06-10 上午9 41 47](https://user-images.githubusercontent.com/1005781/172973521-86eed159-f7b2-4f20-aeab-e03f5a679887.png)

我打开调试工具发现宽度都为0:

![截屏2022-06-10 上午9 39 10](https://user-images.githubusercontent.com/1005781/172973565-bcc0adb4-a611-4dbe-a4f7-a15062495a1b.png)

**Comment by 07akioni** [comment]
@nooooooom 看看这个？
