### ISSUE TITLE
n-input 组件在选中文字的时候浏览器报错。

### ISSUE THREAD

**Issue by freebazzi** [TuSimple/naive-ui#3080]
### TuSimple/naive-ui version (版本)
2.29.0

### Vue version (Vue 版本)
3.2.36

### Browser and its version (浏览器及其版本)
Chrome(101.0.4951.54)

### System and its version (系统及其版本)
Windows 10 Pro

### Node version (Node 版本)
v16.14.0

### Reappearance link (重现链接)
https://www.naiveui.com/en-US/light/components/input

### Reappearance steps (重现步骤)
n-input 输入字符后，鼠标选中文字（选中单个或全部都可）

### Expected results (期望的结果)
解决浏览器红字报错。

### Actual results (实际的结果)
选中文本时会出现浏览器红字报错。

**Comment by 07akioni** [comment]
需要提供更详细的报错信息

**Comment by freebazzi** [comment]
![{YVAQE6ZTF8L7KPYB_QI7L](https://user-images.githubusercontent.com/7948777/173080231-288be2b6-f82b-4719-a19b-247a67bbf04d.png)
![QQ图片20220610224400](https://user-images.githubusercontent.com/7948777/173079882-cd7bc6a0-40f4-44e7-b867-870844daf55b.png)

选中n-input中的值之后，就会报这个错误
多次选中会重复报

**Comment by 07akioni** [comment]
> ![{YVAQE6ZTF8L7KPYB_QI7L](https://user-images.githubusercontent.com/7948777/173080231-288be2b6-f82b-4719-a19b-247a67bbf04d.png) ![QQ图片20220610224400](https://user-images.githubusercontent.com/7948777/173079882-cd7bc6a0-40f4-44e7-b867-870844daf55b.png)
> 
> 选中n-input中的值之后，就会报这个错误 多次选中会重复报

点一下错误堆栈，format 一下看看具体报错的代码？

我确实无法复现

**Comment by 07akioni** [comment]
因为我在 input 源码里面没有搜到 setTimeout 这个东西。打开隐身模式看看呢？是不是和浏览器插件冲突了

**Comment by freebazzi** [comment]
> 因为我在 input 源码里面没有搜到 setTimeout 这个东西。打开隐身模式看看呢？是不是和浏览器插件冲突了

 可能是这个原因。
我换台电脑就没问题了

**Comment by 07akioni** [comment]
> 个原因。
> 我换台电

OK，有问题的话可以继续评论
