### ISSUE TITLE
虚拟化table鼠标不动时快速滚动，会滚一段就无法滚动

### ISSUE THREAD

**Issue by x101046** [TuSimple/naive-ui#3082]
### TuSimple/naive-ui version (版本)
2.30.3

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
chrome 102.0.5005.63

### System and its version (系统及其版本)
win10 19044.1706

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/dark/components/data-table#virtual.vue

### Reappearance steps (重现步骤)
鼠标不动时滚动

### Expected results (期望的结果)
流畅滚动

### Actual results (实际的结果)
会停一段时间才能继续滚动

**Comment by 07akioni** [comment]
在我的机器上无法复现，先给个录屏看看？

**Comment by 07akioni** [comment]
用的什么鼠标能讲一下吗？

**Comment by 07akioni** [comment]
最近确实看到几个反馈，但是一直没能复现

**Comment by x101046** [comment]
和鼠标没有关系，我在多个不同设备上测试都有这个问题，就是鼠标不动，滚轮快速连续滑动，就会出现，缓慢滑动就不会

**Comment by x101046** [comment]
https://user-images.githubusercontent.com/38268032/173311982-fa0681d2-057a-480a-bef3-99dd1ad2ef99.mp4
鼠标停止移动时滚轮的滚动没有停

**Comment by 07akioni** [comment]
应该是 Chrome 102 出现了 bug，可以在这个 issue 讨论，目前推测是同一个问题

https://github.com/TuSimple/naive-ui/issues/3048
