### ISSUE TITLE
希望能有一个setup语法糖版本

### ISSUE THREAD

**Issue by Dongleb** [TuSimple/naive-ui#3083]
### This function solves the problem (这个功能解决的问题)
setup语法糖应该是一个趋势，我有时需要改写一些组件的代码，由于我本身自己写的其他组件用了setup语法糖，导致有时候会有些麻烦，希望能有一个setup语法糖的组件版本。
### Expected API (期望的 API)
更加舒适的

**Comment by 07akioni** [comment]
暂时没这个想法，demo 写起来非常多，几万行，不可能花很多时间专门改的

**Comment by Gino-Y** [comment]
这个修改是有规律的。
是不是可以写个Python脚本，
自动化生成setup语法糖版本。

**Comment by Gino-Y** [comment]
> 暂时没这个计划，demo 写起来非常多，几万行，不可能花很多时间专门改的

这个修改是有规律的。
是不是可以写个Python脚本，
自动化生成setup语法糖版本。

**Comment by Gino-Y** [comment]
这个修改是有规律的。
是不是可以写个Python脚本，
自动化生成setup语法糖版本。

**Comment by 07akioni** [comment]
即使做了都是需要成本的，加了 setup 的还会有人想要不 setup 的版本

精力有限的情况下维护者会优先做一些更重要的事
