### ISSUE TITLE
如何给n-tree的nodeProps添加动态class，希望支持一下

### ISSUE THREAD

**Issue by MrPenta** [TuSimple/naive-ui#3086]
### This function solves the problem (这个功能解决的问题)
希望n-tree中通过nodeProps创建的节点也能支持动态绑定class
### Expected API (期望的 API)
现在再n-tree内通过nodeProps添加的节点，不知道怎么去动态绑定class，希望支持一下，目前涉及到一个需求是需要class动态化

**Comment by amadeus711** [comment]
https://codesandbox.io/s/epic-zeh-qkdxiq?file=/src/Demo.vue
