### ISSUE TITLE
DataTable组件标题列太多，但是表格数据为空时，标题无法滚动

### ISSUE THREAD

**Issue by godzzh** [TuSimple/naive-ui#3093]
### This function solves the problem (这个功能解决的问题)
设置了scroll-x，有数据时，左右滚动正常，但是没有数据时，标题无法滚动，无法看到后面的标题是什么
### Expected API (期望的 API)
期望在表格数据是空时，标题也能正常滚动

**Comment by 07akioni** [comment]
你有在标题上进行过滚动么

**Comment by godzzh** [comment]
> 你有在标题上进行过滚动么

试过了，没有滚动条，鼠标滚动不了，但是键盘左右方向键可以。。。

**Comment by 07akioni** [comment]
这个表现实际上是符合预期的…

**Comment by 07akioni** [comment]
这块暂时优化的想法不大，可能会在之后的重构中顺便处理

**Comment by likailun101929** [comment]
怎么解决表格数据为空不能横向滚动的问题啊

**Comment by godzzh** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 1youziLi** [comment]
我也碰到了，很奇怪，就是没有数据的时候，表头没有滚动条，鼠标不能左右滚动，只能笔记本上的触屏可以

**Comment by godzzh** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
