### ISSUE TITLE
可以在tabs添加滑动功能吗

### ISSUE THREAD

**Issue by index-xiao** [TuSimple/naive-ui#3094]
### This function solves the problem (这个功能解决的问题)
当type=‘card’时，多个panel无法展示完，点击某个panel或者使用api选中时，可以自动定位且滑动到该panel。可以的话将prefix与suffix插槽默认做成按钮形式，点击后可以滑动到最前或最后，类似elementui的tabs那样
### Expected API (期望的 API)
默认插槽 弄成按钮，点击后自动滑动
prefix 
suffix

**Comment by 07akioni** [comment]
按钮的这个问题考虑过，在没找到合适的 UI 呈现方式前应该暂时不会加

感觉箭头有点丑

**Comment by 07akioni** [comment]
之前考虑过，如果一定要处理这个问题的话，更加倾向于 antd 的处理方式

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/18677354/174446873-f8b8cbd8-155e-46b8-9362-693897fc8e6e.png">

**Comment by 07akioni** [comment]
后续可以在 https://github.com/TuSimple/naive-ui/issues/2128 讨论
