### ISSUE TITLE
是否给Data Table某个字段值为空时增加一个默认占位符？

### ISSUE THREAD

**Issue by Adangs** [TuSimple/naive-ui#3095]
### This function solves the problem (这个功能解决的问题)
实际业务场景中每一行中经常会有空值数据。
这个时候
要么渲染之前格式化一下数据，
要么需要单独写个render去判断一下，返回一个具体值或者占位字符，

这个时候是否可以给个data table增加一个全局的 placeholder，并且支持columns中单独配置
{
      title: 'Title',
      key: 'title',
      placeholder: '空'   
}
### Expected API (期望的 API)
无

**Comment by 07akioni** [comment]
这个感觉是个有点意思的功能，可以加上，我们可以想办法让用户接管 cell 的渲染函数
