### ISSUE TITLE
数据表格滚动条支持常显

### ISSUE THREAD

**Issue by yanbowe** [TuSimple/naive-ui#3100]
### This function solves the problem (这个功能解决的问题)
直观的显示表格可滚动，像hover效果一样
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/43030980/173551646-e4a91011-3ddc-4b15-948a-bf5f524a0673.png">

### Expected API (期望的 API)
trigger="none"  像scrollbar一样
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/43030980/173551280-40b3d306-4846-4cd1-8ff7-a4ae2ffa4e61.png">

**Comment by 07akioni** [comment]
暂时不想开这个口子，我觉得必要性不是特别大。

未来有可能会添加一个全局的开关。

**Comment by yanbowe** [comment]
> 暂时不想开这个口子，我觉得必要性不是特别大。
> 
> 未来有可能会添加一个全局的开关，不允许组件级别的定义。

收到
