### ISSUE TITLE
Tabs可以增加左右和底部布局吗?

### ISSUE THREAD

**Issue by Aicmortal** [TuSimple/naive-ui#3102]
### This function solves the problem (这个功能解决的问题)
选项卡可以防止在左侧或者右侧,或者底部
![截图_20220615095105](https://user-images.githubusercontent.com/16420004/173720013-88c01a15-dc4d-4808-924b-82e1d3813026.png)

![截图_20220615095148](https://user-images.githubusercontent.com/16420004/173720021-36e828f7-675b-4594-92bb-1ca7f6b61d13.png)

![截图_20220615094935](https://user-images.githubusercontent.com/16420004/173720030-5a715f28-de11-4d0b-bcbc-1a38046318c1.png)

![截图_20220615095017](https://user-images.githubusercontent.com/16420004/173720045-14732b48-b32e-4d06-bae6-cf127959014e.png)

### Expected API (期望的 API)
选项卡可以防止在左侧或者右侧,或者底部

**Comment by Talljack** [comment]
same #1466
