### ISSUE TITLE
自动引入ts定义丢失问题  auto import definition missing

### ISSUE THREAD

**Issue by kuyaaaa** [TuSimple/naive-ui#3104]
### TuSimple/naive-ui version (版本)
2.30.4

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
windows10

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/docs/usage-sfc

### Reappearance steps (重现步骤)
在配置了Volar支持后，自动引入的组件定义类型会被any顶替：
```json
{
  "compilerOptions": {
    // ...
    "types": ["naive-ui/volar"]
  }
}
```
发现是volar.d.ts定义下有一个 [key: string]: any 的定义导致组件定义被覆盖成any，自行修改tsconfig将naive-ui/volar定义文件替换为自动引入编译的component.d.ts后恢复正常类型定义。

请问这个是什么问题？官方文档也并没有说明这一点。

vscode版本：1.68.0
typescript版本：4.7.3
volar版本：v0.37.8

-------------------------------------------------------------------------------------
After configuring the volar support, the automatically imported component definition type will be replaced by any:
```json
{
  "compilerOptions": {
    // ...
    "types": ["naive-ui/volar"]
  }
}
```
It was found that it was volar d. There is a "[key: string]: any" under the TS definition: the definition of any causes the component definition to be overwritten with any. Modify the tsconfig to replace the"naive-ui/volar" definition file with the Automatic compilation "component.d.ts". Restore the normal type definition after ts.

What is the problem? Official documents do not state this either.

version:
vscode: 1.68.0
typescript: 4.7.3
volar: v0.37.8

### Expected results (期望的结果)
组件自动引入具有ts类型定义
components are auto import with TS type definitions

### Actual results (实际的结果)
组件自动引入后ts全为any定义
components are auto import with TS type is all "any"

**Comment by 07akioni** [comment]
@kuyaaaa 我有点好奇这个问题，我自己之前试发现好像没啥问题，然后之前也没有 issue 提过，会不会是 volar 某个版本之后行为变了

**Comment by kuyaaaa** [comment]
> @kuyaaaa我之前试了一下发现好像没有什么问题，然后之前没有问题提过不会是 volar 也会有一些自己好奇之后的行为变了

我也不是很清楚具体原因，就跟下面这张图一样，组件会有多处定义，而最终取了any类型，开启自动引入删除掉ts的naive-ui/volar type就对了，不知道这个下面的any定义有何意义？
![image](https://user-images.githubusercontent.com/54495986/174451609-5bde622e-033d-493a-becd-e69d1045af21.png)

**Comment by blackawn** [comment]
貌似直接引入也会提示，修改为`ref<any>`才正常
![image](https://user-images.githubusercontent.com/49859450/177253270-d31c0f17-9e8d-4dbf-9bf3-123a460b64bb.png)

**Comment by 07akioni** [comment]
> 

这看起来是 ide 的问题
