### ISSUE TITLE
ios Carousel cannot swipe 轮播图无法滑动

### ISSUE THREAD

**Issue by RogerWenXin** [TuSimple/naive-ui#3106]
### TuSimple/naive-ui version (版本)
2.30.4

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
any

### System and its version (系统及其版本)
ios

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/carousel

### Reappearance steps (重现步骤)
use iphone to visit naive ui official page, cannot swipe.

### Expected results (期望的结果)
can swipe to next and preview

### Actual results (实际的结果)
swipe cannot work

**Comment by 07akioni** [comment]
set draggable to true

**Comment by RogerWenXin** [comment]
> set draggable to true

I mean IOS cannot swipe, you can reappearance it use iphone to visit official page, the slide effect cannot use on ios, even draggable.

**Comment by Wlisfes** [comment]
n-data-table中flex-height设置为true， 在ios、ipad上纵向也无法滑动

**Comment by 07akioni** [comment]
> n-data-table中flex-height设置为true， 在ios、ipad上纵向也无法滑动

get，周末看看，另外提一个 issue 吧

**Comment by 07akioni** [comment]
点错了
