### ISSUE TITLE
是否支持使用css中的vw、vh或百分比设置控件的宽高或space的size参数

### ISSUE THREAD

**Issue by supf1994** [TuSimple/naive-ui#3108]
### This function solves the problem (这个功能解决的问题)
是否支持使用css中的vw、vh或百分比设置控件的宽高或space的size参数

### Expected API (期望的 API)
添加相应功能

**Comment by 07akioni** [comment]
我觉得这从用户体验的角度不是很合理

**Comment by supf1994** [comment]
> 我觉得这从用户体验的角度不是很合理，具体场景是什么

开发平板应用，可能平板有不同的分辨率，因此尽量使用百分比设置大小，以适配不同屏幕的分辨率，比如space的size参数，如果固定采用px，则碰到分辨率比较小的平板可能间距就过大

**Comment by 07akioni** [comment]
> 因此尽量使用百分比设置大小，以适配不同屏幕的分辨率，比如space的size参数，如果固定采用px，则碰到分辨率比较小的平板

我的想法在于 vw 和 wh 实际上是非常粗略的大小，一般用作容器的宽度而不是间距的宽度。

在用他们作为精确大小的时候我感觉可能主要是类似于 rem 的方案，用作等比放大的参照，但是目前看来这个事情和 UI 整体的思路是不一致的，即使这里 hack 了其他地方一样会出问题。我个人也是不太喜欢等比放大的设计方案。

建议用 flex + gap 的 css 属性处理一下
