### ISSUE TITLE
The n-tree component gets both all-selected and partially-selected nodes

### ISSUE THREAD

**Issue by yingnian** [TuSimple/naive-ui#3110]
### This function solves the problem (这个功能解决的问题)
When granting permissions, some nodes under a parent have permissions. At this time, the information of the parent node needs to be passed to the background as well.

在权限赋值的场景下，一个父级菜单下面的节点没有被全部选中时，需要将半选状态的父级也一起传递给后台，所以需要同时获取半选和全选状态的所有节点

### Expected API (期望的 API)
Check-strategy API adds properties other than all/parent/child

能否在 Check-strategy 下增加属性，来获取当前子集的父级直至根节点

**Comment by 07akioni** [comment]
on-update-indeterminated-keys?

反正一开始都是空的

**Comment by 07akioni** [comment]
如果一开始不是空的，说明后台本身已经有所计算，不需要前端告诉
如果一开始是空的，on-update-indeterminate-keys 就够了
如果一开始不是空的，并且后台也不清楚，说明这个权限系统有问题，后台都搞不清楚什么人有什么权限
