### ISSUE TITLE
n-select渲染失败

### ISSUE THREAD

**Issue by SchneeHertz** [TuSimple/naive-ui#3112]
### TuSimple/naive-ui version (版本)
2.30.4

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Chrome 100

### System and its version (系统及其版本)
Window 10

### Reappearance link (重现链接)
https://codesandbox.io/s/kind-estrela-ihnhpo?file=/src/Demo.vue

### Reappearance steps (重现步骤)
在动态表单内使用v-for，当n-select的v-model:value设置的值为undefined时，n-select不能正常渲染

### Expected results (期望的结果)
n-select渲染正常

### Actual results (实际的结果)
在动态表单内使用v-for，当n-select的v-model:value设置的值为undefined时，n-select不能正常渲染
![screenshot](https://p.sda1.dev/6/93c286a5f095d73c71b374003e8b0e74/Snipaste_2022-06-16_16-36-55.png)

**Comment by Talljack** [comment]
看起来像是渲染了，但是没有宽度
![image](https://user-images.githubusercontent.com/34439652/174208681-ab1ad6b5-7ec6-4ee4-b10b-273e52dd74a0.png)

**Comment by 07akioni** [comment]
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/18677354/174439059-4ad5de89-9abd-4d0e-b160-c8f4154b43c2.png">

This is a style issue.

**Comment by 07akioni** [comment]
add flex 1
