### ISSUE TITLE
数据表格 Data Table 居然没有row click/dbclick事件? 不是吧...

### ISSUE THREAD

**Issue by gowy222** [TuSimple/naive-ui#3113]
### This function solves the problem (这个功能解决的问题)
应用场景，上下两个表格联动。上面表格点击行，click/dbclick事件 给出点击行的数据，依据数据中的UID再去加载下面表格对应数据... 。点击行变色没有还能二次想办法实现，但是基操 没有行点击事件 有点尴尬...
### Expected API (期望的 API)
on-row click/dbclick

**Comment by gowy222** [comment]
需求2： 表格 行的 Hover状态 给个开关。

**Comment by 07akioni** [comment]
hover 状态可以用 themeOverrides 把表格行 hover color 设为纯白

**Comment by gowy222** [comment]
@07akioni 您好, rowProps 能拿到数据，但是 click事件怎么设置? 现在的情况是 滚动的时候会触发rowProps 绑定的事件，没有找到click/dbclick的回调接口。其实主要是想用 row-dbclick，有些操作需要区分 单击还是双击

**Comment by gowy222** [comment]
另外 hover 状态 改颜色这个有点伪科学了，底层还是会触发浏览器CC层渲染机制。浪费cpu.... 要不，还是给个开关吧..

**Comment by 07akioni** [comment]
> 另外 hover 状态 改颜色这个有点伪科学了，底层还是会触发浏览器CC层渲染机制。浪费cpu.... 要不，还是给个开关吧..

这个不会对性能任何可观测的影响

**Comment by 07akioni** [comment]
> @07akioni 您好, rowProps 能拿到数据，但是 click事件怎么设置? 现在的情况是 滚动的时候会触发rowProps 绑定的事件，没有找到click/dbclick的回调接口。其实主要是想用 row-dbclick，有些操作需要区分 单击还是双击

滚动的时候不应该触发什么特殊的事件，有的话可以提一个 issue。

rowProps 可以写 { onDblclick: e => {} }
