### ISSUE TITLE
Boolean values are not displayed in Data Table

### ISSUE THREAD

**Issue by franknate** [TuSimple/naive-ui#3114]
### TuSimple/naive-ui version (版本)
2.30.4

### Vue version (Vue 版本)
3.2.36

### Browser and its version (浏览器及其版本)
Firefox(101.0.1)

### System and its version (系统及其版本)
Ubuntu 22.04

### Reappearance link (重现链接)
https://codesandbox.io/s/gracious-saha-y1ek6o

### Reappearance steps (重现步骤)
After opening the link it's visible that the boolean values in the Loved column are invisible.

### Expected results (期望的结果)
I expect to see the boolean values in the Data Table.

### Actual results (实际的结果)
Boolean values are not visible in the Data Table.

### Remarks (补充说明)
It looks the same for Date values.

**Comment by Sepush** [comment]
The reason is in JSX Booleans, Null, and Undefined Are Ignored.
If you want to render Boolean value you can map your data cast them from Boolean to String

**Comment by 07akioni** [comment]
Naive follows vue's `h`'s behavior in JS layer, not `template` rendering behavior. So it's expected.
