### ISSUE TITLE
want to control theme use var() in the :root rather than in each dom

### ISSUE THREAD

**Issue by xxholly32** [TuSimple/naive-ui#312]
### This function solves the problem (这个功能解决的问题)
there is too many style var in each dom and can`t change common var in the :root, I think this is very bad for rendering performance

![image](https://user-images.githubusercontent.com/6063358/123568149-4e44f200-d7f6-11eb-9328-efc2a8745370.png)

![image](https://user-images.githubusercontent.com/6063358/123568387-cf03ee00-d7f6-11eb-8ee4-388a257ff880.png)

### Expected API (期望的 API)
no use n-config-provider to force to control themes or provider useNaiveTheme to change :root var

like  https://vueuse.org/core/usedark/#usedark

In most cases, i will also encapsulate a `useTheme` to control the global style (changing the root element's var), rather than changing the n-config-provider individually. 

for example about dark my code 

```
<template>
  <n-config-provider :theme="isDark ? darkTheme : undefined">
    <router-view />
  </n-config-provider>
</template>

<script setup lang="ts">
import { darkTheme } from "naive-ui"
import { isDark } from "~/hooks"
</script>
```

but i want to control in the button click to change root style (add class="dark" in the root)

**Comment by Fnzero** [comment]
You can use `theme-overrides` to change

**Comment by xxholly32** [comment]
i know, but i still think its not a good idea. or dont add somany vars in each dom.

**Comment by 07akioni** [comment]
> i know, but i still think its not a good idea. or dont add somany vars in each dom.

We have tried, performance is terrible.
