### ISSUE TITLE
tree 支持点击标题展开和手风琴功能

### ISSUE THREAD

**Issue by muchenfine** [TuSimple/naive-ui#3129]
### This function solves the problem (这个功能解决的问题)
tree 支持点击标题展开和手风琴功能
### Expected API (期望的 API)
tree 支持点击标题展开和手风琴功能

**Comment by syhITMAN** [comment]
> > 可以自己写一个吗
> 
> 自己写理论上肯定是可以的，可能不会很好写



> > 可以自己写一个吗
> 
> 自己写理论上肯定是可以的，可能不会很好写

你们有计划加上这个功能吗

**Comment by 07akioni** [comment]
> > > 可以自己写一个吗
> > 
> > 
> > 自己写理论上肯定是可以的，可能不会很好写
> 
> > > 可以自己写一个吗
> > 
> > 
> > 自己写理论上肯定是可以的，可能不会很好写
> 
> 你们有计划加上这个功能吗

加了，之后的版本会上
