### ISSUE TITLE
NTabs 组件出现警告提示 'Slot "default" invoked outside of the render function'

### ISSUE THREAD

**Issue by angeltxwh** [TuSimple/naive-ui#3134]
### TuSimple/naive-ui version (版本)
2.30.4

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
102.0.5005.115

### System and its version (系统及其版本)
Windows 11

### Reappearance link (重现链接)
暂无

### Reappearance steps (重现步骤)
```
import {  defineComponent, h } from "vue";
import { NTabPane, NTabs } from "naive-ui";

export default defineComponent({
	render() {
		return [
			h(NTabs, { type: "line", animated: true }, () => {
				return h(NTabPane, { name: "base", tab: "基础信息" }, () => [])
			}),
			h(NTabs, { type: "line", animated: true }, () => [
				h(NTabPane, { name: "base", tab: "基础信息" }, () => [])
			]),
			h(NTabs, { type: "line", animated: true }, {
				default: () => h(NTabPane, { name: "base", tab: "基础信息" }, () => [])
			}),

		]
	},
})
```

### Expected results (期望的结果)
不报错就好

### Actual results (实际的结果)
```
[Vue warn]: Slot "default" invoked outside of the render function: this will not track dependencies used in the slot. Invoke the slot function inside the render function instead. 
setup	@	Tabs.js:56
```

### Remarks (补充说明)
我是用ts文件写的VUE组件，搜了issue发现有人提了同样的问题但是被归咎为他的使用方式有问题。但是我觉着这个问题是真的存在的， 我上面用各种写法试了一下，他都会报警告的。

**Comment by 07akioni** [comment]
你可以加一个 defaultValue

**Comment by 07akioni** [comment]
会改一下文档

**Comment by angeltxwh** [comment]
@07akioni 好的，谢谢老板

**Comment by coader** [comment]
这个问题如何解决的 我用 ()=>... 或 {default:()=>...}都不行

**Comment by coader** [comment]
哦  加了个defaultValue的属性指定

**Comment by 07akioni** [comment]
> 哦 加了个defaultValue的属性指定

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/18677354/179405871-2954a419-8488-4f24-9926-8f1c9acf7ee3.png">
