### ISSUE TITLE
建议把Data Table组件重构一下

### ISSUE THREAD

**Issue by long5635152** [TuSimple/naive-ui#3143]
### This function solves the problem (这个功能解决的问题)
这个表格是我用过的最难用的表格，1.表格里想放一些元素，必须写h函数来渲染，如果放的东西复杂就是灾难。2.表格每个数据行的宽度不能定义，目前只能根据数据的长度自动调整；3.无法通过参数定义表格的各个颜色；4.各种点击事件不支持
### Expected API (期望的 API)
建议把Data Table组件重构一下

**Comment by binghc** [comment]
table 有个大bug 设置了固定表头maxHeight，水平滚动条不显示，导致table数据显示不全

**Comment by 07akioni** [comment]
1. 可以通过封装组件避免
2. 宽度可以用 col width
3. cell-props 可以定义表格的颜色
4. row-props 可以定义组件的任意行属性，包括所有 DOM 事件

**Comment by 07akioni** [comment]
> table 有个大bug 设置了固定表头maxHeight，水平滚动条不显示，导致table数据显示不全

能给个复现吗？

**Comment by cnki-zan** [comment]
> > table 有个大bug 设置了固定表头maxHeight，水平滚动条不显示，导致table数据显示不全
> 
> 能给个复现吗？

设置了maxheigh后，横向滚动条就消失了
                    <data-table-extend :columns="columnList" :data="tableData" 
                    :key="tableData"
                     max-height="500"
                    :render-cell="renderCell" 
                    v-model:checked-row-keys="checkList" ></data-table-extend>
去掉maxheight后正常显示滚动条
![Uploading snipaste_20240104_104129.png…]()
