### ISSUE TITLE
NDropdown on-select 在 volar 插件 报类型不一致

### ISSUE THREAD

**Issue by Lanseria** [TuSimple/naive-ui#315]
### TuSimple/naive-ui version (版本)
2.14.0

### Vue version (Vue 版本)
3.1.2

### Browser and its version (浏览器及其版本)
Edge

### System and its version (系统及其版本)
windows10

### Node version (Node 版本)
14

### Reappearance link (重现链接)
https://github.com/TuSimple/naive-ui/blob/main/src/dropdown/src/Dropdown.tsx#L94

### Reappearance steps (重现步骤)
volar 插件下会报错, 但不影响开发
文档里类型与实际类型不匹配
https://www.naiveui.com/zh-CN/os-theme/components/dropdown
```
on-select | (key: string \| number) => void | undefined | select 选中时触发的回调函数
```
但类型定义的是
https://github.com/TuSimple/naive-ui/blob/main/src/dropdown/src/Dropdown.tsx#L94
```
onSelect: [Function, Array] as PropType<MaybeArray<OnUpdateValue>>,
```
![image](https://user-images.githubusercontent.com/14802764/123611837-95ea6e80-d834-11eb-8222-fa1baedf7d9f.png)

### Expected results (期望的结果)
类型对应上

### Actual results (实际的结果)
类型没有对应

**Comment by 07akioni** [comment]
这看起来是 volar 的 bug，可以去 volar 提一个。
我们内部的类型没有 (payload: xxx 这部分。

**Comment by 07akioni** [comment]
ref https://github.com/johnsoncodehk/volar/issues/266
