### ISSUE TITLE
n-dropdown 能不能加一个异步加载的功能？就像n-cascader的异步一样

### ISSUE THREAD

**Issue by BarrySJL** [TuSimple/naive-ui#3151]
### This function solves the problem (这个功能解决的问题)
如题，功能和n-cascader的异步差不多
https://www.naiveui.com/zh-CN/dark/components/cascader#single-lazy.vue
### Expected API (期望的 API)
remote 属性 和 n-cascader的一样

**Comment by 07akioni** [comment]
不会加，这就是个下拉菜单而已。

这种用法不符合我们对功能的预期。
