### ISSUE TITLE
table 自定义渲染(render)函数中的index值

### ISSUE THREAD

**Issue by kkfive** [TuSimple/naive-ui#3153]
### TuSimple/naive-ui version (版本)
2.30.5

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Microsoft Edge 102.0.1245.44 (正式版本) (64 位)

### System and its version (系统及其版本)
Windows10

### Reappearance link (重现链接)
https://codesandbox.io/s/gallant-euclid-99tywy?file=/src/Demo.vue

### Reappearance steps (重现步骤)
我试图通过render函数中返回的第二个参数做索引列，但是当我使用展开时(`renderExpand`)，传递的索引与预期不符合

### Expected results (期望的结果)
点击展开在`render`函数中传递的索引为当前行索引，而不是随着展开与关闭而变化

### Actual results (实际的结果)
`render`函数中传递的索引会随着展开与关闭

**Comment by 07akioni** [comment]
当成一个 feature request 优化吧，之前给 index 的时候就把展开的也考虑进去了，这么处理确实会给用户带来一些困扰

**Comment by wangjinku** [comment]
在n-table-data中的树型数据中。期望 展开行可以计入 render 的 index 内 @kkfive

**Comment by wangjinku** [comment]
在n-table-data中的树型数据中。期望 展开行可以计入 render 的 index 内 @XieZongChen

**Comment by wangjinku** [comment]
在n-table-data中的树型数据中。期望 展开行可以计入 render 的 index 内 @XieZongChen 
![Uploading _20240220101604.png…]()
