### ISSUE TITLE
n-time-picker回显问题

### ISSUE THREAD

**Issue by PZ-18664918826** [TuSimple/naive-ui#3158]
### This function solves the problem (这个功能解决的问题)
v-model:value  回显只能通过时间戳回显，又不知道n-time-picker时间戳的转换规则，只能通过用户选择了时间 通过@update:value事件获取到时间戳 存到后台 在返回前端进行回显
### Expected API (期望的 API)
希望v-model:value能通过字符串进行回显 列如  '04:06'

**Comment by 07akioni** [comment]
v-model:formatted-value
