### ISSUE TITLE
NTabs 组件自定义插槽‘default’类型定义好像有问题？

### ISSUE THREAD

**Issue by angeltxwh** [TuSimple/naive-ui#3161]
### TuSimple/naive-ui version (版本)
2.30.4

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
102.0.5005.115

### System and its version (系统及其版本)
Windows 11

### Reappearance link (重现链接)
暂无

### Reappearance steps (重现步骤)
```
h(NDynamicInput, { ...vmodel(this.record.state, 'preparation_content'), "on-create": () => { return { name: null, quantity: null } } },
	{
		default: (options) => { }
	}
)
```

上面这个写法是可以的，但是换成下面这个写法就会报重载错误

```
h(NDynamicInput, { ...vmodel(this.record.state, 'preparation_content'), "on-create": () => { return { name: null, quantity: null } } },
	(options) => {
		console.log(options);
	}
)
```

### Expected results (期望的结果)
希望下面那种写法也能得到类型支持

### Actual results (实际的结果)
TS重载错误

**Comment by amadeus711** [comment]
这是 vue 的 h 函数的用法问题，h 函数第三个参数接收 slots。 vue 规定使用 h 函数的 slots 必须具名。
