### ISSUE TITLE
希望tree组件新增横向排列

### ISSUE THREAD

**Issue by yunlongduan** [TuSimple/naive-ui#3162]
### This function solves the problem (这个功能解决的问题)
我们在开发中，可能会遇到树形组件最后一列进行横向排列的情况。
### Expected API (期望的 API)
希望新增一个属性或方法可以为.n-tree-node-wrapper节点动态添加class属性。

**Comment by 07akioni** [comment]
用 node-props 可以增加 class

**Comment by yunlongduan** [comment]
node-props的属性没法新增到class="n-tree-node-wrapper"所在节点上

**Comment by yunlongduan** [comment]
@07akioni node-props的属性没法新增到class="n-tree-node-wrapper"所在节点上

**Comment by 07akioni** [comment]
wrapper 的样式要不考虑一下直接 css 覆盖？感觉没有必要针对每个节点单独调整吧

**Comment by yunlongduan** [comment]
@07akioni 这边有考虑过，但是直接覆盖难以实现
![image](https://user-images.githubusercontent.com/33390554/176571798-0f342f38-b0e7-4f47-89e3-81f39e26663a.png)
这种效果。

**Comment by 07akioni** [comment]
> @07akioni 这边有考虑过，但是直接覆盖难以实现 ![image](https://user-images.githubusercontent.com/33390554/176571798-0f342f38-b0e7-4f47-89e3-81f39e26663a.png) 这种效果。

不太会考虑这种用例
