### ISSUE TITLE
希望inputnumber组件step功能扩展一种显示模式

### ISSUE THREAD

**Issue by dean16930** [TuSimple/naive-ui#3170]
### This function solves the problem (这个功能解决的问题)
step按钮模式除了现有的左右按钮显示模式外，能扩展新增常见的上下内嵌step按钮模式
### Expected API (期望的 API)
参数名：mode（props）
描述：模式（embed：按钮内嵌模式，button：左右按钮模式）
类型：'embed' | 'button'
默认值：'embed'

**Comment by nooooooom** [comment]
内嵌是什么样的表现形式，目前按钮是支持[设置放右边或者两边的](https://www.naiveui.com/zh-CN/os-theme/components/input-number#button-placement.vue)

**Comment by 07akioni** [comment]
不搞，写起来太麻烦了，也没什么收益
