### ISSUE TITLE
抽屉组件 showMask 设置 transparent 后出现报警信息

### ISSUE THREAD

**Issue by lhf6623** [TuSimple/naive-ui#3172]
### TuSimple/naive-ui version (版本)
2.30.6

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Microsoft Edge(版本 102.0.1245.44 (正式版本) (64 位))

### System and its version (系统及其版本)
windows 10

### Reappearance link (重现链接)
https://codesandbox.io/s/lingering-sound-kpu9m1?file=/src/Demo.vue

### Reappearance steps (重现步骤)
打开控制台，然后点击显示/隐藏抽屉

### Expected results (期望的结果)
消除报警信息

### Actual results (实际的结果)
Invalid prop: type check failed for prop "showMask". Expected Boolean, got String with value "transparent". 
  at <NDrawerContent class="" style=

**Comment by lhf6623** [comment]
![image](https://user-images.githubusercontent.com/29174474/175482961-1c175479-493e-4d6c-bfb0-8f94b6bfa953.png)

**Comment by lhf6623** [comment]
演示地址挂了。。。看图片就可以复现

**Comment by amadeus711** [comment]
wait: https://github.com/vuejs/core/issues/6178
