### ISSUE TITLE
穿梭框如何自定义高度,宽度.

### ISSUE THREAD

**Issue by XTeam-Wing** [TuSimple/naive-ui#3177]
### This function solves the problem (这个功能解决的问题)
穿梭框如何自定义高度,宽度.默认的尺寸太小了.
### Expected API (期望的 API)
None

**Comment by Sepush** [comment]
use `style` 
eg. `style="width:600px"`

**Comment by XTeam-Wing** [comment]
我是直接改源码了. style不生效.

**Comment by XTeam-Wing** [comment]
高度我测试好像不行呀.

**Comment by Sepush** [comment]
> 高度我测试好像不行呀.

![image](https://user-images.githubusercontent.com/39197136/175798588-5f5d35bd-6cc1-4600-829a-34184668a059.png)
