### ISSUE TITLE
custom component attrs

### ISSUE THREAD

**Issue by canvascat** [TuSimple/naive-ui#318]
### This function solves the problem (这个功能解决的问题)
for example, custom component style...
### Expected API (期望的 API)
want custom attrs to override default attrs instead of being overridden by default attrs.

for dropdown:
```html
  <n-dropdown @select="handleSelect" trigger="click" :options="options" style="--option-height: 50px;">
    <n-button :keyboard="false">点击！</n-button>
  </n-dropdown>
```
but this doesn’t modify the option height.

https://github.com/TuSimple/naive-ui/blob/6433a0d783878877c34d90e6125423851960889b/src/dropdown/src/Dropdown.tsx#L387
I suggest `$attrs` to override `props`:
```ts
mergeProps(dropdownProps, this.$attrs) as typeof dropdownProps
```
and other places...
https://github.com/TuSimple/naive-ui/blob/e5d640f4d74ff43e24c9be8f6198f6c238c8c6d7/src/icon/src/Icon.ts#L75

**Comment by amadeus711** [comment]
This proposal needs to be discussed, but you can try to use deep for style overlay, like:
```css
:deep(.n-dropdown-option) {
  height: 50px;
}
```

**Comment by canvascat** [comment]
And for some components, such as NButton:
```html
<n-button color="#ddd" style="--text-color: #000;">
    <template #icon><n-icon><cash-outline /></n-icon></template>
    #ccc
</n-button>
```
I can customize the button text color by modifying `--text-color`. It's best that they behave consistently.

In addition, I think I should think about the reasons for naive-ui extensive use of custom-property-name.

**Comment by amadeus711** [comment]
If you need to modify the style of components, we suggest that you use the Customizing Theme, which you can see on the https://www.naiveui.com/en-US/os-theme/docs/customize-theme , We use a lot of custom-property-name to make it easier for users to customize the theme.

**Comment by 07akioni** [comment]
1. Theme variables exist in JS level, we won't keep css interface stable
2. We won't put $attrs after props in most case, since we don't want user to break components' builtin functionality.
