### ISSUE TITLE
n-config-provider theme-overrides部分不生效

### ISSUE THREAD

**Issue by Charl0tter** [TuSimple/naive-ui#3180]
### TuSimple/naive-ui version (版本)
2.30.6

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
Windows 11

### Reappearance link (重现链接)
https://codepen.io/charl0tter/pen/NWyQZvw?editors=1111

### Reappearance steps (重现步骤)
打开重现链接，n-config-provider配置theme，Button.textColorHover不生效，打开调试工具--n-text-color-hover与--n-text-color相同。第二个Button设置行内样式style="--n-text-color-hover: #ffffff;"生效

### Expected results (期望的结果)
正确匹配theme

### Actual results (实际的结果)
部分不生效

**Comment by 07akioni** [comment]
button 这事情比较复杂，textColorHover 只会对特定的类型生效。某些类型的颜色是有一些逻辑联系的，所以做不到每一个都能独立的配置。

因为 button 的属性特别多，想要做到全部可配置可能属性需要上千个（直接按照几何级数增长）。

目前还没找到特别好的方法，这个问题当前是无解的。
