### ISSUE TITLE
打开Drawer的情况下，在打开一个自定义的Modal，Modal内的输入框可以获得焦点但是无法输入内容

### ISSUE THREAD

**Issue by Charl0tter** [TuSimple/naive-ui#3181]
### TuSimple/naive-ui version (版本)
2.30.6

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
Windows 11

### Reappearance link (重现链接)
https://codepen.io/charl0tter/pen/rNJXEQg?editors=1111

### Reappearance steps (重现步骤)
打开重现链接，直接打开Modal，弹出的输入框可以正常输入内容。先打开一个Drawer后，再打开Modal，Modal内输入框无法输入内容

### Expected results (期望的结果)
可以正常在弹窗内输入内容

### Actual results (实际的结果)
弹窗内Input无法输入

**Comment by jizai1125** [comment]
![image](https://user-images.githubusercontent.com/33979706/175799287-8783e204-e951-47e3-81d2-2804bed55cd8.png)

![image](https://user-images.githubusercontent.com/33979706/175799283-2d43a009-ccd7-4bfb-8748-95873e651121.png)

我发现把 vuec 加上的 aria div 删掉就能输入了，但是不清楚原因啊😂

**Comment by 07akioni** [comment]
你可以把 trap focus 设为 false。

非 naive 的 drawer 没有纳入 naive 的焦点管理，这导致一些行为不符合预期，modal 的焦点管理是个比较复杂的事情。

**Comment by wcnhna** [comment]
I think the default value of 'trap-focus' should be set to false.
