### ISSUE TITLE
modal组件嵌入form表单 在打开时会出现一瞬间的高度错误

### ISSUE THREAD

**Issue by pya789** [TuSimple/naive-ui#3184]
### TuSimple/naive-ui version (版本)
2.30.6

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
89.04

### System and its version (系统及其版本)
windows10

### Reappearance link (重现链接)
https://codesandbox.io/s/suspicious-booth-3v169w?file=/src/Demo.vue

### Reappearance steps (重现步骤)
https://codesandbox.io/s/suspicious-booth-3v169w?file=/src/Demo.vue
点击打开

### Expected results (期望的结果)
 modal开启和结束时元素无抖动

### Actual results (实际的结果)
modal开启和结束时可以明显看到元素的抖动

**Comment by 07akioni** [comment]
有录屏吗

https://user-images.githubusercontent.com/18677354/175821761-75198827-bfea-49ff-b23e-e0109c533abb.mov

**Comment by 07akioni** [comment]
我自己是没能复现的

**Comment by pya789** [comment]
> 有录屏吗
> 
>  2022-06-26.11.32.25.mov


https://user-images.githubusercontent.com/12424245/175845072-791e95d6-0b1c-45d0-a9b1-3c0e04c32bca.mp4


https://user-images.githubusercontent.com/12424245/175845094-8e2c6cd8-013a-405c-91ae-2b5ebd16ed01.mp4

注意打开modal完全展开的一瞬间  input的label和input本身的高度还有按钮高度 modal整体高度都会有1-2个像素的变化 
card边框设定为false时正常 但placeholder会下移一下

**Comment by 07akioni** [comment]
应该不是说实现有什么 bug 之类的

**Comment by pya789** [comment]
> 这种类似的偏移我看过，应该是浏览器自己导致的，本身无解

好吧 Thanks♪(･ω･)ﾉ
