### ISSUE TITLE
input 添加格式化功能

### ISSUE THREAD

**Issue by muchenfine** [TuSimple/naive-ui#3194]
### This function solves the problem (这个功能解决的问题)
input 添加格式化功能
![图片](https://user-images.githubusercontent.com/94693483/175888197-ed6a8506-d580-4de5-9908-da90693c6c69.png)

### Expected API (期望的 API)
input 添加格式化功能

**Comment by 07akioni** [comment]
看不出这个功能有啥用啊，用 prefix 和 suffix slot 就解决了

**Comment by 07akioni** [comment]
如果有非他不可的用例倒是可以考虑

**Comment by 07akioni** [comment]
先关了，主要是感觉确实没啥用
