### ISSUE TITLE
Form表单重置失效

### ISSUE THREAD

**Issue by Wlisfes** [TuSimple/naive-ui#3205]
### TuSimple/naive-ui version (版本)
2.30.6

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Chrome(102.0.5005.115)

### System and its version (系统及其版本)
Windows10

### Node version (Node 版本)
v14.12.0

### Reappearance link (重现链接)
https://codesandbox.io/s/exciting-leaf-10zr8s?file=/src/App.vue

### Reappearance steps (重现步骤)
1. 表单有默认值，点击重置按钮赋值为undefined可以重置成功，值会发生改变页面也会相应的变化
2. 表单手动输入值后，点击重置按钮赋值为undefined重置成功、值会发生改变页面不会变化

### Expected results (期望的结果)
重置表单字段值为undefined后界面上也会相应的清除

### Actual results (实际的结果)
重置表单字段值为undefined，重置成功后界面未发生变化

**Comment by 07akioni** [comment]
undefined 不会对组件的值有影响，只会让组件认为你什么都没传，然后恢复到非受控模式。

如果需要恢复你应该使用 null 或者其他空值。

**Comment by Wlisfes** [comment]
如果不能传递undefined，那fn的可选参数就必须要加上null类型, fn(xxx?: number)这种写法完全就无法通过

![微信截图_20220629140422](https://user-images.githubusercontent.com/32263302/176363645-d66bd312-aac3-49f7-869e-e54226b7ecf8.png)
![微信截图_20220629140433](https://user-images.githubusercontent.com/32263302/176363675-4dd5fec9-0f2b-4a3a-b49d-b131b91facd9.png)

**Comment by 07akioni** [comment]
```
status: status ?? null,
type: type ?? null
```

**Comment by Wlisfes** [comment]
我妥协了  改成了这种写法

![微信截图_20220630100702](https://user-images.githubusercontent.com/32263302/176577455-6627fdd2-ada3-4d7e-b643-eb8dbf6959b7.png)

**Comment by wcldyx** [comment]
> 我妥协了 改成了这种写法
> 
> ![微信截图_20220630100702](https://user-images.githubusercontent.com/32263302/176577455-6627fdd2-ada3-4d7e-b643-eb8dbf6959b7.png)

我也妥协了，本来在typescript一个"?"就能解决的事，表示无或者有值两个类型。现在还要声明 null 且要赋值 null。
