### ISSUE TITLE
Nuxt transpiling causes impossible development workflow

### ISSUE THREAD

**Issue by gijsroge** [TuSimple/naive-ui#3212]
### TuSimple/naive-ui version (版本)
2.30.8

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
103.0.5060.53

### System and its version (系统及其版本)
12.3

### Node version (Node 版本)
v16.15.1

### Reappearance link (重现链接)
https://github.com/07akioni/naive-ui-nuxt-demo (the official demo repo)

### Reappearance steps (重现步骤)
Run `yarn dev` and when the application loads you can see the amount of work Nuxt has to do to transpile all these modules. (see network tab, 2-3k requests) This happens on startup and on HMR.

### Expected results (期望的结果)
Maybe that we do not need to transpile all the modules? But my knowledge is limited about this topic.

https://v3.nuxtjs.org/guide/going-further/esm/#library-author-guide 

### Actual results (实际的结果)
Nuxt is transpiling all these single js files. Causing an impossible dev workflow. My chrome tab freezes for like 5-10 seconds causing all my fans to spin at 100% 😅 

### Remarks (补充说明)
I followed the docs https://www.naiveui.com/en-US/os-theme/docs/ssr

**Comment by 07akioni** [comment]
> This is a big issue! Could someone look into this?

I'll look into it.

**Comment by 07akioni** [comment]
@gijsroge See latest demo repo, I've updated nuxt config.
