### ISSUE TITLE
日期季度范围选择器第二列为Q1,Q2,Q3,Q4

### ISSUE THREAD

**Issue by yanbowe** [TuSimple/naive-ui#3217]
### This function solves the problem (这个功能解决的问题)
希望与季度选择器保持一致
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/43030980/176813373-cba9de89-67b8-476a-921e-138336a98bba.png">

### Expected API (期望的 API)
文案修改

**Comment by Sepush** [comment]
这是国际化的

**Comment by lucky-mouse-14** [comment]
> 这是国际化的
![123](https://user-images.githubusercontent.com/8285267/224926314-dc4593e4-e75b-4e9b-b235-7376f3ba3c22.png)
写死Q，没有设置国际化

**Comment by lucky-mouse-14** [comment]
> 这是国际化的
![123](https://user-images.githubusercontent.com/8285267/224927399-1c8ff04b-868c-45c9-a7b9-28ba0db70e68.png)
写死Q，没有设置国际化
