### ISSUE TITLE
Improve the theme configuration document

### ISSUE THREAD

**Issue by TuiMao233** [TuSimple/naive-ui#322]
### This function solves the problem (这个功能解决的问题)
I don’t know what effect can be set to achieve the effect I want, or I don’t know which one can be configured to set css variables
![}(9}(`SRH GH 8I@YRT H0L](https://user-images.githubusercontent.com/49724027/123728008-2d979d80-d8c5-11eb-9126-c870118cf3f4.png)
![WX96Z N$DF9G}8 HCCF(50O](https://user-images.githubusercontent.com/49724027/123728017-2ff9f780-d8c5-11eb-8c6a-f9709a4b32c6.png)

### Expected API (期望的 API)
~~~json
{
  "common": {
    "primaryColor": "--color",
    "hoverColor": "..."
  }
  ...
}
~~~

**Comment by Fnzero** [comment]
You can check the theme configuration in the lower right corner.
![image](https://user-images.githubusercontent.com/28534224/123729691-faa2d900-d8c7-11eb-979d-e9dee2d4c20f.png)

**Comment by transtone** [comment]
有这些个属性，机器人也不正面回复。改变主题色至少需要改下面三个变量。

```js
const themeOverrides = {
  common: {
    primaryColor:  "--color",
    primaryColorHover:  "--color",
    primaryColorPressed:  "--color",
  },
}
```

**Comment by 07akioni** [comment]
> 有这些个属性，机器人也不正面回复。你给的图片的红框框里已经标明了。 改变主题色需要改下面几个变量。
> 
> ```js
> const themeOverrides = {
>   common: {
>     primaryColor:  "--color",
>     primaryColorHover:  "--color",
>     primaryColorPressed:  "--color",
>     primaryColorFocus:  "--color",
>   },
> }
> ```

可能理解错了问题是啥，一般情况如果觉得没被解答还是可以继续问的，我们有时候处理不过来
