### ISSUE TITLE
使用Cascader的filterable时 check-strategy="child"搜索出来的结果只有最后一级

### ISSUE THREAD

**Issue by lhp0730** [TuSimple/naive-ui#3220]
### This function solves the problem (这个功能解决的问题)
搜索出来的最后一级不知道他们的父级是什么，容易选择错误
### Expected API (期望的 API)
支持展示目标的父级，

**Comment by lhp0730** [comment]
![image](https://user-images.githubusercontent.com/51940708/176983215-4c56d999-3dc9-4f2e-9e9a-3b848b8f969f.png)

**Comment by binghc** [comment]
用户体验非常差的bug：select组件展示大量options，使用鼠标滚轮时，只能滚动一页，无论滚轮怎么滚options都不下滑，只有鼠标动一下位置才能继续滚动一页，然后又被卡死滚不动

**Comment by binghc** [comment]
cascader存在同样问题，版本重2.30.2升级到最新2.30.8 问题依旧

**Comment by 07akioni** [comment]
> ptions，使用鼠标滚轮时，只能滚动一页，无论滚轮怎么滚options都不下滑，只有鼠标动一下位置才能继续滚动一页，然后又被卡

可以提一个 issue，感觉和特定的系统或者浏览器版本有关

**Comment by lhp0730** [comment]
搜索结果展示不出来全路径吗。使用check-strategy=child的时候？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年07月02日 23:36 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [TuSimple/naive-ui] 使用Cascader的filterable时 check-strategy="child"搜索出来的结果只有最后一级 (Issue #3220) |

ptions，使用鼠标滚轮时，只能滚动一页，无论滚轮怎么滚options都不下滑，只有鼠标动一下位置才能继续滚动一页，然后又被卡

可以提一个 issue，感觉和特定的系统或者浏览器版本有关
