### ISSUE TITLE
轮播图内交互区域覆盖导致触发错误的可点击元素（仅fade渐变过渡）

### ISSUE THREAD

**Issue by CV-souryu** [TuSimple/naive-ui#3227]
### TuSimple/naive-ui version (版本)
2.30.8

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
火狐100   |  谷歌100 

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://github.com/Genshin-Impact-Cult-of-Noelle/Noelle-Nuxt3-SLS/tree/NUIBUG

### Reappearance steps (重现步骤)
yarn
yarn dev
打开首页，滚轮翻到第二屏，左边的视频播放连接永远是轮播图中最后一项的链接
底部5个字是控制轮播图的切换

### Expected results (期望的结果)
视频播放链接应符合V-For预期，暨每一页的播放按钮都是不同的URL，这个预期结果在删除effect="fade"时是生效的

### Actual results (实际的结果)
在轮播图的每一项的固定未知放入可交互a标签，似乎永远指向的是轮播图最后一个的a标签

### Remarks (补充说明)
在使用F12选取页面元素时，永远的指向的最后一个轮播图项目

**Comment by nooooooom** [comment]
> @nooooooom

我瞅瞅
