### ISSUE TITLE
为countdown倒计时组件添加重置方法

### ISSUE THREAD

**Issue by Danjuanlab** [TuSimple/naive-ui#3228]
### This function solves the problem (这个功能解决的问题)
当前版本的倒计时插件只能运行一次到finish触发,没有重置倒计时的方法。
### Expected API (期望的 API)
在处理客户端账号在注册时，往往会使用发送手机短信验证码。这个发送的按钮会强制60S的非可用，并显示倒数时间。所以可能存在需要重复发送验证码的场景。所以需要为倒计时组件添加一个重置的方法。

**Comment by 07akioni** [comment]
合理
