### ISSUE TITLE
Bulky sorter for data table

### ISSUE THREAD

**Issue by zhouzilong2020** [TuSimple/naive-ui#3233]
### This function solves the problem (这个功能解决的问题)
In the data table, we can specify the row span prop to collapse rows into a single one. Since Naive-UI does NOT provide any rule for collapsing rows, we must calculate the row span and carefully organize the order of the data in advance.  (e.g., row type A is always above row type B, so A1's row span should be 2, and A2's row span should also be 2...)
But this dedicated rule is broken when we try to sort the data table. 
The desired behavior is to specify a representative row, just like the tree, but with all rows at the same level.
When we try to sort the table, we first sort the representative rows, and its containing rows remain in the same order following it.
### Expected API (期望的 API)
Some possible solutions:
1. Just like tree-table, but show them on the same level. Some UI refraction is needed.
2. Add a new prop for collapsing rows. All the rows with the same key would be rendered within a block, and we can further specify the row's order within that block. (e.g., A1, B1, and C1 are within the same block, and the desired order is alphabetical order.)

**Comment by 07akioni** [comment]
I think we won't implement the feature since it is too specific. If you need it heavy customization is needed. It doesn't follows data model of data table.

If you really need it, I think the only possible way is to use `remote` prop and controll all data by yourself.
