### ISSUE TITLE
form select verify bug

### ISSUE THREAD

**Issue by fengzibo** [TuSimple/naive-ui#3236]
### TuSimple/naive-ui version (版本)
2.30.8

### Vue version (Vue 版本)
3.2.36

### Browser and its version (浏览器及其版本)
Chrome( 102.0.5005.115)

### System and its version (系统及其版本)
win 10

### Reappearance link (重现链接)
https://codesandbox.io/s/laughing-jackson-kolke1?file=/src/Demo.vue

### Reappearance steps (重现步骤)
Click Select to select the value and the validation information appears
（点击select选择值会出现验证信息）

### Expected results (期望的结果)
Verify normal function
（验证功能正常）

### Actual results (实际的结果)
If yes, the authentication information is displayed, but the authentication fails
（有值也会显示验证信息，且验证不通过）

### Remarks (补充说明)
If the value in generalOptions is toString(), the verification function is normal 
（如果将generalOptions中的value值toString(),则验证功能正常）

**Comment by timeTravelCYN** [comment]
@fengzibo 
需要添加 `type` 属性
```javascript
num: {
  type: 'number',
  required: true,
  message: "请选择数值",
  trigger: ["change", "blur"],
}
```
[async-validator](https://github.com/yiminghe/async-validator#type) `type` 默认为 `string`
