### ISSUE TITLE
文档n-layout-sider 缺失api描述expand事件

### ISSUE THREAD

**Issue by wangmiJM** [TuSimple/naive-ui#3239]
### TuSimple/naive-ui version (版本)
2.30.8

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
no

### System and its version (系统及其版本)
no

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/layout

### Reappearance steps (重现步骤)
文档的layout-sider没有描述此api

### Expected results (期望的结果)
希望补充

### Actual results (实际的结果)
文档缺失

**Comment by amadeus711** [comment]
这个事件已废弃，随时可能删除，不建议使用。
