### ISSUE TITLE
关于 #3153 功能修复

### ISSUE THREAD

**Issue by kkfive** [TuSimple/naive-ui#3245]
### TuSimple/naive-ui version (版本)
2.30.8

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
Windows

### Reappearance link (重现链接)
https://codesandbox.io/s/inspiring-gates-tryy7e

### Reappearance steps (重现步骤)
https://github.com/TuSimple/naive-ui/issues/3153

### Expected results (期望的结果)
https://github.com/TuSimple/naive-ui/issues/3153

### Actual results (实际的结果)
https://github.com/TuSimple/naive-ui/issues/3153

### Remarks (补充说明)
我看了当时的[预览文档](https://naive-iudo9rrhl-tusimple.vercel.app/zh-CN/os-theme/components/data-table#expand.vue),可以看到当时确实修复了，但是最新版本文档没有相关内容

**Comment by amadeus711** [comment]
虽然 pr 合并，但还未发版，详情请见 https://github.com/TuSimple/naive-ui/blob/main/CHANGELOG.zh-CN.md
