### ISSUE TITLE
datable横向滚动的问题

### ISSUE THREAD

**Issue by xiaobaichiliangpi** [TuSimple/naive-ui#3248]
### TuSimple/naive-ui version (版本)
2.31.0

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Chrome(89.0.4389.128)

### System and its version (系统及其版本)
MacOS(11.2.3)

### Reappearance link (重现链接)
https://codesandbox.io/s/confident-dewdney-r1ro64?file=/src/Demo.vue

### Reappearance steps (重现步骤)
1. 列比较多的情况下，不设置固定列，未横向滚动条

### Expected results (期望的结果)
在没有固定列的前提下，不需要设置scroll-x也可以出现横向滚动条

### Actual results (实际的结果)
无横向滚动条

### Remarks (补充说明)
场景是列是动态的，而scroll-x需要写死一个值，不符合需求

**Comment by xiaobaichiliangpi** [comment]
目前只能设置列固定，然后动态算scrollx，但是总觉得不够灵活，如果能自动出现横向滚动条就好了。

**Comment by nooooooom** [comment]
@07akioni 要不要给 scrollX 加个 auto 选项，table 的宽度撑不起来 content，外部也不太好监听 table 的实际大小

**Comment by 07akioni** [comment]
> @07akioni 要不要给 scrollX 加个 auto 选项，table 的宽度撑不起来 content，外部也不太好监听 table 的实际大小

这个边界 case 太多了，只可能在没有 y 方向滚动的时候 work，因为还需要同步 header 和 body 的滚动

**Comment by 07akioni** [comment]
> 目前只能设置列固定，然后动态算scrollx，但是总觉得不够灵活，如果能自动出现横向滚动条就好了。

在你的 demo 里面给用 columns 写一个 computed 就好了

```
const scrollXRef = computed(() => columns.value.reduce((v, acc) => acc + v, 0))
```

**Comment by 07akioni** [comment]
> @07akioni 要不要给 scrollX 加个 auto 选项，table 的宽度撑不起来 content，外部也不太好监听 table 的实际大小

如果说每一列都能写好的话给个 scrollX 其实也挺方便的

**Comment by Luxiaochen2015** [comment]
> > [@07akioni](https://github.com/07akioni) 要不要给 scrollX 加个 auto 选项，table 的宽度撑不起来 content，外部也不太好监听 table 的实际大小
> 
> 如果说每一列都能写好的话给个 scrollX 也不会增加什么难度

如果列还有拖拽呢，咋计算，去监听dom的宽度嘛，好麻烦
