### ISSUE TITLE
use tailwind -> reset ,button (background-color) conflict，add<meta name="naive-ui-style" /> invalid

### ISSUE THREAD

**Issue by warmthsea** [TuSimple/naive-ui#3264]
### TuSimple/naive-ui version (版本)
2.31.0

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
last

### System and its version (系统及其版本)
window

### Reappearance link (重现链接)
https://github.com/warmthsea/vitesse-nuxt3

### Reappearance steps (重现步骤)
nuxt3使用useHead添加 naive-ui-style | vueuc-style 未能解决样式冲突
![image](https://user-images.githubusercontent.com/45450994/178139641-48dde682-01b3-4a5d-be99-dccff0030213.png)
![image](https://user-images.githubusercontent.com/45450994/178139650-d8e56a5c-8ae0-4e40-bf04-5a5dc349ad7d.png)

### Expected results (期望的结果)
nuxt3使用useHead添加 naive-ui-style | vueuc-style 后，覆盖tailwind 的reset 

### Actual results (实际的结果)
无覆盖reset 

### Remarks (补充说明)
参看 https://www.naiveui.com/zh-CN/light/docs/style-conflict

**Comment by 07akioni** [comment]
你需要确保 useHead 插入样式的时机比 naive 的组件渲染要更早，不然的话组件 mount 之后样式已经挂上了，再改 head 没有用。

还是写在 HTML 里面最安全。
