### ISSUE TITLE
使用了tailwind 的reset 新增了<meta name="naive-ui-style" />但是按钮样式还是丢失

### ISSUE THREAD

**Issue by warmthsea** [TuSimple/naive-ui#3265]
### TuSimple/naive-ui version (版本)
2.31.0

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
last

### System and its version (系统及其版本)
window

### Reappearance link (重现链接)
https://github.com/warmthsea/vitesse-nuxt3

### Reappearance steps (重现步骤)
nuxt3使用useHead添加 naive-ui-style | vueuc-style 未能解决样式冲突
![image](https://user-images.githubusercontent.com/45450994/178139641-48dde682-01b3-4a5d-be99-dccff0030213.png)
![image](https://user-images.githubusercontent.com/45450994/178139650-d8e56a5c-8ae0-4e40-bf04-5a5dc349ad7d.png)

### Expected results (期望的结果)
nuxt3使用useHead添加 naive-ui-style | vueuc-style 后，覆盖tailwind 的reset 

### Actual results (实际的结果)
无覆盖reset 

### Remarks (补充说明)
参看 https://www.naiveui.com/zh-CN/light/docs/style-conflict

**Comment by wen403** [comment]
请问是怎么解决的

**Comment by Enaium** [comment]
> 请问是怎么解决的

最完美的办法就是关闭taiwind的reset

https://tailwindcss.com/docs/preflight#disabling-preflight

**Comment by czhlin** [comment]
其实保持：1.tailwind 2.naive-ui 3.main.css的顺序是最合理的
所以可以在html中这样修改

In fact, maintaining the order of 1.tailwind 2.naive-ui 3.main.css is the most reasonable, so it can be modified like this in html
```html
<link rel="stylesheet" href="/tailwind.css" />
<meta name="naive-ui-style" />
```
```typescript
// main.ts
import 'uno.css'
import '~/styles/main.css'
````
