### ISSUE TITLE
hope Popover Props “trigger” support contextmenu

### ISSUE THREAD

**Issue by Aaronxjs** [TuSimple/naive-ui#3266]
### This function solves the problem (这个功能解决的问题)
Usually, contextmenu the button to display the information pop-up window in the demand
### Expected API (期望的 API)
element ui Popover

**Comment by Sepush** [comment]
manual-position of dropdown may fit your mental
https://www.naiveui.com/en-US/os-theme/components/dropdown#manual-position.vue

**Comment by 07akioni** [comment]
I think we won't add contextmenu trigger. The feature can be covered by manual position feature.

**Comment by Aaronxjs** [comment]
oh, Thank you for your answer. I see
