### ISSUE TITLE
messageProvider在全屏模式下无法显示

### ISSUE THREAD

**Issue by summerset-zz** [TuSimple/naive-ui#3272]
### TuSimple/naive-ui version (版本)
2.31.0

### Vue version (Vue 版本)
3.2.13

### Browser and its version (浏览器及其版本)
Edge(103.0.1264.49)

### System and its version (系统及其版本)
Windows 11 21H2

### Node version (Node 版本)
16.14.0

### Reappearance link (重现链接)
https://github.com/summerset-zz/bug-reproduce

### Reappearance steps (重现步骤)
在上述重现repo中点击“发消息”可正常显示消息，代码中在切换全屏时也会使用useMessage()发消息。
但在全屏后消息无法显示（虽然正确发出）

### Expected results (期望的结果)
消息应当能在全屏后继续显示

### Actual results (实际的结果)
消息正常发送但没有在全屏后显示。

### Remarks (补充说明)
我看到文档中提供一个:to属性可以指定挂载元素，但是调用useMessage()时通常是在子组件中，在nMessageProvider中指定子元素中的元素比较困难，文档中也缺少相应指导，求教。

**Comment by summerset-zz** [comment]
补充一个代码结构：
```js
//App.vue
<template>
  <n-message-provider>
    <img alt="Vue logo" src="./assets/logo.png" />
    <hello-world msg='123' />
  </n-message-provider>
</template>

<script setup>
import HelloWorld from '@/components/HelloWorld.vue'
import { NMessageProvider } from 'naive-ui';
</script>

```

```js
// Helloworld.vue
<template>
  <div class="hello">
    <p>
      For a guide and recipes on how to configure / customize this project,<br>
      check out the
      <a href="https://cli.vuejs.org" target="_blank" rel="noopener">vue-cli documentation</a>.
    </p>
    <div id="fullscreenContainer">
      <n-space vertical>
        <n-button @click="toggleFullscreen">切换全屏</n-button>
        <n-button @click="sendMessage('测试消息')">发消息</n-button>
      </n-space>
    </div>
  </div>
</template>
<script setup>
import { defineProps } from 'vue'
import { useMessage, NButton, NSpace } from 'naive-ui'
const message = useMessage()
function sendMessage(content) {
  message.info(content)
}
function toggleFullscreen() {
  const fullscreenContainer = document.getElementById('fullscreenContainer')
  if (!document.fullscreenElement) {
    fullscreenContainer.requestFullscreen().then(
      () => {
        // on success
        message.info('已开启全屏')
      },
      () => {
        // on fail
        message.error('全屏开启失败，您的浏览器可能不支持全屏')
      }
    )
  }
  else {
    document.exitFullscreen().then(
      () => {
        // on success
        message.info('已关闭全屏')
      },
      () => {
        // on fail
        message.error('全屏关闭失败。请使用浏览器自带的方法关闭全屏。')
      }
    )
  }
}
</script>
```

**Comment by jizai1125** [comment]
@summerset-zz 你这是让 id 为 fullscreenContainer 的元素全屏吧，但是 Message 容器节点的位置默认在 body，所以才导致看不到；要看得到的话要么你就设置 MessageProvider prop 的 to="#fullscreenContainer"

**Comment by summerset-zz** [comment]
> @summerset-zz 你这是让 id 为 fullscreenContainer 的元素全屏吧，但是 Message 容器节点的位置默认在 body，所以才导致看不到；要看得到的话要么你就设置 MessageProvider prop 的 to="#fullscreenContainer"

感谢，已解决~所以```string | HTMLElement | false```里的string是指selector~

**Comment by 07akioni** [comment]
会考虑直接支持自动寻找全局元素，像是 popover，select 这种之前是专门处理过的
