### ISSUE TITLE
useThemVars function not returning updated theme values 

### ISSUE THREAD

**Issue by elibolonur** [TuSimple/naive-ui#3273]
### TuSimple/naive-ui version (版本)
2.31.0

### Vue version (Vue 版本)
3.2.16

### Browser and its version (浏览器及其版本)
Version 102.0.5005.115 (Official Build) (arm64)

### System and its version (系统及其版本)
MacOS(12.4)

### Node version (Node 版本)
16.15.1

### Reappearance link (重现链接)
https://codesandbox.io/s/billowing-darkness-ks57b6?file=/src/App.vue

### Reappearance steps (重现步骤)
1. Create a file to keep theme customizations e.g. naive-ui.ts
2. Create & Export themeOverrides object in naive-ui.ts, which the object is including common.primaryColor: '#FF0000' customization
3. Import themeOverrides object from naive-ui.ts in a vue file, where it has your NConfigProvider, and use themeOverrides
4. Import useThemeVars from naive-ui and check the primaryColor value

### Expected results (期望的结果)
useThemeVars function should return the updated theme variables, so useThemeVars().value.primaryColor should be equal to '#FF0000'

### Actual results (实际的结果)
useThemeVars function is returning default values and not merging default values with override values. So useThemeVars().value.primaryColor is equal to '18a058'

**Comment by 07akioni** [comment]
Sorry for late response, I'm busy at work last week.

In you reproduction, the behavior is expected. Vue's inject on works for ascendant component.

For example you have a component A provide something. You can only got provided value if the component is inside A.

```
<A>
  <B />
</A>
```
You can get provided in component B but not in current component.
