### ISSUE TITLE
Can the select and dropdown components of naiveui be adapted in qiankun sandbox mode?

### ISSUE THREAD

**Issue by wawa0584** [TuSimple/naive-ui#3281]
### This function solves the problem (这个功能解决的问题)
Adapted to the qiankun sandbox mode environment
### Expected API (期望的 API)
Can a drop-down floating window be used to make a mode similar to ant-design teleport?

**Comment by Sepush** [comment]
what is the qiankun sandbox?

**Comment by 07akioni** [comment]
What do you mean like antd's teleport?

**Comment by wawa0584** [comment]
> What do you mean like antd's teleport? As far as I know they will mount popup at body element by default.

是这样子的 当qiankun 开启严格沙盒模式 下拉菜单、select 这种下拉悬浮就失效了，如果不开启沙盒模式 一切都是正常的，但是我看antd有通过自定义元素挂载来解决该问题 是否能做优化呢？
<img width="328" alt="image" src="https://user-images.githubusercontent.com/60140118/179435338-462b9e6e-e93f-45ad-a239-04c86615daf9.png">

https://user-images.githubusercontent.com/60140118/179435688-db3691d5-c54d-496a-ad0c-3868150c4f7f.mov

**Comment by wawa0584** [comment]
但是使用teleport  功能没有问题 但是样式好像消失了 都是原生的默认样式

**Comment by 07akioni** [comment]
> 拉菜单、select 这种下拉悬浮就失效了，如果不开启沙盒模式 一切都是正常的，但是我看antd有通过自定义元素挂载来解决该问题 是否能做优化呢？

这个得具体分析了，为什么样式没有正确的挂载，是不是 qiankun 拦截了到 head 动态挂载的样式。

我最近应该不太有空有时间研究某个具体沙盒的解决方案，如果你能帮忙解释一下问题具体出在哪的话可能会对 naive 实现兼容这个模式的功能有帮助。

**Comment by wawa0584** [comment]
> > 拉菜单、select 这种下拉悬浮就失效了，如果不开启沙盒模式 一切都是正常的，但是我看antd有通过自定义元素挂载来解决该问题 是否能做优化呢？
> 
> 这个得具体分析了，为什么样式没有正确的挂载，是不是 qiankun 拦截了到 head 动态挂载的样式。
> 
> 我最近应该不太有空有时间研究某个具体沙盒的解决方案，如果你能帮忙解释一下问题具体出在哪的话可能会对 naive 实现兼容这个模式的功能有帮助。



DOM 插入到子应用的盒子中，我看只有ANTD有这个getPopupContainer 弹出框（Select, Tooltip, Menu、Dropdown 等等）渲染父节点，默认渲染到 body 上。 function(triggerNode) () => document.body有这个，他对这一块好像都做了类似的兼容 就是为了适配qiankun的么 希望作者看一下哈 看代码的可行度怎么样

**Comment by 07akioni** [comment]
这感觉可能有很多暗坑

**Comment by wawa0584** [comment]
<img width="781" alt="image" src="https://user-images.githubusercontent.com/60140118/179942357-d865eaec-a5d9-42cb-a332-caca8d1639df.png">



<img width="309" alt="image" src="https://user-images.githubusercontent.com/60140118/179942914-05b97b09-4f6c-4510-9c4c-ad1add5d2ee8.png">


<img width="233" alt="image" src="https://user-images.githubusercontent.com/60140118/179943037-9adbce80-731d-49a5-95ac-f30d5bdd4444.png">



<img width="763" alt="image" src="https://user-images.githubusercontent.com/60140118/179943329-139c61db-cdec-4d1b-9c1c-7c50c77a10fc.png">
现在的需求是希望能在内部给个参数或者是回调函数去把这个浮层挂在当前元素的节点上 系统默认是挂载载body shadowDom开启的话 是拿不到dom元素的 所以无法改变挂载位置 目前遇到的是这个问题

**Comment by wawa0584** [comment]
> 这感觉可能有很多暗坑，antd 能跑的是怎么配置 getPopupContainer 的？

<img width="540" alt="image" src="https://user-images.githubusercontent.com/60140118/179944414-059cc40c-3b8a-463f-98db-f8e0d6204626.png">

<img width="686" alt="image" src="https://user-images.githubusercontent.com/60140118/179944479-088fce90-3e1e-480a-b1e7-bb41b658a68a.png">

他代码里是默认没有这个回掉函数 是默认挂载在body上 如果传入这个函数 就挂载在所在组件的节点 就不在body上了，这个domNode就是取决挂载body还是其他节点的问题
<img width="472" alt="image" src="https://user-images.githubusercontent.com/60140118/179945042-88f81a6b-183f-4224-b035-81c596faa4d8.png">

至于浮层好像没有什么奇特的地方 最终就是个teleport插槽而已  希望能抽空看一下哈

**Comment by wawa0584** [comment]
或者作者在naive-ui中能有什么好的解决方式，避免比较大的改动

**Comment by 07akioni** [comment]
> 能在内部给个参数或者是回调函数去把这个浮层挂在当前元素的节点上 系统默认是挂载载body shadowDom开启的话 是拿不到dom元素的 所以无法改变挂载位置 目前遇到的是这个问题

单纯说控制浮层卸载位置是可以提供一个属性的

**Comment by 07akioni** [comment]
能给个最小复现吗？我看看搞完能不能 work

**Comment by wawa0584** [comment]
> 能给个最小复现吗？我看看搞完能不能 work

https://user-images.githubusercontent.com/60140118/180397670-ca8e32b6-29a9-43cc-838f-d30a33c392f4.mov


我大概调试了下 问题大概
<img width="630" alt="image" src="https://user-images.githubusercontent.com/60140118/180397927-436275fc-7845-43cc-a8f2-6d0195ecb91e.png">
 mergedShowRe.value 一直为false 如果不是shadowDom模式一切正常的 但是开启shaDowDom模式，明明这一次执行openMenu,mergedShowRe的值不是已经变成true了吗，然后在点输入框收起,还是false

**Comment by wawa0584** [comment]
https://user-images.githubusercontent.com/60140118/180402762-1a48fc32-598b-4953-a6b8-7aadba8e47ea.mov


https://user-images.githubusercontent.com/60140118/180403123-354759a7-8f35-4e14-bf05-335f8e47a669.mov

可以看下这两段视频，一个是开启了沙盒 一个是没开启的

**Comment by 07akioni** [comment]
代码仓库复现能整一个？

**Comment by wawa0584** [comment]
> 

好的 
https://github.com/wawa0584/qiankun-vite-test 
跑main和vue3两个就行 默认开启了沙箱模式

<img width="365" alt="image" src="https://user-images.githubusercontent.com/60140118/180689079-89bbe97f-805d-45cc-96b2-860e5c382ae0.png">

**Comment by wawa0584** [comment]
> > 
> 
> 好的 https://github.com/wawa0584/qiankun-vite-test 跑main和vue3两个就行 默认开启了沙箱模式
> 
> <img alt="image" width="365" src="https://user-images.githubusercontent.com/60140118/180689079-89bbe97f-805d-45cc-96b2-860e5c382ae0.png">

十分感谢作者能在百忙中抽出时间来！！！

**Comment by 07akioni** [comment]
我周末看看

**Comment by wawa0584** [comment]
> 我周末看看

谢谢了哈

**Comment by 07akioni** [comment]
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/18677354/182026811-0bdfb9b3-2605-4342-9304-e2c3515dbaea.png">

我看关键问题是鼠标移动的 target 是子 app，不是里面的元素，不知道这玩意有没有解法

**Comment by 07akioni** [comment]
我倒是找到问题的解法了，不过看起来要改的地方不少

**Comment by 07akioni** [comment]
用 `e.composedPath()[0]` 取代 e.target 可以解决这些问题
