### ISSUE TITLE
Rollup error after trying to build nuxt project

### ISSUE THREAD

**Issue by skyroses** [TuSimple/naive-ui#3286]
### TuSimple/naive-ui version (版本)
2.31.0

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Opera GX (88.0.4412.75)

### System and its version (系统及其版本)
MacOS 12.3.1

### Node version (Node 版本)
16.15.0

### Reappearance link (重现链接)
https://github.com/07akioni/naive-ui-nuxt-demo

### Reappearance steps (重现步骤)
1. Clone your demo nuxt project - https://github.com/07akioni/naive-ui-nuxt-demo
2. Install dependencies and run build

### Expected results (期望的结果)
Successfully build project??

### Actual results (实际的结果)
We getting error 
```
Rollup error: Could not load /home/Documents/naive-ui-nuxt-demo/.nuxt/dist/server/server.mjs (imported by node_modules/nuxt/dist/core/runtime/nitro/renderer.mjs): ENOENT: no such file or directory, open '/home/Documents/naive-ui-nuxt-demo/.nuxt/dist/server/server.mjs'
```

### Remarks (补充说明)
Nuxt version: 3.0.0-rc.5
I trying with 3.0.0-rc.3 and 3.0.0-rc.4: the same problem

**Comment by 07akioni** [comment]
It seems to be a bug of nuxt

https://github.com/nuxt/framework/issues/5899

**Comment by skyroses** [comment]
@07akioni, ok, thanks
