### ISSUE TITLE
在Popover组件，打开Dialog窗口，关闭Dialog窗口时同时关闭Popover组件

### ISSUE THREAD

**Issue by linyu520** [TuSimple/naive-ui#3287]
### TuSimple/naive-ui version (版本)
2.31.0

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
96.0.4664.110

### System and its version (系统及其版本)
Windows 10 专业版

### Reappearance link (重现链接)
https://codesandbox.io/s/nice-cherry-moszt4?file=/src/Demo.vue:24-39

### Reappearance steps (重现步骤)
引入Popover组件，属性trigger为click，在Popover组件引入Dialog组件，打开Dialog后关闭Dialog组件！

### Expected results (期望的结果)
只关闭Dialog组件

### Actual results (实际的结果)
同时关闭了Dialog跟Popover组件

**Comment by nooooooom** [comment]
我觉得这种效果在业务上来说应该是行得通的，Dialog 对于开发者可能是由按钮转发出去的一个子组件，但是在视觉上它是挣脱这个按钮独立存在的，所以 ClickAway 对于它来说就是一种直觉上的行为

要做到这种效果的话可以自己掌控 Popover 的显示状态，自定义的需要点击外部关闭的触发元素

**Comment by 07akioni** [comment]
这种需要手动处理，没有办法自动判断用户意图
