### ISSUE TITLE
naive ui how to use postcss-plugin-px2rem

### ISSUE THREAD

**Issue by pro-xiaoy** [TuSimple/naive-ui#3288]
### This function solves the problem (这个功能解决的问题)
如何在vue3-cli中使用naive-ui结合postcss-plugin-px2rem做到响应式
### Expected API (期望的 API)
scss provider

**Comment by 07akioni** [comment]
在编译层面可以说没有可能做到
运行时层面有一点点可能，也不大
未来也不太会考虑支持这种场景

**Comment by liaohui1080** [comment]
> 

why ????

**Comment by 07akioni** [comment]
> > 
> 
> why ????

简单来说就是 naive 没有静态的 css 可供 post css 处理

**Comment by ying-tch** [comment]
> > > 
> > 
> > 
> > 为什么 ？？？？
> 
> 简单来说就是 naive 没有静态的 css 可用 post css 处理

inline-theme-disabled这个模式下，是否可以支持下呢？我们的项目不会频繁的改theme-overrides，但唯一的要求就是要在随便拖拽窗口的状态下，尽量保持样式不变，这就不得不依赖px2rem了
