### ISSUE TITLE
Set the button's focusable property to false does not work（设置按钮的focusable为false没有作用）

### ISSUE THREAD

**Issue by ccitsxy** [TuSimple/naive-ui#3292]
### TuSimple/naive-ui version (版本)
2.31.0

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Chrome 103.0.5060.114

### System and its version (系统及其版本)
Windows 10 21H2

### Node version (Node 版本)
16.15.0

### Reappearance link (重现链接)
https://codesandbox.io/s/blazing-rain-40oynk?file=/src/App.vue

### Reappearance steps (重现步骤)
Click the Button（点击按钮）

### Expected results (期望的结果)
Button is not focused（按钮不被聚焦）

### Actual results (实际的结果)
Button is focused（按钮被聚焦）

**Comment by 07akioni** [comment]
This is a bug, you can set `:native-focus-behavior="false"` with `focusable="false"` as a workaround.
