### ISSUE TITLE
建议在 NDataTable 勾选的时候，自动清空掉不存在的勾选内容，或者提供清空已勾选数据的方法

### ISSUE THREAD

**Issue by hz2** [TuSimple/naive-ui#3294]
### TuSimple/naive-ui version (版本)
2.31.0

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Chrome/104.0.5112.39 Safari/537.36 Edg/104.0.1293.21

### System and its version (系统及其版本)
Linux x86_64

### Reappearance link (重现链接)
https://codesandbox.io/s/rough-grass-cjjmdn?file=/src/page.vue:182-189

### Reappearance steps (重现步骤)
1 打开控制台
2 勾选 Edward King 0
3 点击 remove item 移除 Edward King 0
4 再勾选 Edward King 1
5 控制台打印出来了 Edward King 0 和 Edward King 1

### Expected results (期望的结果)
在 重新赋值表格的 data 的时候，能清理掉 @update:checked-row-keys 存着的数据
或者在 @update:checked-row-keys 清理掉无效的数据
或者提供一个方法手动清空

### Actual results (实际的结果)
打印出了不存在的数据

**Comment by Innei** [comment]
不能手动把 checked-row-keys 置空吗？

**Comment by 07akioni** [comment]
> 不能手动把 checked-row-keys 置空吗？

需要用这种方法，因为没有任何办法能可靠的判断用户是不是传了新的 data

**Comment by qazse41** [comment]
> > 不能手动把 checked-row-keys 置空吗？
> 
> 需要用这种方法，因为没有任何办法能可靠的判断用户是不是传了新的 data

怎么置空
