### ISSUE TITLE
Why mention not extends all features from input?

### ISSUE THREAD

**Issue by xpader** [TuSimple/naive-ui#3297]
### This function solves the problem (这个功能解决的问题)
Why mention not extend all features from input? Like tooltip extend all from popover.
### Expected API (期望的 API)
Mention extend all props, slots and more features from input component.

**Comment by 07akioni** [comment]
Mention has some tricky DOM handling. We are not able to provided all features at once (and now we only provide what we think is neccessary).

If you need some specific props, you can list it here and we may add them later.

**Comment by xpader** [comment]
Maybe input can provide some api or hook to handing DOM tricky, and mention component extends from input and implement mention feature.

**Comment by 07akioni** [comment]
> Maybe input can provide some api or hook to handing DOM tricky, and mention component extends from input and implement mention feature.

According to my experience, it possibly not work so I won't try.
