### ISSUE TITLE
Is it typo in docs?

### ISSUE THREAD

**Issue by richardoey** [TuSimple/naive-ui#33]
Hi, it's a little question. I feel confused with this statement in the docs.

_All the staff in Naive UI is wrote in TypeScript. It can work with your typescript project seamlessly._

do you mean _All of the stuffs_?

**Comment by 07akioni** [comment]
Yes. it's a typo.

**Comment by 07akioni** [comment]
fixed

**Comment by jasonlam-swatow** [comment]
*written
