### ISSUE TITLE
No gaps appear when using fragment child in n-space component（使用Fragment作为Space的子组件时没有出现间隔）

### ISSUE THREAD

**Issue by Thinker-ljn** [TuSimple/naive-ui#3305]
### TuSimple/naive-ui version (版本)
2.31.0

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
chrome103.0.5060.114

### System and its version (系统及其版本)
window 10

### Reappearance link (重现链接)
https://codesandbox.io/s/compassionate-aryabhata-3j89ql

### Reappearance steps (重现步骤)
[open reproduction link](https://codesandbox.io/s/compassionate-aryabhata-3j89ql)
[查看重现链接](https://codesandbox.io/s/compassionate-aryabhata-3j89ql)

### Expected results (期望的结果)
Show gaps when using fragment child in n-space component
使用Fragment作为Space的子组件时展示间隔

### Actual results (实际的结果)
No gaps appear when using fragment child in n-space component
使用Fragment作为Space的子组件时没有出现间隔

**Comment by Thinker-ljn** [comment]
![image](https://user-images.githubusercontent.com/8445972/179491007-ad47b132-8cb9-4878-a8df-1148bb5a5dfd.png)
片段组件内的每个组件应该都要有间隔

**Comment by 07akioni** [comment]
这个的问题不在 Fragment，关键问题是传进来的是个组件，naive 会给每个 vnode 包一个 div。Space 渲染的时候还拿不到子组件的 vnode，因为子组件还没渲染。

针对你这种 case，是有办法解决的，你可以使用 `:wrap-item="false"` 来解决，把 VDOM 级别的行为转化为 DOM 级别的行为。

<img width="1227" alt="image" src="https://user-images.githubusercontent.com/18677354/179564156-0f9b406e-c334-4501-8b27-1bd11e3f4f57.png">
