### ISSUE TITLE
NLog，The scroll bar is still at the initial position when the data is gradually increasing.

### ISSUE THREAD

**Issue by jahnli** [TuSimple/naive-ui#331]
### This function solves the problem (这个功能解决的问题)
The scroll bar is still at the initial position when the data is gradually increasing.  How do I keep the scroll bar up to date like the log in CMD  
### Expected API (期望的 API)
The scroll bar is still at the initial position when the data is gradually increasing.  How do I keep the scroll bar up to date like the log in CMD

**Comment by Sepush** [comment]
use `watch` and `logInstRef.value.scrollTo({position: 'bottom'})`
```js
watch(()=>logRef.value,(cur)=>{
  logInstRef.value.scrollTo({position: 'bottom'})
})
```
I will creat a demo in docs for you later
