### ISSUE TITLE
date range of datepicker can able to including disabled date range

### ISSUE THREAD

**Issue by weiwait** [TuSimple/naive-ui#3311]
### TuSimple/naive-ui version (版本)
2.31.0

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Chrome 103

### System and its version (系统及其版本)
Macos 12.4

### Reappearance link (重现链接)
https://codesandbox.io/s/naive-carousel-forked-vwe0oj?file=/src/components/demo.vue&resolutionWidth=320&resolutionHeight=675

### Reappearance steps (重现步骤)
picking date range on disabled date range both sides

### Expected results (期望的结果)
nothing, i don't know what is correct, just some strange feeling

### Actual results (实际的结果)
picked date range included disabled date range

**Comment by 07akioni** [comment]
This works as expected. If you don't want user's selection overlay with [a, b]. You should disable all date after b if first selected value is smaller than a, and disabled all date before a if first selected value is larger than b.

**Comment by weiwait** [comment]
> This works as expected. If you don't want user's selection to overlay with [a, b]. You should disable all date after b if first selected value is smaller than a, and disabled all date before a if first selected value is larger than b.

no, sometimes i want to exclude multiple date range for selected of before items. may be you can add a event that it trigging on the first date picked,  then refresh disable check, or some  other solution
