### ISSUE TITLE
当动态标签和穿梭框同时使用时，点击穿梭框的输入框然后回车，会删除动态标签

### ISSUE THREAD

**Issue by wj007881** [TuSimple/naive-ui#3312]
### TuSimple/naive-ui version (版本)
2.31.0

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
win11

### Reappearance link (重现链接)
https://codesandbox.io/s/heuristic-smoke-7f0ige?file=/src/Demo.vue

### Reappearance steps (重现步骤)
当动态标签和穿梭框同时使用时，点击穿梭框的输入框然后回车，会删除动态标签
附上的链接有页面代码

### Expected results (期望的结果)
回车没有反应

### Actual results (实际的结果)
删除了动态标签

**Comment by 07akioni** [comment]
可以看看新的版本有没有解决

**Comment by amadeus711** [comment]
这个应该是修好了，在 2.30.7 和之后
