### ISSUE TITLE
Set menu divider style with `nth-of-type` work abnormally

### ISSUE THREAD

**Issue by chioio** [TuSimple/naive-ui#3314]
### TuSimple/naive-ui version (版本)
2.31.0

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Brave (v1.41.96)

### System and its version (系统及其版本)
MacOS 12.3.1

### Reappearance link (重现链接)
https://codesandbox.io/s/angry-butterfly-g98elk?file=/src/App.vue

### Reappearance steps (重现步骤)
1. set `menu` component
2. set `menuOptions` contains dividers
3. change the divider styles with `nth-of-type`

### Expected results (期望的结果)
correct response for `nth-of-type` style.

### Actual results (实际的结果)
I write 4 divider, but just changed on the first and third one.

**Comment by 07akioni** [comment]
You used `nth-of-type` in a wrong way.

![yjZT6NMBDd](https://user-images.githubusercontent.com/18677354/179811149-32051096-f9e7-4c26-bd8f-84d6c384b966.png)

<img width="1355" alt="image" src="https://user-images.githubusercontent.com/18677354/179811242-55a5bfe1-6dfb-45b0-a0d0-7648cd36665b.png">

**Comment by chioio** [comment]
@07akioni Could you make menu divider tag with different with menu item tag (`div`), I want add category text on divider `::before` element, not divider line.😁
