### ISSUE TITLE
关于新版的Avatar 中slots，placeholder不生效问题

### ISSUE THREAD

**Issue by helloAping** [TuSimple/naive-ui#3315]
### TuSimple/naive-ui version (版本)
2.31.0

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
EDGE（103.0.1264.62 (正式版本) (64 位)）

### System and its version (系统及其版本)
Windows10 2004

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/avatar#Avatar-Slots

### Reappearance steps (重现步骤)
使用n-avatar 使用其#placeholder时图片无法加载时不能生效
https://s1.328888.xyz/2022/07/20/lpqZh.png （显示）
https://s1.328888.xyz/2022/07/20/lppUg.png （代码）
加入了lazy之后
https://s1.328888.xyz/2022/07/20/lpiKo.png （代码）
https://s1.328888.xyz/2022/07/20/lpWQF.png （显示）

### Expected results (期望的结果)
能够正常的图片加载失败时显示文字

### Actual results (实际的结果)
加入了lazy则图片，文字同时渲染，不加则只显示图片不显示文字，F12中并未渲染

**Comment by helloAping** [comment]
在 Edge，Firfox浏览器中都会有这种情况，加上了lazy后回添加上一个
`<img style="">文字` 标签跟上名字，然后浏览器会加上一个空图片图标，而不加上lazy就只会显示`<img>`文字不渲染
ps:使用源码没问题，npm下载就会出现问题

**Comment by xushulang** [comment]
2.32.2依然存在avatar懒加载不生效的问题，开了lazy相关配置，但还是一次性全部加载出来了

**Comment by 07akioni** [comment]
> 器中都会有这种情况，加上了lazy后回添加上一个
> `<img style="">文字` 标签跟上名字，然后浏览器会加上一个空图片图标，而不加上lazy就只会显示`<img>`文字不渲染
> ps:使用源码没问题，

浏览器是什么，有相关代码吗？

**Comment by carlosyan1807** [comment]
<img width="379" alt="image" src="https://user-images.githubusercontent.com/50797685/186665385-7e4e357a-7a73-4fd7-b90f-508ab918b6da.png">
<img width="245" alt="image" src="https://user-images.githubusercontent.com/50797685/186665249-4cf38643-e7f8-47ee-a6a4-e60e0d4364f5.png">

**Comment by 07akioni** [comment]
> <img alt="image" width="379" src="https://user-images.githubusercontent.com/50797685/186665385-7e4e357a-7a73-4fd7-b90f-508ab918b6da.png">
> 
> <img alt="image" width="245" src="https://user-images.githubusercontent.com/50797685/186665249-4cf38643-e7f8-47ee-a6a4-e60e0d4364f5.png">

是 Chrome + 最新版吗？

**Comment by carlosyan1807** [comment]
<img width="269" alt="image" src="https://user-images.githubusercontent.com/50797685/187077083-6006bf80-7301-4b92-ad8b-0ed36d45f1b7.png">
