### ISSUE TITLE
[NScrollbar] Add CSS activity classes when displaying scroll bars

### ISSUE THREAD

**Issue by cefiro** [TuSimple/naive-ui#3316]
### This function solves the problem (这个功能解决的问题)
When the scrollbar appears, it overlaps the text. I do something like margin-right or padding-right for the ".n-scrollbar-content" and it works fine. But if there is no scrollbar, it leaves a large indentation on the right
### Expected API (期望的 API)
Add additional classes to the ".n-scrollbar" class:
1. Vertical scrolling active ".n-scrollbar-rail-vertical--active"
2. Horizontal scrolling active ".n-scrollbar-rail-horizontal--active"

**Comment by 07akioni** [comment]
I don't this it's a good practice. Since content would shift if content length changes.

**Comment by cefiro** [comment]
Thanks for the answer!

Programmed styles with indents are not needed. We only need CSS activity classes for the main container ".n-scrollbar" for special cases.

And then, based on "n-scrollbar.n-scrollbar-rail-vertical--active" or "n-scrollbar.n-scrollbar-rail-horizontal--active", I myself can make the necessary styles for the child tag ".n-scrollbar-content"

Example:

// Main style
`.n-scrollbar .n-scrollbar-content { /*my code*/ }`

// If the vertical rail is active
`.n-scrollbar.n-scrollbar-rail-vertical--active .n-scrollbar-content { /*my code*/ }`

// If the horizontal rail is active
`.n-scrollbar.n-scrollbar-rail-horizontal--active .n-scrollbar-content { /*my code*/ }`

I would like to have only "empty" rail activity classes. This will not affect the current implementation of the component, everything will look the same.

**Comment by cefiro** [comment]
Sad =(

Here is a video with my problem: https://vimple.co/10230e613a2a4850b9009623346ee045

How to solve the problem without additional classes?

**Comment by 07akioni** [comment]
> https://vimple.co/10230e613a2a4850b9009623346ee045

I think the best choice is to add padding to right panel inner scroll area, not use scrollbar inside a padded container.
