### ISSUE TITLE
select组件配置max-tag-count="responsive"异常

### ISSUE THREAD

**Issue by xiahdfsq** [TuSimple/naive-ui#3322]
### TuSimple/naive-ui version (版本)
2.31.0

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
103.0.5060.114

### System and its version (系统及其版本)
window11

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/select

### Reappearance steps (重现步骤)
当设置了max-tag-count="responsive"，鼠标浮动到数字上，会出现标签组浮动框，删除第一个标签，那个标签孩子select框里面

### Expected results (期望的结果)
删除后，不应显示在select上了

### Actual results (实际的结果)
当设置了max-tag-count="responsive"，鼠标浮动到数字上，会出现标签组浮动框，删除第一个标签，那个标签孩子select框里面

**Comment by amadeus711** [comment]
当 `max-tag-count` 设置 `responsive` 参数后，只要已选标签长度之和超过一行，就会显示缩略标签，这与标签数量无关

**Comment by xiahdfsq** [comment]
不是说显示个数
本地情况是这样
有设置默认的全部项、后面我多选几个选项，这时候我去把鼠标设置到那个数字上面 把显示出来的全部去掉
但这时候呢 select框里面显示的全部没有去掉



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月22日(周五) 晚上10:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TuSimple/naive-ui] select组件配置max-tag-count="responsive"异常 (Issue #3322)




 
当 max-tag-count 设置 responsive 参数后，只要已选标签长度之和超过一行，就会显示缩略标签，这与标签数量无关

**Comment by 07akioni** [comment]
> 我多选几个选项，这时候我去把鼠标设置到那个数字上面 把显示出来的全部去掉 但这时候呢 select框里面显

来个复现吧，我没能复现
