### ISSUE TITLE
Tooltip 在黑夜模式下颜色异常

### ISSUE THREAD

**Issue by zhannan-cn** [TuSimple/naive-ui#3323]
### TuSimple/naive-ui version (版本)
2.31.0

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
103.0.5060.114

### System and its version (系统及其版本)
Windows10企业版(19043.1566)

### Node version (Node 版本)
16.14.2

### Reappearance link (重现链接)
https://github.com/zhannan-cn/Demo-Naive

### Reappearance steps (重现步骤)
运行环境为 yarn 1.22.18
运行项目,在头部中把主题设为黑暗模式,再重新整体刷新页面,把鼠标移动到切换黑暗模式的按钮上Tooltip 背景为纯黑色,字体也为黑色

### Expected results (期望的结果)
   修复黑暗模式进来直接为黑色的问题

### Actual results (实际的结果)
Tooltip 在黑暗模式异常

**Comment by zhannan-cn** [comment]
![image](https://user-images.githubusercontent.com/53068054/180357447-7aa22873-8853-4fa3-a41a-5ccf194c7fa2.png)

**Comment by amadeus711** [comment]
![image](https://user-images.githubusercontent.com/46394163/180464048-4d644d6c-d7ae-4148-a1bf-f57623b9c80d.png)
需要复现

**Comment by zhannan-cn** [comment]
https://user-images.githubusercontent.com/53068054/180587920-58393d61-4752-4b88-bf94-aace096c7158.mp4

**Comment by zhannan-cn** [comment]
https://user-images.githubusercontent.com/53068054/180589206-e6f20e63-220b-4281-a801-76814fd8c14e.mp4

**Comment by 07akioni** [comment]
不要去持久化主题对象，持久化主题的名称就行了，拿到名称再来取对象。

主题对象内部是有循环引用的，而且完整的储存非常大，localStorage 一共 5M 这个对象就 800K。

<img width="169" alt="image" src="https://user-images.githubusercontent.com/18677354/180653232-48032791-72a7-4ce7-a179-0a3e63cff85e.png">
