### ISSUE TITLE
数据表格设置 remote后 sorter函数失效？

### ISSUE THREAD

**Issue by AnxiangLemon** [TuSimple/naive-ui#3328]
### This function solves the problem (这个功能解决的问题)
<n-data-table remote 

 //设置为异步之后 这个排序就不会生效了 remote
            sorter(rowA: any, rowB: any) {
                console.log(rowA, rowB);

                return rowA.a - rowB.b
            }
### Expected API (期望的 API)
应该是默认的 sorter还在  而不是无效 如果可以前端重写排序的话 而不是请求后端

**Comment by 07akioni** [comment]
API 设计是这样的。Table 的排序总是全局排序，因此当远程拉取数据的时候本地排序不再生效。

**Comment by easy868** [comment]
远程数据不能本地排序吗？

**Comment by YouthShouting** [comment]
远程数据不能本地排序吗？有没有远程数据本地排序的例子？

**Comment by ickedesign** [comment]
本地单页排序可以用 on-update:sorter="handleSorterChange" 这个API来实现，自己手写一个对当前的数组进行排序的方法就好了
