### ISSUE TITLE
feat(Message & Notification): global configuration and global events

### ISSUE THREAD

**Issue by cnguu** [TuSimple/naive-ui#333]
### This function solves the problem (这个功能解决的问题)
More convenient configuration and operation
## global configuration

- `duration`
- `maxVisible`: The maximum number of messages to be displayed beyond the automatic closing time for earlier messages
- `placement`: notification pop up from `topRight` or `bottomRight` or `bottomLeft` or `topLeft`.

```vue
<!-- App.vue -->

<n-message-provider :duration="3" :maxVisible="1">
  <content />
</n-message-provider>

<n-notification-provider :duration="3" placement="bottomRight">
  <content />
</n-notification-provider>
```

## global events

- `destroyAll()`: destroy all

```typescript
// vue-router guard
import type { Router } from "vue-router";

import { useMessage, useNotification } from "naive-ui";

const message = useMessage();
const notification= useNotification();

export default function messageGuard(router: Router) {
  router.beforeEach(() => {
    try {
      message.destroyAll();
      notification.destroyAll();
    } catch (error) {
      console.error("message guard error:"   error);
    }

    return true;
  });
}
```

**Comment by ue360** [comment]
只解决了message的个别配置，notification的呢？destroyAll呢？咋就给关了

**Comment by 07akioni** [comment]
> 只解决了message的个别配置，notification的呢？destroyAll呢？咋就给关了

Notification 的话 placement 计划搞，不过 maxVisible 和 duration 没有计划
