### ISSUE TITLE
vue3.2 has supported setup syntax sugar

### ISSUE THREAD

**Issue by MrYZhou** [TuSimple/naive-ui#3336]
### This function solves the problem (这个功能解决的问题)
When is setup syntax sugar supported
### Expected API (期望的 API)
i mean the official document, for copy

**Comment by MrYZhou** [comment]
desc

**Comment by Sepush** [comment]
always supported.
If you mean script setup It's easy, modify by yourself.
Change all demo code to script setup will cost too much energy.
We need spend the time to bug fix and new features.

**Comment by 07akioni** [comment]
We won't put time into refactor all demos for the syntax sugar, nor we won't be able to iterate on new features or bug fix.
