### ISSUE TITLE
使用h渲染函数的建议

### ISSUE THREAD

**Issue by long5635152** [TuSimple/naive-ui#3337]
### This function solves the problem (这个功能解决的问题)
很多组件需要自定义内容的时候，文档上描述都是要求使用h渲染函数，但是实际操作起来很难用，内容复杂的情况下就是个灾难，为什么不改用slot插槽呢？
### Expected API (期望的 API)
建议将需要使用h渲染函数的地方改为slot插槽

**Comment by 07akioni** [comment]
这个讨论此次数也比较多了，是一个综合之后的权衡，没有完美的方案，都是踩下一头就翘起另一头。

https://github.com/TuSimple/naive-ui/issues/106

**Comment by long5635152** [comment]
这个完全可以参考element+，element+不也是用的typescript吗？h函数体验真的不好，我的同事们没有不吐槽的

**Comment by chenbimo** [comment]
真难受。
