### ISSUE TITLE
期望NCascader组件中，增加一个props可以替代 CascaderOption 中的 disabled 字段名

### ISSUE THREAD

**Issue by AustinQin** [TuSimple/naive-ui#3338]
### This function solves the problem (这个功能解决的问题)
当服务端接口返回的数据中，用来表示禁用选项的字段名不为disabled时，需要遍历数据来更改字段名为disabled，数据量大时不合适。
### Expected API (期望的 API)
disabled-field

**Comment by Sepush** [comment]
不会改 `disabled = yourdisabled`

**Comment by 07akioni** [comment]
@Sepush 这个倒是可以做，treemate 提供了这个配置的一个选项，只不过没通过 naive 暴露出去

**Comment by 07akioni** [comment]
![Uploading image.png…]()

**Comment by 07akioni** [comment]
不过这个事情优先级依然不是很高
