### ISSUE TITLE
tag标签绑定click事件时，点击tag标签的关闭按钮时会同时触发close事件

### ISSUE THREAD

**Issue by maddenBoy** [TuSimple/naive-ui#3343]
### TuSimple/naive-ui version (版本)
2.31.0

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Chrome(103.0.5060.134)

### System and its version (系统及其版本)
window 11

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/tag

### Reappearance steps (重现步骤)
给可关闭的tag标签绑定click事件，点击关闭按钮时会同时触发两个事件

### Expected results (期望的结果)
期望给可关闭的tag标签绑定click事件时，点击非关闭按钮区域时只触发click事件，点击关闭按钮时只触发close事件。

### Actual results (实际的结果)
实际给可关闭的tag标签绑定click事件时，点击关闭按钮时会同时触发click事件和close事件。

### Remarks (补充说明)
elementui的tag有click和close两个回调，naive只有close的回调

**Comment by Sepush** [comment]
use `internal-stop-click-propagation` prop can solve your issue.
``` html
<n-tag 
  type="info" 
  closable 
  internal-stop-click-propagation 
  @click="handleClick" @close="handleClose"
>
  OK
</n-tag>
```

**Comment by 07akioni** [comment]
这个可能得考虑

**Comment by 07akioni** [comment]
外部化这种属性

**Comment by Sepush** [comment]
> 外部化这种属性

暴露出来叫 `stopClickPropagation` 怎么样
