### ISSUE TITLE
Data Table 展开行显示问题

### ISSUE THREAD

**Issue by atAurora** [TuSimple/naive-ui#3362]
### TuSimple/naive-ui version (版本)
2.31.0

### Vue version (Vue 版本)
3.2.13

### Browser and its version (浏览器及其版本)
Chrome(103.0.5060.114)

### System and its version (系统及其版本)
MacOS(11.6)

### Reappearance link (重现链接)
https://github.com/atAurora/naive-ui-datatable-bug

### Reappearance steps (重现步骤)
点击展开行下的 Delete 按钮，将展开行下的信息全部删除

### Expected results (期望的结果)
当可展开按钮不渲染，展开部分也消失

### Actual results (实际的结果)
由于没有信息，展开按钮不显示，但仍然会渲染空白的展开部分，若额外在 renderExpand 中判断，没有信息返回 undefined，此时会多渲染空白间隔，若不判断，在链接中的场景会渲染空的 data table

**Comment by 07akioni** [comment]
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/18677354/181275451-e2eba247-4388-4366-8482-b101266b78c6.png">
