### ISSUE TITLE
n-dropdown

### ISSUE THREAD

**Issue by PZ-18664918826** [TuSimple/naive-ui#3365]
### This function solves the problem (这个功能解决的问题)
n-dropdown options定义了一个ref变量 更改了值 展示的结果是初始化的值
### Expected API (期望的 API)
options希望是一个响应式的，可以更改为任何值。

**Comment by 07akioni** [comment]
需要一个复现

**Comment by PZ-18664918826** [comment]
> 需要一个复现

我的代码原因

**Comment by sky124380729** [comment]
需要添加一个选中状态，类似于ant-design
https://ant.design/components/dropdown-cn/#components-dropdown-demo-selectable

**Comment by 07akioni** [comment]
> https://ant.design/components/dropdown-cn/#components-dropdown-demo-selectable

新开个 issue 吧
