### ISSUE TITLE
Color Picker组件绑定show属性后面板显示隐藏问题

### ISSUE THREAD

**Issue by maddenBoy** [TuSimple/naive-ui#3366]
### TuSimple/naive-ui version (版本)
2.31.0

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Chrome（103.0.5060.134）

### System and its version (系统及其版本)
window 11

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/color-picker

### Reappearance steps (重现步骤)
1.Color Picker组件绑定show属性和click事件去控制面板显示隐藏
2.点击选择器，打开选择面板
3.点击页面空白处不会隐藏颜色选择面板，若给选择器绑定clickoutside隐藏，点击面板任意位置时也会把面板隐藏

### Expected results (期望的结果)
期望绑定show属性时在显示面板的情况下可以点击非面板区域隐藏面板

### Actual results (实际的结果)
绑定show属性时点击非面板区域无法隐藏面板，若给选择器绑定clickoutside隐藏，点击面板时也会触发把面板隐藏

### Remarks (补充说明)

```
<template>
  <n-color-picker ref="pickerRef" :show="isShow" @click="toggleShow" />
</template>
<script>
  import { defineComponent, ref } from "vue";
  import { onClickOutside } from "@vueuse/core";
  const isShow = ref(false);
  const toggleShow = () => {
    isShow.value = !isShow.value;
  };
  const pickerRef = ref(null);
  onClickOutside(pickerRef, () => {
    isShow.value = false;
  });
  export default defineComponent({
    setup() {
      return {
        isShow,
        toggleShow,
        pickerRef,
      };
    },
  });
</script>

```

**Comment by 07akioni** [comment]
用 onUpdate:show 去控制，点在外面会发出 false
