### ISSUE TITLE
为什么按钮后都有个::affter的小分割线，你们凭什么这样封装，这样封装的话最起码要把可配置的参数暴露出来啊

### ISSUE THREAD

**Issue by SSQLQIANBB** [TuSimple/naive-ui#3367]
### This function solves the problem (这个功能解决的问题)
为什么按钮后都有个::affter的小分割线，你们凭什么这样封装，这样封装的话最起码要把可配置的参数暴露出来啊，多个按钮在一起的时候，有时候就显示分割线，有时候就不显示分割线，什么鬼东西
### Expected API (期望的 API)
NButton

**Comment by Zheaoli** [comment]
爱用不用，不用就滚啦。千万别把自己当大爷，社区都是为爱发电，没人惯着你（

<img width="908" alt="image" src="https://user-images.githubusercontent.com/7054676/181272976-81ef828b-b659-4d82-aa7e-50fd97feeb6f.png">

**Comment by 07akioni** [comment]
你是不是引了其他什么库？我看官网上面的例子都是没有的
