### ISSUE TITLE
分页 Pagination 使用元素个数控制分页，自定义page-sizes后 size-picker中的内容默认还是为10

### ISSUE THREAD

**Issue by gcfkhy** [TuSimple/naive-ui#3369]
### TuSimple/naive-ui version (版本)
2.32.0

### Vue version (Vue 版本)
3.2.33

### Browser and its version (浏览器及其版本)
Google Chrome   版本 103.0.5060.134（正式版本） （64 位）

### System and its version (系统及其版本)
Windows 10 

### Node version (Node 版本)
16.5

### Reappearance link (重现链接)
https://codesandbox.io/s/gifted-bird-71eo87?from-embed=&file=/src/Demo.vue

### Reappearance steps (重现步骤)
1  将:page-sizes改为  :page-sizes="[8, 16, 24, 32]"
2 刷新页面 size-picker 中默认还是为10

### Expected results (期望的结果)
size-picker 中默认为已设置的 :page-sizes 数组中的第一个

### Actual results (实际的结果)
size-picker 中默认值为10 非自己已经更改后的

**Comment by sechi747** [comment]
因为你没有传递pageSize属性，如果加上pageSize就正常了

**Comment by gcfkhy** [comment]
> 因为你没有传递pageSize属性，如果加上pageSize就正常了

加上pageSize 就为 响应式绑定了，显示是正常的，但更改要分页大小会一直默认显示pageSize 。
 我此处使用的是按照项目总数计算页码的

这个链接↓ 你可以试一试呢
https://codesandbox.io/s/gifted-bird-71eo87?from-embed=&file=/src/Demo.vue

**Comment by gcfkhy** [comment]
> 因为你没有传递pageSize属性，如果加上pageSize就正常了

pageSize是响应式的 加上切换分页大小会一直保留默认分页大小，因此需使用 default-page-size
