### ISSUE TITLE
inputNumber 输入0.0000001 后 输入框值会变成0

### ISSUE THREAD

**Issue by chenxinjun** [TuSimple/naive-ui#3370]
### This function solves the problem (这个功能解决的问题)
预期结果未0.0000001 实际结果为 0
### Expected API (期望的 API)
https://www.naiveui.com/zh-CN/os-theme/components/input-number

**Comment by chenxinjun** [comment]
任意inputNumber 输入 0.0000001 结果为 0

**Comment by jizai1125** [comment]
> 

可以通过 precision 属性 设置精度

**Comment by jizai1125** [comment]
> 任意inputNumber 输入 0.0000001 结果为 0

可以通过 precision 属性 设置精度

**Comment by jizai1125** [comment]
> 任意inputNumber 输入 0.0000001 结果为 0

@chenxinjun 可以通过 precision 属性设置精度

**Comment by chenxinjun** [comment]
我尝试过 不行的，
@jizai1125 
 到小数点第七位输入一个数字 就会置为0

**Comment by jizai1125** [comment]
@chenxinjun 
![image](https://user-images.githubusercontent.com/33979706/181446157-cebc9f6e-9a73-4dee-8160-c4368f2e0f05.png)
不会呀

**Comment by chenxinjun** [comment]
你输入 0.0000001

**Comment by chenxinjun** [comment]
> @chenxinjun ![image](https://user-images.githubusercontent.com/33979706/181446157-cebc9f6e-9a73-4dee-8160-c4368f2e0f05.png) 不会呀

你输入0.0000001

**Comment by chenxinjun** [comment]
前六位都为0  不要有数

**Comment by jizai1125** [comment]
![image](https://user-images.githubusercontent.com/33979706/181446733-eecd4ca9-575d-443d-ba10-f747391fb6b3.png)

**Comment by chenxinjun** [comment]
> ![image](https://user-images.githubusercontent.com/33979706/181446733-eecd4ca9-575d-443d-ba10-f747391fb6b3.png)
我可能是我版本最近没升级的缘故，我刚刚升级版本后然后重试可以了，感谢您的回复   感谢 
再次非常感谢

**Comment by 07akioni** [comment]
input number 在极限情况下确实是会存在精度问题，这是 double 的特性导致的。

从根本上解决应该靠大整数运算，但是一时半会儿不会加这种功能，因为可能太费精力了。
