### ISSUE TITLE
Dialog's Action Button need a prop to config size

### ISSUE THREAD

**Issue by wtusmchen** [TuSimple/naive-ui#3378]
### This function solves the problem (这个功能解决的问题)
对话框的action button目前是默认small，希望能通过属性控制尺寸
### Expected API (期望的 API)
action-size="big"

**Comment by amadeus711** [comment]
你好，可以使用：
![image](https://user-images.githubusercontent.com/46394163/181570968-645fbda9-65f0-4dfb-91bd-dffb1c61a193.png)
将其替换成你想要的

**Comment by 07akioni** [comment]
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/18677354/181597322-afb52604-0fb5-4f61-a67f-d097f091f1df.png">

**Comment by wtusmchen** [comment]
> <img alt="image" width="1313" src="https://user-images.githubusercontent.com/18677354/181597322-afb52604-0fb5-4f61-a67f-d097f091f1df.png">

解决了，非常感谢

**Comment by wtusmchen** [comment]
@07akioni 解决了，非常感谢
positiveButtonProps: {size: 'medium'}

@amadeus711 你这个方法也是可以的，感谢
action: () => {
           return [h(NButton, {onClick: ()=>{dialogReactive.destroy()}}, {default: ()=>{return '取消'}}),  
                       h(NButton, {type: 'primary', onClick: ()=>{if(okFun){okFun()}dialogReactive.destroy()}}, {default: ()=>{return '确定'}})]
 }
