### ISSUE TITLE
When Menu collapsed, render label as <router-link /> ,has children props can't click，The font color display is abnormal in the tooltips

### ISSUE THREAD

**Issue by shuaibishun** [TuSimple/naive-ui#338]
### TuSimple/naive-ui version (版本)
2.15.1

### Vue version (Vue 版本)
3.1.2

### Browser and its version (浏览器及其版本)
Chrome 91.0.4472.114

### System and its version (系统及其版本)
MacOS

### Reappearance link (重现链接)
https://codesandbox.io/s/empty-resonance-v8el2

### Reappearance steps (重现步骤)
使用render-label 渲染RouterLink 菜单压缩后 多层级点击无响应，单层级 hover  后 tooltips 字体颜色显示不正常

### Expected results (期望的结果)
fix bug

### Actual results (实际的结果)
fix bug

**Comment by 07akioni** [comment]
Fixing

**Comment by fireloong** [comment]
下拉菜单 Dropdown 有同样的问题
