### ISSUE TITLE
Pagination的快速跳跃添加一个可控的失去焦点触发

### ISSUE THREAD

**Issue by x101046** [TuSimple/naive-ui#3387]
### This function solves the problem (这个功能解决的问题)
虽然容易让用户误操作，但确实有很多甲方客户有这样的需求，建议用一个属性来控制是否启用
### Expected API (期望的 API)
通过一个属性来配置，是否失去焦点时触发快速跳跃

**Comment by Sepush** [comment]
可以暴露一个 `trigger-jump-on-blur` @07akioni  你觉得呢
