### ISSUE TITLE
TreeOption Properties, set 'type'='group', treeNode can't expand.

### ISSUE THREAD

**Issue by iwnasup** [TuSimple/naive-ui#3388]
### TuSimple/naive-ui version (版本)
2.32.0

### Vue version (Vue 版本)
3.2.33

### Browser and its version (浏览器及其版本)
Chrome(103.0.5060.134)

### System and its version (系统及其版本)
Windows 11

### Node version (Node 版本)
v16.15.0

### Reappearance link (重现链接)
https://codesandbox.io/s/festive-curran-178sy4?file=/src/Demo.vue

### Reappearance steps (重现步骤)
run it.

### Expected results (期望的结果)
treeNode can expand

### Actual results (实际的结果)
treeNode can't expand

**Comment by Sepush** [comment]
`treeOption` does not have a `type` field

**Comment by iwnasup** [comment]
> `treeOption`没有`type`字段 https://www.naiveui.com/en-US/os-theme/components/tree#TreeOption-Properties

对，没有，但是加了之后会出现这个链接里所展示的问题：https://codesandbox.io/s/festive-curran-178sy4?file=/src/Demo.vue
加了type=“group”，会导致节点无法展开，而且子节点会出现。
我不是想要你们加type属性，而是希望可以解决这个问题。

**Comment by Sepush** [comment]
> > `treeOption`没有`type`字段 https://www.naiveui.com/en-US/os-theme/components/tree#TreeOption-Properties
> 
> 对，没有，但是加了之后会出现这个链接里所展示的问题：https://codesandbox.io/s/festive-curran-178sy4?file=/src/Demo.vue 加了type=“group”，会导致节点无法展开，而且子节点会出现。 我不是想要你们加type属性，而是希望可以解决这个问题。

既然没有这个属性 那就不应该传的 你不设置就是正常的

**Comment by iwnasup** [comment]
> > > `treeOption`没有`type`字段 https://www.naiveui.com/en-US/os-theme/components/tree#TreeOption-Properties
> > 
> > 
> > 对，没有，但是加了之后会出现这个链接里所展示的问题：https://codesandbox.io/s/festive-curran-178sy4?file=/src/Demo.vue 加了type=“group”，会导致节点无法展开，而且子节点会出现。 我不是想要你们加type属性，而是希望可以解决这个问题。
> 
> 既然没有这个属性 那就不应该传的 你不设置就是正常的

确实如此。那么可以请你们给treeNode加一个可以添加自定义属性的功能吗？这样我就可以使用type了

**Comment by 07akioni** [comment]
这是个问题，会处理一下 @iwnasup

**Comment by iwnasup** [comment]
> 这是个问题，会处理一下 @iwnasup

感谢
