### ISSUE TITLE
useDialog cannot be called up in the entry file.

### ISSUE THREAD

**Issue by TuiMao233** [TuSimple/naive-ui#340]
### TuSimple/naive-ui version (版本)
2.15.1

### Vue version (Vue 版本)
3.1.2

### Browser and its version (浏览器及其版本)
90.0.4430.93

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://codesandbox.io/s/optimistic-sinoussi-rz6ki?file=/src/App.vue

### Reappearance steps (重现步骤)

App.vue

~~~html
<template>
  <n-dialog-provider></n-dialog-provider>
</template>

<script>
import { defineComponent } from "vue";
import { useDialog } from "naive-ui";
export default defineComponent({
  setup: () => {
    const dialog = useDialog();
    dialog.warning({
      title: "12321",
    });
  },
});
</script>
~~~

### Expected results (期望的结果)
Normal use

### Actual results (实际的结果)
[naive/use-dialog]: No outer <n-dialog-provider /> founded.

**Comment by 07akioni** [comment]
`useDialog` must in inner component in dialog provider.

**Comment by arrbaron** [comment]
> useDialog must be in inner component in dialog provider.

Could you elaborate on this, with an example? I have the dialog provider in my top level App.vue template like so:

`<template>
  <n-dialog-provider>
    <router-view />
  </n-dialog-provider>
</template>`

I'm trying to use a dialog on a child component, much deeper down the tree (using options API)

`methods: {
    showConfirmPower(): void {
      const dialog = useDialog();

      dialog.warning({
        title: 'Confirm',
        content: 'Are you sure?',
        positiveText: 'Sure',
        negativeText: 'Not Sure',
        onPositiveClick: () => {
          console.log('Sure');
        },
        onNegativeClick: () => {
          console.log('Not Sure');
        }
      });
    }
  }`

I'm seeing the same error:

`No outer <n-dialog-provider /> founded.`
