### ISSUE TITLE
国际化显示语言逻辑优化建议

### ISSUE THREAD

**Issue by qlynick** [TuSimple/naive-ui#3405]
### This function solves the problem (这个功能解决的问题)
设置多个语言环境的时候按照预期显示优先顺序的语言
### Expected API (期望的 API)
我在谷歌浏览器打印navigator对象里现状是这样的 
navigator = {
  language: "ko-KR",
  languages: ['ko-KR', 'ko', 'zh-CN', 'zh', 'zh-HK', 'zh-TW', 'en-US', 'en']
}
进入主页的时候，在这个情况默认显示的是en-US， 应该显示zh-CN比较合情合理一些

**Comment by 07akioni** [comment]
这个再封装一下就好了，国际化都是有体积的，不可能全都塞进去
