### ISSUE TITLE
折叠面板 Collapse

### ISSUE THREAD

**Issue by iZaiZaiA** [TuSimple/naive-ui#3408]
### This function solves the problem (这个功能解决的问题)
现在业务场景中有个需求，就是，可能其中一个或多个，根据接口返回的数据状态，禁止展开。
比如，1-3条数据正常，可正常展开，4-6条数据，不允许展开，7-9条数据可展开。

### Expected API (期望的 API)
希望，n-collapse-item 组件，增加一个是否可展开（或是否禁用）的参数。

**Comment by Sepush** [comment]
根据你的数据 设置一下 `default-expanded-names` 应该能做到

**Comment by iZaiZaiA** [comment]
> 根据你的数据 设置一下 `default-expanded-names` 应该能做到

不能像饿了么那样，直接有个属性吗？，如果用 `default-expanded-names` 的话，处理起来，就比较麻烦。没有 `disabled ` 简单。

<img width="984" alt="image" src="https://user-images.githubusercontent.com/26807649/182341028-7885ac5f-45d8-4fc6-97c0-6ed7686bce6f.png">

**Comment by Sepush** [comment]
可以加

**Comment by 07akioni** [comment]
感觉可以加一下
