### ISSUE TITLE
DataTable 用户可通过调整列宽大小

### ISSUE THREAD

**Issue by zhuangState** [TuSimple/naive-ui#3412]
### This function solves the problem (这个功能解决的问题)
当列宽过小时，无法完整数据。
column.ellipsis.tooltip不方便预览整列
### Expected API (期望的 API)
column.resizable
参考：
antd：https://www.antdv.com/components/table-cn#components-table-demo-resizable-column
element-plus :https://element-plus.gitee.io/zh-CN/component/table.html#%E5%B8%A6%E8%BE%B9%E6%A1%86%E8%A1%A8%E6%A0%BC

**Comment by muchenfine** [comment]
期望可以加上，我也是这样的需求 @07akioni  @amadeus711

**Comment by 07akioni** [comment]
重复 https://github.com/TuSimple/naive-ui/issues/3318
