### ISSUE TITLE
上传 Upload 完成事件里的bug

### ISSUE THREAD

**Issue by iZaiZaiA** [TuSimple/naive-ui#3418]
### TuSimple/naive-ui version (版本)
2.32.1

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Microsoft Edge 版本 103.0.1264.77 (正式版本) (x86_64)

### System and its version (系统及其版本)
MacOS 12.4

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/upload

### Reappearance steps (重现步骤)
因为涉及到删除文件的功能，所以，当我上传完成后，需要把返回的id赋值，在调用删除接口时，提交列表id字段，才能删除成功。

但我这样处理后，控制台报错。

```
//上传完成
const uploadFinish = ({file,event}) => {
    let res = JSON.parse(event.target.response);
    if (res.code === 200) {
        file.id = res.data.id  //赋值接口返回的id
    }
}
```

控制台报错：`File has no corresponding id in current file list.`

我看文档上写的意思，是支持直接修改 `file` 对象的啊

`on-finish` 文件上传结束的回调，可以修改传入的 `UploadFileInfo` 或者返回一个新的 `UploadFileInfo`。

`UploadFileInfo Type`

属性	类型	说明	版本
`id`	`string`	`文件 id`，需要唯一

但为什么不能修改id字段呢？

### Expected results (期望的结果)
希望能够正常修改id字段，因为，能确定接口返回的id是唯一的，如果不主动修改，应该才内置，如果主动修改，应该放行，用户设置为主。

### Actual results (实际的结果)
控制台报错：`File has no corresponding id in current file list.`

**Comment by yamfeel** [comment]
自定义上传onFinish()，多文件上传也是这个id bug。没有指定this id

**Comment by itjackjw** [comment]
这个好像不是返回id的问题是没有返回response，打包上线以后返回的是一个null，但是线下测试的是可以返回。而且打包上线以后好像顺序也有问题，经历的事件顺序有问题

**Comment by amadeus711** [comment]
> 这个好像不是返回id的问题是没有返回response，打包上线以后返回的是一个null，但是线下测试的是可以返回。而且打包上线以后好像顺序也有问题，经历的事件顺序有问题

null 的问题找你用的 admin 看看，是二次封装产生的

**Comment by amadeus711** [comment]
id 会被组件用作 list 的 key，不建议修改这个。

如果你真的想需要搞到一个服务端的 id，建议是维护一个 map，然后在 onFinish 的里面设定。

```
const idToServerId: Record<string, string> = {}

const onFinish = ({ file, event }) => {
  const idToServerId[file.id] = event.response.remoteId
}
```

**Comment by iZaiZaiA** [comment]
> id 会被组件用作 list 的 key，不建议修改这个，否则后续会出很多麻烦。
> 
> 如果你真的想需要搞到一个服务端的 id，建议是维护一个 map，然后在 onFinish 的里面设定。
> 
> ```
> const idToServerId: Record<string, string> = {}
> 
> const onFinish = ({ file, event }) => {
>   const idToServerId[file.id] = event.response.remoteId
> }
> ```

就不说id，你好歹开放下，允许我自己加几个字段，或者加个指定字段，可自定义存放扩展的东西也好啊。可是没有，自定义字段，会被处理掉，不会出现在文件列表的数据中。。



算了算了，给你们提过几个issues，基本上都是回答，这样不建议，自己处理。。。我在想，这种组件的问题，还要我自己处理，那我用这套框架干啥？？我自己写套组件不香？？框架不就是为了提升效率？然后，我并没有感受到，要么就是这个不支持，那个有问题，提issues后，又这个不建议，那个没必要。。。

从技术角度来说，你们是对的，但从业务场景和开发效率来说，我还是用饿了么UI吧，虽然没有naiveUI好看，但毕竟支持的多啊。

**Comment by 07akioni** [comment]
> > id 会被组件用作 list 的 key，不建议修改这个，否则后续会出很多麻烦。
> > 如果你真的想需要搞到一个服务端的 id，建议是维护一个 map，然后在 onFinish 的里面设定。
> > ```
> > const idToServerId: Record<string, string> = {}
> > 
> > const onFinish = ({ file, event }) => {
> >   const idToServerId[file.id] = event.response.remoteId
> > }
> > ```
> 
> 就不说id，你好歹开放下，允许我自己加几个字段，或者加个指定字段，可自定义存放扩展的东西也好啊。可是没有，自定义字段，会被处理掉，不会出现在文件列表的数据中。。
> 
> 算了算了，给你们提过几个issues，基本上都是回答，这样不建议，自己处理。。。我在想，这种组件的问题，还要我自己处理，那我用这套框架干啥？？我自己写套组件不香？？框架不就是为了提升效率？然后，我并没有感受到，要么就是这个不支持，那个有问题，提issues后，又这个不建议，那个没必要。。。
> 
> 从技术角度来说，你们是对的，但从业务场景和开发效率来说，我还是用饿了么UI吧，虽然没有naiveUI好看，但毕竟支持的多啊。

这东西怎么说呢，口味问题。很多事情是没有标准答案的，我很支持大家选符合自己口味的工具来用。
