### ISSUE TITLE
Spin的遮罩层防止穿透

### ISSUE THREAD

**Issue by lspriv** [TuSimple/naive-ui#3429]
### This function solves the problem (这个功能解决的问题)
现在可以在Spin加载状态下操作遮罩下的radio单选按钮
### Expected API (期望的 API)
是否需要提供一个prop来控制遮罩穿透

**Comment by 07akioni** [comment]
听你的描述我感觉这像个 bug

**Comment by amadeus711** [comment]
没能复现，需要一个复现

<img width="790" alt="image" src="https://user-images.githubusercontent.com/46394163/183282037-9764a351-8d8b-4997-bd26-376e9c86f4da.png">
