### ISSUE TITLE
nupload组件打包上线以后finish事件没有返回XMLHttpRequest而是返回一个null,但是调试版本确是能够正常返回

### ISSUE THREAD

**Issue by itjackjw** [TuSimple/naive-ui#3431]
### TuSimple/naive-ui version (版本)
2.32.1

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Google Chrome(103.0.5060.134)

### System and its version (系统及其版本)
macos

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/upload

### Reappearance steps (重现步骤)
打包上线以后上传文件，打印finish事件里面的参数event?.target返回的居然是一个null,但是在线下调试的时候一切正常，而且我还看了这个执行的顺序好像也是有问题的。

### Expected results (期望的结果)
打包上线以后上传文件，打印finish事件里面的参数event?.target能正常返回XMLHttpRequest，执行顺序正常

### Actual results (实际的结果)
打包上线以后上传文件，打印finish事件里面的参数event?.target不能正常返回而且返回了一个null，执行顺序不正常

**Comment by Sepush** [comment]
你是不是用了什么别用封装的admin 之前有一个用户就是因为用别人封装的出现了这个问题

**Comment by amadeus711** [comment]
根据之前的经验是你用了封装的 admin

**Comment by jingtu-Lincoin** [comment]
果然是这样。关闭.env的mock就行了。

**Comment by ZaL0-0** [comment]
> 果然是这样。关闭.env的mock就行了。

我也遇到了相同的问题，但是没有找到大家说的.env mock

> 根据之前的经验是你用了封装的 admin

麻烦问下这是什么意思？ 我也遇到了相同的问题，在子项目写的上传组件可以，引入到父级项目就拿不到response
