### ISSUE TITLE
浅色主题下dropdown的样式bug

### ISSUE THREAD

**Issue by dongnaebi** [TuSimple/naive-ui#3433]
### TuSimple/naive-ui version (版本)
2.32.1

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
chrome103

### System and its version (系统及其版本)
win11

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/dropdown

### Reappearance steps (重现步骤)
浅色模式下，鼠标移入dropdown的选项时，图标消失

### Expected results (期望的结果)
使用自定义的图标（非n-icon），在浅色模式下需要给 .n-dropdown-option-body__prefix 的 z-index 设为1，图标才能显示出来，深色模式正常，暂未对比出差异在哪

### Actual results (实际的结果)
父元素的before（.n-dropdown-menu .n-dropdown-option .n-dropdown-option-body::before）是定位元素，盖住了图标

**Comment by Sepush** [comment]
试着给你的自定义图标套一层` n-icon`
