### ISSUE TITLE
带有背景色的分页

### ISSUE THREAD

**Issue by muchenfine** [TuSimple/naive-ui#3435]
### This function solves the problem (这个功能解决的问题)
设置background属性可以为分页按钮添加背景色。
### Expected API (期望的 API)
设置background属性可以为分页按钮添加背景色。

**Comment by amadeus711** [comment]
<img width="1560" alt="image" src="https://user-images.githubusercontent.com/46394163/183282120-87c1da8a-e36b-4fa2-8c68-22f33ec695fb.png">
