### ISSUE TITLE
在 setup 外使用 dialog 无法渲染 icon

### ISSUE THREAD

**Issue by zhaojh329** [TuSimple/naive-ui#3464]
### TuSimple/naive-ui version (版本)
2.32.1

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
 103.0.5060.134

### System and its version (系统及其版本)
Window 10

### Reappearance link (重现链接)
https://codesandbox.io/s/friendly-sammet-dmz3no

### Reappearance steps (重现步骤)
打开链接后，可以看到 Dropdown 的选项中可以成功渲染 Icon，
但是对话框却不能。

### Expected results (期望的结果)
在 setup 外使用 dialog 可以渲染 icon

### Actual results (实际的结果)
在 setup 外使用 dialog 无法渲染 icon

**Comment by 07akioni** [comment]
createDiscreteApi 是在不同的 API 上下文中运行的，所以 resolveComponent 找不到 n-icon，你必须直接导入 NIcon

**Comment by zhaojh329** [comment]
> createDiscreteApi 是在不同的 API 上下文中运行的，所以 resolveComponent 找不到 n-icon，你必须直接导入 NIcon

但是同样的用法，Dropdown 就能使用 resolveComponent  成功解析。

**Comment by 07akioni** [comment]
> > createDiscreteApi 是在不同的 API 上下文中运行的，所以 resolveComponent 找不到 n-icon，你必须直接导入 NIcon
> 
> 但是同样的用法，Dropdown 就能使用 resolveComponent 成功解析。

Dropdown 在同一个 App 上下文中

**Comment by zhaojh329** [comment]
@07akioni 
Hello, is there a way to use resolveComponent for createDiscreteApi?

**Comment by zhaojh329** [comment]
I found a solution, but one problem remains. Theme and internationalization have not been synced.

**Comment by 07akioni** [comment]
> problem remains. Theme and internationalization ha

You'd better use provider API.

**Comment by 07akioni** [comment]
I'll expose vue app created by `createDiscreteApi` in the next version.

**Comment by zhaojh329** [comment]
> > problem remains. Theme and internationalization ha
> 
> You'd better use provider API.

My project framework dictates that I can only install components globally.
