### ISSUE TITLE
Table slot feature

### ISSUE THREAD

**Issue by dogukanoksuz** [TuSimple/naive-ui#3465]
### This function solves the problem (这个功能解决的问题)
Hello,
If slot feature added to tables it would be great, now it looks like this;

```
{
    title: t("table.actions.title"),
    key: "actions",
    render(row: any) {
      return h(
        NButton,
        {
          strong: true,
          tertiary: true,
          size: "small",
          onClick: () => {
            console.log(row)
          },
        },
        { default: () => "Play" }
      )
    },
  },
```
### Expected API (期望的 API)
<template #headerCell="{ column }">
      <template v-if="column.key === 'name'">
        <span>
          <smile-outlined />
          Name
        </span>
      </template>
    </template>

    <template #bodyCell="{ column, record }">
      <template v-if="column.key === 'name'">
        <a>
          {{ record.name }}
        </a>
      </template>
      <template v-else-if="column.key === 'tags'">
        <span>
          <a-tag
            v-for="tag in record.tags"
            :key="tag"
            :color="tag === 'loser' ? 'volcano' : tag.length > 5 ? 'geekblue' : 'green'"
          >
            {{ tag.toUpperCase() }}
          </a-tag>
        </span>
      </template>
      <template v-else-if="column.key === 'action'">
        <span>
          <a>Invite 一 {{ record.name }}</a>
          <a-divider type="vertical" />
          <a>Delete</a>
          <a-divider type="vertical" />
          <a class="dropdown-link">
            More actions
            <down-outlined />
          </a>
        </span>
      </template>
    </template>

**Comment by 07akioni** [comment]
ref #106
