### ISSUE TITLE
feat(n-dropdown): customizable optionPadding

### ISSUE THREAD

**Issue by OrbisK** [TuSimple/naive-ui#3482]
### This function solves the problem (这个功能解决的问题)
the padding of an option is not adjustable via configprovider
### Expected API (期望的 API)
```ts
const override: GlobalThemeOverrides = {
    Dropdown: {
        optionPadding: `8px 8px`
    }
}
```

**Comment by 07akioni** [comment]
<img width="1474" alt="image" src="https://user-images.githubusercontent.com/18677354/183949240-7b5ee7cc-02f5-4e73-a786-b89708916175.png">

You can use prefix width & suffix width

**Comment by OrbisK** [comment]
and vertical padding? 😅

**Comment by 07akioni** [comment]
> and vertical padding? 😅
> 
> edit: i guess height?

Yep.

**Comment by 07akioni** [comment]
Height is more consistent for implementation.
