### ISSUE TITLE
Menu component, to start routing mode, requires render function，I don't think they are friendly

### ISSUE THREAD

**Issue by jahnli** [TuSimple/naive-ui#355]
### This function solves the problem (这个功能解决的问题)
NAIVEUI has too many render functions  
### Expected API (期望的 API)
Whether to use the Vue-Router mode, which enables the route jump with INDEX as the PATH when navigation is activated

**Comment by jahnli** [comment]
I tried to use NaiveUI in the project, but so many components needed the render function that the parts that could use slots and props still needed the render function, increasing the amount of code

**Comment by jahnli** [comment]
While nice, it feels like the code approach doesn't quite fit Vue's template style.

**Comment by 07akioni** [comment]
It quite need more lines of code but not that much. Maybe about 10 lines for use menu for routing.

I've expalined why we don't add slot API. It won't be added recently.
