### ISSUE TITLE
颜色选择器：点击预设色板颜色 ，不会触发on-complete

### ISSUE THREAD

**Issue by muchenfine** [TuSimple/naive-ui#3652]
### TuSimple/naive-ui version (版本)
2.33.2

### Vue version (Vue 版本)
3.2.38

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
windows

### Reappearance link (重现链接)
https://codesandbox.io/s/goh2tz

### Reappearance steps (重现步骤)

点击预设色板颜色 ，实际也触发了颜色改变，但是并没有回调on-complete

### Expected results (期望的结果)
点击预设色板颜色 ，实际也触发了颜色改变，应该也算on-complete

### Actual results (实际的结果)
颜色选择器：点击预设色板颜色 ，不会触发on-complete	[ 颜色完成改变后的回调（在鼠标移动时候不会调用） ]

**Comment by 07akioni** [comment]
目前是点了确认按钮才算，最好直接和 value 绑定

**Comment by 07akioni** [comment]
> @07akioni 鼠标拖拽时，会有明显卡顿

正常的，浏览器性能跟不上样式用这个速度去改
