### ISSUE TITLE
Badge 处理中动画优化成类似进度动画或调整下闪烁速度可能会更好

### ISSUE THREAD

**Issue by Hucy** [TuSimple/naive-ui#37]
## What problem does the feature solve?
https://www.naiveui.com/zh-CN/os-theme/components/badge#processing
现在处理中的动画，感觉上有点闪烁速度有点快
在设置 `value`  后没有动画，设计上就是这样么
## What does the proposed API look like?

https://www.naiveui.com/zh-CN/os-theme/components/progress

**Comment by 07akioni** [comment]
这个闪烁需要专门的 prop `processing`，不设定没有

**Comment by Hucy** [comment]
https://codesandbox.io/s/13ti9?file=/src/Demo.vue:137-147
```vue
<template>
  <n-space :size="24" align="center">
    <n-badge dot processing>
      <n-avatar />
    </n-badge>
    <n-badge :value="20" processing>
      <n-avatar />
    </n-badge>
    <n-badge dot type="info" processing>
      <n-avatar />
    </n-badge>
  </n-space>
</template>
```
在示例代码中同时设置  `value`  和 `processing` 后没有动画，这个动画只有在设置  `dot`  后生效，本身的设计就是这样么，像是两个不同的展示形式

**Comment by 07akioni** [comment]
![image](https://user-images.githubusercontent.com/18677354/121311210-c5454400-c936-11eb-9c8d-002d98bb97d7.png)
我看是有的，会不会是浏览器问题？

**Comment by Hucy** [comment]
```
System: Windows 10 version 10.0 (64-bit)
Browser: Chrome version 91.0.4472.77 (64-bit)
Display Resolution: 1920 * 1080
```
放大页面后看到了，直接在页面上看动画不明显，以为没有呢，还有就是展示小的情况下，动画闪烁很快

**Comment by 07akioni** [comment]
> ```
> System: Windows 10 version 10.0 (64-bit)
> Browser: Chrome version 91.0.4472.77 (64-bit)
> Display Resolution: 1920 * 1080
> ```
> 
> 放大页面后看到了，直接在页面上看动画不明显，以为没有呢，还有就是展示小的情况下，动画闪烁很快

这个我自己感觉不太好解决，没有 window 电脑。从理论上写的样式应该是没问题。有兴趣调查一下原因吗？

**Comment by myst729** [comment]
Mac在视网膜屏上没问题，外接2K显示器就能看到明显的闪烁

**Comment by 07akioni** [comment]
> 题，外接2K显示器就能看到明显的闪烁。放大到

确实能看出来... 这我有点绝望啊

**Comment by 07akioni** [comment]
> ```
> System: Windows 10 version 10.0 (64-bit)
> Browser: Chrome version 91.0.4472.77 (64-bit)
> Display Resolution: 1920 * 1080
> ```
> 
> 放大页面后看到了，直接在页面上看动画不明显，以为没有呢，还有就是展示小的情况下，动画闪烁很快

这感觉理论上是 chrome 的 bug

**Comment by Hucy** [comment]
> > ```
> > System: Windows 10 version 10.0 (64-bit)
> > Browser: Chrome version 91.0.4472.77 (64-bit)
> > Display Resolution: 1920 * 1080
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 放大页面后看到了，直接在页面上看动画不明显，以为没有呢，还有就是展示小的情况下，动画闪烁很快
> 
> 这感觉理论上是 chrome 的 bug

https://github.com/TuSimple/naive-ui/blob/d2b55889d8141844ec84e2eddc9e2d2cae76c20b/src/badge/src/styles/index.cssr.ts#L18

是这个原因么

**Comment by myst729** [comment]
@Hucy  
Safari 和 Firefox 的表现就是比较明显的跳桢。Chrome 更像是锁定 FPS 导致 2K 屏的动画加速。

**Comment by 07akioni** [comment]
感觉这个我一时半会可能没法改，如果有人找到方法的话提个 PR 或者说一下。

**Comment by Hucy** [comment]
> 感觉这个我一时半会可能没法改，如果有人找到方法的话提个 PR 或者说一下。
> 
> 浏览器确实会有很多奇奇怪怪的边缘情况。

1. 这个 `0.5px` 是必须的么，可以统一设置为 `1px` 
2. 或者使用  media query 兼容下

**Comment by 07akioni** [comment]
> > 感觉这个我一时半会可能没法改，如果有人找到方法的话提个 PR 或者说一下。
> > 浏览器确实会有很多奇奇怪怪的边缘情况。
> 
> 1. 这个 `0.5px` 是必须的么，可以统一设置为 `1px`
> 2. 或者使用  media query 兼容下

你换成整数 px 的话是没问题的吗？我当时用整数在 MBP 上是会出问题。

**Comment by myst729** [comment]
> > 感觉这个我一时半会可能没法改，如果有人找到方法的话提个 PR 或者说一下。
> > 浏览器确实会有很多奇奇怪怪的边缘情况。
> 
> 1. 这个 `0.5px` 是必须的么，可以统一设置为 `1px`
> 2. 或者使用  media query 兼容下

media query 判断 dpr或许是个解法

**Comment by 07akioni** [comment]
> > > 感觉这个我一时半会可能没法改，如果有人找到方法的话提个 PR 或者说一下。
> > > 浏览器确实会有很多奇奇怪怪的边缘情况。
> > 
> > 
> > 
> > 1. 这个 `0.5px` 是必须的么，可以统一设置为 `1px`
> > 2. 或者使用  media query 兼容下
> 
> media query 判断 dpr或许是个解法

应该是可以的，不过我先得确定一下在 windows 上改成整数会不会好呢？或者说在 dpr 为 1 的设备上改成整数。

**Comment by Hucy** [comment]
> > > 感觉这个我一时半会可能没法改，如果有人找到方法的话提个 PR 或者说一下。
> > > 浏览器确实会有很多奇奇怪怪的边缘情况。
> > 
> > 
> > 
> > 1. 这个 `0.5px` 是必须的么，可以统一设置为 `1px`
> > 2. 或者使用  media query 兼容下
> 
> 你换成整数 px 的话是没问题的吗？我当时用整数在 MBP 上是会出问题。

这个问题具体是指什么现象？设置的值是 `5px` 么。我改成 `1px` 后好像没问题。Windows 下的我回去测试下

**Comment by 07akioni** [comment]
> > > > 感觉这个我一时半会可能没法改，如果有人找到方法的话提个 PR 或者说一下。
> > > > 浏览器确实会有很多奇奇怪怪的边缘情况。
> > > 
> > > 
> > > 
> > > 1. 这个 `0.5px` 是必须的么，可以统一设置为 `1px`
> > > 2. 或者使用  media query 兼容下
> > 
> > 
> > 你换成整数 px 的话是没问题的吗？我当时用整数在 MBP 上是会出问题。
> 
> 这个问题具体是指什么现象？设置的值是 `5px` 么。我改成 `1px` 后好像没问题。Windows 下的我回去测试下

比如说改成一个接近的整数值

**Comment by Hucy** [comment]
**1920x1080_1080p:**


![1920x1080_1080p](https://user-images.githubusercontent.com/11373955/122430086-df7dc280-cfc5-11eb-810e-0b3a53cd979b.gif)


**3840x2160_4k:**


![3840x2160_4k](https://user-images.githubusercontent.com/11373955/122430118-e4427680-cfc5-11eb-9f2e-5a1fc25f7328.gif)

**Comment by 07akioni** [comment]
> Yes, at present, the flashing speed is too fast, which leads to the phenomenon of stalling. Would you consider supporting custom speed

This is a bug of chrome. I have no windows laptop so doesn't know how to fix it.

**Comment by hanjialin** [comment]
edge这个问题到现在依然存在。。
