### ISSUE TITLE
[docs] Why use `npm i -D native-ui` for installing

### ISSUE THREAD

**Issue by lchtao26** [TuSimple/naive-ui#378]
NOTE: It is neither a bug nor a feature request, it's a question.

I have no idea why use `npm i -D native-ui` for installing, since `-D` flag will install package into `devDependencies` fileld, which webpack will not include into the final bundle.

**Comment by 07akioni** [comment]
You won't release your app as a package, so UI is your develop dependency.

If you are building a library based on naive ui, you can just install it at as dependency.

**Comment by lchtao26** [comment]
> You won't release your app as a package, so UI is your develop dependency.
> 
> If you are building a library based on naive ui, you can just install it at as dependency.

It's true that I won't release my app as a package, but the UI components will be used in my final production web app(like a website). In this case, should I install it as dependency?

**Comment by 07akioni** [comment]
> > You won't release your app as a package, so UI is your develop dependency.
> > If you are building a library based on naive ui, you can just install it at as dependency.
> 
> It's true that I won't release my app as a package, but the UI components will be used in my final production web app(like a website). In this case, should I install it as dependency?

In practice both should work.

In theory, you package is always in develop status and never been released itself.
