### ISSUE TITLE
Mobile responsive on datatable

### ISSUE THREAD

**Issue by liho98** [TuSimple/naive-ui#379]
### This function solves the problem (这个功能解决的问题)
Mobile responsive on datatable
### Expected API (期望的 API)
Mobile responsive on datatable
![image](https://user-images.githubusercontent.com/44250267/124424874-52df4c80-dd9a-11eb-8b2d-12e824ff86ec.png)
 the official website datatable not responsive as well

**Comment by Fnzero** [comment]
You can customize the column width.

**Comment by 07akioni** [comment]
> ### This function solves the problem (这个功能解决的问题)
> Mobile responsive on datatable
> 
> ### Expected API (期望的 API)
> Mobile responsive on datatable
> ![image](https://user-images.githubusercontent.com/44250267/124424874-52df4c80-dd9a-11eb-8b2d-12e824ff86ec.png)
> the official website datatable not responsive as well

You can use scrollX to make it scrollable in horizontal direction.

**Comment by liho98** [comment]
I think, the documentation should be modified or enhanced to make it mobile resposive and to indicate how the datatable could be responsvie.

**Comment by 07akioni** [comment]
> I think, the documentation should be modified or enhanced to make it mobile resposive and to indicate how the datatable could be responsvie.

In fact there is no builtin responsive solution, currently the best way is to set `scroll-x`.

**Comment by liho98** [comment]
> scroll-x

possible to reopen this issue as feature request, which allow overflow: auto to be happed just like how pure html & css works

**Comment by 07akioni** [comment]
> as feature request, which allow overflow: auto to b

It's impossible to make it work as `overflow: auto`.

If you want to hide some columns on different screens, just modify the PR and I'll reopen it.
