### ISSUE TITLE
Checkbox component enhancements  

### ISSUE THREAD

**Issue by jahnli** [TuSimple/naive-ui#387]
### This function solves the problem (这个功能解决的问题)
 component enhancements  
### Expected API (期望的 API)
1. Through the props   To achieve the effect of all selection
2.Use the min and Max attributes to limit the number of items that can be checked.

**Comment by Fnzero** [comment]
1.I think you can use  `n-checkbox-group` 's v-model to set the group selection
2.planned

**Comment by 07akioni** [comment]
1. won't do

**Comment by 07akioni** [comment]
fixed in https://github.com/TuSimple/naive-ui/pull/491
