### ISSUE TITLE
n-date-picker range should consider an empty array as an empty value

### ISSUE THREAD

**Issue by wc-matteo** [TuSimple/naive-ui#392]
### TuSimple/naive-ui version (版本)
2.15.3

### Vue version (Vue 版本)
3.1.4

### Browser and its version (浏览器及其版本)
chrome 91.0.4472.124

### System and its version (系统及其版本)
windows 10

### Reappearance link (重现链接)
https://codesandbox.io/s/wandering-worker-dzi14?file=/src/Demo.vue

### Reappearance steps (重现步骤)
use an empty array as n-date-picker range v-model

### Expected results (期望的结果)
the empty array is conidered an empty value

### Actual results (实际的结果)
the empty array results in an error: RangeError - Invalid time value

**Comment by 07akioni** [comment]
Won't do, `[]` is a misformatted value.
