### ISSUE TITLE
alert component enhancements

### ISSUE THREAD

**Issue by jahnli** [TuSimple/naive-ui#397]
### This function solves the problem (这个功能解决的问题)
Lack of customization
### Expected API (期望的 API)
1.Custom Icon
2.Writing in the middle

**Comment by 07akioni** [comment]
1. https://www.naiveui.com/zh-CN/os-theme/components/alert#icon
2. Title in the middle doesn't look good. I haven't find some examples like that. If you can find some convincing examples I'll reopen the issue.
