### ISSUE TITLE
time picker step values

### ISSUE THREAD

**Issue by wc-matteo** [TuSimple/naive-ui#399]
### This function solves the problem (这个功能解决的问题)
being able to see and pick only a subset of available values. Especially great for ux and to have a simple ui
### Expected API (期望的 API)
https://www.antdv.com/components/time-picker/#interval-option

**Comment by wc-matteo** [comment]
ah already present: https://github.com/TuSimple/naive-ui/pull/36
sorry

**Comment by 07akioni** [comment]
> ah already present: #36
> sorry

Yes that is a pending PR. We hope it can be finished😂
