### ISSUE TITLE
unused var noDataContent in select component document

### ISSUE THREAD

**Issue by joanne3634** [TuSimple/naive-ui#40]
### Environment Info

- Naive UI version: 2.11.4
- Browser Info: Chome 89.0.4389.90
- System Info: Ubuntu 18.04.5 LTS

### What is actually happening?

In the select component remote feature (single and multiple) documents, there is an unused variable `noDataContent` in the sample code, is it the var for placeholder?

**Comment by 07akioni** [comment]
It's a mistake. Maybe we need a new api to to the thing. Currently let us just remove it and see what's users' demand.
