### ISSUE TITLE
tabs  detail processing 

### ISSUE THREAD

**Issue by jahnli** [TuSimple/naive-ui#400]
### This function solves the problem (这个功能解决的问题)
detail processing 
### Expected API (期望的 API)
At the moment, it looks bloated when you delete a lot of ICONS
Whether to refer to the Element-Plus details, the delete icon is not displayed by default, and is displayed when hovering

**Comment by jahnli** [comment]
![image](https://user-images.githubusercontent.com/20943608/124464621-fe9e9180-ddc6-11eb-9049-d6b46c3f18ca.png)

**Comment by 07akioni** [comment]
I think following chrome's manner is okay.

![image](https://user-images.githubusercontent.com/18677354/124481847-4fb88080-dddb-11eb-8e1d-4ba043b7a212.png)

**Comment by jahnli** [comment]
I think it's good to have more configuration for users

**Comment by 07akioni** [comment]
> I think it's good to have more configuration for users

Sometimes we will make some opinionated decisions. I don't like width shifts, but it width not shifts, cross mark will overlay contents in the tab.
