### ISSUE TITLE
n-image cannot set rounded corners, and provides rounded corners api

### ISSUE THREAD

**Issue by TuiMao233** [TuSimple/naive-ui#409]
### This function solves the problem (这个功能解决的问题)
n-image can set rounded corners
### Expected API (期望的 API)
`<n-image rounded width="32" src="https://07akioni.oss-cn-beijing.aliyuncs.com/07akioni.jpeg" />`

**Comment by Fnzero** [comment]
We will not do that, you can add the style to change it.

**Comment by 07akioni** [comment]
`style="border-radius: 50%;"`

**Comment by TuiMao233** [comment]
No, I mean, the setting style cannot take effect, so I need you to have this attribute.

**Comment by TuiMao233** [comment]
![image](https://user-images.githubusercontent.com/49724027/124689936-0156cf00-df0c-11eb-82ea-e18ac47b6747.png)
![image](https://user-images.githubusercontent.com/49724027/124689945-04ea5600-df0c-11eb-9e01-66a1b64610ab.png)
