### ISSUE TITLE
All layout components cannot add a content type attribute, use it with wind

### ISSUE THREAD

**Issue by TuiMao233** [TuSimple/naive-ui#413]
### This function solves the problem (这个功能解决的问题)
More convenient use of tailwind
### Expected API (期望的 API)
~~~html
<n-layout-sider
    :collapsed-width="66"
    :width="100"
    content-class="rounded-3xl mt-28 flex flex-col items-center"
  >
    asd
  </n-layout-sider>
~~~

**Comment by Fnzero** [comment]
We have not provided content-class, we only provide `content-style`

**Comment by 07akioni** [comment]
For layout we doesn't provide such interface since it may break default behavior. Just wrap another `<div />`.

**Comment by 07akioni** [comment]
For layout we doesn't provide such interface since it may break default behavior. Just wrap another `<div />`.
