### ISSUE TITLE
Menu Unable to customize the menu to expand the left arrow

### ISSUE THREAD

**Issue by TuiMao233** [TuSimple/naive-ui#414]
### This function solves the problem (这个功能解决的问题)
Can be customized
![image](https://user-images.githubusercontent.com/49724027/124584123-75e72a80-de86-11eb-9bbb-1f7dcaa27d75.png)

### Expected API (期望的 API)
~~~jsx
<n-menu
   right-arrow={<n-icon>....<n-icon>}
 />
~~~

**Comment by Fnzero** [comment]
You want the expand arrow display on left?  Considering the display of the icon, the style on the left of the expand icon is not friendly to display.

**Comment by 07akioni** [comment]
> You want the expand arrow display on left? Considering the display of the icon, the style on the left of the expand icon is not friendly to display.

He wants to customize arrow of menu. See https://ant.design/components/menu/#Menu `expandIcon`
