### ISSUE TITLE
Menu v-model:value | default-value should be bound as an array

### ISSUE THREAD

**Issue by TuiMao233** [TuSimple/naive-ui#415]
### This function solves the problem (这个功能解决的问题)
Solve the problem of multi-level routing highlighting and multi-level highlighting

Currently I can only solve it like this

~~~html
<n-menu
      :options="mainMenuOptions"
      :value="route.meta.pathMaps?.[0]"
      @update:value="router.push($event)"
/>
~~~

It's so weird

### Expected API (期望的 API)
~~~html
<n-menu
     :value="['/', '/home']"
/>
~~~

**Comment by Fnzero** [comment]
I think you can use you can render `label` as `<router-link />`  to set route.
