### ISSUE TITLE
n-upload: when setting prop 'multiple="true"'  as well as  'v-model:file-list="file-list"', multiple upload not work. only one last file selected. n-upload 设置 multiple="true"的时候，如果同时绑定 v-model:file-list="file-list"时，多选上传失效，只能上传一个

### ISSUE THREAD

**Issue by madgd** [TuSimple/naive-ui#418]
### TuSimple/naive-ui version (版本)
2.15.3

### Vue version (Vue 版本)
3.1.4

### Browser and its version (浏览器及其版本)
91.0.4472.114

### System and its version (系统及其版本)
MacOS(11.4)

### Reappearance link (重现链接)
https://codesandbox.io/s/eloquent-shaw-339jm?file=/src/Demo.vue

### Reappearance steps (重现步骤)
add multiple="true" to n-upload, try upload multiple files.

### Expected results (期望的结果)
multiple files added.

### Actual results (实际的结果)
last one added

### Remarks (补充说明)
if remove 'v-model:file-list="file-list"',  multiple files added

**Comment by 07akioni** [comment]
@Fnzero 这个优先处理一下
