### ISSUE TITLE
[NScrollBar] Click on the invisible rails area

### ISSUE THREAD

**Issue by cefiro** [TuSimple/naive-ui#4186]
### This function solves the problem (这个功能解决的问题)
If the height or width is too large, the rail becomes small and it is more convenient to click on the invisible area.
### Expected API (期望的 API)
Example on the video, as implemented in ElementPlus:

https://user-images.githubusercontent.com/1112601/207095331-f52d877c-3390-4ded-a37e-12d00a0c18f4.mp4

**Comment by 07akioni** [comment]
Their scrollbar works like that becase it's a native scrollbar that takes actual space.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
