### ISSUE TITLE
add an event for when the user clicks on the overlay/mask of a dialog

### ISSUE THREAD

**Issue by wc-matteo** [TuSimple/naive-ui#419]
### This function solves the problem (这个功能解决的问题)
the ability to do something when the user closes the dialog that way
### Expected API (期望的 API)
I'd use onClose for that as well, since technically it's a way to close the dialog

**Comment by Fnzero** [comment]
I think you can use `on-update:show`

**Comment by 07akioni** [comment]
maskClosable 不够用吗？现在 useDialog 是不是支持了 maskClosable？有别的库有相关的属性吗？

@Talljack

**Comment by 07akioni** [comment]
@wc-matteo Isn't maskClosable enough?

**Comment by wc-matteo** [comment]
no. The issue here is that there is no event for when the user closes the dialog by clicking on the mask/overlay. So you have no way to know.

**Comment by Talljack** [comment]
@07akioni I saw that both antd and iview are binding the mask click event to the onCancel event, other frame not support.

**Comment by 07akioni** [comment]
> no. The issue here is that there is no event for when the user closes the dialog by clicking on the mask/overlay. So you have no way to know.

In which scene you need to know this?

**Comment by wc-matteo** [comment]
let's say there is a dialog with a confirmation. The user can confirm or he can cancel/close the dialog. If he closes the dialog by clicking on the mask/overlay, I have no way to react to that
