### ISSUE TITLE
pass return of file upload request to on-finish

### ISSUE THREAD

**Issue by viztor** [TuSimple/naive-ui#421]
### This function solves the problem (这个功能解决的问题)
currently there is no way to use the return from upload
### Expected API (期望的 API)
on-finish({ fileInfo, result })

**Comment by Fnzero** [comment]
We have `on-finish`

**Comment by viztor** [comment]
> We have `on-finish`

on-finish only pass FileInfo, there is no currently viable way to retrieve the upload result from the POST request.

**Comment by 07akioni** [comment]
@Fnzero 他们要从拿到的是传递完的 http 结果，看看现在有没有方法能解决？
