### ISSUE TITLE
data-table 缺少 paging 类型

### ISSUE THREAD

**Issue by Lanseria** [TuSimple/naive-ui#422]
### TuSimple/naive-ui version (版本)
2.15.3

### Vue version (Vue 版本)
3.1.4

### Browser and its version (浏览器及其版本)
Edge

### System and its version (系统及其版本)
windows11

### Reappearance link (重现链接)
https://github.com/TuSimple/naive-ui/blob/main/src/data-table/src/DataTable.tsx#L94

### Reappearance steps (重现步骤)
文档里有paging属性但实际没有找到具体定义

### Expected results (期望的结果)
有类型定义

### Actual results (实际的结果)
没有

**Comment by 07akioni** [comment]
Sorry, we have a mistake in document. Please use `remote`. `paging` doesn't exist. We will change the doc.
