### ISSUE TITLE
Zooming value does not initialize when switching a picture in N-Image-Group Component 

### ISSUE THREAD

**Issue by LYErin** [TuSimple/naive-ui#423]
### TuSimple/naive-ui version (版本)
2.15.3

### Vue version (Vue 版本)
3.1.4

### Browser and its version (浏览器及其版本)
91.0.4472.124

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://codesandbox.io/s/jidld

### Reappearance steps (重现步骤)
1、 zooming a picture in N-Image-Group Component
2、switch a picture
3、zoom this picture; the zooming effect is not right!

### Expected results (期望的结果)
Zooming value  initialized when switching a picture

### Actual results (实际的结果)
The zooming effect is not right!

**Comment by Fnzero** [comment]
we cannot reproduce it.

**Comment by LYErin** [comment]
I have resolved this problem but can not covered the test.
[pr](https://github.com/TuSimple/naive-ui/pull/430)
