### ISSUE TITLE
n-image cannot set rounded corners, and provides rounded corners api

### ISSUE THREAD

**Issue by TuiMao233** [TuSimple/naive-ui#424]
### This function solves the problem (这个功能解决的问题)
![image](https://user-images.githubusercontent.com/49724027/124689936-0156cf00-df0c-11eb-82ea-e18ac47b6747.png)
![image](https://user-images.githubusercontent.com/49724027/124689945-04ea5600-df0c-11eb-9e01-66a1b64610ab.png)
#409 

### Expected API (期望的 API)
`<n-image rounded width="32" src="https://07akioni.oss-cn-beijing.aliyuncs.com/07akioni.jpeg" />`

**Comment by Fnzero** [comment]
We will not do that, `<n-image style="border-radius: 100%;" width="32" src="https://07akioni.oss-cn-beijing.aliyuncs.com/07akioni.jpeg" />`
