### ISSUE TITLE
Please, please be optimistic about the problem, I can not set the rounded corner picture

### ISSUE THREAD

**Issue by TuiMao233** [TuSimple/naive-ui#427]
### This function solves the problem (这个功能解决的问题)
This is the way I followed yours, the picture does not appear rounded corners

![image](https://user-images.githubusercontent.com/49724027/124689936-0156cf00-df0c-11eb-82ea-e18ac47b6747.png)
![image](https://user-images.githubusercontent.com/49724027/124689945-04ea5600-df0c-11eb-9e01-66a1b64610ab.png)
#409 

### Expected API (期望的 API)
#409

**Comment by Talljack** [comment]
You can set ```js style="border-radius:50%;"```on img,like that 
![image](https://user-images.githubusercontent.com/34439652/124703130-4d157280-df24-11eb-9f4b-b704bce6084d.png)

**Comment by TuiMao233** [comment]
Yes, I know, it can be set like this
~~~html
<n-image class="my-image" width="32" src="https://07akioni.oss-cn-beijing.aliyuncs.com/07akioni.jpeg" />
~~~
~~~css
.my-image img {
   border-radius: 50%;
}
~~~

But I think it should be like this
~~~html
<n-image style="border-radius:50%;" width="32" src="https://07akioni.oss-cn-beijing.aliyuncs.com/07akioni.jpeg" />
~~~

or

~~~html
<n-image rounded width="32" src="https://07akioni.oss-cn-beijing.aliyuncs.com/07akioni.jpeg" />
~~~

Okay, maybe you think this is a bit unreasonable, this is the last time I have raised this issue.

**Comment by 07akioni** [comment]
> , so there are multiple roots of the component, which makes the styles unable to be inherited.

We can make the img `border-radius` inherited, how do you think of it.

**Comment by Talljack** [comment]
I think you can setting the border-radius of img to inherit can resolve the problem
If it is round, the requirement must be square, this will destroy the picture

**Comment by 07akioni** [comment]
@TuiMao233 We will fix it

**Comment by 07akioni** [comment]
Now border radius should work
