### ISSUE TITLE
Carousel 组件当点击轮播指示点后并且不做任何操作时，轮播指示点的active状态不正确

### ISSUE THREAD

**Issue by kungege** [TuSimple/naive-ui#434]
### TuSimple/naive-ui version (版本)
2.15.3

### Vue version (Vue 版本)
3.1.4

### Browser and its version (浏览器及其版本)
91.0.4472.114

### System and its version (系统及其版本)
11.3.1 

### Reappearance link (重现链接)
https://codesandbox.io/s/wntld

### Reappearance steps (重现步骤)
点击轮播指示点等待autoplay进入下一张图片

### Expected results (期望的结果)
轮播指示点状态正确

### Actual results (实际的结果)
轮播指示点状态不正确

**Comment by 07akioni** [comment]
这个严格来说也算个 bug。

这个是 `:focus` 的样式，为了 a11y 的键盘操作准备的。

**Comment by 07akioni** [comment]
我发现 chrome 在寻找第一个 tab 焦点的时候会根据鼠标上次点击的地方，高级
