### ISSUE TITLE
在移动端 深色主题的情况下，输入框的背景色和文本颜色均为白色

### ISSUE THREAD

**Issue by Eve-Wings** [TuSimple/naive-ui#439]
### TuSimple/naive-ui version (版本)
2.14.0

### Vue version (Vue 版本)
3.1.2

### Browser and its version (浏览器及其版本)
华为浏览器 11.1.2.301(也包括其他手机的浏览器)

### System and its version (系统及其版本)
Android 9

### Reappearance link (重现链接)
https://github.com/Eve-Wings/toDoList

### Reappearance steps (重现步骤)
这是我个人做的一个小项目小工具，这个bug是后来通过配置输入框的样式修复了。

在PC端的浏览器中，chrome 火狐 Edge，在深色主题的情况下，输入框的颜色暗灰色，而所输入的文本是白色，用户是可以看到自己所输入的文本的。
但是使用移动端的浏览器时，输入框的颜色是白色，但所输入的文本也是白色，用户是看不到自己输入的文本的。

重现方法：

在深色主题下，input组件，然后手机端上测试；

可以在我提供的仓库中，也可以src/assets/css/style.less中，将171~185行代码删除之后，在移动端上，点击蓝色底的加号按钮弹出表单进行测试。

(在这里还有一个bug，部分移动端上，使用图标的按钮会出现图标丢失的异常，初步怀疑可能是移动端上的浏览器中的层叠关系不一致导致的)

### Expected results (期望的结果)
移动端上，输入框的样式能够和在PC端上的样式一样

### Actual results (实际的结果)
移动端上的输入框样式发生了改变

**Comment by Fnzero** [comment]
1.确认是否是移动端媒体查询范围下有上层自定义样式影响了
2.图标丢失的情况为bug, 在计划修复了

**Comment by Eve-Wings** [comment]
> 1.确认是否是移动端媒体查询范围下有上层自定义样式影响了
> 2.图标丢失的情况为bug, 在计划修复了

基本上所有的样式都是用来调整布局，也没有更上层的自定义样式了

**Comment by Eve-Wings** [comment]
> 1.确认是否是移动端媒体查询范围下有上层自定义样式影响了
> 2.图标丢失的情况为bug, 在计划修复了

我再做一些调整试一下，可能是我有一个事件上绑了样式修改

**Comment by Eve-Wings** [comment]
> 1.确认是否是移动端媒体查询范围下有上层自定义样式影响了
> 2.图标丢失的情况为bug, 在计划修复了

我把所有的有关颜色的样式、有关样式修改的事件全部去掉之后，在移动端上、深色主题的输入框颜色还是白色、文本也是白色

**Comment by Eve-Wings** [comment]
顺带一提……一些移动端上，Gradient Text 这个组件也会出现样式异常的情况

**Comment by Fnzero** [comment]
1.试验了一下，华为浏览器确实存在这个问题， chrome正常， 先记为Bug
2.Gradient Text什么样的异常可以发个截图吗，我们移动端的适配只保证了能用，可能会有一些问题存在

**Comment by Fnzero** [comment]
也可能是华为浏览器自己做了一些未知的修改，反正建议不要用这种手机自带的浏览器吧

**Comment by Eve-Wings** [comment]
> 1.试验了一下，华为浏览器确实存在这个问题， chrome正常， 先记为Bug
> 2.Gradient Text什么样的异常可以发个截图吗，我们移动端的适配只保证了能用，可能会有一些问题存在

1. 手机系统自带的浏览器基本存在问题(像华为、小米这种、目前还没测试ios系统的手机上自带的浏览器)
2. Gradient Text在**部分**移动端上不会有渐变的效果，只会是普通的字体颜色，虽然这个问题不算太大……
 
我现在外出，截图会晚一点

**Comment by Eve-Wings** [comment]
> 也可能是华为浏览器自己做了一些未知的修改，反正建议不要用这种手机自带的浏览器吧

基本也是这种情况吧[扶额
我是发给我朋友的时候他们都用手机直接打开了，然后就给我报了一堆issue我才发现这么个事的

**Comment by Eve-Wings** [comment]
> > 1.试验了一下，华为浏览器确实存在这个问题， chrome正常， 先记为Bug
> > 2.Gradient Text什么样的异常可以发个截图吗，我们移动端的适配只保证了能用，可能会有一些问题存在
> 
> 1. 手机系统自带的浏览器基本存在问题(像华为、小米这种、目前还没测试ios系统的手机上自带的浏览器)
> 2. Gradient Text在**部分**移动端上不会有渐变的效果，只会是普通的字体颜色，虽然这个问题不算太大……
> 
> 我现在外出，截图会晚一点

1. safari的话，没别的问题，主要就是按钮图标丢失……

**Comment by 07akioni** [comment]
> > > 1.试验了一下，华为浏览器确实存在这个问题， chrome正常， 先记为Bug
> > > 2.Gradient Text什么样的异常可以发个截图吗，我们移动端的适配只保证了能用，可能会有一些问题存在
> > 
> > 
> > 
> > 1. 手机系统自带的浏览器基本存在问题(像华为、小米这种、目前还没测试ios系统的手机上自带的浏览器)
> > 2. Gradient Text在**部分**移动端上不会有渐变的效果，只会是普通的字体颜色，虽然这个问题不算太大……
> > 
> > 我现在外出，截图会晚一点
> 
> 1. safari的话，没别的问题，主要就是按钮图标丢失……

按钮的问题应该是修好了

**Comment by 07akioni** [comment]
@Fnzero 这个白色背景的问题咋样了？

**Comment by yaoyylm** [comment]
白色背景的问题可能是华为浏览器不支持#0000 这种hex形式的透明度。
改用rgba(0,0,0,0)发现可以。
usb连上手机可以用chrome://inspect/#devices进行调试😄

**Comment by 07akioni** [comment]
> 白色背景的问题可能是华为浏览器不支持`#0000` 这种hex形式的透明度。
> 改用rgba(0,0,0,0)发现可以。
> usb连上手机可以用chrome://inspect/#devices进行调试😄

如果是这样那是真的草

**Comment by Eve-Wings** [comment]
> 白色背景的问题可能是华为浏览器不支持`#0000` 这种hex形式的透明度。
> 改用rgba(0,0,0,0)发现可以。
> usb连上手机可以用chrome://inspect/#devices进行调试😄

如果是这样那是真的大草特草

**Comment by 07akioni** [comment]
> > 白色背景的问题可能是华为浏览器不支持`#0000` 这种hex形式的透明度。
> > 改用rgba(0,0,0,0)发现可以。
> > usb连上手机可以用chrome://inspect/#devices进行调试😄
> 
> 如果是这样那是真的大草特草

其他组件呢，我看用到这个 #0000 的其实非常多，比如 pagination

**Comment by zerotower69** [comment]
亲测华为浏览器上很多css样式还未支持，其内核还停留在10+年的版本，实在感人肺腑。

**Comment by 07akioni** [comment]
很久没有回复了，暂时关闭
