### ISSUE TITLE
n-tabs希望增加两侧指示器箭头

### ISSUE THREAD

**Issue by qqfei1858** [TuSimple/naive-ui#440]
### This function solves the problem (这个功能解决的问题)
虽然有滚轮滚动,但对于web PC端来说,如果没有指示箭头,在用户使用时并不知道鼠标滚轮能滚动操作,希望增加此功能,或者提供方法,在solt中调用
### Expected API (期望的 API)
无需API

**Comment by 07akioni** [comment]
won't do

**Comment by 07akioni** [comment]
会考虑增加 antd 那样的 dropdown
