### ISSUE TITLE
n-select选择一个值后，给传入的options重新赋值（其中有的选项的disabled设为true），部分选项样式显示不正确

### ISSUE THREAD

**Issue by bljessica** [TuSimple/naive-ui#441]
### TuSimple/naive-ui version (版本)
2.15.3

### Vue version (Vue 版本)
3.1.4

### Browser and its version (浏览器及其版本)
Chrome(91.0.4472.114)

### System and its version (系统及其版本)
Ubuntu 20.04.2 LTS

### Reappearance link (重现链接)
https://codesandbox.io/s/spring-feather-cfzej

### Reappearance steps (重现步骤)
n-select选择第一个选项，然后点击reset按钮，此时再点开n-select会发现部分选项样式不正确

### Expected results (期望的结果)
n-select第二、三个选项样式为disabled样式

### Actual results (实际的结果)
n-select第三个选项样式为disabled样式，第三个选项样式为正常样式

**Comment by songjianet** [comment]
我也遇到这个问题了，正在尝试通过源码查找问题（I have also encountered this problem, and I am trying to find the problem through the source code）
