### ISSUE TITLE
n-tree can not select a node when setting "v-model" 

### ISSUE THREAD

**Issue by LYErin** [TuSimple/naive-ui#443]
### TuSimple/naive-ui version (版本)
2.15.3

### Vue version (Vue 版本)
3.1.4

### Browser and its version (浏览器及其版本)
91.0.4472.124

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://codesandbox.io/s/zw5iz

### Reappearance steps (重现步骤)
n-tree can not select a node when setting "v-model" in single select or multiple

### Expected results (期望的结果)
select a node correctly

### Actual results (实际的结果)
can not select

**Comment by Fnzero** [comment]
You should use `ref`.
