### ISSUE TITLE
数据表格分页跳转，输入页数回车后，无法自动跳转

### ISSUE THREAD

**Issue by ljqlynch** [TuSimple/naive-ui#446]
### TuSimple/naive-ui version (版本)
2.15.1

### Vue version (Vue 版本)
3.0.5

### Browser and its version (浏览器及其版本)
Chrome(91.0.4472.124)

### System and its version (系统及其版本)
Windows 10 家庭中文版(21H1)

### Reappearance link (重现链接)
https://codesandbox.io/s/optimistic-pascal-grvk3?file=/src/Demo.vue

### Reappearance steps (重现步骤)
在数据表格输入分页回车后，无法跳转，但是触发了onChange函数

### Expected results (期望的结果)
希望可以跳转

### Actual results (实际的结果)
实际没跳转

**Comment by 07akioni** [comment]
`page` is controlled manner. If you set `page: 1`, page will always be 1. Just remove `page: 1`.
