### ISSUE TITLE
Tabs component not work with wrapped component

### ISSUE THREAD

**Issue by Nikhilchandra-Rathod** [TuSimple/naive-ui#460]
### TuSimple/naive-ui version (版本)
2.15.4

### Vue version (Vue 版本)
3.1.4

### Browser and its version (浏览器及其版本)
Chrome (91)

### System and its version (系统及其版本)
Windows 10

### Reappearance link (重现链接)
https://codesandbox.io/s/modern-frog-fnie4

### Reappearance steps (重现步骤)
- Open link in browser

### Expected results (期望的结果)
- It should render tabs

### Actual results (实际的结果)
- Nothing display

### Remarks (补充说明)
- I tried this same wrapper things with ant design system and working perfectly fine with all the components.
- In Naive UI, I am having problems with tabs and grid components.
- I really need this wrapper components so can you suggest any way can solve this bug ?

**Comment by Volankey** [comment]
Current component implementations do not support this use at this time.

**Comment by Volankey** [comment]
I think we should refactor tab. @07akioni

**Comment by 07akioni** [comment]
> I think we should refactor tab. @07akioni

In fact I don't know what to do to unwrap the component, you can have a try.

**Comment by Talljack** [comment]
> > I think we should refactor tab. @07akioni
> 
> In fact I don't know what to do to unwrap the component, you can have a try.

Can this be turned off? I don’t think many users would use it like this. @07akioni

**Comment by 07akioni** [comment]
> > I think we should refactor tab. @07akioni
> 
> In fact I don't know what to do to unwrap the component, you can have a try.

I can't find a way to get the child info of the wrapped component, so for me it's impossible to make wrapped component work in tabs.

If anyone has solution, feel free to leave a message. I'll reopen the issue.
