### ISSUE TITLE
n-upload before-upload file parameter object not reactive

### ISSUE THREAD

**Issue by wc-matteo** [TuSimple/naive-ui#464]
### TuSimple/naive-ui version (版本)
2.15.4

### Vue version (Vue 版本)
3.1.4

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
win 10

### Reappearance link (重现链接)
https://codesandbox.io/s/green-rain-fvnfm

### Reappearance steps (重现步骤)
try to use the percentage from the file param in before-upload event from n-upload

### Expected results (期望的结果)
the percentage is updated when uploading

### Actual results (实际的结果)
the percentage is not updated when uploading

### Remarks (补充说明)
change event works

**Comment by 07akioni** [comment]
This is the expected behavior. If you need to controlled the percentage, you need to use controlled mode.
