### ISSUE TITLE
手机上使用数字输入 Input Number时，希望点击+-图标时不要弹出屏幕键盘

### ISSUE THREAD

**Issue by gogososonono** [TuSimple/naive-ui#4646]
### This function solves the problem (这个功能解决的问题)
点击+-按钮弹出屏幕键盘后，界面变得太小
### Expected API (期望的 API)
在Props中开关

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
