### ISSUE TITLE
vite ssr

### ISSUE THREAD

**Issue by yang867381349** [TuSimple/naive-ui#466]
### This function solves the problem (这个功能解决的问题)
在ssr 上能够支持vite工具的功能正常开发。
### Expected API (期望的 API)
解决搜索引擎的SEO 优化(重点)
解决首屏加载性能优化（SSR附带性）
在naive UI 只支持 vue3 的同时。开发者在vue3 上扩展ssr大部分收到UI 控件的报错或者不兼容导致不得不放弃使用UI库

**Comment by yang867381349** [comment]
https://github.com/yang867381349/error
最小代码实现库 内置 element-plus 可替换至 Naive-ui

**Comment by 07akioni** [comment]
https://www.naiveui.com/zh-CN/os-theme/docs/ssr
