### ISSUE TITLE
n-select 绑定参数v-model为空字符串，会把占位符中的数据清空不显示，用户体验不好

### ISSUE THREAD

**Issue by wfc66986** [TuSimple/naive-ui#4678]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-alpha.7

### Browser and its version (浏览器及其版本)
Chrome版本 111.0.5563.147

### System and its version (系统及其版本)
xx

### Reappearance link (重现链接)
https://codesandbox.io/s/naughty-frost-2sphl4?file=/src/Demo.vue

### Reappearance steps (重现步骤)
v-model:value 参数设置空字符   placeholder="请选择内容"占位符绑定值不显示

### Expected results (期望的结果)
不管什么类型不会影响我的占位符显示

### Actual results (实际的结果)
麻烦早点解决，用户体验不好只要空字符串，占位符不显示问题

**Comment by core-admin** [comment]
值可以设置为undefined

**Comment by wfc66986** [comment]
我要用ts定义类型为字符串，不可能定义为undefind 并且赋值后清空占位符又会出现



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月4日(周二) 上午9:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tusen-ai/naive-ui] n-select 绑定参数v-model为空字符串，会把占位符中的数据清空不显示，用户体验不好 (Issue #4678)




 
值可以设置为undefined

**Comment by Gahotx** [comment]
ts 设置成 string | null，数据初始化写 null。个人感觉空字符串显示 placeholder 不太合理，例如这种情况：placeholder 是 '请选择性别'，但是选项可以是男，女，空字符串(保密)，这时候空字符串对应的就是label（保密），而不是展示 placeholder '请选择性别'

**Comment by oyal** [comment]
设置为null，WebStorm会有警告：`类型 null 不可分配给类型 Array<string | number> | string | number `

![2023-11-09_17-56-50](https://github.com/tusen-ai/naive-ui/assets/88022434/e8966441-4ae4-4d23-9ea3-476f02e98847)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by xiazehui** [comment]
> 设置为null，WebStorm会有警告：`类型 null 不可分配给类型 Array<string | number> | string | number `
> 
> ![2023-11-09_17-56-50](https://private-user-images.githubusercontent.com/88022434/281691825-e8966441-4ae4-4d23-9ea3-476f02e98847.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0Mjc4NDgsIm5iZiI6MTcxMzQyNzU0OCwicGF0aCI6Ii84ODAyMjQzNC8yODE2OTE4MjUtZTg5NjY0NDEtNGFlNC00ZDIzLTllYTMtNDc2ZjAyZTk4ODQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA4MDU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlYjk1ZGJkNWMwOTAzZTdjODlkNWZlYjgzM2UwNzQ1ZTBiMDg3N2Y5YzMzMmVmOWRiNjQ3ODg2ODE4NzY3NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JfmdSWYGjg_D-lsoqCBhBvo4nXtYeU7-fk7L9Z2C1so)

这个问题你最好解决了吗

**Comment by jahnli** [comment]
undefined

**Comment by xiazehui** [comment]
> undefined

undefined WebStorm也会有警告

**Comment by oyal** [comment]
@xiazehui 好像没有这个问题了，不清楚是 Vue、WebStorm、NaiveUI 哪个的问题，你可以试着都升级一下版本。我现在 WebStorm 版本 2023.3.2

![2024-04-18_17-57-05](https://github.com/tusen-ai/naive-ui/assets/88022434/39784e0d-5a77-48dd-bfe2-350dacbfe1be)
