### ISSUE TITLE
why dropdown slot trigger is default

### ISSUE THREAD

**Issue by ahwgs** [TuSimple/naive-ui#47]
### Environment Info

- Naive UI version:2.11.4
- Browser Info: Chome 
- System Info:Windows

### Steps to reproduce
![image](https://user-images.githubusercontent.com/26664586/121388564-28a69480-c97e-11eb-9a81-27175b556354.png)

### What is expected?

如代码，在dropdown中，透传给popover组件的trigger slot 为什么是 `default` ，然后下面又重新传了 `default` 函数，我在写dropdown 单测时，传入 `trigger` 发现始终未生效

![image](https://user-images.githubusercontent.com/26664586/121389206-bf735100-c97e-11eb-8ae0-68c1486b6515.png)

如文档所示，`trigger` 应该是 触发弹出的元素

**Comment by ahwgs** [comment]
补充信息:
在Popconfirm 组件中是取的 trigger slot 
![image](https://user-images.githubusercontent.com/26664586/121391617-2b56b900-c981-11eb-972d-4b51138c7388.png)
在popselect 组件中 跟dropmenu 一样取的是 default 
![image](https://user-images.githubusercontent.com/26664586/121391749-4cb7a500-c981-11eb-805a-5b7222608e63.png)

想问一下为什么这么设计

**Comment by 07akioni** [comment]
是这样，dropdown 的内容是无法定制的，你可以理解为是锁定了弹出内容的 popover，所以提供 trigger 是没有意义的，因为 default 不会有东西可以填。

但是 popover 不一样，trigger 和 content 都需要填写东西。

**Comment by 07akioni** [comment]
关于文档的问题你说的对，应该是专门在 dropdown 那里标注一下才对。不然可能把人引向 popover 了。

**Comment by ahwgs** [comment]
嗯，有道理[强]
