### ISSUE TITLE
Mention在异步加载时会保留@之后的多余输入

### ISSUE THREAD

**Issue by dream960727** [TuSimple/naive-ui#48]
### Environment Info

- Naive UI version: 2.11.4
- Browser Info: Safari 14.1.1 
- System Info: Mac OS 11.4

### Steps to reproduce
进入Mention，点击远程加载的文本框.
输入任意字符，会返回该字符为前缀的所有内容，而不会过滤内容。
<img width="675" alt="CleanShot 2021-06-10 at 10 19 51@2x" src="https://user-images.githubusercontent.com/27428177/121454461-6aaef500-c9d5-11eb-9eb1-c9eac17a989b.png">

### What is expected?
类似基本用法中，可以过滤内容，显示无数据。

**Comment by Fnzero** [comment]
This is remote loading, it means that  you should use interfaces to filter. This is just an example of use，you can click show code button to see the method, you will get it.
