### ISSUE TITLE
Date Picker 组件目前的功能有限

### ISSUE THREAD

**Issue by yeyuqh** [TuSimple/naive-ui#493]
### This function solves the problem (这个功能解决的问题)
目前只能选择具体的日期时间
### Expected API (期望的 API)
希望增加只选择年份或月份的选项，这个需求还是很常见的。

**Comment by 07akioni** [comment]
有此打算，可能会花一段时间

**Comment by seekertang** [comment]
有同样的需求！！！

**Comment by agrass-GitHub** [comment]
能不能把 element 的 value-format api 加上呀？表示很需要

**Comment by jkbody** [comment]
> 能不能把元素的value-format api加进去呀？表示很需要

+1

**Comment by qlynick** [comment]
+1

**Comment by Talljack** [comment]
same #111
