### ISSUE TITLE
[Bug report]NTooltip not work

### ISSUE THREAD

**Issue by cnguu** [TuSimple/naive-ui#496]
### TuSimple/naive-ui version (版本)
2.15.4

### Vue version (Vue 版本)
3.1.4

### Browser and its version (浏览器及其版本)
Chrome(91.0.4472.124)

### System and its version (系统及其版本)
Window10 20H2(19042.1083)

### Reappearance link (重现链接)
https://github.com/spider-nest/vue-spider-admin

### Reappearance steps (重现步骤)
1. git clone & yarn install
2. open `src/layouts/page/toolbar/Index.vue`,see the line 41~48
3. run `yarn serve` to open local serve
4. after login, see the `refresh icon`

### Expected results (期望的结果)
NTooltip normal work

### Actual results (实际的结果)
NTooltip not work

**Comment by cnguu** [comment]
Trigger root node needs to add `v-bind="$attrs"`

**Comment by 07akioni** [comment]
![image](https://user-images.githubusercontent.com/18677354/125650075-bdbe2cb4-b09d-4ad1-9744-f7084f80c333.png)
写了 inheritAttrs false 就必须要手动绑定属性
