### ISSUE TITLE
官方能否出个模板，类似ant design pro的中后台模板

### ISSUE THREAD

**Issue by batsx** [TuSimple/naive-ui#497]
### This function solves the problem (这个功能解决的问题)
让开发者专注页面开发
### Expected API (期望的 API)
希望用js/Composition API开发，让跟多的不会ts的后端开发能快速开发业务页面

**Comment by amadeus711** [comment]
不错的建议，但 NaiveUI 团队暂时没有人力去开发这个项目，而社区同学有开发：https://github.com/jekip/naive-ui-admin
