### ISSUE TITLE
add a way to pass an input control to `dynamic-tags` (e.g. for autocomplete)

### ISSUE THREAD

**Issue by wc-matteo** [TuSimple/naive-ui#499]
### This function solves the problem (这个功能解决的问题)
being able to use dynamic-tags in more situations
### Expected API (期望的 API)
probably an input slot?

**Comment by Volankey** [comment]
You can use https://www.naiveui.com/zh-CN/os-theme/components/auto-complete.

**Comment by wc-matteo** [comment]
yes but how do I pass it to `n-dynamic-tags`?

**Comment by Volankey** [comment]
I get what you meant now.
