### ISSUE TITLE
ability to re-order selected tags inside select multiple

### ISSUE THREAD

**Issue by wc-matteo** [TuSimple/naive-ui#501]
### This function solves the problem (这个功能解决的问题)
for example, being able to define which of the selected value is the main one (you would make it the first)
### Expected API (期望的 API)
maybe add a prop like sortable-values?

**Comment by Volankey** [comment]
I think there are few usage scenarios for this.
@07akioni

**Comment by 07akioni** [comment]
@wc-matteo I think set value to sorted value in `on-update:value` callback is enough.

**Comment by wc-matteo** [comment]
but how can you sort them?

**Comment by wc-matteo** [comment]
I was think by drag n drop

**Comment by 07akioni** [comment]
> I was thinking by drag n drop

Implement drag and drop inside select will take tons of code.

**Comment by 07akioni** [comment]
> but how can you sort them?

```
<n-select @update:value="v => this.value = Array.from(v).sort()" />
```
```

**Comment by wc-matteo** [comment]
> > I was thinking by drag n drop
> 
> Implement drag and drop inside select will take tons of code (and it's not useful).

![image](https://user-images.githubusercontent.com/10562635/125844690-c55668a6-a1d3-41b3-b2e6-780d666459ff.png)

I mean like there. Not in the list

**Comment by wc-matteo** [comment]
the use case is, for example, to select a primary value (so you would put it first)

**Comment by 07akioni** [comment]
> > > I was thinking by drag n drop
> > 
> > 
> > Implement drag and drop inside select will take tons of code (and it's not useful).
> 
> ![image](https://user-images.githubusercontent.com/10562635/125844690-c55668a6-a1d3-41b3-b2e6-780d666459ff.png)
> 
> I mean there. Not in the list

I mean here too, the order follows the value of the select, so you can order them everytime the value changes.

**Comment by wc-matteo** [comment]
I mean let the user decide the order tho .-.

**Comment by 07akioni** [comment]
> I mean let the user decide the order tho .-.

This can be done by add dnd listeners to tag by `render-tag`. Since select has many composition of props and we expect everyone should work, for example filterable, we can't implement the feature with no conflict with other props in a reasonable time.

**Comment by wc-matteo** [comment]
fair enough!
