### ISSUE TITLE
being able to insert time manually without specifying minutes or seconds. So only the hours (the other values default to 00)

### ISSUE THREAD

**Issue by wc-matteo** [TuSimple/naive-ui#503]
### This function solves the problem (这个功能解决的问题)
speed up manual inserts
### Expected API (期望的 API)
no api changes

**Comment by Volankey** [comment]
Time Picker?

**Comment by wc-matteo** [comment]
yes

**Comment by Volankey** [comment]
See https://github.com/TuSimple/naive-ui/pull/498.

**Comment by wc-matteo** [comment]
this request is different. I'll give an example:
let's say we have a time-picker with `HH:mm`. I want to input `10` with the keyboard and have the value recognized by the time-picker. At the moment it doesn't work.

**Comment by 07akioni** [comment]
Corresponding to the implementation I think it will be not easy to implement a robust input like that.

**Comment by wc-matteo** [comment]
yeah, maybe not worth it if it's a lot of work

**Comment by 07akioni** [comment]
> yeah, maybe not worth it if it's a lot of work

The main concerning is that it may conflict with formatting.

**Comment by wc-matteo** [comment]
I noticed that when you use the time-picker ui, just by clicking on the first type of value (in my case hours) it auto-selects `00` as minutes. Maybe it could be done using the same logic

**Comment by 07akioni** [comment]
> t when you use the time-picker ui, just by clicking on the first type of value (in my case hours) it auto-selects `00` as minutes.

Controlling input is much harder than just controlling normal DOM.
