### ISSUE TITLE
when n-spin wraps an element, being able to select the position of the n-spin (at the moment it's centered)

### ISSUE THREAD

**Issue by wc-matteo** [TuSimple/naive-ui#506]
### This function solves the problem (这个功能解决的问题)
for example, if you have a long page and you wrap it in an n-spin, the spinner may not show up cause the center is not in view
### Expected API (期望的 API)
position prop like other elements

**Comment by Volankey** [comment]
You should use the css: `position` to make the spin in the center of the view.
