### ISSUE TITLE
add a prop to n-upload to hide the file list

### ISSUE THREAD

**Issue by wc-matteo** [TuSimple/naive-ui#507]
### This function solves the problem (这个功能解决的问题)
makes n-upload more customizable
### Expected API (期望的 API)
add a prop to hide the file list

**Comment by 07akioni** [comment]
If there is no list, how do users know the status?

**Comment by wc-matteo** [comment]
I hid the list with css and displayed the progress with n-progress

**Comment by 07akioni** [comment]
I think we can add a `show-file-list` prop.
