### ISSUE TITLE
Provider specified in the document  

### ISSUE THREAD

**Issue by jahnli** [TuSimple/naive-ui#515]
### This function solves the problem (这个功能解决的问题)
Documentation is not clear
### Expected API (期望的 API)
Currently, many people do not know the purpose of providers（message-provider，dialog-provider，loading-bar-provider........）, whether to consider annotation in the document, provider nesting order, purpose and use

**Comment by jahnli** [comment]
![image](https://user-images.githubusercontent.com/20943608/125723924-66341345-d30d-48cf-8626-83f7d94239c1.png)
Similar to this, official documentation should provide a more standard and reasonable indication

**Comment by 07akioni** [comment]
We will provide a demo in the docs later.

**Comment by Talljack** [comment]
You can get more usage information in [
awesome-naive](https://github.com/naive-ui/awesome-naive/blob/main/README.md#Tutorial)
