### ISSUE TITLE
DataTable scroll-x 属性设置后 table内容宽度未沾满容器宽度

### ISSUE THREAD

**Issue by Volankey** [TuSimple/naive-ui#518]
### TuSimple/naive-ui version (版本)
2.15.4

### Vue version (Vue 版本)
3.1.4

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
Ubuntu

### Reappearance link (重现链接)
https://codesandbox.io/s/solitary-cookies-ho7hf?file=/src/Demo.vue

### Reappearance steps (重现步骤)
将 document width 拉伸 > 700，可以看到table右侧的空白

### Expected results (期望的结果)
应该占满容器宽度

### Actual results (实际的结果)
出现空白

**Comment by Volankey** [comment]
![image](https://user-images.githubusercontent.com/23287363/125741652-389ee9f8-fee9-4d06-9237-01f54a39ab77.png)
width应该是100%而不是fit-content

**Comment by 07akioni** [comment]
在内部用 scrollbar.contentStyle 解决一下吧，或者用 css，看哪个方便

**Comment by Volankey** [comment]
https://codesandbox.io/s/solitary-cookies-ho7hf?file=/src/Demo.vue
这个是第二种情况

**Comment by Volankey** [comment]
@07akioni
