### ISSUE TITLE
[Feature request] NDropdown support template option

### ISSUE THREAD

**Issue by cnguu** [TuSimple/naive-ui#520]
### This function solves the problem (这个功能解决的问题)
Custom rendering option
### Expected API (期望的 API)
```vue
<template>
  <NDropdown>
    <template #trigger>
      <NButton>hover me</NButton>
    </template>

    <NDropdownOption>item 1</NDropdownOption>

    <RouterLink to="path">
      <NDropdownOption>item 2</NDropdownOption>
    </RouterLink>
  </NDropdown>
</template>
```

**Comment by 07akioni** [comment]
We will never provide children API for dropdown, select or menu due to its horrible maintainability.

**Comment by fudiwei** [comment]
毛遂自荐 [@skit/x.naive-ui](https://github.com/fudiwei/x.naive-ui)，基于 Naive-UI 二次封装了 Dropdown 组件，支持插槽式的写法。
