### ISSUE TITLE
timeline不显示左边线

### ISSUE THREAD

**Issue by xdewx** [TuSimple/naive-ui#5252]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
edge

### System and its version (系统及其版本)
windows 11

### Node version (Node 版本)
16

### Reappearance link (重现链接)
https://naive-ui.github.io/issue-helper/?lang=en-US

### Reappearance steps (重现步骤)
原因是样式的问题：·
`.n-timeline .n-timeline-item:last-child .n-timeline-item-timeline .n-timeline-item-timeline__line`能够匹配到所有的timeline，改成`.n-timeline:last-child .n-timeline-item .n-timeline-item-timeline .n-timeline-item-timeline__line`即可

### Expected results (期望的结果)
正常显示

### Actual results (实际的结果)
没显示

**Comment by jizai1125** [comment]
没懂你的问题，给个复现

**Comment by jizai1125** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/33979706/38ceb5ee-0f28-4944-94cf-7d9446e6da73)
现在的效果不是没问题么

**Comment by jizai1125** [comment]
.n-timeline .n-timeline-item:last-child
选择器没问题啊，就是选择最后一个
