### ISSUE TITLE
Stateless version of Popselect component

### ISSUE THREAD

**Issue by djmattyg007** [TuSimple/naive-ui#531]
### This function solves the problem (这个功能解决的问题)
The Popselect component is great, but it contains state about what the currently selected item is. I would like to use this component as a stateless menu used to trigger one of a variety of different actions.
### Expected API (期望的 API)
Create a new component like Popselect, but without the "value" or "on-update:value" props. Instead, each menu item should accept some kind of "on click" handler.

**Comment by 07akioni** [comment]
You can set `value` to `null` and use `on:update:value` as a handler.

**Comment by djmattyg007** [comment]
Ah, fair enough. I think it would be worth documenting this use case, as it's not obvious.

**Comment by 07akioni** [comment]
Maybe in this case `dropdown` is a better choice.

**Comment by djmattyg007** [comment]
Thanks, that does make more sense!
