### ISSUE TITLE
Ability to change default message timeout

### ISSUE THREAD

**Issue by djmattyg007** [TuSimple/naive-ui#535]
### This function solves the problem (这个功能解决的问题)
There are situations where it's desirable to increase the default message timeout for all messages in your application, without having to manually set a duration for every single message.
### Expected API (期望的 API)
Perhaps it would be possible to set the default message timeout on the <n-message-provider> component. Alternatively, it could be done through the config provider.

**Comment by 07akioni** [comment]
ref #375
