### ISSUE TITLE
Add "disabled" flag for forms

### ISSUE THREAD

**Issue by djmattyg007** [TuSimple/naive-ui#538]
### This function solves the problem (这个功能解决的问题)
When a form is submitted, it is a good idea to disable all inputs to prevent the user from making changes that won't take effect. Right now, this must be done for each form field individually.
### Expected API (期望的 API)
`<n-form>` should have a `disabled` prop that will automatically disable all fields inside that form when set to `true`.

**Comment by 07akioni** [comment]
I think it's a reasonable idea.
