### ISSUE TITLE
add a prop to autoclose the date picker after the user has selected a date range

### ISSUE THREAD

**Issue by wc-matteo** [TuSimple/naive-ui#541]
### This function solves the problem (这个功能解决的问题)
makes selecting a date range faster and less confusing
### Expected API (期望的 API)
a prop to have the closing behavior

**Comment by wc-matteo** [comment]
maybe ALSO add a way to open/close the date picker programmatically?

**Comment by 07akioni** [comment]
> maybe ALSO add a way to open/close the date picker programmatically?

I think we should do this.

**Comment by 07akioni** [comment]
Closing behavior can be a prop. We will add it later.
