### ISSUE TITLE
新增 URL卡片

### ISSUE THREAD

**Issue by cn-src** [TuSimple/naive-ui#5416]
### This function solves the problem (这个功能解决的问题)
新增卡片组件，或现有卡片组件支持左右结构，左边可放图片，作为网址导航项。
### Expected API (期望的 API)
实现效果类似：https://ai-bot.cn/ 里的卡片组件样式。
<img width="602" alt="image" src="https://github.com/tusen-ai/naive-ui/assets/8263180/87bd213b-05d5-477c-ae42-e063408be71e">

**Comment by jizai1125** [comment]
看看这个组件  https://www.naiveui.com/zh-CN/light/components/thing

**Comment by XueHua-s** [comment]
这种效果，你自己组合一下不就行了。原本的卡片+栅格+图像组件

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
