### ISSUE TITLE
add material design-like labels to form items

### ISSUE THREAD

**Issue by wc-matteo** [TuSimple/naive-ui#542]
### This function solves the problem (这个功能解决的问题)
have the label occupy less space but still always been visibile (good usability)
### Expected API (期望的 API)
material design inputs have labels that start as placeholders and when the field gets focused they move to the top:
https://material.io/components/text-fields

this would be very useful as a way to have the label always visibile (otherwise when the input is filled the user doesn't know what's it for) but at the same time occupy the least amount of space

**Comment by 07akioni** [comment]
I don't think we can merge material style into the library's component. The difference is so huge.

**Comment by wc-matteo** [comment]
I understand
