### ISSUE TITLE
Popover x/y prop not working

### ISSUE THREAD

**Issue by Zhaocl1997** [TuSimple/naive-ui#55]
### Environment Info

- Naive UI version: (eg. 2.11.0)
- Browser Info: (eg. Chome 91)
- System Info: (eg. Mac OS 11.2.3, Windows)

### Reproduction link
[https://codesandbox.io/s/silly-smoke-h733h?file=/src/Demo.vue](url)

### What is actually happening?
Add x or y, not working. Add both, default slot disappear.

**Comment by 07akioni** [comment]
You need to add both x and y to make it manually triggered.

**Comment by 07akioni** [comment]
Also in manual mode trigger slot won't be displayed.

**Comment by 07akioni** [comment]
If you have a reasonable scene which needs it, I'll reopen it.

Docs will be updated.
