### ISSUE TITLE
Expose the dialog's action slot as an option in DialogOptions 

### ISSUE THREAD

**Issue by ZerroRt** [TuSimple/naive-ui#550]
### This function solves the problem (这个功能解决的问题)
Convenient to customize the dialog according to specific needs 
### Expected API (期望的 API)
dialog.info({
  content: () => createVNode(contentComponent),
  action: () => createVNode(actionComponent)
})

**Comment by 07akioni** [comment]
fixed in https://github.com/TuSimple/naive-ui/pull/581
