### ISSUE TITLE
Batch selection for tables

### ISSUE THREAD

**Issue by DannyFeliz** [TuSimple/naive-ui#554]
### This function solves the problem (这个功能解决的问题)
It would allow selecting more than one element at once
### Expected API (期望的 API)
It would be cool if when we press the <kbd>Shift</kbd> key, we can select multiples elements in the table.

We can take a look to the way [Ant Design](https://ant.design/components/table/#components-table-demo-row-selection) did it
![selection](https://user-images.githubusercontent.com/5460365/126197351-3009cfc0-a02e-415b-84e7-a0e64e0e0b73.gif)

This is the current behavior in [Naive-UI](https://www.naiveui.com/en-US/light/components/data-table#select)
![selection-n](https://user-images.githubusercontent.com/5460365/126197353-57c010e3-c25c-4766-935a-b87ab4fb1106.gif)

**Comment by 07akioni** [comment]
I know the feature. Some of antd table's features are implemented by me 😄.

We will do it.

**Comment by DannyFeliz** [comment]
Haha😄 @07akioni that's even better, I didn't know you're part of the Ant Design team.

**Comment by DannyFeliz** [comment]
Closing this since this was fixed in #1026
