### ISSUE TITLE
[Mention] Support `renderLabel` prop for the options 

### ISSUE THREAD

**Issue by DannyFeliz** [TuSimple/naive-ui#562]
### This function solves the problem (这个功能解决的问题)
I'm aware we have the `render` prop but, if we use that, we basically lose all the functionality and the styles that are build-in with the `renderLabel` prop that wouldn't be an issue.
### Expected API (期望的 API)
I would like the same API we have in the [select](https://www.naiveui.com/en-US/os-theme/components/select#custom-option) component when using the `renderLabel` prop.

**Comment by DannyFeliz** [comment]
This feature request was implemented in #593.

Thanks @amadeus711

**Comment by 07akioni** [comment]
We will add `renderLabel` for batch rendering later.

**Comment by DannyFeliz** [comment]
@07akioni so, should we reopen this?

**Comment by amadeus711** [comment]
> @07akioni so, should we reopen this?

No, I will develop this feature in the near future.
