### ISSUE TITLE
主题生成部分无效，与缺失功能

### ISSUE THREAD

**Issue by duxphp** [TuSimple/naive-ui#567]
### This function solves the problem (这个功能解决的问题)
丰富定制化组件样式
### Expected API (期望的 API)
card组件阴影设置无效，表单组件输入框、按钮组件等需要阴影设置

**Comment by 07akioni** [comment]
card 组件的阴影只对 hoverable 生效。有些组件的阴影如果本身不在 naive ui 的默认样式里，我们暂时不会增加，写 CSS 补充是个合适的方式。
