### ISSUE TITLE
官网不稳定，国内下午一定频率访问不了，出现不止一两次，这是我遇到的第三次

### ISSUE THREAD

**Issue by smiles1x** [TuSimple/naive-ui#580]
### TuSimple/naive-ui version (版本)
2.15.5

### Vue version (Vue 版本)
3.2.0-beta.4

### Browser and its version (浏览器及其版本)
edge

### System and its version (系统及其版本)
Win11

### Reappearance link (重现链接)
https://naive-ui.github.io/issue-helper/?lang=en-US

### Reappearance steps (重现步骤)
截止到2021/01/22 16:18 依然不可访问，每次持续时间较长 20分钟至一个小时

### Expected results (期望的结果)
正常访问

### Actual results (实际的结果)
官网无法访问

**Comment by Volankey** [comment]
等gitee可以部署我们会在gitee上部署一个国内的文档

**Comment by Volankey** [comment]
目前可以clone源码，直接跑起来也能看到文档
