### ISSUE TITLE
[Bug report]: NDataTable, rowClassName not work when the type: [Function, String]

### ISSUE THREAD

**Issue by cnguu** [TuSimple/naive-ui#582]
### TuSimple/naive-ui version (版本)
2.15.5

### Vue version (Vue 版本)
3.1.4

### Browser and its version (浏览器及其版本)
Chrome(91.0.4472.164)

### System and its version (系统及其版本)
Win10 20H2 19042.1110

### Reappearance link (重现链接)
https://codesandbox.io/s/intelligent-ellis-k3oew?file=/src/SDataTable.vue

### Reappearance steps (重现步骤)
1. Look the rowClassName props

### Expected results (期望的结果)
```
props: {
  rowClassName: {
    type: [Function, String],
    default: () => { return string },
  },
},
```

### Actual results (实际的结果)
```
props: {
  rowClassName: {
    type: [Function, String] // not work, but work on `type: Function`
    default: () => { return string },
  },
},
```

**Comment by cnguu** [comment]
It still does not work in version 2.15.8

**Comment by 07akioni** [comment]
It seems work.

![image](https://user-images.githubusercontent.com/18677354/127204860-a40b6380-be04-40fd-b370-af481a125fee.png)

![image](https://user-images.githubusercontent.com/18677354/127204883-f58f4e47-96ff-4bdb-a184-def205e4d9aa.png)

**Comment by cnguu** [comment]
> It seems work.
> 
> ![image](https://user-images.githubusercontent.com/18677354/127204860-a40b6380-be04-40fd-b370-af481a125fee.png)
> 
> ![image](https://user-images.githubusercontent.com/18677354/127204883-f58f4e47-96ff-4bdb-a184-def205e4d9aa.png)

直接使用是没问题，但是从prop进来的就有问题，看下复现 https://codesandbox.io/s/crazy-bassi-7dnq9?file=/src/SDataTable.vue

**Comment by 07akioni** [comment]
> https://codesandbox.io/s/crazy-bassi-7dnq9?file=/src/SDataTable.vue

应该是你使用 vue 的问题，一个 type 为 [Function, String] 的 prop，default 应该为一个返回函数的函数，而不是函数。

**Comment by cnguu** [comment]
> > https://codesandbox.io/s/crazy-bassi-7dnq9?file=/src/SDataTable.vue
> 
> 应该是你使用 vue 的问题，一个 type 为 [Function, String] 的 prop，default 应该为一个返回函数的函数，而不是函数。

即便是函数返回函数，也是无效的

```
  props: {
    rowClassName: {
      type: [Function, String],
      default: (row, index) => {
        return () => {
          return (index & 1) === 1 ? "table-row-class" : null
        };
      },
    },
  },
```

**Comment by 07akioni** [comment]
你写错了

```
  props: {
    rowClassName: {
      type: [Function, String],
      default: () => {
        return (row, index) => {
          return (index & 1) === 1 ? "table-row-class" : null
        };
      },
    },
  },
```
