### ISSUE TITLE
[Feature request]: NDataTable pagination prefix support total items

### ISSUE THREAD

**Issue by cnguu** [TuSimple/naive-ui#585]
### This function solves the problem (这个功能解决的问题)
Total number of items displayed
### Expected API (期望的 API)
```
pagination: {
        page: 1,
        pageSize: 15,
        pageSizes: [15, 25, 50, 100],
        pageCount: 101,
        showQuickJumper: true,
        showSizePicker: true,
            prefix: (info) => {
              // here, `info.total`
              return `${info.startIndex + 1}-${
                info.endIndex + 1
              } item / total: ${info.total||0}`;
            },
      },
```

**Comment by Talljack** [comment]
Total information will not be available in asynchronous state

**Comment by 07akioni** [comment]
> Total information will not be available in asynchronous state

User can fill it by pagination.itemCount

**Comment by Talljack** [comment]
> > Total information will not be available in asynchronous state
> 
> User can fill it by pagination.itemCount

itemCount is total, user must fill it

**Comment by 07akioni** [comment]
> > > Total information will not be available in asynchronous state
> > 
> > 
> > User can fill it by pagination.itemCount
> 
> itemCount is total, user must fill it

In non-remote mode, we should fill it for user by data.length

**Comment by Talljack** [comment]
> > > > Total information will not be available in asynchronous state
> > > 
> > > 
> > > User can fill it by pagination.itemCount
> > 
> > 
> > itemCount is total, user must fill it
> 
> In non-remote mode, we should fill it for user by data.length

In non-remote mode, we should fill it for user by data.length
In remote mode, user fill it by itemCount

**Comment by 07akioni** [comment]
> > > > > Total information will not be available in asynchronous state
> > > > 
> > > > 
> > > > User can fill it by pagination.itemCount
> > > 
> > > 
> > > itemCount is total, user must fill it
> > 
> > 
> > In non-remote mode, we should fill it for user by data.length
> 
> In non-remote mode, we should fill it for user by data.length
> In remote mode, user fill it by itemCount

Yes
