### ISSUE TITLE
DataTable 数据表格撑满高度

### ISSUE THREAD

**Issue by gitlibingchen** [TuSimple/naive-ui#596]
### This function solves the problem (这个功能解决的问题)
表格自适应高度，撑满剩余高度。或者根据表格父容器调整百分比高度。当浏览器高度和行内容高度不确定时，表格总能显示完整
### Expected API (期望的 API)
height:100%; flex:1 ...

**Comment by 07akioni** [comment]
我们至少要提供某种方式能达成这个目标

**Comment by 002269** [comment]
这个需求我也想提的，被你先提了
