### ISSUE TITLE
当drawer内外都有anchor-link对应的href时，点击anchor-link会导航到drawer外对应元素的位置，但不会导航到drawer内元素的对应位置，且anchor-link触发样式丢失

### ISSUE THREAD

**Issue by bljessica** [TuSimple/naive-ui#599]
### TuSimple/naive-ui version (版本)
2.15.6

### Vue version (Vue 版本)
3.2.0-beta.4

### Browser and its version (浏览器及其版本)
Chrome( 91.0.4472.114)

### System and its version (系统及其版本)
Ubuntu(20.04.2)

### Reappearance link (重现链接)
https://codesandbox.io/s/solitary-https-tjlvz?file=/src/Demo.vue

### Reappearance steps (重现步骤)
点击“打开 Drawer”按钮，点击anchor-link

### Expected results (期望的结果)
导航到drawer内元素的对应位置，且触发的anchor-link正常显示触发样式

### Actual results (实际的结果)
导航到drawer外元素的对应位置，未导航到drawer内元素的对应位置，且触发的anchor-link未显示触发样式

**Comment by 07akioni** [comment]
我觉得这个不能算是问题，一个网页上同一个 id 的元素只能有一个，不能这么搞...= =

**Comment by 07akioni** [comment]
里外都要导航这个事也有点奇怪

**Comment by 07akioni** [comment]
当然关键还是第一点

**Comment by bljessica** [comment]
@07akioni 1.7版本是可以的呢

**Comment by 07akioni** [comment]
> @07akioni 1.7版本是可以的呢

你是说 naive 的吗？

这个状态属于未定义行为，不能保证用户输入有问题的情况下能 work。而且这和 drawer portal 的地方也有关系，不能说一定就 work。

**Comment by bljessica** [comment]
@07akioni 是的。好的~
