### ISSUE TITLE
NConfigProvider:   When theme and themeOverrides prop are used together

### ISSUE THREAD

**Issue by shuaibishun** [TuSimple/naive-ui#603]
### TuSimple/naive-ui version (版本)
2.15.6

### Vue version (Vue 版本)
3.1.4

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
MacOS

### Reappearance link (重现链接)
https://codesandbox.io/s/empty-resonance-v8el2?file=/src/App.vue

### Reappearance steps (重现步骤)
When theme is dark， themeOverrides don't take effect

### Expected results (期望的结果)
fix

### Actual results (实际的结果)
fix

**Comment by 07akioni** [comment]
我很奇怪官网没啥没遇到这个问题，得研究一下

**Comment by 07akioni** [comment]
Inverted Menu Color used `primaryColorSuppl` in dark theme
