### ISSUE TITLE
数字输入框 输入精度 precision 属性 如果value 使用字符串就会报错 提示value.toFixed is not a function

### ISSUE THREAD

**Issue by wywsoor** [TuSimple/naive-ui#6091]
### 描述错误

复现代码 
<template>
  <n-input-number :precision="6" v-model:value="value" clearable />
</template>

<script lang="ts">
import { defineComponent, ref } from "vue";

export default defineComponent({
  setup() {
    return {
      value: ref("123"),
    };
  },
});
</script>

### 复现步骤

无

### 最小复现链接

https://codesandbox.io/s/thirsty-cartwright-rwhk3h?file=/src/Demo.vue

### 系统信息

```Shell
无
```

### 使用的包管理器

npm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jahnli** [comment]
提供在线复现连接

**Comment by wywsoor** [comment]
> 提供在线复现连接

<img width="1289" alt="image" src="https://github.com/tusen-ai/naive-ui/assets/26341601/05217ca7-6292-4cd4-b57c-5dafd6d592b9">

**Comment by jahnli** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/20943608/e1d829cf-da2f-4fde-82bc-def7314fef39)

**Comment by jahnli** [comment]
Ok 我空了试试

| |
jahnli
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月28日 11:31 |
| 收件人 | tusen-ai/naive-ui ***@***.***> |
| 抄送人 | jahnli ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [tusen-ai/naive-ui] 数字输入框 输入精度 precision 属性 如果value 使用字符串就会报错 提示value.toFixed is not a function (Issue #6091) |

你用官网上的样例 把value 改成字符串 或者你看我发的图片 问题是util里的format函数报出来的

**Comment by wywsoor** [comment]
> Ok 我空了试试 | | jahnli | | ***@***.*** | ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年06月28日 11:31 | | 收件人 | tusen-ai/naive-ui ***@***.***> | | 抄送人 | jahnli ***@***.***>, Comment ***@***.***> | | 主题 | Re: [tusen-ai/naive-ui] 数字输入框 输入精度 precision 属性 如果value 使用字符串就会报错 提示value.toFixed is not a function (Issue #6091) | 你用官网上的样例 把value 改成字符串 或者你看我发的图片 问题是util里的format函数报出来的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

好的 我想直接 merge request 来着想了一下不合适

**Comment by jahnli** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/20943608/0ca60c54-2373-43f6-bf49-ca525aef2a7c)
如果使用 `input-number` 类型最好是 `number`

**Comment by wywsoor** [comment]
> <img alt="image" width="720" height="48" src="https://private-user-images.githubusercontent.com/20943608/344054571-0ca60c54-2373-43f6-bf49-ca525aef2a7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NTU2NDAsIm5iZiI6MTcxOTU1NTM0MCwicGF0aCI6Ii8yMDk0MzYwOC8zNDQwNTQ1NzEtMGNhNjBjNTQtMjM3My00M2Y2LWJmNDktY2E1MjVhZWYyYTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDA2MTU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjZjYzMTFjMGZiMDg1ODIwYTVmYjg1Nzc2ZDI1NDRlYjA3MWQyN2UwODFhNmQyM2RkMzQxYzY4MDJiYmU4OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PC5lihBFdhvUS7MpvR7Y0gvvHmiPY6O6BD4IEn6gBmU"> 如果使用 `input-number` 类型最好是 `number`

是的我知道，大多数情况是意外传入的，但是对于一个库来说，传入一个期待以外的值比如字符型数字报错是不符合预期的。

**Comment by jahnli** [comment]
> > <img alt="image" width="720" height="48" src="https://private-user-images.githubusercontent.com/20943608/344054571-0ca60c54-2373-43f6-bf49-ca525aef2a7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NTU2NDAsIm5iZiI6MTcxOTU1NTM0MCwicGF0aCI6Ii8yMDk0MzYwOC8zNDQwNTQ1NzEtMGNhNjBjNTQtMjM3My00M2Y2LWJmNDktY2E1MjVhZWYyYTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDA2MTU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjZjYzMTFjMGZiMDg1ODIwYTVmYjg1Nzc2ZDI1NDRlYjA3MWQyN2UwODFhNmQyM2RkMzQxYzY4MDJiYmU4OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PC5lihBFdhvUS7MpvR7Y0gvvHmiPY6O6BD4IEn6gBmU"> 如果使用 `input-number` 类型最好是 `number`
> 
> 是的我知道，大多数情况是意外传入的，但是对于一个库来说，传入一个期待以外的值比如字符型数字报错是不符合预期的。

已经修改了，等待合并吧

**Comment by jahnli** [comment]
https://github.com/tusen-ai/naive-ui/pull/6094#issuecomment-2214518432
建议修改成数字类型

**Comment by jahnli** [comment]
> 版本 naive-ui 2.39.0
> 
> 传入的是string类型的，打包前有警告显示正常，打包后没警告不显示内容
> 
> ![image](https://private-user-images.githubusercontent.com/6964329/348961374-b83b755a-1338-49de-bb62-9bcb146838be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMTEyODksIm5iZiI6MTcyMTExMDk4OSwicGF0aCI6Ii82OTY0MzI5LzM0ODk2MTM3NC1iODNiNzU1YS0xMzM4LTQ5ZGUtYmI2Mi05YmNiMTQ2ODM4YmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTZUMDYyMzA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGI1ZWQ3NDU1YzNiODBhNzNjZTI1MzlhZWY4MzlkYmMwNDRiNjE5MGNjODVhNDUxNGE5YWY2YmYwM2U4NDU2MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xPyQh57rjIPPdjvEXLrBTl6XTEVM-b9vIuYcqrHVazE)
> 
> @jahnli

https://github.com/tusen-ai/naive-ui/pull/6094#issuecomment-2214518432
建议修改成数字类型

**Comment by jahnli** [comment]
1、使用 `n-input`，它是为字符串设计的
2、二次封装下 `n-input-number`  统一处理后传给组件

**Comment by liangyao375** [comment]
@devilmengcry 解决了吗
