### ISSUE TITLE
NTreeSelect: prop checkable doesn't work

### ISSUE THREAD

**Issue by shuaibishun** [TuSimple/naive-ui#618]
### TuSimple/naive-ui version (版本)
2.15.6

### Vue version (Vue 版本)
3.2.0-beta.4

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
MacOS

### Reappearance link (重现链接)
https://codesandbox.io/s/3qy1v

### Reappearance steps (重现步骤)
prop checkable doesn't work

### Expected results (期望的结果)
fix

### Actual results (实际的结果)
fix

**Comment by amadeus711** [comment]
Sorry, this is NTreeSelect's demo bug, you can refer to https://codesandbox.io/s/14318
