### ISSUE TITLE
Tree Select 支持回显节点路径

### ISSUE THREAD

**Issue by pipinet** [TuSimple/naive-ui#623]
### This function solves the problem (这个功能解决的问题)
Tree Select 支持回显节点路径
### Expected API (期望的 API)
例如这样的树，选中了碑林区，那么在select框中展示。 陕西省/西安市/碑林区
北京
     -朝阳区
陕西省
     -西安市
        -✅碑林区

**Comment by amadeus711** [comment]
> ### This function solves the problem (这个功能解决的问题)
> Tree Select 支持回显节点路径
> 
> ### Expected API (期望的 API)
> 例如这样的树，选中了碑林区，那么在select框中展示。 陕西省/西安市/碑林区
> 北京
> -朝阳区
> 陕西省
> -西安市
> -✅碑林区

这个需求可以使用级联（cascader）吧？

**Comment by pipinet** [comment]
cascader目前无法看到整棵树。

**Comment by fireairforce** [comment]
i will work on this
