### ISSUE TITLE
Tree Select支持指定选中策略

### ISSUE THREAD

**Issue by pipinet** [TuSimple/naive-ui#624]
### This function solves the problem (这个功能解决的问题)
Tree Select支持选中策略，例如：选中了一个节点的所有子节点，那么认为选中的父节点，而不是选中了父节点 子节点
### Expected API (期望的 API)
增加如参如下，并实现改能力，后期扩展更多的选中策略
select-strategy: ['parent-only-when-all-children']

**Comment by 07akioni** [comment]
这个东西需要改 treemate，我暂时是没空研究了，你有兴趣可以看看

**Comment by Feellove** [comment]
能加个搜索？

**Comment by 07akioni** [comment]
> 能加个搜索？

filterable

**Comment by zhaowp151** [comment]
树的选中事件  可以带出节点的配置信息吗

**Comment by 07akioni** [comment]
> 树的选中事件 可以带出节点的配置信息吗

正在做
