### ISSUE TITLE
Hope dropdown has a small arrow just like Popover,  as a "Props"

### ISSUE THREAD

**Issue by 002269** [TuSimple/naive-ui#647]
### This function solves the problem (这个功能解决的问题)
Hope dropdown has a small arrow just like Popover,  as a "Props"
### Expected API (期望的 API)
and the documentation of "dropdown" has no description about "placement"

**Comment by Talljack** [comment]
dropdown support popover props, maybe you can take a look at the popover documentation.

**Comment by LYErin** [comment]
poppover props has "showArrow" props  but it does not work because it does not handle the situation when internalRenderBody has value with "showArrow" props  in PopOverBoby.
