### ISSUE TITLE
Data Table使用select，样式似乎被影响了

### ISSUE THREAD

**Issue by jekip** [TuSimple/naive-ui#664]
### TuSimple/naive-ui version (版本)
2.15.7

### Vue version (Vue 版本)
3.2.0-beta.5

### Browser and its version (浏览器及其版本)
Chrome(91.0.4472.77)

### System and its version (系统及其版本)
windos10

### Reappearance link (重现链接)
https://codesandbox.io/s/floral-mountain-pxlen?file=/src/Demo.vue

### Reappearance steps (重现步骤)
n-data-table组件，直接使用 render(row) { return h(NSelect) }

### Expected results (期望的结果)
期望，NSelect箭头和官网一致

### Actual results (实际的结果)
官网也可复现

**Comment by Volankey** [comment]
same as #663
