### ISSUE TITLE
Message组件在setup外调用方式

### ISSUE THREAD

**Issue by Gyang18** [TuSimple/naive-ui#665]
### This function solves the problem (这个功能解决的问题)
目前是通过挂载到window下面，并且要确保message容器挂载成功，才能调用 。这样的方式会有一个问题，当我做路由拦截时，在页面加载前想提示一些错误信息给用户是无法做到的，如请求失败，无权限等
### Expected API (期望的 API)
import { Message } from  'naive-ui';

Message.sucess ()
Message.error ()

就能创建提示信息
....

**Comment by Talljack** [comment]
If you want to use message you have to mount the app, and message is part of the app.
