### ISSUE TITLE
[Bug report]: NPopover onUpdate:show not working

### ISSUE THREAD

**Issue by cnguu** [TuSimple/naive-ui#685]
### TuSimple/naive-ui version (版本)
2.15.8

### Vue version (Vue 版本)
3.1.5

### Browser and its version (浏览器及其版本)
Chrome 92.0.4515.107

### System and its version (系统及其版本)
Windows10 20H2 19042.1110

### Node version (Node 版本)
12.19.0

### Reappearance link (重现链接)
https://codesandbox.io/s/intelligent-ellis-k3oew?file=/src/SPopover.vue

### Reappearance steps (重现步骤)
1. open the link
2. scroll to `Popove Bug`
3. click text `click me`

### Expected results (期望的结果)
When `show` `x` `y` is manually controlled, trigger `onUpdate:show` event

### Actual results (实际的结果)
`onUpdate:show` not working

**Comment by LYErin** [comment]
这个属性是生效的 弹出的提示在下面 你调整一下你设置的x,y试试

**Comment by LYErin** [comment]
非bug 手动触发的话没有回调事件是合理的 相关业务可以写入手动触发的事件里 例如你提供链接的showThe函数内

**Comment by cnguu** [comment]
> 非bug 手动触发的话没有回调事件是合理的 相关业务可以写入手动触发的事件里 例如你提供链接的showThe函数内

那我该如何知道是否clickOutSide呢？

**Comment by LYErin** [comment]
on-clickoutside事件是可以触发的

**Comment by cnguu** [comment]
> on-clickoutside事件是可以触发的

触发了报错 Uncaught TypeError: Cannot read property 'contains' of undefined

**Comment by LYErin** [comment]
我看的你的链接 是你的trigger触发写错了 你参考一下官网 trigger是需要用slot的

**Comment by cnguu** [comment]
当定义了x，y是不需要trigger插槽的，你看下官方文档的手动定位 https://www.naiveui.com/zh-CN/os-theme/components/popover#manual-position

**Comment by cnguu** [comment]
我找到问题在哪里了，当手动定位时，trigger只能是manual，这一点并未在文档找到

**Comment by LYErin** [comment]
嗯 好像把trigger="click"属性去掉就正常了
