### ISSUE TITLE
[Bug report]: NButtonGroup text button icon are not on the same line

### ISSUE THREAD

**Issue by cnguu** [TuSimple/naive-ui#686]
### TuSimple/naive-ui version (版本)
2.15.8

### Vue version (Vue 版本)
3.1.5

### Browser and its version (浏览器及其版本)
Chrome 92.0.4515.107

### System and its version (系统及其版本)
Windows10 20H2 19042.1110

### Node version (Node 版本)
12.19.0

### Reappearance link (重现链接)
https://codesandbox.io/s/intelligent-ellis-k3oew?file=/src/SButton.vue

### Reappearance steps (重现步骤)
1. open the link
2. see the `Button Bug` column

### Expected results (期望的结果)
Icon and text on the same line

### Actual results (实际的结果)
Icon and text are not on the same line

**Comment by labbomb** [comment]
你没引入NButtonGroup，加上试试

**Comment by 07akioni** [comment]
确实是你没引入 NButtonGroup 的原因，loading 的话我再看看吧

![image](https://user-images.githubusercontent.com/18677354/127192726-f2ade460-ab47-4308-9181-9f26987fdc4d.png)

**Comment by cnguu** [comment]
> 确实是你没引入 NButtonGroup 的原因，loading 的话我再看看吧
> 
> ![image](https://user-images.githubusercontent.com/18677354/127192726-f2ade460-ab47-4308-9181-9f26987fdc4d.png)

我知道什么原因了，button-group内必须要接button，不能套div

**Comment by 07akioni** [comment]
> > 确实是你没引入 NButtonGroup 的原因，loading 的话我再看看吧
> > ![image](https://user-images.githubusercontent.com/18677354/127192726-f2ade460-ab47-4308-9181-9f26987fdc4d.png)
> 
> 我知道什么原因了，button-group内必须要接button，不能套div

group 这种东西尽量不要套东西用，除非 demo 也展示了套东西
