### ISSUE TITLE
不带 icon 的 text 按钮文本下沉了

### ISSUE THREAD

**Issue by 002269** [TuSimple/naive-ui#692]
### This function solves the problem (这个功能解决的问题)
不带 icon 的 text 按钮文本下沉了
### Expected API (期望的 API)
看了下，antd 的是齐的，按钮带不带 icon，是不是 text 类型，在不在 loading 状态，在不使用外层包裹的情况下，文本应该水平对齐

**Comment by Fnzero** [comment]
这边测试了下没有复现，能够提供下复现链接吗

**Comment by 002269** [comment]
https://codesandbox.io/s/upbeat-heisenberg-cd0tf?file=/src/Demo.vue
https://cd0tf.csb.app/

**Comment by 002269** [comment]
加不加 icon slot 都一样。。。。。antd 的都测试过了，都是齐的

**Comment by 002269** [comment]
如果说简单的几个按钮排列一下还要加 n-space，不是不可以，但是。。。这个。。。

**Comment by 07akioni** [comment]
这个没办法解决，就先这样吧，如果能做到的话我其实也想做到，但是这玩意复杂到根本没办法保留在文本的排版流中。

如果有人能在为持续现有功能的前提下解决问题，可以提个 PR。
