### ISSUE TITLE
Tag可以在现有的几个类型之外，自定义颜色或者可以自定义类型

### ISSUE THREAD

**Issue by chouchaoren** [TuSimple/naive-ui#693]
### This function solves the problem (这个功能解决的问题)
部分场景下标签不够用，比如说有的有危险，极度危险等可能无法用一个来表示
### Expected API (期望的 API)
例如：color ="#ffeecc"
或 type =“type1”（type1为自定义类型）

**Comment by Volankey** [comment]
需要增加`color`prop
