### ISSUE TITLE
Add an actions 'slot' to the Date Picker

### ISSUE THREAD

**Issue by Ataraxy** [TuSimple/naive-ui#7]
## What problem does the feature solve?

It would be nice to have a slot exposed for custom actions in the Date Picker to augment the three that are available. This way you can add buttons on the component itself for your own predefined date range's such as This Month, Last Week, etc.

**Comment by 07akioni** [comment]
I'm thinking of it. However I wonder where to put it.
There are 2 options.
1.
date
------
actions
------
(builtin) confirm

2.
date
------
actions + (builtin actions)

**Comment by Ataraxy** [comment]
I think 1 would probably be ideal since the built in ones are optional. It's probably better that they're distinct actions also since clear/confirm are important.

**Comment by 07akioni** [comment]
Since date-picker should work with form-item. I can't easily expose the internal change events emitter to the user. So I'm going to provide a ant-design-like api.

```
...
ranges={{
  Today: [xx, xx],
  'This Month': [xx, xx],
}}
...
```

**Comment by Ataraxy** [comment]
Yeah that would be pretty nice. The ant design solution works pretty well. Though they appear to be inline with the built in actions. That's not inherently bad and might even be preferable than having it on a seperate row. They even highlight the ranges on hover and automatically confirm on selection which is pretty slick.

They also have the "Extra Footer" slot.

**Comment by 07akioni** [comment]
> Yeah that would be pretty nice. The ant design solution works pretty well. Though they appear to be inline with the built in actions. That's not inherently bad and might even be preferable than having it on a seperate row. My only concern with that was how it would look if someone had many ranges. They even highlight the ranges on hover and automatically confirm on selection which is pretty slick.
> 
> They also have the "Extra Footer" slot.

Do you have time to implement a `footer` slot? PR is welcomed.

**Comment by 07akioni** [comment]
For `footer` slot you can open an new issue.

**Comment by Developer27149** [comment]
@07akioni 你好，是因为这个组件和表单功能有关联，所以不方便增加自定义对`此刻`和`确认`的自定义插槽支持吗？我的英语不太好。
