### ISSUE TITLE
Avatar component adds an alternative avatar prop 

### ISSUE THREAD

**Issue by ZerroRt** [TuSimple/naive-ui#702]
### This function solves the problem (这个功能解决的问题)
Automatically load alternative avatars when the src of the Avatar component loads error 
### Expected API (期望的 API)
The component adds a'default' attribute, or the src attribute supports passing in a string array, the first item of the array is loaded by default, and the next item of the array is automatically loaded when the loading error occurs

**Comment by Sepush** [comment]
@amadeus711 any update about this?
I'm glad to work on it and give a PR.

**Comment by 07akioni** [comment]
> @amadeus711 any update about this? I'm glad to work on it and give a PR.

You can create a general image inside `_internal` folder and use it in avatar. We can finally move it to vueuc later.

The image component should suppport some fallback options.
