### ISSUE TITLE
在浏览器跑耗时的程序的时候, spin不旋转

### ISSUE THREAD

**Issue by aixia715** [TuSimple/naive-ui#703]
Environment Info
Naive UI version: 2.14.4
Browser Info: Microsoft Edge 92.0.902.55
System Info: Win10
Reproduction link
https://www.naiveui.com/zh-CN/light/components/spin

Steps to reproduce
官网例子

What is expected?
在浏览器跑耗时的程序的时候, spin旋转

What is actually happening?
在浏览器跑耗时的程序的时候, spin不旋转.
怀疑是由于spin的旋转需要浏览器定时运行代码重新渲染, 考虑到使用spin的场景有很多是浏览器运行耗时的程序, 是否可以采用css动画的方式?

**Comment by 07akioni** [comment]
JS 会阻塞 UI 渲染，这个我们控制不了
