### ISSUE TITLE
Loading Bar和Message全局使用

### ISSUE THREAD

**Issue by ItsHeart** [TuSimple/naive-ui#711]
### This function solves the problem (这个功能解决的问题)
加载条 Loading Bar在vue router导航守卫中使用问题与Message在axios返回拦截的时候使用问题
### Expected API (期望的 API)
提供 Loading Bar和Message全局调用的API

**Comment by amadeus711** [comment]
> ### This function solves the problem (这个功能解决的问题)
> 加载条 Loading Bar在vue router导航守卫中使用问题与Message在axios返回拦截的时候使用问题
> 
> ### Expected API (期望的 API)
> 提供 Loading Bar和Message全局调用的API

可以参考这里面的内容：
https://github.com/naive-ui/awesome-naive#tutorial
