### ISSUE TITLE
Time picker support range like Date picker

### ISSUE THREAD

**Issue by pipinet** [TuSimple/naive-ui#716]
### This function solves the problem (这个功能解决的问题)
Time picker support range like Date picker
### Expected API (期望的 API)
Time picker support range like Date picker

**Comment by 07akioni** [comment]
Will do.

**Comment by kungege** [comment]
same as [#390](https://github.com/TuSimple/naive-ui/issues/390)

**Comment by 07akioni** [comment]
trackin 390
