### ISSUE TITLE
Dropdown components dislocation

### ISSUE THREAD

**Issue by Aisen60** [TuSimple/naive-ui#726]
### TuSimple/naive-ui version (版本)
2.15.11

### Vue version (Vue 版本)
3.1.0

### Browser and its version (浏览器及其版本)
Chrome(91.0.4472.77)

### System and its version (系统及其版本)
MacOS(10.14.5)

### Node version (Node 版本)
12.13.0

### Reappearance link (重现链接)
https://codesandbox.io/s/naive-ui-dropdown-components-dislocation-3v5zp?file=/src/Demo.vue

### Reappearance steps (重现步骤)
1.click each text（点击每一个文字）
2.random click text（接着，在随机点击其中的一个文字）
3.the dropdown components always in the last container（下拉菜单始终出现在最后的元素当中，发生了错位）

### Expected results (期望的结果)
the dropdown components should appear in its own container（下来菜单应该出现在它所在的容器中）

### Actual results (实际的结果)
the dropdown components always in the last container（下拉菜单始终出现在最后的元素当中，发生了错位）

### Remarks (补充说明)

![Dropdown components dislocation](https://user-images.githubusercontent.com/19791710/127455962-fe32f087-1406-4b0b-8f1b-a35c32b5ef8a.gif)

**Comment by Volankey** [comment]
复现了，我两个月前的bug

**Comment by Volankey** [comment]
你可以将第五行这么改
```
<span :key="i">click！</span>
```
