### ISSUE TITLE
Where can I find a normal sass Or less?

### ISSUE THREAD

**Issue by JohnBigBang** [TuSimple/naive-ui#737]
### This function solves the problem (这个功能解决的问题)
Where can I find a normal sass Or less?
### Expected API (期望的 API)
Where can I find a normal sass Or less?

**Comment by Talljack** [comment]
what do you mean?  Do you want to find sass or less in naiveUI code?

**Comment by JohnBigBang** [comment]
> what do you mean? Do you want to find sass or less in naiveUI code?

Yes. There should be a css code. This is a UI library, right? I need a deep customization of the several components. I can't even find the names of the css classes that are generated. 

For example: 
https://github.com/TuSimple/naive-ui/blob/main/src/dropdown/src/styles/index.cssr.ts

I don't understand what it is And how to change this in my sass ... .. .

**Comment by 07akioni** [comment]
> > what do you mean? Do you want to find sass or less in naiveUI code?
> 
> Yes. There should be a css code. This is a UI library, right? I need a deep customization of the several components. I can't even find the names of the css classes that are generated.
> 
> For example:
> https://github.com/TuSimple/naive-ui/blob/main/src/dropdown/src/styles/index.cssr.ts
> 
> I don't understand what it is And how to change this in my SCSS... .. .

There is no sass or less in the library, all the styles are css in js.

If you want to change the style you may need to write common style files to overrides it.

(For not complex changes you may just customize the theme of naive ui by using config provider)

**Comment by JohnBigBang** [comment]
@07akioni Is there a way to extract the css code into a separate file, like "ExtractTextWebpackPlugin" or "MiniCssExtractPlugin" or something like that?

> There is no sass or less in the library, all the styles are css in js.

May I ask what is the reason why Css is hard-coded in js?

 :-)

**Comment by JohnBigBang** [comment]
Is there a way to disable embedding Css code in the body? So that I can write and manually import my own?

**Comment by 07akioni** [comment]
> Is there a way to disable embedding Css code in the body? So that I can write and manually import my own?

1. Currently there is no way.

2. You want write the entire style by your self? That will be very hard.

**Comment by 07akioni** [comment]
> @07akioni
> I tried using objects for customization, honestly it's hell. You can do something simple like "Hello word" app, change the colors, etc., but this is not the same as Scss. I have no idea how to work through an object with ::before, ::after, ::nth-child
> 
> Is there a way to extract the css code into a separate file, like "ExtractTextWebpackPlugin" or "MiniCssExtractPlugin" or something like that?
> 
> > There is no sass or less in the library, all the styles are css in js.
> 
> May I ask what is the reason why Css is hard-coded in js?
> 
> Is there another way? :-)

For tree-shaking. I want common user use it without the concerning of CSS (in webpack or something like that).

Also, being usable by default (without style importing) is a concerning.

**Comment by 07akioni** [comment]
> Is there a way to disable embedding Css code in the body? So that I can write and manually import my own?

I've think of it before but it requires a lot of code. (It can be implemented by some compile flags).

**Comment by 07akioni** [comment]
If you doesn't need to change the style fundamentally, you writing some styles that override the current style is recommendedl.

**Comment by JohnBigBang** [comment]
clearly, thank you for the answers

**Comment by JohnBigBang** [comment]
In different build modes, I get a different order of css styles. 

Dev mode:

1. Naive inserts styles in inline, 
2. and during development all my styles are also embedded in inline.

In the build = production mode, the following happens:

1. Naive still embeds its css code in inline
2. My css is taken out in a separate file with `index.123abc.css`

Naive inline styles in PRODUCTION mode override my css.

(This is not a question, a message to the developer)

**Comment by 07akioni** [comment]
> In different build modes, I get a different order of css styles.
> 
> Dev mode:
> 
> 1. Naive inserts styles in `inline`,
> 2. and during development all my styles are also embedded in `inline`.
> 
> In the build = production mode, the following happens:
> 
> 1. Naive still embeds its css code in `inline`
> 2. My css is taken out in a separate file with `index.123abc.css`
> 
> Naive inline styles in PRODUCTION mode override my css.
> 
> (This is not a question, a message to the developer)

Naive's style doesn't work at inline level but style block level.

For example:
```
<style>
div {
  color: --color; /** <--- this line works */
}

div {
  color: red; /** <-- this would override upper style */
}
</style>

<div style="--color: red;" /> <!-- not this line -->
```
