### ISSUE TITLE
回到顶部功能可以自定义回调函数

### ISSUE THREAD

**Issue by programmer-fly** [TuSimple/naive-ui#738]
### This function solves the problem (这个功能解决的问题)
通常我们在右下角除了回到顶部之外还会有一些二维码展示呀，问题的文档连接之类的，这些点击可能需要打开链接之类的。
### Expected API (期望的 API)
添加一个属性callback：类型为function。

**Comment by Talljack** [comment]
我理解你需要的是一个点击事件的回调？

**Comment by programmer-fly** [comment]
是的，点击事件的回调，比如点击之后可以打开一个连接而不是固定的回到顶部

**Comment by 07akioni** [comment]
那就不叫 back-top 了，只是一个看起来在页面右下角的链接，自己用 teleport 实现一个就好了

**Comment by 07akioni** [comment]
你说的这个场景我印象里通常是不同的按钮

**Comment by programmer-fly** [comment]
确实可以，只是建议添加啦，谢谢回复~(*╹▽╹*)
