### ISSUE TITLE
Cannot update value when using NInput component

### ISSUE THREAD

**Issue by jotyy** [TuSimple/naive-ui#775]
### TuSimple/naive-ui version (版本)
2.16.0

### Vue version (Vue 版本)
3.0.5

### Browser and its version (浏览器及其版本)
 92.0.4515.131

### System and its version (系统及其版本)
Window11

### Node version (Node 版本)
14.17.3

### Reappearance link (重现链接)
https://github.com/jotyy/naive-jsx-sample

### Reappearance steps (重现步骤)
`<NInput v-model_value={this.username} />` can not update the binding `username` value.

### Expected results (期望的结果)
Same behavior as `<input v-model_trim={this.username} />`.

### Actual results (实际的结果)
I don't know.

**Comment by Volankey** [comment]
It is only compatible with Babel 7. Vite is not supported at present.
If you use webpack you should use this https://github.com/vuejs/jsx-next.

**Comment by jotyy** [comment]
Solved by pass value property into `v-models`:
```
<A
  v-models={[
    [foo, "foo"],
    [bar, "bar"],
  ]}
/>
```
See the implemenation in [this repository](https://github.com/jotyy/naive-jsx-sample)
