### ISSUE TITLE
When the Data Table components are all selected, the selected state should not contain the disabled row.

### ISSUE THREAD

**Issue by kungege** [TuSimple/naive-ui#778]
### TuSimple/naive-ui version (版本)
2.16.0

### Vue version (Vue 版本)
3.2.0-beta.7

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
macos

### Reappearance link (重现链接)
https://codesandbox.io/s/dnzcb

### Expected results (期望的结果)
all selected state

**Comment by Talljack** [comment]
This is the expected situation, we will set the check box to select all instead of half when you click select all.

**Comment by 07akioni** [comment]
This is a bug
