### ISSUE TITLE
tiny 按钮 loading 时高度不齐

### ISSUE THREAD

**Issue by 002269** [TuSimple/naive-ui#787]
### TuSimple/naive-ui version (版本)
2.16.0

### Vue version (Vue 版本)
3.2.0-beta.7

### Browser and its version (浏览器及其版本)
a

### System and its version (系统及其版本)
a

### Reappearance link (重现链接)
https://codesandbox.io/s/cool-wescoff-b4xe2?file=/src/Demo.vue

### Reappearance steps (重现步骤)
https://codesandbox.io/s/cool-wescoff-b4xe2?file=/src/Demo.vue
https://b4xe2.csb.app/

当 n-button size=tiny 时，即使加了 n-space，loading 时高度也不齐，其它三种尺寸的按钮没有这问题

### Expected results (期望的结果)
修

### Actual results (实际的结果)
修

**Comment by Sepush** [comment]
you can  solve it by useing <n-button-group> to warp buttons
```vue
<template>
  <div>
    <n-button
      @click="loading = !loading"
      style="margin-bottom: 20px"
      type="primary"
    >
      给我转！
    </n-button>
    <n-space>
    <n-button-group>
      <n-button size="tiny" :loading="loading">{{
        loading ? "我喝高了" : "提交"
      }}</n-button>
      <n-button size="tiny">清空</n-button>
      <n-button size="tiny">取消</n-button>
    </n-button-group>
    </n-space>
    <n-space :size="0">
      <n-button size="small" :loading="loading">提交</n-button>
      <n-button size="small">清空</n-button>
      <n-button size="small">取消</n-button>
    </n-space>

    <n-space :size="0">
      <n-button size="medium" :loading="loading">提交</n-button>
      <n-button size="medium">清空</n-button>
      <n-button size="medium">取消</n-button>
    </n-space>

    <n-space :size="0">
      <n-button size="large" :loading="loading">提交</n-button>
      <n-button size="large">清空</n-button>
      <n-button size="large">取消</n-button>
    </n-space>
  </div>
</template>

<script>
import { defineComponent, ref } from "vue";

export default defineComponent({
  setup() {
    return {
      loading: ref(false),
    };
  },
});
</script>
```

**Comment by Sepush** [comment]
https://codesandbox.io/s/priceless-leftpad-xqcgv?file=/src/Demo.vue

**Comment by 07akioni** [comment]
> https://codesandbox.io/s/priceless-leftpad-xqcgv?file=/src/Demo.vue

虽然说这是可以的，但是我其实还没发现原因是啥

**Comment by 07akioni** [comment]
> > https://codesandbox.io/s/priceless-leftpad-xqcgv?file=/src/Demo.vue
> 
> 虽然说这是可以的，但是我其实还没发现原因是啥

这个和 icon 的 height 有关，元素一复杂 vertical align 就让人搞不清。

首先明确一点就是这不会被看作 bug。

如果要使用 n-space 的话，可以使用 `item-style="display: flex;"，这样可以使每个 item 不使用文字流进行 align。
