### ISSUE TITLE
Add onClick event on table row

### ISSUE THREAD

**Issue by martinsura** [TuSimple/naive-ui#8]
## What problem does the feature solve?
Hello,

Really nice library. Thanks for sharing. 

Playing around with table component and not able handle onClick event on table row. Documentation says there is only one event onSelect in selection mode but this is other usecase. 

## What does the proposed API look like?
Just propagate event  on table props ( onRowSelect:(record:T(any)) => void; )

Btw really nice styles - so clean! Gj

**Comment by 07akioni** [comment]
Thanks. I've add `row-props` prop on DataTable. It will be released in next version.

solved in d7b96e6

**Comment by 07akioni** [comment]
If you have time could you please adding test for it. 😂

**Comment by martinsura** [comment]
Haha sure. I have one pet project so maybe next weekend i will test it. Ty
