### ISSUE TITLE
对rem单位的支持

### ISSUE THREAD

**Issue by DotWho** [TuSimple/naive-ui#802]
### This function solves the problem (这个功能解决的问题)
针对高分率屏的支持
### Expected API (期望的 API)
主题设置中有rem单位选项支持

**Comment by 07akioni** [comment]
REM 不会对桌面端的高分屏支持起到任何帮助。

对于移动端，REM 也是过时的方案了。

从我个人角度出发，我觉得使用 REM 适配并不能提供很好的体验，等比缩放浪费屏幕空间。

从开发角度说这会对样式产生过大的影响，所以不会提供。

**Comment by Canees** [comment]
在高分屏中，rem保持原设计稿样非常重要，flex只是针对布局而言，字体适配才是重点，不管使用哪种，至少提供入口来配置
