### ISSUE TITLE
When the child node in the tree table data is disabled, the root node will be selected by default

### ISSUE THREAD

**Issue by kungege** [TuSimple/naive-ui#803]
### TuSimple/naive-ui version (版本)
2.16.1

### Vue version (Vue 版本)
3.2.0-beta.7

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
macos

### Reappearance link (重现链接)
https://codesandbox.io/s/focused-framework-7j5ys?file=/src/Demo.vue

**Comment by 07akioni** [comment]
@kungege 更新一下版本就好了 0.3.0
