### ISSUE TITLE
treeSelect组件在赋值后，呈现所有数据全选状态，且无法取消

### ISSUE THREAD

**Issue by lainbo** [TuSimple/naive-ui#807]
### TuSimple/naive-ui version (版本)
2.16.1

### Vue version (Vue 版本)
3.1.5

### Browser and its version (浏览器及其版本)
Chrome(92.0.4515.131)

### System and its version (系统及其版本)
Windows 21H1

### Node version (Node 版本)
14.17.3

### Reappearance link (重现链接)
https://codesandbox.io/s/infallible-christian-2s0n5?file=/src/components/HelloWorld.vue

### Reappearance steps (重现步骤)
后台获取数据，递归添加treeSelect需要的label、key，赋值

### Expected results (期望的结果)
treeSelect选项正确，且勾选项跟随:value来

### Actual results (实际的结果)
treeSelect选项正确，但勾选项没有跟随:value来，全选了所有选项，children也未能正确识别，最后一级依旧带有标识可展开的小箭头，无法取消选择

**Comment by 07akioni** [comment]
![image](https://user-images.githubusercontent.com/18677354/128605355-7e041522-92e0-4e8c-a604-9672f2c330e3.png)

最后一级有空的 children，这个会被看作是有孩子的。

**Comment by 07akioni** [comment]
check 在有空 children 的情况下会出问题，这是个 bug，会修。

不过针对于你目前的问题，只需要把最后一级的空 children 拿掉就好了。

**Comment by lainbo** [comment]
> check 在有空 children 的情况下会出问题，这是个 bug，会修。
> 
> 不过针对于你目前的问题，只需要把最后一级的空 children 拿掉就好了。

好的，感谢大佬这么晚了还能给我解惑，感谢感谢！！

**Comment by 07akioni** [comment]
> > check 在有空 children 的情况下会出问题，这是个 bug，会修。
> > 不过针对于你目前的问题，只需要把最后一级的空 children 拿掉就好了。
> 
> 好的，感谢大佬这么晚了还能给我解惑，感谢感谢！！

不客气
