### ISSUE TITLE
Undefined handling in n-input

### ISSUE THREAD

**Issue by ChenHaolinOlym** [TuSimple/naive-ui#81]
### Environment Info

- Naive UI version: 2.11.6
- Vue: 3.0.5

### Minimal Reproduction

SFC Code:
```
<template>
  <NInput v-model:value="value" type="input"></NInput>
  <input v-model="value" />
  <button @click="onClick">Button</button>
</template>

<script>
import { NInput } from "naive-ui";
import { ref } from "vue";
export default {
  components: {
    NInput: NInput,
  },
  setup() {
    const value = ref("");
    const onClick = () => {
      value.value = undefined;
    };

    return {
      value,
      onClick,
    };
  },
};
</script>

```

### What is expected?

After the button is clicked, the result of native input and n-input to be the same

### What is actually happening?

value display in n-input is not cleared

### Screenshots
Before:
![image](https://user-images.githubusercontent.com/51154093/121686888-501f6d80-caf4-11eb-97bb-2d2509b1d79b.png)
After:
![image](https://user-images.githubusercontent.com/51154093/121686956-61687a00-caf4-11eb-8411-2d09e7e8e368.png)

**Comment by 07akioni** [comment]
> ### Environment Info
> * Naive UI version: 2.11.6
> * Vue: 3.0.5
> 
> ### Minimal Reproduction
> SFC Code:
> 
> ```
> <template>
>   <NInput v-model:value="value" type="input"></NInput>
>   <input v-model="value" />
>   <button @click="onClick">Button</button>
> </template>
> 
> <script>
> import { NInput } from "naive-ui";
> import { ref } from "vue";
> export default {
>   components: {
>     NInput: NInput,
>   },
>   setup() {
>     const value = ref("");
>     const onClick = () => {
>       value.value = undefined;
>     };
> 
>     return {
>       value,
>       onClick,
>     };
>   },
> };
> </script>
> ```
> 
> ### What is expected?
> After the button is clicked, the result of native input and n-input to be the same
> 
> ### What is actually happening?
> value display in n-input is not cleared
> 
> ### Screenshots
> Before:
> ![image](https://user-images.githubusercontent.com/51154093/121686888-501f6d80-caf4-11eb-97bb-2d2509b1d79b.png)
> After:
> ![image](https://user-images.githubusercontent.com/51154093/121686956-61687a00-caf4-11eb-8411-2d09e7e8e368.png)

This is by design. If you left `props.value` to be `undefined` it will fallback to uncontrolled mode.

You should use `null` to explicitly declare that you want to controll the value.
