### ISSUE TITLE
treeSelect在给了:value默认值后，视图点击checkbox失效，回调函数返回的数据奇怪

### ISSUE THREAD

**Issue by lainbo** [TuSimple/naive-ui#810]
### TuSimple/naive-ui version (版本)
2.16.1

### Vue version (Vue 版本)
3.1.5

### Browser and its version (浏览器及其版本)
Chrome(92.0.4515.131)

### System and its version (系统及其版本)
Windows 21H1

### Node version (Node 版本)
14.17.3

### Reappearance link (重现链接)
https://codesandbox.io/s/musing-wave-kiz3b?file=/src/components/HelloWorld.vue

### Reappearance steps (重现步骤)
不使用default-value这个props，直接给treeSelect的:value一个初始值，模拟业务中表单回填数据，给初始值就会出现问题

### Expected results (期望的结果)
1）正常回填数据，treeSelect组件正常响应，勾选后双向绑定的值变化(或本意就是通过回调函数自己设置？)
2）在添加了default-expand-all 属性的前提下，自动展开所有选项
3）on-update:value回调函数返回值正确，与视图上勾选的一致

### Actual results (实际的结果)
1）回填数据后，该treeSelect的所有checkbox点击都无效
2）在添加了default-expand-all 属性的前提下，未能展开所有选项
3）on-update:value回调函数返回值不正确（点击已经被勾选的父节点、子节点，观察控制台打印）
4）即使不给初始值，使用default-expand-all，在勾选时双向绑定的值（:value）也未发生变化(需要主动通过回调手动设置？)

### Remarks (补充说明)
上述情况都发生在给了:value一个值后出现的

**Comment by 07akioni** [comment]
handle 拿到值得更新。

value 是受控的，你填什么就会显示什么，你不该这个值那 tree-select 永远不会变。

**Comment by 07akioni** [comment]
你如果只是想顺便看一下更新了什么，可以 v-model:value="value" 和 @update:value 一起用。

**Comment by lainbo** [comment]
> 你如果只是想顺便看一下更新了什么，可以 v-model:value="value" 和 @update:value 一起用。

我明白了，意思是如果我需要回填数据，用户还可以接着改，就得用default-value，如果我试用了value，那之后的所有操作都得手动操作数据对吧

**Comment by lainbo** [comment]
> 你如果只是想顺便看一下更新了什么，可以 v-model:value="value" 和 @update:value 一起用。

我认为这样是很不方便的，比如说开关组件，不能是点一下以后要人为把switch的值手动改成true或者false，而是页面上的操作和数据都可以相互控制，不然双向绑定的体现就比较弱了，或许有说的不对的地方，请指正

**Comment by 07akioni** [comment]
> > 你如果只是想顺便看一下更新了什么，可以 v-model:value="value" 和 @update:value 一起用。
> 
> 我认为这样是很不方便的，比如说开关组件，不能是点一下以后要人为把switch的值手动改成true或者false，而是页面上的操作和数据都可以相互控制，不然双向绑定的体现就比较弱了，或许有说的不对的地方，请指正

双向绑定直接用 v-model 就可以了

**Comment by lainbo** [comment]
> > > 你如果只是想顺便看一下更新了什么，可以 v-model:value="value" 和 @update:value 一起用。
> > 
> > 
> > 我认为这样是很不方便的，比如说开关组件，不能是点一下以后要人为把switch的值手动改成true或者false，而是页面上的操作和数据都可以相互控制，不然双向绑定的体现就比较弱了，或许有说的不对的地方，请指正
> 
> 双向绑定直接用 v-model 就可以了

但是根据上面的demo，使用v-model:value，给初始值确实会导致视图无法操作，只能通过回调函数重新给:value赋值，这也确实能获得一个比较正常的表现，但也就是只能通过数据操作视图，不能从视图操作数据，感觉有点怪怪的

**Comment by 07akioni** [comment]
> > > > 你如果只是想顺便看一下更新了什么，可以 v-model:value="value" 和 @update:value 一起用。
> > > 
> > > 
> > > 我认为这样是很不方便的，比如说开关组件，不能是点一下以后要人为把switch的值手动改成true或者false，而是页面上的操作和数据都可以相互控制，不然双向绑定的体现就比较弱了，或许有说的不对的地方，请指正
> > 
> > 
> > 双向绑定直接用 v-model 就可以了
> 
> 但是根据上面的demo，使用v-model:value，给初始值确实会导致视图无法操作，只能通过回调函数重新给:value赋值，这也确实能获得一个比较正常的表现，但也就是只能通过数据操作视图，不能从视图操作数据，感觉有点怪怪的

看起来有点 bug

**Comment by 07akioni** [comment]
> > > > 你如果只是想顺便看一下更新了什么，可以 v-model:value="value" 和 @update:value 一起用。
> > > 
> > > 
> > > 我认为这样是很不方便的，比如说开关组件，不能是点一下以后要人为把switch的值手动改成true或者false，而是页面上的操作和数据都可以相互控制，不然双向绑定的体现就比较弱了，或许有说的不对的地方，请指正
> > 
> > 
> > 双向绑定直接用 v-model 就可以了
> 
> 但是根据上面的demo，使用v-model:value，给初始值确实会导致视图无法操作，只能通过回调函数重新给:value赋值，这也确实能获得一个比较正常的表现，但也就是只能通过数据操作视图，不能从视图操作数据，感觉有点怪怪的

应该是 vue 的一个特性（或者问题）。

你如果使用 @update:value 就没问题了，用 `:on-update-value` 就有问题。

具体原因是这样：

```
@update:value 会被转化为 `onUpdate:value`

而

:on-update-value 会被转化为 `on-update:value`

第一个会合并 v-model 修改数据的回调，而第二个会覆盖 v-model 的修改数据的回调
```

**Comment by 07akioni** [comment]
![image](https://user-images.githubusercontent.com/18677354/128621031-7baa3852-fc4c-4cb2-b44e-05f72fdd8072.png)

**Comment by lainbo** [comment]
> > > > > 你如果只是想顺便看一下更新了什么，可以 v-model:value="value" 和 @update:value 一起用。
> > > > 
> > > > 
> > > > 我认为这样是很不方便的，比如说开关组件，不能是点一下以后要人为把switch的值手动改成true或者false，而是页面上的操作和数据都可以相互控制，不然双向绑定的体现就比较弱了，或许有说的不对的地方，请指正
> > > 
> > > 
> > > 双向绑定直接用 v-model 就可以了
> > 
> > 
> > 但是根据上面的demo，使用v-model:value，给初始值确实会导致视图无法操作，只能通过回调函数重新给:value赋值，这也确实能获得一个比较正常的表现，但也就是只能通过数据操作视图，不能从视图操作数据，感觉有点怪怪的
> 
> 应该是 vue 的一个特性（或者问题）。
> 
> 你如果使用 @update:value 就没问题了，用 `:on-update-value` 就有问题。
> 
> 具体原因是这样：
> 
> ```
> @update:value 会被转化为 `onUpdate:value`
> 
> 而
> 
> :on-update-value 会被转化为 `on-update:value`
> 
> 第一个会合并 v-model 修改数据的回调，而第二个会覆盖 v-model 的修改数据的回调
> ```

我明白了，感谢你的耐心回复，希望有类似情况的还是在文档上注明一下吧，这样可以更加的高效~
