### ISSUE TITLE
TreeSelect error in Firefox

### ISSUE THREAD

**Issue by n-at** [TuSimple/naive-ui#811]
### TuSimple/naive-ui version (版本)
2.16.1

### Vue version (Vue 版本)
3.1.5

### Browser and its version (浏览器及其版本)
Firefox(90.0.2)

### System and its version (系统及其版本)
MacOS(11.5)

### Reappearance link (重现链接)
https://codesandbox.io/s/twilight-silence-cek6w?file=/src/App.vue

### Reappearance steps (重现步骤)
1. Open TreeSelect
2. Expand first item ("Rubber Soul")
3. Scroll to and select the last item ("Wait"). Error reproduces only after scroll

### Expected results (期望的结果)
Item selected.

### Actual results (实际的结果)
Throws an error: TypeError: listElRef.value is null.

In Firefox Nightly error description is TypeError: can't access property "scrollTop", listElRef.value is null

### Remarks (补充说明)
Also reproduces in Firefox Nightly 92.0a1 (2021-08-07).
Chrome 92.0.4515.131 works fine.

**Comment by 07akioni** [comment]
Firefox will emit scroll event on tree select menu close, which is not reasonable.

**Comment by 07akioni** [comment]
fixed

Just remove node_modules and reinstall
