### ISSUE TITLE
Why use Object.assign here?

### ISSUE THREAD

**Issue by brenner8023** [TuSimple/naive-ui#819]
https://github.com/TuSimple/naive-ui/blob/2e014c190e8e2e59050c69ebf2d072e5dc7c1f72/src/popover/src/Popover.ts#L55

**Comment by 07akioni** [comment]
> https://github.com/TuSimple/naive-ui/blob/2e014c190e8e2e59050c69ebf2d072e5dc7c1f72/src/popover/src/Popover.ts#L55

原先没用 cloneVNode，有的时候 vue 会提升 v-for 中的节点，导致 vnode 是同一个。

现在加了 cloneVNode 我看好像没啥用了。
