### ISSUE TITLE
Rename confusing named slots on PageHeader

### ISSUE THREAD

**Issue by SocVi100** [TuSimple/naive-ui#821]
### This function solves the problem (这个功能解决的问题)
Makes the PageHeader more generic
### Expected API (期望的 API)
Some slot names on the PageHeader component are too semantic and are tied to an specific position on the template. What happens if I want the user's avatar on the right side? Or what about if I want to put a button on the left side for toggling a panel?
Names should not be so "semantic" as they're confusing when customizing the theme and when reading the code...
So please, could you rename the slots this way (or another you consider better):
Change #avatar for #start
Change #extra for #end
Change #title for #main-content
Change #subtitle for #main-subcontent

**Comment by 07akioni** [comment]
Sematic slot means there are some specific styles binded with it, nor button won't have an `icon` slot. This is a trade off, we need to make looks consistent by default. No one would like to chose a proper header size for a builtin component (becase of lack of default styling).

Page header is a place where customization happens frequently. The customizations may be too specific and make naive's implementation unusable. The component is for the people who will adopt the current layout.
