### ISSUE TITLE
select menu option needs the header and footer slots 

### ISSUE THREAD

**Issue by Gtanghaibo** [TuSimple/naive-ui#825]
### This function solves the problem (这个功能解决的问题)
custom the actions like fuzzy search in  options
### Expected API (期望的 API)
footer slot 
header slot

### deprecated
action slot

**Comment by 07akioni** [comment]
For fuzzy search you should use filterable.

**Comment by 07akioni** [comment]
For a header slot, you need to convince me it is quite needed with some example.

**Comment by Gtanghaibo** [comment]
![image](https://user-images.githubusercontent.com/15169083/128986357-1acbf28f-fb44-4703-8499-d6340cc4b112.png)

something like this, submenu added a search function which should be setted into header slot

**Comment by 07akioni** [comment]
Why not using filterable?
