### ISSUE TITLE
提供一个过渡动画的组件

### ISSUE THREAD

**Issue by pengxiaotian** [TuSimple/naive-ui#829]
### This function solves the problem (这个功能解决的问题)
有些地方不想用 collapse组件，但是又需要 collapse 这种动画效果
### Expected API (期望的 API)
类似于 https://element-plus.gitee.io/#/zh-CN/component/transition

**Comment by 07akioni** [comment]
建议用第三方的，这些动画对于 wrapper dom 的样式是有特定要求的，我并不计划把这种组件暴露出来，用的人可能会以为组件出了 bug。

**Comment by 07akioni** [comment]
> 额 那真的是太遗憾了😞

说说你的场景

**Comment by 07akioni** [comment]
可以讨论一下

**Comment by pengxiaotian** [comment]
我的场景很简单，我有一个需要 展开/收起的场景，如果使用 collapse 组件也能做到，只不过会麻烦些，

```html
<!-- 需要嵌套使用，n-collapse-item 无法单独使用，  --->
<!-- 我可能需要重写大量的代码才能满足我的需求  --->
<n-collapse>
    <n-collapse-item title="青铜" name="1">
      <div>可以</div>
    </n-collapse-item>
  </n-collapse>
```

最后安利自己项目：
