### ISSUE TITLE
New prop of cards

### ISSUE THREAD

**Issue by amadeus711** [TuSimple/naive-ui#83]
## What problem does the feature solve?

I think the card component can add a prop to control the shadow effect of the card, like:

![image](https://user-images.githubusercontent.com/46394163/121699431-81526a80-cb01-11eb-906d-8504fd93f18b.png)

This prop can replace the current `hoverable` prop.

## What does the proposed API look like?

```html
<n-card shadow="never">
  ...
</n-card>
```
| Name | Type | Default |
| --- | --- | --- |
|shadow|  `'always' \| 'hover' \| 'never'` | `'never'` |

**Comment by 07akioni** [comment]
An always shadowed card is not commonly used. Could you give some convincing use cases?

**Comment by amadeus711** [comment]
Sorry, I didn't find a convincing use case, but from the perspective of design language, it's a good idea to write a piece of important content on a shadowed card when I want to improve the user's attention, which will make the website more hierarchical.

**Comment by 07akioni** [comment]
> Sorry, I didn't find a convincing use case, but from the perspective of design language, it's a good idea to write a piece of important content on a shadowed card when I want to improve the user's attention, which will make the website more hierarchical.

I think it may not help user since their designer will propose various box-shadow, thus they have to write custom css instead of using a built in prop.

**Comment by 07akioni** [comment]
> Sorry, I didn't find a convincing use case, but from the perspective of design language, it's a good idea to write a piece of important content on a shadowed card when I want to improve the user's attention, which will make the website more hierarchical.

I think it may not help user since their designer will propose various box-shadow, thus they have to write custom css instead of using a built in prop.

However I'll keep the issue open. Waiting for further discussion.
