### ISSUE TITLE
`NCode` 支持定制slot包围标签  现在默认`pre`

### ISSUE THREAD

**Issue by afocus** [TuSimple/naive-ui#834]
### This function solves the problem (这个功能解决的问题)
比如行内样式， 适合一些较短的代码展示  类似 markdown code   \` ,  \`\`\`  的区别。还有可能配合`NEllipsis`实现省略
### Expected API (期望的 API)
`tag:string (default:pre)`

`<n-code code="panic(err)" language="go" tag="div"/>`

**Comment by 07akioni** [comment]
> 基本上按照markdown关于code的样式 也就是块状和行内

需要行内 + 高亮吗？我觉得这个并不是很常见的需求呢。

如果只是需要 github 这种行内高亮的话，那么 `<n-text code>就可以满足了</n-text>`

**Comment by afocus** [comment]
这个确实不常见，还是看场景和产品需求了
但是支持行内特性的改动并不复杂，多一些特性总是好的吧。

**Comment by 07akioni** [comment]
> 还是看场景和产品需求了
> 但是支持行内特性

也不是越多越好，如果我感觉这个东西没啥用的话就不会考虑添加了，因为会有额外的维护成本。

到目前为止我确实没到过行内高亮的 case，你能找到一些例子么？

**Comment by afocus** [comment]
目前是我们产品上有类似的需求，如果觉得维护麻烦，我可以自行封装一个。只是觉得有类似的东西，不想重复制轮子。 这只是一个建议，我尊重您的决定 @07akioni

**Comment by 07akioni** [comment]
> 目前是我们产品上有类似的需求，如果觉得维护麻烦，我可以自行封装一个。只是觉得有类似的东西，不想重复制轮子。 这只是一个建议，我尊重您的决定 @07akioni

能说说产品的需求吗？你可以暂时用 CSS 覆盖一下，就可以 inline 了。

**Comment by afocus** [comment]
> > 目前是我们产品上有类似的需求，如果觉得维护麻烦，我可以自行封装一个。只是觉得有类似的东西，不想重复制轮子。 这只是一个建议，我尊重您的决定 @07akioni
> 
> 能说说产品的需求吗？你可以暂时用 CSS 覆盖一下，就可以 inline 了。

我们产品需要引用一些短的代码片段，和其他文案组合。这些引用可能是一行的开始结束区间某个片段。  
确实比较冷门，我觉得您的建议使用css覆盖，是一个不错的解决方案
