### ISSUE TITLE
n-space 默认上下左右都有间隙，应该根据布局方式添加间隙

### ISSUE THREAD

**Issue by pengxiaotian** [TuSimple/naive-ui#839]
### TuSimple/naive-ui version (版本)
2.16.2

### Vue version (Vue 版本)
3.2.1

### Browser and its version (浏览器及其版本)
Chrome 92

### System and its version (系统及其版本)
Mac OS

### Reappearance link (重现链接)
https://codesandbox.io/s/vmpmh?file=/src/Demo.vue

### Reappearance steps (重现步骤)
space 组件默认行为

### Expected results (期望的结果)
除了 size 为 数组情况时：
1. vertical = false 水平布局时：size 的间隙 应该只对左右有效果
2. vertical = true 垂直布局时：size 的间隙 应该只对上下有效果

### Actual results (实际的结果)
无论什么布局，都需要通过 size=[0, 5] 来消除相反方向的间隙

**Comment by 07akioni** [comment]
当然我觉得这么改也是有道理的，但是我还是需要了解一下使用者想的是啥。

**Comment by pengxiaotian** [comment]
我明白 space 默认是换行的，但是以我们项目组为例，不换行的场景远远多于换行的场景，所以我觉得 如果发生换行在手动指定size 也不错啊

**Comment by 07akioni** [comment]
> 我明白 space 默认是换行的，但是以我们项目组为例，不换行的场景远远多于换行的场景，所以我觉得 如果发生换行在手动指定size 也不错啊

我的意思是不换行的话你也看不出 margin 来，为啥要改一个看不出来的东西呢？

另外就是如果换行的话你无论如何都是要设定的，那这么做的意义在哪里？

**Comment by pengxiaotian** [comment]
它会导致内容行高被撑高

**Comment by 07akioni** [comment]
> 它会导致内容行高被撑高

来个例子看看？

**Comment by pengxiaotian** [comment]
我直接用官网例子了：

```html

<div style="
    /* height: 36px; */
    /* line-height: 36px; */
    /* border: 1px solid #f60; */
">
  <n-space style="
    /* height: 36px; */
    /* line-height: 36px; */
    border: 1px solid #000;
">
    <n-button>Oops!</n-button>
    <n-button>Oops!</n-button>
    <n-button>Oops!</n-button>
  </n-space>
<div>

```
<img src="https://user-images.githubusercontent.com/27847994/129301547-e877743e-19d7-4e90-820f-f881d1abe9b9.png" width="300">

如果没设置父容器的高度，实际高度 `36px` 多了 `8px`, 并不是我想要的结果。
如果设置了固定高度，space 内容会超出容器范围，虽然不影响布局，但是调试的时候心里还是很难受😞

<img src="https://user-images.githubusercontent.com/27847994/129302483-d4de09c4-d0c9-402b-a01f-80b12589faf0.png" width="300">


当然这些都不是啥太大问题，只是提个建议哈 ☺️ XD。

**Comment by 07akioni** [comment]
> 我直接用官网例子了：
> 
> ```
> <div style="
>     /* height: 36px; */
>     /* line-height: 36px; */
>     /* border: 1px solid #f60; */
> ">
>   <n-space style="
>     /* height: 36px; */
>     /* line-height: 36px; */
>     border: 1px solid #000;
> ">
>     <n-button>Oops!</n-button>
>     <n-button>Oops!</n-button>
>     <n-button>Oops!</n-button>
>   </n-space>
> <div>
> ```
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/27847994/129301547-e877743e-19d7-4e90-820f-f881d1abe9b9.png">
> 
> 如果没设置父容器的高度，实际高度 `36px` 多了 `8px`, 并不是我想要的结果。
> 如果设置了固定高度，space 内容会超出容器范围，虽然不影响布局，但是调试的时候心里还是很难受😞
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/27847994/129302483-d4de09c4-d0c9-402b-a01f-80b12589faf0.png">
> 
> 当然这些都不是啥太大问题，只是提个建议哈 XD。
> 
> 大佬是在国外么？怎么每天凌晨还在工作。。

我在北京，我没得选hhh

**Comment by 07akioni** [comment]
> 我直接用官网例子了：
> 
> ```
> <div style="
>     /* height: 36px; */
>     /* line-height: 36px; */
>     /* border: 1px solid #f60; */
> ">
>   <n-space style="
>     /* height: 36px; */
>     /* line-height: 36px; */
>     border: 1px solid #000;
> ">
>     <n-button>Oops!</n-button>
>     <n-button>Oops!</n-button>
>     <n-button>Oops!</n-button>
>   </n-space>
> <div>
> ```
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/27847994/129301547-e877743e-19d7-4e90-820f-f881d1abe9b9.png">
> 
> 如果没设置父容器的高度，实际高度 `36px` 多了 `8px`, 并不是我想要的结果。
> 如果设置了固定高度，space 内容会超出容器范围，虽然不影响布局，但是调试的时候心里还是很难受😞
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/27847994/129302483-d4de09c4-d0c9-402b-a01f-80b12589faf0.png"> 
> 
> 当然这些都不是啥太大问题，只是提个建议哈 XD。
> 
> 大佬是在国外么？怎么每天凌晨还在工作。。

![image](https://user-images.githubusercontent.com/18677354/129594991-c7970bd1-31a2-4325-98ed-46df0848f5b2.png)

只是你看着难受，但是排版没受任何影响

**Comment by pengxiaotian** [comment]
好吧，我先关了🤨
