### ISSUE TITLE
Ability to use Vue Router router-link component in menus

### ISSUE THREAD

**Issue by djmattyg007** [TuSimple/naive-ui#84]
Menu items should have the option of creating `router-link` components to support native routing functionality provided by Vue Router. This should also ensure actual `<a>` tags are generated, so as to be more friendly to accessibility.

**Comment by 07akioni** [comment]
The demand does exist. The API should be designed carefully. I need to think it for some time.

**Comment by 07akioni** [comment]
I'm thinking of adding `tag` and `props` prop to menu option. However I need to verify if type constraint will work.

**Comment by 07akioni** [comment]
ref https://www.naiveui.com/en-US/os-theme/components/menu#select

**Comment by djmattyg007** [comment]
Would you consider updating the menus on the documentation site to use this? The current way of how it handles navigation means I can't middle-click the links to open them in new tabs, which is very frustrating.

**Comment by djmattyg007** [comment]
I definitely appreciate the flexibility of this approach, but it would be nice to have a slightly nicer way of handling the common use case of a `<router-link>` with route props. This will end up being very verbose for longer menus.

**Comment by 07akioni** [comment]
> Would you consider updating the menus on the documentation site to use this? The current way of how it handles navigation means I can't middle-click the links to open them in new tabs, which is very frustrating.

You can click 
![image](https://user-images.githubusercontent.com/18677354/122060533-4497b380-ce20-11eb-953d-4274b53e515a.png)

And a new tab will be opened.


![image](https://user-images.githubusercontent.com/18677354/122060472-36499780-ce20-11eb-801f-0d4e037d11b7.png)

**Comment by 07akioni** [comment]
> I definitely appreciate the flexibility of this approach, but it would be nice to have a slightly nicer way of handling the common use case of a `<router-link>` with route props. This will end up being very verbose for longer menus.

I can understand your concern. I'm not going to add props directly relevent to `router-link` since it will make option verbose.

Instead I think it's possible to create a `render-label` prop for menu if you want to create a longer menu will duplicate logic.

**Comment by djmattyg007** [comment]
I meant the main navigation links on the docs site:

![image](https://user-images.githubusercontent.com/489338/122063457-9f86d600-ce33-11eb-9d4b-2e8561a056cf.png)

I can't middle click these, nor can I see where they will take me by hovering over them. This is because they are not regular links.

**Comment by 07akioni** [comment]
> I meant the main navigation links on the docs site:
> 
> ![image](https://user-images.githubusercontent.com/489338/122063457-9f86d600-ce33-11eb-9d4b-2e8561a056cf.png)
> 
> I can't middle click these, nor can I see where they will take me by hovering over them. This is because they are not regular links.

I got it.

**Comment by djmattyg007** [comment]
> this may take a while

That's part of why I suggested providing a nicer way of using `<router-link>` specifically :wink:

**Comment by amadeus711** [comment]
I'll develop it

**Comment by 07akioni** [comment]
> > this may take a while
> 
> That's part of why I suggested providing a nicer way of using `<router-link>` specifically 😉

Done

**Comment by djmattyg007** [comment]
:+1: I think this was a great solution, thank you!

**Comment by abcd498936590** [comment]
> > > 这可能需要一段时间
> > 
> > 
> > 这就是为什么我建议提供一种更好的方法来专门使用😉`<router-link>`
> 
> 做

Your solution solves my need. thank you
