### ISSUE TITLE
Select menu support variadic option height

### ISSUE THREAD

**Issue by 07akioni** [TuSimple/naive-ui#844]
### This function solves the problem (这个功能解决的问题)
Sometime users need to render options higher than default option.
### Expected API (期望的 API)
No API changed.

**Comment by zzal** [comment]
I'm confused. Is this a feature request or documentation addendum?

We need a way to customize the Select's menu height.
If I understand correctly, it is set by `--height:calc(var(--option-height) * 7.6);` at the `.n-base-select-menu.n-select-menu` HTML node.

But apparently there's no way to override this value, Am I right?

**Comment by 07akioni** [comment]
It isn't well documented. It can be set by peers overrides.

```
themeOverrides: GlobalThemeOverrides = {
  Select: {
    peers: {
      InternalSelectMenu: { ... }
    }
  }
}
```

**Comment by 07akioni** [comment]
The issue can't be closed.

**Comment by zzal** [comment]
My suggested value:

```
const themeOverrides: GlobalThemeOverrides = {
  Select: {
    peers: {
      InternalSelectMenu: {
        height: 'clamp(3rem, calc(var(--option-height) * 15.66), 90vh)',
      },
    }
  }
}
```

**Comment by 07akioni** [comment]
> My suggested value:
> 
> ```
> const themeOverrides: GlobalThemeOverrides = {
>   Select: {
>     peers: {
>       InternalSelectMenu: {
>         height: 'clamp(3rem, calc(var(--option-height) * 15.66), 90vh)',
>       },
>     }
>   }
> }
> ```

In different scenes the proper height would be different. Override it when needed is great.

**Comment by fanchenio** [comment]
能否单独设置某一个Select的最大高度？通过GlobalThemeOverrides设置的话就覆盖全局了，我只有某一个页面非常短，所以需要调整select的最大高度。 @07akioni
