### ISSUE TITLE
Data Table Pagination Props page-count is always undefined

### ISSUE THREAD

**Issue by felismargarita** [TuSimple/naive-ui#849]
### TuSimple/naive-ui version (版本)
2.16.2

### Vue version (Vue 版本)
3.2.2

### Browser and its version (浏览器及其版本)
any

### System and its version (系统及其版本)
any

### Node version (Node 版本)
any

### Reappearance link (重现链接)
https://codesandbox.io/s/sad-bash-ply87?file=/src/App.vue

### Reappearance steps (重现步骤)
1.set the pagination prop for data table  
2.set the page-count prop for pagination,like  
{
page:1,
pageCount:100
}  
3.the pagination component display only one page 

### Expected results (期望的结果)
fix the bug

### Actual results (实际的结果)
show all the pages if the pageCount prop is set to the data table pagination prop

### Remarks (补充说明)
在data-table组件里给pagination设置pageCount总页数,实际渲染出来的页码永远只有第1页

**Comment by felismargarita** [comment]
I check the source code of data-table，seems the problem is caused by this part，you see the pageCount is always undefined：
file：use-table-data.ts
line：342-345，
code：
      pageCount:
        mergedItemCountRef.value === undefined
          ? mergedPageCountRef.value
          : undefined,

**Comment by Talljack** [comment]
If you want pageCount to take effect, then you need to set the value of pageSize, otherwise the default is 10, and in non-remote, table will calculate the length of data by default for paging calculation. like this
![image](https://user-images.githubusercontent.com/34439652/129127243-5a857d96-47bf-4fae-b7cf-2de666cf5efb.png)

**Comment by felismargarita** [comment]
> If you want pageCount to take effect, then you need to set the value of pageSize, otherwise the default is 10, and in non-remote, table will calculate the length of data by default for paging calculation. like this
> ![image](https://user-images.githubusercontent.com/34439652/129127243-5a857d96-47bf-4fae-b7cf-2de666cf5efb.png)

Thanks for your answer!I understand that the data table pagination will be effected by both the data length and page size,however,please consider the situation,when we fetch data from the server with pagination parameters ,that means,the whole data length should be a huge number,even over than 100000 [ just an example  :) ],so the server will only send back the current page data which length will be 10 (if the pagination parameter page-size is 10 ),so in this situation,let the data length control the page count is not reasonable, so the page count prop of pagination should take in charge of page count control.
 In a word ,if the prop page count is provided,this prop should be in the first priority.

**Comment by felismargarita** [comment]
> If you want pageCount to take effect, then you need to set the value of pageSize, otherwise the default is 10, and in non-remote, table will calculate the length of data by default for paging calculation. like this
> ![image](https://user-images.githubusercontent.com/34439652/129127243-5a857d96-47bf-4fae-b7cf-2de666cf5efb.png)

Thanks for your reply!I understand that if I need to control the data table pagination without auto calculating page count the prop remote = true should be set.Sorry for missing the remote prop in the document.
