### ISSUE TITLE
Form hide label props 隱藏表單label

### ISSUE THREAD

**Issue by Proladon** [TuSimple/naive-ui#858]
### This function solves the problem (这个功能解决的问题)
更客製能符合更多使用情境
有時候不希望顯示label 但目前label沒有顯示的開關，會一直佔用grid的一個高度欄位
與input的區別是，在不希望顯示label的情境下，仍有表單驗證功能
### Expected API (期望的 API)
```html
<n-form :hide-label="true" />
```

**Comment by Volankey** [comment]
`<n-form :show-label="false" />`

**Comment by kev1nzh37** [comment]
> 更客製能符合更多使用情境
> 有時候不希望顯示label� 但目前label沒有顯示的開關，會一直佔用grid的一個高度欄位
> 與input的區別是，在不希望顯示label的情境下，仍有表單驗證功能

在目前的版本`2.16.2`中，传入 false 会不展示 label 的高度栏位。

```vue
 // 正常情况
  <n-form-item label="姓名" path="user.name">
    <n-input v-model:value="formValue.user.name" placeholder="输入姓名" />
  </n-form-item>

// 不需要 label 和占位时 
  <n-form-item :label="false" path="user.name">
    <n-input v-model:value="formValue.user.name" placeholder="输入姓名" />
  </n-form-item>
```

**Comment by 07akioni** [comment]
> > 更客製能符合更多使用情境
> > 有時候不希望顯示label� 但目前label沒有顯示的開關，會一直佔用grid的一個高度欄位
> > 與input的區別是，在不希望顯示label的情境下，仍有表單驗證功能
> 
> 在目前的版本`2.16.2`中，传入 false 会不展示 label 的高度栏位。
> 
> ```
>  // 正常情况
>   <n-form-item label="姓名" path="user.name">
>     <n-input v-model:value="formValue.user.name" placeholder="输入姓名" />
>   </n-form-item>
> 
> // 不需要 label 和占位时 
>   <n-form-item :label="false" path="user.name">
>     <n-input v-model:value="formValue.user.name" placeholder="输入姓名" />
>   </n-form-item>
> ```

需要保证 `show-label=false` 的时候 label 也不占位
