### ISSUE TITLE
Allow customisation of empty data table content

### ISSUE THREAD

**Issue by djmattyg007** [TuSimple/naive-ui#86]
## What problem does the feature solve?

If an error occurs while loading the data used to fill the data table, I would like to show an error message rather than just saying "No data".

## What does the proposed API look like?

Other frameworks tend to handle this with a slot.

**Comment by 07akioni** [comment]
Good idea, would you like to open a PR for it?

**Comment by djmattyg007** [comment]
I can't commit to anything at this stage sorry.

**Comment by 07akioni** [comment]
> I can't commit to anything at this stage sorry.

No problem. I'll manage to add it.
