### ISSUE TITLE
Menu support expand strategy

### ISSUE THREAD

**Issue by pipinet** [TuSimple/naive-ui#864]
### This function solves the problem (这个功能解决的问题)
通常Menu都是使用在侧边栏的，而大部分菜单栏都是根据当前路由来决策的，所以希望提供一些常用的expand strategy，让Menu使用更简单。
### Expected API (期望的 API)
提供一个expand-strategy参数，用来内置一些可选的展开策略。例如：跟随选中，跟随路由，自定义（目前是该策略的传入展开）等。

**Comment by 07akioni** [comment]
这件事太业务逻辑了，不适合做这么耦合的事。如果你觉得我的看法不合理，可以提出更加具体的 API 和设计。
