### ISSUE TITLE
After using notificationreactive as the type in typescript, the content of the notification component is readonly

### ISSUE THREAD

**Issue by YiFo0315** [TuSimple/naive-ui#876]
### This function solves the problem (这个功能解决的问题)
How can I dynamically modify the content of a component
### Expected API (期望的 API)
If I modify the value, I will prompt TS2540: Cannot assign to 'title' because it is a read-only property.
What should I do？

**Comment by YiFo0315** [comment]
![image](https://user-images.githubusercontent.com/80516655/129475990-84f1b998-b7ca-4622-b532-2311c3c89165.png)

**Comment by Volankey** [comment]
I think you should use like the follow code:
```
const notification = useNotification()
const instance =  notification.create({
          title: "Wouldn't it be Nice",
          description: 'From the Beach Boys',
          content: `1234`,
          meta: '2019-5-27 15:11',
          avatar: () =>
            h(NAvatar, {
              size: 'small',
              round: true,
              src: 'https://07akioni.oss-cn-beijing.aliyuncs.com/07akioni.jpeg'
            }),
          onAfterLeave: () => {
            message.success("Wouldn't it be Nice")
          }
        })
instance.title = 'xxxx'
```
If you want to use it in outside setup, refer to https://www.naiveui.com/en-US/os-theme/components/message#Q-&-A.

**Comment by Volankey** [comment]
`NotificationReactive` type will fix.
