### ISSUE TITLE
Some typescript error in NMenu and NCalendar

### ISSUE THREAD

**Issue by beiyanpiki** [TuSimple/naive-ui#88]
### Environment Info

- Naive UI version: 2.11.7
- Vue version: 3.0.5
- Browser Info: Microsoft Edge 91.0.864.41
- System Info: Windows 10 (Arch WSL)

### Reproduction link

https://codesandbox.io/s/ts-error-in-nmenu-and-ncalendar-77xxs?file=/src/App.vue

### Steps to reproduce

I use `vite` and `vue-ts` as my startup project, every thing is ok in dev server, but when I try to run ``yarn vue-tsc --noEmit && vite build`` got some ts error. And I found both of error come from `@update:value` method.

```bash
# Create a vue-ts project and install naive-ui
$ yarn create @vitejs/app naive-test --template vue-ts && cd naive-test && yarn
$ yarn add naive-ui
```

// App.vue
```vue
<template>
  <NCalendar @update:value="handleUpdateCalendarValue">
    <template #="{ year, month, date }"> </template>
  </NCalendar>
  <NMenu @update:value="handleUpdateMenuValue" :options="menuOptions" />
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { MenuOption, NCalendar, NMenu } from "naive-ui";
export default defineComponent({
  name: "App",
  components: {
    NCalendar,
    NMenu,
  },
  setup() {
    const menuOptions = [
      {
        label: "Item1",
        key: "item1",
      },
      {
        label: "Item2",
        key: "item2",
      },
    ];

    const handleUpdateCalendarValue = (
      timestamp: number,
      { year, month, date }: { year: number; month: number; date: number }
    ) => {
      console.log({ timestamp, year, month, date });
    };

    const handleUpdateMenuValue = (key: string, item: MenuOption) => {
      console.log("key =>", key);
      console.log("item =>", item);
    };

    return {
      handleUpdateCalendarValue,

      menuOptions,
      handleUpdateMenuValue,
    };
  },
});
</script>
```

```bash
$ yarn vue-tsc --noEmit
```

### What is expected?

No error in typescript check.

### What is actually happening?

![image](https://user-images.githubusercontent.com/36980069/121772930-39881d80-cbab-11eb-93c1-b8afc9ffa610.png)

**Comment by 07akioni** [comment]
Calendar do have a bug in type of `on-update:value` which is fixed in 5a7b2fa0e23d3a78a094b00330c0d1578322d1e3.

However the other errors may related to volar. https://github.com/johnsoncodehk/volar/issues/266
