### ISSUE TITLE
n-message: Distinguish message types

### ISSUE THREAD

**Issue by pengxiaotian** [TuSimple/naive-ui#880]
### This function solves the problem (这个功能解决的问题)
Custom message style
### Expected API (期望的 API)
1. `<div class='n-message n-message-${type}'></div>`

or

2. MessageOption: { custome-class: '' }

**Comment by pengxiaotian** [comment]
我想 根据不同类型显示不同颜色的边框，但是可惜没有 `border` 这个变量，而且组件根节点 class 也没能区分是啥类型的

![image](https://user-images.githubusercontent.com/27847994/129486178-c0d2c16b-6da3-47d2-9d3b-1eaae2bb4aaa.png)

**Comment by 07akioni** [comment]
@pengxiaotian 来个 PR，可以的。用这种方式的类名 `message--xxx-type`

**Comment by pengxiaotian** [comment]
好的👌

**Comment by pengxiaotian** [comment]
热乎的PR：https://github.com/TuSimple/naive-ui/pull/882
