### ISSUE TITLE
Tooltip prop for button components

### ISSUE THREAD

**Issue by Blakeinstein** [TuSimple/naive-ui#889]
### This function solves the problem (这个功能解决的问题)
Mainly for tooltips on buttons in a button group.
Sometimes, some buttons are part of an action group, and icons available are not enough to tell the use. A tooltip on buttons is anyways a very basic usecase. 
### Expected API (期望的 API)
```html
<n-button  tooltip-text="This is a button" >
  <template #icon>
     <n-icon><some-icon /></n-icon>
  </template>
</n-button>

<!-- generated by issue-helper DO NOT REMOVE __FEATURE_REQUEST__ -->

**Comment by Blakeinstein** [comment]
I think I worded this a bit badly. I was asking for a native tooltip prop for the button component.

**Comment by Volankey** [comment]
If you want to use browser's native tooltip, just add `title` as a prop to `n-button`. 
```
  <n-button title="I need a tip~" circle>
      <template #icon>
        <n-icon><cash-icon /></n-icon>
      </template>
  </n-button>
```
-----------------------------------------
I think add `tooltip-text` to `n-button`  is not meaningful, It is not hard to use n-tool to combine.
Maybe you can encapsulate a ToolTipButton like the follow code.
```
  <n-tooltip>
      {{tip}}
      <template #trigger>
          <template #icon>
             <n-icon><slot name="icon"></n-icon>
          </template>
      </template>
   </n-tooltip>
```

**Comment by Blakeinstein** [comment]
> It is not hard to use n-tooltip to combine.

Sure, but can you tell me how to do this with n-button-group?

**Comment by Volankey** [comment]
> > It is not hard to use n-tooltip to combine.
> 
> Sure, but can you tell me how to do this with n-button-group?

https://codesandbox.io/s/tender-architecture-7jbml?file=/src/Demo.vue

**Comment by Blakeinstein** [comment]
The codesandbox appears empty. 🤔
