### ISSUE TITLE
useOsTheme 返回的值都是dark

### ISSUE THREAD

**Issue by gx1123** [TuSimple/naive-ui#891]
### TuSimple/naive-ui version (版本)
2.16.4

### Vue version (Vue 版本)
3.0.5

### Browser and its version (浏览器及其版本)
Chrome(92.0.4515.131)

### System and its version (系统及其版本)
MasOs(11.5.1)

### Reappearance link (重现链接)
https://github.com/TuSimple/naive-ui

### Reappearance steps (重现步骤)
点击切换官网切换主题    查看当前操作系统的主题是 

### Expected results (期望的结果)
返回正确的值

### Actual results (实际的结果)
一直是dark

**Comment by Volankey** [comment]
主题是根据 mac上的电脑设置 深色/浅色 返回 dark/light，具体底层也是调用的chrome提供的接口
我这边用最新的操作系统无法复现
