### ISSUE TITLE
数据表格建议增加列筛选,可以自定义列的显示,并且支持动态参数去默认初始化要显示的列.

### ISSUE THREAD

**Issue by hanjialin** [TuSimple/naive-ui#898]
### This function solves the problem (这个功能解决的问题)
某些业务场景下,表格可能会出现较多列,这个功能解决了数据表格不支持列筛选的问题.
### Expected API (期望的 API)
<n-data-table :columns="cols" :data="data" :colfilter="true" :colFilterDefault="[A1,B1,C1,D1]" />

**Comment by Volankey** [comment]
列的渲染完全由开发者来控制，我认为这不属于组件级别要做的事情，开发者只需要对列进行computed，通过Array.prototype.filter进行列筛选，并不麻烦。

**Comment by hanjialin** [comment]
> 列的渲染完全由开发者来控制，我认为这不属于组件级别要做的事情，开发者只需要对列进行computed，通过Array.prototype.filter进行列筛选，并不麻烦。
可否说的再详细一点。谢谢提供思路。
