### ISSUE TITLE
form-item验证提升信息不显示仍会撑大form-item高度

### ISSUE THREAD

**Issue by yibird** [TuSimple/naive-ui#899]
### This function solves the problem (这个功能解决的问题)
form-item因为有验证信息元素的显示占用了高度,会把form-item撑大,form底部会有多余的留白,这样会导致form不是很美观
### Expected API (期望的 API)
建议将验证信息元素在非激活情况高度设置为0,若激活验证信息元素div高度将自适应。

**Comment by Volankey** [comment]
这个在设计的时候有做过考虑，如果高度自适应，出现提示的话也会造成布局的抖动

**Comment by 07akioni** [comment]
我记得有个 showFeedback 的 prop，不需要就关掉。总而言之抖动是不能接受的。
