### ISSUE TITLE
Documentation mis-match for rowKey prop on DataTable component

### ISSUE THREAD

**Issue by djmattyg007** [TuSimple/naive-ui#90]
The documentation suggests that `rowKey` can be either a `String` or a `Function`, but the type of the prop is defined only as a `Function`. Attempting to pass a `String` results in a warning from the Vue core.

**Comment by djmattyg007** [comment]
Ah, it appears I misunderstood the type declaration in the documentation. Nevermind.

**Comment by 07akioni** [comment]
It's not your problem. I've made it more explicit in b008d51039aa22e97ac4e9559e82c5a66bba821e.
