### ISSUE TITLE
替换所有默认图标有什么好的方式么

### ISSUE THREAD

**Issue by pengxiaotian** [TuSimple/naive-ui#900]
### This function solves the problem (这个功能解决的问题)
我有自己的一套 UI 图标

### Expected API (期望的 API)
越简单越好

**Comment by 07akioni** [comment]
ConfigProvider 有一些没有公开的属性，看源码吧，未来有改的可能。

**Comment by 07akioni** [comment]
如果未来全部的图标都迁移到可替换的，可以考虑开放这个 Api，欢迎 PR。

顺便尽量用英语提 issue。

**Comment by pengxiaotian** [comment]
好的，我看情况，先用一个加一个
