### ISSUE TITLE
单选组件选中值类型被改变

### ISSUE THREAD

**Issue by duxphp** [TuSimple/naive-ui#904]
### TuSimple/naive-ui version (版本)
2.16.4

### Vue version (Vue 版本)
3.2.4

### Browser and its version (浏览器及其版本)
edge 92

### System and its version (系统及其版本)
MacOS

### Reappearance link (重现链接)
https://codesandbox.io/s/solitary-brook-z1ld6?file=/src/Demo.vue

### Reappearance steps (重现步骤)
当单选组为对象时 选中后的值会被自动转换为字符串类型

### Expected results (期望的结果)
选中的类型应该保持不变

### Actual results (实际的结果)
实际结果自动转换为了文本类型

**Comment by doom-9** [comment]
value绑定的key不就是个字符串吗
