### ISSUE TITLE
表单的输入框在开启自定义验证后存在中文输入问题

### ISSUE THREAD

**Issue by WankkoRee** [TuSimple/naive-ui#905]
### TuSimple/naive-ui version (版本)
2.16.4

### Vue version (Vue 版本)
3.1.5

### Browser and its version (浏览器及其版本)
Chrome 86.0.4240.198

### System and its version (系统及其版本)
Windows 10 21H1

### Node version (Node 版本)
14.15.4

### Reappearance link (重现链接)
https://github.com/TuSimple/naive-ui/tree/docs

### Reappearance steps (重现步骤)
启用表单输入框的自定义验证功能，在输入框中输入一些任意的文本，接着在这些文本的中间（不需要最中间，实际上也不需要中间，只不过中间可以比较明显地展示bug）在中文输入法状态下输入一些文本，在输入结束之前（未完成字词选择的时候）将鼠标移入或者移出输入框，就会发现光标被强制切换至末尾。若输入结束后再次将鼠标移入或者移出输入框，会发现输入的内容消失。若此时打算删除输入框内容，会发现删除后依旧会在鼠标移入或者移出输入框后重新出现。

### Expected results (期望的结果)
正常完成输入和验证功能。

### Actual results (实际的结果)
影响到正常的输入操作。

### Remarks (补充说明)
提交的`minimal reproduction`指向Naive UI项目本身是因为这个bug可以在组件demo中的[自定义验证板块](https://www.naiveui.com/zh-CN/os-theme/components/form#custom-validation)直接复现。

**Comment by 07akioni** [comment]
真**是个有趣的 bug
