### ISSUE TITLE
级联选择在开启异步、多项、仅叶可选、级联关联后，无法完成选择

### ISSUE THREAD

**Issue by WankkoRee** [TuSimple/naive-ui#906]
### TuSimple/naive-ui version (版本)
2.16.4

### Vue version (Vue 版本)
3.1.5

### Browser and its version (浏览器及其版本)
Chrome 86.0.4240.198

### System and its version (系统及其版本)
Windows 10 21H1

### Node version (Node 版本)
14.15.4

### Reappearance link (重现链接)
https://github.com/TuSimple/naive-ui/tree/docs

### Reappearance steps (重现步骤)
在设置了`multiple`和`remote`时，设置`:cascade="true" :leaf-only="true"`后导致选项无法被成功选择。后两者关闭其中一个即可正常选择。

### Expected results (期望的结果)
正常完成选择。

### Actual results (实际的结果)
无法完成选择。

### Remarks (补充说明)
此bug在`2.16.3`时开始存在，可直接在组件demo中的`多项（异步）`直接复现。

**Comment by 07akioni** [comment]
叶节点还没加载出来呢，上哪里把值发送出来？

**Comment by WankkoRee** [comment]
我没表述清楚，是在已经加载到叶节点的情况下，依旧无法选择（包括去选择叶节点）。

**Comment by 07akioni** [comment]
已修复，删除 node_modules 重装即可
