### ISSUE TITLE
级联选择在开启异步、多项时，子项未完全加载时无法取消选择

### ISSUE THREAD

**Issue by WankkoRee** [TuSimple/naive-ui#907]
### TuSimple/naive-ui version (版本)
2.16.2

### Vue version (Vue 版本)
3.1.5

### Browser and its version (浏览器及其版本)
Chrome 86.0.4240.198

### System and its version (系统及其版本)
Windows 10 21H1

### Node version (Node 版本)
14.15.4

### Reappearance link (重现链接)
https://github.com/TuSimple/naive-ui/tree/docs

### Reappearance steps (重现步骤)
在设置了`multiple`和`remote`时，且设置`:cascade="true"`。
当选了某个或某些叶子节点后，显示为部分选择且子节点未完全加载的非叶子节点将无法被取消选择。

### Expected results (期望的结果)
按照非异步的多项级联选择策略，部分选择的节点在被点击时应当取消选择。

### Actual results (实际的结果)
无任何响应。

### Remarks (补充说明)
因为`2.16.2`版本是最近的相关功能可用版本(#906)，所以拿这个版本进行测试，该问题在修复 #906 后应当可直接在组件demo中的多项（异步）复现（如果两个bug的引发原因是同一个的话，那么这个issue也可以在 #906 修复后直接关闭）。

**Comment by 07akioni** [comment]
fixed, ref #906

**Comment by WankkoRee** [comment]
抱歉，这个bug并没有随着 #906 被修复。

**Comment by 07akioni** [comment]
> 抱歉，这个bug并没有随着 #906 被修复。

应该是好了，很奇怪，重装 node_modules 试试

**Comment by WankkoRee** [comment]
刚尝试过node_modules，bug依旧存在。
![image](https://user-images.githubusercontent.com/21287731/130109892-e9f7d07c-02c3-42ce-8a3c-24619f5b986c.png)

**Comment by 07akioni** [comment]
> 刚尝试过重装 node_modules，bug依旧存在。
> ![image](https://user-images.githubusercontent.com/21287731/130109892-e9f7d07c-02c3-42ce-8a3c-24619f5b986c.png)

我在本地没问题，需要一个你的数据作为复现

**Comment by WankkoRee** [comment]
```javascript
<template>
  <n-space vertical>
    <n-cascader
        v-model:value="value"
        multiple
        placeholder="没啥用的值"
        :options="options"
        :cascade="true"
        :leaf-only="true"
        :show-path="true"
        remote
        :on-load="handleLoad"
    />
  </n-space>
  加载至四级，勾选I-0-0-0-0，取消部分勾选I-0-0-0，正常。<br/>
  加载至四级，勾选I-0-0-0-0，取消部分勾选I-0-0，无法取消勾选。
</template>

<script>
import {NSpace, NCascader} from 'naive-ui'

function genChildren (option) {
  const children = []
  for (let i = 0; i <= option.depth; ++i) {
    children.push({
      label: option.label + '-' + i,
      value: option.value + '-' + i,
      depth: option.depth + 1,
      isLeaf: option.depth === 3
    })
  }
  return children
}
export default {
  name: 'App',
  components: {NSpace, NCascader},
  data () {
    return {
      value: null,
      options: [
        {
          label: 'l-0',
          value: 'v-0',
          depth: 1,
          isLeaf: false
        }
      ]
    }
  },
  methods: {
    handleLoad (option) {
      return new Promise((resolve) => {
        window.setTimeout(() => {
          option.children = genChildren(option)
          resolve()
        }, 300)
      })
    }
  }
}
</script>

<style>
</style>
```

**Comment by 07akioni** [comment]
> ```js
> <template>
>   <n-space vertical>
>     <n-cascader
>         v-model:value="value"
>         multiple
>         placeholder="没啥用的值"
>         :options="options"
>         :cascade="true"
>         :leaf-only="true"
>         :show-path="true"
>         remote
>         :on-load="handleLoad"
>     />
>   </n-space>
>   加载至四级，勾选I-0-0-0-0，取消部分勾选I-0-0-0，正常。<br/>
>   加载至四级，勾选I-0-0-0-0，取消部分勾选I-0-0，无法取消勾选。
> </template>
> 
> <script>
> import {NSpace, NCascader} from 'naive-ui'
> 
> function genChildren (option) {
>   const children = []
>   for (let i = 0; i <= option.depth; ++i) {
>     children.push({
>       label: option.label + '-' + i,
>       value: option.value + '-' + i,
>       depth: option.depth + 1,
>       isLeaf: option.depth === 3
>     })
>   }
>   return children
> }
> export default {
>   name: 'App',
>   components: {NSpace, NCascader},
>   data () {
>     return {
>       value: null,
>       options: [
>         {
>           label: 'l-0',
>           value: 'v-0',
>           depth: 1,
>           isLeaf: false
>         }
>       ]
>     }
>   },
>   methods: {
>     handleLoad (option) {
>       return new Promise((resolve) => {
>         window.setTimeout(() => {
>           option.children = genChildren(option)
>           resolve()
>         }, 300)
>       })
>     }
>   }
> }
> </script>
> ```

安排

**Comment by 07akioni** [comment]
> ```js
> <template>
>   <n-space vertical>
>     <n-cascader
>         v-model:value="value"
>         multiple
>         placeholder="没啥用的值"
>         :options="options"
>         :cascade="true"
>         :leaf-only="true"
>         :show-path="true"
>         remote
>         :on-load="handleLoad"
>     />
>   </n-space>
>   加载至四级，勾选I-0-0-0-0，取消部分勾选I-0-0-0，正常。<br/>
>   加载至四级，勾选I-0-0-0-0，取消部分勾选I-0-0，无法取消勾选。
> </template>
> 
> <script>
> import {NSpace, NCascader} from 'naive-ui'
> 
> function genChildren (option) {
>   const children = []
>   for (let i = 0; i <= option.depth; ++i) {
>     children.push({
>       label: option.label + '-' + i,
>       value: option.value + '-' + i,
>       depth: option.depth + 1,
>       isLeaf: option.depth === 3
>     })
>   }
>   return children
> }
> export default {
>   name: 'App',
>   components: {NSpace, NCascader},
>   data () {
>     return {
>       value: null,
>       options: [
>         {
>           label: 'l-0',
>           value: 'v-0',
>           depth: 1,
>           isLeaf: false
>         }
>       ]
>     }
>   },
>   methods: {
>     handleLoad (option) {
>       return new Promise((resolve) => {
>         window.setTimeout(() => {
>           option.children = genChildren(option)
>           resolve()
>         }, 300)
>       })
>     }
>   }
> }
> </script>
> 
> <style>
> </style>
> ```

已修复，请重装 node_modules

**Comment by WankkoRee** [comment]
已验证，修复成功。
