### ISSUE TITLE
Space align="center" 时不居中

### ISSUE THREAD

**Issue by PenToseLin** [TuSimple/naive-ui#911]
### TuSimple/naive-ui version (版本)
2.16.4

### Vue version (Vue 版本)
3.2.4

### Browser and its version (浏览器及其版本)
Chrome(89.0.4389.128)

### System and its version (系统及其版本)
MacOS(11.2.3)

### Reappearance link (重现链接)
https://codesandbox.io/s/naiveui-nspace-7fvsy?file=/src/Demo.vue

### Reappearance steps (重现步骤)
<n-space align="center">
    <n-avatar round>UserName</n-avatar>
    <n-button>按钮</n-button>
</n-space>

### Expected results (期望的结果)
align为center的时候和flex布局align-items: center;的布局效果一致

### Actual results (实际的结果)
avatar和button上下不居中

**Comment by 07akioni** [comment]
```
<n-space item-style="display: flex;">...</n-space>
```
