### ISSUE TITLE
passing value=ref(0) in n-input will show placeholder and 0 simutanuously

### ISSUE THREAD

**Issue by Zeiion** [TuSimple/naive-ui#914]
### TuSimple/naive-ui version (版本)
2.16.4

### Vue version (Vue 版本)
3.2.4

### Browser and its version (浏览器及其版本)
Chrome(92.0.4515.159)

### System and its version (系统及其版本)
Win10

### Reappearance link (重现链接)
https://codesandbox.io/s/msol6?file=/src/Demo.vue

### Reappearance steps (重现步骤)
把value变成ref(0)

### Expected results (期望的结果)
只显示0吧

### Actual results (实际的结果)
同时显示placeholder和0

**Comment by 07akioni** [comment]
这一定程度是个 bug，不过你也得注意不要绑 number 啊

**Comment by Volankey** [comment]
> 这一定程度是个 bug，不过你也得注意不要绑 number 啊

有空合一下
