### ISSUE TITLE
n-popover arrow position error

### ISSUE THREAD

**Issue by zmtlwzy** [TuSimple/naive-ui#916]
### TuSimple/naive-ui version (版本)
2.16.4

### Vue version (Vue 版本)
3.2.4

### Browser and its version (浏览器及其版本)
Microsoft Edge(92.0.902.73)

### System and its version (系统及其版本)
codesandbox

### Reappearance link (重现链接)
https://codesandbox.io/s/dreamy-shadow-gvd6z?file=/src/Demo.vue

### Reappearance steps (重现步骤)
n-popover default slot use n-ellipsis

### Expected results (期望的结果)
When a component is nested, the arrow position of the dialog box don not inherits the parent component.

### Actual results (实际的结果)
When a component is nested, the arrow position of the dialog box inherits the parent component.

**Comment by Volankey** [comment]
May be same as #872 .

**Comment by zmtlwzy** [comment]
![image](https://user-images.githubusercontent.com/49909526/130055462-144049b5-97b4-415d-901e-8fda76dcf56d.png)

**Comment by 07akioni** [comment]
@amadeus711 @Volankey 
I know the reason. For animation concerning, Popover inside popover is detached inside popover but not `body`. So the outer placement style has influenced the inner popover.
