### ISSUE TITLE
菜单是否可以内置提供手风琴模式

### ISSUE THREAD

**Issue by JHeLiu** [TuSimple/naive-ui#917]
### This function solves the problem (这个功能解决的问题)
管理后台这个功能非常重要，就是菜单过多的时候非常有用
### Expected API (期望的 API)
拥有参数配置 开启或者关闭手风琴模式即可

**Comment by pipinet** [comment]
https://github.com/TuSimple/naive-ui/issues/864

**Comment by 07akioni** [comment]
考虑加一个
