### ISSUE TITLE
Table表格是否提供类似于模板的语法功能

### ISSUE THREAD

**Issue by JHeLiu** [TuSimple/naive-ui#924]
### This function solves the problem (这个功能解决的问题)
更接近原生，比较易读，尤其是某些单元格需要放入复杂的 组件 或者其它元素。显然要简单轻松的多。

### Expected API (期望的 API)
https://2x.antdv.com/components/table-cn#components-table-demo-template

https://www.heyui.top/component/data/view/table#Table%20%E5%86%85%E5%AE%B9%E6%BB%9A%E5%8A%A8

类似于表格自己UI的 表格子组件

**Comment by amadeus711** [comment]
1. 在 js 层面这么做没问题，但是在 ts 层面这样不会存在任何类型检查，目前 vue 的 slot 没有类型。
2. 同时维护两种 api 成本比较高，我们暂时不打算提供类似的 api。naive-ui 提供的 slot 以简单渲染任务为主，例如 header。

**Comment by liu-xinhui** [comment]
对表格模板语法，需求特别高。从element ui转过来发现用render麻烦太多了，而且不易读，对开发者要求也高。
表格是管理系统第一大组件，这个不好用，等于全盘否定
