### ISSUE TITLE
暴露组件内部过渡样式

### ISSUE THREAD

**Issue by inreasons** [TuSimple/naive-ui#927]
### This function solves the problem (这个功能解决的问题)
在使用组件的时候，把系统切换的过渡效果改为和UI库内部过渡的样式统一的话，看上去不会有那么强的割裂感
### Expected API (期望的 API)
希望可以像element-ui、element-plus一样内置一些过滤样式类名方便调用。
[预览链接](https://element-plus.gitee.io/#/zh-CN/component/transition)

**Comment by 07akioni** [comment]
Use `n-element` or `useThemeVar` and use `--cubic-bezier-ease-in-out` or `cubicBezierEaseInOut`.

**Comment by 07akioni** [comment]
I'm considering exposing a collapse transition.

No plan for other transitions.
