### ISSUE TITLE
There is a bug in the n-input

### ISSUE THREAD

**Issue by amadeus711** [TuSimple/naive-ui#93]
### Environment Info

- Naive UI version: 2.11.7
- Vue version: 3.0.11
- Browser Info: Chrome(89.0.4389.128)
- System Info: Mac OS 11.2.3

### Reproduction link

```html
<n-input
      v-model:value="form.functionalExpectations"
      type="textarea"
      placeholder="请输入"
      :autosize="{ minRows: 2, maxRows: 5 }"
    ></n-input>
```

![image](https://user-images.githubusercontent.com/46394163/121784345-20e92900-cbe6-11eb-9135-6e59611ede75.png)

### Steps to reproduce

When I set the `minRows` and `maxRows` properties at the same time, entering a lot of text will stretch the textarea horizontally

**Comment by 07akioni** [comment]
![image](https://user-images.githubusercontent.com/18677354/121792955-6a109b80-cc2d-11eb-9465-f351acfa1b98.png)

It works in the demo page. A reproduction link is needed.

**Comment by amadeus711** [comment]
I'm sorry I didn't explain the root cause before. After checking again, I found that the above problems only occurred after using < n-form-item >
## Reproduction link:

https://github.com/amadeus711/issue-demo

The code in src/components/Demo.vue

## Reproduction steps:

1. clone
2. install
3. npm run dev

**Comment by amadeus711** [comment]
I'll fix it
