### ISSUE TITLE
Placeholder blank by default

### ISSUE THREAD

**Issue by Terminatt** [TuSimple/naive-ui#933]
### This function solves the problem (这个功能解决的问题)
From the UX point of view, the placeholder text is not needed. Users either don't read it or they can be misguided by it. Also "Please Input" is just verbose and not useful. If the placeholder is blank by default, it helps writing less code since developers don't have to pass everywhere empty string, or create a wrapper for the input and take care or all the events it has.
### Expected API (期望的 API)
If placeholder attribute is not provided, then the input field is rendered without it.

**Comment by 07akioni** [comment]
If I can build the library from scratch, I won't add placeholder for components. However we can't afford breaking change like that.

**Comment by 07akioni** [comment]
We may let config provider work like that, however it would take a lot of code (won't be done soon).
