### ISSUE TITLE
Data Form组件的width和ellipsis只有在最末列填写时才会奏效

### ISSUE THREAD

**Issue by YiFo0315** [TuSimple/naive-ui#934]
### TuSimple/naive-ui version (版本)
2.16.5

### Vue version (Vue 版本)
3.2.4

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
win

### Reappearance link (重现链接)
https://codesandbox.io/s/51uhf?file=/src/Demo.vue

### Reappearance steps (重现步骤)
如果在除了最后一列的任何一列加上这些property，并不会奏效。
但是如果在最后一列加上property，全部列都会正常工作。

### Expected results (期望的结果)
任何一列使用省略与宽度

### Actual results (实际的结果)
property不奏效

**Comment by doom-9** [comment]
![image](https://user-images.githubusercontent.com/65016011/130346637-5c5e3f3c-e16f-47c8-986c-21f8464a6da6.png)

**Comment by doom-9** [comment]
不是个bug吧，只是没设置table-layout

**Comment by 07akioni** [comment]
> ![image](https://user-images.githubusercontent.com/90209/134190119-6363e0e9-c6d2-45d9-97bd-7cf324379ec7.png)
> 
> 期望的是任意一列设置ellipsis，就hasEllipsis吧。

table-layout = auto 时候怎么布局是浏览器决定的，它自己有一个算法。我就是设定了 overflow hidden 也不够控制整个 table 不同列之间的宽度分配。

**Comment by thankwsx** [comment]
> > ![image](https://user-images.githubusercontent.com/90209/134190119-6363e0e9-c6d2-45d9-97bd-7cf324379ec7.png)
> > 期望的是任意一列设置ellipsis，就hasEllipsis吧。
> 
> table-layout = auto 时候怎么布局是浏览器决定的，它自己有一个算法。我就是设定了 overflow hidden 也不够控制整个 table 不同列之间的宽度分配。

大佬，我的意思是，从代码角度看hasEllpisis，初始值是false，然后遍历column，如果有设置ellipsis的列，则hasEllpisis就是true了。

不能因为后面还有其他的列没有设置ellipsis，就把这个hasEllpisis的值给改回false吧。

hasEllpisis的意思不是说“我有N个列，其中只要有需要缩写的列就为true”吗？
这里这么写，只要最后一列没有ellipsis的话，这个hasEllpisis就是false，那么前面无论多少个列有ellipsis的值也没有用了。

**Comment by 07akioni** [comment]
> 大佬，我的意思是，从代码角度看hasEllpisis，初始值是false，然后遍历column，如果有设置ellipsis的列，则hasEllpisis就是true了。
> 
> 不能因为后面还有其他的列没有设置ellipsis，就把这个hasEllpisis的值给改回false吧。

你说的是对的，这是个 bug

**Comment by 07akioni** [comment]
@Volankey 这个尽快修一下

**Comment by 07akioni** [comment]
fixed in https://github.com/TuSimple/naive-ui/pull/1246

**Comment by xcore-oss** [comment]
借楼，datable的column属性可以添加一个最小宽度吗？这样在大屏幕的时候可以实现铺满没有滚动条，在小屏幕宽度不够的时候自动出现滚动条 @07akioni

**Comment by 07akioni** [comment]
> 借楼，datable的column属性可以添加一个最小宽度吗？这样在大屏幕的时候可以实现铺满没有滚动条，在小屏幕宽度不够的时候自动出现滚动条 @07akioni

你先试试在 `<col />` 里面加上这种样式是不是真的能做到你说的那样。

**Comment by xcore-oss** [comment]
可以，但是我又发现另外一个不确定是不是bug的问题，我把datatable的样子改成了flex布局后滚动条不显示了，但是我用触摸屏可以滚动

**Comment by xcore-oss** [comment]
检查元素能找到滚动条的div的位置查看是存在的
![image](https://user-images.githubusercontent.com/44192818/136064452-a9045755-e27c-4cf3-8005-e5ce5f05bbc5.png)

**Comment by 07akioni** [comment]
这东西实际上还是挺复杂的，你期望中的表现未必能出现，必须要具体情况具体分析，我自己试过的组合就不下十几种
