### ISSUE TITLE
upload组件的submit在一些情况提示“Provisional headers are shown”

### ISSUE THREAD

**Issue by YiFo0315** [TuSimple/naive-ui#935]
### TuSimple/naive-ui version (版本)
2.16.5

### Vue version (Vue 版本)
3.2.4

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
win

### Reappearance link (重现链接)
https://codesandbox.io/s/zx8od

### Reappearance steps (重现步骤)
与官网文档的例子所发送的请求结果相同。
我试着向我的云服务api发送上传请求，method也一致，抓包结果是提示“Provisional headers are shown”。
![5EH47}H61(LL@9M0O3ORJ$Q](https://user-images.githubusercontent.com/80516655/130343639-c8231900-dc06-4420-adc1-c9bbb2e8d909.png)
但是我用postman及axios可以正常工作。
用mock可以正常发送请求。

### Expected results (期望的结果)
解决“Provisional headers are shown”

### Actual results (实际的结果)
在

**Comment by doom-9** [comment]
Mixed Content: The page at 'https://codesandbox.io/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.mocky.io/v2/5e4bafc63100007100d8b70f'. This request has been blocked; the content must be served over HTTPS.

**Comment by doom-9** [comment]
![image](https://user-images.githubusercontent.com/65016011/130344803-b1f66f4c-4abe-45c1-a4d2-6047ce1c7d46.png)
