### ISSUE TITLE
Docs(Dynamic Input) Inline puts do not align

### ISSUE THREAD

**Issue by xon52** [TuSimple/naive-ui#938]
### TuSimple/naive-ui version (版本)
2.16.5

### Vue version (Vue 版本)
3.2.4

### Browser and its version (浏览器及其版本)
Chrome(92.0.4515.159)

### System and its version (系统及其版本)
Windows 10

### Reappearance link (重现链接)
https://codesandbox.io/s/08khd

### Reappearance steps (重现步骤)
Just look at the alignment of the example in [https://www.naiveui.com/en-US/light/components/dynamic-input#form](https://www.naiveui.com/en-US/light/components/dynamic-input#form)

### Expected results (期望的结果)
Inputs and text will align.

### Actual results (实际的结果)
The inputs are in a grid format and appear to have extra grid/flexbox spaces which make them unaligned.

**Comment by 07akioni** [comment]
fixed
