### ISSUE TITLE
Data Table组件的ellipsis和渲染Tag配合的不是很好

### ISSUE THREAD

**Issue by YiFo0315** [TuSimple/naive-ui#943]
### This function solves the problem (这个功能解决的问题)
希望能自动省略多余的Tag
### Expected API (期望的 API)
[Tag1] [Tag2] [Tag3] ...
而现在是
![image](https://user-images.githubusercontent.com/80516655/130395090-1ce2792e-201d-4d66-8f45-0759bab9775a.png)

**Comment by Volankey** [comment]
`DataTable` 内的 ellipsis 通过 `n-ellipsis` 来做的，`n-ellipsis` 的期望不是扔一堆的tag过去，建议利用css来做这个需求

**Comment by 07akioni** [comment]
> `DataTable` 内的 ellipsis 通过 `n-ellipsis` 来做的，`n-ellipsis` 的期望不是扔一堆的tag过去，建议利用css来做这个需求

Ellpisis 期望是支持 inline 的元素的，浏览器本身支持，看看为啥吧

**Comment by Volankey** [comment]
> > `DataTable` 内的 ellipsis 通过 `n-ellipsis` 来做的，`n-ellipsis` 的期望不是扔一堆的tag过去，建议利用css来做这个需求
> 
> Ellpisis 期望是支持 inline 的元素的，浏览器本身支持，看看为啥吧

貌似都有点问题，在不同浏览器下表现不太一致

**Comment by 07akioni** [comment]
正常 ellpisis 对于 inline-block 也会生效的，问题出在哪里了呢？

**Comment by Volankey** [comment]
> 正常 ellpisis 对于 inline-block 也会生效的，问题出在哪里了呢？

子元素 `position:relative`

**Comment by 07akioni** [comment]
> > 正常 ellpisis 对于 inline-block 也会生效的，问题出在哪里了呢？
> 
> 子元素 `position:relative`

你的意思是在 native html 里面，子元素 relative 也会出问题吗？这有可能解决吗

**Comment by Volankey** [comment]
> > > 正常 ellpisis 对于 inline-block 也会生效的，问题出在哪里了呢？
> > 
> > 
> > 子元素 `position:relative`
> 
> 你的意思是在 native html 里面，子元素 relative 也会出问题吗？这有可能解决吗

可以看看这个示例，https://jsbin.com/loyehipaku/edit?html,output，我还没找到解决办法

**Comment by 07akioni** [comment]
> > > > 正常 ellpisis 对于 inline-block 也会生效的，问题出在哪里了呢？
> > > 
> > > 
> > > 子元素 `position:relative`
> > 
> > 
> > 你的意思是在 native html 里面，子元素 relative 也会出问题吗？这有可能解决吗
> 
> 可以看看这个示例，https://jsbin.com/loyehipaku/edit?html,output 我还没找到解决办法

看起来解决不了，不管了。

可以考虑给 ellpisis 增加一个 clip 模式，不 ellpisis

**Comment by 07akioni** [comment]
由于 ellpisis 的行为是浏览器控制的，这个问题暂时无法解决
