### ISSUE TITLE
n-radio-group在选项长度不一致时希望边框能重合

### ISSUE THREAD

**Issue by YiFo0315** [TuSimple/naive-ui#944]
### This function solves the problem (这个功能解决的问题)
n-radio-group在选项长度不一致时希望边框能重合
### Expected API (期望的 API)
n-radio-group在选项长度不一致的时候，交界处的边框会变粗
![image](https://user-images.githubusercontent.com/80516655/130397378-ca7d8c28-350a-44da-868b-7f5da6f95368.png)

**Comment by Volankey** [comment]
无法复现，请给出复现代码

**Comment by YiFo0315** [comment]
> 无法复现，请给出复现代码

官方文档上的例子就是，右面比左面粗
![image](https://user-images.githubusercontent.com/80516655/130431860-bf197870-744c-4ba3-9274-efd8562e6c79.png)

**Comment by Volankey** [comment]
列一下系统版本以及浏览器版本吧

**Comment by YiFo0315** [comment]
> 列一下系统版本以及浏览器版本吧

版本	Windows 10 家庭中文版
版本号	21H1
安装日期	‎2021/‎4/‎10
操作系统内部版本	19043.1165
体验	Windows Feature Experience Pack 120.2212.3530.0

Google Chrome 已是最新版本
版本 92.0.4515.159（正式版本） （64 位）

**Comment by Volankey** [comment]
> > 列一下系统版本以及浏览器版本吧
> 
> 版本 Windows 10 家庭中文版
> 版本号 21H1
> 安装日期 ‎2021/‎4/‎10
> 操作系统内部版本 19043.1165
> 体验 Windows Feature Experience Pack 120.2212.3530.0
> 
> Google Chrome 已是最新版本
> 版本 92.0.4515.159（正式版本） （64 位）

这个我得找个windows看一下，现在手前还没有

**Comment by huozhenzhen** [comment]
我WIN10 Chrome92   怎么没有复现，你说奇怪不。。。  @YiFo0315

**Comment by John60676** [comment]
建议检查一下浏览器缩放

![image](https://user-images.githubusercontent.com/21698973/132084216-5a96947b-4952-4235-bab8-643c505a11b8.png)

**Comment by 07akioni** [comment]
如果缩放渲染有问题我一般把这个当成 chrome 的问题，就先不想办法 hack 了，说不定猴年马月哪个版本就好了
