### ISSUE TITLE
Tag 标签在设置 type 属性后边框消失

### ISSUE THREAD

**Issue by inreasons** [TuSimple/naive-ui#953]
### TuSimple/naive-ui version (版本)
2.16.5

### Vue version (Vue 版本)
3.2.4

### Browser and its version (浏览器及其版本)
chrome(92.0.4515.159)

### System and its version (系统及其版本)
Windows(10.1909)

### Node version (Node 版本)
v14.17.5

### Reappearance link (重现链接)
https://codesandbox.io/s/focused-kirch-vnk5o?file=/src/App.vue

### Reappearance steps (重现步骤)
创建 `Vue3` 项目，引入 `naive-ui`，使用 `Tag` 组件，设置 `type` 属性.

### Expected results (期望的结果)
设置 type 属性后边框依然存在.

### Actual results (实际的结果)
设置属性后边框消失了.

**Comment by Talljack** [comment]
type类型使用不对
![image](https://user-images.githubusercontent.com/34439652/130597708-4326c563-95f2-4d5e-aa21-24ed8a5db604.png)

**Comment by Volankey** [comment]
type | 'default' \| 'primary' \| 'info' \| 'success' \| 'warning' \| 'error' | 'default' | 类型
-- | -- | -- | --
