### ISSUE TITLE
Tree defaultExpandedKeys can't apply to nested node, and defaultSelectedKeys is never effect.

### ISSUE THREAD

**Issue by coader** [TuSimple/naive-ui#958]
### TuSimple/naive-ui version (版本)
2.16.5

### Vue version (Vue 版本)
3.2.4

### Browser and its version (浏览器及其版本)
Chrome(91)

### System and its version (系统及其版本)
Windows10

### Reappearance link (重现链接)
https://codesandbox.io/s/naughty-lumiere-tjkog?file=/src/Demo.vue

### Reappearance steps (重现步骤)
      defaultExpandedKeys: ['4030' ],
      defaultSelectedKeys:ref(['41'])

### Expected results (期望的结果)
set default expand nodes and selected node

### Actual results (实际的结果)
not effect

**Comment by Talljack** [comment]
If you need to set defaultSelectedKeys, then you need to set checkable and cascade properties, and when your defaultExpandedKeys is set to ['4030'], the inner layer is already expanded, if you set it to ['40'] then you can obviously See the effect.
![image](https://user-images.githubusercontent.com/34439652/130713759-b5c7e94d-d0bd-45e3-8236-c741f6ee7d37.png)
