### ISSUE TITLE
How can i reset form,i can't found method clearValidationEffect method in form ref

### ISSUE THREAD

**Issue by nabaonan** [TuSimple/naive-ui#96]
### Environment Info

- Naive UI version: 2.11.7
- Vue version: 3.1.1
- Browser Info: Chome 91.0.4472.77
- System Info: macos 11.4

### Reproduction link

https://codesandbox.io/s/naive-ui-test-vi95j?file=/src/App.vue:1326-1347
### Steps to reproduce
click reset botton 
### What is expected?
the form can be reset
### What is actually happening?
The form does not have a method called clearValidationEffect ,and  with an error,but i found a method called restoreValidation,it is useful for clear validation ,but not for form's value

**Comment by 07akioni** [comment]
The docs have mistakes, I've fixed it.

About resetting, naive-ui doesn't provide a method for reset a form. Form just collect values and do validation to the correspoinding form items.

If you want to restore a value. Just implemenet it. For example:

```js
{
  setup () {
    const formInitValue = { key: 'value' }
    const formValueRef = ref({ ...formInitValue })
    const resetFormValue = () => { formValueRef.value = formInitValue }
    // ...
  }
}
```

**Comment by jahnli** [comment]
@07akioni  Writing this seems to lead to object double reference problems,

**Comment by jahnli** [comment]
@07akioni   form.value = { ...formInitValue }    它是可以的

**Comment by 07akioni** [comment]
> @07akioni form.value = { ...formInitValue } 它是可以的

是的，我们这个表格由于实现的比较简陋，内部根本不去收集值，完全是受控的，想恢复就是记录一下初始值的事

**Comment by wangfpp** [comment]
应该提供这个方法吧  还是经常使用的

**Comment by 07akioni** [comment]
> 应该提供这个方法吧 还是经常使用的

提供不了，数据是用户自己控制的

**Comment by 07akioni** [comment]
或许可以用 v-model:model 来做一个简单的清除工作，不过 emmm 确实感觉意义不大，省不了多少代码
