### ISSUE TITLE
n-tabs show-divider prop is not implemented

### ISSUE THREAD

**Issue by kungege** [TuSimple/naive-ui#962]
### TuSimple/naive-ui version (版本)
2.16.5

### Vue version (Vue 版本)
3.2.6

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
windows

### Reappearance link (重现链接)
https://codesandbox.io/s/elated-morse-1r2fh?file=/src/Demo.vue:85-97

**Comment by 07akioni** [comment]
Yes, it's useless. I have removed it.

Type `line` and `bar` is enough to distinguish the divider.
