### ISSUE TITLE
n-table中td使用rowspan后边框出现缺失和重叠

### ISSUE THREAD

**Issue by xxx1012** [TuSimple/naive-ui#976]
### This function solves the problem (这个功能解决的问题)
n-table中td使用rowspan后边框出现缺失和重叠
### Expected API (期望的 API)
第二列的右边框部分缺失，后面几列底部边框出现重叠，复现代码：
`<n-table :single-line="false">
            <thead>
              <tr>
                <th>Abandon</th>
                <th>Abormal</th>
                <th>Abolish</th>
                <th>...</th>
                <th>万事开头难</th>
              </tr>
            </thead>  
            <tbody>  
              <tr>
                <td>放弃</td>
                <td>反常的</td>
                <td rowspan="2">彻底废除</td>
                <td rowspan="2">...</td>
                <td rowspan="2">干！我刚才背的是啥</td>
              </tr>
              <tr>
                <td>放弃</td>
                <td>反常的</td>
              </tr>
            </tbody>
          </n-table>`

**Comment by Talljack** [comment]
> @Talljack

感觉纯用css比较难处理

**Comment by 07akioni** [comment]
It's impossible to make `n-table` work with span automatically.

The only possiblity is that we can provide some prop to help you control the border status of table cell, like `border="left botom"` or something like that.

**Comment by 07akioni** [comment]
Currently you should use n-data-table.

**Comment by 07akioni** [comment]
After some time of thinking I think the overhead is too large to provide something like that. If you must do it, please use `n-data-table`.
