### ISSUE TITLE
Distinct title for each documentation page

### ISSUE THREAD

**Issue by ouuan** [TuSimple/naive-ui#984]
### This function solves the problem (这个功能解决的问题)
Now all pages of the documentation have the same title "Naive UI: A Vue 3 Component Library". When multiple pages are opened, it's hard to find the needed one.
### Expected API (期望的 API)
I hope each page can have a distinct title.

For example, the title of https://www.naiveui.com/en-US/dark/components/avatar could be "Avatar - Components - Naive UI: A Vue 3 Component Library".

**Comment by ouuan** [comment]
能不能直接使用页面上 h1 元素的内容？

**Comment by 07akioni** [comment]
> 能不能直接使用页面上 h1 元素的内容？

也行，可以暂时先这么做
